:PROPERTIES:
:ID:       07c481ec-9b2e-7777-bbd2-a447199a7bf4
:END:
#+title: Acer5600 Cooltouch TS58xxA TC56xxA

#+begin_example sh
lspci --topo
lspci --t
lspci -t
lspci -t -v
lsusb
lsusb -v -h
lsusb -v -s 003:006
libinput --help
libinput list-devices
sudo libinput list-devices
libinput --help
libinput debug-events
sudo libinput debug-events
sudo libinput list-devices
i2cdetect
i2cdetect -l
sudo ddcutil capabilities
sudo ddcutil detect
sudo ddcutil capabilities --help
sudo ddcutil capabilities --usbenv
sudo ddcutil --usbenv
sudo ddcutil capabilities usbenv
sudo ddcutil usbenv
history | tail -n40 > /data/xdg/Documents/acer5600-cooltouch-TS58xxA-TC56xxA.org
#+end_example

ddcutil output

#+begin_quote
VCP (aka MCCS) version for display is undetected or less than 2.0. Interpretation may not be accurate.
Model: RTK
MCCS version: 2.1
Commands:
   Op Code: 01 (VCP Request)
   Op Code: 03 (VCP Set)
VCP Features:
   Feature: 04 (Restore factory defaults)
   Feature: 10 (Brightness)
   Feature: 7E (Trapezoid)
#+end_quote

ddcutil output

#+begin_quote
The following tests probe for monitors that use USB for VCP communication...

Checking for USB connected monitors...

   Using lsusb to summarize USB devices...
      Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
      Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
      Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
      Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
      Bus 003 Device 005: ID 0bda:0138 Realtek Semiconductor Corp. RTS5138 Card Reader Controller
      Bus 003 Device 006: ID 2149:2306 Advanced Silicon S.A. TS58xxA/TC56xxA [CoolTouch]
      Bus 003 Device 009: ID 046d:c31c Logitech, Inc. Keyboard K120
      Bus 003 Device 010: ID 413c:301a Dell Computer Corp. Dell MS116 Optical Mouse
      Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
      Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
      Bus 004 Device 003: ID 04ca:3006 Lite-On Technology Corp. [unknown]
      Bus 004 Device 004: ID 0461:4e11 Primax Electronics, Ltd [unknown]
      Bus 004 Device 005: ID 04f2:b350 Chicony Electronics Co., Ltd [unknown]

   USB device topology...
      /:  Bus 001.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/4p, 480M
      /:  Bus 002.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/4p, 5000M
      /:  Bus 003.Port 001: Dev 001, Class=root_hub, Driver=ehci-pci/2p, 480M
          |__ Port 001: Dev 002, If 0, Class=Hub, Driver=hub/8p, 480M
              |__ Port 001: Dev 010, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
              |__ Port 002: Dev 009, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
              |__ Port 002: Dev 009, If 1, Class=Human Interface Device, Driver=usbhid, 1.5M
              |__ Port 007: Dev 005, If 0, Class=Mass Storage, Driver=ums-realtek, 480M
              |__ Port 008: Dev 006, If 0, Class=Human Interface Device, Driver=usbhid, 12M
              |__ Port 008: Dev 006, If 1, Class=Human Interface Device, Driver=usbhid, 12M
      /:  Bus 004.Port 001: Dev 001, Class=root_hub, Driver=ehci-pci/2p, 480M
          |__ Port 001: Dev 002, If 0, Class=Hub, Driver=hub/6p, 480M
              |__ Port 003: Dev 003, If 0, Class=Wireless, Driver=btusb, 12M
              |__ Port 003: Dev 003, If 1, Class=Wireless, Driver=btusb, 12M
              |__ Port 004: Dev 004, If 0, Class=Human Interface Device, Driver=usbhid, 12M
              |__ Port 004: Dev 004, If 1, Class=Human Interface Device, Driver=usbhid, 12M
              |__ Port 005: Dev 005, If 0, Class=Video, Driver=uvcvideo, 480M
              |__ Port 005: Dev 005, If 1, Class=Video, Driver=uvcvideo, 480M

   Listing /dev/usb...
      total 0
      crw-------. 1 root root 180, 96 Dec 24 15:27 hiddev0
      crw-rw----+ 1 root root 180, 97 Dec 24 15:27 hiddev1

   Listing /dev/hiddev*...
      ls: cannot access '/dev/hiddev*': No such file or directory

   Listing /dev/bus/usb...
      total 0
      drwxr-xr-x. 2 root root  60 Dec 24 10:25 001
      drwxr-xr-x. 2 root root  60 Dec 24 10:25 002
      drwxr-xr-x. 2 root root 160 Jan 21 11:46 003
      drwxr-xr-x. 2 root root 140 Dec 24 10:25 004

   Listing /dev/hidraw*...
      crw-------. 1 root root 241, 0 Jan 21 11:46 /dev/hidraw0
      crw-------. 1 root root 241, 1 Dec 24 15:27 /dev/hidraw1
      crw-------. 1 root root 241, 2 Jan 21 05:08 /dev/hidraw2
      crw-------. 1 root root 241, 3 Jan 21 05:08 /dev/hidraw3
      crw-------. 1 root root 241, 4 Dec 24 15:27 /dev/hidraw4
      crw-------. 1 root root 241, 5 Dec 24 15:27 /dev/hidraw5
      crw-------. 1 root root 241, 6 Dec 24 15:27 /dev/hidraw6

   Searching /sys for hiddev* entries...
      /sys/class/usbmisc/hiddev0
      /sys/class/usbmisc/hiddev1
      /sys/devices/pci0000:00/0000:00:1a.0/usb4/4-1/4-1.4/4-1.4:1.1/usbmisc/hiddev0
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.8/3-1.8:1.1/usbmisc/hiddev1

   Searching /sys for hidraw* entries...
      /sys/class/hidraw
      /sys/class/hidraw/hidraw6
      /sys/class/hidraw/hidraw4
      /sys/class/hidraw/hidraw2
      /sys/class/hidraw/hidraw0
      /sys/class/hidraw/hidraw5
      /sys/class/hidraw/hidraw3
      /sys/class/hidraw/hidraw1
      /sys/devices/pci0000:00/0000:00:1a.0/usb4/4-1/4-1.4/4-1.4:1.1/0003:0461:4E11.0004/hidraw
      /sys/devices/pci0000:00/0000:00:1a.0/usb4/4-1/4-1.4/4-1.4:1.1/0003:0461:4E11.0004/hidraw/hidraw4
      /sys/devices/pci0000:00/0000:00:1a.0/usb4/4-1/4-1.4/4-1.4:1.0/0003:0461:4E11.0002/hidraw
      /sys/devices/pci0000:00/0000:00:1a.0/usb4/4-1/4-1.4/4-1.4:1.0/0003:0461:4E11.0002/hidraw/hidraw1
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.8/3-1.8:1.0/0003:2149:2306.0006/hidraw
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.8/3-1.8:1.0/0003:2149:2306.0006/hidraw/hidraw5
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.8/3-1.8:1.1/0003:2149:2306.0007/hidraw
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.8/3-1.8:1.1/0003:2149:2306.0007/hidraw/hidraw6
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.2/3-1.2:1.1/0003:046D:C31C.000C/hidraw
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.2/3-1.2:1.1/0003:046D:C31C.000C/hidraw/hidraw3
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.2/3-1.2:1.0/0003:046D:C31C.000B/hidraw
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.2/3-1.2:1.0/0003:046D:C31C.000B/hidraw/hidraw2
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.1/3-1.1:1.0/0003:413C:301A.000D/hidraw
      /sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1.1/3-1.1:1.0/0003:413C:301A.000D/hidraw/hidraw0


Checking for USB HID devices using hiddev...
   hiddev device names found in file system:
      /dev/usb/hiddev0
      /dev/usb/hiddev1
   hiddev device names found in udev:
      /dev/usb/hiddev0
      /dev/usb/hiddev1
   Examining hiddev devices reported by udev...
   Found 2 USB HID devices.

   Device /dev/usb/hiddev0 is not a HID device or is a mouse or keyboard.  Skipping

   Device /dev/usb/hiddev1, devnum.busnum: 3.6, vid:pid: 2149:2306 - Advanced Silicon S.A CoolTouch(TM) System
      Not a USB HID monitor

Checking for USB HID Report Descriptors in /sys/kernel/debug/hid...

Checking for USB connected monitors complete
#+end_quote
