:PROPERTIES:
:ID:       48d763a8-5579-4585-a9a2-e7cbb11701fe
:END:
#+TITLE:     Homelab
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes


* Planning

** Layers
+ Hardware
+ VM
+ Containers
+ Service
+ Network
+ Storage

** Dimensions
+ Agent Provisioning
  - qemu guest account (automated startup/shutdown/etc)
  - or Jumpcloud Agent or [[https://help.okta.com/en/prod/Content/Topics/Provisioning/opp/OPP-architecture.htm][Okta Agent]]
+ Authentication/Authorization
+ Certificates & Key Management
+ Passwords
+ DNS (masks complexity of IP/VLAN)
+ IP Addressing (& VLAN)
+ Firewall & Route/Switch
+ Documentation
+ Playbook (ansible/whatever)
+ Service Configuration
  - service users
+ Directory Management
  - LDAP/etc
+ Task Management (Cron, etc)
+ VM Host/Cluster
+ VM Image Management
+ Storage Provisioning (& Backups)
+ Logshipping (& indexing/searching)

* Devops

** Ansible



* Services

** DNS

** NTP

** AWX


** SSH

** Cuirass

Automated Builds

** Podman

*** Syncthing

*** Sourcegraph

*** Org Roam UI

* Equipment Post

Shoot me a message if you want to connect or if you have networking or computing
gear that you're willing to sell.

I'm generally looking for networking, storage and compute stuff. I am ready to
buy some stuff now, but I don't have a ton of money. I may have something for
trade or sale as well.

I badly need storage for backups, so that's what I'm looking for first. Other
than that, adding things like a better router/switch opens up options,
especially when it supports 10ge.

There may be things that could help me out that I'm not aware of. If so, please
reach out! I'm generally pessimistic about performance requirements.

** Storage

+ HDD for networked storage
+ SSDs that are at least 1 TB
+ PCIe card for NVMe expansion

** Networking

Maybe a 10gb switch, though I'm just not sure for now, since I don't have a
machine for a NAS.

*** WiFi Routers

+ I'm looking for models than can run OpenWRT, not DDWRT.
+ Send me the model number if you're looking to get rid of one
+ I would pay probably $20-30 for models from the last 5 years. I am picky, but
  i'm willing to go up if the model is good. Otherwise it's not worth the time.

*** 10 gb/s Ethernet

I really need to check compatibility for cables/modules before I commit to
anything

+ PCIe card for SFP modules (low priority)

SFP network modules compatible with Cisco 2560

+ 10GE SR SFP+ (or 10GE LR SFP+ or 10GE ER SFP+)
+ 10GE LRM SFP+ (or 10GE USR SFP+ or 10GE LRM SFP+)

SFP network modules compatible with Dell rack server

+ 10GBSFP+

** Compute

+ Older Dell or HP rack servers.

*** ARM

ARM is great. Low power.

**** Rasberry Pi

Reasonably priced raspberry pi's.

+ The first-gen is typically too old (i have 3) and the 4th/5th gen are too expensive.

*** NUCs

+ It's a bit tough to find NUC's with multiple network ports, so let me know!
+ [[https://protectli.com/][Protectli]] is a vender that offers these, but there are others.
+ I'm looking for stuff, even if it's not built for networking. If the ethernet
  chipset offers SR-IOV, then it doesn't matter (I could mix and match MACVLAN,
  BRIDGE and VLAN or passthrough to VM; without this, I'm stuck with the host's
  networking)

**** ARM NUC

I'm willing to pay more for these, but I'll need the model number.
+ I need to check the chipset and networking capabilities, particularly SR-IOV
  which is probably absent if it's a consumer model. I may still be interested
  though.

**** Intel NUC

+ Anything better than a Celeron processor with a decent number of CPU's.
+ That would make it expensive when purchased new because Celeron is trash
  and the plebs don't care; no offense.


** Graphics Cards

+ Nvidia 1080 or 2080. Or higher, since the last two numbers matter way more;
  anything less than XX80 begins to lose performance quickly the die size is too
  small; the number of transisters is cut by up to 75%. At best, it's a higher
  OpenCL version; at worst, it's a complete ripoff.
+ Any workstation GPU, provided it has a decent OpenCL level.

** Misc

+ Rockwool and other soundproofing/insulating materials
+ Fans/etc for ventilation (at odds with the above which introduces ventilation
  requirements)
+ Steel for rackmounting (like literally even if it's just steel; I don't mind
  threading a few holes to save $100+)

The need for soundproofing/ventilation is lower if I move my rack, but then it's
networking only supports the short-range optical connections ... which means I
need a new switch. Things like this just perpetually keep me chasing my tail,
but I'm literally trying to get experience so I walk onto a job as someone who
is /_not_ vulnerable to mischaracterization./

* Why so specific?

There are a lot of problems I'm running into on my network that strongly limit
my options. I would like Kubernetes (or k3s), since Helm is basically an
app-store for networked apps like Gitlab/Artifactory/etc, but K8S has high
performance requirements.

+ My computers require too much power, but only have 4 cores, so running 3+ VM's
  on them to support Kubernetes Etcd makes running multiple Kubernetes clusters
  a bit precarious.
+ Most of my computers also lack SR-IOV (whoever is in charge of speccing out
  motherboards these days needs to face the wall). This opens up quite a few and
  security issues.

I need multiple kubernetes clusters, though usually k3s works:

+ K3S for Longhorn (flexible backups that, I think, can support multiple clusters)
+ K3S for Hashicorp Vault (completely separated, which is hard when you don't
  have SR-IOV)
+ K3S/K8S for running apps, machine learning tasks, etc.

I need more storage, so I won't need to move databases between VM disks or
kubernetes pods.
