@startuml
left to right direction
hide circle
/'
 ' skinparam linetype ortho
 '/

entity "**api_meeting_meeting**" {
  + ""id"": //serial [PK]//
  --
  *""date"": //timestamp with time zone //
  *""type"": //character varying(10) //
  ""chair"": //character varying(20) //
}

entity "**api_meeting_meeting_attendees**" {
  + ""id"": //serial [PK]//
  --
  *""meeting_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
}

entity "**api_meeting_proxyvote**" {
  + ""id"": //serial [PK]//
  --
  ""user_city"": //character varying(30) //
  ""proxy_city"": //character varying(30) //
  *""created_date"": //timestamp with time zone //
  *""meeting_id"": //integer [FK]//
  *""proxy_user_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
}

entity "**api_admin_tools_membertier**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(150) //
  *""description"": //character varying(250) //
  *""visible"": //boolean //
  *""featured"": //boolean //
}

entity "**api_admin_tools_paymentplan**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(50) //
  *""visible"": //boolean //
  *""cost"": //integer //
  *""interval"": //character varying(10) //
  *""member_tier_id"": //integer [FK]//
  *""interval_count"": //integer //
  *""currency"": //character varying(3) //
}

entity "**auth_group**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(150) //
}

entity "**auth_group_permissions**" {
  + ""id"": //serial [PK]//
  --
  *""group_id"": //integer [FK]//
  *""permission_id"": //integer [FK]//
}

entity "**auth_permission**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(255) //
  *""content_type_id"": //integer [FK]//
  *""codename"": //character varying(100) //
}

entity "**profile_profile**" {
  + ""id"": //serial [PK]//
  --
  ""digital_id_token"": //uuid //
  ""digital_id_token_expire"": //timestamp with time zone //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
  *""screen_name"": //character varying(30) //
  *""first_name"": //character varying(30) //
  *""last_name"": //character varying(30) //
  ""rfid"": //character varying(20) //
  *""memberbucks_balance"": //double precision //
  *""last_memberbucks_purchase"": //timestamp with time zone //
  *""must_update_profile"": //boolean //
  ""last_seen"": //timestamp with time zone //
  ""last_induction"": //timestamp with time zone //
  *""user_id"": //integer [FK]//
  ""membership_plan_id"": //integer [FK]//
  *""subscription_status"": //character varying(10) //
  *""exclude_from_email_export"": //boolean //
  ""subscription_first_created"": //timestamp with time zone //
}

entity "**profile_user**" {
  + ""id"": //serial [PK]//
  --
  *""password"": //character varying(128) //
  ""last_login"": //timestamp with time zone //
  *""is_superuser"": //boolean //
  *""email"": //character varying(255) //
  *""email_verified"": //boolean //
  ""password_reset_key"": //uuid //
  ""password_reset_expire"": //timestamp with time zone //
  *""staff"": //boolean //
  *""admin"": //boolean //
}

entity "**profile_user_groups**" {
  + ""id"": //serial [PK]//
  --
  *""user_id"": //integer [FK]//
  *""group_id"": //integer [FK]//
}

entity "**profile_user_user_permissions**" {
  + ""id"": //serial [PK]//
  --
  *""user_id"": //integer [FK]//
  *""permission_id"": //integer [FK]//
}

entity "**profile_usereventlog**" {
  + ""log_ptr_id"": //integer [PK][FK]//
  --
  *""user_id"": //integer [FK]//
}

"**api_admin_tools_paymentplan**"   }--  "**api_admin_tools_membertier**"
"**profile_profile**"   }--  "**api_admin_tools_paymentplan**"
"**api_meeting_meeting_attendees**"   }--  "**api_meeting_meeting**"
"**api_meeting_meeting_attendees**"   }--  "**profile_user**"
"**api_meeting_proxyvote**"   }--  "**api_meeting_meeting**"
"**api_meeting_proxyvote**"   }--  "**profile_user**"
"**auth_group_permissions**"   }--  "**auth_group**"
"**auth_group_permissions**"   }--  "**auth_permission**"
"**profile_profile**"   }--  "**profile_user**"
"**profile_usereventlog**"   }--  "**profile_user**"
"**profile_user_groups**"   }--  "**auth_group**"
"**profile_user_groups**"   }--  "**profile_user**"
"**profile_user_user_permissions**"   }--  "**auth_permission**"
"**profile_user_user_permissions**"   }--  "**profile_user**"

@enduml
