@startuml
left to right direction
hide circle
/'
 ' skinparam linetype ortho
 '/

entity "**api_general_kiosk**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(30) //
  *""kiosk_id"": //character varying(70) //
  ""ip_address"": //inet //
  ""last_seen"": //timestamp with time zone //
  *""play_theme"": //boolean //
  *""authorised"": //boolean //
}

entity "**api_metrics_metric**" {
  + ""id"": //serial [PK]//
  --
  *""creation_date"": //timestamp with time zone //
  *""data"": //jsonb //
  *""name"": //character varying(250) //
}

entity "**api_spacedirectory_spaceapi**" {
  + ""id"": //serial [PK]//
  --
  *""space_is_open"": //boolean //
  ""space_message"": //character varying(255) //
  *""status_last_change"": //timestamp with time zone //
}

entity "**api_spacedirectory_spaceapisensor**" {
  + ""id"": //serial [PK]//
  --
  *""sensor_type"": //character varying(100) //
  *""name"": //character varying(255) //
  ""value"": //numeric(10,3) //
  ""unit"": //character varying(50) //
  ""location"": //character varying(255) //
  ""description"": //character varying(255) //
}

entity "**api_spacedirectory_spaceapisensorproperties**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(100) //
  *""value"": //numeric(10,3) //
  *""unit"": //character varying(100) //
  *""sensor_id_id"": //integer [FK]//
}

entity "**constance_config**" {
  + ""id"": //serial [PK]//
  --
  *""key"": //character varying(255) //
  ""value"": //text //
}

entity "**rest_framework_api_key_apikey**" {
  + ""id"": //character varying(150) [PK]//
  --
  *""created"": //timestamp with time zone //
  *""name"": //character varying(50) //
  *""revoked"": //boolean //
  ""expiry_date"": //timestamp with time zone //
  *""hashed_key"": //character varying(150) //
  *""prefix"": //character varying(8) //
}

"**api_spacedirectory_spaceapisensorproperties**"   }--  "**api_spacedirectory_spaceapisensor**"
@enduml
