@startuml
left to right direction
hide circle
skinparam linetype ortho

entity "**access_accesscontrolleddevice**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(30) //
  *""description"": //character varying(500) //
  ""ip_address"": //inet //
  ""last_seen"": //timestamp with time zone //
  *""all_members"": //boolean //
  *""locked_out"": //boolean //
  *""play_theme"": //boolean //
  *""exempt_signin"": //boolean //
  *""hidden"": //boolean //
  ""serial_number"": //character varying(50) //
  *""report_online_status"": //boolean //
  *""post_to_discord"": //boolean //
  *""authorised"": //boolean //
  *""post_to_slack"": //boolean //
}

entity "**access_accesscontrolleddeviceapikey**" {
  + ""id"": //character varying(150) [PK]//
  --
  *""prefix"": //character varying(8) //
  *""hashed_key"": //character varying(150) //
  *""created"": //timestamp with time zone //
  *""name"": //character varying(50) //
  *""revoked"": //boolean //
  ""expiry_date"": //timestamp with time zone //
}

entity "**access_doorlog**" {
  + ""id"": //serial [PK]//
  --
  *""date"": //timestamp with time zone //
  *""user_id"": //integer [FK]//
  *""door_id"": //integer [FK]//
  *""success"": //boolean //
}

entity "**access_doors**" {
  + ""accesscontrolleddevice_ptr_id"": //integer [PK][FK]//
  --
}

entity "**access_externalaccesscontrolapikey**" {
  + ""id"": //character varying(150) [PK]//
  --
  *""prefix"": //character varying(8) //
  *""hashed_key"": //character varying(150) //
  *""created"": //timestamp with time zone //
  *""name"": //character varying(50) //
  *""revoked"": //boolean //
  ""expiry_date"": //timestamp with time zone //
}

entity "**access_interlock**" {
  + ""accesscontrolleddevice_ptr_id"": //integer [PK][FK]//
  --
  *""cost_per_hour"": //integer //
  *""cost_per_kwh"": //integer //
  *""cost_per_session"": //integer //
}

entity "**access_interlocklog**" {
  + ""id"": //uuid [PK]//
  --
  *""date_updated"": //timestamp with time zone //
  *""user_started_id"": //integer [FK]//
  *""interlock_id"": //integer [FK]//
  ""date_ended"": //timestamp with time zone //
  *""date_started"": //timestamp with time zone //
  ""reason"": //character varying(500) //
  *""success"": //boolean //
  ""total_cost"": //double precision //
  ""total_kwh"": //double precision //
  *""total_time"": //interval //
  ""user_ended_id"": //integer [FK]//
}

entity "**access_memberbucksdevice**" {
  + ""accesscontrolleddevice_ptr_id"": //integer [PK][FK]//
  --
}

entity "**api_admin_tools_membertier**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(150) //
  *""description"": //character varying(250) //
  *""visible"": //boolean //
  *""featured"": //boolean //
}

entity "**api_admin_tools_paymentplan**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(50) //
  *""visible"": //boolean //
  *""cost"": //integer //
  *""interval"": //character varying(10) //
  *""member_tier_id"": //integer [FK]//
  *""interval_count"": //integer //
  *""currency"": //character varying(3) //
}

entity "**api_general_emailverificationtoken**" {
  + ""id"": //serial [PK]//
  --
  *""creation_date"": //timestamp with time zone //
  *""verification_token"": //uuid //
  *""user_id"": //integer [FK]//
}

entity "**api_general_kiosk**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(30) //
  *""kiosk_id"": //character varying(70) //
  ""ip_address"": //inet //
  ""last_seen"": //timestamp with time zone //
  *""play_theme"": //boolean //
  *""authorised"": //boolean //
}

entity "**api_general_sitesession**" {
  + ""id"": //serial [PK]//
  --
  *""signin_date"": //timestamp with time zone //
  ""signout_date"": //timestamp with time zone //
  *""guests"": //text //
  *""user_id"": //integer [FK]//
}

entity "**api_meeting_meeting**" {
  + ""id"": //serial [PK]//
  --
  *""date"": //timestamp with time zone //
  *""type"": //character varying(10) //
  ""chair"": //character varying(20) //
}

entity "**api_meeting_meeting_attendees**" {
  + ""id"": //serial [PK]//
  --
  *""meeting_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
}

entity "**api_meeting_proxyvote**" {
  + ""id"": //serial [PK]//
  --
  ""user_city"": //character varying(30) //
  ""proxy_city"": //character varying(30) //
  *""created_date"": //timestamp with time zone //
  *""meeting_id"": //integer [FK]//
  *""proxy_user_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
}

entity "**api_metrics_metric**" {
  + ""id"": //serial [PK]//
  --
  *""creation_date"": //timestamp with time zone //
  *""data"": //jsonb //
  *""name"": //character varying(250) //
}

entity "**api_spacedirectory_spaceapi**" {
  + ""id"": //serial [PK]//
  --
  *""space_is_open"": //boolean //
  ""space_message"": //character varying(255) //
  *""status_last_change"": //timestamp with time zone //
}

entity "**api_spacedirectory_spaceapisensor**" {
  + ""id"": //serial [PK]//
  --
  *""sensor_type"": //character varying(100) //
  *""name"": //character varying(255) //
  ""value"": //numeric(10,3) //
  ""unit"": //character varying(50) //
  ""location"": //character varying(255) //
  ""description"": //character varying(255) //
}

entity "**api_spacedirectory_spaceapisensorproperties**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(100) //
  *""value"": //numeric(10,3) //
  *""unit"": //character varying(100) //
  *""sensor_id_id"": //integer [FK]//
}

entity "**auth_group**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(150) //
}

entity "**auth_group_permissions**" {
  + ""id"": //serial [PK]//
  --
  *""group_id"": //integer [FK]//
  *""permission_id"": //integer [FK]//
}

entity "**auth_permission**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(255) //
  *""content_type_id"": //integer [FK]//
  *""codename"": //character varying(100) //
}

entity "**constance_config**" {
  + ""id"": //serial [PK]//
  --
  *""key"": //character varying(255) //
  ""value"": //text //
}

entity "**django_admin_log**" {
  + ""id"": //serial [PK]//
  --
  *""action_time"": //timestamp with time zone //
  ""object_id"": //text //
  *""object_repr"": //character varying(200) //
  *""action_flag"": //smallint //
  *""change_message"": //text //
  ""content_type_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
}

entity "**django_celery_beat_clockedschedule**" {
  + ""id"": //serial [PK]//
  --
  *""clocked_time"": //timestamp with time zone //
}

entity "**django_celery_beat_crontabschedule**" {
  + ""id"": //serial [PK]//
  --
  *""minute"": //character varying(240) //
  *""hour"": //character varying(96) //
  *""day_of_week"": //character varying(64) //
  *""day_of_month"": //character varying(124) //
  *""month_of_year"": //character varying(64) //
  *""timezone"": //character varying(63) //
}

entity "**django_celery_beat_intervalschedule**" {
  + ""id"": //serial [PK]//
  --
  *""every"": //integer //
  *""period"": //character varying(24) //
}

entity "**django_celery_beat_periodictask**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(200) //
  *""task"": //character varying(200) //
  *""args"": //text //
  *""kwargs"": //text //
  ""queue"": //character varying(200) //
  ""exchange"": //character varying(200) //
  ""routing_key"": //character varying(200) //
  ""expires"": //timestamp with time zone //
  *""enabled"": //boolean //
  ""last_run_at"": //timestamp with time zone //
  *""total_run_count"": //integer //
  *""date_changed"": //timestamp with time zone //
  *""description"": //text //
  ""crontab_id"": //integer [FK]//
  ""interval_id"": //integer [FK]//
  ""solar_id"": //integer [FK]//
  *""one_off"": //boolean //
  ""start_time"": //timestamp with time zone //
  ""priority"": //integer //
  *""headers"": //text //
  ""clocked_id"": //integer [FK]//
  ""expire_seconds"": //integer //
}

entity "**django_celery_beat_periodictasks**" {
  + ""ident"": //smallint [PK]//
  --
  *""last_update"": //timestamp with time zone //
}

entity "**django_celery_beat_solarschedule**" {
  + ""id"": //serial [PK]//
  --
  *""event"": //character varying(24) //
  *""latitude"": //numeric(9,6) //
  *""longitude"": //numeric(9,6) //
}

entity "**django_celery_results_chordcounter**" {
  + ""id"": //serial [PK]//
  --
  *""group_id"": //character varying(255) //
  *""sub_tasks"": //text //
  *""count"": //integer //
}

entity "**django_celery_results_groupresult**" {
  + ""id"": //serial [PK]//
  --
  *""group_id"": //character varying(255) //
  *""date_created"": //timestamp with time zone //
  *""date_done"": //timestamp with time zone //
  *""content_type"": //character varying(128) //
  *""content_encoding"": //character varying(64) //
  ""result"": //text //
}

entity "**django_celery_results_taskresult**" {
  + ""id"": //serial [PK]//
  --
  *""task_id"": //character varying(255) //
  *""status"": //character varying(50) //
  *""content_type"": //character varying(128) //
  *""content_encoding"": //character varying(64) //
  ""result"": //text //
  *""date_done"": //timestamp with time zone //
  ""traceback"": //text //
  ""meta"": //text //
  ""task_args"": //text //
  ""task_kwargs"": //text //
  ""task_name"": //character varying(255) //
  ""worker"": //character varying(100) //
  *""date_created"": //timestamp with time zone //
  ""periodic_task_name"": //character varying(255) //
}

entity "**django_content_type**" {
  + ""id"": //serial [PK]//
  --
  *""app_label"": //character varying(100) //
  *""model"": //character varying(100) //
}

entity "**django_migrations**" {
  + ""id"": //serial [PK]//
  --
  *""app"": //character varying(255) //
  *""name"": //character varying(255) //
  *""applied"": //timestamp with time zone //
}

entity "**django_session**" {
  + ""session_key"": //character varying(40) [PK]//
  --
  *""session_data"": //text //
  *""expire_date"": //timestamp with time zone //
}

entity "**memberbucks_memberbucks**" {
  + ""id"": //serial [PK]//
  --
  *""amount"": //double precision //
  *""transaction_type"": //character varying(10) //
  *""description"": //character varying(500) //
  *""date"": //timestamp with time zone //
  *""logging_info"": //text //
  *""user_id"": //integer [FK]//
}

entity "**memberbucks_memberbucksproduct**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(30) //
  ""description"": //character varying(250) //
  ""image_url"": //text //
  ""external_id"": //character varying(250) //
  ""external_id_name"": //character varying(250) //
  *""stock_level"": //integer //
  *""price"": //integer //
  *""cost_price"": //integer //
}

entity "**memberbucks_memberbucksproductpurchaselog**" {
  + ""id"": //serial [PK]//
  --
  *""date"": //timestamp with time zone //
  *""price"": //integer //
  *""cost_price"": //integer //
  *""success"": //boolean //
  *""memberbucks_device_id"": //integer [FK]//
  *""product_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
}

entity "**oidc_provider_client**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(100) //
  *""client_id"": //character varying(255) //
  *""client_secret"": //character varying(255) //
  *""_redirect_uris"": //text //
  *""date_created"": //date //
  *""client_type"": //character varying(30) //
  *""jwt_alg"": //character varying(10) //
  *""contact_email"": //character varying(255) //
  *""logo"": //character varying(100) //
  *""terms_url"": //character varying(255) //
  *""website_url"": //character varying(255) //
  *""_post_logout_redirect_uris"": //text //
  *""require_consent"": //boolean //
  *""reuse_consent"": //boolean //
  ""owner_id"": //integer [FK]//
  *""_scope"": //text //
}

entity "**oidc_provider_client_response_types**" {
  + ""id"": //serial [PK]//
  --
  *""client_id"": //integer [FK]//
  *""responsetype_id"": //integer [FK]//
}

entity "**oidc_provider_code**" {
  + ""id"": //serial [PK]//
  --
  *""expires_at"": //timestamp with time zone //
  *""_scope"": //text //
  *""code"": //character varying(255) //
  *""client_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
  *""nonce"": //character varying(255) //
  *""is_authentication"": //boolean //
  ""code_challenge"": //character varying(255) //
  ""code_challenge_method"": //character varying(255) //
}

entity "**oidc_provider_responsetype**" {
  + ""id"": //serial [PK]//
  --
  *""value"": //character varying(30) //
  *""description"": //character varying(50) //
}

entity "**oidc_provider_token**" {
  + ""id"": //serial [PK]//
  --
  *""expires_at"": //timestamp with time zone //
  *""_scope"": //text //
  *""access_token"": //character varying(255) //
  *""_id_token"": //text //
  *""client_id"": //integer [FK]//
  ""user_id"": //integer [FK]//
  *""refresh_token"": //character varying(255) //
}

entity "**oidc_provider_userconsent**" {
  + ""id"": //serial [PK]//
  --
  *""expires_at"": //timestamp with time zone //
  *""_scope"": //text //
  *""client_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
  *""date_given"": //timestamp with time zone //
}

entity "**profile_eventlog**" {
  + ""log_ptr_id"": //integer [PK][FK]//
  --
}

entity "**profile_log**" {
  + ""id"": //serial [PK]//
  --
  *""logtype"": //character varying(30) //
  *""description"": //character varying(500) //
  ""data"": //text //
  *""date"": //timestamp with time zone //
  ""door_id"": //integer [FK]//
  ""interlock_id"": //integer [FK]//
  ""memberbucks_device_id"": //integer [FK]//
}

entity "**profile_profile**" {
  + ""id"": //serial [PK]//
  --
  ""digital_id_token"": //uuid //
  ""digital_id_token_expire"": //timestamp with time zone //
  *""created"": //timestamp with time zone //
  *""modified"": //timestamp with time zone //
  *""screen_name"": //character varying(30) //
  *""first_name"": //character varying(30) //
  *""last_name"": //character varying(30) //
  ""rfid"": //character varying(20) //
  *""memberbucks_balance"": //double precision //
  *""last_memberbucks_purchase"": //timestamp with time zone //
  *""must_update_profile"": //boolean //
  ""last_seen"": //timestamp with time zone //
  ""last_induction"": //timestamp with time zone //
  *""user_id"": //integer [FK]//
  ""membership_plan_id"": //integer [FK]//
  *""subscription_status"": //character varying(10) //
  *""exclude_from_email_export"": //boolean //
  ""subscription_first_created"": //timestamp with time zone //
}

entity "**profile_profile_doors**" {
  + ""id"": //serial [PK]//
  --
  *""profile_id"": //integer [FK]//
  *""doors_id"": //integer [FK]//
}

entity "**profile_profile_interlocks**" {
  + ""id"": //serial [PK]//
  --
  *""profile_id"": //integer [FK]//
  *""interlock_id"": //integer [FK]//
}

entity "**profile_user**" {
  + ""id"": //serial [PK]//
  --
  *""password"": //character varying(128) //
  ""last_login"": //timestamp with time zone //
  *""is_superuser"": //boolean //
  *""email"": //character varying(255) //
  *""email_verified"": //boolean //
  ""password_reset_key"": //uuid //
  ""password_reset_expire"": //timestamp with time zone //
  *""staff"": //boolean //
  *""admin"": //boolean //
}

entity "**profile_user_groups**" {
  + ""id"": //serial [PK]//
  --
  *""user_id"": //integer [FK]//
  *""group_id"": //integer [FK]//
}

entity "**profile_user_user_permissions**" {
  + ""id"": //serial [PK]//
  --
  *""user_id"": //integer [FK]//
  *""permission_id"": //integer [FK]//
}

entity "**profile_usereventlog**" {
  + ""log_ptr_id"": //integer [PK][FK]//
  --
  *""user_id"": //integer [FK]//
}

entity "**rest_framework_api_key_apikey**" {
  + ""id"": //character varying(150) [PK]//
  --
  *""created"": //timestamp with time zone //
  *""name"": //character varying(50) //
  *""revoked"": //boolean //
  ""expiry_date"": //timestamp with time zone //
  *""hashed_key"": //character varying(150) //
  *""prefix"": //character varying(8) //
}

"**access_doorlog**"   }--  "**access_doors**"
"**access_doorlog**"   }--  "**profile_user**"
"**access_doors**"  ||-||  "**access_accesscontrolleddevice**"
"**access_interlock**"  ||-||  "**access_accesscontrolleddevice**"
"**access_interlocklog**"   }--  "**access_interlock**"
"**access_interlocklog**"   }--  "**profile_user**"
"**access_memberbucksdevice**"  ||-||  "**access_accesscontrolleddevice**"
"**api_admin_tools_paymentplan**"   }--  "**api_admin_tools_membertier**"
"**api_general_emailverificationtoken**"   }--  "**profile_user**"
"**api_general_sitesession**"   }--  "**profile_user**"
"**api_meeting_meeting_attendees**"   }--  "**api_meeting_meeting**"
"**api_meeting_meeting_attendees**"   }--  "**profile_user**"
"**api_meeting_proxyvote**"   }--  "**api_meeting_meeting**"
"**api_meeting_proxyvote**"   }--  "**profile_user**"
"**api_spacedirectory_spaceapisensorproperties**"   }--  "**api_spacedirectory_spaceapisensor**"
"**auth_group_permissions**"   }--  "**auth_group**"
"**auth_group_permissions**"   }--  "**auth_permission**"
"**auth_permission**"   }--  "**django_content_type**"
"**django_admin_log**"   }--  "**django_content_type**"
"**django_admin_log**"   }--  "**profile_user**"
"**django_celery_beat_periodictask**"   }--  "**django_celery_beat_clockedschedule**"
"**django_celery_beat_periodictask**"   }--  "**django_celery_beat_crontabschedule**"
"**django_celery_beat_periodictask**"   }--  "**django_celery_beat_intervalschedule**"
"**django_celery_beat_periodictask**"   }--  "**django_celery_beat_solarschedule**"
"**memberbucks_memberbucksproductpurchaselog**"   }--  "**access_memberbucksdevice**"
"**memberbucks_memberbucksproductpurchaselog**"   }--  "**memberbucks_memberbucksproduct**"
"**memberbucks_memberbucksproductpurchaselog**"   }--  "**profile_user**"
"**memberbucks_memberbucks**"   }--  "**profile_user**"
"**oidc_provider_client**"   }--  "**profile_user**"
"**oidc_provider_client_response_types**"   }--  "**oidc_provider_client**"
"**oidc_provider_client_response_types**"   }--  "**oidc_provider_responsetype**"
"**oidc_provider_code**"   }--  "**oidc_provider_client**"
"**oidc_provider_code**"   }--  "**profile_user**"
"**oidc_provider_token**"   }--  "**oidc_provider_client**"
"**oidc_provider_token**"   }--  "**profile_user**"
"**oidc_provider_userconsent**"   }--  "**oidc_provider_client**"
"**oidc_provider_userconsent**"   }--  "**profile_user**"
"**profile_eventlog**"  ||-||  "**profile_log**"
"**profile_log**"   }--  "**access_doors**"
"**profile_log**"   }--  "**access_interlock**"
"**profile_log**"   }--  "**access_memberbucksdevice**"
"**profile_profile**"   }--  "**api_admin_tools_paymentplan**"
"**profile_profile_doors**"   }--  "**access_doors**"
"**profile_profile_doors**"   }--  "**profile_profile**"
"**profile_profile_interlocks**"   }--  "**access_interlock**"
"**profile_profile_interlocks**"   }--  "**profile_profile**"
"**profile_profile**"   }--  "**profile_user**"
"**profile_usereventlog**"  ||-||  "**profile_log**"
"**profile_usereventlog**"   }--  "**profile_user**"
"**profile_user_groups**"   }--  "**auth_group**"
"**profile_user_groups**"   }--  "**profile_user**"
"**profile_user_user_permissions**"   }--  "**auth_permission**"
"**profile_user_user_permissions**"   }--  "**profile_user**"

@enduml
