@startuml
left to right direction
hide circle
/'
 ' skinparam linetype ortho
 '/

entity "**api_admin_tools_membertier**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(150) //
  *""description"": //character varying(250) //
  *""visible"": //boolean //
  *""featured"": //boolean //
}

entity "**api_admin_tools_paymentplan**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(50) //
  *""visible"": //boolean //
  *""cost"": //integer //
  *""interval"": //character varying(10) //
  *""member_tier_id"": //integer [FK]//
  *""interval_count"": //integer //
  *""currency"": //character varying(3) //
}


entity "**profile_profile**" {
  + ""id"": //serial [PK]//
  --
  ""digital_id_token"": //uuid //
  ""digital_id_token_expire"": //timestamp with time zone //
  *""screen_name"": //character varying(30) //
  ""rfid"": //character varying(20) //
  *""memberbucks_balance"": //double precision //
  *""last_memberbucks_purchase"": //timestamp with time zone //
  *""user_id"": //integer [FK]//
  ""membership_plan_id"": //integer [FK]//
  *""subscription_status"": //character varying(10) //
}

entity "**profile_profile_doors**" {
  + ""id"": //serial [PK]//
  --
  *""profile_id"": //integer [FK]//
  *""doors_id"": //integer [FK]//
}

entity "**profile_profile_interlocks**" {
  + ""id"": //serial [PK]//
  --
  *""profile_id"": //integer [FK]//
  *""interlock_id"": //integer [FK]//
}

"**api_admin_tools_paymentplan**"   }--  "**api_admin_tools_membertier**"
"**profile_profile**"   }--  "**api_admin_tools_paymentplan**"
"**profile_profile_doors**"   }--  "**profile_profile**"
"**profile_profile_interlocks**"   }--  "**profile_profile**"

@enduml
