@startuml
left to right direction
hide circle
/'
 ' skinparam linetype ortho
 '/

entity "**access_memberbucksdevice**" {
  + ""accesscontrolleddevice_ptr_id"": //integer [PK][FK]//
  --
}

entity "**memberbucks_memberbucks**" {
  + ""id"": //serial [PK]//
  --
  *""amount"": //double precision //
  *""transaction_type"": //character varying(10) //
  *""description"": //character varying(500) //
  *""date"": //timestamp with time zone //
  *""logging_info"": //text //
  *""user_id"": //integer [FK]//
}

entity "**memberbucks_memberbucksproduct**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(30) //
  ""description"": //character varying(250) //
  ""image_url"": //text //
  ""external_id"": //character varying(250) //
  ""external_id_name"": //character varying(250) //
  *""stock_level"": //integer //
  *""price"": //integer //
  *""cost_price"": //integer //
}

entity "**memberbucks_memberbucksproductpurchaselog**" {
  + ""id"": //serial [PK]//
  --
  *""date"": //timestamp with time zone //
  *""price"": //integer //
  *""cost_price"": //integer //
  *""success"": //boolean //
  *""memberbucks_device_id"": //integer [FK]//
  *""product_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
}

entity "**profile_eventlog**" {
  + ""log_ptr_id"": //integer [PK][FK]//
  --
}

entity "**profile_log**" {
  + ""id"": //serial [PK]//
  --
  *""logtype"": //character varying(30) //
  *""description"": //character varying(500) //
  ""data"": //text //
  *""date"": //timestamp with time zone //
  ""door_id"": //integer [FK]//
  ""interlock_id"": //integer [FK]//
  ""memberbucks_device_id"": //integer [FK]//
}

entity "**profile_profile**" {
  + ""id"": //serial [PK]//
  --
  ""digital_id_token"": //uuid //
  ""digital_id_token_expire"": 
  *""screen_name"": 
  ""rfid"": //character varying(20) //
  *""memberbucks_balance"": 
  *""last_memberbucks_purchase"": 
  *""user_id"": //integer [FK]//
  ""membership_plan_id"": //integer [FK]//
  *""subscription_status"": 
}

entity "**profile_user**" {
  + ""id"": //serial [PK]//
  --
  *""password"": 
  *""is_superuser"": 
  *""email"": 
  *""staff"": 
  *""admin"": 
}

"**memberbucks_memberbucksproductpurchaselog**"   }--  "**access_memberbucksdevice**"
"**memberbucks_memberbucksproductpurchaselog**"   }--  "**memberbucks_memberbucksproduct**"
"**memberbucks_memberbucksproductpurchaselog**"   }--  "**profile_user**"
"**memberbucks_memberbucks**"   }--  "**profile_user**"
"**profile_eventlog**"  ||-||  "**profile_log**"
"**profile_log**"   }--  "**access_memberbucksdevice**"
"**profile_profile**"   }--  "**profile_user**"

@enduml
