@startuml
left to right direction
hide circle
/'
 ' skinparam linetype polyline
 '/

entity "**api_general_emailverificationtoken**" {
  + ""id"": //serial [PK]//
  --
  *""creation_date"": //timestamp with time zone //
  *""verification_token"": //uuid //
  *""user_id"": //integer [FK]//
}

entity "**api_general_kiosk**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(30) //
  *""kiosk_id"": //character varying(70) //
  ""ip_address"": //inet //
  ""last_seen"": //timestamp with time zone //
  *""play_theme"": //boolean //
  *""authorised"": //boolean //
}

entity "**api_general_sitesession**" {
  + ""id"": //serial [PK]//
  --
  *""signin_date"": //timestamp with time zone //
  ""signout_date"": //timestamp with time zone //
  *""guests"": //text //
  *""user_id"": //integer [FK]//
}

entity "**oidc_provider_client**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(100) //
  *""client_id"": //character varying(255) //
  *""client_secret"": //character varying(255) //
  *""_redirect_uris"": //text //
  *""date_created"": //date //
  *""client_type"": //character varying(30) //
  *""jwt_alg"": //character varying(10) //
  *""contact_email"": //character varying(255) //
  *""logo"": //character varying(100) //
  *""terms_url"": //character varying(255) //
  *""website_url"": //character varying(255) //
  *""_post_logout_redirect_uris"": //text //
  *""require_consent"": //boolean //
  *""reuse_consent"": //boolean //
  ""owner_id"": //integer [FK]//
  *""_scope"": //text //
}

entity "**oidc_provider_client_response_types**" {
  + ""id"": //serial [PK]//
  --
  *""client_id"": //integer [FK]//
  *""responsetype_id"": //integer [FK]//
}

entity "**oidc_provider_code**" {
  + ""id"": //serial [PK]//
  --
  *""expires_at"": //timestamp with time zone //
  *""_scope"": //text //
  *""code"": //character varying(255) //
  *""client_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
  *""nonce"": //character varying(255) //
  *""is_authentication"": //boolean //
  ""code_challenge"": //character varying(255) //
  ""code_challenge_method"": //character varying(255) //
}

entity "**oidc_provider_responsetype**" {
  + ""id"": //serial [PK]//
  --
  *""value"": //character varying(30) //
  *""description"": //character varying(50) //
}

entity "**oidc_provider_token**" {
  + ""id"": //serial [PK]//
  --
  *""expires_at"": //timestamp with time zone //
  *""_scope"": //text //
  *""access_token"": //character varying(255) //
  *""_id_token"": //text //
  *""client_id"": //integer [FK]//
  ""user_id"": //integer [FK]//
  *""refresh_token"": //character varying(255) //
}

entity "**oidc_provider_userconsent**" {
  + ""id"": //serial [PK]//
  --
  *""expires_at"": //timestamp with time zone //
  *""_scope"": //text //
  *""client_id"": //integer [FK]//
  *""user_id"": //integer [FK]//
  *""date_given"": //timestamp with time zone //
}

entity "**profile_user**" {
  + ""id"": //serial [PK]//
  --
  *""password"": //character varying(128) //
  ""last_login"": //timestamp with time zone //
  *""is_superuser"": //boolean //
  *""email"": //character varying(255) //
  *""email_verified"": //boolean //
  ""password_reset_key"": //uuid //
  ""password_reset_expire"": //timestamp with time zone //
  *""staff"": //boolean //
  *""admin"": //boolean //
}

"**api_general_emailverificationtoken**"   }--  "**profile_user**"
"**api_general_sitesession**"   }--  "**profile_user**"
"**oidc_provider_client**"   }--  "**profile_user**"
"**oidc_provider_client_response_types**"   }--  "**oidc_provider_client**"
"**oidc_provider_client_response_types**"   }--  "**oidc_provider_responsetype**"
"**oidc_provider_code**"   }--  "**oidc_provider_client**"
"**oidc_provider_code**"   }--  "**profile_user**"
"**oidc_provider_token**"   }--  "**oidc_provider_client**"
"**oidc_provider_token**"   }--  "**profile_user**"
"**oidc_provider_userconsent**"   }--  "**oidc_provider_client**"
"**oidc_provider_userconsent**"   }--  "**profile_user**"

@enduml
