@startuml
left to right direction
hide circle
/'
 ' skinparam linetype ortho
 '/

entity "**access_accesscontrolleddevice**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(30) //
  *""description"": //character varying(500) //
  ""ip_address"": //inet //
  ""last_seen"": //timestamp with time zone //
  *""all_members"": //boolean //
  *""locked_out"": //boolean //
  *""play_theme"": //boolean //
  *""exempt_signin"": //boolean //
  *""hidden"": //boolean //
  ""serial_number"": //character varying(50) //
  *""report_online_status"": //boolean //
  *""post_to_discord"": //boolean //
  *""authorised"": //boolean //
  *""post_to_slack"": //boolean //
}

entity "**access_doorlog**" {
  + ""id"": //serial [PK]//
  --
  *""date"": //timestamp with time zone //
  *""user_id"": //integer [FK]//
  *""door_id"": //integer [FK]//
  *""success"": //boolean //
}

entity "**access_doors**" {
  + ""accesscontrolleddevice_ptr_id"": //integer [PK][FK]//
  --
}

entity "**access_interlock**" {
  + ""accesscontrolleddevice_ptr_id"": //integer [PK][FK]//
  --
  *""cost_per_hour"": //integer //
  *""cost_per_kwh"": //integer //
  *""cost_per_session"": //integer //
}

entity "**access_interlocklog**" {
  + ""id"": //uuid [PK]//
  --
  *""date_updated"": //timestamp with time zone //
  *""user_started_id"": //integer [FK]//
  *""interlock_id"": //integer [FK]//
  ""date_ended"": //timestamp with time zone //
  *""date_started"": //timestamp with time zone //
  ""reason"": //character varying(500) //
  *""success"": //boolean //
  ""total_cost"": //double precision //
  ""total_kwh"": //double precision //
  *""total_time"": //interval //
  ""user_ended_id"": //integer [FK]//
}

entity "**api_admin_tools_membertier**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(150) //
  *""description"": //character varying(250) //
  *""visible"": //boolean //
  *""featured"": //boolean //
}

entity "**api_admin_tools_paymentplan**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(50) //
  *""visible"": //boolean //
  *""cost"": //integer //
  *""interval"": //character varying(10) //
  *""member_tier_id"": //integer [FK]//
  *""interval_count"": //integer //
  *""currency"": //character varying(3) //
}

entity "**profile_profile_doors**" {
  + ""id"": //serial [PK]//
  --
  *""profile_id"": //integer [FK]//
  *""doors_id"": //integer [FK]//
}

entity "**profile_profile_interlocks**" {
  + ""id"": //serial [PK]//
  --
  *""profile_id"": //integer [FK]//
  *""interlock_id"": //integer [FK]//
}

entity "**profile_profile**" {
  + ""id"": //serial [PK]//
  --
  ""digital_id_token"": //uuid //
  ""digital_id_token_expire"":
  *""screen_name"":
  ""rfid"": //character varying(20) //
  *""memberbucks_balance"":
  *""last_memberbucks_purchase"":
  *""user_id"": //integer [FK]//
  ""membership_plan_id"": //integer [FK]//
  *""subscription_status"":
}

entity "**profile_user**" {
  + ""id"": //serial [PK]//
  --
  *""password"":
  *""is_superuser"":
  *""email"":
  *""staff"":
  *""admin"":
}

"**access_doorlog**"   }--  "**access_doors**"
"**access_doorlog**"   }--  "**profile_user**"
"**access_doors**"  ||-||  "**access_accesscontrolleddevice**"
"**access_interlock**"  ||-||  "**access_accesscontrolleddevice**"
"**access_interlocklog**"   }--  "**access_interlock**"
"**access_interlocklog**"   }--  "**profile_user**"
"**api_admin_tools_paymentplan**"   }--  "**api_admin_tools_membertier**"
"**profile_profile**"   }--  "**api_admin_tools_paymentplan**"
"**profile_profile_doors**"   }--  "**access_doors**"
"**profile_profile_doors**"   }--  "**profile_profile**"
"**profile_profile_interlocks**"   }--  "**access_interlock**"
"**profile_profile_interlocks**"   }--  "**profile_profile**"
"**profile_profile**"   }--  "**profile_user**"

@enduml
