@startuml
left to right direction
hide circle
/'
 ' skinparam linetype ortho
 '/

entity "**constance_config**" {
  + ""id"": //serial [PK]//
  --
  *""key"": //character varying(255) //
  ""value"": //text //
}

entity "**django_celery_beat_clockedschedule**" {
  + ""id"": //serial [PK]//
  --
  *""clocked_time"": //timestamp with time zone //
}

entity "**django_celery_beat_crontabschedule**" {
  + ""id"": //serial [PK]//
  --
  *""minute"": //character varying(240) //
  *""hour"": //character varying(96) //
  *""day_of_week"": //character varying(64) //
  *""day_of_month"": //character varying(124) //
  *""month_of_year"": //character varying(64) //
  *""timezone"": //character varying(63) //
}

entity "**django_celery_beat_intervalschedule**" {
  + ""id"": //serial [PK]//
  --
  *""every"": //integer //
  *""period"": //character varying(24) //
}

entity "**django_celery_beat_periodictask**" {
  + ""id"": //serial [PK]//
  --
  *""name"": //character varying(200) //
  *""task"": //character varying(200) //
  *""args"": //text //
  *""kwargs"": //text //
  ""queue"": //character varying(200) //
  ""exchange"": //character varying(200) //
  ""routing_key"": //character varying(200) //
  ""expires"": //timestamp with time zone //
  *""enabled"": //boolean //
  ""last_run_at"": //timestamp with time zone //
  *""total_run_count"": //integer //
  *""date_changed"": //timestamp with time zone //
  *""description"": //text //
  ""crontab_id"": //integer [FK]//
  ""interval_id"": //integer [FK]//
  ""solar_id"": //integer [FK]//
  *""one_off"": //boolean //
  ""start_time"": //timestamp with time zone //
  ""priority"": //integer //
  *""headers"": //text //
  ""clocked_id"": //integer [FK]//
  ""expire_seconds"": //integer //
}

entity "**django_celery_beat_periodictasks**" {
  + ""ident"": //smallint [PK]//
  --
  *""last_update"": //timestamp with time zone //
}

entity "**django_celery_beat_solarschedule**" {
  + ""id"": //serial [PK]//
  --
  *""event"": //character varying(24) //
  *""latitude"": //numeric(9,6) //
  *""longitude"": //numeric(9,6) //
}

entity "**django_celery_results_chordcounter**" {
  + ""id"": //serial [PK]//
  --
  *""group_id"": //character varying(255) //
  *""sub_tasks"": //text //
  *""count"": //integer //
}

entity "**django_celery_results_groupresult**" {
  + ""id"": //serial [PK]//
  --
  *""group_id"": //character varying(255) //
  *""date_created"": //timestamp with time zone //
  *""date_done"": //timestamp with time zone //
  *""content_type"": //character varying(128) //
  *""content_encoding"": //character varying(64) //
  ""result"": //text //
}

entity "**django_celery_results_taskresult**" {
  + ""id"": //serial [PK]//
  --
  *""task_id"": //character varying(255) //
  *""status"": //character varying(50) //
  *""content_type"": //character varying(128) //
  *""content_encoding"": //character varying(64) //
  ""result"": //text //
  *""date_done"": //timestamp with time zone //
  ""traceback"": //text //
  ""meta"": //text //
  ""task_args"": //text //
  ""task_kwargs"": //text //
  ""task_name"": //character varying(255) //
  ""worker"": //character varying(100) //
  *""date_created"": //timestamp with time zone //
  ""periodic_task_name"": //character varying(255) //
}

"**django_celery_beat_periodictask**"   }--  "**django_celery_beat_clockedschedule**"
"**django_celery_beat_periodictask**"   }--  "**django_celery_beat_crontabschedule**"
"**django_celery_beat_periodictask**"   }--  "**django_celery_beat_intervalschedule**"
"**django_celery_beat_periodictask**"   }--  "**django_celery_beat_solarschedule**"

@enduml
