:PROPERTIES:
:ID:       b5db93f1-02a4-4ee7-bf62-70f19c2e8731
:ROAM_REFS: @bischof-2020-higher-order-co
:END:
#+title: (2020) Higher Order Co-Occurrence Tensors for Hypergraphs Via Face-Splitting - Bryan Bischof.
#+created: [2024-06-30 Sun 17:27]
#+last_modified: [2024-06-30 Sun 17:27]

+ file :: bischof-2020-higher-order-co.pdf



This allows you (or an algorithm) to more easily reason about potential tensor
decompositions that give you options for recombinating the
structure. i.e. so you can

+ Decompose Tensors: $A_{abc} B_{def}$ into $A\prime_{abef} $B\prime_{bief}$
+ For $A$ the index $c\rightarrow \left(e,f\right)$ and for $B$, the index $c\rightarrow \left(b,i\right)$
+ Then contract along the available indices: $X_{ai}$


#+begin_quote
The Khatri-Rao product is the “matching columnwise” Kronecker product
#+end_quote

And

#+begin_quote
Similarly, the “matching rowwise” Kronecker product, or the face-splitting product is defined:
#+end_quote

.... though I don't have much of an understanding of it symbolically, this is
something i've been struggling to identify/name for over a decade (since the
notation is a PITA with no one to ask for clarification). I've seen the
definition/explanation of tensor product explained using like 10 different sets
of symbols.

* Notes
:PROPERTIES:
# :NOTER_DOCUMENT:
:END:
