:PROPERTIES:
:ID:       f90b0a6d-1144-499d-8fff-64cb5465d336
:ROAM_REFS: @pizzimentibernazzani-2021-oxidat-cross-linkin
:END:
#+title: (2021) Oxidation and Cross-Linking in the Curing of Air-Drying Artists’ Oil Paints - Pizzimenti, Silvia and Bernazzani, Luca and Tinè, Maria Rosaria and Treil, Valérie and Duce, Celia and Bonaduce, Ilaria.
#+created: [2023-11-21 Tue 21:35]
#+last_modified: [2023-11-21 Tue 21:35]

+ file :: pizzimentibernazzani-2021-oxidat-cross-linkin.pdf

#+begin_quote
i'm not 100% clear on whether peroxides bad or peroxides good.

it depends on whether they consume oxygen that would otherwise contribute to
cross-linking. this should be what happens, which is bad for the polymerization
oxygen economy.  if so, peroxides bad, but the article doesn't exactly "ELI5"
#+end_quote

* Takeaways

** Ultramarine

Don't use way too much ultramarine: it accelerates the wrong reaction
pathways. The significance you should attribute to this should be proportional
to however much attention the art community gives it (except people who tend to
blow things out of proportion).

** Oils

Prefer linseed oil over safflower oil

+ With linseed, the crosslinking always increases with age.
+ Safflower crosslinks significantly less. It also contributes to the
  "problematic organic reactants" economy, where some of these reaction products
  contribute to volatility (movement of small molecules).

** Misc (IMO)

Obviously, paint is robust enough to use without a degree in chemistry. The
manufacturers probably add stabilizers to problematic pigments in an attempt to
dampen their capacity to compete for oxygen (which drives cross-linking). No
idea what these are, some of them may be generic and others may be
pigment-specific. The color of inorganics mostly arises from bandgaps (i think
everything does, probably?), but it's less affected by smaller side reactions
than organics. So they may respond well to stabalizers or at least ... yeh IDK.

*** Mechanics

+ Inorganics are relatively large when compared to components of
  hydrocarbons. This is esp. true with the inorganic mineral complexes
  (ultramarine).
+ For inorganics, the size of the ion complex or smallest unit is much less
  important than the grain size.
+ The variation in sizes of solution particles should also be considered.
+ For organic pigments, as reactions occur, the grains will break down. These
  should generally require less time to mill. Without a lattice, a pigment will
  breakdown easily, since the bonds in a lattice produce strength/hardness
  through resonance. you can't easily produce highly durable materials without a
  lattice.
+ For titanium white, it's extremely stable and probably /somewhat/ mobile with
  extremely small grain size. It won't contribute to breakdown whatsoever (it's
  stability is responsible for the price of titanium).

*** Dynamics

Once sufficient cross-linking occurs, volatility shouldn't contribute much to
breakdown.

Volatility carries hydrocarbons and could transport products between layers. But
it's the mobility provided by volatility that drives additional chain
reactions.

Typically, the reaction products are successively smaller: something is more
likely to break in the middle than at the ends. That's an overgeneralization,
but it holds for unsaturated fats where the double-bonds provide a potential
site where cross-linking mechanisms can occur.

If something bonds strongly to a large ion (like with lead white), then it will
tend to remain there (the degrees of freedom are limited for the atoms closest
to the /strong/ bond). I don't have a sense of proportion for organometallic
bonds (or for much of chemistry).

Inorganic grains may tend to break down over time, depending on how they
interact with the cross-linking. This could occur with lead-white. This would be
a separate effect from what's observed in the article's results where lead white
form complexes with cross-linked molecules. If the sum of resonant forces in a
pigment grain can't deal with the tension/shear, then the grain will begin to
split.

** Lead White

The amount of lead in a tube of paint is more than enough for acute lead
poisoning. Pigments in paint are often 30-70% of the content, unless it's
stretched by titanium white. Unless you can plan hours ahead on your painting
(layers/regions), and use separate jars/brushes/pallettes and wear gloves, it's
not worth it. You can't avoid encountering it in your workspace unless you can
track every drop.

... But it has extremely useful and unique chemical properties for the color. It
also apparently reduces the drying time.

* Notes
:PROPERTIES:
:NOTER_DOCUMENT: /data/xdg/documents/articles/pizzimentibernazzani-2021-oxidat-cross-linkin.pdf
:END:

* Roam
+ [[id:beafc05d-75b4-4013-8b43-9c0483a30328][Art]]
