#+TITLE:     Noter: Readme
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes


* Org Noter

A repo decicated to the remarkable PDF's worth noting on

* Ideas

** Organization of Journals and Books

#+begin_quote
This is older stuff. There are likely better alternatives. I'd eventually like
to have something that pulls DOI docs into a file system, along with a task that
updates a sqlite database for bibliography.
#+end_quote

I need to restructure my kindle docs, but after looking at =org-bibtex= &
=org-ref=, it seems the best way to do this is to process the docs/pdf's from
their existing location (as needed) into =*.bib= files (and/or integrations with
some kind of bibtex DB or with a product like Zotoro.)

org-bibtex and org-roam have some facilities for doing this, but are mainly
intended to browse "frontend" lists/collections of related papers -- frontend
meaning similar to the kind of output a set of graphdb query might provide.
variables similar to =org-directory= or =org-roam-db= can be set to provide access to multiple =*.bib= databases.

*** File Structures

+ [[http://arxitics.com/help][arXiv.org help]] includes:
  - categories,
  - themes/topics,
  - journals,
  - tags
  - resource types
  - commands

+ DOI (prefix/suffix) includes more general information
  - less human-readable. prefix is structured by the registrant
  - there are ontological standards for mapping categories here, but they are
    likely too general (meant for human/comp interaction without getting bogged
    down by language)

*** Process

- Private repo.
- Copy in the PDF's

**** TODO autogenerate folders

+ either named/numbered according to DOI categories or journal categories
+ something i don't have to think about that doesn't change
