CREATE TABLE [n_association_scan_category] ([scan], [category], FOREIGN KEY (category) REFERENCES n_category(id), FOREIGN KEY (scan) REFERENCES n_scan(id));
CREATE TABLE [n_association_scan_hostname] ([scan], [hostname], FOREIGN KEY (hostname) REFERENCES n_hostname(id), FOREIGN KEY (scan) REFERENCES n_scan(id));
CREATE TABLE [n_category] ([id] integer PRIMARY KEY, [name]);
CREATE TABLE [n_hop] ([id] integer PRIMARY KEY, [trace], [ipaddr], [ttl], [rtt], [host], [domains], FOREIGN KEY (trace) REFERENCES n_trace(id), FOREIGN KEY (ipaddr) REFERENCES n_scan(addr));
CREATE TABLE [n_hostname] ([id] integer PRIMARY KEY, [scan], [domains], [name], [type], FOREIGN KEY (scan) REFERENCES n_scan(id));
CREATE TABLE [n_port] ([id] integer PRIMARY KEY, [scan], [port], [protocol], [state], [state_reason], [state_reason_ip], [state_reason_ttl], [service_name], [service_tunnel], [service_product], [service_version], [service_conf], [service_devicetype], [service_extrainfo], [service_hostname], [service_ostype], [service_fp], FOREIGN KEY (scan) REFERENCES n_scan(id));
CREATE TABLE [n_scan] ([id] integer PRIMARY KEY, [addr], [info], [time_start], [time_stop], [state], [state_reason], [state_reason_ttl], [schema_version], [source]);
CREATE TABLE [n_script] ([port], [name], [output], [data], FOREIGN KEY (port) REFERENCES n_port(id));
CREATE TABLE [n_tag] ([id] integer PRIMARY KEY, [scan], [value], [type], [info], FOREIGN KEY (scan) REFERENCES n_scan(id));
CREATE TABLE [n_trace] ([id] integer PRIMARY KEY, [scan], [port], [protocol], FOREIGN KEY (scan) REFERENCES n_scan(id));
CREATE TABLE [passive] ([id] integer PRIMARY KEY, [addr], [sensor], [count], [firstseen], [lastseen], [port], [recontype], [source], [targetval], [value], [info], [moreinfo], [schema_version]);
CREATE INDEX ix_n_hop_domains ON n_hop ([domains]);
CREATE INDEX ix_n_hop_host ON n_hop ([host]);
CREATE INDEX ix_n_hop_ipaddr_ttl ON n_hop ([ipaddr],[ttl]);
CREATE INDEX ix_n_hostname_domains ON n_hostname ([domains]);
CREATE INDEX ix_n_hostname_name ON n_hostname ([name]);
CREATE INDEX ix_n_hostname_type ON n_hostname ([type]);
CREATE INDEX ix_n_scan_host ON n_scan ([addr]);
CREATE INDEX ix_n_scan_info ON n_scan ([info]);
CREATE INDEX ix_n_scan_time ON n_scan ([time_start],[time_stop]);
CREATE INDEX ix_n_script_data ON n_script ([data]);
CREATE INDEX ix_n_script_name ON n_script ([name]);
