@startuml





/' Objects '/

class sway_drag {
	+seat : struct sway_seat*
	+destroy : struct wl_listener
	+wlr_drag : struct wlr_drag*
}


class sway_drag_icon {
	+x : double
	+y : double
	+seat : struct sway_seat*
	+link : struct wl_list
	+destroy : struct wl_listener
	+map : struct wl_listener
	+surface_commit : struct wl_listener
	+unmap : struct wl_listener
	+wlr_drag_icon : struct wlr_drag_icon*
}


class sway_keyboard_shortcuts_inhibitor {
	+link : struct wl_list
	+destroy : struct wl_listener
	+inhibitor : struct wlr_keyboard_shortcuts_inhibitor_v1*
}


class sway_pointer_constraint {
	+cursor : struct sway_cursor*
	+destroy : struct wl_listener
	+set_region : struct wl_listener
	+constraint : struct wlr_pointer_constraint_v1*
}


class sway_seat {
	+has_focus : bool
	+prev_workspace_name : char*
	+seatop_impl : const struct sway_seatop_impl*
	+touch_x : double
	+touch_y : double
	+touch_id : int32_t
	+deferred_bindings : list_t*
	+cursor : struct sway_cursor*
	+im_relay : struct sway_input_method_relay
	+workspace : struct sway_workspace*
	+exclusive_client : struct wl_client*
	+devices : struct wl_list
	+focus_stack : struct wl_list
	+keyboard_groups : struct wl_list
	+keyboard_shortcuts_inhibitors : struct wl_list
	+link : struct wl_list
	+focus_destroy : struct wl_listener
	+new_node : struct wl_listener
	+request_set_primary_selection : struct wl_listener
	+request_set_selection : struct wl_listener
	+request_start_drag : struct wl_listener
	+start_drag : struct wl_listener
	+focused_layer : struct wlr_layer_surface_v1*
	+wlr_seat : struct wlr_seat*
	+idle_inhibit_sources : uint32_t
	+idle_wake_sources : uint32_t
	+last_button_serial : uint32_t
	+seatop_data : void*
}


class sway_seat_device {
	+input_device : struct sway_input_device*
	+keyboard : struct sway_keyboard*
	+sway_seat : struct sway_seat*
	+switch_device : struct sway_switch*
	+tablet : struct sway_tablet*
	+tablet_pad : struct sway_tablet_pad*
	+link : struct wl_list
}


class sway_seat_node {
	+node : struct sway_node*
	+seat : struct sway_seat*
	+link : struct wl_list
	+destroy : struct wl_listener
}


class sway_seatop_impl {
	+allow_set_cursor : bool
	+end : void (* ) ( struct sway_seat* seat )
	+unref : void (* ) ( struct sway_seat* seat, struct sway_container* con )
	+render : void (* ) ( struct sway_seat* seat, struct sway_output* output, pixman_region32_t* damage )
	+tablet_tool_motion : void (* ) ( struct sway_seat* seat, struct sway_tablet_tool* tool, uint32_t time_msec )
	+tablet_tool_tip : void (* ) ( struct sway_seat* seat, struct sway_tablet_tool* tool, uint32_t time_msec, enum wlr_tablet_tool_tip_state state )
	+pointer_axis : void (* ) ( struct sway_seat* seat, struct wlr_event_pointer_axis* event )
	+pointer_motion : void (* ) ( struct sway_seat* seat, uint32_t time_msec )
	+rebase : void (* ) ( struct sway_seat* seat, uint32_t time_msec )
	+button : void (* ) ( struct sway_seat* seat, uint32_t time_msec, struct wlr_input_device* device, uint32_t button, enum wlr_button_state state )
}





/' Inheritance relationships '/




/' Aggregation relationships '/

.sway_drag o-- .sway_seat


.sway_drag_icon o-- .sway_seat


.sway_seat o-- .sway_seatop_impl


.sway_seat_device o-- .sway_seat


.sway_seat_node o-- .sway_seat


.sway_seatop_impl "9" o-- .sway_seat






/' Nested objects '/



@enduml
