:PROPERTIES:
:ID:       158a3cd8-c08b-4c25-a76d-48bfbe579c6d
:END:
#+TITLE: Agenticalisterisis: Agents, LLM, AI
#+DESCRIPTION: Agents
#+TAGS:

* Roam
+ [[id:cea7d11c-8357-4e4f-90b3-fa8210eff796][AI]]
+ [[id:b4c096ee-6e40-4f34-85a1-7fc901e819f5][Python]]
+ [[id:90c681e3-7748-4039-abf1-69755e14c918][SELinux]]
+ [[id:afe1b2f0-d765-4b68-85d0-2a9983fa2127][Containers]]

* Docs

* Resources

* Topics
** Sandboxes
+ Seccomp, AppArmor, SELinux, Network Isolation, User Namespaces
+ Running any of those without some kind of pre-established service probably
  requires root or elevated permissions. With network isolation, it doesn't
  cascade.
+ At some point, it relies on strong cryptography and doesn't have a single
  human point of failure.

#+begin_quote
"once is a accident, twice is a coincidence, three times is a pattern"

This is about conditional dependencies:

\(P(\overline{a\,\&\, b\,\&\,c}) = \left(1 - a*b*c\right)\)

Individual probabilities of =a,b,c= are inconsequential w.r.t. their product.
#+end_quote

*** "Sandboxes"
**** Restricted Python

IMO, this is the "wrong box"[fn:1]. Still interesting. Then again, I don't get
anything done.

+ [[https://github.com/zopefoundation/RestrictedPython][zopefoundation/RestrictedPython]]
+ [[https://codeberg.org/sudontdoit/uv-ai-sandbox][sudontdoit/uv-ai-sandbox]]
** Frameworks

*** [[https://github.com/lexler/augmented-coding-patterns][lexler/augmented-coding-patterns]]

+ [[https://lexler.github.io/augmented-coding-patterns/][Augmented Coding Patterns]] some handy tips. There's not really a roadmap of the
  SRE/Archtecture Engineer's terrain though.

**** [[https://codeberg.org/bbaassssiiee/claudia][bbaassssiiee/claudia]]

A fork of the above. A few word changes here and it sounds a tiny bit like
scientology:

#+begin_quote
The practitioner who can recognize their own role shifts in real time is
operating at a higher +level+ thetans than the one who cannot. Claudia's job is
partly to make those shifts visible.
#+end_quote

Using theatre/dialogue creates separation/abstraction that causes LLM to engage
in dialectic with itself (and also permitting similar dialectic in your
interaction with chat-based LLM). It's super useful. It's hard to become super
attached *to the letter* of what the LLM is writing, since dialogue requires
interpretation.

That's not necessarily what's happening here in [[https://codeberg.org/bbaassssiiee/claudia/src/branch/main/documents/theatre_entree.md][claudia]]. instead, it seems to
encourage the user to ask Claude to focus on these roles -- while indirectly
encouraging the user to adopt these roles somewhat, whether they realize it or
not. It could become difficult to determine who's the agent, the actor and the
entity in control... mwahaha.


* Footnotes

[fn:1] [[id:887aa490-b6d9-4776-9ef8-57b4143f8f30][Everything is a box (Sops)]]
    - also [[id:480f561a-ee49-444f-b3f7-b0e886fb83ca][Everything is a box: (Abstractification™)]]
    - and [[id:887aa490-b6d9-4776-9ef8-57b4143f8f30][Everything is a box (Sops)]]
