:PROPERTIES:
:ID:       158a3cd8-c08b-4c25-a76d-48bfbe579c6d
:END:
#+TITLE: Agenticalisterisis: Agents, LLM, AI
#+DESCRIPTION: Agents
#+TAGS:

* Roam
+ [[id:cea7d11c-8357-4e4f-90b3-fa8210eff796][AI]]
+ [[id:b4c096ee-6e40-4f34-85a1-7fc901e819f5][Python]]
+ [[id:90c681e3-7748-4039-abf1-69755e14c918][SELinux]]
+ [[id:afe1b2f0-d765-4b68-85d0-2a9983fa2127][Containers]]

* Docs

* Resources
+ [[https://github.com/AlexsJones/llmfit][AlexsJones/llmfit]] like =llm-checker= but without terminal nodejs hydrocephalus
  - =nix shell github:AlexsJones/llmfit=

** Fine Tuning

*** Unsloth

*** Techniques

| LoRA | QLoRA | PEFT | BitDelta |

* Topics
** Harnesses
*** Crush

**** Secrets

Uses a restricted bash evaluation in the config file, so something like this
works, without leaving shit around the =/proc= filesystem

#+begin_example json
{
  "providers": {
    "opencode": {
      "api_key": "$(gpg --quiet --decrypt ~/.secrets/opencode.gpg)",
      "base_url": "https://opencode.ai/zen/v1"
    }
  },
  "models": {
    "big-pickle": {
      "provider": "opencode",
      "id": "big-pickle"
    }
  }
}
#+end_example

... if we're worried about AI hording energy and zealously minimizing human
energy consumption, then .... um the first thing AI will go for is tokens.
(idk... paranoid)

** Metrics

*** Perplexity

**** Definition/comparison

Perplexity (via [[http://huggingface.co/docs/transformers/en/perplexity][huggingface]])

\(\text{PPL}(X) = \exp\left\{ -\frac{1}{t}\sum_i^t \log p_\theta (x_i|x_{<i})
\right\}\)

Cross Entropy



Quantifying confidence

| Entropy       | Measures the average uncertainty in a single probability distribution P           |
| Cross-Entropy | Measures how well a predicted distribution Q approximates the true distribution P |
| Perplexity    | Exponentiation of cross-entropy;                                                  |
|               | Measures how many likely candidate tokens the model is choosing between           |

Via [[https://www.comet.com/site/blog/perplexity-for-llm-evaluation/][Perplexity for LLM Evaluation]]

#+begin_quote
exponentiated average log-likelihood of the predicted words in a sequence. Or,
less verbosely, perplexity is cross-entropy with the exponential function
applied
#+end_quote

***** Chain Rule Vectorization

via gemini

+(P(H\vert{}A) = \frac{P(A\vert{}H) \odot P(H)}{\sum (P(A\vert{}H) \odot P(H))}\)
+ prior probability :: \(P(H) = [P(H_1), P(H_2), \dots, P(H_k)]^T\)
+ likelihood :: \(P(A\vert{}H) = [P(A\vert{}H_1), P(A\vert{}H_2), \dots, P(A\vert{}H_k)]^T\)

+When not vectorized:+ .... (the vars around the pipe are backwards...)

\(P(A\mid B_{1},\dots ,B_{n})=\frac{P(A)\prod _{i=1}^{n}P(B_{i}\mid A)}{\sum _{j}P(A_{j})\prod _{i=1}^{n}P(B_{i}\mid A_{j})}\)

I wanted a vectorization that would reflect the lower-triangular causal matrix.
This got a bit confusing. So i needed some clarification. It seems like the
algebraic structure is simpler than I expected.

In practice, the perplexity calculation looks like this (ctrl c, ctrl v)

\(\text{PPL}_{\text{aggregated}}=\exp \left(-\frac{1}{N_{\text{total}}}\sum _{d=1}^{D}\sum _{i=1}^{t_{d}}\log p_{\theta }(x_{i,d}\mid x_{<i,d})\right)\)

****** Gemini :crypt:
:PROPERTIES:
:CRYPTKEY: David Conner <aionfork@gmail.com>
:END:

-----BEGIN PGP MESSAGE-----

hQIMAz05LBTqCkO0AQ//SaWw50DjD9Nb/GyZJ5M0qetzawMzB55Fm3GfOMh+Qmzs
uWOpMzjelWvbag0JBRSNicYzprXA7lZ9oH1bsVn0DN1WvTYglh5hMI5nQJ3l0BU6
scZu5dgehshP7iSoC87gJ3nSSr2B36Goyk289RzEGPQU8OZsWWjb8Kq2/dZAqfjH
o+uzvr9sAT3kbG2rQrx6pj5Thn1ipQbgVeYBZ/SNfZhfnThkVg8roQgqrBb/VspT
qcK/+n8yN6XpDiVD3yKu4CF2w3t7jO+ebchQrOI2dGWKlLZq0ucHNsBAUu+xY4tS
FLM6VIWocSEpMr0SN6q7xMFzE1nFVA9EJGz0uQmM+wDCyn4j4t2fZ5CmA5raNdk7
9sq19BCA7ivVIVBO6iGiTz65FsA814jLPsz07YxOEx3qbaCjhQEc4KuYyleDGC2n
SNXV34tm2bxNS3ykYeuXwdTsRiKgX/uAFluAObqG2CZqS0/I5OVP5b7f8oiPGQ1j
456hOdrC4aWZeApLbbtKx24yKezP7UagzaxLuGSKBkX5PjTGsHrOJERjpQKx7ZsC
3AEVctso+FocBjkgWZhTRbgF/H09diC/CEG+I0qdc4bkuBzIxBEUPCbpnZtefqmZ
Ob+eIcP+rNXeTqmD6tpG6mgGFxgQiA+m1es3r4LVpf3JeTuj+oxl+RFRTi+3Xb7S
agEb2VBPoucqyD/P9yJnqf/tbvmO51AoQDxkZmGftevjxappUrqTUBfmSKRuJD5I
tJCSclA9hck1iZM80yDzcz/XpxP/d1KFKqdIMiDB2HwwmZsRZJ8TJ/uIJ+pW8PS0
S6MtiuBuDdGx7TA=
=6bRT
-----END PGP MESSAGE-----
** Fine Tuning
*** Ablation

For fine-tuning, specifically, can be used to edit behavior, circumvent
restrictions, discover jailbreaks, etc.

**** Selective Caps

+ [[https://arxiv.org/html/2601.07411v1][SCALPEL: Selective Capability Ablation via Low-rank Parameter Editing for LLM]]

*** Encoding

+ Use same quantization
** Sandboxes
+ Seccomp, AppArmor, SELinux, Network Isolation, User Namespaces
+ Running any of those without some kind of pre-established service probably
  requires root or elevated permissions. With network isolation, it doesn't
  cascade.
+ At some point, it relies on strong cryptography and doesn't have a single
  human point of failure.

#+begin_quote
"once is a accident, twice is a coincidence, three times is a pattern"

This is about conditional dependencies:

\(P(\overline{a\,\&\, b\,\&\,c}) = \left(1 - a*b*c\right)\)

Individual probabilities of =a,b,c= are inconsequential w.r.t. their product.
#+end_quote

*** "Sandboxes"
**** Restricted Python

IMO, this is the "wrong box"[fn:1]. Still interesting. Then again, I don't get
anything done.

+ [[https://github.com/zopefoundation/RestrictedPython][zopefoundation/RestrictedPython]]
+ [[https://codeberg.org/sudontdoit/uv-ai-sandbox][sudontdoit/uv-ai-sandbox]]
** Frameworks

*** [[https://github.com/lexler/augmented-coding-patterns][lexler/augmented-coding-patterns]]

+ [[https://lexler.github.io/augmented-coding-patterns/][Augmented Coding Patterns]] some handy tips. There's not really a roadmap of the
  SRE/Archtecture Engineer's terrain though.

**** [[https://codeberg.org/bbaassssiiee/claudia][bbaassssiiee/claudia]]

A fork of the above. A few word changes here and it sounds a tiny bit like
scientology:

#+begin_quote
The practitioner who can recognize their own role shifts in real time is
operating at a higher +level+ thetans than the one who cannot. Claudia's job is
partly to make those shifts visible.
#+end_quote

Using theatre/dialogue creates separation/abstraction that causes LLM to engage
in dialectic with itself (and also permitting similar dialectic in your
interaction with chat-based LLM). It's super useful. It's hard to become super
attached *to the letter* of what the LLM is writing, since dialogue requires
interpretation.

That's not necessarily what's happening here in [[https://codeberg.org/bbaassssiiee/claudia/src/branch/main/documents/theatre_entree.md][claudia]]. instead, it seems to
encourage the user to ask Claude to focus on these roles -- while indirectly
encouraging the user to adopt these roles somewhat, whether they realize it or
not. It could become difficult to determine who's the agent, the actor and the
entity in control... mwahaha.


* Footnotes

[fn:1] [[id:887aa490-b6d9-4776-9ef8-57b4143f8f30][Everything is a box (Sops)]]
    - also [[id:480f561a-ee49-444f-b3f7-b0e886fb83ca][Everything is a box: (Abstractification™)]]
    - and [[id:887aa490-b6d9-4776-9ef8-57b4143f8f30][Everything is a box (Sops)]]
