:PROPERTIES:
:ID:       cea7d11c-8357-4e4f-90b3-fa8210eff796
:END:
#+title: AI

* Docs

* Resources

* Communities
+ [[https://ai.science/][AI.science]] (slack)

* Ideas
** Topology of the Hyperplane

*** Amateur Go Player Beats Top Go AI With 100% Win Rate

Sources:

+ [[The HUGE Problem with ChatGPT]]
+ [[github:HumanCompatibleAI/go_attack][HumanCompatibleAI/go_attack]]
+ [[https://arxiv.org/abs/2211.00241][Adversarial Policies Beat Superhuman Go AIs]]

So basically, the AI is not aware of the topology of the hyperplane. This is why
the strategy to beat the AI involves ... the topology (or shape) of the
arrangement of Go pieces on the board.

Since the AI algorithms for Go utilize information compression to render the
game of Go tractible, then they are unlikely to be adapted to deal with this
without being augmented with another technique -- such as the algorithm attained
by the MIT researchers themselves.

**** This "Topological perspective" also explains LLM Jailbreaks

This also explains jailbreak techniques and why it's so difficult to guard
against them. Because it's difficult to define regions of the hyperplane so that
they are "convex" for some loose definition of the term, it's also difficult to
construct an XAI policy to wall those regions off. The structure of the
hyperplane for language-based models probably moreso resembles swiss chess than
anything that can be "convexified".

That is, the regions of the hyperplane (or a LLM's state space, if I'm mincing
terminology) form a kind of labyrinth. Your interactions with it lead it down
various paths. The space represents language, conversation and interaction
state, Because of the connectedness of this space (it is Riemannian), then given
its n-dimensional holes, then there are no simple way to define XAI-based
semantic policy to prevent someone's interaction path from reaching certain
regions of the space -- not without significantly altering the behavior of the
AI.

Just like you can flip a convex function into a concave function you could
perhaps invert this behavior: simply define interaction paths starting from a
point within a boundary and limit the paths leaving that bounded
region. However, doing so will significantly alter the behavior of the AI. To
further confound this, it requires prohibitive levels of computation /and time
lag introduced from ML ops to update the LLM policies from XAI techniques./

And convexity/concavity are extremely complicated to define even in lower
n-dimensional Euclidean space (with or without the need for variational
methods). Here your topological concerns are mostly incidential to the functions
you're analyzing, not the connectedness of manifolds or the definition of
metrics to determine some arbitrary "increase/decrease." The definitions of
convexity here are based on derivation of functions or other tools -- anyways,
is a saddle point concave or convex? How about a local minima in a 9-D subspace
of an function on 11-D Euclidian space? It's totally convex in 9-D? What is it
then in 11-D? When this happens in Riemannian manifolds, it creates
wormhole-like structures: hence the "swiss" in the swiss cheese I menioned
above.

**** Thence:

[[https://te.xel.io/posts/2019-04-12-the-analytic-iching-a-novel-exegesis-for-the-age-of-data-science.html#the-algebraic-topology-of-hyperplanes][The Algebraic Topology of Hyperplanes … Donuts My Mind May Never Digest]] where I
describe the need for a "Gauss Bonnet Theorum" to analyze the structure of the
hyperplane and define such analysis as metacognition:

#+begin_quote
... reasoning about the topological features of the hyperplane corresponds to metacognition.
#+end_quote

From the bundle of crazy I wrote in 2019, [[https://te.xel.io/posts/2019-04-12-the-analytic-iching-a-novel-exegesis-for-the-age-of-data-science.html][The Analytic I Ching: A Novel Exegesis
In The Age of Data Science]].

... But then again, I'm not even allowed to exist. Or, at least, my name is not
showing up on TV or on some influencer's channels. And no, I didn't make it, but
once someone's life has been destroyed, network theory and social physics
implies that fixing it is a bit like escaping a black hole.
