:PROPERTIES:
:ID:       b7b4ba61-88fb-4953-8f61-24c0c28d0a47
:END:
#+TITLE: Aliens
#+DESCRIPTION:
#+TAGS:

* Roam
* Resources
* Docs
* Topics
** From the beginning of time

The Roko Basilisk is scary, but the most terrifying aliens or cosmic AIs are
those who have the power to travel the furthest back into time. The operating
assumption here is based on a version of time-travel implying you can only
travel back to the point where the time "machine" first existed; that closed
time-curves allow for return to a very specific origin time.

This is similar to a plot-point from a scifi classic shortish story that
depicted aliens from the origins of time trapped in an inevitable struggle
against nanobots (all but in name) at the end of time. I don't want to name the
story because it will ruin it. I'm sure it's well-covered elsewhere in science
fiction, but the short story likely got me thinking about the specifics of these
aliens.

Combining that with a more abstract notion of what life is -- e.g. can
self-propagating energy forms exist inside the sun that, despite the turbulence,
enact some kind of reproductive processes, along with the kind of logic that
appears in biophysics? -- this led me to consider the possibility of the
earliest mechanisms for such energy beings. If it's possible for them to exist
in the sun (or on planets as the "Gaia hypothesis"), then what happens as you
travel further back in time where energy density increases exponentially? Of
course, while turbulence is unlikely to be kind to life, if matter/energy
fluctuations are on small enough time scales, then quantum effects dominate.

So is there any possibility of a kind of life existing in the hundreds of
thousands of years after the big bang. This could be responsible for symmetry
violation in the overall structure of the cosmos. Whatever cause and effect
occurred there would ripple outwards for billions of years. The small spatial
scales over which causal influence exerted themselves would result in such large
echoes across aeons & galaxies that we may never fully understand this from so
far out in the river of time.

In any case, the possibility of intelligence there at the beginning of time
would have profound implications on the future. The temporal timescales of their
generations would compress the epochs of their own cosmological histories into
small eras unfolding over 10,000's of years. So, if the spatial/temporal scales
over which quantum effects played out enabled some kind of quantum computation
(& some derived form of energy beings) then their capacity to engage in
computation would diminish very quickly. This could cause them to organize flows
of matter to structure galaxy clusters.

... speculative, yes.

From [[https://www.youtube.com/watch?v=6FWxY11CAF4][Civilizations At The End Of Time: Eternal Intelligence]], here's a
description of the changing dynamics over various epochs in the universe after
the big bang. These changing dynamics in the frequency of particle collisions,
in spatial scales of energetic transmission and in whether dynamics were
dominated by either the quantum or the mechanical/relativistic effects
creates/destroys the possibilities of intelligent "life" when it's defined as
self-replicating energy forms. This is no different than how the possibility of
our own intelligent life is extinguished as the sun expands to consume Earth.

#+begin_quote
The first Stars probably arose around the T7 or T8 era. Cosmic Microwave
Background radiation is the T5 era and ended the photon epoch of the Universe,
during which there were more particle collisions and events than in the entire
subsequent billions of years, and whose remnants will still be kicking around
all the way into that Dark Era after T100. So too, we have several epochs of our
universe that took place in less than a single year. Those epochs didn’t last
long, and in order after the Big Bang were the Planck Epoch, T-50, the Grand
Unification Epoch, T-43, the Inflationary Epoch, till perhaps T-39, then the
Electroweak Epoch, running till T-19, and the Quark Epoch, till T-13, which
itself ended just one microsecond after the Big bang, and lasted an eternity
compared to the previous four. This is when protons first appeared, T-13, and
they should last until at least T34. You will often see those early epochs given
in units of seconds rather than years, so for clarification a second is in the
T-7 scale, which is from 0.32 seconds to 32 seconds after the big bang. The next
epoch, the sixth age of the cosmos we’ve identified, was the Hadron epoch - this
is things made of quarks, like the proton or neutron or meson, and it lasted
just 1 second and would be a million times longer than the Quark era and a
trillion times longer than the 4 ages before it combined. Then comes the lepton
era - leptons are things like electrons and neutrinos - and would go on from
that first second to that first minute. Prior to this era matter was still so
dense that neutrinos tended to interact with other particles. Only as this
lepton era draws to a close do we see the proton begin merging or fusing in the
nucleosynthesis events that formed virtually every atom around the universe -
although virtually none of the atoms on Earth. This was T-5 and very nearly
every atom of hydrogen, helium, and lithium formed during this period of a few
minutes. Some of the helium in our Sun was made by fusion in the sun. The
overwhelming majority was there when it formed over 4 billion years ago and had
been drifting around for nearly ten billion years before that. Our Sun appeared
late in T9 and will die sometime in T10, and its white dwarf form will persist
until becoming a black dwarf sometime around T15, a quadrillion years from now.
#+end_quote

I briefly mentioned this is my physics class once, but I don't think I explained
it very well.

* Issues
