:PROPERTIES:
:ID:       b6d2c374-bdd0-4034-a27f-c44af23c5d9e
:END:
#+TITLE: Apple
#+DESCRIPTION: Apple
#+TAGS:

* Roam
* Docs
* Resources
* Issues

* OSX
** Docs
** Docs

+ [[https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/KernelProgramming/booting/booting.html][MacOS Kernel Programming Guide]]
  - [[https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/KernelProgramming/Architecture/Architecture.html#//apple_ref/doc/uid/TP30000905-CH1g-CACDAEDC][Kernel Architecture Overview]]

** Resources
+ [[2011 MacBook Pro & OSX][updating EFI vars to disable a discrete GPU]]

* Macbook Pro 2011
** Kernel Panic Issues

It's probably bad RAM, but it's cost me an unbelievable amount of time. It
doesn't display the error unless you're in a terminal.

*** SMART Status

**** Where is the SMS (Sudden Motion Sensor)?

[[https://support.apple.com/en-us/HT201666][Mac notebooks: About the Sudden Motion Sensor]]

- SMS events are logged in smartctl as "Free Fall", which shows more than 4,000
  events ... I've dropped this laptop like twice.

**** High Load_Cycle_Count (857372)

[[https://unix.stackexchange.com/questions/504245/s-m-a-r-t-shows-high-load-cycle-count-why-and-how-to-prevent-the-number-from][S/O post]] answers that this is results from a technique Western Digital (and
other manufacturers use).

*** Testing RAM
Ram tests fine

* Macbook Pro Late 2013 (fully loaded)

Screen is broken. Go figure. The keyboard bounced -- long time ago... lesson
learned. Anyways . . . It's usable & worth salvaging, but the display damage is
refractory: gets worse, doesn't get better.

Options:

+ use as server ... but literally anything touching this makes the display
  worse, though it's boot menus are operable without it.
  - however, the unibody frame is necessary for cooling to work
+ use as scrap, buy a nearly identical MBP, same year/model -- but without the
  massive surcharge that someone would add for a fully loaded (which mine was)
  - move the logic board to the new body and just use as is.

** Issues

*** Touchpad on Guix

Sometimes it's necessary to blacklist the =usbmouse= module because it

*** AHCI SSD

So I have a 500GB SSD which is difficult to integrate into any system. (details
on [[https://forums.macrumors.com/threads/upgrading-2013-2014-macbook-pro-ssd-to-m-2-nvme.2034976/][macrumors]])

*** Linux GPU support is meh on arch

- arch briefly had the 4xx nVidia drivers ...

*** Converting the MBP into a slaptop

This computer has better hardware than most of what I'm using. Can I convert it
into a server?

Maybe: [[https://www.theverge.com/22965732/macbook-decapitation-slabtop-mod-mac-studio-event-rumor-keyboard-computer-diy][Honey, I decapitated the MacBook (Macbook 2009)]]

The article covers how to drive a headless 2009 and +the problems you encounter+
the valuable life lessons you learn along the way.

+ You will lose display/webcam on most models
+ You may lose WiFi on older models

Also:

+ You can't easily change BIOS settings if you're not running MacOS.
+ Attempting to install MacOS to do various things may be complicated if the
  hardware is in a wierd state.

I would definitely not recommend doing this to anyone else.

But .... the laptop is actually spec'd out to coordinate Spark/Kafka compute
tasks or be a K3S master node (with rigged elections) ... and ideally, if I can
use it like that, it will run hot from time to time. Also:

+ The laptop won't cool properly with the lid closed -- kinda important!
+ The laptop will generally cool better without the display AFAIK.
+ I can't reuse its 500GB NVMe SSD, since it's not exactly portable.
+ The display is broken and the liquid crystal drained from the working
  half. The display costs more than the laptop ... used. And it's unlikely to
  find one that's a exact match, even if it's late 2013.
+ I already borked a fragile WiFi antenna and I hate WiFi anyways.
+ Servers don't need webcams.

... what else could possibly go wrong?

**** TBD: Does the slaptop server work?

If it works, I know someone who wants to buy 2014/2015 macbooks with broken
displays ... since these laptops are designed with good hardware that is
well-documented, but since they're generally worthless when you need to replace
the display.

[[https://www.ifixit.com/Guide/MacBook+Pro+13-Inch+Retina+Display+Late+2013+Display+Assembly+Replacement/27666][MacBook Pro 13" Retina Display Late 2013 Display Assembly Replacement]]

#+begin_quote
Down here along X-axis, we have "fuck around."

And over here on the Y-axis, we have "find out."
#+end_quote

I kinda want to examine the Laptop's hardware state in Linux /before/ I
decapitate it and plan on ... ummm recapitating it if I gotta find out.
