:PROPERTIES:
:ID:       beafc05d-75b4-4013-8b43-9c0483a30328
:END:
#+title: Art

* Docs

... RTFM? lulz

... oh right, the manual: [[https://www.amazon.com/Artists-Handbook-Materials-Techniques-Reference/dp/0670837016][The Artist's Handbook of Materials and Techniques]]. A
little dated, but essential. There are newer resources like the Painter's
Handbook, but honestly, something a bit older gives you perspective.

** Conservation

The [[https://www.conservation-wiki.com/wiki][AIC conservation wiki]] is also essential, but more technical.

+ [[https://www.conservation-wiki.com/wiki/Paintings][painting]]
+ [[https://www.conservation-wiki.com/wiki/Book_and_Paper_Group_Wiki][books/paper]]
+ [[https://www.conservation-wiki.com/wiki/BGP_Inpainting][inpainting]]

For creating art, it's mostly only useful as adjunct information: you get
insight into the materials for product ingredients or at least the desired
properties/functions thereof.

** Pigments

*** CHOS

I have no idea why a visible-light spectroscopic database was so hard to come
by, but I couldn't find this before. I'm guessing it's because art/paint
suppliers will basically pay you /not/ to do this.

+ [[https://chsopensource.org/pigments-checker/][Pigment Checker]] includes many free resources on Raman, XRF, FTIR, and
  Reflectance Spectroscopy.
+ The [[https://chsopensource.org/download/23968/?tmstv=1700255640][Gorgias database]] contains reflectance spectroscopy data collected via the
  [[https://chsopensource.org/reflectance-spectroscopy-system/][Gorgias spectrometer]]. There are multiple links to the database.

** Color Charts

+ [[https://drawpaintacademy.com/color-charts/][Richard Schmid Color Charts]]

* Resources

This is more appropriate for art.

* Art Conservation

** Chemistry

*** Paint Consolidants

+ [[https://www.conservation-wiki.com/wiki/Paint_Consolidation][Paint Consolidation]]


* Medium

** Oil

*** Chemistry

#+begin_quote
Somehow either =org-ref= or =citar= or =org-export= should format the citekey
links ... but I need to reinforce other features first. Whenever I use this,
it's always for some passing interest.
#+end_quote

*Electrochemical Assessment of Pigments-Binding Medium Interactions in Oil Paint
Deterioration: a Case Study on Indigo and Prussian Blue*

[cite:@domenech-carbodomenech-carbo-2020-elect-asses-pigmen]

** Support

*** Metallic

**** The degradation of oil painted copper support

From 2006, but discusses the electrochemical basis for adhesion of oil paint to
metallic mediums. [cite:@pavlopoulouwatkinson-2006-degrad-oil-paint]

**** Consolidants for treatment of oil paintings on copper support

*A technical investigation of an oil painting on copper support, including a
study on consolidants for treatment.* [cite:@oliveira-2015-techn-inves-oil]

A thesis on conservation, but it covers a lot of history & chemistry.

**** Multi-spectroscopic Approach for Paintings on Metal Surfaces

*Multi-Spectroscopic Approach for the Non-invasive Characterization of Paintings
on Metal Surfaces* [cite:@albiniridolfi-2020-multi-spect-approac]

Probably details electrochemical basis for adhesion to metallic mediums (I
haven't read these)


** Pastel
*** DIY

$100 for 75 pastel pencils from a decent brand is honestly unbelievable -- and
this is about half the MSRP. That's fine, since they actually do add a lot of
value in the pigment-specific binders/stabalizers/preservatives. However, the
cheaper brands will absolutely skimp on pigment, where the decent brands mix in
organic pigments with the bundled product.

**** Art Instruction Blog

[[https://www.artinstructionblog.com/how-to-make-soft-pastels-by-hand/][How to make soft pastels by hand]] this is a more thorough, visual guide than
what's in the Artist's Handbook, etc. This requires precautions and protective
gear to handle pigments/dust. See the link for the full ingredients/process. I
would just like to print it out and compare ...

From the article via "The Art of Pastel Painting," Watson Guptill

#+begin_quote
+ Preservative Solution (PS) :: Lukewarm water: 5 quarts + 2 level teaspoons of
  sodium orthophenyl phenate
+ *Gum Tragaranth (GT)* :: use warm distilled water to encourage
#+end_quote

Note: you can substitute Gum Arabic, but I'm unsure of how this changes the
ratios in the recipe. There are other sources, including the Artist's Handbook.
Organic binders will encourage mold growth.

The concentration of their solutions.

|   | PS, fl oz | GT, tbsp (fl oz) | Ratio | Pigments                                                                  |
|---+-----------+------------------+-------+---------------------------------------------------------------------------|
| A |        48 | 2 (1)            | ~2%   | Cd Red; Cd Yellow; Alizarin                                               |
| B |         8 | 8 (4)            | ~33%  | Cerulean                                                                  |
| C |        24 | 8 (4)            | ~17%  | Precip. Chalk; Ti White; Zn White; Ultramarine; Co Blue; $Cr_2 O_3$ Green |
| D |        24 | 4 (2)            | ~8%   | Raw Sienna; Yellow Ochre; Prussian Blue; Indian Red                       |
| E |        24 | 2 (1)            | ~5%   | Burnt Umber; Raw Umber                                                    |
| F |      100% | 0 (0)            | >0%   | Burnt Sienna; Terre Verte                                                 |

IMO, Titanium white is needed in all the pastels. It stretches the other
pigments and also encourages diffuse reflections from lighting. Note you always
have to mix a ton of white for paint: that's the diffusion. Mixing premade $TiO$
paste gives you exact tints where you can control the purity of the other
pigments. You're much less likely to end up with "mud" when smudging, whereas
with organics and hues, you have to be more cautious or you'll dull the colors

Though I really don't have much experience, it's a pain to look up the pigment
info from manufacturers ... unless you buy singles. That said, DIY pastels may
lack a lot of the value added by color-specific materials/recipes.

** Pigments

*** MSDS

[[https://www.conservation-wiki.com/w/images/7/7c/H%26S_Pigment_Guide_Toxicity_Chart.pdf][Conservation Wiki: Pigment Toxicity Information]] (pigments do bad things)


* Subjects

** Portrait

*** Human Face

+ [[https://plasticsurgerykey.com/anthropometrics/][Anthropometrics]] (from plasticsurgerykey.com)
+ [[https://www.scss.tcd.ie/Rachel.McDonnell/papers/ApplicationOfGR.pdf][Application of the Golden Ration to 3D Facial Models]] (from [[https://www.scss.tcd.ie/Rachel.McDonnell/portfolio.shtml][Rachel McDonnel]])


* Misc Forms of Visual Art

** Cosplay & Costume Design
*** Links
** Tattoo Design & Body Art
*** Links
** Makeup Art
*** Links
+ [[https://youtube.com/KawaiiPateen][Kawaii Pateen]] :: eye/face makeup
** Sculpture
*** Links
** Landscape Design
*** Links
** Architecture
*** Links
** Materials Design
*** Links
