:PROPERTIES:
:ID:       38638b3e-e023-460e-9670-84776e61468e
:END:
#+title: Browser

* Chromium

* Firefox

** Topics

*** Extensions

**** Tree Style Tabs

+ Impressive project, given how modular/interoperable it is.
+ A lot of config options.

***** User Stylesheet Fix To Hide Tab Bar

The TST extensions can basically replace the tab bar. I kept looking for this
option (for TST to manage the horizontal tab bar visibility), but apparently you
[[https://www.reddit.com/r/firefox/comments/nwrtdv/comment/h1b6c62/?utm_source=share&utm_medium=web2x&context=3][just hide the tab bar]] altogether. This needs to be done on a per-installation,
per-profile basis, hence ... the notes.

And add this stylesheet to =~/.mozilla/firefox/$profile/chrome/userChrome.css=

#+begin_src css
#TabsToolbar
{
    visibility: collapse;
}
#+end_src

I really fucking hate the browser tabs UI/UX. I understand these things evolve
slowly for ... reasons. some of them good. but holy shit.

the solutions for these things are always hacky, brittle and ad hoc ... this
tabstyletree, not so much. of course, i never see anyone else use a computer, so
how am i supposed to know?

**** Debugging

The devtools are nice, but missing 5+ years of development has not been kind to
me (esp. knowing how useful the tools were then). Luckily, you can just enable
the logging in TST (and also debug, which took me a second).

Determining TST entry points was a bit complicated, but es6 modules can be
imported to eval (?) ... I would have just used breakpoints, but the issue
seemed to be in the initialization.

Not really a bug, just needed customization (to avoid unnecessary permissions: a
good thing).

***** Profiles

Isolated browser contexts can be created by using =about:profiles=

***** [[https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html][Browser Console]]

Requires enabling the [[https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html][Browser Toolbox]].

***** Extension Console

Found in [[about:debugging][about:debugging]].

The extensions may include files built which are not in the Github.

=C-M-f/b= for =forward/backward-sexp= are about as useful as you'd think they
are, so it sucks not having that kinda most of the time. You can, of course,
connect remotely to the debugger and ... well [[https://www.reddit.com/r/xkcd/comments/46w1zc/til_that_emacs_has_a_reference_to_xkcd_378_mx/][XKCD has a comic about this]].

* Nyxt
