:PROPERTIES:
:ID:       403bc47c-7255-447d-ae36-7b446382fe6b
:END:
#+TITLE: Climate Change
#+DESCRIPTION:
#+TAGS:

* Docs
* Resources
* Topics

** $CO_2$ Saturation

Given that any inaccuracy or local variation in $CO_2$'s spectral saturation
represents a large potential shift in absorbed heat, it's important to be sure.
However, it seems that scientists are just afraid to speak out. Given that the
mass, total content and total area under the earth's thermal emission spectrum
are all far higher for water than for $CO_2$, maybe we should ban
that. Regardless, any reasonable policy or advice should compare their
assumptions/recommendations to water as a litmus for ridiculousness.

We absolutely need to conduct costs/benefits analysis here. If this is urgent,
then there are opportunity costs in chasing $CO_2$. I would assume that $CO_2$
in the ocean would melt glaciers faster, but where's the visibility on that
issue? Where's the desalinization technology that gives us an interface to "boil
the oceans" and extract pollutants/acidity?

No one is even talking about realistic implementations technologies -- instead
most business endeavors here are just greenwashing. "We'll send the carbon to
the bottom of the ocean" and things like this sound an awful lot like
Scientology trying to cleanse the thetans when $CO_2$ is saturated. And if it
is, this means that _ALL_ your efforts in carbon policy are /wasted/ because
they produce diminishing returns with exponential costs. We could have focused
on real targets for global warming, but no one knows wtf is going on because GWP
is measured relative to $CO_2$.

** GWP Global Warming Potential

Any of [[file:img/refrigerant_table_June2019.pdf][these Refrigerants]] have a more serious GWP than $CO_2$, considering that
$CO_2$ effect is oversaturated at 1km. Their spectrum is not relative to the
$CO_2$ absorption spectrum whatsoever, which is why GWP is meaningless!

You must develop more accurate units even if the antifa or econut protestors
can't grok the science. That's too bad. If they cared so much, they would _read
a book_. If they were more concerned about objectivity rather than
sensationalism on social media as a hack, then maybe we could get something
done. The reason I'm angry is because the left fucks everything up and we cannot
entrust this issue to you if you're just going to fuck it up like everything
else. I don't see the conservatives taking a strong stand on this and if you use
weak measures while hiding behind censorship & cheap tricks, who's going to save
us? Yeh, not the left. You're only weakening the issue here, which makes you
inevitably vulnerable. Do I really need to remind the left how badly the fucked
up their coronavirus response? Take the capes off until you're ready to be
heroes instead of simply play-acting.

GWP in proportion to CO2 units is basically meaningless. Any singular system of
units is challenging to develop. The primary units should be relative to the
total area under the curve for theoretical thermal emission. A secondary system
of units should be used to determine how much the chemical would create a change
in this emission spectrum -- this is difficult to empirically verify, but even
worse is that it changes, so unless you're creative, your units would change.
Other systems of units should be devised, but it's impossible to determine the
actual effect a chemical would have without taking into account the atmospheric
dispersion of a chemical.

It's just unbelievable to finally really dig into the science here and realize
just how problematic the semantics are. The truth is that any time you're
dealing with simple units (particularly scalar values), you're probably in high
school and God I hope you're not in graduate school. You should be so lucky to
encounter scalar units. You need a set of standards for visualization of the
spectrum that's easy to read/interpret that forms the basis for conversations
based in fact. Such a system must not lend itself to confusion. If people cannot
understand anything other than simple scalar GWP, then I guess we need
education. Can we trust the left to not fuck that up?

*** GWP and Refrigerants

I would be far more concerned about health and environmental effects from
exposure events than about GWP when selecting refrigerants, esp. given that
cycling out equipment requires retooling industrial production and large costs
borne mostly by building owners.

It would make more sense to prioritize thermally sealed homes & buildings,
though that's somewhat decoupled from refrigerant selection and HVAC. However,
given that malfunction occurs during HVAC system stress, I do really think that
any reasonable policy/advice would take this into account. Otherwise, I'm going
to immediately assume that you're full of shit if you lack a sense of proportion
or if your models are not ranked by actual fucking impact. It's fine to
specialize in some area, but you most have a rational understanding of how your
area of expertise relates to the most critical parts of the overall system.

* Issues

* Roam
+
+ [[id:fd5d939e-480b-4800-a789-8dd0fcb347fa][HVAC]]
