:PROPERTIES:
:ID:       5ecd7027-37a7-474f-950d-021f7cf39c79
:END:
#+TITLE: Communism
#+DESCRIPTION:
#+TAGS:

* Roam
+ [[id:5cdf4cef-5ffe-4853-a9f0-dcb3e99360ca][Philosophy]]

* Docs
* Resources
* Topics
* Issues

* Maoism Marxism +2.0+

Marxism 2.0 was Leninism

** Docs
** Resources
** Topics

*** Criticism and self-criticism (Marxism–Leninism)

From [[https://www.youtube.com/watch?v=-VeZp2d7mDs][Jung Chang (Wild Swans author) - Living Through History's Largest Man-Made Famine]]

#+begin_quote
*Dwarkesh:* so let's go back to the cultural revolution one thing that I find
really interesting about you communism especially in China is the need for the
victims to then incriminate themselves to confess [... can you] explain why it
was important that the victims of these purges had to then talk about oh you
know "I'm guilty I'm complicit" why couldn't they just be ostracized?

*Jung Chang:* [... Mao] uses this as a weapon to break people. To humiliate them
and to break them. I mean so even his opponents then started to grow doubt about
their own opposition so I think that's the main thing.

I mean it I tell you it's it's not very nice I mean in China when I lived in
China I wasn't denounced but we all had to attend criticism and self-criticism
meetings.

it really is stirs up some very basic discomfort and unsettling upset feelings
if you have to criticize yourself.

not do it cynically because you have to in our days it's not you couldn't do it
cynically because nobody has reason to understand the whole thing in order to be
cynical. so you were starting with being quite sincere. it certainly breaks
people

and also it makes people turn people against each other. when people are
criticizing each other you create a lot of animosities among the people. which
is one reason why no opposition can get organized. I mean people can't don't
dare to to um talk to each other in case they were denounced I mean um in case
they were.

it's all it's very it's a psychological warfare against his own population which
is quite effective. it wasn't just a campaign against political opposition it
was literally every part of your life
#+end_quote

* Marxism +3.0+ 4.0 (in America)
** Docs
** Resources
** Topics
*** Technology

There is a usage of technological means to subvert/avoid open conflict &
resistence. This increases the temperature while the frog boils. It hijacks an
already increasing generational differential in the culture. As the cultural
influences of technologies proliferate, it widens the intergenerational rift
while also shortening the number of years separating each "cohort". The younger
cohorts do not fully/correctly develop a proper self-consciousness and cannot
properly identify as anything except members of a subculture, which itself does
not properly reciprocate the identification.

**** Dysnormalization

American culture can clearly identify/describe different eras in the latter half
of the 20th century -- the sixties/seventies/eighties/nineties. But clear
distinctions separating eras in the 21st century have basically been
obliterated. This is confusing.

I described this in my drafts as "dysnormalization" using a language of
terminology based on breaking the sound barrier. Around Mach 1, various dynamics
emerge that create fundamentally new aeronautical design concerns (e.g. vapor
cones and low-frequency/high-magnitude pressure waves).

+ Here, I model norms as "interesting points" in distributions regarding
  decisions, language, etc.
+ The perceived consensus on how these norms are shaped is particularly
  important. This facilitates epistemic reasoning on top of norms. e.g. "I
  believe I should do X because I believe other people regard X as an
  interesting point on a norm. It's thus an appropriate action that also
  effectively communicates my intent to A/B/C persons who would understand why
  choosing X over Y/Z means ..."
+ As cultural evolution accelerates, the amount of probability measure is
  diffused outwards until it basically becomes immeasurable. This means that no
  norms and no consensus are perceived almost all the time. This disrupts the
  learning process.

These distributions & norms are mostly incomputable and immeasurable. The
critical takeaways:

+ to understand there are fundamentally new dynamics emerging
+ that we need to focus on consensus where it's possible
+ that we need to augment/strengthen our ability to communicate. otherwise,
  feedback loops are too long and corrective measures can't be tuned.

Society actually has gone through periods of time where norms/culture was
significantly disrupted. So we're not in entirely new territory.
