:PROPERTIES:
:ID:       afe1b2f0-d765-4b68-85d0-2a9983fa2127
:END:
#+title: Containers
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

* Docs

* Resources

* [[https://github.com/containerd/containerd][Containerd]]
The basic implementation of the spec from OCI (Open Container Initiative)

* Docker
** Docs

[[https://docs.docker.com][docs.docker.com]]

+ [[https://docs.docker.com/get-started/06_bind_mounts/][bind mounts]]


*** Storage
+ [[https://docs.docker.com/storage/storagedriver/overlayfs-driver/][OverlayFS]] (overlay vs. overlay2)


** Resources
+ [[github:Silex/docker.el][Silex/docker.el]]
+ [[https://github.com/wagoodman/dive][wagoodman/dive]]

** Topics
*** Dockerfile
*** Docker Hub
** Issues
*** Get dockerfile from an image stored on Docker hub

The [[mrhavens/dedockify][mrhavens/dedockify]] repo can be used to recover a Dockerfile from an image
downloaded from the hub. See [[https://gcore.com/blog/reverse-engineer-docker-images-into-dockerfiles-with-dedockify/][Reverse Engineer Docker Images into Dockerfiles]]

I need to know what generated a docker image, so I can extend the
rocm/tensorflow image to include Spark dependencies while minimizing the storage
required for new images/deltas

#+begin_quote
I don't have money and I don't have unlimited storage.
#+end_quote

Most of the commands generating an image on Docker Hub are listed if you check
the "tags" page and click on [[https://hub.docker.com/layers/rocm/tensorflow/latest/images/sha256-3640f66fc0046656a694eda7680b496fa6532db658839a77d1baadb5f5eb52a6?context=explore][a digest for an image/hash]], but they're difficult to read.


* Podman

+ [[https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md][Configuring rootless containers]]

** Configuration

+ Storage: =~/.config/containers/storage.conf= or =/etc/containers/storage.conf=
  - may encounter some problems using =btrfs= with default storage locations
  - particularly, CoW/snapshots on =/var/run/containers/...= runtime
    - or btrfs might be better than ext4 ... not sure

