:PROPERTIES:
:ID:       4bbb591a-dd94-40ba-93eb-7386de2f5f4b
:END:
#+TITLE: Cooking
#+DESCRIPTION: Recipes and whatnot
#+TAGS:

This is mostly online for my own reference. Recipes can vary subtly, according
to the cookware you use, whether you're using gas or radial heat, etc, so these
work for me. I don't make these all the time, but I would like to be able to
review/print more efficiently.

The directions I note for myself will probably be sparse, but links are included
in case it's not sufficient.

* General Tips

** Temperature Control

Having one of those infrared temp sensors can help you learn faster or ensure
things reach temperature. However, you shouldn't be dependent on it. Most cooks
will just develop a feel for qualitative changes in the food, so you have to pay
attention to those.

*** For ingredients

**** Don't overcook butter

This is really important for a sauté

Law of thermodynamics as applied to chemical reactions involving LDL and HDL
(two main classes of chemicals) implies that HDL will tend to convert to LDL if
heat is not controlled. i.e. Lipids will tend to push away from each other. At
the molecular level, if there is a high-density version of a lipid and
lower-density version, the conversions will almost always be from low-density to
high-density in the presence of heat.

Try to avoid the butter browning. I'm not sure whether the brown color indicates
HDL conversion, but it doesn't really unbrown. Color changes almost always to
indicate a chemical change though, but this may be the milk-based ingredients or
cream

*** While cooking

**** Adding ingredients

Adding ingredients will almost always change the temperature, according to the
mass of ingredients added.

** Prep

*** Ingredient specific

**** Chopping Cilantro

Not processing this correcly can ruin the texture

+ [[https://www.youtube.com/watch?v=QGcGKuEoIZI][Fork method]]
+ [[https://www.youtube.com/watch?v=mDrKKXNML_8][Chopping]]

* Roam
+ Chemistry
