:PROPERTIES:
:ID:       cdf0de7c-cf7c-456f-a12c-b2496359064b
:END:
#+TITLE: Data Mux: JQ, YQ, XQ, Queries, Conversion
#+DESCRIPTION:
#+TAGS:


* JQ/YQ/XQ

** Docs

** Resources

** Topics

*** XQ

**** Working with Attributes

Specifying =[]= after =.manifest.project[]= causes document separators to be
inserted for =xq -y= output. Annoying if you're not expecting, but useful
otherwise. The =[]= is somewhat of an implicit map.

While also relevant to =jq=, this is more helpful for =xq= to =yq= conversions.
The triple-dash document separators are actually part of the YAML standard
whereas =jq= must know to parse them while maintaining escaped strings.

This first query creates a unified stream where each XML node can be treated as
separate documents, whereas the latter splats everything together. They both
lose their identity as =<project/>= nodes.

#+begin_src sh :dir (identity dc/repo-path) :results output verbatim :wrap example yaml
xq  -y '
    .manifest.project[]
    | select(."@path" != ."@name")' typescript/astro-themes.xml
#+end_src

#+RESULTS:
#+begin_example yaml
'@name': abdllahdev/nimbus-narratives
'@path': algorizr/nimbus-narratives
'@groups': blog,preact,tailwind,typescript,mdx
---
'@name': bywhitepine/astro-minimal-starter
'@path': jaydanurwin/astro-minimal-starter
'@groups': minimal
---
'@name': bywhitepine/cannonball
'@path': littlesticks/cannonball
'@groups': landing-page
---
'@name': bywhitepine/odyssey-theme
'@path': littlesticks/odyssey-theme
'@groups': featured,landing-page
---
'@name': bywhitepine/simple-blog-astro
'@path': littlesticks/simple-blog-astro
'@groups': blog,lit,mdx
---
'@name': Johnkat-Mj/agency-landing-page-astrojs
'@path': Johnkat-Mj/agencex-astro
'@groups': landing-page,tailwind
---
'@name': LaB-CH3/astrobrew
'@path': anthonylan/astrobrew
'@groups': landing-page
#+end_example

Without separators:

#+begin_src sh :dir (identity dc/repo-path) :results output verbatim :wrap example yaml
xq  -y '
    .manifest.project
    | map(select(."@path" != ."@name"))' typescript/astro-themes.xml
#+end_src

#+RESULTS:
#+begin_example yaml
- '@name': abdllahdev/nimbus-narratives
  '@path': algorizr/nimbus-narratives
  '@groups': blog,preact,tailwind,typescript,mdx
- '@name': bywhitepine/astro-minimal-starter
  '@path': jaydanurwin/astro-minimal-starter
  '@groups': minimal
- '@name': bywhitepine/cannonball
  '@path': littlesticks/cannonball
  '@groups': landing-page
- '@name': bywhitepine/odyssey-theme
  '@path': littlesticks/odyssey-theme
  '@groups': featured,landing-page
- '@name': bywhitepine/simple-blog-astro
  '@path': littlesticks/simple-blog-astro
  '@groups': blog,lit,mdx
- '@name': Johnkat-Mj/agency-landing-page-astrojs
  '@path': Johnkat-Mj/agencex-astro
  '@groups': landing-page,tailwind
- '@name': LaB-CH3/astrobrew
  '@path': anthonylan/astrobrew
  '@groups': landing-page
#+end_example



** Issues


*** XQ not attributing

If you find your self with an =xq= that just can't meaningfully convert
documents to XML, just try converting a document from XML to YAML ... you'll
find that you need to use =@= to set attributes ... maybe idk. =xq --help= does
not mention this at all.

Like this:

#+begin_example sh
echo meooow |\
  awk -f concat-yaml.awk |\
  yq -sy . |\
  yq -sy '.[] | map(select(.repoUrl))' |\
  yq -x --xml-root WOW 'map({LIKE: .title, "@MUCH": "WTF"})'
#+end_example

Yeh wow, that would've helped quite a bit.

*** ob-jq in emacs

+ results :: use =output= to reuse strings in another babel block that doesn't
  parse json. this eliminates the quoting
+ cmd-line :: use =-r= for =--raw-output= and =-j= to eliminate the trailing
  newline.
+ stdin :: an org-babel reference
+ in-file :: a file reference

#+begin_example org
#+property: header-args:jq :stdin varname :cmd-line --raw-output

the above header args are for reference but would set defaults

#+name: ffactive
#+headers: :results output silent
#+begin_src jq :stdin ffprofilesjson :cmd-line "-rj"
. | your | query
  | here | @text

# or @tsv or @csv
#+end_src
#+end_example

** Examples


* Roam
+ [[id:c99b63b3-e18f-4b4b-8424-dbbac937b596][Serialization]]
