:PROPERTIES:
:ID:       4630e006-124c-4b66-97ad-b35e9b29ae0a
:END:
#+title: Electronic Communications
#+description: (and electromagnetic radation generally)

* Roam
+ Electronics

* Docs

* Resources

* Topics

** Fourier Optics

*** Birefringence

This is the tendancy of a material's crystal lattice to promote anisotropic
optical refraction. That is, the refractive index varies according to the angle
of incidence w.r.t the crystal lattice (and inclusions inside the crystal)

The problem:

#+begin_quote
How can you correct the scattering of light so it leaves a device with most of
the power and spectrum intact?

+ ... without a magnetron or a proper amplification-based laser. the latter
  usually produces narrow spectra, unsure of former.
+ Thermal production of photons will tend to involve more scattered/disordered
  light which can
#+end_quote

So, in other words, is there a "gomboc" shape for light? i.e. no matter what the
light's starting orientation, it always results in a single orientation.

**** DLP as Digital "Birefringence"

DLP projectors seem to accomplish this "descattering" via color filters &
reflection, which produces a ton of heat.

+ Instead of redirecting the scattered light, each tiny mirror is effectively a
  pinhole (i.e. after some limited orientation of the light rays, once they hit
  the mirror, the light transmitted to the screen is only bouncing from the
  micron-scale mirror).
+ The perceived color results from mirrors switched in sync with the color
  wheel. [[https://www.projectorcentral.com/Digital-Projector-Imaging-Technologies-Explained.htm][Digital Projector Imaging Technologies Explained]].

***** Use for spectroscopy

+ If it's possible and somewhat simple, you could use DLP to create a
  spectrometer with far more potential for analysis of data, especially if it
  has multiple DMD's while still using a white light source (xenon lamp,
  probably rare? idk). If the DMD's were fitted with an LCD color filter that
  can be triggered to block specific bands of white light, this is even more
  interesting.
+ Reversal of the DLP seems possible in theory, but probably encounters signal
  integrity & magnitude issues. Reversal is not necessary to create a
  spectrometer that can scatter light of specific regions of a sample, but it's
  still interesting.
+ These techniques would need to generate an image, but one that's tuned in real
  time to cover areas of the sample. The light scattered off the sample would
  need hit the diffraction grating to spread the reflectance spectrum.

Spoiler: "Simpsons did it":

+ [[https://www.mdpi.com/2079-9292/11/13/1945][Monitoring Time-Non-Stable Surfaces Using Mobile NIR DLP Spectroscopy]]
+ [[https://opg.optica.org/ao/abstract.cfm?uri=ao-62-8-2154][Optical System Design of a DMD-SHS combined modulation interference
  spectrometer]]
+ [[https://www.nature.com/articles/s41598-021-89788-y][Compressive spectral image fusion via a single aperture high throughput
  imaging system]] (using DLP with DMD mirrors)

I had often thought about hacking my old projectors and I thought about
spectroscopy, but at some point I learned about how much design goes into
medical diagnostics and sensors, so I assumed that everything had been tried.
I'm always looking for a stupid simple design that solves a lot of problems.

Though it seems like it's being explored, there are definitely opportunities for
this technique: medical diagnostics, sensors deployed to IoT devices and sensors
used in industrial/chemical engineering contexts.

The novel factors which make these methods more practical:

+ ML for stochastic control of mirror/filter/sample actuation and for signal
  generation/modulation
+ ML for classification and availability of datasets for vector databases

Apparently, the more proper terminology:

+ Spectral coding
+ [[https://en.wikipedia.org/wiki/Computational_imaging][Computational imaging]] (see above, the "novel factors" which differentate these
  techniques from the classical imaging with some analysis)
+ [[https://en.wikipedia.org/wiki/Coded_aperture][Coded Aperture Imaging]] (if modulated), [[https://en.wikipedia.org/wiki/Super-resolution_imaging][Super-resolution imaging]] and [[https://en.wikipedia.org/wiki/Coherent_diffraction_imaging][coherent
  diffraction imaging]]
+ Compressive spectral imaging. See [[https://en.wikipedia.org/wiki/Compressed_sensing][compressed sensing]] for more detail. It
  requires the $L^0$ norm, which is interesting, but implies that the
  reconstruction is a synthesis (from the hermite polynomials, in some methods,
  which shows how orthogonal polynomials are magical). i can't really "do" this
  math, but yeh i probably could have.

=import scipy as ok; ok.wow("fisher price", 1,2,3)=

The challenge lies in collecting & collating experimental data into a kind of
vector database that produces classes that represent "spectra metatypes" which
can be composed according to the methodology at hand... sooo, it's ML Ops, where
you can expect to pay about $3M per year to collate/validate data (~20*150,000
average pay).

**** Fourier Ptychography and Characterization of Birefringence

[[https://doi.org/10.1364/OE.469377][Angularly resolved polarization microscopy for birefringent materials with
Fourier ptychography]] (doi: 10.1364/OE.469377)

I've never seen this word ptychography before. Not actually sure what it means.
I'd love to revisit this paper again soon.

** Pipe Dreams

*** Power-over-DirecTV

So I was looking at buying overpriced ESP32 boards with PoE, when I got to
thinking about how ridiculous it is to run all that cable. Then I thought about
all the background radiation my WiFi router puts out. How much of that could I
harness from spare 802.11n/ac antennae that drain into a battery. Is it enough
to trip a single diode? IDK

It'd be cool if you could charge ESP32 devices using EMF that's gradually
collected from ambient wifi signals. This sounds preposterous (it is), but you
never know (now I do).

+ [[https://blog.solidsignal.com/tutorials/can-you-measure-satellite-signal-with-a-multimeter/][Can you measure satellite signal with a multimeter?]]
+ [[https://electronics.stackexchange.com/a/382364][Expected peak-to-peak output voltage of satellite LNB]] (see the main answer)

Then I remembered this satellite dish I picked up. I was going to paint it or
something. I only planned on using the steel that came along with it ... and now
I have this dish. For context, [[https://www.youtube.com/watch?v=L8XOqrKBM5w][this guy on Hackaday built an SDR cyberdeck and used scrapped TV
dishes record signals from space satellites]]. So there is something to learn
here. There is also a video on the [[https://www.youtube.com/watch?v=bSJSktT07bo][Cyberdeck 2.0]]

Anyways, it'd be cool to try to charge a battery from one of these dishes. If
the ESP32 was connected to a battery, then you could keep it in passive mode
kinda most of the time. If you could trick your 802.11ac Wireless A into
beamforming real hard at your ESP32, then maybe you can. Who knows.

#+begin_quote
Also...

The dish had a bees' nest in it, which is probably a bit of a sad story,
considering that it doesn't look like the dish came out of the roof the way one
may prefer it to. It's a bit banged up. I'm actually imagining that these dishes
may be known for containing bees nests, which is a pretty awful problem to have
... especially if you're getting to business with your drill that vibrates the
whole thing, along with the roof it's bolted to. I really wonder whether bees
love these things because it doesn't seem like they're too easy to raid out once
they're halfway into the post.

Really, idk what happened. I just hope there wasn't a shitton of cyclomethrin
insecticide on it ... but that's because I'm paranoid, which is also why I was
wearing gloves.
#+end_quote
