:PROPERTIES:
:ID:       844c1801-23e1-4229-9447-e0e396a576f1
:END:
#+TITLE:     Email
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

+ [[id:da888d96-a444-49f7-865f-7b122c15b14e][Desktop]]

* Architecture

** Resources

+ [[https://www.youtube.com/watch?v=3xWEnAVl1Tw][Emacs: Managing Emails and Mailing Lists]]
+ [[https://emacsconf.org/2022/talks/mail/][Revisiting the anatomy of Emacs mail user agents]]

** Agents

|---------+-------------|
| Acronym | Description |
|---------+-------------|
| MUA     | User        |
| MTA     | Transfer    |
| MDA     | Delivery    |
| MSA     | Submission  |
| MRA     | Receiving   |
|---------+-------------|

** Protocols
*** SMTP

*** IMAP

*** POP3

* Clients
** Thunderbird
*** Docs
*** Resources
*** Issues
+ [[https://support.mozilla.org/en-US/questions/1261974][add a google calendar with CalDAV URL]]
  - kinda poorly documented

*** Topics

**** TODO Thunderbird Configuration (old notes from 6/15 after laptop crash)

#+begin_quote
I think there's some more to this somewhere else.
#+end_quote

Flatpak installation for GTD/Productivity apps like Thunderbird/etc.

***** Resources

+ Thunderbird [[https://support.mozilla.org/en-US/kb/keyboard-shortcuts-thunderbird][Keyboard Shortcuts]] and [[https://wiki.mozilla.org/Thunderbird:Help_Documentation:Keyboard_Shortcuts][More Keyboard Shortcuts]]

***** Migrating

+ Thunderbird uses several sqlite databases in the =.thunderbird= directory.
  - it does not appear to use much in the way of =$XDG_CONFIG_DIR=
  - instead it uses =$XDG_DATA_DIR=

****** Thunderbird

+ Main :: /flatpak/dc/.var/app/org.mozilla.Thunderbird/
  + Configs :: ./

Thunderbird flatpak state: almost everything is in =.thunderbird=

#+begin_src shell
tree -ad -L3 --prune -I cache /flatpak/dc/.var/app/org.mozilla.Thunderbird/
#+end_src

#+begin_example
.var/app/org.mozilla.Thunderbird/
├── config
│   ├── fontconfig -> /home/dc/.dotfiles/.config/fontconfig
│   ├── glib-2.0
│   │   └── settings
│   ├── gtk-3.0
│   ├── ibus
│   │   └── bus
│   └── pulse
├── data
│   ├── applications
│   └── mime
│       ├── application
│       └── packages
├── .ld.so
├── .local
│   └── statel
└── .thunderbird
    ├── 123abc45.default
    │   ├── datareporting
    │   ├── extensions
    │   ├── saved-telemetry-pings
    │   ├── security_state
    │   └── storage
    ├── 54cba321.default-default
    │   ├── calendar-data
    │   ├── chrome_debugger_profile
    │   ├── crashes
    │   ├── datareporting
    │   ├── extensions
    │   ├── ImapMail
    │   ├── Mail
    │   ├── minidumps
    │   ├── saved-telemetry-pings
    │   ├── security_state
    │   ├── settings
    │   └── storage
    ├── Crash Reports
    │   ├── events
    │   └── pending
    └── Pending Pings

#+end_example

******* .thunderbird

#+begin_src shell
tree -a -L3 --prune -I cache -P "*.sqlite" .var/app/org.mozilla.Thunderbird/.thunderbird
#+end_src

#+begin_example
.var/app/org.mozilla.Thunderbird/.thunderbird
├── 123abc45.default
│   ├── abook.sqlite
│   ├── cookies.sqlite
│   ├── history.sqlite
│   ├── permissions.sqlite
│   ├── storage
│   │   └── permanent
│   │       └── chrome
│   │           └── idb
│   │               └── 3870112724rsegmnoittet-es.sqlite
│   └── storage.sqlite
└── 54cba321.default-default
    ├── abook-1.sqlite
    ├── abook-1.v3.sqlite
    ├── abook-2.sqlite
    ├── abook-2.v3.sqlite
    ├── abook-3.sqlite
    ├── abook-3.v3.sqlite
    ├── abook.sqlite
    ├── abook.v3.sqlite
    ├── blist.sqlite
    ├── bounce-tracking-protection.sqlite
    ├── calendar-data
    │   ├── cache.sqlite
    │   ├── deleted.sqlite
    │   └── local.sqlite
    ├── chrome_debugger_profile
    │   ├── cookies.sqlite
    │   ├── favicons.sqlite
    │   ├── formhistory.sqlite
    │   ├── permissions.sqlite
    │   ├── places.sqlite
    │   ├── storage
    │   │   ├── ls-archive.sqlite
    │   │   └── permanent
    │   │       ├── chrome
    │   │       │   └── idb
    │   │       │       └── 3708121247racbdoitnebc-es.sqlite
    │   │       └── indexeddb+++fx-devtools
    │   │           └── idb
    │   │               └── 749681157eeckagrtoafsltss--cans.sqlite
    │   └── storage.sqlite
    ├── content-prefs.sqlite
    ├── cookies.sqlite
    ├── enigmail.sqlite
    ├── favicons.sqlite
    ├── formhistory.sqlite
    ├── global-messages-db.sqlite
    ├── history.sqlite
    ├── history.v3.sqlite
    ├── openpgp.sqlite
    ├── permissions.sqlite
    ├── places.sqlite
    ├── storage
    │   ├── ls-archive.sqlite
    │   └── permanent
    │       ├── chrome
    │       │   └── idb
    │       │       ├── 3708121247itracbdonebc_p.sqlite
    │       │       └── 3708121247oiracbdtnebc-es.sqlite
    │       └── indexeddb+++fx-devtools
    │           └── idb
    │               └── 749681157rtoafstleeckagss--cans.sqlite
    ├── storage.sqlite
    └── webappsstore.sqlite

#+end_example


***** Integration

+ Thunderbird + 2FA (browser access for auth flows)

****** Backups
+ Backup to an instance of syncthing?

****** Storage
+ Encryption?
+ Partition?

****** Fonts
+ can it access the !@#$ing fonts?
+ is this stable (can it be installed on a new comp without excedrin)

***** Processing Data

****** Old Mail

+ Goal for inbox: ~20,000 or less emails remaining
  + [ ] Promotions: 40,000 / 60,000
  + [ ]

******* Filters for 12+ years of Promotions (1 year at a time?)
+ [X] 2021
+ [ ] 2020
+ [ ] 2019
+ [ ] ...

****** Unsubscribes

#+begin_src html

<div dir="ltr" class="gmail_signature" data-smartmail="gmail_signature"><div dir="ltr"><div><div dir="ltr"><div><div dir="ltr"><div dir="ltr"><div dir="ltr" style="font-size:small">;;<b>&nbsp;David Conner&nbsp;</b></div><div dir="ltr" style="font-size:small">;; @dcunit3d<b>&nbsp;</b></div><div><font size="2">(</font><span style="font-size:14px;color:rgb(37,37,37);font-family:sans-serif"><span lang="el">λ</span></span><span style="color:rgb(37,37,37);font-family:sans-serif;font-size:14px">&nbsp;</span><span style="color:rgb(37,37,37);font-family:sans-serif;font-size:14px">&nbsp;</span><span style="background-color:transparent;font-size:12.8px;font-family:&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;,NotoColorEmoji,&quot;Segoe UI Symbol&quot;,&quot;Android Emoji&quot;,EmojiSymbols;color:rgb(0,0,0)"><font size="1">❤</font></span><span style="color:rgb(37,37,37);font-family:sans-serif;font-size:14px">&nbsp;</span><span style="color:rgb(37,37,37);font-family:sans-serif;font-size:14px">&nbsp;</span><span style="font-size:small"><a href="http://te.xel.io/" target="_blank">'te.xel.io</a>)</span></div></div></div></div></div></div></div></div>
<div dir="ltr" class="gmail_signature" data-smartmail="gmail_signature"><div><br></div><div dir="ltr">David Conner<br><div><br></div></div></div>

#+end_src


* Issues

** Setup

** As flatpak, japanese fonts are not included



*** These may help but didn't fix the core issue

+ Add the Japanese extension
+ Change the default fonts in preferences
+ Only some fonts are available
+ Change the settings in userChrome.css
  - this is described [[https://kb.mozillazine.org/Font_settings_in_Thunderbird#Thunderbird_user_interface][here]]
  - since this is CSS, listing the font after should allow it to fallthrough
