:PROPERTIES:
:ID:       d7cc15ac-db8c-4eff-9a1e-f6de0eefe638
:END:
#+title: File Systems


* BTRFS
:PROPERTIES:
:ID:       d8216961-cd6a-47cd-b82a-8cd67fe7190f
:END:

** Docs
+ [[https://btrfs.readthedocs.io/en/latest/][Main]]
+ [[https://github.com/btrfs/btrfs-dev-docs][Dev Docs]]

*** Maintainence
+ [[https://btrfs.readthedocs.io/en/latest/Scrub.html][Scrub]]
+ [[https://btrfs.readthedocs.io/en/latest/Resize.html][Resize]]

*** Advanced
+ [[https://btrfs.readthedocs.io/en/latest/Seeding-device.html][Seeding device]]: extend read-only FS with another that captures all writes

** Resources
+ [[https://linuxhint.com/resize_a_btrfs_filesystem/][Resizing BTRFS]]

** Topics
*** Snapshots
*** Defrag
This relates to compression and CoW, so it is relevant to SSD's

+ There is an =autodefrag= mount option.
*** Compression

** In Linux

*** In Garuda

*** In Guix

* EXTFS
:PROPERTIES:
:ID:       faa7e444-6171-4225-9220-1b7f70ce6303
:END:

** Docs

** Issues
*** Repair
+ dumpe2fs $device | grep -i superblock :: find alternate superblocks
+

* LUKS
:PROPERTIES:
:ID:       80ccbcbb-a244-418f-be86-47e8969928a5
:END:

** Docs
+ [[11. Encrypting block devices using LUKS][Red Hat: Encrypting Block Devices with Luks]]

** Topics

*** Security at rest


Don't put your secrets on a LUKS drive. Either vault, ansible-vault, pass or
some other means is much more secure.

+ Vault requires certificate deployment, but integrates nicely in k3s or K8S.
+ Ansible Vault permits retrieval of secrets GPG-encrypted at rest.

Unless you restrict the mount to a namespace accessible by your user, the second
you mount on it on a network ... well it's there. Your opinion on this I guess
depends on whether you trust your own user account and ... unless you're running
in =vty= I wouldn't.  It is strange though, how people rely on "opsec"
(i.e. don't publicly host dotfiles like what we don't see is somehow black arts)
while simultaneously defaulting to fairly WM standard configurations. The apps
aren't jailed, not that I know what that means other than zomfg ZFS.

I'm pretty sure that the lack of awareness/accountability on secure
configurations creates a fairly weak baseline by default. You can only count so
much on the network to protect you if you know how to use it & how it's
configured ... and only then if you never trust a WiFi that isn't a hassle.

It is quite a relief to trust GPG on a smartcard though.

*** LUKS2

This issue explains the LUKS2+Grub mounting process in full: [[https://issues.guix.gnu.org/55723][Full disk
encryption with grub-efi and LUKS2]]
