:PROPERTIES:
:ID:       7a4a7eea-5795-44e5-86e8-eec2afebf110
:END:
#+TITLE: GraphQL
#+DESCRIPTION:
#+TAGS:

* Roam
+ [[id:73aee8fe-b894-4bda-a9b9-c1685d3249c2][SQL]]
+ [[id:8d789c98-5e74-4bf8-9226-52fb43c5ca51][Gitforge]]

* Docs

** Lang
*** Go
**** gqlgen

[[https://gqlgen.com/][gqlgen]] and see [[https://gqlgen.com/feature-comparison/][comparison of go graphql implementations]]

+ "Schema First" for servers. generates code

** LSP

The Graphiql AUR doesn't build on arch

+ [[github:graphql/graphiql][graphql/graphiql]]
+ [[github:graphql/graphql-language-service-cli][graphql/graphql-language-service-server]]
+ [[github:graphql/graphql-language-service-cli][graphql/graphql-language-service-cli]]


* Resources

** Formats

*** Cytoscape
[[https://manual.cytoscape.org/en/stable/Supported_Network_File_Formats.html#cytoscape-js-json][Cytoscape Graph JSON]] (cyjs), a general graph/network modeling tool

Formats:

+ SIF :: simple interaction format
+ GML :: graph markup language
+ XGMML :: XML-based GML
+ SBML :: Systems Biology Markup Language
+ BioPAX :: Biological Pathways Exchange (an OWL doc)
+ GraphML :: XML-based graph format
+ CSV/XLS :: construct graph from tables describing nodes, edges, and edge-types
+ Cytoscape JSON :: see above. Docs are styleable (like XLST)
+ Cytoscape CX :: for communication between Cytoscape services


** Tools

+ [[github:dotansimha/graphql-code-generator][dotansimha/graphql-code-generator]]
  
** IDEs

+ [[https://github.com/APIs-guru/graphql-voyager][APIs-guru/graphql-voyager]] Visualization only, runs in a host [[https://github.com/APIs-guru/graphql-voyager/blob/main/example/cdn/index.html][HTML body]]
  - based on [[https://nathanrandal.com/graphql-visualizer/][NathanRSmith/graphql-visualizer]] free online schema visualization

* Topics

** IDEs


*** Voyager
:PROPERTIES:
:header_args+: :var obtmp=(or (bound-and-true-p ob@alacritty_auto) (setq ob@alacritty_auto (make-temp-file "roam-" t)))
:END:

+ Noweb only works with ~#+begin_src html :noweb yes :exports none~
+ No ~<script type=\"application/graphql\"/>~ without a webserver

The graphql folks basically made this easier than ever, which is fantastic.
However, I have tried every possible hack to load a local schema from file and
basically nothing works except serving the JSON locally.

CORS requires that it must either be a chromium webapp or that the =index.html=
is not served from =file:///=

#+begin_quote
Unsafe attempt to load URL file:///home/me/site/graphql.html from frame with URL
file:///home/me/site/graphql.html. 'file:' URLs are treated as unique security
origins.
#+end_quote

**** In HTML

#+begin_src emacs-lisp :noweb yes :exports none
(setq-local org-html-head-include-default-style nil
            org-html-head "
    <style>
      body { height: 100%; margin: 0; width: 100%; overflow: hidden; }
      #voyager { height: 100vh; }
    </style>
    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/graphql-voyager/dist/voyager.css\" />
    <script src=\"https://cdn.jsdelivr.net/npm/graphql-voyager/dist/voyager.standalone.js\"></script>")
#+end_src

#+begin_export html
<!-- <script id="graphql-schema" type="application/graphql"> -->
<div id="graphql-schema" style="width: 0px; height: 0px; visibility: false;">
#+end_export

#+name: graphqlSchema
#+headers: :results output htmlh :exports results :eval yes
#+begin_src shell :var sdl="../assets/github.json"
cat $sdl
#+end_src

#+begin_export html
</div>
<!-- </script> -->
<div id="voyager">Loading...</div>
<script type="module">
  const { voyagerIntrospectionQuery: query } = GraphQLVoyager;
  const graphqlSchema = document.getElementById('graphql-schema').textContent;
  console.log(graphqlSchema);

  // Render <Voyager /> into the body.
  GraphQLVoyager.renderVoyager(document.getElementById('voyager'), {
    graphqlSchema,
  });
  
  // const graphqlSchema = document.getElementById('graphql-schema').innerText
</script>
#+end_export

**** On Docker

~<div id="graphql-schema" style="{ width: 0px; height: 0px; visibility: false;
}"></div>~

meh, i don't want to build it (i'm so lazy. html so easy)

#+begin_src dockerfile :exports none
    # :dir (identity obtmp)
FROM node:24

WORKDIR /app

COPY ./graphql-voyager-*.tgz graphql-voyager.tgz

COPY ./example/webpack ./example/webpack

WORKDIR /app/example/webpack
RUN npm install && npm test

EXPOSE  9090
CMD ["npm", "start"]
#+end_src

** [[https://the-guild.dev/graphql/config/docs][graphql-config]]

Configs are written in json, yaml, yml, toml, ts or js files and include:

+ [[https://the-guild.dev/graphql/config/docs/user/schema][Schema]]
+ [[https://the-guild.dev/graphql/config/docs/user/documents][Documents]] (fragments)
+ Project references

See [[https://the-guild.dev/graphql/config/docs/user/usage][usage]] or the [[https://the-guild.dev/graphql/config/docs/library/load-config][library author docs]] for more info.

*** Loading Schemas

To use multiple schema files, supply a list to the =schema= key

Definitions can be loaded from environment variables using:

#+begin_src yaml
schema: ${SCHEMA_FILE:./default-schema.json}
#+end_src

And this can hit an API endpoint using =__schema= (?) with double quotes.

#+begin_src yaml
schema: ${SCHEMA_FILE:"http://localhost:4000/graphql}
#+end_src

* Issues
