:PROPERTIES:
:ID:       b6d2c374-bdd0-4034-a27f-c44af23c5d9a
:END:
#+TITLE: HP
#+DESCRIPTION: Apple
#+TAGS:

* Roam

* Docs

* Resources
+ Support

* HP 845 G7

** Docs

** Resources
+ Post on r/AMDLaptops [[https://www.reddit.com/r/AMDLaptops/comments/lg0knl/hp_elitebook_835845_g7_linux_compatibility/][HP Elitebook 835/845 G7 Linux Compatibility]]
** Linux

Runs linux great. It requires non-free firmware to install Guix. Almost zero
hardware issues so far. Even Guix enables most hardware without tweaks,

** Hardware
+ Great BIOS configurability. Some of it is a bit confusing. The laptop can be
  hardened in many ways at the BIOS level. Some of the options sound a bit
  crazy.
+ Includes a fingerprint scanner (haven't tried it)
+ Can upgrade to support 5G Wifi (afaik it's not an upgrade that is limited by
  firmware). This requires using an M2.2242 slot, which support confirmed cannot
  run an SSD :(
+ The Wifi is on an M2.2260 slot. It probably also cannot run an SSD.
+ My model includes a smart card reader. I also haven't used it, but that's
  awesome.
+ Includes a trackpad and trackpoint, like the IBM ThinkPads.
+ Same form factor as the recently discontinued HP Dev One (their linux
  hardware).
+ The main noticeable problem is the brightness of the screen. I can't really
  think of anything else. I don't really care. Getting everything else right in
  one package is way more than worth it. Buying a laptop is usually a crapshoot.

*** Keyboard

+ Escape :: swapped with =caps=
+ Ctrl_L/Ctrl_R :: After swapping function, these are both available.
+ Alt_L/Alt_R :: Right beside the spacebar.
+ Menu :: Set to =altgr=.
+ Super :: Just one of these unfortunately.

The modkey setup is flexible and mine is configured to be symmetric -- to avoid
repeititive strain, to give more options for keybinds and to prevent the
formation of habits & muscle memory. I guess I'm to misappropriating the
[[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwisx6iC59n9AhWpn4QIHbZTASYQFnoECAkQAQ&url=https%3A%2F%2Falexandertechnique.com%2F&usg=AOvVaw1Pggnk3DREPyjbHHJrkn3v][Alexander Technique]].

+ Expanded keyboard: includes delete, page up/down, home/end. The delete key can
  be remapped.
+ I'm not sure if the power key is much use for xkb, since the BIOS contains
   configuration options for it: I'm not sure whether X11 gets the events (i
   donno). That can be customized on some versions of Macbook Pro, so you get an
   extra key -- which can't be mapped to a modkey afaik.
+ The function key is between =ctrl/win=, which I mistype all the time. In BIOS,
  you can swap =fn/ctrl=. Since fn's key's combinations are handled by the
  device/firmware, it's not very useful. There are only a handful of recognized
  scan codes with it. BIOS configured whether the media keys require holding =fn=.
+ I'm not sure what keyboard layout it has.  i'm looking into configuring
  loadkeys now, which is why i'm typing this up. I've got it set to =pc105= and
  =us:altgr-intl=, with =caps:escape= and this works pretty well.
+ In the display manager, I'm loading =lv3:ralt_alt= and =lv3:menu_switch=,
  which sets up the =altgr=
+ It has a menu key which can be used as a modkey, so I can type any of the
  =us:altgr-intl= keycodes and I'm not tripping over the compose key. Accents
  are composed using =altgr= and the compose trigger.
+ =delete= could reasonably be set to a =hyper=, but I haven't figured out how
  to customize XKB this with Guix yet -- the top-level package inherits a
  private package or something. AFAIK, few window managers will recognize Hyper
  anyways. The code for Sway needs to be adapted to do so.

  Remember, before 2022, I didn't realize you could customize the firmware on
  the Kinesys style keyboards -- I never encountered who could provide that
  information or who was give a shit about configuring a keyboard. I never
  looked into them because I wanted my laptop to be portable.  Now I'm usually
  on a desktop with the laptop providing an extra two screens and an extra WM
  session in case mine needs to go down.

  This stuff is all incredibly time consuming to configure if you're not on an
  immutable OS. If you're not on Linux, the tools are non-standard and
  constantly change. I've heard good things about one Windows keyboard
  customization tool and the Mac OS tools are great. But being able to burn your
  OS to ashes and start over /exactly where you were/ ... it's priceless.

  That's /without the cloud/, which is really a ball and chain to keep you a
  customer. Ever convert from the Android religion to the iPhone religion? Yeh,
  both of them, it's like trying to start over after scientology, am I right?

** Issues
*** Bios
**** Time to enter BIOS
A bit tough to get into BIOS without extending the delay at start. It just starts booting too fast
**** Installing BIOS Updates
Probably just do it from within Windows. I'm a bit scared to update from
BIOS. TL;DR; HP replaced my motherboard for free and it's a laptop I bought
used. It was still under warranty, but holy crap.

Somehow, about three months into owning the laptop, my BIOS was bricked very
badly. I was switching between Windows & Guix Linux and something got messed
up. I tried switching back and forth, but it seemed that nothing would boot. "I
know, I'll try a BIOS update under suspicious conditions." ... yehh nothing at
that point would give the laptop a heartbeat.
