:PROPERTIES:
:ID:       fd5d939e-480b-4800-a789-8dd0fcb347fa
:END:
#+TITLE: HVAC
#+DESCRIPTION:
#+TAGS:

#+begin_quote
To be clear, I'm just documenting this as is. I don't want to blame anyone
because things like this just happen. However, /why/ something happens doesn't
matter nearly as much as /what/ happens and /how/ you deal with it.
#+end_quote

* Docs

* Resources
* Topics
* Issues

* Refrigerants

+ [[file:img/refrigerant_table_June2019.pdf][Table of Refrigerants]] From Canada With Love


** Pentafluoroethane and Difluoromethane

Our AC Unit uses either pentafluoroethane or a mixture of that and
difluoroethane. These are not thought to be that bad.

#+begin_quote
Around 2015 we had the unit replaced. My family keeps me mostly unaware of all
specifics of anything happening to or around me, so I don't know the details.
Why? When I'm not ignored/isolated, it's annoying when I have something to say,
like a "good idea" or a "question."

But we do own a building (a skating rink) that has lots of appliance
upkeep/maintainence, so it's not like they're actually clueless. My mom did draw
my attention to the sound of the coolant leaking, which I otherwise would not
have noticed.

I'm mostly angry not at any people, but at my situation. I've been in a
protracted humiliating situation where all the cascading problems are framed in
such a way that my intelligence, creativity, etc are thought of as some of my
worst qualities when they are my greatest strengths. I have no financial
independence, so any option that requires money typically also requires begging.

There is definitely something wrong with the basement, but no other person ever
visits me here in "secret phantom zone jail" ... which is pretty much a law of
the universe at this point. IT. NEVER. HAPPENS. So if there was something to
spot or something that might help, well there is no one here. No one can
determine what is normal for me or what is abnormal about my environment. So
then it becomes real hard to determine when something has changed (there's no
baseline to compare against or to track with time).
#+end_quote

*** Health Effects

/Potentially/ ataxic gait, though it's really unclear. God that would be pretty
bad if it did that. That's probably something else.

+ [[file:img/r-410a-pentafluoroethane-ataxic-gait-suppressed-respiration.pdf]]
+ file:img/r-410a-refrigerant.pdf

*** Structure

Pentafluoroethane

#+begin_src smiles :tangle no :results file :file img/smiles/pentafluoroethane.svg
FC(F)C(F)(F)F
#+end_src

#+RESULTS:
[[file:img/smiles/pentafluoroethane.svg]]

Difluoromethane

#+begin_src smiles :tangle no :results file :file img/smiles/difluoromethane.svg
FCF
#+end_src

#+RESULTS:
[[file:img/smiles/difluoromethane.svg]]

Pentafluoroethane breaks down into HF, CO2, CO and COF2, which I believe is
limited to combustion reactions. Here, the action as a coolant depends on its
thermal stability in a wide variety of vessels, pipes, pressures and
temperatures. The chemicals are /designed for stability/ and thus these
downstream products aren't worth worrying about. In other cases, maybe, but this
is the stuff forever chemicals are made of. The carbon-fluorine bond is noted as
being particularly problematic for cleanup of PFAS: see [[https://www.youtube.com/watch?v=eglcqP2qv1w&pp=ygUEcGZhcw%3D%3D][Burning Forever
Chemicals With Water]]. Whatever problematic chemical properties it has, they
will mostly stay that way, which makes it easier to deal with here actually.

This is good, since the COF2 is an analog of phosgene gas.

** Freon

Well at least we don't use this coolant, though there are worse options.

* Roam
+ [[id:4630e006-124c-4b66-97ad-b35e9b29ae0a][Electronics]]
