:PROPERTIES:
:ID:       01f7dc95-2246-4871-af7c-b9cdfc248a01
:END:
#+TITLE: Iching
#+DESCRIPTION:
#+TAGS:

* Docs
+ [[http://wengu.tartarie.com/wg/wengu.php?l=Yijing][wengu.tartarie.com]] I Ching translations in several languages, presented
  alongside the classical chinese.
  
* Resources

* Topics

* Issues

* Taixuanjing

A mid-Han dynasty successor to the I Ching, where its 81 hexagrams map to the 81
chapters of the Tao Te Ching.

** Resources

+ [[https://en.wikipedia.org/wiki/Taixuanjing][wiki]]
+ [[https://chinesenotes.com/taixuanjing/taixuanjing001.html][Chinese text]] with a verbatim translation of english to chinese
+ [[http://www.russellcottrell.com/virtualyarrowstalks/TaiXuanJing.htm][The math of the Taixuanjing]]

** Topics
*** The Taixuanjing as [[taixuanjing-as-vedic-clifford-algebra][Vedic Clifford Algebra]]

Ok, I thought this link was interesting, but suspect ... until he mentions this
Frank "Tony" Smith guy's website. See articles on [[https://www.tony5m17h.net/Ganesha.html#vedivin][Ganesha]], [[https://www.tony5m17h.net/clfpq.html][Clifford Algebras]] and
[[https://www.tony5m17h.net/ichgene6.html#TaiHsuanChing][I Ching]].

#+begin_quote
It seems to me as though Vedic divination and Tai Shuan Ching are based on the
Triality aspect of the 256-dimensional Cl(8) Clifford algebra of IFA, while I Ching is
based on the 64-dimensional Cl(6) Clifford subalgebra of the Cl(8) of IFA
#+end_quote

And whoo boy it is a gateway to my kinda crazy.

* Roam
+ [[id:2d9ee325-cce1-4492-9249-59f72416187e][Sinology]]
