:PROPERTIES:
:ID:       863b112d-c897-477f-b9ce-30cda0b5375d
:END:
#+TITLE: International Law
#+DESCRIPTION: Please return to your plane of existence.
#+TAGS:

* Roam

* Docs

* Resources

* Topics

** Concepts

*** [[https://guide-humanitarian-law.org/content/article/3/hierarchy-of-norms/][Hierarchy of Norms]]

**** Jus Cogens

#+begin_quote
International legal norms take different forms, and they may be written
or not. They include, in decreasing order of authoritativeness:

(1) jus cogens , or peremptory norms of general international law;

(2) ...
#+end_quote

Interesting and important, as =jus cogens= concerns rules/structure which at the
relevant time(s) need neither to be written nor specifically acknowledged until
relevant. The norms can vary from region to region but are supposed to supercede
local custom and describe how nations believe entities should normally interact
in international legal contexts ... this explanation is likely missing a few
pieces.

The point of Int'l Law studies is to research issues not yet covered. Eventually
these should be codified, by institutions/instruments/jurisdiction, but that
encroaches on sovereignty and enforcement requires credibility/consensus.
usually, cooperation/etc avoids the need for enforcement/proceedings. So, =jus
cogens= covers much of what hasn't been determined or formalized yet.

... as far as I understand it. It's definitely interesting.

The terms =custom=, =customary=, =norm*= and a few others start to develop facets of
abstract meaning that's really hard to bind down to specific contexts... which
usually means "i did not quite grok, but maybe a hundred more pages or so"

** Refugee Law

* Issues
