:PROPERTIES:
:ID:       cb615a46-f9df-4dd8-aa42-d5ae49af741c
:END:
#+TITLE: Krita
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:beafc05d-75b4-4013-8b43-9c0483a30328][Art]]
* Docs
* Resources
* Topics
** Configuration

*** From Dotfiles

#+begin_quote
Note, there is likely a API that a python script can hit to config some of the
ephemeral configs. I spend quite a bit of time tuning applications like this, so
it's important to be able to carry settings with me:

+ tablet mapping settings, scripts and hotkeys
+ pallettes and templates
+ configs for various types of brushes
+ krita workspaces, plugins, general keymaps

I haven't been able to touch it though.
#+end_quote

**** Issues

+ Can't save workspaces
+ Brushes reset unless restoring from a $XDG_DATA_HOME copy

**** Files

***** Config
+ Persisted with Git
+ Three files
  - kritarc
  - kritashortcutsrc
  - kritadisplayrc

Unfortunately, these files contain KDE's trademark state-information, which
makes them questionable for git.

***** Data
+ Persisted by syncthing
+ Contains:
  - brushes
  - docker/window arrangements

***** Cache
+ Ignored by syncthing
+ Contains:
  - an index that is built the first time you run krita.
  - things that should not be synced.

**** Distributions

***** Pacman

Running this will cause krita to pick up config changes in home

***** Guix

This should work ... but may cause problems depending on how the =data= and
=cache= directory get setup. I'm guessing into =.local/share=.

***** Flatpak

Flatpak may work well if your flatpaks are installed to =$HOME=, but it still
will not let you save/sync brushes to other machines (i.e. syncing the data dir)

+ Config :: $_FLATPAK_ROOT/.var/app/org.kde.krita/config
+ Data :: $_FLATPAK_ROOT/.var/app/org.kde.krita/data
+ Cache :: $_FLATPAK_ROOT/.var/app/org.kde.krita/data

The flatpak app won't easily pick up config changes. I tried linking files, but
depending on how the Flatpak accesses the files, then its permissions either
will or won't allow it to pick up config/data/cache. In the case of Krita, the
application can't readily pick up config changes, which defines the data/cache
locations.

The flatpak app doesn't seem to want to let go of
=$_FLATPAK_ROOT/.var/app/org.kde.krita/data=.

This is fine, since any configuration involving flatpak had at least 5 symlinks
(to containerize the application installations, so they work identically machine
to machine)

* Issues
