:PROPERTIES:
:ID:       5bb2016d-f38e-4a0b-9678-b024973fe1dc
:END:
#+title: Linguistics

* Docs

* Resources

* Books


* Languages


** French



*** Homophones
+ [[https://www.thoughtco.com/french-homophone-vocabulary-1371264][French Homophone Vocabulary]]
+ [[https://www.fluentu.com/blog/french/french-homophones][25 French Homophone Sets]]

** Italian



** Spanish




** Japanese



** Greek
*** Writing System
**** Minuscule (script)

* Writing Systems

** Logographic

** Phonosyllabic

** Evolution

*** Writing Tools
**** Handedness
+ when using many tools to write (pressed/cut by stylus in clay; templated
   chisel on stone), it is possible the modern conception of handedness may
   seem alien to the early literate class.
   - unless i'm missing something, it seems that cuneiform would be particularly
     easy for people to write using their non/dominant hand(s).
  - when juggling many tools, you tend to use both hands. the complexity of
    stone writing would probably make it a small group effort requiring a
    workspace set up to facillitate it.
  - the ancient egyptians seemed to obsess over the legacy of written messages
    (e.g. they would very well understand how long papyrus/etc would last versus
    stone)
    - the leaders would understand this very well and production of paper
      writing tools could be controlled to make most paper/ink inferior (making
      inferior technology in the bronze age: not a problem)
+ the phoenecians and the greeks seem to have horizontally flipped their letters
  - this would be more clear if the clay/papyrus writing samples were compared.
  - ... it may be useful if a culture's priest class mostly taught writers to
    use the less frequently dominant hand. so few people would learn to write
    anyways and were anyone who wasn't formally taught to start writing, it
    would leave a characteristic imprint and provide a basis for
    provenance/validation of writing.
    - it is also useful to distinguish writing people outside of a culture's
      center, especially once the proto-sinaitic writing system spread
      - this occured exactly around the Bronze Age collapse. it's actually
        pretty likely that a lack of control over literacy/writing was a major
        factor in preciptating the chaos.

*** Logographic To Phonosyllabic

* Sign Language

** Docs

** Resources

*** Variation/Evolution in ASL Signs

**** [[https://www.nytimes.com/interactive/2022/07/26/us/american-sign-language-changes.html][How a Visual Language Evolves as Our World Does]]

in which NYT spends +20% of the word count explaining why a gendered sign for
parents is offensive. This makes sense in some situations ... but there's less
effort spent on explaining "social privilege" which is more relevant to deaf
people. That content is instead found immediately after the "critique".

+ That's great though: if someone takes interest and isn't turned off by the
  critcal theory, then they can propagate half-formed woke ideas about
  gender-neutral signs for "parents."
+ Why bother having signs for boy/girl, man/woman or king/queen?  I'm sure
  someone can explain it to the deaf child without writing it down, right?
+ It is irrelevant to tack on political subjects like that to an expository
  interest piece about an identity group whose challenges are often
  overlooked.
+ if you would default to gender-neutral sign for mom/dad, would it be
  inconsistent if you didn't also sign birthing person? Should you invest
  wordcount programming mild unconscious biases in people with a peripheral
  interest in ASL? Who is the article about and who is it for?

Otherwise, interesting -- and I suddenly realized that I am injecting politics
... great!
