:PROPERTIES:
:ID:       5bb2016d-f38e-4a0b-9678-b024973fe1dc
:END:
#+title: Linguistics

* Docs

* Resources

* Books


* Languages


** French



*** Homophones
+ [[https://www.thoughtco.com/french-homophone-vocabulary-1371264][French Homophone Vocabulary]]
+ [[https://www.fluentu.com/blog/french/french-homophones][25 French Homophone Sets]]

** Italian



** Spanish




** Japanese



** Greek
*** Writing System
**** Minuscule (script)

* Writing Systems

** Logographic

** Phonosyllabic

** Evolution

*** Writing Tools
**** Handedness
+ when using many tools to write (pressed/cut by stylus in clay; templated
   chisel on stone), it is possible the modern conception of handedness may
   seem alien to the early literate class.
   - unless i'm missing something, it seems that cuneiform would be particularly
     easy for people to write using their non/dominant hand(s).
  - when juggling many tools, you tend to use both hands. the complexity of
    stone writing would probably make it a small group effort requiring a
    workspace set up to facillitate it.
  - the ancient egyptians seemed to obsess over the legacy of written messages
    (e.g. they would very well understand how long papyrus/etc would last versus
    stone)
    - the leaders would understand this very well and production of paper
      writing tools could be controlled to make most paper/ink inferior (making
      inferior technology in the bronze age: not a problem)
+ the phoenecians and the greeks seem to have horizontally flipped their letters
  - this would be more clear if the clay/papyrus writing samples were compared.
  - ... it may be useful if a culture's priest class mostly taught writers to
    use the less frequently dominant hand. so few people would learn to write
    anyways and were anyone who wasn't formally taught to start writing, it
    would leave a characteristic imprint and provide a basis for
    provenance/validation of writing.
    - it is also useful to distinguish writing people outside of a culture's
      center, especially once the proto-sinaitic writing system spread
      - this occured exactly around the Bronze Age collapse. it's actually
        pretty likely that a lack of control over literacy/writing was a major
        factor in preciptating the chaos.

*** Logographic To Phonosyllabic
