:PROPERTIES:
:ID:       0c10bf9a-650a-4f6a-8add-a4ca09b964e1
:END:
#+TITLE: Maths: Discrete
#+DESCRIPTION: The Shapes of Clouds and Stuff
#+TAGS:

Hmmm, I'm not sure why this topic didn't exist. Maybe I intended to place
"Discrete Math" in the "Maths: Computational" topic.

* Roam
+ [[id:a24b12f8-b3e3-4f66-9a5c-f29b715e1506][Math]]

* Docs
+ [[wikipedia:Discrete_mathematics][wikipedia:Discrete_mathematics]]


* Resources

** Lectures
*** Simon's Institute

+ [[https://www.youtube.com/playlist?list=PLgKuh-lKre12YBy6mn8k8spPp19F-V8K9][Algorithmic Spectral Graph Theory Boot Camp]] (2015)


* Graph Theory



** Computational

*** Algorithms

**** [[https://www.youtube.com/watch?v=WA6b7EFbN8I][104 Native Graph Algorithms in Rust (NODES2022)]]

See: [[https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa29ZTkZWYTdCNklhU3o1Zjd2Uk9NOFJoOUlVQXxBQ3Jtc0tuSWxlbEhQUkc2bXVYVDRZeEhFeDdtZDlucDUybDhDT00yT3RsZ0szRTlmUC1XOFdOQ08xU2JOOW1TMHRNclhsTEtMVjBlV014MnJSa2gyei1YUmtKZlNIR1NuS3NKSkVnblRqTjY4aEx3Si12Ml8wcw&q=https%3A%2F%2Fdist.neo4j.com%2Fnodes-20202-slides%2F104%2520Native%2520Graph%2520Algorithms%2520in%2520Rust%2520-%2520NODES2022%2520EMEA%2520Advanced%25209%2520-%2520Martin%2520Junghanns%252C%2520Paul%2520Horn.pdf&v=WA6b7EFbN8I][Slides]] and [[github:neo4j-labs/graph][neo4j-labs/graph]]

Code for a server in the graph library response in =Arrow Flight= allowing
clients to stream graphs to/from the server, which may be created/modified there

* Set Theory

* References

* Group Theory

** Terminology

+ [[https://en.wikipedia.org/wiki/Presentation_of_a_group#Examples][Presentation]]: specification of group or subgroup using
  - a set =S= of generators (to fully expand into the sub/group)
  - a set =R= of relations

From wiki on [[https://en.wikipedia.org/wiki/Equivalence_class][Equivalence Class]].

#+begin_quote
The set of all equivalence classes in $X$ with respect to an equivalence
relation $R$ is denoted as $X / R$ and is called $X modulo R$ (or the _quotient
set_ of $X$ by $R$).[3]

The surjective map $x\mapsto [x]$ from $X$ onto $X/R$ which maps each element to
its equivalence class, is called the _canonical surjection_, or the _canonical
projection_.

Every element of an equivalence class "*characterizes*" the class, and *may be used
to represent it*. When such an element is chosen, it is called a representative
of the class.

The choice of a representative in each class _defines an injection_ from $X/R$ to
$X$. Since its composition with the canonical surjection is the identity of $X /
R$ such an injection is called a _section_, when using the terminology of category
theory.
#+end_quote

I've known what these are since discrete math in 2005... but it's been difficult
to find concise definitions of the quotient. Or i basically thought it was
essentially that, but reading definitions would leave me somewhat confused.
Resolving ambiguity indicates intelligence. I'm pretty good at that ... being
stuck with unresolved ambiguity just generates a bunch aggregate garbage in your
head. It's like malicious pedagogy (autodydacts should not be isolated).

** Permutations

+ Symmetric Group (group of all permutation groups, which are thus subgroups)
+ [[https://docs.gap-system.org/doc/ref/chap39.html][GAP: Groups]] (nothing much makes sense without args to the =Group()= constructor)
+ [[https://mathworld.wolfram.com/GroupOrbit.html][Group Orbit]]
  + [[https://docs.gap-system.org/doc/ref/chap43.html#X85D769FF85545AAB][GAP: Natural Action]]
+ [[https://docs.gap-system.org/doc/ref/chap46.html#X7EAD57C97EBF7E67][GAP: Polycyclic Groups]]
  + [[https://docs.gap-system.org/doc/ref/chap43.html#X7C2406B97E057196][Randomized methods for permutation groups]] conveys how practical computation
    is and "where stabalizer chains are required"

#+begin_quote
If $M = {1, 2, ..., n}$ then $Sym(M)$ is usually denoted by $S_n$, and may be
called the symmetric group on $n$ _letters_.
#+end_quote

I didn't think of "letters", "alphabets", "words" and "sentences" (predicate
relations) as semantically indicating what are fundamentally group-theoretic
objects. Those appear everywhere & take me awhile to bootstrap when reading a
paper. Seeing them as objects primarily defined via groups -- instead of only
secondarily/incidentally having those properties, obviously -- would reduce that
bootstrap time.

*** Software

So i don't have to draw aimlessly on graph paper forever.

+ Permuta: Python
+ GAP: PatternClass
+ Combinatorial Specification Searcher: Python
+ PermCode is a Java lib with GUI

*** Patterns & Density

**** In ML and Training

[[https://arxiv.org/abs/2603.21373][PLR: Placket-Luce for Reordering In-Context Learning Examples]]

Relies on statistical assumptions about convexity (? density) on a statistical
manifold for the PL distribution Testing specific permutations can lead to
convergence faster than you'd expect. See [[https://doi.org/10.37236/8234][Limit Densities of Patterns in
Permutation Inflations]] ... which i barely understand but i've found permutations
are apparently kinda important

Some of the notation resembles definitions for KL divergence. idk why.

***** Grid Classes

Useful abstraction for permutations with a visual representation. They're known
to have rational generating functions (because of the parameters of the matrix)

+ [[https://ajc.maths.uq.edu.au/pdf/58/ajc_v58_p027.pdf][Inflations Of Geometric Grid Classes]] probably start here
+ [[https://arxiv.org/abs/1108.6319][Geometric grid classes of permutations]]

From [[https://arxiv.org/abs/1202.1833][Inflations of Geometric Grid Classes of Permutations]]

#+begin_quote
As mentioned earlier, there are uncountably many classes with growth rate κ
which give rise to uncountably many different generating functions. Hence there
are permutation classes of growth rate κ with nonrational, nonalgebraic, and
even nonholonomic generating functions, so that the final result above is best
possible.
#+end_quote

The high-level important takeaway: there are nice permutation classes and evil
permutation classes

***** Permutation Inflation

[[https://doi.org/10.1016/j.jcta.2017.09.004][Characterising inflations of monotone grid classes of permutations]], a good
overview & explainer for WTF is signified by the terse notation... It's really
not that hard ... to cite a trivial example. Accounting for all possible corner
cases & counterexamples to rules seems pretty devious.

** Galois

** Modular Forms

*** Hecke Operators

[[Calculating decomposition matrices of Hecke algebras][GAP package: hecke]]

**** [[https://doi.org/10.1016/j.aim.2024.109828][Hecke operators on topological modular forms]]

Interesting because of reference to Seshat, egyptian goddess of labyrinths, who
uses knotted ropes to explore a maze (backtracking).

[[https://dspace.library.uu.nl/items/02862473-23e3-4f6f-8f49-f027b64bddd2][Stable Operations & Topological Modular Forms]] a full text.

* Combinatorics
** Series
*** Catalan

**** Relationship to $\pi$

[[https://www.researchgate.net/publication/278730648_DERIVING_FORSYTH-GLAISHER_TYPE_SERIES_FOR_AND_CATALAN'S_CONSTANT_BY_AN_ELEMENTARY_METHOD][Deriving Forsyth-Glaisher Type Series For And Catalan's Constant By An
Elementary Method]] via [[Https://math.stackexchange.com/questions/3053715/relationship-between-catalans-constant-and-pi][Relationship between Catalan's constant and π]]

I once heard about this, but it was always so difficult to find, as is the
connection between Andre's Theorem ("euler numbers") and $\pi$.

* Simplicial Complex


** Nerves

*** On Hypergraphs

[[https://arxiv.org/abs/2409.18310v2][A survey of simplicial, relative, and chain complex homology theories for
hypergraphs]] contains the elusive woild "nerves on hypergraphs in their natural
habitat" ... Actual examples of nerves, hypergraphs and their dual
transformations
* Matroids

** Resources
*** Polymake and =topaz=
polymake is the C/C++ library/framework and =topaz= is a perl-based shell. there
are some tools for wrapping jupyter/python

+ =topaz= allows you to visualize various objects from combinatorics
  - simplicial complices, hasse diagrams, lattices, matroids
  - looks pretty useful for querying analyzing these objects or checking
    exceptions/understanding, but idk whether =topaz= is meant for enumerating and
    validation.



*** Python

[[https://github.com/gmou3/matroid-database/tree/main][gmou3/matroid-database]] This is a python wrapper around a database of
revlex-encoded matroids. Can't access the original database though, but the
=.txt.xz= files include the data.

#+begin_example python
from matroid_database import *

for m in all_matroids_revlex(5, 2): print(m)
# **********
# 0*********
# 0****0****
# 00*0**0***
# 000*******
# 000******0
# 0000**0***
# 0000**0**0
# 00000*00**
# 000000****
# 0000000***
# 00000000**
# 000000000*
#+end_example

So anyways, I'd need to relate those to vector matroids.

*** Julia
**** Oscar.jl

Matroids

+ [[https://docs.oscar-system.org/stable/Combinatorics/matroids/#matroid_hex-Tuple{Matroid][matroid_hex(M::Matroid) and matroid_from_hex(M::Matroid)]]
+ [[https://github.com/oscar-system/Oscar.jl/blob/master/src/Combinatorics/Matroids/properties.jl#L961-L1013][revlex_basis_encoding]] and others, including orderings and distnace between
  isomorphic matroids

There's a ton of stuff available, but it comes with some caveats, mainly a need
to quantize to reasonable rational or integer representations. It's meant more
for computer algebra. Working with its types/modules requires in-depth knowledge
of implementations/constraints maybe unless your work is silo'd to singular
domains.

[[https://github.com/oscar-system/Oscar.jl/blob/d4d55120132283fe478dbaf0142477739a999500/.devcontainer/devcontainer.json#L4][devcontainer]] using [[https://github.com/julia-vscode/julia-devcontainer/pkgs/container/julia-devcontainer][ghcr.io/julia-vscode/julia-devcontainer]] which redirects to
[[https://github.com/JuliaLang/devcontainer-features][JuliaLang/devcontainer-features]] and [[https://github.com/JuliaLang/devcontainer-templates][JuliaLang/devcontainer-templates]]

If you have an AMD GPU and you see the words "mini conda" just give up.
