:PROPERTIES:
:ID:       a0ef7bfe-1587-4fec-ac87-f7dda5dc0d24
:END:
#+TITLE: Maths: Foundations
#+DESCRIPTION: The Shapes of Clouds and Stuff
#+TAGS:

#+LATEX_HEADER_EXTRA: \usepackage{amsfonts}

# ... nope
# +LATEX_HEADER_EXTRA: \usepackage[Cyrrilic]{amsfonts}

# T1 is already provided by org-export and these invocations will `concat|uniq`
#+LATEX_HEADER_EXTRA: \usepackage[T2A]{fontenc}
#+LATEX_HEADER_EXTRA: \usepackage[utf8]{inputenc}
#+LATEX_HEADER_EXTRA: \usepackage[russian]{babel}
# +LATEX_HEADER_EXTRA: \substitutefont{T2A}{\familydefault}{NotoSerif-LF}

* Roam
+ [[id:a24b12f8-b3e3-4f66-9a5c-f29b715e1506][Math]]
+ [[id:a0ef7bfe-1587-4fec-ac87-f7dda5dc0d22][Maths: Category Theory]]
+ Set theory
+ Type theory

* Docs
+ [[wikipedia:Foundations_of_mathematics][wikipedia:Foundations_of_mathematics]]

* Logicism

** Docs

+ [[https://en.wikipedia.org/wiki/Logicism][Logicism]] (main [[https://en.wikipedia.org/wiki/Logicism][wiki]])

** Topics

*** Abductive Logic

**** Questions

***** Induction of Function To Explain Logical Relations

See also my zettle on [[id:45b0ba21-fb20-44dc-9ee9-c4fed32acbde][On Fallibalism, Peirce and Combinators]]

While mentioning "abductive logic" to the average plebian is perhaps a risky
endeavor, this setup should clarify what I mean:

Imagine there is some $f(X)$ in function space for some $X$ whose size $0 <
\left( N = |X| \right) < \infty$ is perhaps variable, but
finite...[fn:formatting] Thus if $N=3$ Then we basically have some $x_i$ with
three values, such that it acts like $x$, $y$, and $z$ -- we can't confuse the
plebs.

Now, imagine some function =Ñ= that outputs pseudorandom bits.

****** TODO finish connecting abductive logic to komolgorov complexity

Consider X where N is infinite. Some subset $X\prime \subset X$ of size $0 <
\left( M = |X\prime| \right) < \infty$ is known.

+ the truth table for some finite subset of X is known, but is not /immediately/
  sufficient for determining the structure of some $f(X)$ /whose output is
  known/
+ whether boolean values of $x_i$ are able to be determined (can the be measured
  or queried?) potentially sets up variations of the problem. However, /because/
  there are infinite parameters, you cannot check them all in finite time.
+ these may be rank-ordered by importance ... as you do to lower (or lift?)
  kernel algorithms down to finite dimensions so they are computable. this is
  not a kernel alg, but boolean values for $X_i$ could be probability
  measures. Even neural nets are capable of boolean logic.




* References

* Footnotes
[fn:formatting] The LaTeX definition of size is needed because plebs are
involved and may even be writing this sentence at this very moment. It's hard
for me to know when sufficient detail is sufficient because I can't assumptions
about knowledge of my readership. Thus, I either describe with too much detail
_or_ seemingly inconsistent detail _or_ only the detail that I need (if I
believe that I'm the only reader the writing consequentially affects). There
fore ... I would argue that most academics don't understand the most essential
parts of their own disciplines. They memorize and copy, but it requires so much
effort and difficulty that they forget that academia isn't the only way to learn
or to know.
