:PROPERTIES:
:ID:       a0ef7bfe-1587-4fec-ac87-f7dda5dc0d28
:END:
#+TITLE: Maths: Topology
#+DESCRIPTION: The Shapes of Clouds and Stuff
#+TAGS:

* Roam
+ [[id:a24b12f8-b3e3-4f66-9a5c-f29b715e1506][Math]]

* Docs
+ [[wikipedia:Topology][wikipedia:Topology]]

* Curves

** Parameterization

*** Frenet/Darboux

+ [[https://en.wikipedia.org/wiki/Principal_curvature#Classification_of_points_on_a_surface][Classification of points on a surface]]

The [[https://en.wikipedia.org/wiki/Frenet%E2%80%93Serret_formulas][Frenet frame]] describes the motion along a curve using the tangent, normal
and binormal vectors to establish a local reference frame. This could be used to
classify curves into a typology based on their appearance with less regard for
the system of equations used to generate the curves given Euclidean parameters.

The [[https://en.wikipedia.org/wiki/Darboux_frame][Darboux frame]] is the analogy of the Frenet frame applied to surfaces.

**** Typology of curves in art.

+ You can project n-dimensional curves described by Frenet frames down onto 2d
  in many ways resulting in lots of variation.
+ Following similar logic, any curve you draw is a projection from the
  configuation space describing your anatomical motion down onto the 2d surface
  of the paper (loosely, since friction/etc need to be taken into account). This
  is an overly complicated way of looking at things ... but still, not every
  curve is possible when drawn using human anatomy.

* References
