:PROPERTIES:
:ID:       0c10bf9a-650a-4f6a-8add-a4ca09b964e1
:END:
#+TITLE: Maths: Discrete
#+DESCRIPTION: The Shapes of Clouds and Stuff
#+TAGS:

Hmmm, I'm not sure why this topic didn't exist. Maybe I intended to place
"Discrete Math" in the "Maths: Computational" topic.

* Roam
+ [[id:a24b12f8-b3e3-4f66-9a5c-f29b715e1506][Math]]

* Docs
+ [[wikipedia:Discrete_mathematics][wikipedia:Discrete_mathematics]]


* Resources

** Lectures
*** Simon's Institute

+ [[https://www.youtube.com/playlist?list=PLgKuh-lKre12YBy6mn8k8spPp19F-V8K9][Algorithmic Spectral Graph Theory Boot Camp]] (2015)


* Graph Theory



** Computational

*** Algorithms

**** [[https://www.youtube.com/watch?v=WA6b7EFbN8I][104 Native Graph Algorithms in Rust (NODES2022)]]

See: [[https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa29ZTkZWYTdCNklhU3o1Zjd2Uk9NOFJoOUlVQXxBQ3Jtc0tuSWxlbEhQUkc2bXVYVDRZeEhFeDdtZDlucDUybDhDT00yT3RsZ0szRTlmUC1XOFdOQ08xU2JOOW1TMHRNclhsTEtMVjBlV014MnJSa2gyei1YUmtKZlNIR1NuS3NKSkVnblRqTjY4aEx3Si12Ml8wcw&q=https%3A%2F%2Fdist.neo4j.com%2Fnodes-20202-slides%2F104%2520Native%2520Graph%2520Algorithms%2520in%2520Rust%2520-%2520NODES2022%2520EMEA%2520Advanced%25209%2520-%2520Martin%2520Junghanns%252C%2520Paul%2520Horn.pdf&v=WA6b7EFbN8I][Slides]] and [[github:neo4j-labs/graph][neo4j-labs/graph]]

Code for a server in the graph library response in =Arrow Flight= allowing
clients to stream graphs to/from the server, which may be created/modified there

* Set Theory

* References


* Matroids

** Resources
*** Polymake and =topaz=
polymake is the C/C++ library/framework and =topaz= is a perl-based shell. there
are some tools for wrapping jupyter/python

+ =topaz= allows you to visualize various objects from combinatorics
  - simplicial complices, hasse diagrams, lattices, matroids
  - looks pretty useful for querying analyzing these objects or checking
    exceptions/understanding, but idk whether =topaz= is meant for enumerating and
    validation.



*** Python

[[https://github.com/gmou3/matroid-database/tree/main][gmou3/matroid-database]] This is a python wrapper around a database of
revlex-encoded matroids. Can't access the original database though, but the
=.txt.xz= files include the data.

#+begin_example python
from matroid_database import *

for m in all_matroids_revlex(5, 2): print(m)
# **********
# 0*********
# 0****0****
# 00*0**0***
# 000*******
# 000******0
# 0000**0***
# 0000**0**0
# 00000*00**
# 000000****
# 0000000***
# 00000000**
# 000000000*
#+end_example

So anyways, I'd need to relate those to vector matroids.

*** Julia
**** Oscar.jl

Matroids

+ [[https://docs.oscar-system.org/stable/Combinatorics/matroids/#matroid_hex-Tuple{Matroid][matroid_hex(M::Matroid) and matroid_from_hex(M::Matroid)]]
+ [[https://github.com/oscar-system/Oscar.jl/blob/master/src/Combinatorics/Matroids/properties.jl#L961-L1013][revlex_basis_encoding]] and others, including orderings and distnace between
  isomorphic matroids

There's a ton of stuff available, but it comes with some caveats, mainly a need
to quantize to reasonable rational or integer representations. It's meant more
for computer algebra. Working with its types/modules requires in-depth knowledge
of implementations/constraints maybe unless your work is silo'd to singular
domains.

[[https://github.com/oscar-system/Oscar.jl/blob/d4d55120132283fe478dbaf0142477739a999500/.devcontainer/devcontainer.json#L4][devcontainer]] using [[https://github.com/julia-vscode/julia-devcontainer/pkgs/container/julia-devcontainer][ghcr.io/julia-vscode/julia-devcontainer]] which redirects to
[[https://github.com/JuliaLang/devcontainer-features][JuliaLang/devcontainer-features]] and [[https://github.com/JuliaLang/devcontainer-templates][JuliaLang/devcontainer-templates]]

If you have an AMD GPU and you see the words "mini conda" just give up.
