:PROPERTIES:
:ID:       a0ef7bfe-1587-4fec-ac87-f7dda5dc0d20
:END:
#+TITLE: Maths: Algebra
#+DESCRIPTION: The Shapes of Clouds and Stuff
#+TAGS:

* Roam

+ [[id:a24b12f8-b3e3-4f66-9a5c-f29b715e1506][Math]]

* Docs

+ [[wikipedia:Algebra][wikipedia:Algebra]]

* Hodge Conjecture

** OpenAI Publications

*** [[https://github.com/openai/math/tree/main/preprints/The-rational-Hodge-conjecture-for-products-of-K3-surfaces-October-4-2026][The Rational Hodge Conjecture For Products Of K3 Surfaces]]

The proof relies on "Factor Categories", which _seem_ to be tools for "factoring"
tensors while exposing their projection maps as objects than can be enumerated
combinatorially. The proof asserts that it needs to establish something as a
perfect category (i think, from a factor category). If my low-resolution
intuition is correct, this would prove that higher-dimensional projection maps
preserve properties when certain dimensions are "factored out" (or maybe in the
other direction: they build up to that).

At some point, it needs "hamiltonians" to perturb, which naturally correspond to
"symplectic manifolds" -- these objects basically correspond to "phase space."
The phase space of what? No idea really. I'd imagine that you want to examine a
position in phase space while perturbing it to ensure preservation of local
properties.

+ [[https://github.com/manjunath5496/ML-Lectures/blob/main/pdfs/2010-the-hopf-algebra-of-mobius-intervals.pdf][2010 The Hopf Algebra Of Mobius Intervals]] recommended by NCatLab for
  explaining factor categories.

**** Factor Categories and Perfect Categories

[[https://arxiv.org/abs/1003.5492v2][Perfect category-graded algebras]] explains perfect category (or it would
probably maybe...)

#+begin_quote
An abelian category C is called perfect if every object of C has a *projective
cover* (see Section 2). The existence of projective covers for every object
guarantees the existence of minimal projective resolutions for every object in
the category.

The category C is called semi-perfect if every finitely generated object has a
projective cover (... in construction of a pre-thing)
#+end_quote

[[https://arxiv.org/abs/2209.09679v2][An introduction to model categories with examples]] introduces factor categories
to build up to "model categories".

**** Complex Surfaces

I don't necessarily understand /where/ the complex plane of K3 comes from, but not
everything has non-complex solutions. I wonder how this connects to _degenerate
product spaces_ -- the _need_ for them, where they arise.

#+begin_quote
Degenerate product spaces arise when modeling problems where umm you can prove
that naive altruism is sadly insufficient. e.g. when tuning the coefficients of
utility function where it's applications can be expressed in terms of a
dot-product:

+ There are some combinations of parameters that you can increase which interact
  to nullify their effects.
+ Things like: government spends more money, but somehow people get more poor

For dot products to match certain properties, then complex numbers or objects
like them are necessary.

Usually where such models go wrong: they assume linearity or isolation (society,
economy, interactions are part of a "system in a box"). The math for ML with
Complex Tensors is too challenging. Only physicists go there. Never data
scientists or AI researchers. (can't find a link to a youtube that's like the
only example)
#+end_quote

Kind of a tangent, but products with complex numbers end up "adding together" in
ways that cancel out the magnitudes of other arguments.

* Linear Algebra

** Resources

+ [[http://www.cs.cornell.edu/~tomf/notes/cs421-cheat-sheet.pdf][CS 421 Cheatsheet (Thomas Finley)]]

** Determinant

The determinant is profound

*** Minors and Cofactors

#+begin_src python
    from numpy import *
    from numpy import linalg

    m = [[ 1,  3, 10], [ 2,  4, -1], [ 3,  5, 17]]
    mm = transpose(m)

    print(f`{det(m)} == `{det(mm)}`
#+end_src

the determinants are equal (at least for invertible matrices). this is
entirely intrinsic to how:

+ relationships established between values at matrix indices
+ end up supplying parameters to the summed n-1 determinants

that is, there is there is some painful algebra for transforming
variables from the full expansion of n-dimensional \(det(M^{T})\) to
the full expansion of \(det(M^{T})\). Notice that for the argument of
the \(det(M^{T})\), all its values \(m^{T}_ij == m_ji\). So this is a
set of algebraic relations that hold purely based on the arrangement
of numbers in a grid (when it's interpreted to represent a linear
system)

this isn't the only algrebraic statement where equality holds. it's
apparently true for every minor of the matrix.

#+begin_src python
  import numpy as np
  from numpy import linalg

  m = [[ 1,  3, 10], [ 2,  4, -1], [ 3,  5, 17]]
  mm = np.transpose(m)

  for row in np.arange(np.size(m,0)):

  # for row in np.arange(np.size(m,0)):
  #   list(map(lambda mat: np.split(mat,[row]), [m,mm]). 
  #     map(lambda mat: (np.concatenate(mat, [0]))))

  # how about a list for your map that returns mappable listables
  #list(map(lambda n:
  #  list(map(lambda mat:
  #    (stack(mat,[0],*split(mat,[n]))), [m,mm])), arange(1, size(m,0))))

#+end_src

#+RESULTS:
* Tensor Algebra

** Factorization

+ [[https://www.tcrwebsite.org/volumes/1700003/la/v4_pdf/LA-04][Deconstructing Hedonic Experiences Using Tensor Factorization]] (not even a
  joke)

*** De Lathauwer

These have a good level of detail and nice/concise summaries.

**** arXiv: 1607.01668

[[https://arxiv.org/abs/1607.01668][Tensor Decomposition for Signal Processing and Machine Learning]]

**** arXiv: 1403.4462

[[https://arXiv.org/abs/1403.4462][Tensor DecompositionS for Signal Processing Applications]]

From Two-way to Multiway Component Analysis


** With Discrete

*** With Trees

**** TODO Noter: [[https://arxiv.org/abs/1703.10252][Linguistic Matrix Theory]]

+ arXiv: 1703.10252
+ Interesting approach to linguistic data: "Physicists do ML; hold their beers."

#+begin_quote
I found this /while trying to stay positive/semidefinite/ looking for examples
of random matrices, maybe specifying tensors -- that was a joke btw: can I just
nudge non-invertable matrices until i get one that fits a set? does the
statistical mechanics mulligan apply? probably not. i'm thinking "matrices with
norm 1" and add in some representation theory
#+end_quote

***** TODO Noter: [[https://arXiv.org/abs/2202.06829v2][Permutation invariant matrix statistics and computational language tasks]]

+ arXiv: 2202.06829v2 (shares two authors with Linguistic Matrix Theory)

**** TODO Noter: [[doi:10.4230/LIPIcs.FSTTCS.2019.44][The Tree-Generative Capacity of Combinatorial Categorial Grammars]] :noter:

doi: 10.4230/LIPIcs.FSTTCS.2019.44

+ CCG's are used to model grammar.
+ alphabet is a finite set of symbols


+ There aren't tensors here. It would be good to learn how/where such a
  structure (similar to Linguistic Ran

*** With Networks

**** TODO Noter: [[doi:10.1109/TNSE.2015.2419133][Algorithmic Renormalization for Network Dynamics]]

doi: 10.1109/TNSE.2015.2419133

+ Describes rules for a HK system (Hegselmann-Krause), then generalizes the
  relations between agents using the $\Phi_{i,j}$. This is effectively a
  function for each =i,j= which returns the adjacency matrix for agents in the
  simulation.
+ the example with robotics & delauney triangulation doesn't prove that a
  first-order theory of reals is necessary to bundle into $\Phi_{i,j}$ many
  logical statements about =HK-system=
+ the system(s) on p3 were impractical (the complexity is the challenge here).

but it does get interesting on p4, as it combines elements from:

+ physics: p4+ phase-space. also, to renormalize and rescale requires some
  attempt at a conservation of measure, even for these systems
+ chaos theory & equilibrium (or lack thereof)
+ hyperbolic geometry grounded in a shared "unit cube" that also must
  necessarily provide paths for traversal where agents may be connected.
+ functions and sequences on the graph (using the graph as domain)
+ again, the letter/alphabet, word, sentence abstractions make an appearance
+ mixed timescales: this shows up everywhere. nowhere do you have continuity if
  it runs on a computer.

  This reminds me of some of the WebGL social physics simulations that I wanted
  to build.


* References
