:PROPERTIES:
:ID:       1fc69994-e9e7-44dc-99e5-22f8e10533be
:END:
#+TITLE:     Matlab
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

* Docs

** [[https://www.mathworks.com/help/matlab/matlab-environment-control.html?s_tid=CRUX_lftnav][System Commands]]

+ [[https://www.mathworks.com/help/matlab/matlab_external/access-and-modify-settings.html][Access and modify settings]]

* Resources

* Issues

** Linux GPU: AMD OpenGL

+ The problem: matlab ships its own basic c++ libs (everything is self-contained).
  - Then your system graphics (build & kernel integration) isn't ... . . .
    something.
+ Ubuntu addresses this with a [[https://psychtoolbox.discourse.group/t/up-to-date-hardware-recommendations/3351/5][magical matlab-support package]] and a dpkg update
  - i haven't really gotten the arch package to install cleanly, but the
    =matlab-support= package should indicate what needs to be done (manually) to
    fix the problem one real good time before you =pacman Syu= and blow
    everything away.
    - it will ... probably? ... still run after that?
      - but probably with software rendering: long lag times for graphics

** Installing

*** On Arch

[[https://unix.stackexchange.com/questions/636463/how-to-install-aur-package-in-home-directory][This post]] describes installing a makepkg's contents to an alternate directory

#+begin_src sh

# Set this to `true` to do a partial install, otherwise install all products.
_partialinstall=true
# Example list of products for a partial install. Check the README for details.
_products=(
  "MATLAB"
  "Simulink"
  "Bioinformatics_Toolbox"
  "Control_System_Toolbox"
  "Curve_Fitting_Toolbox"
  "Deep_Learning_Toolbox"
  "Econometrics_Toolbox"
  "Financial_Instruments_Toolbox"
  "Financial_Toolbox"
  "Instrument_Control_Toolbox"
  "MATLAB_Coder"
  "MATLAB_Compiler"
  "MATLAB_Report_Generator"
  "Optimization_ Toolbox"
  "Partial_Differential_Equation_Toolbox"
  "Reinforcement_Learning_Toolbox"
  "Robotics_System_Toolbox"
  "Simulink_3D_Animation"
  "Simulink_Check"
  "Simulink_Code_Inspector"
  "Simulink_Coder"
  "Simulink Control_Design"
  "Simulink_Test"
  "Statistics_and_Machine_Learning_Toolbox"
  "Symbolic_Math_Toolbox"
  "Wavelet_Toolbox"
)

# Motor_Control_Blockset, Mixed_Signal_Blockset, Powertrain_Blockset, SoC_Blockset, Vehicle_Dynamics_Blockset
# DSP_System_Toolbox, Signal_Processing_Toolbox
# RF_Blockset, RF_PCB_Toolbox, RF_Toolbox
# SimEvent
# Simscape, Simscape_Battery, Simscape_Driveline, Simscape_Electrical, Simscape_Fluids, Simscape_Multibody
# Simulink_3D_Animation, Simulink_Control_Design, Simulink_Design_Optimization, Simulink_PLC_Coder

#+end_src

*** On Guix

It's ... not worth trying lol

** Issues

*** Update License

For my existing installation:

+ Find the jre in =$MATLAB_ROOT/R2022a/sys/java/jre/glnxa64=
+ Check license details, potentially copy a new license

Then, run this script and that should be it (no recursive lib64 patch necessary)

#+begin_src sh
# system java: /usr/lib/jvm/java-8-openjdk/jre/
MATLAB_JAVA=$MATLAB_HOME/R2022a/sys/java/jre/glnxa64/jre
$MATLAB_HOME/R2022a/bin/activate_matlab.sh \
    -javadir $MATLAB_JAVA
#+end_src

*** Tempfiles on linux when /tmp is on another filesystem

According to a [[https://www.mathworks.com/matlabcentral/answers/1798895-invalid-cross-device-link-18-when-saving-a-file-on-arch-linux?s_tid=prof_contriblnk][mathworks post]], matlab's temp directory can be set from within
the app, fixing this terribly annoying problem.

#+begin_src matlab :eval no :tangle (file-name-concat (getenv "MATLAB_HOME") "resettemp.m"))
clear all
tempdir
setenv('TMPDIR','$MATLAB_HOME/tmp')
clear all
tempdir
#+end_src

*** Matlab and AMD

**** [[https://blogs.mathworks.com/matlab/2022/07/13/linear-algebra-in-matlab-trying-out-amds-aocl/][Linear Algebra in MATLAB: Trying out AMD’s AOCL]]
+ [[https://www.mathworks.com/matlabcentral/answers/1672304-how-can-i-use-the-blas-and-lapack-implementations-included-in-amd-optimizing-cpu-libraries-aocl-wi?s_tid=srchtitle][mathworks solution describing setup]]
+ Requires [[https://developer.amd.com/amd-aocl/][AMD Optimizing CPU Libraries]]
  - [[https://aur.archlinux.org/packages/aocl-aocl][amd-aocl]] and [[https://aur.archlinux.org/packages/aocl-gcc][amd-gcc]] on AUR
  - [[https://developer.amd.com/wp-content/resources/AOCL_User%20Guide_2.2.pdf][AOCL User Guide]] from AMD

**** AMD GPU

*** Loading Matlab

#+begin_src toml :eval no :tangle no
#!/bin/sh
if [ "${MATLAB_INTEL_OVERRIDE}" = "yes" ] ; then
    # exec env MESA_LOADER_DRIVER_OVERRIDE=i965 GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop;
    env MESA_LOADER_DRIVER_OVERRIDE=i965 GTK_PATH=/usr/lib/gtk-2.0 progl matlab -desktop "$@"
else
    exec env GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop "$@"
    # env GTK_PATH=/usr/lib/gtk-2.0 progl matlab -desktop;
fi
#+end_src

* Topics

Official matlab examples in =$MATLAB_HOME/R2022a/examples= (linked from project)

** Dotfiles

Installing on Arch may be tough if you want a customized install, multiple
versions, etc. Also, it can be somewhat difficult to edit the included packages
after you install

Install on Guix if you like a Nightmare mode challenge (may be impossible
actually). It's okay though. Their federal funding bought you a flatpak (not).
Actually, their support for linux is not really so bad, if you don't mind a
deb/rpm distribution.

Lots of tweaks and security checks like matlab installer is broken if =/bin/pwd=
doesn't exist

+ it accounts for legacy_unix and BSD and 8 levels of links (for continuous
  integration?)
+ ... and i think it checks for modifications (it does)
+ i tried strace and gdb/disassembly ... nothing
+ the zip file also doesn't unpack correctly

*** Old Dotfiles Setup

Completing the Arch package install is only necessary if you want it installed
via Pacman. It requires =libxcrypt-compat= and =freetype=

#+begin_src sh :tangle .config/sh/profile.d/matlab.sh :shebang #!/bin/sh
#alias matlab=
export MATLAB_HOME=/flatpak/matlab
#export MATLAB_HOME=$_LANG/matlab
export MATLAB_VERSION=R2022a
export MATLAB_ARCH=glnxa64
export MATLAB_PATH=$MATLAB_HOME/$MATLAB_VERSION/bin
export MATLAB_JAVA=$MATLAB_HOME/$MATLAB_VERSION/sys/java/jre/glnxa64/jre

export PATH=$MATLAB_PATH:$PATH

function matlab_open() {
    if [ "${MATLAB_INTEL_OVERRIDE}" = "yes" ] ; then
        # exec env MESA_LOADER_DRIVER_OVERRIDE=i965 GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop;
        env MESA_LOADER_DRIVER_OVERRIDE=i965 GTK_PATH=/usr/lib/gtk-2.0 progl matlab -desktop;
    else
        # exec env GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop;
        env GTK_PATH=/usr/lib/gtk-2.0 progl matlab -desktop;
    fi
}

function matlab_open_mesa() {
    if [ "${MATLAB_INTEL_OVERRIDE}" = "yes" ] ; then
        # exec env MESA_LOADER_DRIVER_OVERRIDE=i965 GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop;
        env MESA_LOADER_DRIVER_OVERRIDE=i965 GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop;
    else
        # exec env GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop;
        env GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop;
    fi
}
#+end_src

Start with this =mlab= script or preferably a =.desktop= file

#+begin_src sh
#!/bin/sh
if [ "${MATLAB_INTEL_OVERRIDE}" = "yes" ] ; then
    # i965 is a thing i do not have ... maybe one day, it'll come up in trivia
    # exec env MESA_LOADER_DRIVER_OVERRIDE=i965 GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop;
    env MESA_LOADER_DRIVER_OVERRIDE=amdgpu-pro-libgl GTK_PATH=/usr/lib/gtk-2.0 progl matlab -desktop "$@"
else
    # just always use opengl because why not
    progl env GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop "$@"
    # exec env GTK_PATH=/usr/lib/gtk-2.0 TMPDIR=$MATLAB_HOME/tmp matlab -desktop "$@"
    # env GTK_PATH=/usr/lib/gtk-2.0 progl matlab -desktop;
fi

#+end_src


** Physics

+ [[https://www.mathworks.com/help/symbolic/modeling-the-velocity-of-a-paratrooper.html?searchHighlight=physics&s_tid=srchtitle_physics_1][Unit Conversions in Physics]]

*** [[yt:][Simulation the motion of a pendulum]]

  =openExample('symbolic/SimulateThePhysicsOfAPendulumsPeriodicSwingExample')=
** Engineering

+ [[https://www.mathworks.com/help/sps/ug/torque-motor-parameterization.html][Torque Motor Parameterization]]
+ [[https://www.mathworks.com/help/sps/ug/motor-torque-speed-curves.html?searchHighlight=motor%20torque&s_tid=srchtitle_motor%20torque_1][Motor Torque-Speed Curves]]

** Geometric Algebra

+ [[https://www.mathworks.com/matlabcentral/fileexchange/39288-dual-quaternion-toolbox?s_tid=srchtitle][Dual Quaternions]] (library)
  - examples compute the forward kinematics of a robot arm

** Preferences

The settings directory =~/.matlab= can be linked.

Matlab won't expand the settings into that directory until you navigate through
all the sub/panes in preferences (and hit apply?)

*** Schemer

[[github:scottclowe/matlab-schemer][Matlab Schemer]] allows you to load themes like Monokai

This doesn't work on my system bc calls like:

#+begin_src matlab
com.mathworks.services.Prefs.getColorPref(backupVal{1})
#+end_src

Until I get matlab to build with java support (not risking it!), i just setup a
hotkey to KDE's "Invert Window Color" function.

*** API Access

Use =getpref/setpref= or use the [[https://www.mathworks.com/help/matlab/matlab-environment-control.html?s_tid=CRUX_lftnav][settings]] function to get a reference, like this:

#+begin_src matlab
% this makes it easier to navigate the pref groups
s = settings;
s.matlab

s.matlab.editor.language.matlab.comments.MaxWidth

s.matlab.editor.language.matlab.comments.MaxWidth.TemporaryValue = 80;
s.matlab.editor.language.matlab.comments.MaxWidth
#+end_src


**** [[https://www.mathworks.com/help/matlab/ref/matlab.colors-settings.html][Color Settings]]
