:PROPERTIES:
:ID:       1fc69994-e9e7-44dc-99e5-22f8e10533be
:END:
#+TITLE:     Matlab
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

* Docs

** [[https://www.mathworks.com/help/matlab/matlab-environment-control.html?s_tid=CRUX_lftnav][System Commands]]

+ [[https://www.mathworks.com/help/matlab/matlab_external/access-and-modify-settings.html][Access and modify settings]]

* Resources

* Issues

** Linux GPU: AMD OpenGL

+ The problem: matlab ships its own basic c++ libs (everything is self-contained).
  - Then your system graphics (build & kernel integration) isn't ... . . .
    something.
+ Ubuntu addresses this with a [[https://psychtoolbox.discourse.group/t/up-to-date-hardware-recommendations/3351/5][magical matlab-support package]] and a dpkg update
  - i haven't really gotten the arch package to install cleanly, but the
    =matlab-support= package should indicate what needs to be done (manually) to
    fix the problem one real good time before you =pacman Syu= and blow
    everything away.
    - it will ... probably? ... still run after that?
      - but probably with software rendering: long lag times for graphics


** Installing

*** On Arch

[[https://unix.stackexchange.com/questions/636463/how-to-install-aur-package-in-home-directory][This post]] describes installing a makepkg's contents to an alternate directory

#+begin_src sh

# Set this to `true` to do a partial install, otherwise install all products.
_partialinstall=true
# Example list of products for a partial install. Check the README for details.
_products=(
  "MATLAB"
  "Simulink"
  "Bioinformatics_Toolbox"
  "Control_System_Toolbox"
  "Curve_Fitting_Toolbox"
  "Deep_Learning_Toolbox"
  "Econometrics_Toolbox"
  "Financial_Instruments_Toolbox"
  "Financial_Toolbox"
  "Instrument_Control_Toolbox"
  "MATLAB_Coder"
  "MATLAB_Compiler"
  "MATLAB_Report_Generator"
  "Optimization_ Toolbox"
  "Partial_Differential_Equation_Toolbox"
  "Reinforcement_Learning_Toolbox"
  "Robotics_System_Toolbox"
  "Simulink_3D_Animation"
  "Simulink_Check"
  "Simulink_Code_Inspector"
  "Simulink_Coder"
  "Simulink Control_Design"
  "Simulink_Test"
  "Statistics_and_Machine_Learning_Toolbox"
  "Symbolic_Math_Toolbox"
  "Wavelet_Toolbox"
)

#+end_src

*** On Guix

It's ... not worth trying lol

** Issues

*** Tempfiles on linux when /tmp is on another filesystem

According to a [[https://www.mathworks.com/matlabcentral/answers/1798895-invalid-cross-device-link-18-when-saving-a-file-on-arch-linux?s_tid=prof_contriblnk][mathworks post]], matlab's temp directory can be set from within
the app, fixing this terribly annoying problem.

#+begin_src matlab :eval no :tangle (file-name-concat (getenv "MATLAB_HOME") "resettemp.m"))
clear all
tempdir
setenv('TMPDIR','$MATLAB_HOME/tmp')
clear all
tempdir
#+end_src

*** Matlab and AMD

**** [[https://blogs.mathworks.com/matlab/2022/07/13/linear-algebra-in-matlab-trying-out-amds-aocl/][Linear Algebra in MATLAB: Trying out AMD’s AOCL]]
+ [[https://www.mathworks.com/matlabcentral/answers/1672304-how-can-i-use-the-blas-and-lapack-implementations-included-in-amd-optimizing-cpu-libraries-aocl-wi?s_tid=srchtitle][mathworks solution describing setup]]
+ Requires [[https://developer.amd.com/amd-aocl/][AMD Optimizing CPU Libraries]]
  - [[https://aur.archlinux.org/packages/aocl-aocl][amd-aocl]] and [[https://aur.archlinux.org/packages/aocl-gcc][amd-gcc]] on AUR
  - [[https://developer.amd.com/wp-content/resources/AOCL_User%20Guide_2.2.pdf][AOCL User Guide]] from AMD

**** AMD GPU

*** Loading Matlab

#+begin_src toml :eval no :tangle no
#!/bin/sh
if [ "${MATLAB_INTEL_OVERRIDE}" = "yes" ] ; then
    # exec env MESA_LOADER_DRIVER_OVERRIDE=i965 GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop;
    env MESA_LOADER_DRIVER_OVERRIDE=i965 GTK_PATH=/usr/lib/gtk-2.0 progl matlab -desktop "$@"
else
    exec env GTK_PATH=/usr/lib/gtk-2.0 matlab -desktop "$@"
    # env GTK_PATH=/usr/lib/gtk-2.0 progl matlab -desktop;
fi
#+end_src

** Preferences

The settings directory =~/.matlab= can be linked.

Matlab won't expand the settings into that directory until you navigate through
all the sub/panes in preferences (and hit apply?)

*** Schemer

[[github:scottclowe/matlab-schemer][Matlab Schemer]] allows you to load themes like Monokai

This doesn't work on my system bc calls like:

#+begin_src matlab
com.mathworks.services.Prefs.getColorPref(backupVal{1})
#+end_src

Until I get matlab to build with java support (not risking it!), i just setup a
hotkey to KDE's "Invert Window Color" function.

*** API Access

Use =getpref/setpref= or use the [[https://www.mathworks.com/help/matlab/matlab-environment-control.html?s_tid=CRUX_lftnav][settings]] function to get a reference, like this:

#+begin_src matlab
% this makes it easier to navigate the pref groups
s = settings;
s.matlab

s.matlab.editor.language.matlab.comments.MaxWidth

s.matlab.editor.language.matlab.comments.MaxWidth.TemporaryValue = 80;
s.matlab.editor.language.matlab.comments.MaxWidth
#+end_src


**** [[https://www.mathworks.com/help/matlab/ref/matlab.colors-settings.html][Color Settings]]
