:PROPERTIES:
:ID:       ef2ad591-9e40-4011-9c91-3942462ecb58
:END:
#+title: Medicine
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

* Docs

* Resources

* Topics
** Ophthamology

*** Cataracts

... which ones look like what? (these are bilateral)

+ [[https://www.sciencedirect.com/science/article/pii/S2451993621001183][Unilateral implantation of a new non-diffractive extended range-of-vision IOL
  in a young patient with Curschmann-Steinert Myotonic Dystrophy]] "using a Halo &
  Glare simulator ... . . . patient reported a /starburst/ type of halo, the size
  was 40 and the intensity 50.""
+ [[https://www.surveyophthalmol.com/action/showPdf?pii=S0039-6257%2816%2930105-9][Drug-induced corneal epithelial changes]] A good overview on many types/causes
  of visual artifacts, including rainbow halos. Oh, and Thorazine causes similar
  effects. Great.
+ [[https://pmc.ncbi.nlm.nih.gov/articles/PMC9422984/][Ocular Features and Clinical Approach to Cataract and Corneal Refractive
  Surgery in Patients with Myotonic Dystrophy]] CTC is "Due to elevated calcium in
  the crystalline lens leading to protein breakdown."

DM1/DM2, specifically.

+ [[https://www.academia.edu/download/109910776/epi-2020-032820240102-1-dyqlo1.pdf][DNA methylation at the DMPK gene locus is associated with cognitive functions in
myotonic dystrophy type]] The epigenetic concepts in this article are pretty
trivial, but no one ever really cared about that.

#+begin_quote
My feet keep glitching, specifically when i'm applying this Lamisil to treat the
athletes foot I got during the summer while dealing with fucking "noseeums" in
the garage no one would ever help me clean. I feel like DM1 would be the least
of my problems, especially if I don't have it ... and obviously I have no idea.

I haven't had a person I could trust to bring with me to a doctor in over 10
years. And I wouldn't have reported these symptoms to my doctor. The main issue
there is that, while I had real health insurance, my family pushed me away from
going and I would be yelled at when I asked for money to cover a copay, while
being belittled at other times for having someone else pay for my health
insurance. Anyways, fewer appointments, less confidence in going: this means
there's very little data. That wouldn't be super useful here anyways ... but if
my career (and psyche) hadn't gotten fucked in the ass, I'm pretty sure I
would've had 23andme... who knows if they'd disclose it to me? IDK. IDFK
anything because I am alienated from every possible thing I could ever
participate in.

Probably immature to assume much, but thank god the tests are simple. There's no
reason for my family to play epistemic games here, right? So I can just have
information about myself? No one wanted me diagnosed with Aspberger's because it
wasn't a detrimental enough diagnosis. Maybe listen to a family member and don't
attempt to preemptively cut that person out of your kids' lives to later shut
them away while the kids go to college.
#+end_quote

* Regulation

** Docs
*** AI/ML
+ [[https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-aiml-enabled-medical-devices][Artificial Intelligence and Machine Learning (AI/ML)-Enabled Medical Devices]]
+ [[https://www.fda.gov/medical-devices/premarket-submissions-selecting-and-preparing-correct-submission/de-novo-classification-request][De Novo Classification Request]]

** Resources
*** AI/ML
+ [[https://www.natlawreview.com/article/fda-announces-first-ever-aiml-medical-device-draft-guidance][FDA Announces First-Ever AI/ML Medical Device Draft Guidance]] (2023/04/06)

* Roam

