:PROPERTIES:
:ID:       ef2ad591-9e40-4011-9c91-3942462ecb58
:END:
#+title: Medicine
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

* Docs

* Resources

* Topics
** Ophthamology

*** Cataracts

... which ones look like what? (these are bilateral)

+ [[https://www.sciencedirect.com/science/article/pii/S2451993621001183][Unilateral implantation of a new non-diffractive extended range-of-vision IOL
  in a young patient with Curschmann-Steinert Myotonic Dystrophy]] "using a Halo &
  Glare simulator ... . . . patient reported a /starburst/ type of halo, the size
  was 40 and the intensity 50.""
+ [[https://www.surveyophthalmol.com/action/showPdf?pii=S0039-6257%2816%2930105-9][Drug-induced corneal epithelial changes]] A good overview on many types/causes
  of visual artifacts, including rainbow halos. Oh, and Thorazine causes similar
  effects. Great.
+ [[https://pmc.ncbi.nlm.nih.gov/articles/PMC9422984/][Ocular Features and Clinical Approach to Cataract and Corneal Refractive
  Surgery in Patients with Myotonic Dystrophy]] CTC is "Due to elevated calcium in
  the crystalline lens leading to protein breakdown."

DM1/DM2, specifically.

+ [[https://www.academia.edu/download/109910776/epi-2020-032820240102-1-dyqlo1.pdf][DNA methylation at the DMPK gene locus is associated with cognitive functions in
myotonic dystrophy type]] The epigenetic concepts in this article are pretty
trivial, but no one ever really cared about that.

I guess I can't explain how I would get the autosomal dominant gene, but that's
not the only cause. It's more likely that these are idiopathic symptoms of mixed
origin -- via supplements, dehydration, adrenal fatigue, exposure to chemicals
causing rainbow halos. There is a fairly good match, but almost nothing
impairing kinesthetics, except idk gait. I've complained about something making
"ligaments/tendons" weaker.

There are glitches that seem to be caused by the [[https://en.wikipedia.org/wiki/Reflex_arc][somatic reflex arc]], which
occasionally leaves muscles in a contracted state. When it happens in
hands/feet, it can result in brief pain. I thought this was possibly downstream
from ion concentration fluctations (either in body or muscle), since it seems to
be related to delayed phases of parts of action potentials. I thought this would
be related to kidney issues (something like adrenal fatigue, ACTH and/or
mineralocorticoids), since ion concentrations can destabalize with gradual loss
of functionality. But it's basically impossible to deduce anything /concrete/
without a decent record of tests.

It also irritates me that I've been unable to socialize with people who'd
gradually satiate hobbies involving neurology/etc. It's ridiculous. I needed to
learn this stuff earlier. I continually encounter issues where, if I had just
made more progress at various points, that I may have avoided so many otherwise
easy to spot things:

- signs of dehydration to act as cues, since I'm taking many supplements. not
  doing so can damage kidneys, thus leading to complex systems medicine dynamics
  that are hard to read.
- patterns of deductive logic to determine things like: is it really my food? is
  it really inflammation from gluten? is it really gut-inflammation for corn
  oils? is it really sodium fluctuation?

But it requires continual education on the same specific topics for months,
otherwise, you forget everything you learn. i.e. I've forgotten everything I've
learned from taking "Drugs in the Brain" on Coursera. It's fucking unbelievable
how society fucking neutered the shit out of my life.

* Regulation

** Docs
*** AI/ML
+ [[https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-aiml-enabled-medical-devices][Artificial Intelligence and Machine Learning (AI/ML)-Enabled Medical Devices]]
+ [[https://www.fda.gov/medical-devices/premarket-submissions-selecting-and-preparing-correct-submission/de-novo-classification-request][De Novo Classification Request]]

** Resources
*** AI/ML
+ [[https://www.natlawreview.com/article/fda-announces-first-ever-aiml-medical-device-draft-guidance][FDA Announces First-Ever AI/ML Medical Device Draft Guidance]] (2023/04/06)

* Roam

