:PROPERTIES:
:ID:       676fa714-05d2-4422-b23e-1a97637ff161
:END:
#+TITLE: NASA
#+DESCRIPTION: space stuff
#+TAGS:

* Roam
* Docs
* Resources

** Data

Other Data Sources in [[id:8f853c3f-a42c-4d43-8015-a41313fe2d9b][Astronomy]].

+ [[https://science.data.nasa.gov/astrophysics-data/][Astrophysics Data]]
+ [[https://nlsp.nasa.gov/explore/][NLSP]] (Nasa Life Sciences Project): [[https://nlsp.nasa.gov/view/lsdapub/lsda_experiment/50256716-9cec-5390-abb1-893df24cc3f8][1961 Orbital Chimpanzee Flights]]
+ [[https://visualization.genelab.nasa.gov/data/][NASA Genelab]] (not really what I'm looking for)

*** Metadata
**** [[https://www.sti.nasa.gov/nasa-thesaurus/#.XKttRUN7lZI][NASA Thesaurus]]

This comes in several formats: RDF/SKOS, RDF/OWL. It's [[id:bb8bbe7c-6d49-4088-9161-2ae2edb4abd6][ontological data]]. There
are also PDF's that overview the datat ([[https://www.sti.nasa.gov/docs/thesaurus/thesaurus-vol-1.pdf][volume 1]]). When you want to link things
by category (e.g. the topic nodes in these org roam notes), it's useful to base
it on something authoritative or something you believe is widely used to link
other data/sets. When there's consensus on these ontological categorizations
... ummmm you end up renaming things a lot less.

*** PDS
+ [[https://nasa-pds.github.io/pds-api/guides/search/tutorials.html#sample-jupyterlab-notebooks-python][PDS Tutorials/Cookbooks]]
  - [[https://nasa-pds.github.io/pds-api/guides/search/cookbook.html][Search API Cookbook]]
+ [[https://github.com/NASA-PDS/pds-api-notebook/][PDS API Jupyter Notebook]]
  - [[https://github.com/NASA-PDS/search-api-notebook/blob/aa8d1c9d094879bc582719222901536fc0261e3f/notebooks/geo/DEM_MapVisualization.ipynb#L30][DEM_MapVisualization.ipynb]] uses [[https://github.com/nasa-pds/pds-view][nasa-pds/pds-view]]
+ [[https://github.com/NASA-PDS/pds4-graph/blob/main/notebooks/PDS4.ipynb][NASA-PDS/pds4-graph]] connect to SparQL database to analyze RDF data for
  datasets associated to research/publications
  - [[https://nasa-pds.github.io/pds4-information-model/index.html][Information Model]]: This is processed into a ontological database [[https://protege.stanford.edu/][Protogé]]
    which facilitates validation & extrapolation. From here, RDF is generated &
    disseminated.
    - See [[https://pdfs.semanticscholar.org/bac3/5f45bc439435fd8df9e52e0546940043fb79.pdf][protogé document management]]


**** Side Trek

From the [[https://nasa-pds.github.io/pds4-information-model/index.html][PDS4 Information Model]] page

#+begin_quote
This enables data dictionary and ontology designers to share the _changing
morphology_ of the PDS model with the rest of the PDS nodes and the general
public.
#+end_quote

When I write crazy shit no one understands on my LinkedIn banner.

#+begin_quote
Epistemology with _Morphological Operators_ and Spectral Methods; Self-Styled
Philosopher
#+end_quote

it's there bc it's prominently positioned and I consider this idea to be
incredibly important -- at least to me, though obviously other people alread
understand the same ideas. No matter how crazy that wording looks now, it has to
be at the root of how AI will optimize knowledge expansion.

I'm literally talking about the boundary of an expanding/contracting knowledge
graph and using methods that look for similarity in the spectral content of
changes to the graph's boundary's which should be observed consistently if there
is some universal structure underlying knowledge (i.e. like if plato's forms are
the atoms/elements that make up the Monad). Specifially, one should apply
open/close/dilate/erode to the boundary of the graph, reevaluating it for
consistency. The trends that play out as knowledge becomes certain should
exhibit a kind of graph spectrum in the subgraphs & boundary. 

Protegé, apparently an old tool, is used by the administration-department
interface in universities to queue up potential research: to decide what's
likely answerable over a 5-10 year horizon; to decide how to allocate their
staff's specific skills & resources.

**** Using PDS Deep Archive

+ Find a base URL from one of NASA's services
  - These serve collections of assets over HTTP coupled with a manifest
  - explore the URL root to get a feel for the data
  - JIRAM [[https://en.wikipedia.org/wiki/Jovian_Infrared_Auroral_Mapper][Jovian Infrared Auroral Mapper]] project has a [[https://atmos.nmsu.edu/PDS/data/jnojir_2050/DOCUMENT/JIRAM_SIS_V7.5.pdf][Software Interface
    Specification]], which covers the organization of data as well as experiment
    design and data processing ... $\frac{W}{m^{2} µm} sterad^{-1}$
  - steradians should probably be in everyone's vocab
+ Bundles have DOIs, which is nice.
  - [[https://pds.nasa.gov/ds-view/pds/viewCollection.jsp?identifier=urn%3Anasa%3Apds%3Amaven.static.c&version=4.7][10.17189/1517741]] is for MAVEN. Other MAVEN bundles are available from
    [[https://pds-ppi.igpp.ucla.edu/bundle/urn:nasa:pds:maven.static.c][ppds-ppi.igpp.ucla.edu]] (the [[https://pds-ppi.igpp.ucla.edu/index.jsp][Planetary Plasma Interactions]] host)
  - ahh here we are... the main [[https://pds.jpl.nasa.gov/][PDS page]] (nasa doesn't have a frontend designer)

*** [[https://data.nasa.gov][data.nasa.gov]]

+ [[https://data.nasa.gov/data_visualizations.html][Visualization of datasets]]
+ [[https://api.nasa.gov][api.nasa.gov]]

Formerly open.nasa.gov. This looks like the place where you might go first

#+begin_quote
... but without guidance, finding much here wouldn't be much easier than the
internet. Obtaining nice data sets (without guidance) is usually the biggest
speedbump for noobs ... whether it's economics, finance, etc. Collating any of
them would be the next speedbump (more like a speedwall).

My guy! I heard you like flat-files? Without byte boundaries?
#+end_quote
*** [[https://code.nasa.gov][code.nasa.gov]]

**** CODE-A

This points to a page for NAS (NASA Advanced Supercomputing).

**** NAS

There are actually quite a few useful tools here: Ballast, Mesh, SSHIM

Mostly just greybeard wisdom, but may be more useful than the perspective
shfit. These are HPC tools and I don't have the scale. But the info seems like a
good treatment for security paranoia.

***** BASSHFS

The NAS site contains a BASSHFS, which is SSHFS without FUSE. now why on earth
would you want to avoid/limit FUSE file systems?  ...

[[https://github.com/pkolano/basshfs/blob/master/basshfs][BASSHFS]] sounds a lot like Emacs Tramp, but in pure Bash. No pain, no gain
... oh, nevermind it's perl and now i just really don't know.

***** SSHIM

[[https://github.com/pkolano/sshim][pkolano/sshim]]: my random-walk around efficient patterns for paranoia would've
been a lot less random if I had read these 500 words.

+ Another perl script.
+ SSH over ZeroTier/TailScale would be better for the average person. I'm not
  real sure what that does for battery life, but Ole' Cisco takes 45-seconds to
  negotiate a key so I'm not real sure SSH drains much after that. ZeroTier on
  the other hand is probably fairly noncy.

* Issues


* Tech $\otimes$ Microgravity

** Papers
+ [[https://ntrs.nasa.gov/api/citations/19990040250/downloads/19990040250.pdf][Chemical Vapor Deposition at High Pressure in a Microgravity Environment]]
+ [[https://www.cnet.com/science/nasa-upgrading-iss-system-that-turns-astronaut-pee-into-drinking-water/][NASA upgrading ISS system that turns astronaut pee into drinking water]]

* DOI Ontology

Since most researchers use non-free bibliography database management systems
(e.g. IDK), the documentation for DOI category/publication ID's is a bit sparse.
This would be the simplest way to sync papers locally or to file devices like
the Kindle DX which is impossible to find on sale. There's got to be an answer
to this besides cloud storage or Google Scholar (limited features), but I don't
know what it is.

** How to freely index papers on local storage
+ [[https://link.springer.com/article/10.1007/s00799-008-0033-1][Towards a digital library theory: a formal digital library ontology]]
+ [[https://link.springer.com/article/10.1186/2041-1480-1-S1-S6][CiTO, the Citation Typing Ontology]]
  - Uses RDF/OWL to define an ontology
  - This is related to the same XML specs used in Apache SPARQL for censorship
    in social media at scale.
