:PROPERTIES:
:ID:       676fa714-05d2-4422-b23e-1a97637ff161
:END:
#+TITLE: NASA
#+DESCRIPTION: space stuff
#+TAGS:

* Roam
* Docs
* Resources

** Data

Other Data Sources in [[id:8f853c3f-a42c-4d43-8015-a41313fe2d9b][Astronomy]].

+ [[https://science.data.nasa.gov/astrophysics-data/][Astrophysics Data]]
+ [[https://nlsp.nasa.gov/explore/][NLSP]] (Nasa Life Sciences Project): [[https://nlsp.nasa.gov/view/lsdapub/lsda_experiment/50256716-9cec-5390-abb1-893df24cc3f8][1961 Orbital Chimpanzee Flights]]
+ [[https://visualization.genelab.nasa.gov/data/][NASA Genelab]] (not really what I'm looking for)

*** Metadata
**** [[https://www.sti.nasa.gov/nasa-thesaurus/#.XKttRUN7lZI][NASA Thesaurus]]

This comes in several formats: RDF/SKOS, RDF/OWL. It's [[id:bb8bbe7c-6d49-4088-9161-2ae2edb4abd6][ontological data]]. There
are also PDF's that overview the datat ([[https://www.sti.nasa.gov/docs/thesaurus/thesaurus-vol-1.pdf][volume 1]]). When you want to link things
by category (e.g. the topic nodes in these org roam notes), it's useful to base
it on something authoritative or something you believe is widely used to link
other data/sets. When there's consensus on these ontological categorizations
... ummmm you end up renaming things a lot less.

*** [[https://data.nasa.gov][data.nasa.gov]]

+ [[https://data.nasa.gov/data_visualizations.html][Visualization of datasets]]
+ [[https://api.nasa.gov][api.nasa.gov]]

Formerly open.nasa.gov. This looks like the place where you might go first

#+begin_quote
... but without guidance, finding much here wouldn't be much easier than the
internet. Obtaining nice data sets (without guidance) is usually the biggest
speedbump for noobs ... whether it's economics, finance, etc. Collating any of
them would be the next speedbump (more like a speedwall).

My guy! I heard you like flat-files? Without byte boundaries?
#+end_quote

*** [[https://code.nasa.gov][code.nasa.gov]]

**** CODE-A

This points to a page for NAS (NASA Advanced Supercomputing).

**** NAS

There are actually quite a few useful tools here: Ballast, Mesh, SSHIM

Mostly just greybeard wisdom, but may be more useful than the perspective
shfit. These are HPC tools and I don't have the scale. But the info seems like a
good treatment for security paranoia.

***** BASSHFS

The NAS site contains a BASSHFS, which is SSHFS without FUSE. now why on earth
would you want to avoid/limit FUSE file systems?  ...

[[https://github.com/pkolano/basshfs/blob/master/basshfs][BASSHFS]] sounds a lot like Emacs Tramp, but in pure Bash. No pain, no gain
... oh, nevermind it's perl and now i just really don't know.

***** SSHIM

[[https://github.com/pkolano/sshim][pkolano/sshim]]: my random-walk around efficient patterns for paranoia would've
been a lot less random if I had read these 500 words.

+ Another perl script.
+ SSH over ZeroTier/TailScale would be better for the average person. I'm not
  real sure what that does for battery life, but Ole' Cisco takes 45-seconds to
  negotiate a key so I'm not real sure SSH drains much after that. ZeroTier on
  the other hand is probably fairly noncy.

* Issues


* Tech $\otimes$ Microgravity

** Papers
+ [[https://ntrs.nasa.gov/api/citations/19990040250/downloads/19990040250.pdf][Chemical Vapor Deposition at High Pressure in a Microgravity Environment]]
+ [[https://www.cnet.com/science/nasa-upgrading-iss-system-that-turns-astronaut-pee-into-drinking-water/][NASA upgrading ISS system that turns astronaut pee into drinking water]]

* DOI Ontology

Since most researchers use non-free bibliography database management systems
(e.g. IDK), the documentation for DOI category/publication ID's is a bit sparse.
This would be the simplest way to sync papers locally or to file devices like
the Kindle DX which is impossible to find on sale. There's got to be an answer
to this besides cloud storage or Google Scholar (limited features), but I don't
know what it is.

** How to freely index papers on local storage
+ [[https://link.springer.com/article/10.1007/s00799-008-0033-1][Towards a digital library theory: a formal digital library ontology]]
+ [[https://link.springer.com/article/10.1186/2041-1480-1-S1-S6][CiTO, the Citation Typing Ontology]]
  - Uses RDF/OWL to define an ontology
  - This is related to the same XML specs used in Apache SPARQL for censorship
    in social media at scale.
