:PROPERTIES:
:ID:       ea11e6b1-6fb8-40e7-a40c-89e42697c9c4
:END:
#+title: Networking
#+filetags: networking wireless

* General
** Docs

** Resources

** Network Manager
*** Setup VPN

Fix routes

#+begin_src conf
ipv4.never-default yes
ipv6.never-default yes
#+end_src

+ check key permissions
+ ensure user name is set

* Network Maps

See also nmap

** Resources

** Tools

*** Using Cisco's Next UI

[[https://habr.com/en/articles/534716/][Visualizing Network Topologies: Zero to Hero in Two Days]]

This tool was discontinued by Cisco quite a long time ago, but otherwise this
guide is fairly good.

*** OWASP Amass

+ [[https://github.com/owasp-amass/amass][owasp-amass/amass]] and [[https://github.com/owasp-amass/amass/blob/master/doc/user_guide.md][User Guide]]

*** Netplan

This eats YAML and generates network configuration for systemd-networkd &
network-manager... no idea how i never encountered this...

+ [[https://netplan.readthedocs.io/en/stable/netplan-tutorial/#editing-netplan-yaml-files-to-disable-ipv6][explanation]]
+ There's no AUR package ... but there is an arch package.
+ [[https://netplan.readthedocs.io/en/stable/netplan-yaml/][netplan yaml]]


* NTP

** Docs

** Resources

** Tools

*** ntpq

For usage, see [[https://medium.com/@minimalist.ascent/exploring-ntp-servers-bf631074d403][enumerating NTP servers]]

On Guix, this is just in the =ntp= package.

Useful commands:

+ ntpq -c rv
+ ntpq -pn
+ ntpq -c sysinfo (and check the leap code)

* Infrastructure Layer

The not-quite-application ~layer~: names, load balancing, caching and transport
at this level provide essential abstractions for indirection. So they are
arguably more so networking than part of the application ... For now, until I
move them out.

** Resources

+ [[https://vishalrana9915.medium.com/deep-dive-into-system-design-d6b27525f208][Deep Dive Into System Design]]
+ [[System Design Blueprint: The Ultimate Guide][System Design Blueprint: The Ultimate Guide]]

** DNS

*** Docs

*** Resources

*** Topics

**** Avahi mDNS

***** Prevent binding to interface

Edit =/etc/avahi/avahi-daemon.conf=

#+begin_src conf
[server]
deny-interfaces=$ifx
#+end_src

***** Force =host.local= to IP

#+begin_src sh
cat >> /etc/avahi/hosts <<EOF
host.local 123.45.67.8
EOF

# maybe restart, then check
avahi-resolve --name host.local

# this won't show up
avahi-browse -atvr

# double check
ping host.local
#+end_src

This doesn't work bc it's too late:

#+begin_src sh
# packets attempted, kernel blocks, process confused
iptables -s $ip -I OUTPUT 2 -p tcp --dport $port -j REJECT
#+end_src

TLDR: one cannot simply "split" traffic for services discovered by avahi

***** Network Devices

****** Gemini :crypt:urlllm:
:PROPERTIES:
:CRYPTKEY: David Conner <aionfork@gmail.com>
:END:

-----BEGIN PGP MESSAGE-----

hQIMAz05LBTqCkO0AQ/+KIABWXkjQ0h/OhaMgv0m30jjnDUQS0Vmz9+Y4O0TuuCC
aCm48ihKEc0FkZKI8lYlKalccPySmqrfusIrZTMKqnUcN+d4Y+P1gEQL5t70y/Rz
G3IzG9G170IDt+Ydjm+PF5mBn0Htj87K42WDt6QM8M41zC3lbgq9EKaCkxkZjD4p
gi4vW1QV1cmYiTxp5PIoR6mGktj+V3GbBw9GGwAaX176BTJmVQkdEkyNbULk9OKd
6OOjpm5+ilm6KqJ1AZSpY9GUCrjPWS3fhn15h5Pp2woH9EEjR4Jcz/gT+KAkxq4W
j9c0R3EgilzWTQNR0U/bg23kfslwblO0FpX6XQsP2xrZJKkPlY00G67e6pn0BxOb
Yr9PRWI67Gr4C+toulyYwBBvRMbxTiH7DY5bxu3JtzIiIQoDmWMgP3SdS3tUe7GJ
xZ25C8RfyRoRqW4Da1JfjEJGca3sCzNjh1VuAUh9dOojEQxk5+QFxxCbXWPoCIKr
wi7ART5AlDItycsIRKZ7LTdVCu9i2abC3VCJmUbPZqJEEOfEfFbM6gCNwGAu6kTc
IoLIoPLN2E3w5Wxfue0Y3alWAiXIQT05VVuPR91eI4ffGrIXKbZg20C/ltOHB2MP
8+DuTw33EhjLU552QhTEc1A0I5ofYKe2hkGovjyJWjNLcqKxAjqU/hm+khTkKCPS
6gHCK8zNu4cDDCvSeLwEeNLA2/6BSwypkB8kiTKX+M+HIh+cDkTScwV1QzX5oF4y
NG05PcwnH+2sCSKWfXdruVHSxQZulafaGBsVYicFvg8RTO3cv3vFv1E8yhJfm0Be
w7vTXCd1R7jCkXL7IN9QuHzp0AvZIhgz8jWPAqRr9kRRQ0f+Ef4mqogQhoklGwcr
jxL8vXwFc1RIsu/g+Jmmu+KP30wyLf7CApELJAxlsZl0eUMEfRASVHJp3zmRNvQl
bIyr3IQmOaqh3XbkHj8xV/yTRK2hFZvKyqsGfzTnhyXFwnqmXDy338y5tQOnF+F1
Q/Dy0gecFq7m2Wd2eoq7p+9VbSUkisk3T5cowtm8ha9UUS6K0D+MJoU5gOUJ0o5e
PANtnnq1C5/+kCmRsTdmwa5/4GWhGvJY0F3A1Wep+wRKraNaRZ8ozPDur3+fY8me
ZbDkeNgNT3ZMpr2KmOk19+diA5Mgt1+9Lida6ND/+xBKEnQ1DSZlzJYWQ7ABvQ6c
YbGU9ePExPzk54guYJiArJTmQeNmwiXALsMDrQA1yak4kP2ku8hX6hdXY3dDtwa+
RS2JOdHQGdTz0y0h2DM4hO0QZSbfpiRqj3Y79i1wboEHUpK+cKBbCJchObxjVxDm
0vyjPL7sz0jIrm5Q2XnuFU0ooz8XbWzfVyRjPdrm7g/5vWOajiw63tod+wfMJuX6
WsuiB9+TlAdc21N/T2O51KglEZ9niztm38013xY04c9qV8Lh8BRo02rsEPf3xCII
v+UHgzdCk8jYKuEz4QwKxcJXlNcUP2S0V+MIOP/uHNfhXJhK1GZ45zKgjB3RRVz8
QbQ4vGd+4bCmlPV95LCo5tcmFHmu27Z127OT8MmTS/RmH4n+7AvF9+Xzy0EALn+D
sG5tcV9Xnaq4EVX2tAheFRJJFuXNbwatee5uzEsEAOJEbhx7t5HprDJ+a46HWX9O
kTMQWpzZKQygaP7/n0yyTlV6fI0DQnu1Eo1jr55UR8EGflj85jqK5qJceNYu+qkR
jCfQ+s77ewTHt/ssr0jIo+HhtMvpB4wiAmi444x7VkxtQ9RE0yj9WyMvEWavM5PO
6vX3K0niYUIOXtattugQQwwvgDL91S7eNgaHq7j4Y6JMpYn/89EEESnAqjI69pqz
iLBAP4id88chC3wJNwAHwIM7T96oDlqtCWQpye7MOZFCiBVSXSGp7zuciXPeMN52
XvkJ+2O5FEGybvZ3rDpADPC4huhY9AEUonaYp0sCWlaheWeiwo/Sq2XZiV/Y+BOy
btM/h2UX6PfEtjzHTGvwVD13lV8JrmUkLfqdQSmiZ+5rkvWj9PTu0kIL4QOJsFh4
5bmOuqL3ZCJIlVYDF0XHxNHA1Po9sObDWFi3xzdOyu9FNjjaEfumWxiwfvUjSE2y
LL26dY/CHyqgQ69vCxphLe1OPLG/MjTami7Bel2fDcNzOthijazXZvRil2rhIgNP
NFULH3vG1ebr2bEmr3SUq0NP6e2JCo1ZDM6F8otbRgaBjY+RXDNPUHekXQhxXoqE
y6cX3j2e2mhOKe1G0M9vz8C6TtVIdVq4dNNl+bNzMLybeqXVPmtduA3a/Dt/LDWO
3cDlo/PQHy2pyxFhRmIKkh8IHLVKvAaM48j8bB707OMfXzBNUQtaOYncVhGLdwPL
OjCpilHjUBxGEosRmfY2tgxe0Y9xKf5bbPVexUgCKmcW3LWBKFCh9FPHliYsAiZC
yFGxfI46QjuRZFWA4pLCrHLVIVvxqj7gCxhwlKlojhh65RRFF2cFsK3mqj8J9BXr
o8liadBZ4c3G7Po2Svx7yRmnAZLF8hKG5dpNbnaZgmoUsffScOBgnJt/bKalgNmc
yBH/TYmAq66qCsRayTcxB2JYGwPMc7pyZ7p4+QUQF1CTCLxn357N
=UCQy
-----END PGP MESSAGE-----


** Load Balancing

*** Docs

*** Resources

*** Topics

**** Session Tracking

+ [[https://vishalrana9915.medium.com/consistent-hashing-36fa25892b4f][Consistent Hashing]] or "Why Twitter didn't really DDoS itself"

**** Edge Services

+ [[https://datatracker.ietf.org/doc/html/rfc3238][RFC 3238]]: IAB Architectural/Policy for Open Pluggable Edge Services
+ [[https://datatracker.ietf.org/doc/html/rfc3507][RFC 3507: Internet Content Adaptation Protocol (ICAP)]]
  - formerly used for [[https://github.com/Exa-Networks/exaproxy][malware scanning]]

** Caching

*** Resources
+ [[USENIX Association 10th USENIX Symposium on Networked Systems Design and Implementation (NSDI ’13) 385
Scaling Memcache at Facebook][Scaling Memcache at Facebook]] via [[The A-Z guide to Distributed Caching][A-Z Guide To Distributed Caching]]

** Web Sockets

*** Resources

+ [[https://vishalrana9915.medium.com/understanding-websockets-in-depth-6eb07ab298b3][Understanding Websockets in Depth]]

*** Topics

**** Proxyies

***** Socks/Broker

Just wondering whether I can bridge a websocket to a normal socket via =socat=

+ LLM recommends an "Architectural Proxy Buffer"
  - this really requires the client be capable of managing both async data
    streams (client speaks both websocket & socks)
+ or configuring the client's network to attach to a SOCKS5

****** Gemini :crypt:urlllm:
:PROPERTIES:
:CRYPTKEY: David Conner <aionfork@gmail.com>
:END:

-----BEGIN PGP MESSAGE-----

hQIMAz05LBTqCkO0AQ/9HR8c3sg4Z9LK/VPSg77IXb1kM/jpEdALanja+lYvz8YT
7wU442BV2bWSsp7WzM9a7jZxwTFtOnA4hFBqQddIkTfr8lqpBO2KOEpHaZCdtkcn
4cHLnGZjkXKctuvO8/m+TnKfj7n2D62YWImbuF9QcoyYJACZ/jXSE4viZTJ4RzKT
BNB+uyAoViJgFgbi6BDi1SPNObBTyHNDAbpyWAxn7XBuCLFXiw/D69Kg6Ef8nbUR
gpjhfjjs3NNewxw5AoxKxMPDLM++hCOMpuL9ecEFqzUqKdtRPUFJQach6V6w0+sD
8Ku/gb3fRTI/oTrfXSq7yHFm3aApIeAy7WQiHcsll+xKfOwXZ2CuGsvQwVJlVHtU
qIym9BexZmMbCcevCBgyFWv18hqBXry9DeiYucm+Ylp4RTm5wlWJcMbefGdQywta
uBwkBmRODQKyllDsZsrJ/ZOQumHvwx0KfwmQ3l4JcyAKXDJ9CfVN2+6nQb6USUFa
bzwUZ/wDcxGrxGZ/z7BPahNfhwbTrukfXHdh/WaZOEdoibz3jsMUfaUTMoBlbgc7
HplLhYZTgO42vOOkc8Wc0iWoaCHFIMxnN1E+BCUllhZXUeAiTTEUAZLp1YmI8Yd4
glp7yaxOEAM1sNtRuZ5KaHbIcepLSqg91Pgkkzey49vP5vBJWlJwnx69ZJRkrbrS
6QGgwtOtgHacsvvg3XG80/MMNZ+n9vtRYGWYKbwJKk+s6U26PmorCEANHw2gqj8O
Sb1/u2e8a+Kej8clwGdNul136bA2SRj823PdajSTXUfX8/lM9MVhAntdBLg8o7hq
BD7q7hxrceMIkzJNaWUaqmxjGrGcoSHWOSsEX9SXFEhWwwyfWk66nfYpleowqjwu
wCFX0oe7AdbN3D4pHsBNudrp0y+9hKxJIKFrLSGxvKpTXZPVVioKUg2Hvj25CKCK
voxxnBTjqgCUvDpDu6PaJEFUpRFV/w6up1gRXr/tgmIEVhr8rlkozu1AB7wdG4HT
xwQHhYK1u95GMS0HLrWF5h20J0hQGx00TApD0AAt77XKPIbA1Oue8C41iz0DcD+f
JsZ+rOCQqUwm3DqmtyMT+h9G8/PIMR0VqQukSfBD46sZ0kZqIAxPwVl1/xULwVgj
KlRxso4cymasr2nStH5m414489p6rSYV6fE57D7NqnTZlXwBUUGWzj+cZzd3g0ER
QW7HCYA9YJIKzK1YcR2KkA7QZOp7lwFtD5ANEUmqtQBE0Pp8Kv1WrVhsEOBL5RPT
y4p3OoGYQCh7ytpV2JUqJWP5hlKr9tdeVKHEpWyL0fdcy2tupoxgA6GDGnjKrmeB
eQ0xdLLlcaciMqqMaZcsKblX9JB4h91MXtBLURCOKvkTwGRpUU+IQT0ToBFxMKOO
UebMTTuzjw4GTII9Wa6JH6WMHOTKvL8cGpiHAgcNt1CzH0sNP0GXsh+YC2PafseK
dE+CemXyIJZzRMUctKUvuQLi7VKjWJjamj5cqwxmNk73lOQ5MMdVxy+1J/thiNpu
clQYseYUCCiSM7opMx8sTAC1OHL6ZhjCxl4GdcbPeXy68h10NUKRMf/5quz7TTi6
Lc96TUrIMK09ZK+U/1oT7iTkVsuUSsa36WNocH6KC02FA5NgpM45UvoTOsQqSAo7
uS7UkxlBqxPxFhmSrIQ9RIUy6PmsRGZ2fZQe5wR3D/mB6onHQp/L1oWxWPaznaoF
7WJcti+kpoN8Brz91jktlS4LRZeXIgC2lBbVC4NksakAmqOEmNF5
=rGbZ
-----END PGP MESSAGE-----


** Wire Protocol

Protobuf and things

*** Docs
+ [[https://protobuf.dev/programming-guides/encoding/][Protobuf]]
+ [[https://grpc.io/docs/][gRPC]]
+ Flatbuffers (TF Lite)

*** Resources

+ [[https://ssudan16.medium.com/internals-of-grpc-architecture-afae7450ff5b][Internals of gRPC architecture]]


* Layer 1 and 2

** Ethernet

*** Docs

*** Resources

*** Adapters

**** Intel

+ [[https://core.dpdk.org/supported/nics/intel/][Intel Cards]] (links to DPDK guides for each driver)
+ DPDK [[https://doc.dpdk.org/guides/nics/index.html][Driver Docs]]

***** Card Support For SR-IOV in Ethernet

This [[https://www.intel.com/content/www/us/en/support/articles/000005722/ethernet-products.html][Intel ethernet cards that support SR-IOV]] FAQ describes what to expect when
using SR-IOV. The Guest OS also needs Virtual Function (VF) drivers.

**** Resources

*** Physical Layer

**** Decoupling

+ [[https://networkengineering.stackexchange.com/questions/29927/what-is-the-purpose-of-an-ethernet-magnetic-transformer-and-how-are-they-used][Ethernet: magnetic decoupling via transformers]]
+ [[https://electronics.stackexchange.com/questions/27756/why-are-ethernet-rj45-sockets-magnetically-coupled][Why are RJ45 Ethernet Sockets Magnetically Coupled]]

*** SR-IOV Networking
**** Docs

**** Resources
+ [[https://www.juniper.net/documentation/en_US/release-independent/nce/topics/task/configuration/vsrx3.0-sr-iov-10g-ha-deployment.html][Set Up SR-IOV 10GbE High Availability on vSRX 3.0 with Ubuntu on a KVM Server]]
  - vSRX is an SRX firewall in a VM (like VyOS)

** Wireless

*** Docs
+ [[people.freedesktop.org/~lkundrak/nm-docs/nmcli-examples.html][nmcli-examples]]

*** WPA Supplicant
+ [[https://man.archlinux.org/man/wpa_supplicant.conf.5][WPA Supplicant Conf]]
+ [[/usr/share/doc/wpa_supplicant/wpa_supplicant.conf][Example Config]] (local)

* Layer 3

** IP4

** IP6
*** Resources

+ [[https://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xhtml][IANA doc on multicast IP addresses]]
+ [[https://www.roesen.org/files/ipv6_cheat_sheet.pdf][ipv6 cheatsheet]]

*** Topics


**** Dynamic WAN Addresses

See this answer on [[https://superuser.com/questions/1479327/why-is-ipv6-still-dynamic][addresses and prefixes]] and this one on [[https://superuser.com/questions/1372769/ipv6-home-set-up-openwrt-18-06-1-how-to/1374251#1374251][DHCPv6 stateliness]]

#+begin_quote
The WAN's gonna give you an address. And you gonna go in there and be like
"what's your address" and the ISP router's gonna be all like "You can't tell me
what to do."
#+end_quote

.... not really though. Thank god they can't screw that up. I need to double
check this because doubling the IPv4 addressing on most of my interfaces might
not work.  The plan is to add a one-to-one IPv4 overlay using trunked vlans with
IP's to ping for test. This should be fairly trivial ... but there are
potentially address space conflicts, in addition to firewall issues.


**** IP6 addressing, subnetting & *-casting divvy up a hypergraph of networks
  - This is the "mathy" way to think of it when:
    - designing addressing schemes
    - designing application-level features that utilize the IP6 multicasting &
      subnetting
  - [[https://www.youtube.com/watch?v=ft35bUVxiLQ&t=2489s][There be dragons]]: as the IP6 route/switch config becomes more complex, so
    do the devops, firewall rules & attack surfaces.
    - It should be more secure ... but not necessarily
    - Specifics?

*** Issues
**** How to force IP6 on a network?
+ how to ensure internal devices are complying as expected?
**** How to detect NAT translated ports connecting via your router, initiated externally?
+ This will happen all the time...
  - but if I force IP6 internally and at least expect VPN/external connections
    to connect via IP6,
  - then this can distinguish computers/connections under my control from an
    attacker (who isn't aware of my preferences)
+ How to specify this with PFSense/Snort (or security onion) to sniff some
  matching patterns?

* Layer 4

** TCP/UDP
+ [[https://medium.com/@jamesbordane57/nat-traversal-how-it-works-90cfe7a2ec97][NAT Traversal: How it works]]
