:PROPERTIES:
:ID:       68d21e2f-97ad-4543-9deb-6517be92c9d0
:END:
#+TITLE: Nootropics
#+DESCRIPTION: umm shit
#+TAGS:

* Roam
+ [[id:59f56c1a-d91e-48eb-88d9-868e6250465a][Biomechanics]]
+ [[id:8adf45de-c02e-427e-b8bd-ad0b169a5d34][Bioinformatics]]
+ [[id:fe6cfff6-52e4-44fe-a429-b8e599a3f008][Chemistry]]
+ [[id:7b98efac-9db8-4293-9e1c-d5730f0b1667][Spectroscopy]]
+ [[id:d6782147-2239-4d0d-9e86-091cb3a5fff0][Toxicology]]
  
* Docs
* Resources
* Topics
** Racetams

See [[https://www.reddit.com/r/Nootropics/comments/cength/testing_your_supplements/][Analytical Methods for testing]]. Thanks [[https://www.reddit.com/r/Nootropics/comments/cength/testing_your_supplements/][misteryouaresodumb]], who hails from
nootropics depot. *It is so absurd that fda action against nootropics depot
resulted in the almost complete withdrawal of racetams from the market.

#+begin_quote
_Caveat Emptor_: it would seem that some vendors have variations in some batches.
The production methods for many of these is to produce them using THF as a
solvent using a process where the THF converts into the pyrolidine ring.
#+end_quote

*** General

Only some of these have been well studied, with the affects of delivery vehicles
_not_ well studied. It seems that the presumed insolubility has greatly distorted
the research into these drugs.

**** Effects in Humans/Rats

For research into vascular dementia, effects from solubility _should_ greatly
affect the conclusions from results. Large-scale effects on neurons by molecules
(_especially_ those exhibiting _allosteric_ modulation) are subject to network
effects.

+ In an oversimplification: neurons -- made of networks.
  - Vasculature? Also made of networks. The vasculature arranges itself
    according to a wierd tree-based version of Voronoi, where both veinous and
    arterial branches of the CVS are constructed of "arborous processes" where
    the system attempts to balance distance from CVS with the radius of the CVS.
  - It's hard to explain. Just like the heartbeat of an organism is derivative
    of the size of their body, so to are certain effects from solutiblity on the
    variations in dissolved solutes -- _especially_ for insoluble molecules.
  - Networks of fats in the brain introduce yet another source of insolubility.
+ There are two tissue-specific filters in the BBB:
  - endothelial: at the interface between CVS
  - astrocytic: at the interface between astrocytes and neurons
  - that is, in addition to the variations in charge density (which mostly
    affect the boundaries between the BBB interfaces) the solubility of
    molecules affects the ability to travel/distribute within the cytosol (and
    the preference of a molecule for retention in lipids)
+ Solubility would also affect clearance of a molecule from the brain via
  interstitial (Brain-ISF) and cerebrospinal fluid (CSF). This is mostly
  blood-plasma:
  - with large molecules/particles
  - with less Hemoglobin and O2/CO2-based effects
  - and with different regulation via albumin (see [[https://en.wikipedia.org/wiki/CSF_albumin#:~:text=CSF%20albumin%20is%20a%20measurement,of%20albumin%20in%20cerebrospinal%20fluid.&text=A%20closely%20related%20test%2C%20CSF,50%20mg/dl%20in%20adults.][CSF Albumin]] and
    osmotic/oncotic regulation mechanisms)
+ The CSF drains into the ventricles and down into the spinal cord via CSF
  pumping (more affected by yoga, orthostatic mechanism and macroscopic motion
  than by hydrastatics; both ISF and CSF are constantly facility osmotic
  mechanisms along their surface boundaries)

So both the variance _AND the variance-in-variance_ in [empirically measured]
solubility should be much greater for organisms with larger brains.

+ This is because the strength of network-based effects should be much stronger,
  given much larger networks -- generally, but also very difficult for me to
  explain to technical satisfaction.
+ Regardless, this should be abundantly obvious in research, unless almost all
  medical research is fraudulent (or at least, a waste of time.)
+ In any case, more testing methods like PET are needed, but come with specific
  costs & side effects.

*** Oxiracetam

This is the one that I remember "liking", which may be a result of its
solubility

**** Solubility

|---------+------------------+-----------------------------------------------|
| Vehicle | Solubility       | Notes                                         |
|---------+------------------+-----------------------------------------------|
| H2O     | < 31mg/mL in H2O |                                               |
| Ethanol | Insoluble        |                                               |
| DMSO    | Soluble          | Toxic, smelly                                 |
| PBS     | < 100/mL in PBS  | From Google AI. Can't find actual attribution |
|---------+------------------+-----------------------------------------------|

**** Research

+ [[https://pmc.ncbi.nlm.nih.gov/articles/PMC6853072/][Oxiracetam ameliorates cognitive deficits in vascular dementia rats by
  regulating the expression of neuronal apoptosis/autophagy-related genes
  associated with the activation of the Akt/mTOR signaling pathway]]
*** Aniracetam

**** Solubility

|---------+------------+---------------|
| Vehicle | Solubility | Notes         |
|---------+------------+---------------|
| H2O     | Barely     |               |
| Ethanol | Soluble    |               |
| DMSO    | Soluble    | Toxic, smelly |

**** Dosing

This is a bit tough to dose, as it's fat-soluble, but quickly liver-metabolized,
where vehicles of the former (e.g. coconut oil) would amplify the effects of the
latter. It's important to remind one that, if you resolve the solubility
problem, /you greatly reduce the total dosage needed./

What I've done to get around insolubility: make the solute "pick a team" -- i.e.
formulating multi-layered vehicle where order of solvation may affect the total
absorption.

Here's the method:

1. Mix 250-500mg of aniracetam into some maltodextrin-only sugar supplements
   - you can find these  marketed to runners & athletes. Some of these
   - the idea: force aniracetam into voids between the polymer chains of
     maltodextrin
2. Mix this into some water (about 100ml)
   - the aniracetam should avoid the water and VDW-interactions between racetams
     and aniracetam should be stronger here than much anything water can disrupt
   - phenomenologically, if there is a difference, the maltodextrin should form
     long "sheets" in the fluid. The formation of these sheets will not be
     completely absent with/out aniracetam -- just different.
   - Weak VDW interactions (maltodextrin/itself, maltodextrin/h2o,
    maltodextrin/aniractem, h2o/aniracetam) should be highly varied, producing
    sheets of fluid that move against itself. With less h2o penetration, the
    fluid should be generally more resistant to h2o penetration. Thus, the
    friction that governs mechanics of inter-layer shearing should be higher
    with aniracetam.
3. Mix this into your average greenstuff containing pulverized vegetables,
   spriulina and amino-acid containing powder. Prefer stuff with maybe less
   spirulina.
   - The powder will disrupt the fluid layers from the previous
     stage, but will itself preferentially intake more H2O into both itself and
     the maltodextrin.
   - the rational: Aniracetam is forced to choose a new "solvent" or substrate.
     It will prefer voids/spaces in the vegetable powder, which has tons of
     irregular voids from puverization.
4. Finally, mix some milk/water into the the greenstuff/maltodextrin.
   - The milk adds colloidal effects (on the micro-level), but also adds fats,
     which aniracetam will prefer (though it may not be physically accessible;
     not immediately)
   - the water at this point should not have much of an effect on where
     aniracetam has chosen to distribute itself.

The result:

+ a mixture that should steadily release aniracetame into fat tissues, without
  "bundling it all" into fats (like coconut oil) to be promptly delivered to the
  liver for metabolization.
+ This is also a mixture which may scatter aniracetam across the CVS, if
  particles are absorbed into the gut lining and remain somewhat in tact when
  they enter the CVS. The aniracetam should stil prefer the voids in the
  vegetable matter, as that substrate is slightly alkaline while pulling in
  stomach acids which break particles into smaller sizes.
+ Aniracetam prefers acidic conditions, so it should be pulled towards the
  outside of particls, while not into extrinsic solutions.

Where I could be wrong:

+ the gastrointestinal system preferentially absorbs nutrients and other solutes
  by very specific means. however, this doesn't describe _all_ the means by which
  solutes may be absorbed.
+ the gastrointestinal system is surrounded by fatty tissues. i don't know all
  the ways in which nutrients in the gut/etc can be absorbed into fats.
  once there, the solute would be trapped and released slowly.
+ I also don't know how the absoption of nutrients into fatty tissues interacts
  with nutrients (or other materials) from blood/lymph

TLDR: things are magical. there must be a mechanism or reason that explains
distribution of molecules throughout the body.

+ There are many specific mechanisms which represent high probability
  transitions in distribution. This explains the majority of changes to molecule
  distribution -- but not all changes.
+ One of the fundamental premises of multicellular organism (esp those complex
  enough to differentiate cells into different shapes/types of tissues) -- there
  is _compartmentalization of state_, where state is the concentrations of
  molecules (though the definition state can be more generalized) and this
  compartmentalization of state *must be* _facilitated_ and _perserved_ by physical
  separation.
+ Hence, there must be fairly well-understood mechanisms for nutrient
  absorption, distribution, usage & clearance through the body. The mechanisms
  must be _specific_ in some way or another, otherwise the compartmentalization of
  state breaks down.
  - _Fungi_ are one class of animals which generally facilitate the breakdown of
    this compartmentalization of state *in other organism but not themselves*.
  - Incidentally our processes of digestion and immunological response
    (inherited from fungi) also preferentially break down the
    compartmentalization of state.
  
Probably wrong though. Just saying. It does seem to work though, but so do other
methods:

+ sublingual doses: but dental & gum health is seriously a concern here with
  various molecules; this is not a joke (idk about racetams, but you want the
  nootropics to go down the hatch quickly)
+ adding to xylitol gum (again: dental/gum health)

* Issues
