:PROPERTIES:
:ID:       33cee19d-b67b-429c-963b-29209d0982bc
:END:
#+title: Orgmode

* Docs
** org-mode
** org-ref
** org-roam
** org-noter

* Resources
** Examples
+ [[dfeich-org-babel-examples]]
** Philosophy
+ Karl Voit [[https://karl-voit.at/tagstore/downloads/Voit2012b.pdf][TagTrees: Improving Personal Information Management Using
  Associative Navigation]] (thesis)

* Topics
** Publishing
+ For a summary of options: =org-export-dispatch=
  - [[https://hieuphay.com/en/posts/2018-05-17_org-mode-to-latex-pdf/][Basic publishing config]] of org/latex for export
+ [[https://www.aidanscannell.com/post/org-mode-resume/][Creating a CV/Resume in Org-Mode using LaTeX Templates]] (aidanscannell)

** Org Drill

**** TODO move some of this into a slip

*** Example Configs
+ sacha
+ HaoZeke
+ blejdfist
*** Example Decks
+ [[https://github.com/jzsampaio/spaced-repetition-decks][jzsampaio/spaced-repitition-decks]]
+ [[https://github.com/jschaf/org-drill][jschaf/org-drill]]
*** Example captures


#+begin_example emacs-lisp
;; from blejdfist/dotfiles
;; TODO append to org-capture-templates

          ("w"
           "Capture web snippet"
           entry
           (file+headline "my-facts.org" "Inbox")
           ,(concat "* Fact: '%:description'       :"
                    (format "%s" org-drill-question-tag)
                    ":\n:PROPERTIES:\n:DATE_ADDED: %u\n:SOURCE_URL: %c\n:END:\n\n%i\n%?\n")
           :empty-lines 1
           :immediate-finish t)

          ("f"
           "Capture normal snippet"
           entry
           (file+headline "my-facts.org" "Inbox")
           ,(concat "* Fact: '%f'       :"
                    (format "%s" org-drill-question-tag)
                    ":\n:PROPERTIES:\n:DATE_ADDED: %u\n:SOURCE_URL: [[%l][%f]]\n:END:\n\n%i\n%?\n")
           :empty-lines 1
           :immediate-finish t)

#+end_example

** Org Capture

+ [[file:/data/ecto/x.files/sachac/emacs/Sacha.org::*Templates][Sacha's capture templates]]
+ [[file:/data/ecto/x.files/blejdfist/dotfiles/.emacs.d/init.el][file:/data/ecto/x.files/blejdfist/dotfiles/.emacs.d/init.el]]:568

** Org Snippets
+ When is it more appropriate to use snippets vs capture templates:

#+begin_example
# zzamboni
./zzamboni/doom/snippets/org-mode/cq
./zzamboni/doom/snippets/org-mode/star
./zzamboni/doom/snippets/org-mode/htmldiv
./zzamboni/doom/snippets/org-mode/floatright
./zzamboni/doom/snippets/org-mode/graph
./zzamboni/doom/snippets/org-mode/leanpubquiz
./zzamboni/doom/snippets/org-mode/digraph
./zzamboni/doom/snippets/org-mode/frag
./zzamboni/doom/snippets/org-mode/elvish-literate-module
./zzamboni/doom/snippets/org-mode/plantuml
./zzamboni/doom/snippets/graphviz-dot-mode/htmlnode
./zzamboni/doom/snippets/graphviz-dot-mode/graph
./zzamboni/doom/snippets/graphviz-dot-mode/digraph

# HaoZeke
./HaoZeke/doom/snippets/org-mode/beamerSection
./HaoZeke/doom/snippets/org-mode/Anki Card
./HaoZeke/doom/snippets/org-mode/twoColbeamer
./HaoZeke/doom/snippets/org-mode/afterSaveHook
./HaoZeke/doom/snippets/org-mode/subfigure
./HaoZeke/doom/snippets/org-mode/eisvogelPdf
./HaoZeke/doom/snippets/org-mode/shebang
./HaoZeke/doom/snippets/org-mode/New Seminar
./HaoZeke/doom/snippets/org-mode/shortPdf
./HaoZeke/doom/snippets/org-mode/org-beamer Execushares
./HaoZeke/doom/snippets/org-mode/uniRprt
./HaoZeke/doom/snippets/org-mode/maximaMath
./HaoZeke/doom/snippets/org-mode/nowebCode
./HaoZeke/doom/snippets/org-mode/orgBeamerVerona
./HaoZeke/doom/snippets/org-mode/orgReRevPres
./HaoZeke/doom/snippets/org-mode/ReReveal Two Column
./HaoZeke/doom/snippets/org-mode/Orgmode R Analysis
./HaoZeke/doom/snippets/org-mode/orgBeamerMetropolis
./HaoZeke/doom/snippets/org-mode/short-review

# tecosaur
./tecosaur/doom/snippets/org-mode/header-arg-tangle
./tecosaur/doom/snippets/org-mode/python_src
./tecosaur/doom/snippets/org-mode/display-maths
./tecosaur/doom/snippets/org-mode/header-arg-noweb
./tecosaur/doom/snippets/org-mode/header-arg-dir
./tecosaur/doom/snippets/org-mode/header-arg-wrap
./tecosaur/doom/snippets/org-mode/elisp_src
./tecosaur/doom/snippets/org-mode/property-header-args
./tecosaur/doom/snippets/org-mode/inline-math
./tecosaur/doom/snippets/org-mode/src
./tecosaur/doom/snippets/org-mode/global-property
./tecosaur/doom/snippets/org-mode/header-arg-width
./tecosaur/doom/snippets/org-mode/header-arg-output
./tecosaur/doom/snippets/org-mode/__
./tecosaur/doom/snippets/org-mode/header-arg-eval
./tecosaur/doom/snippets/org-mode/header-arg-results
./tecosaur/doom/snippets/org-mode/header-arg-session
./tecosaur/doom/snippets/org-mode/header-arg-export
./tecosaur/doom/snippets/org-mode/header-arg-height
./tecosaur/doom/snippets/org-mode/header-arg-graphics
./tecosaur/doom/snippets/org-mode/header-arg-silent
./tecosaur/doom/snippets/org-mode/header-arg-file


#+end_example

*** File Templates

Not exactly org-mode, but related to snippets/captures

#+begin_example
./zzamboni/doom/doom.org:287
./zzamboni/doom/init.el:63
./HaoZeke/doom/docs/index.html:379
./HaoZeke/doom/docs/config.html:601
./HaoZeke/doom/config.org:220
./HaoZeke/doom/init.el:69
./dwt1/dotfiles/.config/doom/init.el:56
./benmezger/dotfiles/dot_doom.d/init.el:28
./isti115/dotfiles/.doom.d/init.el:53
./lccambiaghi/doom/init.el:51
./hlissner/doom/init.el:43
./sunnyhasija/doom/init.el:53
./Brettm12345/emacs/init.el:9
./tecosaur/doom/config.org:544
./tecosaur/doom/config.org:4955
./tecosaur/doom/config.org:4956
./tecosaur/doom/config.org:4957
#+end_example


* Issues

**** Org-Babel & Tangling

This is a quick self-reference for me, while I'm focusing on this tangle-heavy project.

***** Testing Header Args

Test babel's perceived =header-args= for a block with:

#+begin_example emacs-lisp
(org-entry-get (point) "header-args" t)
#+end_example

***** Inherited Header Args

=:PROPERTIES: ... :END:= must start *exactly one new-line* after a headline

Using this under a headline will wipe out any existing header-args.

#+begin_example org
:PROPERTIES:
:header-args: ...
:END:
#+end_example

Must use =:header-args+:= instead.

***** =:mkdirp yes=

This does not work in a file-level #+PROPERTY header-args declaration.

***** =:comments link=

This is useful for detangling... but can't be used with =<<noweb-templates>>= AFAIK. I will simply tangle the blocks to individual files and assemble into a script somewhere else.


* Workflow Ideas
** Refile Lists
+ use a different charset for refile labels intended as inboxes?
  - i.e. '** 研究の受信' instead of '** Reserch Inbox'
  - prefixing with a letter from the alt-gr set may be easier
    * must be mnemonic & obvious

* org-noter
Emacs needs to build epdftools, which it will try to do on the first invocation of =org-noter=

+ Dependencies
  - libpng
  - zlib
  - poppler-glib
  - cask
