:PROPERTIES:
:ID:       265a53db-5aac-4be0-9395-85e02027e512
:END:
#+TITLE: PFSense and OPNSense
#+DESCRIPTION: The Firewall
#+TAGS:

Being kind of an idiot ... it's a bit hard to distinguish these two things. The
commit frequency charts are misleading. They look about the same ... but when
the red correlates strongly to the green -- that's a refactor. You can't scale
the Github charts, so it's a bit hard to judge the activity on either.

Hardened BSD Kernel sounds sexy and all, but ... migrate my firewall for a
plugin? Nope. Still, this is perhaps just a [[https://github.com/zerotier/ZeroTierOne/blob/dev/LICENSE.txt][sad, sad casualty of licensing]] (BSL).

By the way, Github, a more useful chart on some projects would identify the
anti-correlation between positive/negative Commit SLOC and then subtract the
scaled magnitude of SLOC anticorrelation from the signal. The difficulties:
finding a window function to run on any arbitrary repository and also deciding
how to renormalize the anticorrelated signal. I think that's what
anticorrelation is for. Not really a practical feature though...


* PFSense
** Docs
+ [[https://github.com/pfsense/pfsense][pfsense/pfsense]]
+ [[github:pfsense/FreeBSD-Ports][pfsense/FreeBSD-Ports]]

*** Package Development

+ [[https://docs.netgate.com/pfsense/en/latest/development/develop-packages.html][Developing Packages]]
+ [[Package Port Directory Structure][Package Port Directory Structure]]
+ [[https://docs.netgate.com/pfsense/en/latest/development/package-port-list.html][FreeBSD Ports Used For Packages]]
+ [[https://docs.netgate.com/pfsense/en/latest/development/compile-software.html][Compiling Software On The Firewall]] (don't)
+ [[https://docs.netgate.com/pfsense/en/latest/development/branches.html][Development Branch Names]]

*** Systems

+ [[https://github.com/pfsense/FreeBSD-ports/blob/devel/GIDs][GIDs]] and [[https://github.com/pfsense/FreeBSD-ports/blob/devel/UIDs][UIDs]] (from packages)

** Resources

+ [[https://difyel.com/cheatsheet/freebsd-pkg-cheat-sheet/index.html][Freebsd Pkg Cheatsheet]]
+ [[https://optionkey.blogspot.com/2022/03/restore-pfsense-backup-using-cli.html][Restore a PFSense Backup using the CLI]]

** Topics

*** Terminal

Setting your terminal to something funny like =TERM=alacritty= before =ssh= will
prevent you from editing files ... though I'm not sure why I set my term to
that.

*** FreeBSD Packages

**** Quirks

+ Requires login/logout after installing for bin's to be found in path.
+ Enable emacs shortcuts in terminal by using =sh=, but I'd rather not.

**** GNU Screen

=pkg install screen=

This one is recommended by the docs as an example ... it has no dependencies.


**** Pkg Repos

Man is not included (is this foreshadowing?)

***** TLDR:

I should probably finish reading the cheatsheet: =pkg config REPOS_DIR=

#+begin_quote
/etc/pkg/
/usr/local/etc/pkg/repos/
#+end_quote

In which case, we see the content

#+begin_quote
FreeBSD: { enabled: no }

pfSense-core: {
  url: "pkg+https://pkg.pfsense.org/pfSense_v2_6_0_amd64-core",
  mirror_type: "srv",
  signature_type: "fingerprints",
  fingerprints: "/usr/local/share/pfSense/keys/pkg",
  enabled: yes
}

pfSense: {
  url: "pkg+https://pkg.pfsense.org/pfSense_v2_6_0_amd64-pfSense_v2_6_0",
  mirror_type: "srv",
  signature_type: "fingerprints",
  fingerprints: "/usr/local/share/pfSense/keys/pkg",
  enabled: yes
}
#+end_quote


***** Adding the pfsense/FreeBSD-Ports repo

One potential solution is here [[https://forum.netgate.com/topic/130832/solution-posted-dns-tls-getdns-stubby-from-pfsense-freebsd-ports][getdns-stubby-from-pfsense-freebsd-ports]] (2018)
but it's hard to validate whether running stuff like =pkg install git= will
result in a stable system. The package dependencies seem to match the system
... for now, but they definitely overlap.

|------------------+---------------------------+----------|
| name             | origin                    |  version |
|------------------+---------------------------+----------|
| expat            | textproc/expat2           |    2.4.1 |
| p5-IO-Socket-SSL | security/p5-IO-Socket-SSL |    2.072 |
| p5-Authen-SASL   | security/p5-Authen-SASL   |   2.16_1 |
| perl5            | lang/perl5.32             | 5.32.1_1 |
| p5-Error         | lang/p5-Error             |  0.17029 |
| curl             | ftp/curl                  |   7.80.0 |
| pcre2            | devel/pcre2               |    10.39 |
| gettext-runtime  | devel/gettext-runtime     |    0.21" |
|------------------+---------------------------+----------|

... it seems that =pkg install git= is safe-ish: [[https://docs.netgate.com/pfsense/en/latest/development/gitsync.html?highlight=pkg%20git#troubleshooting][Using gitsync [to update PHP
files w/o Binary Updates)]]

***** Trying to find pkg.conf

There is =/etc/pkg/FreeBSD.conf=, but it looks like nothing's there and it tells
you to enable the wrong repository.

#+begin_quote
[2.6.0-RELEASE][user@pf.com]/root: find /etc/ -type f -exec grep -re  "FreeBSD-ports" \{\} +

/etc/inc/pkg-utils.inc:             "https://github.com/pfsense/FreeBSD-ports/commits/devel/" .

[2.6.0-RELEASE][user@pf.com]/root: find /usr/local/etc/ -name "*conf" -type f -exec grep -re "FreeBSD-ports" \{\} +

[2.6.0-RELEASE][user@pf.com]/root: find /usr/local/etc/ -type f -exec grep -re "FreeBSD-ports" \{\} +

[2.6.0-RELEASE][user@pf.com]/root: find /etc/ -type f -exec grep -re "FreeBSD-ports" \{\} +

/etc/inc/pkg-utils.inc:             "https://github.com/pfsense/FreeBSD-ports/commits/devel/" .
#+end_quote

Tracing the =pkg-utils.inc= leads to these maintainance scripts, so it looks
like I already have the repository, but it's just not enabled by a config
file. I already tried searching =/tmp= ... since I've scripted DDWRT by =nvram=
before I know how runtime state is setup there.

#+begin_quote
[2.6.0-RELEASE][user@pf.com]/root: find /etc/ -type f -exec grep -re "pkg-utils.inc" \{\} +

/etc/rc.update_pkg_metadata:    && /usr/local/bin/php -r 'require_once("pkg-utils.inc");update_repos();' \
/etc/rc.stop_packages:require_once("pkg-utils.inc");
/etc/rc.start_packages:require_once("pkg-utils.inc");
/etc/inc/pkg-utils.inc: * pkg-utils.inc
/etc/inc/pkg-utils.inc: require_once("pkg-utils.inc");
/etc/inc/system.inc:    require_once("pkg-utils.inc");
/etc/phpshellsessions/uninstallpkg:require_once("pkg-utils.inc");
/etc/phpshellsessions/installpkg:require_once("pkg-utils.inc");
/etc/phpshellsessions/gitsync:  require_once("pkg-utils.inc");
/etc/rc.packages:require_once("pkg-utils.inc");
/etc/rc.initial.defaults:require_once("pkg-utils.inc");
/etc/mtree/etc.dist:    pkg-utils.inc \
/etc/rc.bootup:require_once("pkg-utils.inc");
/etc/rc.package_reinstall_all:require_once("pkg-utils.inc");
#+end_quote


**** ZeroTier

Zerotier has no runtime dependencies which is fantastic. It only has the
buildtime deps: =as= for gas and =gmake= for making things.

+ [[https://forum-netgate-com.translate.goog/topic/178751/pfsense-plus-23-01%E5%AE%89%E8%A3%85%E9%85%8D%E7%BD%AEzerotier?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_hist=true][Forum Post on installing ZeroTier from pkg.freebsd.org]] ... but how do I get it
  from the pfsense/FreeBSD-ports repository? They say [[https://forum.netgate.com/topic/174951/pfsense-pkg-from-freebsd-ports-or-repo/11][don't do it]], but I already
  figured that out.

***** Update to the beta pfSense

Start by upgrading to the devel channel of pfsense, which is =12.7-beta= for
me. This should avoid kernel mismatch problems when installing the latest
zerotier packages.

When the system comes back online, you may need to update/refresh some packages
and restart some services. DNS and the WebConfigurator were not running properly
at first.

***** Manual install

Then install these. The grungier the system, the more essential =screen= is...

#+begin_src shell
pkg install screen
pkg install git
#+end_src

Then add the FreeBSD package tree: Edit the
=/usr/local/etc/pkg/repos/{FreeBSD,pfSense}.conf= files and change ={ enabled no
}= to =yes=.

+Run pkg upgrade and reboot+ nevermind: don't do this unless necessary. it wants
to upgrade too many packages.

Run =pkg install zerotier= and if you're running on pfSense 12.7 it will still
complain about differences in the kernel version, but they will be minimal. You
should see output like the following.

This apparently includes instructions on how to start zerotier as a service,
which was one point where I was a bit confused.

#+begin_quote
To ignore this error set IGNORE_OSVERSION=yes
- package: 1400090
- running kernel: 1400085
Ignore the mismatch and continue? [y/N]: y
Processing entries: 100%
FreeBSD repository update completed. 32316 packages processed.
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	zerotier: 1.10.6 [FreeBSD]

Number of packages to be installed: 1

The process will require 2 MiB more space.
551 KiB to be downloaded.

Proceed with this action? [y/N]: y
[1/1] Fetching zerotier-1.10.6.pkg: 100%  551 KiB 564.2kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing zerotier-1.10.6...
[1/1] Extracting zerotier-1.10.6: 100%
=====
Message from zerotier-1.10.6:

--
Note that ZeroTier 1.4.6+ has a *new* license prohibiting commercial SaaS
style usage, as well as excluding government organisations. Read the
license details carefully to ensure your compliance.

First start the zerotier service:

service zerotier start

To connect to a zerotier network:

zerotier-cli join <network>

If you are running other daemons or require firewall rules to depend on
zerotier interfaces being available at startup, you may need to enable
the following sysctl in /etc/sysctl.conf:

net.link.tap.up_on_open=1

This avoids a race condition where zerotier interfaces are created, but
not up, prior to firewalls and services trying to use them.

You can place optional configuration in /var/db/zerotier-one/local.conf
as required, see documentation at https://www.zerotier.com/manual.shtml

If your system boots from DHCP (such as a laptop), there is a new rc.conf
flag that will require that system startup will wait until the zerotier
network is established before proceeding. Note that this flag *does not*
work for systems configured with statically assigned IP addresses, and
these will hang indefinitely due to an irreducible loop in rc(8) startup
files. This flag is disabled by default.
#+end_quote

***** Testing the service

+ Config??
+ run =zerotier -d=

***** Autostarting the service

*** Ansible Collections
Yay [[https://galaxy.ansible.com/pfsensible/core][declarative configuration]]

.... i can haz declarative configuration? Well technically it's just XML, but
you don't see any that in the manual because too risky for business model. So
now it's realllly risky. It beats the hell out of MikroTik or so I've heard, but
if you're willing to reconsider, I'd like to introduce you to my friends
=Ctrl-F= and =libxml2=.

Sorry if my criticism sounds harsh, but trying to manage the firewall is verrry
slow in the GUI. Also, my working memory does not get along with 24 browser
tabs. Nice GUI though. The features are nice, but it's hard to experiment with
them while controlling variables if you can't diff configs, grok config
changesets or script things easily.

I guess I just don't know enough BSD. I did customize the shell prompt though.

** Issues

*** ZeroTier on PFSense

+ [[https://discuss.zerotier.com/t/sharing-my-experience-to-setup-zerotier-in-opnsense-and-pfsense-with-ospf/6740/17][Sharing my experience to setup Zerotier in OPNsense and PFsense with OSPF]]
+ [[https://forum.netgate.com/topic/173470/tailscale-package-now-available-on-pfsense-software][Tailscale Package Now Available on pfSense Router]] But no ZeroTier... ?
  Tailscale isn't revolutionary, it's likely brittle since it's not "the thing
  in itself."

[[https://forum.netgate.com/topic/91683/zerotier-one-as-a-package-100usd][$1000+ Bounty Stands For ZeroTier GUI in PFSense]] (see thread)

...? is this legit? a few lines of PHP?

**** Old Notes

Now that I'm really getting into this ... it would be difficult to control
access if ZeroTier isn't coming through the front door.

According to [[https://www.reddit.com/r/PFSENSE/comments/tskpkl/official_zerotier_pfsense_package/][r/PFSense]], this feature isn't being implemented, while being
available on OPNSense. There are mentions of [[https://github.com/ChanceM/pfSense-pkg-zerotier][ChanceM/pfSense-pkg-zerotier]], a
custom package implementing the FreeBSD ZeroTier 1.8.6, but it doesn't seem to
be very active.

However, there are [[https://github.com/search?q=repo%3Apfsense%2FFreeBSD-ports+zerotier&type=commits][recent commits]] to PFSense indicating the package is coming
(1.10+), but it requires installing directly from the [[https://github.com/pfsense/FreeBSD-ports/blob/main/net/zerotier/Makefile][FreeBSD "ports tree"]]. The
main difference here is that the custom package modifies the PHP and installs as
a bundle ... while also being incompatible with the fresh ports version.

The OPNSense package, which sources an older ZeroTier package comes with this
[[https://github.com/opnsense/ports/blob/87bbf9d6d93faceee98816de7f86989405f323d5/net/zerotier/pkg-message#L16-L23][important caveat]] addressing a potential race condition, which is mentioned as a
problem for the custom PFSense package. The following "sysctl" should be enabled
=net.link.tap.up_on_open=1= to address the problem (on OPNSense)


* OPNSense

** Docs

** Resources

** Topics
*** Ansible Collections

There are basically no downloads. That's sad.

** Issues

* Roam
