:PROPERTIES:
:ID:       4cdfd5a2-08db-4816-ab24-c044f2ff1dd9
:END:
#+TITLE: Programming
#+DESCRIPTION: General Info On Programming
#+TAGS:

Holy shit [[https://www.cheat-sheets.org/][The motherlode of all cheatsheets]] ... holy shit lol

Oh and also [[https://github.com/EbookFoundation/free-programming-books/blob/main/more/free-programming-cheatsheets.md][EBookFoundation/free-programming-books]] has more cheatsheets (via an
indexed [[https://sourcegraph.com/github.com/EbookFoundation/free-programming-books/-/blob/more/free-programming-cheatsheets.md#scala][sourcegraph search]], of all places). It also has books by [[https://ebookfoundation.github.io/free-programming-books-search/?&sect=books&file=free-programming-books-subjects.md][subject]] and
[[https://ebookfoundation.github.io/free-programming-books-search/?&sect=books&file=free-programming-books-langs.md][proglang]]

* Resources

** Social
** Toxicity
[[https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/code-review-antipatterns/][Simon Tatham (PuTTY): Code Review Antipatterns]]

** Functional Programming

*** AlHassy

+ [[https://alhassy.com/PathCat][Graphs are to categories as Lists are to Monoids]]
** Tools

*** Read

**** Sourcegraph

**** Codesearch

An internal Google tool using indexed regexp, with finite automata ... and
trigrams?

+ The original article: [[https://swtch.com/~rsc/regexp/regexp4.html][Regular Expression Matching with a Trigram Index]] (or How
  Google Code Search Worked)
+ [[https://about.sourcegraph.com/podcast/han-wen-nienhuys][Building The Foundation of Code Search]]: podcast with Han-Wen Nienhuys, author
  of lilypond (a great reference for Guile Scheme ... and it does sheet music,
  guitar tabs, etc)

*** Learn

**** Indexing ASTs

+ Concepts: [[https://dcreager.net/stack-graphs/][Stack Graphs]] and [[https://dcreager.net/scope-graphs/][Scope Graphs]]
+ [[https://dcreager.net/2021/06/tree-sitter-map/][Treesitter ecosystem]]
+ [[https://github.blog/2021-12-09-introducing-stack-graphs/][GH Announcment]]
+ [[https://github.com/github/semantic][github/semantic]]: treesitter-based parsing, analyzing and comparing. Used for
  Github's analysis. Maybe discontinued, not sure. Semantic generates haskell
  types from treesitter grammers and implements some of the ideas above to index
  code at scale.
+ [[github:github/stack-graphs][github/stack-graphs]] and [[https://docs.rs/tree-sitter-stack-graphs/0.7.0/tree_sitter_stack_graphs/][tree_sitter_stack_graphs]] provides the Tree Sitter DSL
  for stack graphs ... so it's more useful when trying to figure out how various
  parts of the source code interact with other parts.

Roam: [[id:aef34489-3943-4c2f-bf88-828f5ea39e16][Tree-sitter]]


** Awesome Lists

*** General

**** [[https://github.com/jwasham/coding-interview-university][jwasham/coding-interview-university]]

main resouces

+ a bunch of c/c++ [[https://github.com/jwasham/coding-interview-university/tree/main/extras/cheat%20sheets][cheatsheets]]
+ lots of structured advice on data structures and algs in the readme
+ more specific topics in [[https://github.com/jwasham/coding-interview-university/tree/main#additional-detail-on-some-subjects][Additional Detail]]
+ many book recommendations in [[https://github.com/jwasham/coding-interview-university/blob/main/programming-language-resources.md][programming-language-resources.md]].

other info

+ [[https://github.com/jwasham/coding-interview-university/tree/main#additional-books][additional books]]
+ a section on system design, which recommends starting with
  [[https://github.com/donnemartin/system-design-primer][donnemartin/system-design-primer]]. lots of links; many articles from
  [[http://highscalability.com/][highscalability.com]] (out of date, no ssl, but probably a good resource)
+ [[https://github.com/jwasham/coding-interview-university/tree/main#balanced-search-trees][balanced search trees]]
+ deep dives on garbage collection
+ [[https://github.com/jwasham/coding-interview-university/tree/main#video-series][playlists of lectures]]
+ recommendations of [[https://github.com/jwasham/coding-interview-university/tree/main#additional-detail-on-some-subjects][lectures]] for specific topics
+ recommendations on [[https://github.com/jwasham/coding-interview-university/tree/main#papers][papers]]

* Topics

** Grammar

+ [[https://github.com/FranklinChen/Ebnf2ps?tab=readme-ov-file][FranklinChen/ebnf2ps]]. There is also an ebnf2ps.el in emacs core (generates
  [[https://raw.githubusercontent.com/FranklinChen/Ebnf2ps/master/doc/doc.pdf][railroad diagrams]])
+ [[https://github.com/sergeyklay/bnf-mode][bnf-mode]] and [[https://github.com/nverno/ebnf-mode][ebnf-mode]]

*** From [[https://github.com/oils-for-unix/oils][oils-for-unix/oils]]

Oil Shell is now OSH and [[https://oils.pub/release/latest/doc/ysh-tour.html][YSH]]. Lots of interesting programming wisdom and "ysh"

+ [[https://www.oilshell.org/blog/2017/01/04.html][Success with ASDL]] (and [[https://www.oilshell.org/blog/tags.html?tag=ASDL#ASDL][#ASDL]] posts)
+ [[https://github.com/oils-for-unix/oils/blob/master/tools/find/find.asdl][find.asdl]] abstract representation of a =find= expression (example) for "an
  implementation of [[https://github.com/oils-for-unix/oils/tree/master/tools/find][find]] using =pgen2= and =asdl=." There is also [[https://github.com/oils-for-unix/oils/tree/master/tools/xargs][xargs]]
+ [[https://github.com/oils-for-unix/oils/blob/master/core/runtime.asdl][core/runtime.asdl]]: models state of shell runtime; for typed state and for
  features like array of command statuses & results
+ [[https://github.com/oils-for-unix/oils/blob/master/core/value.asdl][core/value.asdl]]: models state of intermediate representations submitted for
  evaluation (and the IR results?...)
+ runtime & value both partially extend frontend/syntax.asdl as a base


  #+begin_quote
*Zephyr ASDL* — Oils uses this DSL to declare *algebraic data types* in Python _and_
C++. We use it to represent _both_ the *syntax* of shell programs _and_ the
*interpreter's runtime data structures.*
  #+end_quote

hmmm... interesting. It's also a project that UVA worked on


+ [[https://www.oilshell.org/blog/2016/10/20.html][Parsing Bash is Undecidable]] dynamic type of variables can affect parsing of
  outer statements e.g. ~array[X=b+2*3]~ parses as an array (either indexed/assoc)
+ [[https://www.oilshell.org/blog/2017/02/11.html][From AST to Lossless Syntax Tree]]
+ [[https://www.oilshell.org/blog/2017/01/13.html][Shell has a Forth-like Quality]] (2017/1/13) on Bernstein chaining
+ [[https://www.oilshell.org/blog/2017/01/15.html][Pipelines Support Vectorized, Point-Free and Imperitive Style]]

**** Composable Shell ...

Commands

|--------+----------------+-----+---------------+----|
| sudo   | chroot         | env | /usr/bin/time | su |
| strace | systemd-nspawn | gdb |               |    |
|--------+----------------+-----+---------------+----|

builtins

|------+------+---------+---------|
| exec | time | command | builtin |
|------+------+---------+---------|


*** PEG

+ [[https://bford.info/pub/lang/peg.pdf][Parsing Expression Grammars: A Recognition-Based Syntactic Foundation]]
+ The [[https://github.com/declantsien/guix-rustup][guix-rustup]] channel has an example of [[https://github.com/declantsien/guix-rustup/blob/master/guix/rustup/build/toml.scm][Guile's PEG parser (used for toml)]]


*** ASDL

+ Abstract Syntax Description Language
+ [[https://asdl.sourceforge.net/][Zephyr ASDL]] (Source Forge)
+ =asdlGen= "takes ASDL descriptions & produces implementations in a variety of languages"
** Boilerplate

I've seen this mentioned here and there, but I swear my entire life is a
conspiracy to prevent me from learning. Is it helpful? I hate boilerplate.

*** Cookie Cutter
+ [[https://www.cookiecutter.io/templates][Templates]]
+ [[https://github.com/drivendataorg/cookiecutter-data-science][drivendataorg/cookiecutter-data-science]]
** Printing Source Code

*** Enscript

Use =enscript= to [[https://tashian.com/guides/print-out-your-code/#_][Print Out Your Code. On Paper]]. It's occasionally
useful.

**** Print Guix Home Sources

#+begin_src sh
find . -name "*.scm" -type f -exec cat \{\} + \
    | grep -ve '^;;' \
    | enscript -2rG -w html \
    --line-numbers --highlight=scheme --color=1 \
    -o /tmp/enscript.html \
    && sed -ie 's/#BC8F8F/darkgreen/g' /tmp/enscript.html
#+end_src

Or, using =cat=

#+begin_src sh
cat channels/nonguix/nonguix/build-system/*.scm | grep -ve '^;;' \
    | enscript -2rG -w html \
    --line-numbers --highlight=scheme --color=1 \
    -o /tmp/enscript.html \
    && sed -ie 's/#BC8F8F/darkgreen/g' /tmp/enscript.html
#+end_src

Remove the =-w html= and use =-o /tmp/enscript.ps= to print with =lpr
/tmp/enscript.ps= if you're feeling lucky

Enscript colors:

+ #A020F0 :: keywords
+ #BC8F8F :: strings
+ #B22222 :: comments
+ #0000FF :: recognized methods


** Visualizing Source Code

*** [[github:githubocto/repo-visualizer][githubocto/repo-visualizer]]

[[https://githubnext.com/projects/repo-visualization][Visualizing a codebase]]

** Testing

For code comprehension, extrapolation or interviews

*** Red/Green Partial Diffs

I think this might be a good way to broaden younger programmers' exposure to
code or Open Source culture or Git Forge practices, regardless of whether this
is an app that would be used to test for comprehension.

The goal is not for a student/interviewee to "fix" the code or "find the bug" --
instead these would be intended to:

+ Require less time investment than later stage technical interviews (which may
  require 5+ hours ... of free work?)
+ Filter interviewees after or perhaps before initial phone screen.
+ Provide questions that mix some structure/grading with opportunity for
  open-ended responses.

Thus, the code should be fairly "normal" while the changeset is definitely
driven by a purpose. This could either be explained a diff that:

+ corrects a bug or adds a feature
+ illustrates a possible use case (either integration test or e2e test) changes
  an interface
+ expands potential for interaction between extant design patterns
+ expands CLI options, etc
+ creates inversion of control

... But you want a large base of source material, likely 1,000+ changesets:

+ some smaller fraction of which would be repeated
+ changesets can be tagged/categorized or scored according to difficulty

Draw testing material from somewhat complicated PRs or Diffs on Github where
many lines are changed in a small number of files.

+ Obscure 40-80% of either the diff's red lines or green lines or 20% of both
+ Ask the student/interviewer to identify missing functionality.
+ Press for reasoning, reaction time, potential social reception of the Diff/PR
  (e.g. there could be problems)
+ Ask for extrapolation of changes, code or future problems
+ Potentially ask the student/interviewer to add the missing lines or to outline
  the UML/Models for unspecified interfaces (outside of the context of the )

*Technically what I've described is basically Github ...*

#+begin_quote
I was thinking last night about the "nevers" and "havent' evers" and those
quantifiably infinitessimals ... I don't think I have ever seen a single Github
notification on my desktop. Not on MacOS, Not on Github. My browser
notifications have been misconfigured for some time. But yeh, there's not much
that draws me back into Github or grabs my attention when responses are needed.

/I don't have Windows, I don't have a tablet, I don't have the GH desktop app,
My old email account crashes every client I log into, I have never used the =gh=
CLI tool because I don't put authorization cookies in my home directory/.

So yeh, given how much time I wasted on social media, I definitly regret not
using Github socially or seeking out FOSS as a kind of social network.
#+end_quote

* Pair Programming

** Apps

*** [[https://github.com/orgs/remotemobprogramming/repositories?type=all][mob.sh]]

The link points to a Github org that built mob.sh and the tools that surround
it. These are lightweight tools, which can be composed into a workflow.

+ [[https://github.com/remotemobprogramming/mob][remotemobprogramming/mob]] :: the main tool. Basically, a protocol where, given
  a branch prefix/name, then a group can collaborate on incremental commits. any
  kind of conference call, streaming, etc is completely outside it's area of concern.
+ [[https://github.com/remotemobprogramming/posignal][remotemobprogramming/posignal]] :: pull product owners into a Zoom
+ [[https://github.com/remotemobprogramming/timer][timer.mob.sh]] :: this is a shared "room" with just a timer & a list of users.

And editor plugins. Since these are simply wrappers around =mob= cli and since
mob.sh is just a wrapper around =git= index, refs and cli (mostly cli), then you
don't need the editor plugins necessarily.

*** [[https://zed.dev/][zed.dev]]

Pairing IDE

*** [[https://code.librehq.com/qhong/crdt.el/][crdt.el]]

Emacs pairing based on [[https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type][CRDT (conflict-free replicated data types)]]

** Topics

*** Ensemble Programming
*** Code Retreats
+ [[https://www.coderetreat.org/facilitators/gameoflife/][Game of Life]]
*** Problems
+ [[https://www.cs.cornell.edu/courses/cs1380/2018sp/textbook/chapters/08/3/monty-hall-problem.html][Monty Hall Problem]]

* Bison Parser Generator

* Antlr Parser Generator
** Docs
+ [[https://github.com/antlr/antlr4][antlr/antlr4]]
+ [[https://github.com/antlr/grammars-v4][antlr/grammars-v4]] and [[https://github.com/antlr/grammars-v4/wiki][wiki]] for example grammars
** Resources
+ [[https://github.com/teverett/antlr4-cpp-example][teverett/antlr4-cpp-example]] but this is for modelica...
+ [[https://tomassetti.me/getting-started-antlr-cpp/#][Getting started with Antlr Cpp]] this covers generating cpp code

** Topics

*** Python

**** Where?

=java-antlr4-runtime-python= is used in:

+ [[https://cps.pages.gitlab.lrz.de/commonroad-route-planner/][CommonRoad's Route Planner]] for OmegaConf
+ [[https://github.com/notofonts/nototools][Nototools]] for Google's Noto font (for [[https://github.com/adobe-type-tools/afdko][Adobe's font devkit]])

[[file:img/antlr4-revdeps.svg]]

***** OmegaConf

#+begin_quote
OmegaConf is a hierarchical configuration system, with support for merging
configurations from multiple sources (YAML config files, dataclasses/objects
and CLI arguments) providing a consistent API regardless of how the
configuration was created.
#+end_quote

Well that answers a really big question I've had (I think)... I just never
thought there was actually a practical answer.

#+begin_src python
import sys
import OmegaConf
# sys.argv = ["script.py", "srv.port=82"]
conf = OmegaConf.from_cli()
# conf == { srv: { port: 82 } } # basically
#+end_src

Variable interpolation: this lets you automagically use Python dataclasses
(instead of Ruby) to merge objects together, all in the pursuit of
re-implementing =&yml_std_features=. So far, anyways (see [[https://docs.google.com/presentation/d/e/2PACX-1vT_UIV7hCnquIbLUm4NnkUpXvPEh33IKiUEvPRF850WKA8opOlZOszjKdZ3tPmf8u7hGNP6HpqS-NT5/pub?start=false&loop=false&delayms=3000&slide=id.g84632f636b_5_135][2.2 slides]]). Those don't
really scope beyond a single file though. Also:

+ string interpolation
+ custom resolvers: specification of functions in yaml
+ =env.VARS= resolver

It basically allows your python code to hint the order of evaluation when
merging configs

+ You can choose =DictConfig= or types
+ You can =freeze= objects before (or after?) merging them into a =StructuredConfig=
+ You can lazily evaluate environment or process-specific details

***** Antlr4 in OmegaConf

The grammar has already generated code in the project, which uses =antlr= to
ensure completeness of expressions contained in YAML.

+ [[https://github.com/omry/omegaconf/blob/fa8461729021558f19a538bcac789105c173637e/omegaconf/grammar_parser.py][./omegaconf/grammar_parser.py]]
+ [[https://github.com/omry/omegaconf/blob/fa8461729021558f19a538bcac789105c173637e/omegaconf/grammar_visitor.py][./omegaconf/grammar_visitor.py]]

**** Testing Enumeration of C++ headers

From [[https://github.com/antlr/grammars-v4/tree/master/cpp/Python3][antlr/grammars-v4 ./cpp/Python3]]

#+begin_src shell
git clone https://github.com/antlr4/grammars-v4
cd cpp

# the second one gives you the antlr4 python import
guix shell antlr4 java-antlr4-runtime-python python

lexer=CPP14Lexxer.g4
parser=CPP14Parser.g4

python3 transformGrammar.py
#+end_src

That ... does something:

#+begin_example diff
diff --git a/cpp/CPP14Parser.g4 b/cpp/CPP14Parser.g4
index d89a8a83..39c5e667 100644
--- a/cpp/CPP14Parser.g4
+++ b/cpp/CPP14Parser.g4
@@ -817,8 +817,8 @@ memberDeclaratorList
 memberDeclarator
     : declarator (
         virtualSpecifierSeq
-        | { this.IsPureSpecifierAllowed() }? pureSpecifier
-        | { this.IsPureSpecifierAllowed() }? virtualSpecifierSeq pureSpecifier
+        | { self.IsPureSpecifierAllowed() }? pureSpecifier
+        | { self.IsPureSpecifierAllowed() }? virtualSpecifierSeq pureSpecifier
         | braceOrEqualInitializer
     )
     | declarator
#+end_example

Then =python= to start a repl

#+begin_src python
# import Python3.CPP14ParserBase

# or from ./cpp/Python3 (but this requires __init__.py, I think)
# import .CPP14ParserBase

from antlr4 import * # this may be needed beforehand
from Python3 import CPP14ParserBase

help(CPP14LexerBase) # for help
help(CPP14ParserBase)

f="../../chromium/src/apps/switches.h"

# from Gemini
with open(f, 'r') as file:
  data = file.read()

# this sets up a pipeline, but not sure where the start button is
input_stream = InputStream(data)
lexer = CPP14ParserBase.Lexer(input_stream)
token_stream = CommonTokenStream(lexer)
parser = CPP14ParserBase.Parser(input_stream)

# (parser.state == -1)
# ... i'm pretty sure that's bad

parser.getNumberOfSyntaxErrors() # ... hmmm. good?
parser.getCurrentToken() # 47! 47 is very good.

# .... yeh it expects java-style iterators (need to build out the Visitor or it
# doesn't do anything)
#+end_src

Just use =grep=. Parser doesn't =.parse()=. I just need to reflect across the parse
results. I don't really have time. For as many languages as there are examples,
IDK where to go to figure out how =antlr4= expects its generated grammars in each
langauge to behave -- there are about 10 languages per language.

+ [[https://github.com/antlr/grammars-v4/blob/master/_scripts/templates/Python3/st.Test.py][_scripts/templates/Python3/st.Test.py]] this may help.
+ OmegaConf is like built like a machine ... I can't bounce around 50+ python
  files for =antlr= on a whim without some context clues.

** Issues
