:PROPERTIES:
:ID:       e967c669-79e5-4a1a-828e-3b1dfbec1d19
:END:
#+TITLE:     Route Switch
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

* Linux Routing

** VyOS

+ [[https://blog.kroy.io/2019/11/21/battle-of-the-bare-metal-routers/][Battle of the Metal Routers]]
+ [[https://blog.kroy.io/2019/08/23/battle-of-the-virtual-routers/][Battle of the Virtual Routers]] (VyOS)

* Cisco

Can't find the notes...

** Docs

** Resources
+ [[https://etherealmind.com/cisco-ios-cli-shortcuts/][Cisco IOS Shortcuts]]
+ [[https://www.cisco.com/c/en/us/support/ios-nx-os-software/ios-15-0s/products-command-reference-list.html#anchor913][Cisco IOS Command Reference]]

*** SSH Configuration

+ [[https://www.cisco.com/c/en/us/support/docs/security-vpn/terminal-access-controller-access-control-system-tacacs-/10384-security.html][Configure AAA on an access server]]
+ [[https://www.firewall.cx/cisco-technical-knowledgebase/cisco-routers/1100-cisco-routers-ssh-support-configuration-rsa-key-generation.html][Enabling/Configuring SSH on Cisco Routers]]

** Topics

*** Usability

+ =do show ...= from within config modes
+ =show run | beg $KEYPHRASE= is very helpful
+ Use the linux vtty's and serial.
  - SSH and IP config aren't needed this way. No lost connections.
  - i.e. you're better off on a server without a GUI
+ run =set BAUD 115200= in ROMMON for faster connection.
  - commands output much more quickly.
  - 9600 is 1200 bytes per second...

*** Configure NTP

AHHH! 1993? What the fuck?

#+begin_src ios
show ntp status
show ntp associations
#+end_src

Configure PFSense to act as an NTP server, then get the switch to talk to it.

From =conf t= configure an [[https://www.cisco.com/c/en/us/td/docs/switches/connectedgrid/cgs2520/software/release/12_2_53_ex/configuration/guide/scg2520/swadmin.html?dtid=osscdc000283#98219][ntp server association]]

#+begin_src ios
ntp server $ip
#+end_src

Cisco appears to support NTP authentication, but PFSense indicates I need
=NTPv3= and I just don't feel like winning that round of trivia at the
bar. Usually when protocol versions of something are needed for this device, I
just err on the side of "i don't actually have smartnet", but it looks like my
switch does support NTPv3. Unfortunately, NTP usually flows freely through a
network, so not using this could render you susceptible to drift attacks, though
Cisco's usage of MD5 really makes you wonder.

#+begin_quote
We all remember what happened with Windows and MD5, right? We remember that,
right? ... no, no one remembers anything that happened more than a week ago.
#+end_quote

Some points on security of old cisco devices generally:

- The lack of smartnet-enabled IOS updates means that you only get
  "critical" security updates, so you can't have nice things like =ecdsa= which is
  far more efficient to calculate.
- There's no way these devices have an equivalent to =AES-NI= instructions
  AFAIK. But block ciphers related to those are the only ones you can select
  from.
- I don't know the implementation details for =ecdsa= but I'm guessing most
  CPU's can handle it, but lack the software requirements. My switch offers the
  option in autocomplete ... and just errors out when you try to use it.

Given the usage of weak crypto: the key takeaway here is that if you don't
configure =ntp= with authentication on an old Cisco device, you really need to
ensure that =port 123= traffic could only reach it if it's emitted from that
network. I'm not sure what PFSense does with =scapy= packets generated from an
insecure subnet, but if it doesn't reject them (and it probably won't), then you
need a floating firewall rule to filter that from the outside in.

**** No Practical Free & Open Network Devices that can be automated?

The lack of reasonably configurable open/free options for route/switch/firewall
is particularly infurating. Well plebs, if you want to automate your network
gear for your "smart" home, you better start paying up. Your cloud bill is due
and it's easily $500. You could always invest hundreds of hours managing your
network, but why not give a handful of corporate giants alllll of your data.
It's properly secured with encryption isn't it?

This is almost as infurating as the lack of decent features on that Cable
Company router that you're perpetually "renting" ... which is almost as
infuriating as the leverage that ISP's generally have when selling your
data. That IPv6 makes it fairly easy to use a combination of devices (even with
the proper DHCPv6 or SLAAC) to unmask the identity of a network assigned a
dynamic IP is a little unsettling given the number of "smart" devices in your
home.

*** Copy files from flash

This is a bit hard to search, given that downloading an IOS image from a TFTP
server is the first thing you learn in a CCNA course. There's shortage of
indexed internet content on that. I didn't try, but I don't think ChatGPT could
provide a solution here. Most of the questions I have are difficult to answer.

Fortunately, there's an [[https://www.cisco.com/c/en/us/td/docs/ios/fundamentals/command/reference/cf_book/cf_t1.html][alphabetized command reference]] that describes how to get
the switch to /act as a TFTP server/.

**** Get you a TFTP client.

Preferably one that doesn't stick around on your system.

#+begin_src shell
guix shell tftp-hpa
#+end_src

Inspect the file systems on the switch. Not your switch, but the one in this
[[https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst3850/software/release/3se/system_management/configuration_guide/b_sm_3se_3850_cg/b_sm_3se_3850_cg_chapter_010011.html][incomprehensible URL]]. Although I guess you can find device-specific docs by
using "my devices" in Cisco. I was under the impression that required smart
net.

I guess I'm irritated because it's realllly complicated to answer the question
"what _actual features_ do my device and IOS support?" So I have the sneaking
suspicion that my device only supports =3072-bit= RSA keys and I remember it was
tough to transfer files. So if I use =4096-bit=, does that mean i'll have to
start over after getting vague errors? Only way I know to find out is to try.

**** List files on the device

#+begin_src ios
show filesystems

dir
dir flash:
#+end_src

Delete files

#+begin_src ios
delete flash:$keyname*
#+end_src

Generate your keys (see [[https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/security/a1/sec-a1-xe-3se-3850-cr-book/sec-a1-xe-3se-3850-cr-book_chapter_0110.pdf][PDF for 3800 series switches]])

#+begin_src ios
crypto key generate rsa label $hostname exportable 4096 storage flash:
#+end_src

And here I discover what I already found (but I guess didn't note) ...

the =flash:= file system cannot store crypto keys and =show usb controllers= is
not a valid command. soooo. =xmodem:= it is ..............

**** Start the TFTP Server

Generate your keys and start the TFTP server on the switch

#+begin_src ios
tftp-server flash
#+end_src

*** Configure SSH


**** From old notes

*Caveat Lector:* This section contains an incomplete description of the process,
but it includes some some useful tricks using GNU screen if you're on a serial
connection.

Particularly, some of the older hardware uses older algorithms, but also
certificate formats that are non-standard (or at least unusual), which makes it
a bit wierd to import. I can't remember which method I got to work: either
transferring files via =xmodem= or transferring text.

***** TODO Describe problems with =crypto key rsa import=

Yeh, som of this is reaaly really bad.

***** Importing External Keys

=crypto key rsa import $KEYNAME pem url xmodem:/file= was working for
either public or private keys (when one was in PEM format).

This approach wasnt working for me -- SSH user setup just needs
=key-string= anyways.

***** Generating Keypairs

- Run =crypto key rsa generate rsa modulus 4096= to generate a generic
  keypair. This requires a hostname & domain name.
- Validate generation/upload with =do show crypto key mypubkey all=
- Remove keys with =crypto key rsa zeroize $KEYNAME=

***** Setup SSH

This will let you remotely manage your router (and use tools like
ansible)

+ Configuring SSH from Linux
  - IOS doesn't accept DSA or OpenSSH keys
  - keys need to be in the format of =ssh-rsa ... comment=
+ Refer to this post on [[https://nsrc.org/workshops/2016/renu-nsrc-cns/raw-attachment/wiki/Agenda/Using-SSH-public-key-authentication-with-Cisco.html][Cisco/SSH via Linux]]

****** Generate keys

Older cisco devices want RSA, but generating 4096b keys on the device
takes forever.

+ Run =ssh-keygen -t rsa -b 4096 -f $FILENAME=
+ Use screen & =exec !! fold= to copy/paste into the key-string
  - or modify the key-string in a config that you upload
+ Verify the key with =ssh-keygen -E md5 -lf $FILENAME.pub=

***** Configuring SCP Transfers

****** TODO maybe figure this out someday. maybe not.

*** Linux Tools for Cisco

**** TFTP: =dnsmasq=

Ensure your firewall is temporarily configured. Only TFTP downloads
are allowed.

=dnsmasq --no-daemon --enable-tftp --tftp-root=$TFTPROOT -i $IFACE=

**** Serial: =screen=

***** Enable Linux Serial for User

Find the =/dev/ttySn= serial file. Also, add user to =dialout= group.

For faster connection, run =set BAUD 115200= or the serial gnomes won't favor
your file transfers.

***** Use Screen to Transfer Files to IOS via Serial

To transfer files like IOS updates, type =C-a := in screen. Then run =exec !! sx
-b -X $FILENAME= to copy.

The =-b= flag pipes binary data into screen, so the IOS terminal can be expected
to receive it. From what I remember, this is tricky to time right.

At the correct time, press the button after typing:

=copy xmodem:/flash:/filename.bin=

Press it again if it didn't work. Also, this must be done from within ROMMON,
unless the =copy= menu gives you access to =xmodem:=

***** Pasting A Big SSH Key

To emulate copy/paste in screen, enter content into a file, then type =C-a := in
screen to run Screen commands.

Run =exec !! fold -bw72 $FILENAME= and the content will be piped in as input.

Cisco has a maximum of 254 chars per line, so the =-bw72= arg specifies a
maximum.

***** Updating IOS from ROMMON

Refer to this post to [[https://stelfox.net/2019/reflashing-cisco-catalyst-with-xmodem/][Reflash Cisco Catalyst with XMODEM]]


** Hardware

*** 2960



* Avaya

** Issues

*** Ctrl-y

Avaya expects a "Ctrl-y" after boot. This is displayed to a user
connecting to a console (with putty/etc) ... if the console cable is
connected during the boot.

* DDWRT

** Docs

*** Top Wikis

+ [[https://wiki.dd-wrt.com/wiki/index.php/Useful_scripts][Useful Scripts]]
+ [[https://wiki.dd-wrt.com/wiki/index.php/TFTP_flash#Linux][TFTP Flash (linux)]]
+ [[https://forum.dd-wrt.com/phpBB2/viewtopic.php?t=51486][The "Peacock" Thread]] old, but lots of useful info

*** Firewall

+ [[https://forum.dd-wrt.com/wiki/index.php/FirewallExample][Firewall Example]]
+ [[https://forum.dd-wrt.com/wiki/index.php/Firewall][Firewall]]
+ [[https://forum.dd-wrt.com/wiki/index.php/Firmware_FAQ#Which_router_should_I_buy.3F][Firmware FAQ]]
+ [[https://forum.dd-wrt.com/wiki/index.php/Installation#Is_Your_Router_Supported.3Fhttps://forum.dd-wrt.com/wiki/index.php/Installation#Is_Your_Router_Supported.3F][Installation]]

**** Netgear R7000-specific

+ R7000 [[https://wiki.dd-wrt.com/wiki/index.php/Category:R7000][wiki articles]]
+ R7000 [[https://forum.dd-wrt.com/phpBB2/viewtopic.php?t=264152][best practices]] (forum)

** Resources

*** Guides

This guy has guides with the r7000 router

+ [[http://www.regressionist.com/2020/07/05/poor-mans-cluster/][Poor Man's Cluster]]
+ [[http://www.regressionist.com/2020/06/11/securing-a-research-vlan-on-a-retail-router-with-dd-wrt/][Securing a research VLAN on a retail router with DD-WRT]]
+ [[http://www.regressionist.com/2020/06/14/kickstarting-from-my-dd-wrt-router/][Kickstarting from my DD-WRT Router]]
+ and to top it off: [[http://www.regressionist.com/2020/06/20/reviews-of-distributed-filesystems/][Reviews of Distributed File Systems]]
+ [[https://www.tweaking4all.com/hardware/netgear-r7000-dd-wrt/][Netgear R7000 specific instructions]] (2014)

*** Scripts

**** [[https://github.com/tknarr/ddwrt-nvram-tools][tknarr/ddwrt-nvram-tools]]

+ nvram_dump & nvram_build scripts
+ diff your nvram backups
+ my notes say: "doesn't quite work" but seeing the code solved my problems

**** [[https://github.com/impressiver/ddwrt_conntrack][impressiver/ddwrt_conntrack]]

+ QoS IP Connection Tracking/Bandwidth Monitor

**** [[https://github.com/daenney/ddwrt-snmp_exporter][daenney/ddwrt-snmp_exporter]]

+ yaml file to enable "prometheus" to scrape DDWRT routers for SNMP

**** [[github:carlosedp/ddwrt-monitoring][carlosedp/ddwrt-monitoring]]

+ monitor ddwrt with prometheus/graphana (configs only)


** Topics

*** Basic Install/Config

Some generic steps to walk through in the webui

**** Install
+ Reset Netgear Router
+ Walk through initial Netgear setup (one last time)
+ Then flash the *.chk file to the router

**** Initial Config
+ Set a new admin/password
+ Disable wifi radios
+ Set time zone
+ Configure Gateway
  - network/cidr/gateway
+ Configure LAN
  - network/cidr/gateway (and a router IP address)
+ Configure DHCP
+ Configure NTP
  - most external router should sync to =time.nist.gov=
+ Configure Administration settings
  - change protocol to HTTPS
  - disable info site
  - restrict  remote ip range

*** Intrusion Detection

If socat can run, then it should be possible to use it (and maybe light
iptables) to intercept traffic streams, duplex them and forward them to an
off-device instance of snort or something

#+begin_quote
... this is without something like an $500 ARM device or the $100 [[https://shop.hak5.org/products/throwing-star-lan-tap][Hak5 ethernet
ninja star]] thing that only people with annual average salaries above that of
Saharan Africa can afford.

Ahhhh it really pays to be poor. It's about the journey, not the destination! It
really ~just~ forces you to develop smart ways /just/ to get around -- which is
obviously something most people appreciate! That's why people like Marc Cuban
value keeping their kids poor of course. So they have a well-balanced
perspective and a background with challenges to overcome.
#+end_quote

*** Filesystem


**** /tmp (ramfs)


**** /jffs (jffs2)

+ [[https://wiki.dd-wrt.com/wiki/index.php/Jffs][Journaling Flash File System]]


*** SSH

This requires RSA-2048 which has bit me so many times

*** [[https://wiki.dd-wrt.com/wiki/index.php/Ipkg][ipkg]]

A package manager that can get =socat= on the device somehow...



** Issues

*** ipkg commands report missing files or read-only file system

+ [[https://forum.dd-wrt.com/phpBB2/viewtopic.php?p=503846][old post]] seems to indicate missing modules or potential storage issues

