:PROPERTIES:
:ID:       01ace2d7-1324-4dd2-9e2e-d5c152fdc378
:END:
#+TITLE: Social Physics
#+DESCRIPTION: We live in a society
#+TAGS:

"Every sufficiently intelligent person is each a unique standard candle ... for
overlapping subspaces of an infinite-dimensional space."

* Docs

** te.xel.io

It's a bit ranty. Sue me.

*** Speed of Thought

+ [[https://te.xel.io/posts/2017-09-22-speed-of-thought-illusion-of-separation.html][The Speed of Thought: Illusion of Separation]] (part 1)
+ [[https://te.xel.io/posts/2017-10-30-speed-of-thought-sociophysical-postulates-1-to-11.html][The Speed of Thought: Sociophysical Postulates I–XI]] (part 2)
+ draft: [[https://github.com/dcunited001/dcunited001.github.io/blob/sources/_drafts/2017-11-01-speed-of-thought-sociophysical-postulates-12-to-20.md#postulates-of-sociophysical-systems][The Speed of Thought: Sociophysical Postulates XII–XX]] (part 3)

* Resources
* Topics

** Drafts

*** A Typology of Occupations, Delineated by Sociophysical Mechanics & Dynamics

Another draft: [[https://github.com/dcunited001/dcunited001.github.io/blob/sources/_drafts/a-sociophysically-dilineated-typology-of-occupations][A Sociophysically Delineated Typology of Occupations]]

This draft was from late-ish November 2017. IDK when it was written, but [[https://github.com/dcunited001/dcunited001.github.io/commits/sources/_drafts/a-sociophysically-dilineated-typology-of-occupations][here
are the commits]]. I was working on this IMMEDIATELY before that time someone
threw me at the police. okay ... for emphasis it was IMMEDIATELY before someone
threw me at the police. There's not much here, but I wanted to explore this idea
as applied to specific occupation types. It's sad that high-magnitude trauma can
cause you to completely forget all the other little things happening around the
same time.

I brought this up once or twice to my family. I can't imagine they would
remember this or almost any other /specific/ idea I've had. They didn't care. At
all. Once that all went down, i kinda forgot about it.

#+begin_quote
There are financial resources, social resources and informational resources. The
first two exist entirely within the latter.
#+end_quote

This article, in particular, was important to me because writing it would help
me imagine more optimal ways to recover social resources. At the time, there was
a abyss of social resources in my life -- I WAS SOCIALLY POOR, in addition to
being financially poor. Therefore, if I needed "just a regular job", you'd think
that people would want to maybe consider what I was saying or writing


** "Postulates"

Postulates ⌈i⌉ – ⌈xi⌉ of Sociophysical Systems

#+begin_quote
⊗ ∆ ⌈i⌉ There Are Infinitely Many Types of Sociophysical Energy Having Both Linear And Non-Linear Mechanics That Determine Their Equivalence and Interaction Dynamics

⊗ ∆ ⌈ii⌉ Mechanics of Social Interactions And Connections Are Physical and Logical, But Increasingly Virtualized

⊗ ∆ ⌈iii⌉ Power Describes The Rate of Energy Fluxing Through Sociophysical Networks

⊗ ∆ ⌈iiii⌉ Social Power Depends On Potentials For Types Of Energy Flux, Each Actual And Perceived

⊗ ∆ ⌈v⌉ Perceived Beliefs Drive Social Power Dynamics Via Positive and Negative Feedback Loops

⊗ ∆ ⌈vi⌉ Agents Have Varying Degrees Of Autonomy and Individual Definitions Of Energy Types. They Share Traits, Such As Concurrency, Bandwidth and Physicality

⊗ ∆ ⌈vii⌉ To Hedge Against Domain Complexity, Agents Amplify Perceived Beliefs And Interact In Other Ways

⊗ ∆ ⌈viii⌉ Spectral Coherence of Knowledge, Information and Agent Context Strongly Influences Conceptualization and Anticipation

⊗ ∆ ⌈ix⌉ Social Circuitry Enables Sociophysical Energy Flows, Where The Superposition Principle Applies Circuit and Network Topologies. All Exist Simultaneously

⊗ ∆ ⌈x⌉ Social, Financial and Other Energetic Flows Signal Interest and Intent Via Frequency, Magnitude and Abstract Spectral Decomposition

⊗ ∆ ⌈xi⌉ Disruption of Connections & Interactions Alters Flow Of Energy & Power, Physically, Logically and Virtually
#+end_quote

Postulates ⌈xii⌉ – ⌈xx⌉ of Sociophysical Systems

#+begin_quote
⊗ ∆ ⌈xii⌉ Even When Invisible, Intent Is Further Signified And Clarified By Parallel, Anti-Parallel and Orthogonal Orientations of Motion As They Relate to Laplacian of High-Dimensional Surfaces

⊗ ∆ ⌈xiii⌉ Whether Cognizant, Nearly All Attach Their Behavior, Thoughts and Identity To Equilibria In Social Games. While Unbound From Conceived Attachments, Our Energy Becomes Labile, Formless, Trackless and Incomprehensible to Those Who Lust For Power.

⊗ ∆ ⌈xiv⌉ The Evolutionary Dynamics of Social Physics Build Upon Antifragility and the Ideas of Programs in Chaos

⊗ ∆ ⌈xv⌉ For Timescales Both Small and Large, Each Agent’s State and Context Is Constructed From Their Sum Of Experience Via Directed Focus

⊗ ∆ ⌈xvi⌉ Everything is a particle. Everything is a Wave. Even Information, Modeled Holonically

⊗ ∆ ⌈xvii⌉ Models of Sociophysical Phase Change Require Topological Spaces Imbued Onto Physical and Aphysical Topologies

⊗ ∆ ⌈xviii⌉ Independence and Connectedness Can Be Measured In Sociophysical Network Topologies

⊗ ∆ ⌈xix⌉ For The Efficient and Pragmatic Assertion of Behavior and Intent, Sociophysical Configuration Entropy is Nearly Unparalleled

⊗ ∆ ⌈xx⌉ Information In Holonic, Particle Form Exhibits Complicated Behavior Analogous To Entanglement
#+end_quote
* Issues

* Roam
