:PROPERTIES:
:ID:       033c8d7d-1069-4001-a880-172c55db603c
:END:
#+TITLE: Social Media
#+DESCRIPTION: Social Media
#+TAGS:

* Docs
* Resources
* Topics

** Sociological Adaptation to Social Media

*** Heideggar's "Many Man"

Deconstructing this quote and recombinating it a bit illustrates how social
media has changed how people develop consensus on other individuals' identities.

#+begin_quote
"Every man is born as many men and dies as a single one"
#+end_quote

The quote contrasts a being's past and future potentials by comparing the extremes. 
Unfolding the social dimensions -- from groups' perception(s) of an individuals' 
potentials, extending to the groups' reflections on those perceptions -- very quickly we
experience the discomfort of complexity induced by combintorial explosion. Society
facillitates and attunes itself to consensus to avoid the very same angst induced by
the seven pluralized concepts above.

# salience

# ... trying to segue to the point (before i depart), which is that social media
# restricts the variety of early experiences people (while also restricting the
# dimensionality of features: visual/auditory/verbal/etc. we instinctually follow
# others' visual fields, reacting to eye, head, torso rotation with increasing 
# certaintly as to intent/stimulus/meaning). 

# possibilities 
# Older generations' accumulated 
# experience constrains perceived potential, counterbalanced by hope, wisdom and
# humility. 

# As memory ages, past experiences
#
#  constrain the variety of paths left open
# 
# tends to overconstrain how 
# The variety of paths one's life  may take are  constrained
# dimension that develop about someone's life trajectory. 

Students
who are talented early on often don't continue developing with the same promise.
The development of a precocious genius is full of paradoxes. 

+ Truly gifted and they shouldn't need to ask questions. Even if extremely creative
  & intelligent, they don't miraculously have knoweldge their mind didn't derive.
  Determining what to plan for them to learn & balancing thas with what they
  should discover on their own is difficult. Learning from a book or from rigid
  instruction is fast/efficient, but you're basically copying.
+ If they don't ask questions, how can you measure their interest or depth of
  understanding?
+ If they're smarter than most adults around them, how can they accurately judge
  the potential?

Basically, your life has a trajectory with first and second derivatives. As you
prove yourself, people will invest more energy into you. More doors open. Then
you reach adolescence and your own understanding of life's potential changes. A
child that's not prepared for this (whether sheltered or discouraged by challenge/effort)
will change or may become disillusioned. At any point, if the people around the "gifted
person" suddenly develop a new consensus on their potential, their second derivative
falls fast (but may still be positive). Regardless of what position you attain
as a intellectual (or really in any field), eventually your "fuel" is spent. Everyone
can see where the trajectory was headed the whole time (or so they think)

The relation to social media results from /how/ people develop consensus. It used
to be that everyone met people for themselves. Most of life (whether yours
or someone else's) was unknown until some first-hand or third-hand interaction 
caused you to develop your own understanding of someone, some story, some idea. 
This process continues to function almost identically on many levels levels...

one particularly important change: the rate of consensus formation has dramatically
accelerated (in most ways). 

there shouldn't be a single Silicon Valley working in
a technical or financial role who doesn't understand consensus. After all, RAFT and
PAXIS were huge developments in the field because the improvement fundamentally changed
conditions of possibility. Increase rates of information transmission & processing: 
ensure that data becomes consistent in distributed computing.

people are not much different. someone's apparent range of trajectories will tend
to collapse into a more limited range of possibilities -- collapse here refers to the contraction
of statistical parameters which decreases entropy and reduces the domain over which
a distribution's measure can be found. this is partly because the social infrastructure
over which consensus occurs permits faster consolidation & redistribution of belief.
obviously, how an individual reacts can affect the process ... but usually the only
thing to be done is nothing -- i.e. there isn't much an individual can do to correct
rumor mill, poison pen ..or maybe less malicious disfiguring circumstances.

My focus here is really less about "bad things happened to someone" and more about
the loss of the individuals's control over what happens, whether Alice's influence
over the perception of their identity or Bob's influence over how society 
generally receives Alice. It's clear that social media doesn't ruin everyones lives
(at least not yet).

"Genius trajectory" is only an example where, clearly, society
must judge the potential of someone whose ideas and skills can't be fully comprehended.
While counterfactuals here are impossible, for society to accurately determine
trajectory (an assessment potential for knowledge, intelligence, personality, motivation of motivation, etc from the age of 
'weeble wobble' to rocket scientist), then for the most part, they would only know
indirectly. 

Returning ontology, Being, and Time:






** Threads
*** Launch

Did FB really just steal Twitter AND Reddit — at the same time? That’s gotta be
a first. Stonks++

I wouldn’t be surprised if this fortunate confluence of tailwinds for Threads
ends up in the doldrums:

+ It’s still not Twitter, the Threads brand name is generic and lacks luster
+ You can’t delete your account and you're just providing more links between
  data and your identity
+ What about FB groups: how is this different, really?
+ Users may quickly lose interest, but it will hang on for a while.
+ The social media slots can only keep you hooked for so long.

**** Threads Doesn't Have A Business Model

It doesn’t have a real business model and represents a large money pit. The
infrastructure costs that Twitter are dealing with are pretty much the same as
the cost structure threads has ... the main difference is that the employees FB
hired from Twitter can work on greenfield projects while Twitter must awkwardly
transition away from a minefield of microservices.

So Threads is definitely a large cost sink with no real promise of monetization.
How Facebook's profitability, revenues and costs translate into it's
fundamentals' affect on Meta share price will determine whether this was a good
move or not. It seems like they've thought about this for a long time and
opportunism caused them to pull the trigger on it. That doesn't make it a good
move in the longterm it simply didn't have a long viable window of opportunity.

There are many SEO benefits of operating a Twitter clone if it's sufficiently
active. As Twitter limits what data Google has access to, then Twitter's
conversations don't influence search rankings. Threads can unseat Twitter in
some way in this regard for a time, which is a shame because people should be
willing to pay Twitter's API pricing. Twitter's past ability to influence Google
search results I think has been overlooked, but if I'm correct, then it is an
incredibly powerful amplifier for the kind of information that shows up in
Google's results.

**** Censorship will be counterproductive

While the political animus motivating people to flee to Threads is an
interesting "Social Complex," it only has so much power in and of itself.  Most
people are already disillusioned with either being censored or not having enough
censorship. Threads isn't going to fix this and Twitter's conversations will be
more interesting. A preeminant social network with less restrained dialectic &
dialogue will determine the course of conversations outside of that
network. This is a bit like Othello: the larger players occupy the outside,
cannot easily be unseated and will determine the course of what happens in the
middle, since ideas do not require digital channels to spread.

The way the left has treated Elon Musk is so telling. When I'm thinking --
people need to empower themselves with knowledge on whatever they're capable of
doing, whether it's engineering, science or actual policy work (Int'l law, FDI,
USAID, think tanks, etc) -- few people would exemplify that more than SpaceX and
Tesla. I actually care about the climate, but the magnetism this social complex
exerts oon the left leads them right off a cliff like a stampede of lemmings.
You can't solve any real problems in the world if you cannot deal with things
you don't like or that make you uncomfortable. Get over it.



* Issues

* Roam
