:PROPERTIES:
:ID:       033c8d7d-1069-4001-a880-172c55db603c
:END:
#+TITLE: Social Media
#+DESCRIPTION: Social Media
#+TAGS:

* Docs
* Resources
* Topics
** Threads
*** Launch

Did FB really just steal Twitter AND Reddit — at the same time? That’s gotta be
a first. Stonks++

I wouldn’t be surprised if this fortunate confluence of tailwinds for Threads
ends up in the doldrums:

+ It’s still not Twitter, the Threads brand name is generic and lacks luster
+ You can’t delete your account and you're just providing more links between
  data and your identity
+ What about FB groups: how is this different, really?
+ Users may quickly lose interest, but it will hang on for a while.
+ The social media slots can only keep you hooked for so long.

**** Threads Doesn't Have A Business Model

It doesn’t have a real business model and represents a large money pit. The
infrastructure costs that Twitter are dealing with are pretty much the same as
the cost structure threads has ... the main difference is that the employees FB
hired from Twitter can work on greenfield projects while Twitter must awkwardly
transition away from a minefield of microservices.

So Threads is definitely a large cost sink with no real promise of monetization.
How Facebook's profitability, revenues and costs translate into it's
fundamentals' affect on Meta share price will determine whether this was a good
move or not. It seems like they've thought about this for a long time and
opportunism caused them to pull the trigger on it. That doesn't make it a good
move in the longterm it simply didn't have a long viable window of opportunity.

There are many SEO benefits of operating a Twitter clone if it's sufficiently
active. As Twitter limits what data Google has access to, then Twitter's
conversations don't influence search rankings. Threads can unseat Twitter in
some way in this regard for a time, which is a shame because people should be
willing to pay Twitter's API pricing. Twitter's past ability to influence Google
search results I think has been overlooked, but if I'm correct, then it is an
incredibly powerful amplifier for the kind of information that shows up in
Google's results.

**** Censorship will be counterproductive

While the political animus motivating people to flee to Threads is an
interesting "Social Complex," it only has so much power in and of itself.  Most
people are already disillusioned with either being censored or not having enough
censorship. Threads isn't going to fix this and Twitter's conversations will be
more interesting. A preeminant social network with less restrained dialectic &
dialogue will determine the course of conversations outside of that
network. This is a bit like Othello: the larger players occupy the outside,
cannot easily be unseated and will determine the course of what happens in the
middle, since ideas do not require digital channels to spread.

The way the left has treated Elon Musk is so telling. When I'm thinking --
people need to empower themselves with knowledge on whatever they're capable of
doing, whether it's engineering, science or actual policy work (Int'l law, FDI,
USAID, think tanks, etc) -- few people would exemplify that more than SpaceX and
Tesla. I actually care about the climate, but the magnetism this social complex
exerts oon the left leads them right off a cliff like a stampede of lemmings.
You can't solve any real problems in the world if you cannot deal with things
you don't like or that make you uncomfortable. Get over it.



* Issues

* Roam
