:PROPERTIES:
:ID:       d6782147-2239-4d0d-9e86-091cb3a5fff0
:END:
#+TITLE: Toxicology
#+DESCRIPTION: 
#+TAGS:


* Docs

* Resources

* Topics

** Benzalkonium Chloride

My main concern with this chemical the global/systemic level of exposure,
coupled with the potential to kill intestinal flora.

They started putting it in everything once COVID started:

+ like +80% of hand soaps -- it's hard to find a bathroom without it, though
  /minimal/ handwashing exposure is not a problem for me.
+ it is in the floor cleaners used on bathrooms (and on other tiled floors)
+ it's in most disinfectant sprays used at restaurants.
+ it's also in generic handwipes (which are usually either a bleach formulation
  /or/ BAC ... where both are bleach branded)

Basically, it's in any product where you might think "wouldn't that be great if
that killed COVID." Italy famously sprayed its streets with it in its first
outbreaks.

*** Vision Problems

Some mostly artificial exogenous chemicals, but particularly Benzalkonium
Chloride, seem to exacerbate a particular vision problem I have, almost making
it a litmus or proxy for chemical exposure.

+ Some industrial chemicals/solvents
+ Pure DMSO (which is potentially the cause)

.... todo: continue... I need to relocate the precise terminology for the weird
halos. There was formerly (maybe initially) a crystal clear "rainbow halo"
effect. Now it just blurs intense light, with less spectrum-specific effects for
how light sources appear to bleed out.

**** DMSO

DMSO is contained in many cosmetic and personal care products, in minor
quantities, but it's well known that if you spill it on your hand you /will/
absolutely smell garlic, even if you don't ingest it or otherwise smell it. The
smell is evidence of its skin penetration, as it is not a particularly volatile
chemical, as its Vapor Pressure is [[https://en.wikipedia.org/wiki/Vapor_pressure#Examples][approximately 1% of ethanol]].

|----------------+-----------+-------------------|
| vapor pressure | 0.556 kPa | ethanol: 5.83 kPa |
|----------------+-----------+-------------------|

Brief experimentation with pure DMSO as a carrier solvent may have triggered the
eventual development of mild blurry vision. I immediately (and permanently)
ceased ingestion of DMSO after a few months of occasional consumption ... for
obvious reasons.

+ Vision problems and potential blindness are cited as reasons that medicine
  avoids DMSO.
+ DMSO is only rarely used in medicine, AFAIK, except as a minor constituent in
  products where it aids in solubility (or at least I believe that's its purpose
  as an ingredient).
+ It has a sulfoxide group which causes it to "seek & destroy" free radicals, if
  you drink a little too much of the DSMO misinfo kool-aid.

#+begin_quote
"It’s a colorless liquid that gained notoriety for its ability to penetrate the
skin and other biological membranes."

Via [[https://www.healthline.com/health/what-is-dmso#What-is-DMSO?][Healthline]], which is more credible than wikipedia, apparently, despite the
Rx ads. =¯\_(ツ)_/¯=
#+end_quote

.... todo: continue

*** Contact Dermititus

I have a skin allergy to this, which is basically contact dermatitus. I
develeped the reaction by 2018-2019, possibly earlier. It's the skate spray
chemical. The allergy mostly reminds me of how hard it is to wash this chemical
off. It's a non-polar quaternary amine that lingers on surfaces until
deactivated by something it reacts to. Isopropyl alcohol doesn't remove it (it
only dissolves it in). Soap doesn't do anything.

*** Unintended Consequences

Other than unintended consequences, BAC may not be a problem.

+ It is a calculated risk though -- put benzalkonium choride in everything or
  rates of viral pneumonia from COVID increase by x% ... It's just not apparent
  that it could be hazardous unless used as directed.
+ The antibiotic triclosan was mostly removed from the US market for reasons
  including interfering with intestinal flora -- everyone washes their hands
  before they eat, which promotes ingestion. Where triclosan was rarely
  formulated outside of handsoaps, BAC stuff /sticks/ to surfaces and, given
  sufficient concentrations, reacts with whatever lands on it.

If there's any risk that accumulated exposure disrupts gut bacteria, then the
population exposure is already systemic and has been for several
years. Researchers are looking into viral/immunological pathologies to explain
post-COVID brain fog ... but what if that's not the only cause? Disrupting the
gut biome can attenuate or even shut down serotonergic activitiy in some parts
of the brain.

Whether this is worth looking into depends on the BAC dosage req. for unintended
effects as well as and occupational variance in exposure levels.

I've been worried about this since mid/late 2020 -- again, I was well aware of
the chemical before COVID started.

*** TODO Read References

[[https://pubmed.ncbi.nlm.nih.gov/29859783/][Adaptive microbial response to low-level benzalkonium chloride exposure]]

[[https://pubmed.ncbi.nlm.nih.gov/28683210/][Pulmonary Toxicity of Benzalkonium Chloride]] (inhalation risk at high
concentrations)

At high doses, BAC is used in animal injury models: [[https://www.mdpi.com/1422-0067/23/9/4799][How to heal the Gut's Brain:
Regeneration of the Enteric Nervous System]]. The chemical kills nerves in the
gut (at high doses). Whether it survives the stomach is unclear, but it's
positively charged and pairs with chloride ions.

** Hard Water

*** Onycholysis and Hyperkeratosis

My nails look nothing like what comes up online or in [[https://nailknowledge.org/nail-knowledge-base/onycholysis][NailKnowledge.org: Onycholysis]]. 
It just becomes inflammed under the nail, but I don't notice until about 12+ hours
later when it (barely) splits open. After 1-3 days, it's fine. One unintentional scrape
of my nail about 3 inches down the shower will do it. 

It's not severe and I know what could cause it, so I can avoid them. 

Known causes:

+ Solvents. Wallpaper Glue (should wear gloves)
+ lime on the shower
+ many concentrated chemicals (particularly if powdered) 
  that dehydrates the tissue directly or indirectly.

Precise causes:

+ Calcium carbonate? If $CaCO_3$ did this, you wouldn't find kids playing with chalk.
+ Magnesium Carbinate? idk

See [[https://en.wikipedia.org/wiki/Solubility_chart][Solubility Chart]] for 
reference values. It would be on the low-end of "slightly soluble" -- around 
0.1 g/L ($CaCO3$ is 0.013 g/L @ 25 °C) -- but maybe with a similar response to temperature 
changes... and obviously this stuff builds up over time, but most chemicals have
fairly constrained densities and it requires almost none of it to exhibit the 
effect.

I'm not too concerned about it, unless it's a litmus for something else. These
things could be common, but I would have no idea (I have no social access; I 
spend zero time in other people's homes or cars ... which turns everyday things
into an epic mystery quest). 

The calcium forming from cooling water  

+ [[https://en.wikipedia.org/wiki/Hard_water#Temporary_hardness][Temporary Hardness]]: 
  Boiling water always produces what looks like dust on the surface. IDK if Calcium carbonate 
+ I thought it quicklime forming on my shower .... but probably not...
+ At one point, I was getting contact dermititus from an aluminum(?) soap holder. 
  It was intermittent. I found that small amounts of water had built up under the soap
  which usually sat facing the same side. I suspect something was being leached into
  the soap and predicatably causing contact dermititus. 

Over the past ten years, I've found and de-booby-trapped like 20 different 
environmental problems causing downstream 2nd and 3rd order problems.
/It is a running theme/. But I can't validate dust/mold. 


* Issues


* Roam
+ [[id:ef2ad591-9e40-4011-9c91-3942462ecb58][Medicine]]
+ [[id:fe6cfff6-52e4-44fe-a429-b8e599a3f008][Chemistry]]
+ [[id:1fa38c8b-f6b6-4088-9d31-63e36b1f32b4][Pharmacology]]
