:PROPERTIES:
:ID:       d6782147-2239-4d0d-9e86-091cb3a5fff0
:END:
#+TITLE: Toxicology
#+DESCRIPTION: 
#+TAGS:


* Docs

* Resources

* Topics

** Benzalkonium Chloride

My main concern with this chemical the global/systemic level of exposure,
coupled with the potential to kill intestinal flora.

They started putting it in everything once COVID started:

+ like +80% of hand soaps -- it's hard to find a bathroom without it, though
  /minimal/ handwashing exposure is not a problem for me.
+ it is in the floor cleaners used on bathrooms (and on other tiled floors)
+ it's in most disinfectant sprays used at restaurants.
+ it's also in generic handwipes (which are usually either a bleach formulation
  /or/ BAC ... where both are bleach branded)

Basically, it's in any product where you might think "wouldn't that be great if
that killed COVID." Italy famously sprayed its streets with it in its first
outbreaks.

*** Contact Dermititus

I have a skin allergy to this, which is basically contact dermatitus. I
develeped the reaction by 2018-2019, possibly earlier. It's the skate spray
chemical. The allergy mostly reminds me of how hard it is to wash this chemical
off. It's a non-polar quaternary amine that lingers on surfaces until
deactivated by something it reacts to. Isopropyl alcohol doesn't remove it (it
only dissolves it in). Soap doesn't do anything.

*** Unintended Consequences

Other than unintended consequences, BAC may not be a problem.

+ It is a calculated risk though -- put benzalkonium choride in everything or
  rates of viral pneumonia from COVID increase by x% ... It's just not apparent
  that it could be hazardous unless used as directed.
+ The antibiotic triclosan was mostly removed from the US market for reasons
  including interfering with intestinal flora -- everyone washes their hands
  before they eat, which promotes ingestion. Where triclosan was rarely
  formulated outside of handsoaps, BAC stuff /sticks/ to surfaces and, given
  sufficient concentrations, reacts with whatever lands on it.

If there's any risk that accumulated exposure disrupts gut bacteria, then the
population exposure is already systemic and has been for several
years. Researchers are looking into viral/immunological pathologies to explain
post-COVID brain fog ... but what if that's not the only cause? Disrupting the
gut biome can attenuate or even shut down serotonergic activitiy in some parts
of the brain.

Whether this is worth looking into depends on the BAC dosage req. for unintended
effects as well as and occupational variance in exposure levels.

I've been worried about this since mid/late 2020 -- again, I was well aware of
the chemical before COVID started.

*** TODO Read References

[[https://pubmed.ncbi.nlm.nih.gov/29859783/][Adaptive microbial response to low-level benzalkonium chloride exposure]]

[[https://pubmed.ncbi.nlm.nih.gov/28683210/][Pulmonary Toxicity of Benzalkonium Chloride]] (inhalation risk at high
concentrations)

At high doses, BAC is used in animal injury models: [[https://www.mdpi.com/1422-0067/23/9/4799][How to heal the Gut's Brain:
Regeneration of the Enteric Nervous System]]. The chemical kills nerves in the
gut (at high doses). Whether it survives the stomach is unclear, but it's
positively charged and pairs with chloride ions.

* Issues


* Roam
+ [[id:ef2ad591-9e40-4011-9c91-3942462ecb58][Medicine]]
+ [[id:fe6cfff6-52e4-44fe-a429-b8e599a3f008][Chemistry]]
+ [[id:1fa38c8b-f6b6-4088-9d31-63e36b1f32b4][Pharmacology]]
