:PROPERTIES:
:ID:       0e36af9c-a6ef-45ef-8940-b8ca1108b193
:END:
#+TITLE: US Code
#+DESCRIPTION: US Federal Code
#+TAGS:

* Docs
+ [[https://www.law.cornell.edu/uscode/text][Cornell US Code Reference]]

** eCFR ([[https://www.ecfr.gov/reader-aids][Reader Aids]], RSS)
+ [[https://www.ecfr.gov/titles][Titles]]
+ [[https://www.ecfr.gov/agencies][Agencies]]
+ [[https://www.ecfr.gov/incorporation-by-reference][Incorporation By Reference]]
+ [[https://www.ecfr.gov/issues/2023][Updates (2023)]]

** Federal Register ([[https://www.federalregister.gov/reader-aids/using-federalregister-gov/subscription-options-and-managing-your-subscriptions][Reader Aids]], RSS)

A.K.A. "What executively empowered federal departments are planning to do to you
soon."

+ [[https://www.federalregister.gov/public-inspection/current][Public Inspection]] upcoming documents it seems you can't do anything about.
+ [[https://www.federalregister.gov/reader-aids/using-federalregister-gov/understanding-public-inspection/table-of-effective-dates-time-periods][Table of Effective Dates and Time Periods]] The timeframes during which
  informing yourself about facts on  topics do something

** Data.gov

Instead of using machine learning to draw waifu album art or to undermine the
economics of artists, you could (i donno...) use one of the data sources in
Docs.

+ [[https://resources.data.gov/categories/data-tools/][Data Tools]]: including [[https://ckan.org/][CKAN]], which is generally something that should have an
  emacs mode, since it's used by many governments and organizations to package
  data sources


***** TODO finish outlining tools, maybe link the noter PDF

* Resources

** RSS Feeds

Pro-tip: find the RSS feed under "reader aids." The lack of RSS usage has
enabled the disruption of the publics' relationships with news publishers.
Formerly, academic journals widely supported RSS. Upwork enables the use of
RSS-backed searches which provide up-to-date results for search keywords in an
app like Thunderbird ... but no one uses RSS because it's dead.

RSS subscription delivers articles from trusted sources with near guaranteed
delivery with a UI that encourages "conscious selection" of content -- you have
to click on the feeds for topics you want to see when you want to see them.
Social media encourages you to repeatedly flick your thumb as it shows you more
Brawndo ... since the algorithms indicate that plants crave Brawndo.

* Topics

* Issues

* Roam

