:PROPERTIES:
:ID:       e93eebbe-d702-46e6-864e-114fc4e61fc5
:END:
#+TITLE: Video
#+CATEGORY: topics
#+TAGS:

* Docs

* Resources

* FFMPEG

** Issues

*** Convert Video To GIF

[[https://superuser.com/questions/1049606/reduce-generated-gif-size-using-ffmpeg][Create PNG Palette, Then Convert]]

#+begin_src shell
ffmpeg -y -i file.mp4 -vf palettegen palette.png
ffmpeg -y -i file.mp4 -i palette.png -filter_complex paletteuse -r 10 -s 480x320 file.gif
#+end_src

* OBS Studio

** Docs

** Resources

** Topics

*** Network Streams

**** NDI (distroav)

This is useful for network-local video monitors, esp if dealing with multiple
OBS streaming sources... but not only for that, since the main streaming output
can also send over mDNS to other monitor stations. This use case is _not_ useful
if using wifi. In my case, the sender's default route is going out wifi...

+ install =distroav= plugin on both receiver & sender
  - on the sender side, this will just "magically" play whatever's showing in
    OBS, I guess.
+ ensure firewall ports are open on both receiver/sender
+ ensure mDNS is accessible on both receiver/sender

***** Firewall Setup

The stream was failing, since NDI requires bidirectional communication

#+begin_src shell
# ... that was so much easier than SRT
# but it's also annoyingly opaque (proprietary)
ufw allow proto tcp from "$ip" to any port 5959
ufw allow proto tcp from "$ip" to any port 5960:5965
ufw allow proto udp from "$ip" to any port 5960:5965
#+end_src

***** Ports

[[https://docs.ndi.video/all/getting-started/white-paper/ndi-related-network-ports][NDI Related Network Ports]]

| port        | protocol       | summary                            | desc                                                            |
|-------------+----------------+------------------------------------+-----------------------------------------------------------------|
| 5353        | UDP            | mDNS                               |                                                                 |
| 5959        | TCP            | NDI Discovery Server               | Optional: connect NDI between subnets (or without mDNS)         |
| 5960        | TCP            | Source Discovery                   | Discover NDI sources by IP                                      |
| 5960 and up | TCP            | TCP NDI Stream                     | NDI uses shared TCP/UDP per stream                              |
| 5961 and up | UDP (Reliable) | UDP NDI Stream                     |                                                                 |
| 6960 and up | TCP/UDP        | Multi-TCP or UDP Receiving         | at least one port will be used per connection (dep on features) |
| 7960 and up | TCP/UDP        | Multi-TCP or UDP Unicast/Multicast | at least one port will be used per connection (dep on features) |

**** SRT Stream from laptop

+ Stream to service over LAN
+ stream SRT source from laptop -> desktop on wifi.

On desktop, ensure the port is open on wifi

#+begin_src shell
line=10
port=54321

# for now, just ignoring the source
iptables -I nixos-fw $line -p udp --dport $port \
    -m state --state NEW,ESTABLISHED \
    -j ACCEPT
#+end_src

I believe the listener needs to initiate first

#+begin_src shell
laptop=172.16.17.123 # wifi
desktop=172.16.17.231 # wifi
port=54321

# on laptop, IP is still $desktop, mode=listener allows for resume
echo "srt://$desktop:$port?mode=listener&timeout=100000&transtype=live"

# on desktop, mode=caller here allows for resume
echo "srt://$desktop:$port?mode=caller&timeout=100000&transtype=live"
#+end_src

***** Troubleshoot firewall issues in =srt= stream 

I was having firewall issues, so, to test:

#+begin_src shell
# on desktop
socat UDP-LISTEN:$port,fork STDOUT

# on laptop
socat - UDP:$desktop:$port
#+end_src

Bytes will be transmitted when you hit newline

***** Troubleshoot connection issues

I was still seeing notifications on my laptop about "stream
connected/disconnected"

#+begin_src shell
# from desktop
nix shell 'nixpkgs#ffmeg'

# ffplay *from* the desktop's stream URL
ffplay -i "srt://$desktop:$port?mode=listener&timeout=1000000&transtype=live"

# set laptop stream target (to the desktop's SRT url)
echo "srt://$desktop:$port?mode=caller&timeout=100000&transtype=live"
#+end_src

This seemed to require initializing the =listener= on desktop first, then
beginning the stream from laptop.

Also, =ffplay= can confirm that OBS has bound the socket... (address already in
use). =socat= also does this, but it's less clear.

*** =gpu-screen-viewer=

**** Stream to =srt=
Useful to troubleshoot XDG screen sharing problems, since it forces the
=hyprland-share-picker= window to popup. If you're not using it, remove it, since
it usually gets around the need for portal-based screen sharing.

#+begin_src shell
mic=default_input
desktop=default_input
fps=60

# using "-w portal" will fail without "-restore-portal-session yes"
sharesource=portal

# output as srt stream
fromhost=127.0.0.1
tohost=127.0.0.1
port=54321

srt_container=mpegts # gpu-screen-recorder can't infer the container format
srtmode_TO=listener
srtmode_FROM=caller

# listener (output) must be online before the caller (input) bc of how SRT
# negotiates stream setup
output="srt://${tohost}:$port?mode=${srtmode_FROM}&timeout=1000000&transtype=live"
input="srt://${fromhost}:$port?mode=${srtmode_TO}&timeout=1000000&transtype=live"

# To establish the SRT Listener waiting for SRT Callers
gpu-screen-recorder -w "$sharesource" -restore-portal-session yes \
    -f "$fps" -a "$mic" -a "$desktop" -o $output -c "$srt_container"

# To view the SRT output (as an input)
# - test with `ffplay -i $some_audio_or_video`
# - audio plays video with a spectrogram
nix shell nixpkgs#ffmpeg --command ffplay -i $input


#+end_src

Then wait for the share picker to pop up. For me, it's popping up off-screen

#+begin_src shell
hyprctl clients -j | jq '. | map(select((.title | match(".*share.*"))))'
#+end_src

To test the stream, use =vlc=, =obs=, =ffplay= or =socat=

#+begin_src shell

#+end_src

=gpu-stream-recorder= also contains these useful options:


| --list-capture-options   | $card_path |
| --list-monitors          |            |
| --list-audio-devices     |            |
| --list-application-audio |            |
| --list-v4l2-devices      |            |


*** MQTT/0MQ

**** MQTT

MQTT may be appropriate in lieu of 0MQ: which would allow OBS to integrate with
IoT devices.

#+begin_quote
"This is the project that never ends.... it goes on and on my friends..."
#+end_quote

***** obs-mqtt-status

There is a [[https://github.com/glikely/obs-mqtt-status][glikely/obs-mqtt-status]] project, which receives updates from OBS,
forwards them to MQTT intermediary. When listening devices connected to the MQTT
broker are forwarded messages, it changes the color of a display to indicate
recording state. (the code to perform the latter isn't in the project, per se)

**** 0MQ

Nope... not 0MQ lol

#+begin_quote
"*obs-websocket* is now included by default with OBS Studio 28.0.0 and above"
#+end_quote

Wow I really just don't get out much, huh (i swear everything in life is phony)

***** Remote Control

For remote control of files rendered by OBS. This prevents a safe-ish boundary
between applications that manage renderable state.

****** Example: Update on screen text

Render on screen text, which e.h. may contain _most recent emacs command_ and _most
recent file_. Emacs has 0MQ bindings, used with jupyter.el.

+ 0MQ messages from Emacs received by 0MQ server listening to socket. Or 0MQ
  messages may contain current state of network devices, rendered on screen as
  things come up & go down.
+ 0MQ server runs in either OBS application extension or there is a file-based
  boundary between 0MQ server and OBS -- i.e. OBS reads file, does _not_ manage
  state of a 0MQ plugin, etc. This avoids a dump-truck full of problems (it also
  allows processes running elsewhere in the network to update the rendered file)
+ Messages contain short strings or data structures with guarantees on
  compactness.

***** Stability Guarantees

Assuming:

+ The 0MQ server type-checks received messagse
+ That specific components in the OBS cannot crash or crash "safely"
+ That OBS handles crashes by replacing receiving renderables with safe data
  structures

Then it's sufficiently stable -- this may need some work. If stability is an
issue, then OBS can render from a file and (I believe) updates on-screen
rendered text if file changes.

**** OCR

***** [[https://github.com/dram55/MarioMaker2OCR][Mario Maker 2 OCR]]

+ Extract text with OCR and insert into Video Stream Overlay
+ Written in C# and uses OpenCV/Tesseract (libs wrapped by [[http://www.emgu.com/wiki/index.php/Main_Page][EmguCV]] for .NET)
+ [[https://github.com/unosquare/embedio][EmbedIO]] provides a .NET-based Websocket/HTTP server interface
+ Example video: [[https://www.youtube.com/watch?v=myG9h01B4Bs&t=445s][Karibukai Play]]

***** Crowdsourced OCR Setup

also, a smarter way to solve this would be to crowdsource the translations. set
up a chat command that forwards suggested translations to another chat
channel/room. then someone running your stream in the backend gets a list of
suggested translations along with:

- an "up/down" function to promote/demote the user making suggestions
- a function to pin suggested translation on-screen.

this way, you're only pinning on-screen what is relevant to the audience while
you're encouraging audience participation. it's also much more resilient:

- it doesn't require multiple OBS/OCR/etc configs per game
- it requires a web service and most everything else can be set up by someone
  who can write/customize a discord chat bot

***** Hypothetical OCR Setup

#+begin_quote
Responding to a reddit post on OBS/OCR with translation
#+end_quote

Translating the text is going to require a few moving parts.

I don't have much familiarity with the OBS or OCR ecosystems, but this
[[https://github.com/dram55/MarioMaker2OCR][MarioMaker2OCR]] project solves some of the problems.

Having a PCIe capture card would distribute the load across multiple computers,
which itself would require some networking/automation. Without that or multiple
GPU's, it's likely that the load from the Game, OCR and additional transcoding
would be intermittent.

This would require several services:

- OBS
- OCR-service
- Translation-service

You'd need to transcode several times and decide what kind of workload you want
the OCR to have and how its output is encoded back onto the output video stream:

- receive streaming video source into OBS
- either duplex that stream (fast, but potentially brittle req. networking) or
  have OBS transcode a video output to make available to OCR (slow, but easy;
  also brittle if OBS crashes/lags)
- at this point, sending a trigger to OCR would be useful. this could be done
  with an FFMPEG script that takes a screenshot to forward to the OCR, so OCR
  isn't actively processing it's input stream the entire time.
- layer on OCR output into video -- again, creating an image-based processing
  flow here or using an capture card would lighten the load.
- have the OCR service send it's output to a translation web service, given some
  conditions. it receives it's HTTPS translation response and then another
  service makes a file available to OBS as a composited image
- have OBS combine the final video streams as output from OBS to streaming
  server

This is what makes sense to me as a Linux guy. Depending on how OBS responds to
file updates between Windows/Linux implementations, it may be able to detect
changes in a file. In this case, you can just create a new image file with
ImageMagick and update a symlink (not in Windows)

Ultimately, there are a few UI/UX problems to be solved:

- is there background content you don't want to translate (background images
  with Kanji)
- do you always want to translate text boxes?
- where do you place the translated output on stream?

It's easier to solve these problems if you have an app running on a streaming
station with the capture card that displays the video on an overlay and
translates content given a mouse click. However, it's a bit tough to get any of
this to work, since it would require game-specific settings. Unless you're using
Ansible/Git to automate a VM that gets a capture card on passthrough, whatever
you set up will eventually become buggy and cease to work. (Windows is smoll
brain)

So then with multiple computers, there are other problems to be solved:

- automation/network
- testing and backing up the OBS & OCR service configs
- handling service failure

Getting something like this to work on a single workstation would require less
networking/automation, but still it's likely that the configs/environment would
be brittle.
**** Ansible

* Share Picker
** Issues
*** XPDH =xdg-desktop-portal-hyprland= initializes windows at non-rendered coordinates

Started with =hyprland-share-picker --allow-token=, but requires some application
context (or something)

For me, it gets called twice. This happens in OBS bc there are two separate
sources. But for other applications.

Get the =.address= or =.stableId=, reference [[https://github.com/basecamp/omarchy/blob/43bfe9b9d82ba650b5b80eef79e94776790801c9/bin/omarchy-hyprland-window-pop#L1][bin/omarchy-hyprland-window-pop]]. that
script is intended to manipulate the active window.

#+begin_src shell
# get the stableId
hyprctl clients -j | jq '. | map(select(.class == "Alacritty" and .workspace.name != "special:docs"))'

# this won't work on tiled windows
hyprctl dispatch "hl.dsp.window.center({ window = \"stableId:180000b5\" })"

# move the window to a specific workspace
hyprctl dispatch "hl.dsp.window.move({ workspace = \"2\", window = \"stableId:180000b5\" })"
#+end_src

**** Using =dbus-monitor=

#+begin_src shell
# dbus-monitor "type='signal'\
# ,sender='org.gnome.TypingMonitor'\
# ,interface='org.gnome.TypingMonitor'"

# the query syntax sucks
dbus-monitor "type='signal',interface='org.freedesktop.*'"

# instead, just capture as .pcap and open in `bustle` or `d-spy`
dbus-monitor --pcap > $somefile
#+end_src

**** Troubleshoot sharepicker from =cli=

Check for open sharepickers

#+begin_src shell :results output code :wrap example jsonc
HYPRLAND_INSTANCE_SIGNATURE=$(hyprstance)
hyprctl clients -j \
    | jq 'map(select(.title == "Select what to share"))
| (map([.at,.size] | map(@csv)))'
#+end_src

#+RESULTS:
#+begin_example jsonc
[
  [
    "480,1100",
    "960,800"
  ]
]
#+end_example

