:PROPERTIES:
:ID:       5aa36ac8-32b3-421f-afb1-5b6292b06915
:END:
#+title: VyOS
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

VyOS has =nftables= and a decent DSL with fairly good ansible support.

+ +The DSL+ Some significant part of VyOS is implemented in OCaml.
+ It only supports x86 for now.
+ It's missing some of the plug-in functionality of OPNsense (packet/traffic
  inspection), but has the ability to run images in containers with
  routing/firewall on the container host. So you could set up a container to do
  much of what the PFSense and OPNsense ecosystem allows (see the [[https://docs.vyos.io/en/stable/configuration/container/index.html#example-configuration][Zabbix
  container example]])

* Roam
+ [[id:5aa36ac8-32b3-421f-afb1-5b6292b06915][VyOS]]
+ [[id:e967c669-79e5-4a1a-828e-3b1dfbec1d19][Route Switch]]
+ [[id:23716a1b-7937-4cd1-923d-9adae1286601][Debian]]
+ [[id:ea11e6b1-6fb8-40e7-a40c-89e42697c9c4][Networking]]

* Docs

+ [[https://docs.vyos.io/en/stable/automation/index.html][Automation]] and [[https://docs.vyos.io/en/stable/automation/command-scripting.html#executing-pre-hooks-post-hooks-scripts][pre/post hooks]]
+ [[https://docs.vyos.io/en/stable/cli.html#configuration-overview][Configuration overview]] (navigating the router CLI like with IOS
  shortcuts/help)
+ [[https://docs.vyos.io/en/stable/troubleshooting/index.html][Troubleshooting]]
+ [[https://support.vyos.io/support/solutions/articles/103000096255-what-are-the-hardware-requirements-][Hardware Requirements]]

** How to
+ [[https://docs.vyos.io/en/stable/configexamples/index.html][Configuration Blueprints]] and [[https://docs.vyos.io/en/stable/configexamples/index.html#configuration-blueprints-autotest][Autotest Blueprints]]
+ [[https://docs.vyos.io/en/sagitta/contributing/build-vyos.html#][Build a VyOS ISO]]

** DSL

+ [[https://docs.vyos.io/en/stable/configuration/firewall/index.html][firewall]]
+ [[https://docs.vyos.io/en/stable/configuration/container/index.html][container]]
+ [[https://docs.vyos.io/en/stable/configuration/interfaces/index.html][interfaces]]
  + [[https://docs.vyos.io/en/stable/configuration/interfaces/openvpn.html][OpenVPN]] (with LDAP)

** Community
+ [[https://forum.vyos.io/][forum.vyos.io]]
+ [[https://support.vyos.io/support/home][Support Portal]]
+ [[https://vyos.dev/][vyos.dev]]: Issue/Feature Tracking
+ Slack is for customers/contributors

** Printable

#+begin_src javascript
document.querySelector('.copyDiv').forEach(el => el.remove())
#+end_src

whoa this is way to hard

#+begin_src css

#+end_src

* Resources
+ [[https://blog.kroy.io/2019/11/21/battle-of-the-bare-metal-routers/][Battle of the Metal Routers]]
+ [[https://blog.kroy.io/2019/08/23/battle-of-the-virtual-routers/][Battle of the Virtual Routers]] (VyOS)

** Kernel

+ Post with [[https://discourse.ubuntu.com/t/kernel-configuration-in-ubuntu/35857][Notes on Kernel Configuration in Ubuntu]] (not vyos-specific)

** OpenAPI

A VyOS instance that runs the API can be configured to host an OpenAPI browser
at https://muh.router.lab.local/redoc, so this is a good place to look for
metaprogramming

* Topics



** Automation

*** Managing Config

+ Jinja templates may work well.


*** Devops
+ Ansible is the main tool for configuration. Their ansible code includes
  inventory plugins, but I'm unsure of the discovery mechanisms.
+ Ansible requires paramiko for ssh
+ SSH/Shell is just as proficient as ansible for DSL configuration, but doesn't
  include the benefits (or overhead) of an Ansible project.
+ Napalm, Netmiko, Salt can also be used, but support/functionality seems
  limited.
+ [[https://docs.vyos.io/en/stable/automation/terraform/index.html][Terraform]] can provision a VyOS image (and Ansible configures).
+ [[https://docs.vyos.io/en/stable/automation/cloud-init.html][Cloud-init]] is also an option

** From A Live ISO

#+name: tmpdir
#+begin_src sh :cache yes
mktemp -d
#+end_src

#+RESULTS[d11bbe9264aafab22d88733f2c0f56e64bc0e8a9]: tmpdir
: /tmp/tmp.FGNzBW0pUI

*** Packages

*** Services


*** Kernel


Fetch =/proc/config.gz=, then =gunzip=

#+begin_example shell
# this works, but tramp completion is problematic -- emacs close to locking :(
# +begin_src shell :dir /ssh:vyostest:/home/vyos :results output file :file img/vyos.kconfig
cat /proc/config.gz | gunzip -c
#+end_example

Just use scp

#+begin_src shell :var d=tmpdir
scp vyostest:/proc/config.gz $d
#+end_src

Run =gunzip= and save to =kconfig=

#+begin_src shell :var d=tmpdir
# total lines: 6390. without commented or empty lines: 3309
cat $d/kconfig | grep -v '^#' | grep -ve '^$' | wc -l
#+end_src

#+RESULTS:
: 3309

Whereas for this hsot arch zen kernel, there are =9386= positively-defined kconfig
settings (and =12192= total).

*** Hardware

Gonna want =hwinfo=
** Security

*** Stripping Private Data From Config

[[https://forum.vyos.io/t/ip-tv-with-igmp-issues/11604/3][Source]]

#+begin_example shell
show configuration commands | strip-private
#+end_example
** Source
*** vyos-1x

+ Contains the XML that specifies the VyOS cli.

Running =make all= runs these tasks

+ clean
+ interface_definitions :: configuration mode commands (via *.xml.in files)
+ op_mode_definitions :: operation mode commands (via *.xml.in files)
+ test
+ j2lint :: run linter for jinja2 files in =data/=
+ vyshim :: run make tasks in =src/{shim,shim/mkjson}/Makefile=
+ generate-configd-include-json :: generates JSON from the results of
  =interface_definitions= and =op_mode_definitions=

**** VyShim

+ vyos-configd-service :: 0MQ server
+ vyshim :: 0MQ client
+ mkjson :: C serializer to lay JSON on the 0MQ wire

[[https://vyos.dev/T6326][vyos.dev/T6326]] explains that API requests are relayed to the core
vyos-configd-service via 0MQ socket:

#+begin_quote
1. API(configure)
2. vyos-http-api-server(.py)
3. configsession.py
4. /opt/vyatta/sbin/my_commit(symlinked to: my_cli_bin)
5. sudo is called here, but I am too code blind when it comes to C to figure out where/how it is called
6. vyshim (ZMQ client)
7. vyos-configd-service (ZMQ server)
8. <py service file>
#+end_quote

**** XML Spec

Transclusion for XML specs in [[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/op-mode-definitions/][./op-mode-definitions]] and
[[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/interface-definitions][./interface-definitions]] is performed by [[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/scripts/transclude-template#L54][./scripts/transclude-template]]

Running =make op_mode_definitions= and =make interface_definitions= will generate
XML in the respective subdirs of =./build=. This can be queried with =xq= et alias.

***** Op Mode Definitions

+ [ ] in emacs, this results in a find/exec task that doesn't complete

***** Interface Definitions

+ [ ] building these requires having a compatible =libvyosconfig.so=

***** XML Schema

After building ISO, XML =RelaxNG= schemas are in
=./build/vyos-1x/schema/*.{rnc,rng}=


**** GraphQL API

The API is implemented in python using Ariadne in the vyos-1x repo.

The last task when =make all= generates the JSON versions of the same XML

The file [[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/src/services/api/graphql/README.graphql#L3][src/services/api/graphql/README.graphql]] contains example queries

+ [[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/src/services/api/graphql/graphql/schema/schema.graphql#L17][src/services/api/graphql/graphql/schema/schema.graphql]]
+ [[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/src/services/api/graphql/graphql/schema/auth_token.graphql#L1][src/services/api/graphql/graphql/schema/auth_token.graphql]]
+ [[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/src/services/api/graphql/graphql/client_op/auth_token.graphql#L3][src/services/api/graphql/graphql/client_op/auth_token.graphql]]

Python generates schemata (in this order, in generate_schema.py)

+ [[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/src/services/api/graphql/generate/schema_from_op_mode.py#L154][src/services/api/graphql/generate/schema_from_op_mode.py]]
+ [[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/src/services/api/graphql/generate/schema_from_config_session.py#L154][src/services/api/graphql/generate/schema_from_config_session.py]]
+ [[https://github.com/vyos/vyos-1x/blob/4d3e976271e30d70c8b2660d869a220de98d8c59/src/services/api/graphql/generate/schema_from_composite.py#L154][src/services/api/graphql/generate/schema_from_composite.py]]

These files use these config values

#+begin_example python
from vyos.defaults import directories

# ...

OP_MODE_PATH = directories['op_mode'] #
SCHEMA_PATH = directories['api_schema']
CLIENT_OP_PATH = directories['api_client_op']
DATA_DIR = directories['data']
#+end_example

** ISO Build

It's a =debian-live= build

+ [[https://debian-live-config.readthedocs.io/][Debian Live Config Docs]]
  - [[https://github.com/nodiscc/debian-live-config/blob/master/doc/md/custom.md][./doc/md/custom.md]]
+ [[https://packages.debian.org/bookworm/live-build][Live Build System Components]]

Other build projects (apparently the support isn't great)

+ [[https://github.com/grahamhayes/vyos-build/][grahamhayes/vyos-build]] (containers, but old)
+ [[https://github.com/mcbridematt/vyos-arm64-builder][mcbridematt/vyos-arm64-builder]] (without containers)
+ [[https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.youtube.com/watch%3Fv%3DpbCQ5DXwUhI&ved=2ahUKEwimnNHcgaKNAxVzEFkFHTrZMG4QtwJ6BAgUEAI&usg=AOvVaw0mxO4FE6gLKe1cgbZzdZJc][Video: successfully installed VyOS on custom ARM64]]

*** Directories

According to [[https://github.com/vyos/vyos-build?tab=readme-ov-file][vyos/vyos-build]], the directories used:

#+begin_quote
+ build :: Used for temporary files used for the build and for build artifacts
+ data :: Data required for building the ISO (e.g. boot splash/configs)
+ packages :: This directory can hold arbitrary *.deb packages which will be
  embeded into the resulting ISO. Among other things those packages will be:
  Linux Kernel, FRR, Netfiler...
+ scripts :: Scripts that are used for the build process
+ tools :: Scripts that are used for maintainer's tasks automation and other
  purposes, but not during ISO build process
#+end_quote

*** Customization

The [[https://github.com/vyos/vyos-build/blob/247e810339294218876922d6cc015c8bbc746c39/scripts/image-build/build-vyos-image#L201-L223][options passed to build-vyos-image]] can also be customized in
=./data/build-flavors/*.toml=, where the most complete defaults are seen in
[[https://github.com/vyos/vyos-build/blob/247e810339294218876922d6cc015c8bbc746c39/data/defaults.toml#L1][./data/defaults.toml]]

**** Add Packages

When added to the =build-flavor=, these should append.

#+begin_src toml
packages = [
  "lvm2",
  "hwinfo",
  "yubico-piv-tool",
  "opensc-pkcs11",
  "opensc",
  "age"
]
#+end_src

*** Permanent Installation

Running =install image= eventually spawns =sudo
${vyos_op_scripts_dir}/image_installer.py --action install=

+ This is built into the ISO at ./build/vyos-1x/src/op_mode/image_installer.py
+ And sourced from the vyos-1x repo at [[https://github.com/vyos/vyos-1x/blob/572400156976a5fc36e1dbe2fcdaf12d61510e13/src/op_mode/image_installer.py#L4][src/op_mode/image_installer.py]]
+ It basically transfers the ISO contents onto the Root and EFI partitions. See
  [[https://github.com/vyos/vyos-1x/blob/572400156976a5fc36e1dbe2fcdaf12d61510e13/src/op_mode/image_installer.py#L791-L963][image_install]]
+ For the bootloader, it relies on [[https://github.com/vyos/vyos-1x/blob/572400156976a5fc36e1dbe2fcdaf12d61510e13/python/vyos/system/grub.py][grub]] and [[https://github.com/vyos/vyos-1x/blob/572400156976a5fc36e1dbe2fcdaf12d61510e13/python/vyos/system/grub_util.py][grub_util]] from =import vyos.system=
  - grub_util :: handles ={set,update}_console_speed= and
    ={set,update}_kernel_cmdline_options=
  - grub ::

*** Other Artifacts
**** Interesting files

+ ./build/vyos-1x/schema/*.{rnc,rng} :: RelaxNG XML schemas for interface &
  op-mode commands
+ ./build/config/hooks/{live,normal} ::


**** Structure of =build=

The files at =data/live-build-config/hooks/live= run when the ISO is mounted, so
=data/live-build-config/hooks/live/00-manifest.binary= writes to
=./live/packages.txt=, found at =/usr/lib/live/mount/medium/live/packages.txt=

***** Directories

Without vyos-1x, cache or chroot directories, the file structure is compact

#+begin_src shell :results output verbatim :dir /data/ecto/vyos/vyos/vyos-build
tree -dI vyos-1x -I cache -I chroot build
#+end_src

#+RESULTS:
#+begin_example
build
├── auto
├── binary
│   ├── boot
│   │   └── grub
│   │       ├── live-theme
│   │       └── x86_64-efi
│   ├── EFI
│   │   └── boot
│   ├── isolinux
│   └── live
├── config
│   ├── apt
│   ├── archives
│   ├── bootloaders
│   │   └── grub-pc
│   │       └── live-theme
│   ├── debian-installer
│   ├── hooks
│   │   ├── live
│   │   └── normal
│   ├── includes
│   ├── includes.binary
│   │   └── isolinux
│   ├── includes.bootstrap
│   ├── includes.chroot
│   │   ├── etc
│   │   │   ├── initramfs-tools
│   │   │   │   └── hooks
│   │   │   ├── modprobe.d
│   │   │   ├── modules-load.d
│   │   │   ├── sudoers.d
│   │   │   └── systemd
│   │   │       └── system
│   │   │           └── getty@tty1.service.d
│   │   ├── opt
│   │   │   └── vyatta
│   │   │       └── etc
│   │   │           ├── grub
│   │   │           └── install-image
│   │   ├── usr
│   │   │   └── share
│   │   │       └── vyos
│   │   │           └── keys
│   │   └── var
│   │       └── lib
│   │           └── shim-signed
│   │               └── mok
│   ├── includes.chroot_after_packages
│   ├── includes.chroot_before_packages
│   ├── includes.installer
│   ├── includes.source
│   ├── package-lists
│   ├── packages
│   ├── packages.binary
│   ├── packages.chroot
│   ├── preseed
│   └── rootfs
└── local
    └── bin

60 directories
#+end_example

** Config

*** Default Profiles

There are several profiles to build, each with a =config.boot.default=, though
some of the profiles below are CI/CD (not in the =vyos-build= project)

#+begin_src shell :results output verbatim
locate '/data/ecto/vyos*vyos*config*default' \
    | sed -e 's/\/data\/ecto\/vyos\/vyos\///g'  \
    | tree --fromfile .
#+end_src

#+RESULTS:
#+begin_example
.
├── gh-action-test-vyos-1x
│   ├── data
│   │   └── config.boot.default
│   └── tests
│       └── data
│           └── config.boot.default
├── vyos
│   └── configs
│       └── etc
│           └── vyos
│               └── config.boot.default
├── vyos-1x
│   ├── data
│   │   └── config.boot.default
│   └── tests
│       └── data
│           └── config.boot.default
├── vyos-build
│   ├── build
│   │   └── vyos-1x
│   │       ├── data
│   │       │   └── config.boot.default
│   │       └── tests
│   │           └── data
│   │               └── config.boot.default
│   └── tools
│       ├── cloud-init
│       │   └── AWS
│       │       └── config.boot.default
│       └── container
│           └── config.boot.default
└── vyos-workflow-test-temp
    ├── data
    │   └── config.boot.default
    └── tests
        └── data
            └── config.boot.default

27 directories, 11 files
#+end_example

*** Snippets

Lots of snippets tests (mostly jinja templates), though some of these are
standard =.conf= files. The jinja is a bit hard to parse.

#+begin_src sh
find ./vyos/vyos-workflow-test-temp/ -name '*.conf*' -type f
#+end_src

+ vrf-basic: lots of static routes

** Org Babel

It would be possible to run commands against a vyos interface.

*** Potential Problems

+ Since [[https://docs.vyos.io/en/equuleus/cli.html#the-config-mode][configuraton mode changes the shell prompt from $ to #]], the tramp regexp
  may need to change.

**** Statefulness

The usage of =configure= introduces "statefulness" and so your scripts must adapt
to this.

***** Config modes

Three modes for configuration: saved (startup), working, and active/running.

This actually makes scripting much easier:

+ Your changes are transactional, =commit= the whole thing or reset
+ Aborted automation scripts can easily be unwound.

***** Command Modes

There are two modes for commands: Operational mode and Configuration mode

+ Running =show interfaces= in configuration mode outputs diffs with
  additions/replacements/deletions.

So scripts that do the following may be problematic

+ sets data based on state which cannot be predicted: network data or
  configuration management service which retrieve data on the router itself
+ sets data only in the working configuratioin parameters
+ can only source data for configuration after changes to firewall/routing.
  these scripts should generally be broken into multiple scripts, unless that
  would require multiple "transaction" rewinds
+ scripts that need to "hold" changes to working configuration on multiple
  devices, to evaluate whether the transaction should be commit. e.g. making
  changes to VPN/GRE tunnels for devices that would lose connectivity, where you
  want something to validate changes to working configuration (again, it
  displays in diff)

And actually, most of the working-configuration state is lost when you exit
configuration mode. This is probably for the best, as your scripts should
precompute all values anyways.

+ also, scripts that should generally require multiple transactions. i.e. you
  would like to =commit= mutliple times, but then need to rewind the changes to
  multiple devices -- in this case, the sequence of commands to rewind the
  changes cannot be known to be the "inverse" of the configured commands. So, a
  pattern for automation where you always save the running config before you
  initiate changes.

Since you can't exit configuration mode without commiting, your automation needs
to manage:

+ connection state (e.g. ssh)
+ error handling ... (e.g. you fat-fingered that VPN)
+ in addition to config delta and configuration mode state (e.g. the mode or the
  active interface)

The answers to the above general design concerns should be found in the code
that supports the [[https://docs.vyos.io/en/equuleus/configexamples/index.html][Configuration Blueprints]], especially the automated testing.

THE PROBLEM: these scenarios are actually exceedingly common for managing large
deployments, which are actually more common than you'd think (although
Route/Switch is small world)

You absolutely will take down the network & services lulz

*** Connect using =sshfs= to eval

One approach would just set the =:dir= to a Tramp path, but this isn't great

#+begin_example org
#+begin_src sh :dir (concat (identity sshfs-uri)) :shebang #!/bin/ash :eval never
ssh aserver '
nvram show | grep vlan
'
#+end_src
#+end_example

+ and [[https://lists.gnu.org/archive/html/emacs-orgmode/2016-01/msg00321.html][there can be issues with =/tmp=]] since babel will try to store scripts
  there on the remote host while it runs them
  - This is an issue for =busybox=, maybe =ash= and maybe =dropbear=... so it like
    doesn't work well for ddwrt, unless it's a custom build
+ =sshfs-uri= would be something like =(setq sshfs-uri
  "/ssh:root@router.mynet.local:/jffs/deploy")=
+ idk whether I used =sshfs= because =/ssh:user@host:/root/muh/server=, but Tramp
  maintains a persistent =ssh= connection that it injects real commands into
  (which is why it doesn't work when =PS1= has a colorized prompt)

There may be other approaches that combine Tramp/Babel

+ This requires some [[https://stewart123579.github.io/blog/posts/emacs/emacs-on-windows-getting-tramp-to-work/][Tramp tweaks for Windows]]

*** From the VyOS manual

Running this at a shell would connect, then run the commands

#+begin_example sh
ssh 192.0.2.1 'vbash -s' <<EOF
source /opt/vyatta/etc/functions/script-template
run show interfaces
exit
EOF
#+end_example

** ZeroTier & Tailscale

[[https://lev-0.com/][lev-0]] has several series on setting Tailscale on VyOS as a podman service. The
VyOS DSL has a =container= subcommand. I haven't worked out the details, but
this seems like a fairly viable option.

** PKI
