:PROPERTIES:
:ID:       013f2a46-ac4a-4881-a25a-ef0beb9d8290
:END:
#+TITLE: Yubikey

* Docs

* Resources

* Issues

** PKCS#11

*** On Arch, the ssh-agent won't authorize the use of an added PKCS#11 key

Error message:

#+begin_example
Could not add card "/usr/lib/pkcs11/opensc-pkcs11.so": agent refused operation
#+end_example

Potential causes:

+ bad configuration?
  - yubikey? ssh-config?
  -
+ suspend or OOM cause keys to be dumped from ssh-agent memory
  - reported on mac os mostly. however, this happens immediately for me
+ similar issues (from ~2017) recommend compiling openssh


** Webauthn

*** Yubikey not accessible from browser when using webauthn/u2f
This may be a udev rule

+ [[https://blog.hansenpartnership.com/webauthn-in-linux-with-a-tpm-via-the-hid-gadget/][Webauthn in Linux with a TPM via the HID gadget]]

**** ANSWER: the =hidraw= devices are receiving permissions =600=
This requires a udev rule, but something is already assigning permission.

It hits this rule in =/run/current-system/profile/lib/udev/rules.d/=, but the Guix =operating-system= must be configured to pull this =./lib/udev/rules.d/...= rule from the == package

#+begin_example udev
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0200|0402|0403|0406|0407|0410", TAG+="uaccess", GROUP="plugdev", MODE="0660"
#+end_example
