:PROPERTIES:
:ID:       20ab2c77-ba4e-4213-99cc-a3767861178d
:END:
#+TITLE: Emacs: Sibling Functons
#+DESCRIPTION: Emacs Social Cheatsheet
#+TAGS:

* Functions

#+begin_quote
Candidate ▼ Annotation
cider-connect-sibling-clj                              c@      (PARAMS &optional OTHER-REPL)           Create a Clojure REPL with the same server as OTHER-REPL.
cider-connect-sibling-cljs                             c@      (PARAMS &optional OTHER-REPL)           Create a ClojureScript REPL with the same server as OTHER-REPL.
dired-subtree-next-sibling                             c       (&optional ARG)                         Go to the next sibling.
dired-subtree-previous-sibling                         c       (&optional ARG)                         Go to the previous sibling.
dom-previous-sibling                                   f       (DOM NODE)                              Return the previous sibling of NODE in DOM.
emmet-sibling                                          f       (INPUT)
emmet-siblings                                         f       (INPUT)                                 Parse an e+e expression, where e is an tag or a pexpr.
find-sibling-file                                   (C-x f s)    c       (FILE)                                  Visit a "sibling" file of FILE.
find-sibling-file-search                               f       (FILE &optional RULES)                  Return a list of FILE’s "siblings".
magit-section-backward-sibling                         c       ()                                      Move to the beginning of the previous sibling section.
magit-section-forward-sibling                          c       ()                                      Move to the beginning of the next sibling section.
magit-section-siblings                                 f       (SECTION &optional DIRECTION)           Return a list of the sibling sections of SECTION.
nxml-following-sibling-data-p                          f       ()
nxml-preceding-sibling-data-p                          f       ()                                      Return non-nil if there is a previous sibling that is data.
org-agenda-archive-to-archive-sibling                  c       ()                                      Move the entry to the archive sibling.
org-archive-to-archive-sibling                         c       ()                                      Archive the current heading by moving it under the archive sibling.
org-block-todo-from-children-or-siblings-or-parent     f       (CHANGE-PLIST)                          Block turning an entry into a TODO, using the hierarchy.
org-export-first-sibling-p                             f       (BLOB INFO)                             Non-nil when BLOB is the first sibling in its parent.
org-export-last-sibling-p                              f       (DATUM INFO)                            Non-nil when DATUM is the last sibling in its parent.
org-first-sibling-p                                    c       ()                                      Is this heading the first child of its parents?
org-fold-show-siblings                                 f       ()                                      Show all siblings of the current headline.
org-get-last-sibling                                   f&-     ()                                      Move to previous heading of the same level, and return point.
org-get-next-sibling                                   f       ()                                      Move to next heading of the same level, and return point.
org-get-previous-sibling                               f       ()                                      Move to previous heading of the same level, and return point.
org-goto-sibling                                       f       (&optional PREVIOUS)                    Goto the next sibling, even if it is invisible.
org-show-siblings                                      f&-     ()                                      Show all siblings of the current headline.
outline-get-last-sibling                               f       ()                                      Move to previous heading of the same level, and return point.
outline-get-next-sibling                               f       ()                                      Move to next heading of the same level, and return point.
smie-rule-sibling-p                                    f       ()                                      Return non-nil if the parent is actually a sibling.
widget-get-sibling                                     f       (WIDGET)                                Get the item WIDGET is assumed to toggle.
window--resize-siblings                                f       (WINDOW DELTA &optional HORIZONTAL IG…  Resize other windows when WINDOW is resized vertically by DELTA pixels.
window-next-sibling                                    sf      (&optional WINDOW)                      Return the next sibling window of window WINDOW.
window-prev-sibling                                    sf      (&optional WINDOW)                      Return the previous sibling window of window WINDOW.
#+end_quote

* Variables

#+begin_quote
find-sibling-rules              u       nil                                    Rules for finding "sibling" files.
wgrep-sibling-buffer            lv      nil
org-archive-sibling-heading     u       "Archive"                              Name of the local archive sibling that is used to archive entries locally.
#+end_quote

** Handlers
