:PROPERTIES:
:ID:       8c34b195-76d9-4382-9600-45d70b2403d1
:END:
#+TITLE:     Cheatsheets: Index
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

* Resources
+ [[https://derechodelared.com/category/cheat-sheet/][Derecho Delared]]

** GNU

+ The Emacs refcard sources use =tex= and are in [[https://github.com/emacs-mirror/emacs/tree/master/etc/refcards][etc/refcards]]
+ The Guix refcard uses the =lout= format and sourced from
  [[https://git.savannah.gnu.org/cgit/guix/maintenance.git/tree/doc/refcard/guix-refcard.lout][doc/refcard/guix-refcard.lout]] in the [[https://git.savannah.gnu.org/cgit/guix/maintenance.git/tree/doc/refcard/guix-refcard.lout][guix/guix-maintainance]] repo


* TODO convert emacs keymaps and/or general.el output to SVG's

* On My Cheatsheets

This org roam category contains cheatsheets. For now these are mostly applicable
with my own system -- containing references to keybinds in my own emacs init.el
for example.

This information is all easy to find online, in manuals, in emacs or in
man/info, but it is rarely distilled or visually condensed. It always consumes
monitor space, where on paper it's easy to organize my thoughts and notate
quickly with pen/pencil. It's also hard to pull the content away from
distractions/notifications while I study if it's online.

Having a library of this content helps quite a bit. I've collected and printed
probably 250+ pages of the kind of well-arranged and dense information that I
wish I could find in a single book -- yet most of it obselesces as quickly as
it's published. There's something special about universally relevant tech info,
especially when it's timeless. Bash is one such . POSIX is another. This is the
kind of information that I especially value having printed in a condensed format.

If I intend on publishing them, they are likely to become scripted, whereby the
org tables will be populated from shell/elisp scripting results. I also may
prefer publishing something I illustrated anyways.

They should still contain valuable information in the meantime

** On Handwritten Notes

It's actually more helpful when it's printed just small enough to read. After
all, if I can't read it, but I know what is written, then my brain has to draw
more on my memory to fill in the blanks quickly. The overall visual arrangement
of information is something that becomes more important than the
words/characters which are always slow to read and fast to know. This thus hacks
my brain's tendency to follow the path of least resistence -- which is helpful,
since my memory sucks and for whatever reason, it seems more taxing than it
should be so much so that my Alt-Tab/Ctrl-T reaction became conditioned to
instinctively reach for Google at every chance...

** On Old Textbooks

Old textbooks always have a different perspective that we can look back on from
the shoulders of giants in just as distinct a perspective as those older notions
we dismiss today as being outdated or irrelevant. Donald Knuth's four books
exemplify this. RPC is an example of a type of interface that is consistently
reinvented. Another lense that's helpful to dust off quite often: the evolution
from thin-client/mainframe to fat-client and back -- this plays out repeatedly,
but the topologies continue to become flipped inside out, convoluted and
contraposed. Thus, these paradigmatic frames are much simpler to understand as
prototypes to recompose into metatypes when they can be distilled into their
simplest form.
