:PROPERTIES:
:ID:       41400dfc-5525-4634-9b69-0459c903445b
:END:
#+TITLE:     Cheatsheet: VA Code ยง 37.2-800
#+AUTHOR:    David Conner
#+EMAIL:     aionfork@gmail.com
#+DESCRIPTION: notes

Chapter 8. Emergency Custody and Voluntary and Involuntary Civil Admissions

Here it is, your TDO Cheatsheet for 51/50 Kangaroo Court, where there is:

+ one window and zero due process (but "no charges")
+ no pencils, but maybe you can write it with a crayon
+ no "legal record" but countless lifelong repurcussions
+ no 5th or 8th amendment rights
+ no access to external resources: to include almost all people &
  places
+ no internet, no social media, no books (okay maybe two)
+ arguably no access to patient rights, since you are not
  realistically able to become informed during your treatment
+ no need for your miranda rights, including access to an attorney for
  Kangaroo Court.
+ constant stimulation by insane people, who are known to rub off on
  each other

There's also a need to restrict information flow to you, in order to
control variables so observation is more effective. you gradually
awaken to the system rules/structure which nurses/doctors have seen
play out hundreds of times. It is effective, but also bullshit.

** CSS Import Rule

See [[https://developer.mozilla.org/en-US/docs/Web/API/CSSImportRule/media][CSSImportRule]]

Disable printing customization in [[https://law.lis.virginia.gov/Scripts/printThisCoV.js][printThisCoV.js]] by running the following.

#+begin_src js

// convert to an iterable
const styleSheets = document.styleSheets;
const sheets = [];
const rgxDns=new RegExp("virginia\.gov")

var sheets2 = []

// new Regexp().constructor === Regexp.prototype.constructor??... yes
for (let i=0;i<styleSheets.length;i++){
    let s = styleSheets[i];

    // sheets.pop() doesn't provide a preview because if they made it
    // so, that would seriously slow some subr shit down.
    //
    // can't push to sheets now

    // await undefined void 0
    console.log(s)
    console.log(s.href)
    if (s.href && s.href.match(rgxDns))
	if (s.media.length > 0) {
	    sheets2.push(s);
	}
    }
}
#+end_src

** This still worked though

Add this inline stylesheet customizations

#+begin_src css

/* 986_grid.css | https://law.lis.virginia.gov/Content/986_grid.css */

.flipcol .slot-6-7-8 {
  /* padding-left: 249px; */
}

.slot-6-7-8, .slot-7-8-9 {
  /* width: 717px; */
}

.slot-0, .slot-1, .slot-2, .slot-3, .slot-4, .slot-5, .slot-0-1, .slot-0-1-2, .slot-0-1-2-3, .slot-0-1-2-3-4, .slot-0-1-2-3-4-5, .slot-1-2, .slot-1-2-3, .slot-1-2-3-4, .slot-1-2-3-4-5, .slot-2-3, .slot-2-3-4, .slot-2-3-4-5, .slot-3-4, .slot-3-4-5, .slot-4-5, .slot-6, .slot-7, .slot-8, .slot-9, .slot-6-7, .slot-6-7-8, .slot-6-7-8-9, .slot-7-8, .slot-7-8-9, .slot-8-9 {
  /* float: left; */
}

.grid {
  /* width: 966px; */
}

/* 720_grid.css | https://law.lis.virginia.gov/Content/720_grid.css */

.flipcol .slot-6-7-8 {
  /* padding-left: 180px; */
}

.grid {
  /* width: 700px; */
}

dl.number-descrip-list-outline {
  /* line-height: 1.55em; */
  line-height: 1.25em;
}

dl.number-descrip-list-outline dt {
  /* clear: left; */
  /* float: left; */
  /* display: table-cell; */
}

dl.number-descrip-list-outline dd {
  /* display: table-cell; */
  flex-basis: 90%;
  flex-shrink: 4;
  margin-left: 10px;
}

/* base.css | https://law.lis.virginia.gov/Content/base.css */

article.content {
  /* float: left; */
}

dl.number-descrip-list-outline {
  /* margin-left: 1em; */
  display: flex;
  flex-wrap: wrap;
  justify-content: right;
}

dl.number-descrip-list-outline dt {
  /* width: 7em; */
  flex-basis: content;
  flex-shrink: 0;
}

#+end_src

* wow

One thing happening sure does lead to another, am I right? My life is
so staged...... Exactly why no one will say anything to defend me or
support me (if this were to happen...)

Gee I wonder why I don't trust anyone.

Regardless, I'm sure not looking forward to the TDO Kangaroo Court's
weeklong Jumanji lighting round. With such inexplicable rules, you may
never leave.
