:PROPERTIES:
:ID:       ebc4951b-6969-4436-4321-f9d7b4406cf1
:END:
#+TITLE:     XDG: Icon Naming Specification
#+AUTHOR:    David Conner
#+EMAIL:     aionfork@gmail.com
#+DESCRIPTION: notes
#+OPTIONS: ':nil *:t -:t ::t <:t \n:nil ^:t arch:headline
#+OPTIONS: author:nil c:nil d:(not "LOGBOOK") date:nil
#+OPTIONS: e:t email:nil f:t inline:t num:nil p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:nil todo:t |:t
#+OPTIONS: toc:nil
#+SELECT_TAGS:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en

* Contexts

|--------------+------------+------------+------------+---------------+-----------+--------+-----------|
| Name         | *Directory*  | Name       | *Directory*  | Name          | *Directory* | Name   | *Directory* |
|--------------+------------+------------+------------+---------------+-----------+--------+-----------|
| Actions      | *actions*    | Categories | *categories* | Emotes        | *emotes*    | Places | *places*    |
| Animations   | *animations* | Devices    | *devices*    | International | *intl*      | Status | *status*    |
| Applications | *apps*       | Emblems    | *emblems*    | MimeTypes     | *mimetypes* |        |           |
|--------------+------------+------------+------------+---------------+-----------+--------+-----------|
*  

#+begin_export html
<pre>
#+end_export

#+begin_verse
_.$theme/actions_                                                                            _./$theme/apps_

*address*            *format*                    *mail*                   *tools*                  *accessories*
└── book           ├── indent                ├── forward            └── check              ├── calculator
└── new            │   ├── less              ├── mark                   └── spelling       ├── character
                   │   └── more              │   ├── important                             │   └── map
*application*        ├── justify               │   ├── junk           *view*                   ├── dictionary
└── exit           │   ├── center            │   ├── notjunk        ├── fullscreen         ├── screenshot
                   │   ├── fill              │   ├── read           ├── refresh            │   └── tool
*appointment*        │   ├── left              │   └── unread         ├── restore            └── text
└── new            │   └── right             ├── message            └── sort                   └── editor
                   └── text                  │   └── new                ├── ascending
*call*                   ├── bold              ├── reply                  └── descending     *help*
├── start              ├── direction         │   ├── all                                   └── browser
└── stop               │   ├── ltr           │   └── sender         *window*
                       │   └── rtl           └── send               ├── close              *multimedia*
*contact*                ├── italic                └── receive        └── new                └── volume
└── new                ├── strikethrough                                                       └── control
                       └── underline         *media*                  *zoom*
*document*                                     ├── eject              ├── fit                *preferences*
├── new            *go*                        ├── playback           │   └── best           └── desktop
├── open           ├── bottom                │   ├── pause          ├── in                     ├── accessibility
│   └── recent     ├── down                  │   ├── start          ├── original               ├── font
├── page           ├── first                 │   └── stop           └── out                    ├── keyboard
│   └── setup      ├── home                  ├── record                                        ├── locale
├── print          ├── jump                  ├── seek                                          ├── multimedia
│   └── preview    ├── last                  │   ├── backward       _./$theme/animations_        ├── screensaver
├── properties     ├── next                  │   └── forward                                   ├── theme
├── revert         ├── previous              └── skip               *process*                    └── wallpaper
├── save           ├── top                       ├── backward       └── working
│   └── as         └── up                        └── forward                               *system*
└── send                                                                                   ├── file
                   *help*                      *object*                 _./$theme/categories_    │   └── manager
*edit*               ├── about                 ├── flip                                      └── software
├── clear          ├── contents              │   ├── horizontal     *applications*               ├── install
├── copy           └── faq                   │   └── vertical       ├── accessories            └── update
├── cut                                      └── rotate             ├── development
├── delete         *insert*                        ├── left           ├── engineering        *utilities*
├── find           ├── image                     └── right          ├── games              ├── system
│   └── replace    ├── link                                         ├── graphics           │   └── monitor
├── paste          ├── object                *process*                ├── internet           └── terminal
├── redo           └── text                  └── stop               ├── multimedia
├── select                                                          ├── office
│   └── all        *list*                      *system*                 ├── other
└── undo           ├── add                   ├── lock               ├── science
                   └── remove                │   └── screen         ├── system
*find*                                         ├── log                └── utilities
└── location                                 │   └── out
                                             ├── reboot             *preferences*
*folder*                                       ├── run                ├── desktop
└── new                                      ├── search             │   ├── peripherals
                                             └── shutdown           │   └── personal
                                                                    ├── other
                                                                    └── system
                                                                        └── network

                                                                    *system*
                                                                    └── help
#+end_verse

#+begin_export html
</pre>
<br>
#+end_export

#+begin_export html
<pre>
#+end_export

#+begin_verse
_./$theme/devices_                  _./$theme/mimetypes_               _./$theme/status_                            
                                                                                              
*audio*                             *application*                      *appointment*                    *sync*                    
├── card                          └── x                            ├── missed                     ├── error                
└── input                             └── executable               └── soon                       └── synchronizing       
    └── microphone                                                                                                         
                                  *audio*                            *audio*                          *task*                    
*battery*                           └── x                            └── volume                     ├── due                  
                                      └── generic                      ├── high                   └── past                
*camera*                                                                 ├── low                        └── due             
├── photo                         *font*                                 ├── medium                                          
├── video                         └── x                                └── muted                  *user*                    
└── web                               └── generic                                                 ├── available           
                                                                   *battery*                        ├── away                
*computer*                          *image*                            ├── caution                    ├── idle                 
drive                             └── x                            └── low                        ├── offline             
├── harddisk                          └── generic                                                 └── trash               
├── optical                                                        *dialog*                             └── full            
└── removable                     *package*                          ├── error                                               
    └── media                     └── x                            ├── information                *weather*                 
                                      └── generic                  ├── password                   ├── clear               
*input*                                                              ├── question                   │   └── night           
├── gaming                        *text*                             └── warning                    ├── few                 
├── keyboard                      ├── html                                                        │   └── clouds          
├── mouse                         └── x                            *folder*                         │       └── night       
└── tablet                            ├── generic                  ├── drag                       ├── fog                 
                                      │   └── template             │   └── accept                 ├── overcast            
*media*                                 └── script                   ├── open                       ├── severe              
├── flash                                                          └── visiting                   │   └── alert           
├── floppy                        *video*                                                           ├── showers             
├── optical                       └── x                            *image*                          │   └── scattered       
└── tape                              └── generic                  ├── loading                    ├── snow                
                                                                   └── missing                    └── storm
*modem*                                                                   
                                  *x*                                                           
*multimedia*                        └── office                       *mail*                      
└── player                            ├── address                  ├── attachment              
                                      │   └── book                 ├── read                   
*network*                               ├── calendar                 ├── replied                
├── wired                             ├── document                 ├── signed                 
└── wireless                          ├── presentation             │   └── verified           
                                      └── spreadsheet              └── unread                 
*pda*                                                                                           
                                                                   *media*                     
*phone*                             _./$theme/intl_                    └── playlist                
                                                                       ├── repeat             
*printer*                           *flag*                                 └── shuffle            
                                  └── aa                                                      
*scanner*                                                            *network*                   
                                                                   ├── error                   
*video*                             _./$theme/places_                  ├── idle                   
└── display                                                        ├── offline                
                                  *folder*                           ├── receive                
                                  └── remote                       └── transmit               
_./$theme/emblems_                                                       └── receive            
                                  *network*                                                    
*emblem*                            ├── server                        *printer*                  
├── default                       └── workgroup                    ├── error                   
├── documents                                                      └── printing               
├── downloads                     *start*                                                       
├── favorite                      └── here                         *security*                  
├── important                                                      ├── high                    
├── mail                          *user*                             ├── low                    
├── photos                        ├── bookmarks                    └── medium                 
├── readonly                      ├── desktop                                                 
├── shared                        ├── home                         *software*                  
├── symbolic                      └── trash                        └── update                  
│   └── link                                                           ├── available          
├── synchronized                                                       └── urgent             
├── system                                                                                    
└── unreadable
#+end_verse           

#+begin_export html
</pre>
#+end_export



* noexport :noexport:

#+begin_src javascript
let iconContexts = Array.from(document.querySelectorAll('.sect1 table'))[0];
let iconContextRows = Array.from(iconContexts.querySelectorAll('tr td')).
    reduce((acc,el,i) => ((i % 3 != 1) && acc.push(el.innerText) && acc) || acc, []);
console.log("| " + iconContextRows.sort().join("\n| "))
#+end_src

it's all ascii, so uppercase preceeds lowercase.

+ I can select 11 rows, use =mc/edit-lines=
+ Then knock them to one line. Repeat for the next 11
+ Then =org-table-transpose-table-at-point=

#+begin_src javascript
let iconTables = Array.from(document.querySelectorAll('.table[id]')).slice(1);
let iconNames = iconTables.map(function (t) {
  return {
    key: t.id,
    value: Array.from(t.querySelectorAll('tbody tr td:first-child')).
      reduce((acc,name) => (acc.push(name.innerText.replaceAll("-","/")) && acc), [])
  }})
console.log(iconNames.map(c => (`** ${c.key}\n\n` + c.value.join('\n'))).join('\n\n'))
#+end_src

Then copy, then =C-u M-|= and for each:

+ =tree --noreport --fromfile . | sed -e 's/^....//g'=
+ =M-x query-replace-regexp= with =^J\([a-z0-9]+\)^J= → =^J^J*\1*^J"=
+ Then =M-x query-replace-regexp= with =^\s\{4\}= → three =M-x insert-char= with
  =non-breaking=... before =C-& i= for =yas-insert-snippet= with =verse= block to retain
  formatting.

Thanks alot, Github. Thanks for screwing up the formatting.

#+begin_src css
/* org reset --------------------------------------------- */
body { font-size: 0.9em; margin: 0.1em; padding: 0em }
p { font-size: 0.9em; }
th { background-color: seagreen; color: #F6F6F6; }
table { border: 1px solid darkgreen; border-radius: 3px; }
th,td { border: 1px solid darkgreen; padding: 0.2em; font-size: 0.9em; }
#content { max-width: 100% !important }
code { color: indigo; }
h1,h2,h3,h4,h5 { margin: 0.2em; padding: 0.1em}
ul,ol { margin: 0.1em; }

dd { margin: 0.1em 2em; }
li { margin: 0.1em; }

/* cheatsheet --------------------------------------------- */
table { display: table; margin: auto; }
pre { background: inherit; border: none; padding: 0.2em; margin: 0.2em auto; display:table; }
h2 { color: darkblue; font-size: 1.1em; line-height: 1.1em; text-align: center; margin: 0.2em auto; }

/* this rule is needed twice for some reason */
p.verse b { color: darkgreen !important; }
p.verse b { color: darkgreen; }
p.verse span.underline { color: maroon !important; }  /* font-weight: 550; */
/* p.verse b { color: darkgreen; } */
p.verse { font-family: monospace; line-height: 0.7em; padding: 0; margin: 0.2em}; }
#+end_src
