

* Headline
David Conner

Versatile Software Engineer and Aspiring Polymath

*** Address

426 N. Market St.
Salem, VA 24153
dconner.pro@gmail.com
(540)761-1257

* Overview

I'm a metacognition auteur who enjoys dissecting mental models and finding
creative ways to connect diverse fields.

As an aspiring polymath, I hope to apply first-hand experience with diverse
fields to connect them together in unexpected ways.

#+begin_quote
Nope, they're looking for an NPC
#+end_quote

Experienced full-stack software developer with experience in almost every layer
of abstraction: from bit crunching in binary, hardware, operating systems, text
editors, applications, graphics, databases, and networking to web applications,
frontend frameworks, javascript and HTML. Metacognition auteur who enjoys:
dissecting and reconfiguring mental models; exploring epistemology in terms of
spectral graph theory and algebra; finding unique ways to connect seemingly
unrelated fields. Finds a way to model everything in terms of math; there is
always a way. Worked with .NET and C# to extend functionality of Microsoft GP
and Cisco UCCX call centers. Developed frontend applications with Angular. Built
API’s with NodeJS. Misses Ruby on Rails a little bit. Fast learner with a thirst
for staying ahead in the technology world. Longs for relocation to a city with a
thriving technology community (and one where access to niche subcultures like
Kendo are the norm). Skilled at integrating disparate systems with minimal
service interruptions and no loss of data. Understands what the business and its
customers want and knows how to automate it. Willing to be on call, respond to
emergencies, and complete upgrades after hours.

** Skills and key experience include:

⊗ Ruby, NodeJS, JS, TS
⊗ Startups, Business Models
⊗ Social Physics
⊗ Mathematics
⊗ Swift, iOS, Metal
⊗ Marketing, PR, Branding
⊗ 21st Century Philosophy
⊗ Machine Learning
⊗ Angular 6, WebGL
⊗ C#, MSSQL, PostgreSQL
⊗ Psychology, Sociology
⊗ Writing
⊗ Fullstack (12 Factor)
⊗ Payroll Databases
⊗ Linguistics, Semiotics
⊗ Epigenetics
⊗ Java, Clojure, Android
⊗ SQL Reporting, Optimization
⊗ Marketing, PR, Branding
⊗ Bioinformatics

* Professional Experience

** RAKE DIGITAL  – Salem, VA		January 2018 – September 2018

Rake’s cloud engineers and experts collaborate to provide customized digital services to design, implement, and maintain Azure cloud infrastructures, particularly for professional service organizations and government agencies. Rake hosts ReadyPay accounting software for clients who manage payroll for thousands of businesses.
Cloud Engineer		[January 2018 – September 2018]
    • Used MS SQL table metadata to quickly learn the accounting database schema for Millennium and ReadyPay. Instantly developed an understanding of how to algebraically manipulate business records and accounting data; learned how to create a network of shell companies to launder money in the Caymans.
    • Wrote SQL scripts to migrate payroll data from Millennium to ReadyPay and to provide reporting for payroll account reconciliation for CPA’s at Rake Digital. Never produced invalid results for payroll, accounting and tax queries.
    • Developed familiarity with all of Azure’s API’s by writing scripts to convert Swagger JSON to UML to PNG images for documentation. Wrote python scripts for configuration management.
    • Developed documentation in VISIO for virtual networks, managed servers & services in Azure.
    • Designed an application stack with LoopbackJS and Angular 6 to automate Millennium & ReadyPay tasks in Azure. Wrote Powershell scripts to collect service metrics for display in Site 24x7 charts.
    • Managed the VOIP phone system.

** VOXXEL  – Salem, VA		February 2016 – Mid 2017

Voxxel was an app for creators, fans and entertainers to see how their movie, personality and accent impersonators stacked up against other Voxxel users. An algorithm would score the user-submitted audio samples for similarity to the source samples. The collected data would be useful in training other audio processing algorithms to distinguish types of emotional inflection.
Founder (Not Incorporated)		[February 2016 – 2017]
    • Built out a working proof-of-concept for the app in iOS, Android and AngularJS (with Web Audio).
    • Developed plans for staging the startup's development through various phases and developed a business model based on potential revenue streams. Could not find a cofounder. Burnt myself out.

** OSCIL8  – Salem, VA		November 2011 – Late 2015

Oscil8 was designed to be the “Github for Music Producers” where musicians, audio engineers and foley artists of any skill level can collaborate, learn their craft, find inspirations, make connections and promote their craft to fans and labels.
Founder (Not Incorporated)  		[November 2011 – 2015]
    • Researched MIDI protocol. Wrote software to translate MIDI SYSEX messages from hardware synths to and from JSON to enable producers to reload, visually edit, backup and share hardware configurations.
    • After Splice.io was released to the public October 2014, Oscil8 was pivoted to specifically focus on two alternative revenue streams: development of an “App Store” for hardware/software sample packs (which Splice eventually monetized) and development of a cloud-based platform to rent time on hardware synthesizers to produce samples.
    • Could not find a cofounder. Splice.io has a valuation that has surpassed $100M.

** LEFT + RIGHT  – Richmond, VA		February 2014 – August 2014
The L+R team has unique startup experience navigating the ups and downs of building great software.
Rails Developer (Independent Contractor)  		[February 2014 – August 2014]
    • Containerized Ruby applications for deployment with Docker and CoreOS.
    • Developed a Rails Reporting API that interfaced with databases from several other apps.
    • The Reporting API aggregated data stored in multiple databases from an Amazon RDS Mysql Server.

** JUMPCLOUD  – Boulder, CO		July 2013 – August 2013
Jumpcloud provides a Cloud Server Access Control SaaS.
Software Engineer  		[July 2013 – August 2013]
    • Simulated various client/server configurations in Vagrant multi-VM environment.
    • Full stack development using a NodeJS API and MongoDB.
    • Built and tested clients on multiple versions of Ubuntu and CentOS.
    • Wrote unit and integration tests using Mocha, Selenium and Soda.

** WEEDMAPS  – Denver, CO		February 2013 – May 2013
Weedmaps helps people find dispensaries.
Rails Developer  		[February 2013 – May 2013]
    • Integrated with ElasticSearch to help users find the nearest results.
    • Implemented Backbone to provide a fluid user experience.
    • Resolved bugs in API and Frontend using Airbrake.
    • Obtained Android debug data to help troubleshoot issues on specific handsets.
    • Wrote gems to facilitate testing.

** SIC SEMPER LLC  – Salem, VA		March 2012 – February 2013
Sic Semper designs, develops and optimizes web applications.
Owner  		[March 2012 – February 2013]
    • Optimization of reporting in Rails applications.
    • Development of Skiima gem to load and unload SQL objects for testing.

** ENABLE LABS  – Troy, NY		February 2012 – March 2012
Enable Labs designs, implements and deploys Rails applications.
Rails Developer  		[February 2012 – March 2012]
    • PDF generation of invoices using Prawn and Prawnto2.
    • Reduced time required for tests from over 10 minutes to less than 2 minutes.
    • Implemented Hydra to utilize multiple CPU cores for testing.
    • Implemented Capybara-Webkit for headless javascript testing.

** INTERNET MARKETING NINJAS  – Clifton Park, NY	September 2011 – January 2012
IMNinjas provides SEO and internet marketing services to clients and provides free SEO tools online.
Rails Developer  		[September 2011 – January 2012]
    • Quickly able to contribute to a framework with JRuby, MongoDB, RabbitMQ and Knockout.JS
    • Worked diligently to help ensure our large codebase was clean and manageable.
    • Utilizing a queued architecture, harvested data from numerous sources and API's and distilled into data used by online tools.  Data was cached where valid and not expired.
    • Wrote modules and tools to help minimize developer time on repeated tasks.
    • Facilitated debugging by creating a means to collect and display exceptions documents.
    • Used Knockout.JS to update a view with updates in a view model, in real time.
    • Added Standard Threads and Celluloid Futures to speed up worker processes.
    • Designed a means to extract the framework into a serviced based architecture using gems and quickly evolve the project to be more easily deployed and more maintainable.
    • Using git logs and ffmpeg, scripted creation of code swarm videos that showed team progress and allocation by model and per each project API source.

** QUOTIENT, INC. – Columbia, MD		May 2011 – March 2012
Quotient is a proven provider of comprehensive custom solutions to government and commercial clients.
Rails Developer (Independent Contractor) 		[May 2011 – March 2012]
    • Configuring Cron tasks for server maintenance and retrieving email on an EngineYard instance.
    • Writing Rails migrations to add indexes, improving application and MySQL performance.
    • Using Request Log Analyzer to identify requests and queries that need optimization most.
    • Modifying implementation of ExtJS javascript framework to fix defects and extend functionality.
    • Using Git and Github to maintain separate branches for features in development and for deployment of Production and Development environments.
    • Migrating a legacy Rails 1.2.6 application to a new server running with Apache/Passenger with a Passenger Spawn Server.

** WE ARE TITANS – Norfolk, VA		May 2011 – July 2011
We Are Titans is an agile development and design company skilled in Rails and iOS development.
Rails Apprentice		[May 2011 – June 2011]
    • Pair programming to develop features and Rspec tests for Rails applications.
    • Writing acceptance, controller and model tests using RSpec and Capybara.
    • Deploying Rails applications to the Heroku cloud infrastructure and maintaining Postgres data.
    • Creating and integrating new engines to extend functionality of Refinery CMS.
    • Integrating Refinery CMS with Amazon S3 for storage in the cloud.

** ABS TECHNOLOGY ARCHITECTS – Roanoke, VA	February 2007 – April 2011
ABS is an advanced technology solutions provider specializing in Cisco IP Technologies.
Database and Report Developer 		[Feb 2007 – Feb 2010]
Contract Consultant		[Feb 2010 – April 2010]
Network Engineer		[Mar 2011 – April 2011]
    • Managed the design, development, and documentation of Crystal Reports for Cisco IPCC and related systems used by Fortune 500 companies.
    • Used C# and MSSQL to design dashboards interfacing with IPCC Call Center to help supervisors determine in real time optimal staffing needs, results of marketing efforts, and agent productivity.
    • Integrated marketing data based on customer’s dialed phone number and path through the call center with Oracle sales databases and other external systems.
    • Created summarized reports in Ruby using text output from a Cisco ASA firewall to help eliminate unused or overlapping object groups and rules to improve firewall performance.

** COMPREHENSIVE COMPUTER SOLUTIONS – Christiansburg, VA	July 2010 – March 2011
CCS provides computer, enclosure and networking solutions to manufacturers around the world.
Software Developer 		[Jul 2010 – Mar 2011]
    • On Internal Programs team, developed web applications and reports for MS GP/ERP in C# and SQL
    • Identified and devised solutions for bugs in GP and internal tools, including one where GP custom variable data was sporadically not found and caused logistic problems in internal tools.
    • Administered software and implemented processes for agile software development.
    • Reduced the time required for one internal web application for listing the upcoming jobs from over 70 seconds to less than 10 seconds by optimizing the queries used.
    • Maintained SSRS reports which aggregated sales data for four separate business units.
    • Produced reports on financials from accounting data from MS GP/ERP
* Technical Skills
Ruby/Rails ∘ Redis ∘ Clojure ∘ NodeJS ∘ Javascript ∘ Python ∘ Swift ∘ Metal (Apple Graphics)
HTML/CSS ∘ Web Audio ∘ Angular 6 ∘ Unix ∘ Git ∘ Emacs ∘ Emacs Lisp

C# ∘ MSSQL ∘ SSIS/SSRS ∘ Crystal Reports ∘

Postgres ∘ Route/Switch ∘ VOIP/IVR/Reporting

GIS (limited) ∘ GDAL and Mesh Triangulation ∘ Uber's Viz.gl, Deck.gl, Luma.gl (for graphics & GIS)

* Education
** VIRGINIA TECH – Blacksburg , VA – 2004 to 2006
Completed two years of study towards a Bachelor's Degree in Computer Science
** VIRGINIA WESTERN – Roanoke, VA – 2007
Studied at the Cisco Networking Academy and achieved the Cisco CCNA Certification
** COURSERA – Coursera.com – 2012 to 2015
Studied Machine Learning, Bioinformatics, Epigenetics, Cryptography
** CONTINUAL LEARNING – Internet – 2012 ad infinitum
At least a basic familiarity with: Bioinformatics ∘ Epigenetics ∘ Chemistry ∘ Physics ∘ Logistics
Business ∘ Venture Capital ∘ Finance ∘ Economics ∘ Mathematics ∘ Linguistics ∘ Semiotics
Neurology ∘ Psychology ∘ Sociology ∘ Pharmacology ∘ Philosophy ∘ Biomechanics
3D Graphics ∘ Computational Geometry ∘ Mythology ∘ Art History ∘ Color Chemistry
Copyright Law ∘ International Law ∘ Maritime Law ∘ Military Strategy/Doctrine
(via Simon’s Institute, Institute for Advanced Study, NPTEL and others)
** Hobbies
Art ∘ Graffiti ∘ Breakdancing ∘ Poplocking ∘ Jamskating ∘ DnD ∘ Board Games
Electronics ∘ Music Production ∘ Writing & Philosophy ∘ Tarot ∘ I Ching ∘ Jung
Kanji ∘ Japanese (limited) ∘ Hangul ∘ Bilingual Books ∘ French ∘ Spanish (reading only)
