:PROPERTIES:
:ID:       b4287471-d846-4a18-bf2e-31e74f1b9e64
:END:
#+CATEGORY: resume


* Roam

* Docs

* Notes


** Versions

*** 2026 July

**** Improvements

The assumptions that org-babel and org-export make on document structure work
much better for some documents -- not this one per se. I get the feeling that
more knowledge of latex would go a long way...

i need to know how to change out the underlying document class (or wrapping
inner output) without affecting overall layout.

#+begin_quote
e.g. skills/tools have a different inner structure and the basic setup cant
naively translate it without a lot of raw latex.
#+end_quote

Ideally, I'd supply some data/metadata, then be able to generate slightly
different versions. This can be difficult as code.

I could use ~org-babel~ to emit an ~export latex~ block from data in tables/etc, but
that seems messy. Not impossible, but messy and leading to tedious maintainence.

**** Options

+ Revise in overleaf, so i can understand the relationships between document
  elements. Once it looks alright, then produce the document in org.
  - still, deciding what basic macros/etc. for the overall skeleton has
    particular consequences with strange nuances. (lack of experience/guidance)
  - once you know the magic =\words{fdsa}= that work well with each other, i think
    it's much simpler. e.g. environments vs. global state vs
    latex-function-thingies without environments? -- one does not simply mix &
    match ... or one does not get a PhD.

+ Or find a new template. This one works well in some ways, but the mixed units
  for =A4= and =Letter= layout detract from something I really like about LaTeX:
  declarative precision.
  - It's more difficult to get satisfying precision from simple HTML/CSS. As I
    found out the hard way with these [[id:18b6e880-37af-4276-ae0a-9f92f02d0412][FRC: April Tags]]. There, I started with
    tight tolerances which were difficult to measure in small =1x1= printed tags
    which became noticeable at =6.25x6.25= .... and for a while, I was =~98%=
    confident that it was at least =~98%= accurate.

**** Issues

LaTeX's block model isn't much different than HTML, which is actually much more
complicated. It actually makes you understand & appreciate HTML more.

However, LaTeX imposes some global geometry constraints -- 2D width/height --
which make typical templates more challenging for complex arrangements. Outside
of the basic header/footer or other visual structure in/around the top-level
document, this starts getting hairy if you really want a dense presentation
without small typesetting artifacts.


