:PROPERTIES:
:ID:       5e1d0068-b3d4-4d49-6543-1972998f6e0d
:END:
#+TITLE:     David Conner Resume (twocol, letter)
# +SUBTITLE:  Subtitle
#+CATEGORY: resume
#+AUTHOR:    David Conner

# ## see notes at the end to export/generate

#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:nil c:nil d:(not "LOGBOOK") date:nil title:nil
#+OPTIONS: e:t email:nil f:t inline:t num:nil p:nil pri:nil stat:t
#+OPTIONS: tags:nil tasks:nil tex:t timestamp:nil todo:nil |:t
#+OPTIONS: toc:nil

#+SELECT_TAGS:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en

#+STARTUP: inlineimages

#+PROPERTY: header-args :eval never-export

#+LATEX_CLASS: resume
#+LATEX_CLASS_OPTIONS: [10pt,letterpaper]

#+LATEX_HEADER_EXTRA: \usepackage[utf8]{inputenc}
#+LATEX_HEADER_EXTRA: \usepackage{xifthen}

# #+LATEX_HEADER_EXTRA: %\usepackage[defaultsans]{droidsans}
# #+LATEX_HEADER_EXTRA: %\usepackage[default]{comfortaa}
# #+LATEX_HEADER_EXTRA: %\usepackage{cmbright}
# #+LATEX_HEADER_EXTRA: %\usepackage[default]{raleway}
# #+LATEX_HEADER_EXTRA: %\usepackage{fetamont}
# #+LATEX_HEADER_EXTRA: %\usepackage[default]{gillius}
# #+LATEX_HEADER_EXTRA: %\usepackage[light,math]{iwona}
# #+LATEX_HEADER_EXTRA: % \usepackage[thin]{roboto}

#+LATEX_HEADER_EXTRA: \usepackage[T1]{fontenc}
#+LATEX_HEADER_EXTRA: \renewcommand*\familydefault{\sfdefault}

#+LATEX_HEADER_EXTRA: \usepackage{moresize}
# #+LATEX_HEADER_EXTRA: \usepackage{showframe}

#+LATEX_HEADER_EXTRA: \usepackage[letterpaper]{geometry}
#+LATEX_HEADER_EXTRA: \geometry{top=1.00cm, bottom0.0cm, left=1.0cm, right=1.0cm}

# (8.5 x 11) ~ (21.25 X 27.5)

#+LATEX_HEADER_EXTRA: \usepackage{fancyhdr}
#+LATEX_HEADER_EXTRA: \pagestyle{fancy}
#+LATEX_HEADER_EXTRA: \setlength{\headheight}{-15pt}

#+LATEX_HEADER_EXTRA: \usepackage[none]{hyphenat}
#+LATEX_HEADER_EXTRA: \setlength{\parindent}{0mm}

#+LATEX_HEADER_EXTRA: \input{twocol.preamble.tex}

#+LATEX_HEADER_EXTRA: \usepackage{multicol}
#+LATEX_HEADER_EXTRA: \usepackage{multirow}
#+LATEX_HEADER_EXTRA: \usepackage{array}
#+LATEX_HEADER_EXTRA: \usepackage{enumitem}

#+LATEX_HEADER_EXTRA: \usepackage{graphicx}
#+LATEX_HEADER_EXTRA: \usepackage{wrapfig}
#+LATEX_HEADER_EXTRA: \usepackage{float}
#+LATEX_HEADER_EXTRA: \usepackage{tikz}
#+LATEX_HEADER_EXTRA: \usepackage{tikz-3dplot}
#+LATEX_HEADER_EXTRA: \usepackage{tcolorbox}
#+LATEX_HEADER_EXTRA: \tcbuselibrary{most}
#+LATEX_HEADER_EXTRA: \usetikzlibrary{shapes, backgrounds, mindmap, trees, math}

#+LATEX_HEADER_EXTRA: \usepackage{color}
#+LATEX_HEADER_EXTRA:  \definecolor{bgcol}{RGB}{140,130,120}
#+LATEX_HEADER_EXTRA:  \definecolor{sectcol}{RGB}{30,25,18}
#+LATEX_HEADER_EXTRA:  \definecolor{softcol}{RGB}{195,205,175}
#+LATEX_HEADER_EXTRA:  \definecolor{txtcol}{RGB}{25,20,15}
#+LATEX_HEADER_EXTRA:  \definecolor{softcol2}{RGB}{175,195,145}

#+begin_export latex
\pagestyle{fancy}
#+end_export

*  

#+begin_export latex
%	TITLE HEADLINE
\hspace{-0.25\linewidth}\colorbox{bgcol}{\makebox[1.25\linewidth][c]{\textcolor{bgcol}{\rule[-1mm]{1mm}{1.0cm}} \HUGE{\textcolor{txtcol}{\textsc{David Conner}}}}}
%---------------------------------------------------------------------------------------
%	HEADER IMAGE
% \hspace{-0.25\linewidth}\includegraphics[width=1.2725\linewidth]{myphoto.jpg} %use full size
%---------------------------------------------------------------------------------------
%	QR CODE (optional)
%\vspace{-100pt}
%\hspace{0.59\linewidth}
%\includegraphics[width=88pt]{qrcode}
%\normalsize
% \pareindent here is a hack
\setlength{\parindent}{5mm}

\vspace{-0.1cm}\\
\small{Software engineer with experience in networking, databases, containers,
and web applications. Seeking role that leverages software to solve domain-specific
problems, whether as an application programmer or devops. Experience integrating
disparate systems with minimal service interruptions and no loss of data.}

\small{Fast learner with a thirst for staying ahead in technology world.
Prefers the source code as the canonical documentation for most tools, but
also reads the docs.}\\[-2pt]
#+end_export

*  


#+begin_export latex
%---------------------------------------------------------------------------------------
%	SUMMARY (optional)
\cvsection{Summary}
\metasection{Lang}{Bash, Ruby, Python, JS, TS, Clojure, Emacs Lisp, Scheme, Julia, Scala}
\metasection{Tools}{Emacs, Org Mode, Direnv, Ansible, KDE, i3, VTY, GNU Screen, pyenv, poetry}
\metasection{Data}{Reporting, ETL, Postgres, MSSQL, SQLite3, Parquet, jq}
\cvrule{-6pt}{0pt}
\vspace{\spread}\\
\metasection{Security}{GPG, PIV, CA, Firewalls, Crypto}
\metasection{Linux}{RPM, Guix, Docker, Podman, LVM}
\metasection{Cloud}{Terraform, k8s, GCP}
\metasection{Homelab}{SDN, VLAN, Proxmox, SR-IOV, UPS/Power}
\cvrule{-6pt}{0pt}
\vspace{\spread}\\
\setlength{\parindent}{5mm}
\small{\textbf{Interests} Math, 3D Graphics, 3D Design, Philosophy, Futurism,
Writing, Linguistics, Semiotics, Bioinformatics, Epigenetics, Colorimetry,
Logistics, Materials}
#+end_export

*  

#+begin_export latex
%---------------------------------------------------------------------------------------
%	EXPERIENCE
\cvsection{Experience}
\cvevent{2022-2023}{Engineering Student Aide}{Virginia Western}
{\cvpoint{Maintained Ender-3 Pro and Raise3D printers. Synced Ender-3 configurations for PLA plastics}\\ % \\[2pt]
\cvpoint{Created an Autodesk Fusion CNC config for a Velocity CNC}\\ % \\[2pt]
\cvpoint{Collected notes on almost all equipment including support links and digital copies of manuals}} \\[\spread]
%
\cvrule{-6pt}{0pt}
%
\cvevent{2018}{Cloud Engineer}{RAKE Digital}
{\cvpoint{Used MS SQL table metadata to quickly learn the accounting database schema for Millennium and ReadyPay}\\ % \\[2pt]
\cvpoint{Designed an application stack with LoopbackJS and Angular 6 to automate payroll tasks in Azure}} % \\[\spread]
%
\cvrule{-6pt}{0pt}
%
\cvevent{2015-2017}{Founder}{Voxxel}
{\cvpoint{Voxxel enabled fans to score their impersionations of movie quotes and accents}\\ % \\[2pt]
\cvpoint{Built a Rails API to back prototypes in iOS, Android and AngularJS. Each client processed and visualized the FFT}} % \\[\spread]
%
\cvrule{-6pt}{0pt}
%
\cvevent{2011-2015}{Founder}{Oscil8}
{\cvpoint{Oscil8 was designed to be the “Github for Music Producers”}\\ % \\[2pt]
\cvpoint{Developed a business model and strategic vision}}
%
\cvrule{-6pt}{0pt}
%
\cvevent{2014}{Software Developer (Contracted)}{Left + Right}
{\cvpoint{Developed a web service to extend a Ruby on Rails application with reporting on SQL Views}\\ % \\[2pt]
\cvpoint{Cached report results in MongoDB to enable a dashboard}}
%
\cvrule{-6pt}{0pt}
%
\cvevent{2013}{Software Engineer}{Jumpcloud}
{\cvpoint{Full stack development using a NodeJS API and MongoDB}\\ % \\[2pt]
\cvpoint{Integration tests using Mocha, Selenium and Soda}} % \\[\spread]
#+end_export

*  

#+begin_export latex
%---------------------------------------------------------------------------------------
%	EDUCATION SECTION
\vspace{2pt}
\cvsection{Formal Education}\cvevent{2006-2008
2021-2023}
{Mechatronics S.E.T.}
{Virginia Western}
{\cvpoint{Obtained a Cisco CCNA certification (2008)}\\ % \\[2pt] % more condensed
\cvpoint{Studied design, manufacture, electronics, CNC and safety}\\
\cvpoint{Planning one course per semester to utilize the Fab Lab}}
%
\cvrule{-6pt}{0pt}
%
\cvevent{2004-2006; 2008}
{Computer Science}
{Virginia Tech}
{\cvpoint{Studied Computer Science. Dropped out to compete in jamskating at a national level}}\\
%\textcolor{softcol}{\hrule}
%
%
\cvsection{Continuing Education}\cvevent{2012 -}{Perennial Education}{Coursera}
{\cvpoint{Certificates: Epigenetics, 2014; Bioinformatics I/II, 2015}\\ % \\[2pt]
\cvpoint{Other: Machine Learning, 2012; Drugs in the Brain, 2014}}
%
\cvrule{-6pt}{0pt}
%
\cvevent{2015 -}{Perennial Education}{Self-Directed Study}
{\cvpoint{Watched at least 1,000 hours of YouTube lectures on mathematics, engineering and emerging fields.}\\ % \\[2pt]
\cvpoint{Used the zettelkasten method to synthesize insights from dozens of fields.
Wrote essays combining cybernetics, semiotics, artificial intelligence, agency and sociology}\\ % \\[2pt]
\cvpoint{Designed a graphics library for Swift to leverage functional composition for dynamic rendering
pipelines using features unique to Metal}}
%
\cvrule{-6pt}{0pt}
%
\cvevent{2021 -}{Automation}{Homelab}
{\cvpoint{Developed ansible playbooks SDN for VLANS, Firewalls and IP Migration}\\ % \\[2pt]
\cvpoint{Created a Guix System image for GPG and Smallstep CA}}
%
\cvrule{-6pt}{0pt}
%
\cvevent{2021 -}{Craftsmanship}{Workshop}
{\cvpoint{Modifying online designs to build a workbench and shelving}\\ % \\[2pt]
\cvpoint{Organized a workshop for woodworking, electronics, and making art supplies}}  % \\[\spread]
%\textcolor{softcol}{\hrule}
#+end_export

*  

#+begin_export latex
\cvbar
\setlength{\parindent}{3mm}
\vspace{\spread}\\
\small{\textbf{Hobbies}{ FOSS, Learning, Painting, Drawing, Kaggle, Electronics, Dance, Board Games, Writing}
\vspace{\spread}\\
\small{\textbf{Apps}{ Blender, Krita, FreeCAD, OpenCascade, Inventor, Matlab, IRC}
#+end_export

*  

#+begin_export latex
%	ARTIFICIAL FOOTER (fancy footer cannot exceed linewidth)

\null
\vspace*{\fill}
% this won't print
%\hspace{-0.25\linewidth}\colorbox{gray}{\makebox[1.5\linewidth][c]{\mystrut  \textcolor{bgcol}{www.jankuester.com $\cdot$ github.com/jankapunkt}}}
%\hspace{-0.25\linewidth}\colorbox{bgcol}{\makebox[1.5\linewidth][c]{\mystrut \textmd{\textcolor{white}{https://te.xel.io $\cdot$ github.com/dcunited001}}}}

#+end_export

* TODO add/explain                                                :noexport:

** Cloud

** Coursera
+ other certifications

** Homelab

*** Using packer to build images for cloud
*** Configuring users across network to run rootless apps on podman


* Latex :noexport:

** Rendering

+ From latex: use =C-c C-e= then =C-b l p=
  - this uses org to export the body only
  - this still works from =twocol.*.org=
  - this doesn't work with org-export's default latex handling: the body of the
    org file is already after the preamble
  - this works, but doesn't really use org-export
+ From org-export: use =C-c C-e= then =l p=
  - this requires moving most of the declarations inside of properties
    - e.g. packages inside =#+LATEX_HEADER_EXTRA=

*** Glitches

#+begin_example latex
\end{minipage}\hfill
% 
% a single space here will pop the \minipage onto a new page
% 
\begin{minipage}[t]{0.485\textwidth}
\vspace{\spread}
#+end_example

** Classes

Unfortunately, moving 

#+begin_example emacs-lisp
(add-to-list 'org-latex-classes
'("resume" "\\documentclass[10pt,letterpaper]{article}"
  ;; ("\\minipage{%s}" . "\\minipage*{%s}")
  
  ;; exports with num:nil
  ("\\begin{minipage}[t]{0.490\\textwidth}
\\vspace{\\spread}%s"
  "
\\end{minipage}
\\hfill"

  ;; exports with num:nil
  "\\begin{minipage}[t]{0.490\\textwidth}
\\vspace{\\spread}%s"
  "
\\end{minipage}
\\hfill"
  )
  ("\\cvsection{%s}" . "\\cvsection*{%s}")))
   ;;"\\minipage[t]{0.485\textwidth}%% %s}\n\vspace" . "\\minipage*[t]{0.485\textwidth}%% %s\n"
  ;; ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
  ;; ("\\paragraph{%s}" . "\\paragraph*{%s}")
  ;; ("\\subparagraph{%s}" . "\\subparagraph*{%s}")
#+end_example

#+begin_example emacs-lisp

'("resume" "\\documentclass[10pt,letterpaper]{article}"
(lambda (reduced-headline-level is-numbered))
  ;; must return a string containing %s
  )
#+end_example

*** From my emacs config

The only document class i've added is =beamer=

#+begin_src emacs-lisp :results value code :wrap example emacs-lisp
org-latex-classes
#+end_src

#+RESULTS:
#+begin_example emacs-lisp
(("beamer" "\\documentclass[presentation]{beamer}"
  ("\\section{%s}" . "\\section*{%s}")
  ("\\subsection{%s}" . "\\subsection*{%s}")
  ("\\subsubsection{%s}" . "\\subsubsection*{%s}"))
 ("article" "\\documentclass[11pt]{article}"
  ("\\section{%s}" . "\\section*{%s}")
  ("\\subsection{%s}" . "\\subsection*{%s}")
  ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
  ("\\paragraph{%s}" . "\\paragraph*{%s}")
  ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
 ("report" "\\documentclass[11pt]{report}"
  ("\\part{%s}" . "\\part*{%s}")
  ("\\chapter{%s}" . "\\chapter*{%s}")
  ("\\section{%s}" . "\\section*{%s}")
  ("\\subsection{%s}" . "\\subsection*{%s}")
  ("\\subsubsection{%s}" . "\\subsubsection*{%s}"))
 ("book" "\\documentclass[11pt]{book}"
  ("\\part{%s}" . "\\part*{%s}")
  ("\\chapter{%s}" . "\\chapter*{%s}")
  ("\\section{%s}" . "\\section*{%s}")
  ("\\subsection{%s}" . "\\subsection*{%s}")
  ("\\subsubsection{%s}" . "\\subsubsection*{%s}")))
#+end_example

** Packages

Search with =tlmgr info $pkg=. Some of these are not package names but files to
include. These seem to all be native to the Guix =texlive= distribution, even
tikz.

| Guix texlive | Need?     | =*.sty= |
|--------------+-----------+-------|
| multirow     | multicol  | y     |
| enumitem     | array     | y     |
| xifthen      | graphicx  | y     |
| wrapfig      | tikz      | y     |
| float        | color     | y     |
| moresize     | inputenc  | y     |
| geometry     | fontenc   | y     |
| fancyhdr     | showframe | y     |
| hyphenat     |           |       |

Fonts

| Guix texlive | Need      |
|--------------+-----------|
| comfortaa    | droidsans |
| cmbright     |           |
| raleway      |           |
| fetamont     |           |
| gillius      |           |
| iwona        |           |
| roboto       |           |

These are the notes from the original document's author.

|--------------------+----------+---------------------------------------------------------------------|
| package            | category | desc                                                                |
|--------------------+----------+---------------------------------------------------------------------|
| inputenc           | encoding | use ~utf8~ to build from any machine                                  |
| xifthen            | logic    | provides ~\isempty~ test                                              |
| multirow, multicol |          | for laying out tables                                               |
| array              |          | extended aligning of tabular cells                                  |
| enumitem           |          |                                                                     |
| wrapfig,float      |          | for floating figures                                                |
| moresize           |          | more font size definitions                                          |
| geometry           |          | define page styles using geometry                                   |
| fancyhdr           |          | use customized header                                               |
| hyphenat           |          | it's unclear how hyphenation affects keyword detection. turn it off |
| graphicx           |          | for header image                                                    |
| tikz               |          | for fancy charts                                                    |
| color              |          | color theme                                                         |
| fontenc            |          | font default                                                        |
| showframe          |          | debug page outer frames                                             |

*** Notes

**** Hyphenation

hyphenat adds too much space. a global ~\raggedright~ isn't working. it looks
terrible in sections where it does (throws off blocks). sooo... manually balance
text ~\raggedright~
