:PROPERTIES:
:ID:       5e1d0068-b3d4-4d49-6543-1972998f6e0d
:END:
#+TITLE:     David Conner Resume (twocol, letter)
# +SUBTITLE:  Subtitle
#+CATEGORY: resume
#+AUTHOR:    David Conner

# ## see notes at the end to export/generate

#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:nil c:nil d:(not "LOGBOOK") date:nil title:nil
#+OPTIONS: e:t email:nil f:t inline:t num:nil p:nil pri:nil stat:t
#+OPTIONS: tags:nil tasks:nil tex:t timestamp:nil todo:nil |:t
#+OPTIONS: toc:nil

#+SELECT_TAGS:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en

#+STARTUP: inlineimages

#+PROPERTY: header-args :eval never-export

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt,letterpaper]

#+LATEX_HEADER_EXTRA: \usepackage[utf8]{inputenc}
#+LATEX_HEADER_EXTRA: \usepackage{xifthen}

# #+LATEX_HEADER_EXTRA: %\usepackage[defaultsans]{droidsans}
# #+LATEX_HEADER_EXTRA: %\usepackage[default]{comfortaa}
# #+LATEX_HEADER_EXTRA: %\usepackage{cmbright}
# #+LATEX_HEADER_EXTRA: %\usepackage[default]{raleway}
# #+LATEX_HEADER_EXTRA: %\usepackage{fetamont}
# #+LATEX_HEADER_EXTRA: %\usepackage[default]{gillius}
# #+LATEX_HEADER_EXTRA: %\usepackage[light,math]{iwona}
# #+LATEX_HEADER_EXTRA: % \usepackage[thin]{roboto}

#+LATEX_HEADER_EXTRA: \usepackage[T1]{fontenc}
#+LATEX_HEADER_EXTRA: \renewcommand*\familydefault{\sfdefault}

#+LATEX_HEADER_EXTRA: \usepackage{moresize}
# #+LATEX_HEADER_EXTRA: \usepackage{showframe}

#+LATEX_HEADER_EXTRA: \usepackage[letterpaper]{geometry}
#+LATEX_HEADER_EXTRA: \geometry{top=1.75cm, bottom=-.6cm, left=1.5cm, right=1.5cm}

#+LATEX_HEADER_EXTRA: \usepackage{fancyhdr}
#+LATEX_HEADER_EXTRA: \pagestyle{fancy}
#+LATEX_HEADER_EXTRA: \setlength{\headheight}{-5pt}

#+LATEX_HEADER_EXTRA: \usepackage[none]{hyphenat}
#+LATEX_HEADER_EXTRA: \setlength{\parindent}{0mm}

#+LATEX_HEADER_EXTRA: \input{twocol.preamble.tex}

#+LATEX_HEADER_EXTRA: \usepackage{multicol}
#+LATEX_HEADER_EXTRA: \usepackage{multirow}
#+LATEX_HEADER_EXTRA: \usepackage{array}
#+LATEX_HEADER_EXTRA: \usepackage{enumitem}

#+LATEX_HEADER_EXTRA: \usepackage{graphicx}
#+LATEX_HEADER_EXTRA: \usepackage{wrapfig}
#+LATEX_HEADER_EXTRA: \usepackage{float}
#+LATEX_HEADER_EXTRA: \usepackage{tikz}
#+LATEX_HEADER_EXTRA: \usetikzlibrary{shapes, backgrounds,mindmap, trees}

#+LATEX_HEADER_EXTRA: \usepackage{color}
#+LATEX_HEADER_EXTRA:  \definecolor{bgcol}{RGB}{140,130,120}
#+LATEX_HEADER_EXTRA:  \definecolor{sectcol}{RGB}{30,25,18}
#+LATEX_HEADER_EXTRA:  \definecolor{softcol}{RGB}{225,225,225}
#+LATEX_HEADER_EXTRA:  \definecolor{txtcol}{RGB}{25,20,15}

#+begin_export latex
%use our custom fancy header definitions
\pagestyle{fancy}

\begin{minipage}[t]{0.485\textwidth}

\vspace{\spread}

%	TITLE HEADLINE
\hspace{-0.25\linewidth}\colorbox{bgcol}{\makebox[1.25\linewidth][c]{\textcolor{bgcol}{\rule[-1mm]{1mm}{1.0cm}} \HUGE{\textcolor{txtcol}{\textsc{David Conner}}}}}
%---------------------------------------------------------------------------------------
%	HEADER IMAGE
% \hspace{-0.25\linewidth}\includegraphics[width=1.2725\linewidth]{myphoto.jpg} %use full size
%---------------------------------------------------------------------------------------
%	QR CODE (optional)
%\vspace{-100pt}
%\hspace{0.59\linewidth}
%\includegraphics[width=88pt]{qrcode}
%\normalsize
% \pareindent here is a hack
\setlength{\parindent}{5mm}

\vspace{-0.1cm}\\
\small{I'm an engineer with experience in networking, databases, containers,
and web applications. I'm looking to transition into a role that
leverages software to solve domain-specific problems, whether as an
application programmer or devops. I have experience integrating
disparate systems with minimal service interruptions and no loss of data.}

\small{I'm fast learner with a thirst for staying ahead in the technology world.
When practical, I prefer the source code as documentation for most tools.}\\[-2pt]
\textcolor{softcol}{\hrule}
\setlength{\parindent}{0mm}
\vspace{\spread}\\
\metasection{Hobbies:}{FOSS, Learning, Painting, Drawing, Kaggle, Electronics, Dance, Board Games, Writing}
\metasection{Apps:}{Blender, Krita, FreeCAD, OpenCascade, Inventor, Matlab, IRC}
\end{minipage}
\hfill
\begin{minipage}[t]{0.485\textwidth}
#+end_export


#+begin_export latex
%---------------------------------------------------------------------------------------
%	SUMMARY (optional)
\vspace{\spread}

\cvsection{Summary}
\vspace{1pt}\\
\metasection{Lang:}{Bash, Ruby, Python, JS, TS, Clojure, Emacs Lisp, Scheme, Julia, Scala}
\metasection{Tools:}{Emacs, Org Mode, Direnv, Ansible, KDE, i3, VTY, GNU Screen, pyenv, poetry}
\metasection{Data:}{Reporting, ETL, Postgres, MSSQL, SQLite3, Parquet, jq}
\textcolor{softcol}{\hrule}
\vspace{\spread}\\
\metasection{Security:}{GPG, PIV, CA, Firewalls, Crypto}
\metasection{Linux:}{RPM, Guix, Docker, Podman, LVM}
\metasection{Cloud:}{Terraform, k8s, GCP}
\metasection{Homelab:}{SDN, VLAN, Proxmox, SR-IOV, UPS/Power}
\textcolor{softcol}{\hrule}
\vspace{\spread}\\
\setlength{\parindent}{5mm}
\small{\textbf{Interests:} Math, 3D Graphics, 3D Design, Philosophy, Futurism,
Writing, Linguistics, Semiotics, Bioinformatics, Epigenetics, Colorimetry,
Logistics, Materials}
\end{minipage}

\begin{minipage}[t]{0.485\textwidth}

\vspace{\spread}
#+end_export



#+begin_export latex
%---------------------------------------------------------------------------------------
%	EDUCATION SECTION
\cvsection{Formal Education}\cvevent{2006 - 2008; 2021 -}
{Mechatronics S.E.T.}
{Virginia Western Community College}
{\cvpoint{Obtained a Cisco CCNA certification (2008)}\\ % \\[2pt] % more condensed
\cvpoint{Studied design, manufacture, electronics, CNC and safety}\\
\cvpoint{Planning one course per semester to utilize the Fab Lab}}
%
\cvrule{-8pt}{0pt}
%
\cvevent{2004 - 2006; 2008}
{Computer Science}
{Virginia Tech}
{\cvpoint{Studied Computer Science. Dropped out to compete in jamskating at a national level}}\\
%\textcolor{softcol}{\hrule}
\cvsection{Continuing Education}\cvevent{2012 -}
{Perennial Education}
{Coursera}
{\cvpoint{Certificates: Epigenetics, 2014; Bioinformatics I/II, 2015}\\ % \\[2pt]
\cvpoint{Other: Machine Learning, 2012; Drugs in the Brain, 2014}}
%
\cvrule{-8pt}{0pt}
%
\cvevent{2015 -}
{Perennial Education}
{Self-Directed Study}
{\cvpoint{Watched at least 1,000 hours of YouTube lectures on mathematics, engineering and emerging fields.}\\ % \\[2pt]
\cvpoint{Used the zettelkasten method to synthesize insights from dozens of fields.
Wrote essays combining cybernetics, semiotics, artificial intelligence, agency and sociology}\\ % \\[2pt]
\cvpoint{Designed a graphics library for Swift to leverage functional composition for dynamic rendering
pipelines using features unique to Metal}}
%
\cvrule{-8pt}{0pt}
%
\cvevent{2021 -}
{Automation}
{Homelab}
{\cvpoint{Developed ansible playbooks SDN for VLANS, Firewalls and IP Migration}\\ % \\[2pt]
\cvpoint{Created a Guix System image for GPG and Smallstep CA}}
%
\cvrule{-8pt}{0pt}
%
\cvevent{2021 -}
{Learning Craftsmanship For Independence}
{Workshop}
{\cvpoint{Modifying online designs to build a workbench and shelving}\\ % \\[2pt]
\cvpoint{Organized a workshop for woodworking, electronics, and making art supplies}}  % \\[\spread]

%\textcolor{softcol}{\hrule}

\end{minipage}
\hfill
\begin{minipage}[t]{0.485\textwidth}

\vspace{\spread}
#+end_export



#+begin_export latex
%---------------------------------------------------------------------------------------
%	EXPERIENCE

\cvsection{Experience}\cvevent{2022 - 2023}
{Engineering Student Aide}
{Virginia Western Community College}
{\cvpoint{Maintained Ender-3 Pro and Raise3D printers. Synced Ender-3 configurations for PLA plastics}\\ % \\[2pt]
\cvpoint{Created an Autodesk Fusion CNC config for a Velocity CNC}\\ % \\[2pt]
\cvpoint{Collected notes on almost all equipment including support links and digital copies of manuals}} \\[\spread]
%
\cvrule{-8pt}{0pt}
%
\cvevent{2018}
{Cloud Engineer}
{RAKE Digital}
{\cvpoint{Used MS SQL table metadata to quickly learn the accounting database schema for Millennium and ReadyPay}\\ % \\[2pt]
\cvpoint{Designed an application stack with LoopbackJS and Angular 6 to automate payroll tasks in Azure}} % \\[\spread]
%
\cvrule{-8pt}{0pt}
%
\cvevent{2015 - 2017}
{Founder}
{Voxxel (Startup)}
{\cvpoint{Voxxel enabled fans to score their impersionations of movie quotes and accents}\\ % \\[2pt]
\cvpoint{Built a Rails API to back prototypes in iOS, Android and AngularJS. Each client processed and visualized the FFT}} % \\[\spread]
%
\cvrule{-8pt}{0pt}
%
\cvevent{2011 - 2015}
{Founder}
{Oscil8 (Startup)}
{\cvpoint{Oscil8 was designed to be the “Github for Music Producers”}\\ % \\[2pt]
\cvpoint{Developed a business model and strategic vision}}
%
\cvrule{-8pt}{0pt}
%
\cvevent{2014}
{Software Developer}
{Left + Right (Contract)}
{\cvpoint{Developed a web service to extend a Ruby on Rails application with reporting on SQL Views}\\ % \\[2pt]
\cvpoint{Cached report results in MongoDB to enable a dashboard}}
%
\cvrule{-8pt}{0pt}
%
\cvevent{2013}
{Software Engineer}
{Jumpcloud}
{\cvpoint{Full stack development using a NodeJS API and MongoDB}\\ % \\[2pt]
\cvpoint{Integration tests using Mocha, Selenium and Soda}} % \\[\spread]

\end{minipage}

#+end_export


#+begin_export latex
%	ARTIFICIAL FOOTER (fancy footer cannot exceed linewidth)

\null
\vspace*{\fill}
% this won't print
%\hspace{-0.25\linewidth}\colorbox{gray}{\makebox[1.5\linewidth][c]{\mystrut  \textcolor{bgcol}{www.jankuester.com $\cdot$ github.com/jankapunkt}}}
%\hspace{-0.25\linewidth}\colorbox{bgcol}{\makebox[1.5\linewidth][c]{\mystrut \textmd{\textcolor{white}{https://te.xel.io $\cdot$ github.com/dcunited001}}}}

#+end_export

* TODO add/explain                                                :noexport:

** Cloud

** Coursera
+ other certifications

** Homelab

*** Using packer to build images for cloud
*** Configuring users across network to run rootless apps on podman


* Latex :noexport:

** Rendering

+ From latex: use =C-c C-e= then =C-b l p=
  - this uses org to export the body only
  - this still works from =twocol.*.org=
  - this doesn't work with org-export's default latex handling: the body of the
    org file is already after the preamble
  - this works, but doesn't really use org-export
+ From org-export: use =C-c C-e= then =l p=
  - this requires moving most of the declarations inside of properties
    - e.g. packages inside =#+LATEX_HEADER_EXTRA=


** Packages

Search with =tlmgr info $pkg=. Some of these are not package names but files to
include

| Guix texlive | Need?     | =*.sty= |
|--------------+-----------+-------|
| multirow     | multicol  | y     |
| enumitem     | array     | y     |
| xifthen      | graphicx  | y     |
| wrapfig      | tikz      | y     |
| float        | color     | y     |
| moresize     | inputenc  | y     |
| geometry     | fontenc   | y     |
| fancyhdr     | showframe | y     |
| hyphenat     |           |       |

Fonts

| Guix texlive | Need      |
|--------------+-----------|
| comfortaa    | droidsans |
| cmbright     |           |
| raleway      |           |
| fetamont     |           |
| gillius      |           |
| iwona        |           |
| roboto       |           |

These are the notes from the original document's author.

|--------------------+----------+---------------------------------------------------------------------|
| package            | category | desc                                                                |
|--------------------+----------+---------------------------------------------------------------------|
| inputenc           | encoding | use ~utf8~ to build from any machine                                  |
| xifthen            | logic    | provides ~\isempty~ test                                              |
| multirow, multicol |          | for laying out tables                                               |
| array              |          | extended aligning of tabular cells                                  |
| enumitem           |          |                                                                     |
| wrapfig,float      |          | for floating figures                                                |
| moresize           |          | more font size definitions                                          |
| geometry           |          | define page styles using geometry                                   |
| fancyhdr           |          | use customized header                                               |
| hyphenat           |          | it's unclear how hyphenation affects keyword detection. turn it off |
| graphicx           |          | for header image                                                    |
| tikz               |          | for fancy charts                                                    |
| color              |          | color theme                                                         |
| fontenc            |          | font default                                                        |
| showframe          |          | debug page outer frames                                             |

*** Notes

**** Hyphenation

hyphenat adds too much space. a global ~\raggedright~ isn't working. it looks
terrible in sections where it does (throws off blocks). sooo... manually balance
text ~\raggedright~
