:PROPERTIES:
:ID:       5f261657-70aa-4682-bd82-cd7e9321857e
:END:
#+TITLE:     Ellipsis
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

This is a guix parent module that helps with code reuse.

* Guix

** Writing Packages

+ OpenSSL has an example of a Spliced G-Expression

+ nothing happens if there's no (arguments...)?

*** Questions
+ how to prevent guile from loading WIP code
  - these packages should definitely not be in dotfiles..
+ arch & nix use =go build= here, but how are go-deps fetched?
+ =guix import go= can consume package metadata and produce guix packages, perhaps recursively
  - [[github:ryanprior/emacs-guix-packaging][ryanprior/emacs-guix-packaging]] can help with this

** Writing Services

* Utils

* Services

* Home Services

* Packages

** Performance

+ cpupower-gui ([[https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cpupower-gui][AUR]])
  - [[https://wiki.archlinux.org/title/CPU_frequency_scaling#cpupower-gui][CPU Powerscaling]]
+ throttled ([[https://github.com/erpalma/throttled][github]])
  - this may provide fixes for CPU throttling/scaling issues on my laptop, which seems not properly read the =tctl= sensor (it is set +20° from tdie, which i can't find)

** Misc

+ libsixel
+ emacs-x509

* Notes

**** TODO fully disambiguate compose/extend/extension
... silly french /agir/

** Performance

+ amd_pstate ([[https://www.kernel.org/doc/html/latest/admin-guide/pm/amd-pstate.html][linux docs]]) module is builtin to my kernel
  - but apparently this is very new...
  - cpu must be Zen 2 or higher (laptops? ... i donno?)
  - [[https://www.reddit.com/r/linuxhardware/comments/vww97x/owner_report_hp_victus_16_laptop_with_amd_rx5500m/][enabling amd_pstate driver on a laptop]]
  - and an article from [[https://www.phoronix.com/news/AMD-P-State-How-To][phoronix]]

inspect current CPU state:

+ lscpu
+ =sudo cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq=
+ =sudo cpupower frequency-info=

inspect current TLP state:

+ =sudo tlp-stat=


** Root Profile

This profile is also created via =/etc/skel= which is defined in =./gnu/system/shadow.scm=

=/etc/profile= should be extended with:

  - special-file-service
  - extra-special-file-service

**** TODO it's not quite clear how this would be extended
+ ideally, i could just append to the files defined by the =/etc/skel= service

** Boot Params

Configure with =sysctl-service-type= and extend/override =%default-sysctl-settings=.

** ThermalD

Fix thermald on kharis

#+begin_quote
Jul 24 19:50:37 localhost shepherd[1]: Service thermald has been started.
Jul 24 19:50:37 localhost shepherd[1]: [thermald] [1658706637][MSG]Config file /gnu/store/n3ag66c5bgcfwffrzlz0qmib1ildv9pa-thermald-2.4.7/etc/thermald/thermal-conf.xml does not exist
Jul 24 19:50:37 localhost shepherd[1]: [thermald] [1658706637][MSG]Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check
Jul 24 19:50:37 localhost shepherd[1]: [thermald] [1658706637][MSG]THD engine start failed
Jul 24 19:50:37 localhost shepherd[1]: Service thermald (PID 27678) exited with 2.
Jul 24 19:50:37 localhost shepherd[1]: Service thermald has been disabled.
Jul 24 19:50:37 localhost shepherd[1]:   (Respawning too fast.)
#+end_quote

* Systems

** USB GPG Image

This is mostly a reimplementation of the Nix image from [[github:drduh/YubiKey-Guide][drduh/YubiKey-Guide]] in Guix. The image is intended to be used for:

+ GPG key generation
+ SSL keygen
+ [[https://developers.yubico.com/PIV/Guides/Certificate_authority.html][Certificate Authority with a Yubikey]]

**** Resources

+ [[https://gnupg.org/aegypten2][gnupg.org/aegypten2]] has an architectural overview of how GnuPG interacts with system services (it's a bit old)

**** Multiboot USB

+ [[https://guix.gnu.org/manual/en/html_node/Initial-RAM-Disk.html][Guix: Initial RAM Disk]] documents the boot arguments

*** Grub Config

#+begin_example conf
for isofile in $isopath/guix-gpg-*.iso; do
  if [ -e "$isofile" ]; then
    regexp --set=isoname "$isopath/(.*)" "$isofile"
    submenu "$isoname ->" "$isofile" {
      iso_path="$2"
      loopback loop "$iso_path"
      menuentry "Start Guix GPG USB" {
        search --fs-uuid --set "1970-01-01-09-41-59-29" root
        # bootoptions="root=31393730-3031-3031-3039-343135393239"
        bootoptions="root=$root gnu.system=/gnu/store/wzxv66d1iviqxax88vkfnxfc9zppxim7-system gnu.load=/gnu/store/wzxv66d1iviqxax88vkfnxfc9zppxim7-system/boot modprobe.blacklist=radeon"
        linux (loop)/gnu/store/lq7rpl835igf983766fm8xbb6knvdrs8-linux-libre-6.13.7/bzImage $bootoptions
        initrd (loop)/gnu/store/yvf65kvmi5xcw1ydw033nca69zyr05f2-raw-initrd/initrd.cpio.gz
      }
    }
  fi
done

#+end_example

*** Tasks

**** TODO resolve need to use nonguix when generating USB images for laptops requiring non-free firmware

*** Notes

**** Yubico

***** Disk Utils

****** BTRFS duplication

Including BTRFS could help when writing to SD cards of questionable quality
when they are intended as long-term backups.

This will ensure that one copy of the disk's metadata and block-level data is
duplicated within the partition. It results in <50% of the storage space.

#+begin_src sh
mkfs.btrfs -d dup -m dup --label "backup" /dev/sdXn
#+end_src

******* TODO ensure =noatime= is configured as udisks2 default

in =/etc/udisks2/mount_options.conf=:

#+begin_src conf
[defaults]
btrfs_defaults=noatime,space_cache=v2, ... etc
#+end_src

^^^ review the above

One problem: =noatime= must be configured on each mount. Also, other metadata may be updated when the system is mounted, unknown to user. this is a shortcoming of simply duplicating LUKS volumes.

****** Duplicate encrypted volumes

However, storing these partitions within an encrypted volume would erase the
benefits of BTRFS duplication. You can simply duplicate the encrypted volume with =dd=.

Use =cryptsetup= to open/work on the volume is opened. then

***** PIV

These packages should not be necessary for my use case.

***** PAM

Modules for yubico PAM. Irrelevant for GPG key creation

#+begin_src scheme :eval no
#:use-module (gnu packages authentication)
;; gnu/packages/openpgp.scm
;; gnu/packages/gnu-pw-mgr.scm
#+end_src

***** Keepass

Modules for keepass w/ yubico support:

#+begin_src scheme :eval no
#:use-module (gnu packages password-utils)
#+end_src

**** Refactoring GnuPG services into modules

#+begin_src scheme :eval no
;; TODO: this will require building an image with firmware
;; - e.g. on the HP laptop
;; NOTE: PIV is not necessary
;;   TODO: udev.packages support for yubikey-personalization

;; =========================
;; (define-configuration usb-gpg-agent-configuration)

;; TODO: implement as service (later ... just use screen now)
;;
;; TODO: services: enable gpg-agent
;; TODO: add config option for GNUPGHOME
;; TODO: add config option for starting gnupg-connect-agent /bye

(define usb-gpg-agent-shepherd-service
  (shepherd-service
   (documentation "Run a GPG agent")
   (provision '(usb-gpg-agent gpg-agent))
   (requirement '(user-processes syslogd loopback))

   (start #~ (make-forkexec-constructor ))
   ()))

;; if more entropy is needed
;; "echo 'SCD RANDOM 512 | gpg-connect-agent | tee /dev/random | "

(define usb-gpg-agent-service-type
  (service-type
   (name 'usb-gpg-agent-service-type)
   (extensions (list
                (service-extensions profile-service-type '(gnupg))))
   (description )))
#+end_src

**** Refactoring xsecurelock-service

#+begin_src scheme :eval no
;; =========================
;; TODO this needs to be tested (in a separate iso image with xorg)
;; (define xsecurelock-service-type
;;   (service-type
;;    (name 'xsecurelock)
;;    (extensions
;;     (list (service-extension pam-root-service-type
;;                              screen-locker-pam-services)
;;           (service-extension setuid-program-service-type
;;                              ;; (lambda (program)  ... )
;;                              (setuid-program
;;                               ((lambda (program)
;;                                  (pretty-print  (string-append  #$xsecure-lock "/libexec/xsecurelock/authproto_pam"))
;;                                  program
;;                                  )
;;                                (program (string-append  #$xsecure-lock "/libexec/xsecurelock/authproto_pam"))))
;;                              )))
;;    (description "Setup xsecurelock with authproto_pam to run xscreensaver and configure it as a PAM service")))
;; =========================
#+end_src

* Systems

* Wayland

** Keyboard

+ [[https://github.com/kmonad/kmonad][kmonad/kmonad]]

* Base System

** Groups

Base Groups for guix. Found in =./gnu/system/shadow.scm=

|---------+--------------------------|
| Group   | Description              |
|---------+--------------------------|
| root    |                          |
| wheel   | root-like users          |
| users   | normal users             |
| nogroup | for daemons              |
| tty     | %tty-gid                 |
| dialout | serial devices           |
| kmem    |                          |
| input   | input devices, from udev |
| video   |                          |
| audio   |                          |
| netdev  | used in avahi-dbus.conf  |
| lp      |                          |
| disk    |                          |
| floppy  |                          |
| cdrom   |                          |
| tape    |                          |
| kvm     |                          |
|---------+--------------------------|

** Packages

=%base-packages=

| bash@5.1.8                  | gnu/packages/bash.scm               |
| bash-completion@2.8         | gnu/packages/bash.scm               |
| bzip2@1.0.8                 | gnu/packages/compression.scm        |
| coreutils@8.32              | gnu/packages/base.scm               |
| diffutils@3.8               | gnu/packages/base.scm               |
| e2fsprogs@1.46.4            | gnu/packages/linux.scm              |
| eudev@3.2.11                | gnu/packages/linux.scm              |
| findutils@4.8.0             | gnu/packages/base.scm               |
| gawk@5.1.0                  | gnu/packages/gawk.scm               |
| grep@3.6                    | gnu/packages/base.scm               |
| guile@3.0.8                 | gnu/packages/guile.scm              |
| guile-colorized@0.1         | gnu/packages/guile-xyz.scm          |
| guile-readline@3.0.7        | gnu/packages/guile.scm              |
| guix-icons@0.1              | gnu/packages/package-management.scm |
| gzip@1.10                   | gnu/packages/compression.scm        |
| inetutils@2.0               | gnu/packages/admin.scm              |
| info-reader@6.7             | gnu/packages/texinfo.scm            |
| iproute2@5.15.0             | gnu/packages/linux.scm              |
| isc-dhcp@4.4.3-P1           | gnu/packages/admin.scm              |
| iw@5.19                     | gnu/packages/linux.scm              |
| kbd@2.5.1                   | gnu/packages/linux.scm              |
| kmod@29                     | gnu/packages/linux.scm              |
| less@590                    | gnu/packages/less.scm               |
| lzip@1.22                   | gnu/packages/compression.scm        |
| man-db@2.10.2               | gnu/packages/man.scm                |
| mg@20221112                 | gnu/packages/text-editors.scm       |
| nano@7.1                    | gnu/packages/nano.scm               |
| nvi@1.81.6                  | gnu/packages/nvi.scm                |
| patch@2.7.6                 | gnu/packages/base.scm               |
| pciutils@3.7.0              | gnu/packages/pciutils.scm           |
| procps@3.3.16               | gnu/packages/linux.scm              |
| psmisc@23.5                 | gnu/packages/linux.scm              |
| sed@4.8                     | gnu/packages/base.scm               |
| shadow@4.9                  | gnu/packages/admin.scm              |
| sudo@1.9.12p2               | gnu/packages/admin.scm              |
| tar@1.34                    | gnu/packages/base.scm               |
| usbutils@014                | gnu/packages/linux.scm              |
| util-linux-with-udev@2.37.2 | gnu/packages/linux.scm              |
| wget@1.21.3                 | gnu/packages/wget.scm               |
| which@2.21                  | gnu/packages/base.scm               |
| wireless-tools@30.pre9      | gnu/packages/linux.scm              |
| xz@5.2.5                    | gnu/packages/compression.scm        |

* Misc

** Locking

*** On Removing Yubikey


** PAM Limits Entries

Entries require: domain, type, item, value

Items:

| core     | data      | fsize        |
| memlock  | nofile    | rss          |
| stack    | cpu       | nproc        |
| as       | maxlogins | maxsyslogins |
| priority | locks     | sigpending   |
| msgqueue | nice      | rtprio       |

From =gnu/services/pam.scm=

#+begin_src scheme

(define-record-type* <pam-service> pam-service
  make-pam-service
  pam-service?
  (name       pam-service-name)                   ; string

  ;; The four "management groups".
  (account    pam-service-account                 ; list of <pam-entry>
              (default '()))
  (auth       pam-service-auth
              (default '()))
  (password   pam-service-password
              (default '()))
  (session    pam-service-session
              (default '())))

(define-record-type* <pam-entry> pam-entry
  make-pam-entry
  pam-entry?
  (control    pam-entry-control)         ; string
  (module     pam-entry-module)          ; file name
  (arguments  pam-entry-arguments        ; list of string-valued g-expressions
              (default '())))

(define-record-type <pam-limits-entry>
  (make-pam-limits-entry domain type item value)
  pam-limits-entry?
  (domain     pam-limits-entry-domain)   ; string
  (type       pam-limits-entry-type)     ; symbol
  (item       pam-limits-entry-item)     ; symbol
  (value      pam-limits-entry-value))

(define (pam-limits-entry domain type item value)
  "Construct a pam-limits-entry ensuring that the provided values are valid."
  (define (valid? value)
    (case item
      ((priority) (number? value))
      ((nice)     (and (number? value)
                       (>= value -20)
                       (<= value 19)))
      (else       (or (and (number? value)
                           (>= value -1))
                      (member value '(unlimited infinity))))))
  (define items
    (list 'core      'data       'fsize
          'memlock   'nofile     'rss
          'stack     'cpu        'nproc
          'as        'maxlogins  'maxsyslogins
          'priority  'locks      'sigpending
          'msgqueue  'nice       'rtprio))
  (when (not (member type '(hard soft both)))
    (error "invalid limit type" type))
  (when (not (member item items))
    (error "invalid limit item" item))
  (when (not (valid? value))
    (error "invalid limit value" value))
  (make-pam-limits-entry domain type item value))
#+end_src

