@startuml
    !pragma layout smetana
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods
    edu.wpi.first.cameraserver --> edu.wpi.first.networktables
    edu.wpi.first.epilogue.logging --> edu.wpi.first.networktables
    edu.wpi.first.networktables --> edu.wpi.first.util.struct
    edu.wpi.first.networktables --> edu.wpi.first.util.protobuf
    edu.wpi.first.networktables --> edu.wpi.first.util.function
    edu.wpi.first.networktables --> edu.wpi.first.util.concurrent
    edu.wpi.first.networktables --> edu.wpi.first.util.datalog
    edu.wpi.first.networktables --> edu.wpi.first.util.sendable
    edu.wpi.first.wpilibj2.command.button --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.event --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.shuffleboard --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.livewindow --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.smartdashboard --> edu.wpi.first.networktables
    class "edu.wpi.first.networktables" [[edu/wpi/first/networktables/package-summary.html]] {}
@enduml
