@startuml
    !pragma layout smetana
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods
    edu.wpi.first.vision --> edu.wpi.first.cscore
    edu.wpi.first.vision --> org.opencv.core
    class "edu.wpi.first.vision" [[edu/wpi/first/vision/package-summary.html]] {}
@enduml
