@startuml
    !pragma layout smetana
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods
    edu.wpi.first.cameraserver --> edu.wpi.first.networktables
    edu.wpi.first.cameraserver --> edu.wpi.first.cscore
    edu.wpi.first.cameraserver --> edu.wpi.first.util
    class "edu.wpi.first.cameraserver" [[edu/wpi/first/cameraserver/package-summary.html]] {}
@enduml
