@startuml
    !pragma layout smetana
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods
    edu.wpi.first.apriltag --> edu.wpi.first.math.geometry
    edu.wpi.first.apriltag --> edu.wpi.first.util
    edu.wpi.first.apriltag --> org.opencv.core
    edu.wpi.first.apriltag --> edu.wpi.first.math
    edu.wpi.first.apriltag.jni --> edu.wpi.first.apriltag
    edu.wpi.first.apriltag.jni --> edu.wpi.first.math.geometry
    edu.wpi.first.apriltag.jni --> edu.wpi.first.util
    class "edu.wpi.first.apriltag" [[edu/wpi/first/apriltag/package-summary.html]] { }
    class "edu.wpi.first.apriltag.jni" [[edu/wpi/first/apriltag/jni/package-summary.html]] {}
@enduml
