@startuml
    !pragma layout smetana
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods
    edu.wpi.first.epilogue --> edu.wpi.first.units.measure
    edu.wpi.first.epilogue.logging --> edu.wpi.first.units
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj2.command.sysid --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj.motorcontrol --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj.sysid --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.units.measure
    edu.wpi.first.math.trajectory --> edu.wpi.first.units.measure
    edu.wpi.first.math.kinematics --> edu.wpi.first.units.measure
    edu.wpi.first.math.geometry --> edu.wpi.first.units.measure
    edu.wpi.first.units --> edu.wpi.first.units.measure
    edu.wpi.first.units --> edu.wpi.first.units.collections
    edu.wpi.first.units.mutable --> edu.wpi.first.units
    edu.wpi.first.units.mutable --> edu.wpi.first.units.measure
    edu.wpi.first.units.measure --> edu.wpi.first.units
    edu.wpi.first.units.measure --> edu.wpi.first.units.mutable
    class "edu.wpi.first.units.measure" [[edu/wpi/first/units/measure/package-summary.html]] {}
    class "edu.wpi.first.units" [[edu/wpi/first/units/package-summary.html]] {}
    class "edu.wpi.first.units.collections" [[edu/wpi/first/units/collections/package-summary.html]] {}
    class "edu.wpi.first.units.mutable" [[edu/wpi/first/units/mutable/package-summary.html]] {}
@enduml
