@startuml
    !pragma layout smetana
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods
    edu.wpi.first.vision --> edu.wpi.first.cscore
    edu.wpi.first.cameraserver --> edu.wpi.first.cscore
    edu.wpi.first.cscore --> edu.wpi.first.util
    edu.wpi.first.cscore --> org.opencv.core
    edu.wpi.first.cscore.raw --> edu.wpi.first.cscore
    edu.wpi.first.cscore.raw --> edu.wpi.first.util
    edu.wpi.first.wpilibj.shuffleboard --> edu.wpi.first.cscore
    class "edu.wpi.first.cscore" [[edu/wpi/first/cscore/package-summary.html]] {}
    class "edu.wpi.first.cscore.raw" [[edu/wpi/first/cscore/raw/package-summary.html]] {}
@enduml
