@startuml
    !pragma layout smetana
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods
    edu.wpi.first.apriltag --> edu.wpi.first.math.geometry
    edu.wpi.first.apriltag --> edu.wpi.first.math
    edu.wpi.first.apriltag.jni --> edu.wpi.first.math.geometry
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.math.trajectory
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.math.controller
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.math.kinematics
    edu.wpi.first.wpilibj2.command.button --> edu.wpi.first.math.filter
    edu.wpi.first.wpilibj --> edu.wpi.first.math.geometry
    edu.wpi.first.wpilibj.event --> edu.wpi.first.math.filter
    edu.wpi.first.wpilibj.drive --> edu.wpi.first.math.geometry
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.math.system.plant
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.math.system
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.math
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.math.geometry
    edu.wpi.first.wpilibj.smartdashboard --> edu.wpi.first.math.geometry
    edu.wpi.first.wpilibj.smartdashboard --> edu.wpi.first.math.trajectory
    edu.wpi.first.math.filter --> edu.wpi.first.util
    edu.wpi.first.math --> edu.wpi.first.math.geometry
    edu.wpi.first.math --> edu.wpi.first.util.protobuf
    edu.wpi.first.math --> edu.wpi.first.util.struct
    edu.wpi.first.math --> org.ejml.simple
    edu.wpi.first.math --> edu.wpi.first.math.proto
    edu.wpi.first.math --> edu.wpi.first.math.struct
    edu.wpi.first.math.proto --> us.hebi.quickbuf
    edu.wpi.first.math.proto --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.proto --> edu.wpi.first.math
    edu.wpi.first.math.spline --> org.ejml.simple
    edu.wpi.first.math.spline --> edu.wpi.first.math.geometry
    edu.wpi.first.math.spline --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.spline --> edu.wpi.first.util.struct
    edu.wpi.first.math.spline --> edu.wpi.first.math.spline.proto
    edu.wpi.first.math.spline --> edu.wpi.first.math.spline.struct
    edu.wpi.first.math.spline.proto --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.spline.proto --> us.hebi.quickbuf
    edu.wpi.first.math.spline.proto --> edu.wpi.first.math.proto
    edu.wpi.first.math.spline.proto --> edu.wpi.first.math.spline
    edu.wpi.first.math.spline.struct --> edu.wpi.first.util.struct
    edu.wpi.first.math.spline.struct --> edu.wpi.first.math.spline
    edu.wpi.first.math.system --> edu.wpi.first.math
    edu.wpi.first.math.system --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.system --> edu.wpi.first.util.struct
    edu.wpi.first.math.system --> edu.wpi.first.math.system.proto
    edu.wpi.first.math.system --> edu.wpi.first.math.system.struct
    edu.wpi.first.math.system --> edu.wpi.first.math.controller
    edu.wpi.first.math.system --> edu.wpi.first.math.estimator
    edu.wpi.first.math.system.proto --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.system.proto --> edu.wpi.first.math
    edu.wpi.first.math.system.proto --> us.hebi.quickbuf
    edu.wpi.first.math.system.proto --> edu.wpi.first.math.proto
    edu.wpi.first.math.system.proto --> edu.wpi.first.math.system
    edu.wpi.first.math.system.plant.proto --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.system.plant.proto --> us.hebi.quickbuf
    edu.wpi.first.math.system.plant.proto --> edu.wpi.first.math.proto
    edu.wpi.first.math.system.plant.proto --> edu.wpi.first.math.system.plant
    edu.wpi.first.math.system.plant --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.system.plant --> edu.wpi.first.util.struct
    edu.wpi.first.math.system.plant --> edu.wpi.first.math.system.plant.proto
    edu.wpi.first.math.system.plant --> edu.wpi.first.math.system.plant.struct
    edu.wpi.first.math.system.plant --> edu.wpi.first.math.system
    edu.wpi.first.math.system.plant.struct --> edu.wpi.first.util.struct
    edu.wpi.first.math.system.plant.struct --> edu.wpi.first.math.system.plant
    edu.wpi.first.math.system.struct --> edu.wpi.first.util.struct
    edu.wpi.first.math.system.struct --> edu.wpi.first.math.struct
    edu.wpi.first.math.system.struct --> edu.wpi.first.math
    edu.wpi.first.math.system.struct --> edu.wpi.first.math.system
    edu.wpi.first.math.path --> edu.wpi.first.math.geometry
    edu.wpi.first.math.path --> edu.wpi.first.math
    edu.wpi.first.math.trajectory.proto --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.trajectory.proto --> us.hebi.quickbuf
    edu.wpi.first.math.trajectory.proto --> edu.wpi.first.math.proto
    edu.wpi.first.math.trajectory.proto --> edu.wpi.first.math.trajectory
    edu.wpi.first.math.trajectory --> edu.wpi.first.math.geometry
    edu.wpi.first.math.trajectory --> edu.wpi.first.math.spline
    edu.wpi.first.math.trajectory --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.trajectory --> edu.wpi.first.math.trajectory.proto
    edu.wpi.first.math.trajectory --> edu.wpi.first.units.measure
    edu.wpi.first.math.trajectory --> edu.wpi.first.math.trajectory.constraint
    edu.wpi.first.math.trajectory --> edu.wpi.first.math.kinematics
    edu.wpi.first.math.trajectory.constraint --> edu.wpi.first.math.geometry
    edu.wpi.first.math.trajectory.constraint --> edu.wpi.first.math.kinematics
    edu.wpi.first.math.trajectory.constraint --> edu.wpi.first.math.controller
    edu.wpi.first.math.kinematics --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.kinematics --> edu.wpi.first.util.struct
    edu.wpi.first.math.kinematics --> edu.wpi.first.math.kinematics.proto
    edu.wpi.first.math.kinematics --> edu.wpi.first.math.kinematics.struct
    edu.wpi.first.math.kinematics --> edu.wpi.first.units.measure
    edu.wpi.first.math.kinematics --> edu.wpi.first.math.geometry
    edu.wpi.first.math.kinematics --> edu.wpi.first.math.interpolation
    edu.wpi.first.math.kinematics --> org.ejml.simple
    edu.wpi.first.math.kinematics.proto --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.kinematics.proto --> us.hebi.quickbuf
    edu.wpi.first.math.kinematics.proto --> edu.wpi.first.math.proto
    edu.wpi.first.math.kinematics.proto --> edu.wpi.first.math.kinematics
    edu.wpi.first.math.kinematics.struct --> edu.wpi.first.util.struct
    edu.wpi.first.math.kinematics.struct --> edu.wpi.first.math.kinematics
    edu.wpi.first.math.struct --> edu.wpi.first.util.struct
    edu.wpi.first.math.struct --> edu.wpi.first.math
    edu.wpi.first.math.controller.proto --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.controller.proto --> us.hebi.quickbuf
    edu.wpi.first.math.controller.proto --> edu.wpi.first.math.proto
    edu.wpi.first.math.controller.proto --> edu.wpi.first.math.controller
    edu.wpi.first.math.controller --> edu.wpi.first.math
    edu.wpi.first.math.controller --> edu.wpi.first.math.system
    edu.wpi.first.math.controller --> edu.wpi.first.math.geometry
    edu.wpi.first.math.controller --> edu.wpi.first.math.trajectory
    edu.wpi.first.math.controller --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.controller --> edu.wpi.first.util.struct
    edu.wpi.first.math.controller --> edu.wpi.first.math.controller.struct
    edu.wpi.first.math.controller --> edu.wpi.first.math.controller.proto
    edu.wpi.first.math.controller --> edu.wpi.first.math.kinematics
    edu.wpi.first.math.controller --> edu.wpi.first.util.sendable
    edu.wpi.first.math.controller.struct --> edu.wpi.first.util.struct
    edu.wpi.first.math.controller.struct --> edu.wpi.first.math.controller
    edu.wpi.first.math.estimator --> edu.wpi.first.math
    edu.wpi.first.math.estimator --> edu.wpi.first.math.kinematics
    edu.wpi.first.math.estimator --> edu.wpi.first.math.geometry
    edu.wpi.first.math.estimator --> edu.wpi.first.math.interpolation
    edu.wpi.first.math.estimator --> edu.wpi.first.math.system
    edu.wpi.first.math.geometry --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.geometry --> edu.wpi.first.util.struct
    edu.wpi.first.math.geometry --> edu.wpi.first.units.measure
    edu.wpi.first.math.geometry --> edu.wpi.first.math
    edu.wpi.first.math.geometry --> edu.wpi.first.math.geometry.proto
    edu.wpi.first.math.geometry --> edu.wpi.first.math.geometry.struct
    edu.wpi.first.math.geometry --> edu.wpi.first.math.interpolation
    edu.wpi.first.math.geometry.proto --> edu.wpi.first.util.protobuf
    edu.wpi.first.math.geometry.proto --> us.hebi.quickbuf
    edu.wpi.first.math.geometry.proto --> edu.wpi.first.math.proto
    edu.wpi.first.math.geometry.proto --> edu.wpi.first.math.geometry
    edu.wpi.first.math.geometry.struct --> edu.wpi.first.util.struct
    edu.wpi.first.math.geometry.struct --> edu.wpi.first.math.geometry
    edu.wpi.first.math.numbers --> edu.wpi.first.math
    edu.wpi.first.wpilibj.xrp --> edu.wpi.first.math.geometry
    class "edu.wpi.first.math.geometry" [[edu/wpi/first/math/geometry/package-summary.html]] {}
    class "edu.wpi.first.math" [[edu/wpi/first/math/package-summary.html]] {}
    class "edu.wpi.first.math.trajectory" [[edu/wpi/first/math/trajectory/package-summary.html]] {}
    class "edu.wpi.first.math.controller" [[edu/wpi/first/math/controller/package-summary.html]] {}
    class "edu.wpi.first.math.kinematics" [[edu/wpi/first/math/kinematics/package-summary.html]] {}
    class "edu.wpi.first.math.filter" [[edu/wpi/first/math/filter/package-summary.html]] {}
    class "edu.wpi.first.math.system.plant" [[edu/wpi/first/math/system/plant/package-summary.html]] {}
    class "edu.wpi.first.math.system" [[edu/wpi/first/math/system/package-summary.html]] {}
    class "edu.wpi.first.math.proto" [[edu/wpi/first/math/proto/package-summary.html]] {}
    class "edu.wpi.first.math.struct" [[edu/wpi/first/math/struct/package-summary.html]] {}
    class "edu.wpi.first.math.spline" [[edu/wpi/first/math/spline/package-summary.html]] {}
    class "edu.wpi.first.math.spline.proto" [[edu/wpi/first/math/spline/proto/package-summary.html]] {}
    class "edu.wpi.first.math.spline.struct" [[edu/wpi/first/math/spline/struct/package-summary.html]] {}
    class "edu.wpi.first.math.system.proto" [[edu/wpi/first/math/system/proto/package-summary.html]] {}
    class "edu.wpi.first.math.system.struct" [[edu/wpi/first/math/system/struct/package-summary.html]] {}
    class "edu.wpi.first.math.estimator" [[edu/wpi/first/math/estimator/package-summary.html]] {}
    class "edu.wpi.first.math.system.plant.proto" [[edu/wpi/first/math/system/plant/proto/package-summary.html]] {}
    class "edu.wpi.first.math.system.plant.struct" [[edu/wpi/first/math/system/plant/struct/package-summary.html]] {}
    class "edu.wpi.first.math.path" [[edu/wpi/first/math/path/package-summary.html]] {}
    class "edu.wpi.first.math.trajectory.proto" [[edu/wpi/first/math/trajectory/proto/package-summary.html]] {}
    class "edu.wpi.first.math.trajectory.constraint" [[edu/wpi/first/math/trajectory/constraint/package-summary.html]] {}
    class "edu.wpi.first.math.kinematics.proto" [[edu/wpi/first/math/kinematics/proto/package-summary.html]] {}
    class "edu.wpi.first.math.kinematics.struct" [[edu/wpi/first/math/kinematics/struct/package-summary.html]] {}
    class "edu.wpi.first.math.interpolation" [[edu/wpi/first/math/interpolation/package-summary.html]] {}
    class "edu.wpi.first.math.controller.proto" [[edu/wpi/first/math/controller/proto/package-summary.html]] {}
    class "edu.wpi.first.math.controller.struct" [[edu/wpi/first/math/controller/struct/package-summary.html]] {}
    class "edu.wpi.first.math.geometry.proto" [[edu/wpi/first/math/geometry/proto/package-summary.html]] {}
    class "edu.wpi.first.math.geometry.struct" [[edu/wpi/first/math/geometry/struct/package-summary.html]] {}
    class "edu.wpi.first.math.numbers" [[edu/wpi/first/math/numbers/package-summary.html]] {}
@enduml
