@startuml
    !pragma layout smetana
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.util.sendable
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.wpilibj
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.math.trajectory
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.math.controller
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.math.kinematics
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.wpilibj.event
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj2.command --> edu.wpi.first.util.function
    edu.wpi.first.wpilibj2.command.sysid --> edu.wpi.first.wpilibj.sysid
    edu.wpi.first.wpilibj2.command.sysid --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj2.command.sysid --> edu.wpi.first.wpilibj2.command
    edu.wpi.first.wpilibj2.command.button --> edu.wpi.first.wpilibj.event
    edu.wpi.first.wpilibj2.command.button --> edu.wpi.first.wpilibj2.command
    edu.wpi.first.wpilibj2.command.button --> edu.wpi.first.math.filter
    edu.wpi.first.wpilibj2.command.button --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj2.command.button --> edu.wpi.first.wpilibj
    edu.wpi.first.wpilibj --> edu.wpi.first.util.sendable
    edu.wpi.first.wpilibj --> edu.wpi.first.hal
    edu.wpi.first.wpilibj --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj --> edu.wpi.first.math.geometry
    edu.wpi.first.wpilibj --> edu.wpi.first.wpilibj.motorcontrol
    edu.wpi.first.wpilibj --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj --> edu.wpi.first.wpilibj.util
    edu.wpi.first.wpilibj --> edu.wpi.first.hal.util
    edu.wpi.first.wpilibj --> edu.wpi.first.hal.can
    edu.wpi.first.wpilibj --> edu.wpi.first.wpilibj.event
    edu.wpi.first.wpilibj --> edu.wpi.first.util.datalog
    edu.wpi.first.wpilibj --> edu.wpi.first.util
    edu.wpi.first.wpilibj.event --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.event --> edu.wpi.first.math.filter
    edu.wpi.first.wpilibj.motorcontrol --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj.motorcontrol --> edu.wpi.first.wpilibj
    edu.wpi.first.wpilibj.motorcontrol --> edu.wpi.first.util.sendable
    edu.wpi.first.wpilibj.shuffleboard --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.shuffleboard --> edu.wpi.first.util.sendable
    edu.wpi.first.wpilibj.shuffleboard --> edu.wpi.first.cscore
    edu.wpi.first.wpilibj.shuffleboard --> edu.wpi.first.util.function
    edu.wpi.first.wpilibj.shuffleboard --> edu.wpi.first.wpilibj.smartdashboard
    edu.wpi.first.wpilibj.sysid --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj.sysid --> edu.wpi.first.util.datalog
    edu.wpi.first.wpilibj.drive --> edu.wpi.first.util.sendable
    edu.wpi.first.wpilibj.drive --> edu.wpi.first.wpilibj.motorcontrol
    edu.wpi.first.wpilibj.drive --> edu.wpi.first.math.geometry
    edu.wpi.first.wpilibj.drive --> edu.wpi.first.wpilibj
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.hal
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.wpilibj
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.hal.simulation
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.math.system.plant
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.math.system
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.units.measure
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.math
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.math.geometry
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.wpilibj.motorcontrol
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.livewindow --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.livewindow --> edu.wpi.first.util.sendable
    edu.wpi.first.wpilibj.counter --> edu.wpi.first.util.sendable
    edu.wpi.first.wpilibj.counter --> edu.wpi.first.wpilibj
    edu.wpi.first.wpilibj.smartdashboard --> edu.wpi.first.networktables
    edu.wpi.first.wpilibj.smartdashboard --> edu.wpi.first.math.geometry
    edu.wpi.first.wpilibj.smartdashboard --> edu.wpi.first.util.sendable
    edu.wpi.first.wpilibj.smartdashboard --> edu.wpi.first.wpilibj.util
    edu.wpi.first.wpilibj.smartdashboard --> edu.wpi.first.util.function
    edu.wpi.first.wpilibj.smartdashboard --> edu.wpi.first.math.trajectory
    edu.wpi.first.wpilibj.romi --> edu.wpi.first.hal
    edu.wpi.first.wpilibj.romi --> edu.wpi.first.wpilibj.motorcontrol
    edu.wpi.first.wpilibj.romi --> edu.wpi.first.wpilibj
    edu.wpi.first.wpilibj.xrp --> edu.wpi.first.wpilibj.motorcontrol
    edu.wpi.first.wpilibj.xrp --> edu.wpi.first.hal
    edu.wpi.first.wpilibj.xrp --> edu.wpi.first.wpilibj
    edu.wpi.first.wpilibj.xrp --> edu.wpi.first.math.geometry
    class "edu.wpi.first.wpilibj2.command" [[edu/wpi/first/wpilibj2/command/package-summary.html]] {}
    class "edu.wpi.first.wpilibj" [[edu/wpi/first/wpilibj/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.event" [[edu/wpi/first/wpilibj/event/package-summary.html]] {}
    class "edu.wpi.first.wpilibj2.command.sysid" [[edu/wpi/first/wpilibj2/command/sysid/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.sysid" [[edu/wpi/first/wpilibj/sysid/package-summary.html]] {}
    class "edu.wpi.first.wpilibj2.command.button" [[edu/wpi/first/wpilibj2/command/button/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.motorcontrol" [[edu/wpi/first/wpilibj/motorcontrol/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.util" [[edu/wpi/first/wpilibj/util/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.shuffleboard" [[edu/wpi/first/wpilibj/shuffleboard/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.smartdashboard" [[edu/wpi/first/wpilibj/smartdashboard/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.drive" [[edu/wpi/first/wpilibj/drive/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.simulation" [[edu/wpi/first/wpilibj/simulation/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.livewindow" [[edu/wpi/first/wpilibj/livewindow/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.counter" [[edu/wpi/first/wpilibj/counter/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.romi" [[edu/wpi/first/wpilibj/romi/package-summary.html]] {}
    class "edu.wpi.first.wpilibj.xrp" [[edu/wpi/first/wpilibj/xrp/package-summary.html]] {}
@enduml
