@startuml
    !pragma layout smetana
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods
    edu.wpi.first.hal.can --> edu.wpi.first.hal
    edu.wpi.first.hal.simulation --> edu.wpi.first.hal
    edu.wpi.first.wpilibj --> edu.wpi.first.hal
    edu.wpi.first.wpilibj --> edu.wpi.first.hal.util
    edu.wpi.first.wpilibj --> edu.wpi.first.hal.can
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.hal
    edu.wpi.first.wpilibj.simulation --> edu.wpi.first.hal.simulation
    edu.wpi.first.wpilibj.romi --> edu.wpi.first.hal
    edu.wpi.first.wpilibj.xrp --> edu.wpi.first.hal
    class "edu.wpi.first.hal.can" [[edu/wpi/first/hal/can/package-summary.html]] {}
    class "edu.wpi.first.hal" [[edu/wpi/first/hal/package-summary.html]] {}
    class "edu.wpi.first.hal.simulation" [[edu/wpi/first/hal/simulation/package-summary.html]] {}
    class "edu.wpi.first.hal.util" [[edu/wpi/first/hal/util/package-summary.html]] {}
@enduml
