@startuml
hide circle
skinparam linetype ortho

entity "**auth_account**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  *""public_id"": //wt_public_id //
  *""auth_method_id"": //wt_public_id [FK]//
  *""scope_id"": //wt_scope_id [FK]//
  ""iam_user_id"": //wt_public_id [FK]//
  ""iam_user_scope_id"": //wt_scope_id [FK]//
}

entity "**auth_method**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  *""public_id"": //wt_public_id //
  *""scope_id"": //wt_scope_id [FK]//
}

entity "**auth_password_account**" {
  + ""public_id"": //wt_public_id [PK][FK]//
  --
  *""public_id"": //wt_public_id //
  *""auth_method_id"": //wt_public_id [FK]//
  *""auth_method_id"": //wt_public_id //
  *""auth_method_id"": //wt_public_id //
  *""scope_id"": //text [FK]//
  ""name"": //text //
  ""description"": //text //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""login_name"": //text //
  ""version"": //wt_version //
}

entity "**auth_password_argon2_conf**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""private_id"": //wt_private_id [FK]//
  *""password_method_id"": //wt_public_id [FK]//
  *""password_method_id"": //wt_public_id //
  ""create_time"": //wt_timestamp //
  *""iterations"": //integer //
  *""memory"": //integer //
  *""threads"": //integer //
  *""salt_length"": //integer //
  *""key_length"": //integer //
}

entity "**auth_password_argon2_cred**" {
  + ""private_id"": //wt_private_id [PK][FK]//
  --
  *""password_account_id"": //wt_public_id [FK]//
  ""password_conf_id"": //wt_private_id [FK]//
  *""password_method_id"": //text [FK]//
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""salt"": //bytea //
  *""derived_key"": //bytea //
  *""key_id"": //text //
}

entity "**auth_password_conf**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""private_id"": //wt_private_id //
  *""password_method_id"": //wt_public_id [FK]//
}

entity "**auth_password_credential**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""password_account_id"": //wt_public_id [FK]//
  *""password_account_id"": //wt_public_id //
  ""password_conf_id"": //wt_private_id [FK]//
  *""password_method_id"": //wt_public_id [FK]//
}

entity "**auth_password_method**" {
  + ""public_id"": //wt_public_id [PK][FK]//
  --
  *""public_id"": //wt_public_id //
  *""scope_id"": //wt_scope_id [FK]//
  *""scope_id"": //wt_scope_id //
  ""password_conf_id"": //wt_private_id [FK]//
  ""name"": //text //
  ""description"": //text //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""min_login_name_length"": //integer //
  *""min_password_length"": //integer //
  ""version"": //wt_version //
}

entity "**auth_token**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  *""token"": //bytea //
  *""key_id"": //text //
  *""auth_account_id"": //wt_public_id [FK]//
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""approximate_last_access_time"": //wt_timestamp //
  ""expiration_time"": //wt_timestamp //
}

entity "**db_test_car**" {
  + ""id"": //bigint [PK]//
  --
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""public_id"": //text //
  ""name"": //text //
  ""model"": //text //
  ""mpg"": //smallint //
}

entity "**db_test_rental**" {
  + ""id"": //bigint [PK]//
  --
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""public_id"": //text //
  ""name"": //text //
  *""user_id"": //bigint [FK]//
  *""car_id"": //bigint [FK]//
}

entity "**db_test_scooter**" {
  + ""id"": //bigint [PK]//
  --
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""private_id"": //text //
  ""name"": //text //
  ""model"": //text //
  ""mpg"": //smallint //
}

entity "**db_test_user**" {
  + ""id"": //bigint [PK]//
  --
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""public_id"": //text //
  ""name"": //text //
  ""phone_number"": //text //
  ""email"": //text //
  ""version"": //wt_version //
}

entity "**host**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  *""public_id"": //wt_public_id //
  *""catalog_id"": //wt_public_id [FK]//
}

entity "**host_catalog**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  *""public_id"": //wt_public_id //
  *""scope_id"": //wt_scope_id [FK]//
}

entity "**host_set**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  *""public_id"": //wt_public_id //
  *""catalog_id"": //wt_public_id [FK]//
}

entity "**iam_group**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  *""public_id"": //wt_public_id //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""name"": //text //
  ""description"": //text //
  *""scope_id"": //wt_scope_id [FK]//
  *""scope_id"": //wt_scope_id //
  ""version"": //wt_version //
}

entity "**iam_group_member_user**" {
  + ""group_id"": //wt_public_id [PK][FK]//
  + ""member_id"": //wt_user_id [PK][FK]//
  --
  ""create_time"": //wt_timestamp //
}

entity "**iam_group_role**" {
  + ""role_id"": //wt_role_id [PK][FK]//
  + ""principal_id"": //wt_public_id [PK][FK]//
  --
  ""create_time"": //wt_timestamp //
}

entity "**iam_role**" {
  + ""public_id"": //wt_role_id [PK]//
  --
  *""public_id"": //wt_role_id //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""name"": //text //
  ""description"": //text //
  *""scope_id"": //wt_scope_id [FK]//
  *""scope_id"": //wt_scope_id //
  *""grant_scope_id"": //wt_scope_id [FK]//
  ""version"": //wt_version //
}

entity "**iam_role_grant**" {
  + ""role_id"": //wt_role_id [PK][FK]//
  + ""canonical_grant"": //text [PK]//
  --
  ""create_time"": //wt_timestamp //
  *""raw_grant"": //text //
}

entity "**iam_scope**" {
  + ""public_id"": //wt_scope_id [PK]//
  --
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""name"": //text //
  *""type"": //text [FK]//
  ""description"": //text //
  ""parent_id"": //text [FK]//
  ""version"": //wt_version //
}

entity "**iam_scope_global**" {
  + ""scope_id"": //wt_scope_id [PK][FK]//
  --
  ""name"": //text //
}

entity "**iam_scope_org**" {
  + ""scope_id"": //wt_scope_id [PK][FK]//
  --
  *""parent_id"": //wt_scope_id [FK]//
  ""name"": //text //
}

entity "**iam_scope_project**" {
  + ""scope_id"": //wt_scope_id [PK][FK]//
  + ""parent_id"": //wt_public_id [PK][FK]//
  --
  *""scope_id"": //wt_scope_id //
  *""parent_id"": //wt_public_id //
  ""name"": //text //
}

entity "**iam_scope_type_enm**" {
  + ""string"": //text [PK]//
  --
}

entity "**iam_user**" {
  + ""public_id"": //wt_user_id [PK]//
  --
  *""public_id"": //wt_user_id //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""name"": //text //
  ""description"": //text //
  *""scope_id"": //wt_scope_id [FK]//
  *""scope_id"": //wt_scope_id //
  ""version"": //wt_version //
}

entity "**iam_user_role**" {
  + ""role_id"": //wt_role_id [PK][FK]//
  + ""principal_id"": //wt_user_id [PK][FK]//
  --
  ""create_time"": //wt_timestamp //
}

entity "**kms_database_key**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""root_key_id"": //wt_private_id [FK]//
  ""create_time"": //wt_timestamp //
}

entity "**kms_database_key_version**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""database_key_id"": //wt_private_id [FK]//
  *""root_key_version_id"": //wt_private_id [FK]//
  ""version"": //wt_version //
  *""key"": //bytea //
  ""create_time"": //wt_timestamp //
}

entity "**kms_oplog_key**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""root_key_id"": //wt_private_id [FK]//
  ""create_time"": //wt_timestamp //
}

entity "**kms_oplog_key_version**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""oplog_key_id"": //wt_private_id [FK]//
  *""root_key_version_id"": //wt_private_id [FK]//
  ""version"": //wt_version //
  *""key"": //bytea //
  ""create_time"": //wt_timestamp //
}

entity "**kms_root_key**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""scope_id"": //wt_scope_id [FK]//
  ""create_time"": //wt_timestamp //
}

entity "**kms_root_key_version**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""root_key_id"": //wt_private_id [FK]//
  ""version"": //wt_version //
  *""key"": //bytea //
  ""create_time"": //wt_timestamp //
}

entity "**kms_session_key**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""root_key_id"": //wt_private_id [FK]//
  ""create_time"": //wt_timestamp //
}

entity "**kms_session_key_version**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""session_key_id"": //wt_private_id [FK]//
  *""root_key_version_id"": //wt_private_id [FK]//
  ""version"": //wt_version //
  *""key"": //bytea //
  ""create_time"": //wt_timestamp //
}

entity "**kms_token_key**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""root_key_id"": //wt_private_id [FK]//
  ""create_time"": //wt_timestamp //
}

entity "**kms_token_key_version**" {
  + ""private_id"": //wt_private_id [PK]//
  --
  *""token_key_id"": //wt_private_id [FK]//
  *""root_key_version_id"": //wt_private_id [FK]//
  ""version"": //wt_version //
  *""key"": //bytea //
  ""create_time"": //wt_timestamp //
}

entity "**oplog_entry**" {
  + ""id"": //bigint [PK]//
  --
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""version"": //text //
  *""aggregate_name"": //text //
  *""data"": //bytea //
}

entity "**oplog_metadata**" {
  + ""id"": //bigint [PK]//
  --
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""entry_id"": //bigint [FK]//
  *""key"": //text //
  ""value"": //text //
}

entity "**oplog_ticket**" {
  + ""id"": //bigint [PK]//
  --
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  *""name"": //text //
  *""version"": //bigint //
}

entity "**recovery_nonces**" {
  + ""nonce"": //text [PK]//
  --
  ""create_time"": //wt_timestamp //
}

entity "**server**" {
  + ""private_id"": //text [PK]//
  + ""type"": //text [PK]//
  --
  *""name"": //text //
  ""description"": //text //
  ""address"": //text //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
}

entity "**session**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  ""user_id"": //text [FK]//
  ""host_id"": //wt_public_id [FK]//
  ""server_id"": //text [FK]//
  ""server_type"": //text [FK]//
  ""target_id"": //wt_public_id [FK]//
  ""host_set_id"": //wt_public_id [FK]//
  ""auth_token_id"": //wt_public_id [FK]//
  ""scope_id"": //wt_scope_id [FK]//
  *""certificate"": //bytea //
  ""expiration_time"": //wt_timestamp //
  *""connection_limit"": //integer //
  ""tofu_token"": //bytea //
  ""key_id"": //text //
  ""termination_reason"": //text [FK]//
  ""version"": //wt_version //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""endpoint"": //text //
}

entity "**session_connection**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  *""session_id"": //wt_public_id [FK]//
  ""client_tcp_address"": //inet //
  ""client_tcp_port"": //integer //
  ""endpoint_tcp_address"": //inet //
  ""endpoint_tcp_port"": //integer //
  ""bytes_up"": //bigint //
  ""bytes_down"": //bigint //
  ""closed_reason"": //text [FK]//
  ""version"": //wt_version //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
}

entity "**session_connection_closed_reason_enm**" {
  + ""name"": //text [PK]//
  --
}

entity "**session_connection_state**" {
  + ""connection_id"": //wt_public_id [PK][FK]//
  + ""start_time"": //timestamp with time zone [PK]//
  --
  *""connection_id"": //wt_public_id //
  *""connection_id"": //wt_public_id //
  *""state"": //text [FK]//
  ""previous_end_time"": //timestamp with time zone [FK]//
  ""end_time"": //timestamp with time zone //
}

entity "**session_connection_state_enm**" {
  + ""name"": //text [PK]//
  --
}

entity "**session_state**" {
  + ""session_id"": //wt_public_id [PK][FK]//
  + ""start_time"": //timestamp with time zone [PK]//
  --
  *""session_id"": //wt_public_id //
  *""session_id"": //wt_public_id //
  *""state"": //text [FK]//
  ""previous_end_time"": //timestamp with time zone [FK]//
  ""end_time"": //timestamp with time zone //
}

entity "**session_state_enm**" {
  + ""name"": //text [PK]//
  --
}

entity "**session_termination_reason_enm**" {
  + ""name"": //text [PK]//
  --
}

entity "**static_host**" {
  + ""public_id"": //wt_public_id [PK][FK]//
  --
  *""public_id"": //wt_public_id //
  *""catalog_id"": //wt_public_id [FK]//
  *""catalog_id"": //wt_public_id //
  ""name"": //text //
  ""description"": //text //
  *""address"": //text //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""version"": //wt_version //
}

entity "**static_host_catalog**" {
  + ""public_id"": //wt_public_id [PK][FK]//
  --
  *""scope_id"": //wt_scope_id [FK]//
  ""name"": //text //
  ""description"": //text //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""version"": //wt_version //
}

entity "**static_host_set**" {
  + ""public_id"": //wt_public_id [PK][FK]//
  --
  *""public_id"": //wt_public_id //
  *""catalog_id"": //wt_public_id [FK]//
  *""catalog_id"": //wt_public_id //
  ""name"": //text //
  ""description"": //text //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""version"": //wt_version //
}

entity "**static_host_set_member**" {
  + ""host_id"": //wt_public_id [PK][FK]//
  + ""set_id"": //wt_public_id [PK][FK]//
  --
  *""catalog_id"": //wt_public_id [FK]//
}

entity "**target**" {
  + ""public_id"": //wt_public_id [PK]//
  --
  *""scope_id"": //wt_scope_id [FK]//
  ""create_time"": //wt_timestamp //
}

entity "**target_host_set**" {
  + ""target_id"": //wt_public_id [PK][FK]//
  + ""host_set_id"": //wt_public_id [PK][FK]//
  --
  ""create_time"": //wt_timestamp //
}

entity "**target_tcp**" {
  + ""public_id"": //wt_public_id [PK][FK]//
  --
  *""scope_id"": //wt_scope_id [FK]//
  *""name"": //text //
  ""description"": //text //
  ""default_port"": //integer //
  *""session_max_seconds"": //integer //
  *""session_connection_limit"": //integer //
  ""create_time"": //wt_timestamp //
  ""update_time"": //wt_timestamp //
  ""version"": //wt_version //
}

entity "**wh_date_dimension**" {
  + ""id"": //integer [PK]//
  --
  *""date"": //date //
  ""calendar_quarter"": //wh_dim_text //
  ""calendar_month"": //wh_dim_text //
  *""calendar_year"": //smallint //
  ""day_of_week"": //wh_dim_text //
  *""day_of_week_number"": //smallint //
  *""day_of_week_number_iso"": //smallint //
  *""day_of_week_number_zero_based"": //smallint //
  *""day_number_in_calendar_month"": //smallint //
  *""day_number_in_calendar_year"": //smallint //
  ""weekday_indicator"": //wh_dim_text //
}

entity "**wh_host_dimension**" {
  + ""id"": //wh_dim_id [PK]//
  --
  *""host_id"": //wh_public_id //
  ""host_type"": //wh_dim_text //
  ""host_name"": //wh_dim_text //
  ""host_description"": //wh_dim_text //
  ""host_address"": //wh_dim_text //
  *""host_set_id"": //wh_public_id //
  ""host_set_type"": //wh_dim_text //
  ""host_set_name"": //wh_dim_text //
  ""host_set_description"": //wh_dim_text //
  *""host_catalog_id"": //wh_public_id //
  ""host_catalog_type"": //wh_dim_text //
  ""host_catalog_name"": //wh_dim_text //
  ""host_catalog_description"": //wh_dim_text //
  *""target_id"": //wh_public_id //
  ""target_type"": //wh_dim_text //
  ""target_name"": //wh_dim_text //
  ""target_description"": //wh_dim_text //
  *""target_default_port_number"": //integer //
  *""target_session_max_seconds"": //integer //
  *""target_session_connection_limit"": //integer //
  *""project_id"": //wt_scope_id //
  ""project_name"": //wh_dim_text //
  ""project_description"": //wh_dim_text //
  *""host_organization_id"": //wt_scope_id //
  ""host_organization_name"": //wh_dim_text //
  ""host_organization_description"": //wh_dim_text //
  ""current_row_indicator"": //wh_dim_text //
  ""row_effective_time"": //wh_timestamp //
  ""row_expiration_time"": //wh_timestamp //
}

entity "**wh_session_accumulating_fact**" {
  + ""session_id"": //wt_public_id [PK]//
  --
  *""auth_token_id"": //wt_public_id //
  *""host_id"": //wh_dim_id [FK]//
  *""user_id"": //wh_dim_id [FK]//
  *""session_pending_date_id"": //integer [FK]//
  *""session_pending_time_id"": //integer [FK]//
  ""session_pending_time"": //wh_timestamp //
  *""session_active_date_id"": //integer [FK]//
  *""session_active_time_id"": //integer [FK]//
  ""session_active_time"": //wh_timestamp //
  *""session_canceling_date_id"": //integer [FK]//
  *""session_canceling_time_id"": //integer [FK]//
  ""session_canceling_time"": //wh_timestamp //
  *""session_terminated_date_id"": //integer [FK]//
  *""session_terminated_time_id"": //integer [FK]//
  ""session_terminated_time"": //wh_timestamp //
  ""total_connection_count"": //bigint //
  ""total_bytes_up"": //wh_bytes_transmitted //
  ""total_bytes_down"": //wh_bytes_transmitted //
}

entity "**wh_session_connection_accumulating_fact**" {
  The Wh Session Connection Accumulating Fact table is an accumulating fact table. The grain of the fact table is one row per session connection.
  ..
  + ""connection_id"": //wt_public_id [PK]//
  --
  *""session_id"": //wt_public_id [FK]//
  *""host_id"": //wh_dim_id [FK]//
  *""user_id"": //wh_dim_id [FK]//
  *""connection_authorized_date_id"": //integer [FK]//
  *""connection_authorized_time_id"": //integer [FK]//
  ""connection_authorized_time"": //wh_timestamp //
  *""connection_connected_date_id"": //integer [FK]//
  *""connection_connected_time_id"": //integer [FK]//
  ""connection_connected_time"": //wh_timestamp //
  *""connection_closed_date_id"": //integer [FK]//
  *""connection_closed_time_id"": //integer [FK]//
  ""connection_closed_time"": //wh_timestamp //
  ""client_tcp_address"": //inet //
  ""client_tcp_port_number"": //wh_inet_port //
  ""endpoint_tcp_address"": //inet //
  ""endpoint_tcp_port_number"": //wh_inet_port //
  *""connection_count"": //smallint //
  ""bytes_up"": //wh_bytes_transmitted  : Bytes Up is the total number of bytes received by the worker from the client and sent to the endpoint for this connection. Bytes Up is a fully additive measurement.//
  ""bytes_down"": //wh_bytes_transmitted  : Bytes Down is the total number of bytes received by the worker from the endpoint and sent to the client for this connection. Bytes Down is a fully additive measurement.//
}

entity "**wh_time_of_day_dimension**" {
  + ""id"": //integer [PK]//
  --
  *""time_no_zone"": //time without time zone //
  *""time_at_utc"": //time with time zone //
  *""hour_of_day"": //smallint //
  *""minute_of_hour"": //smallint //
  *""second_of_minute"": //smallint //
  ""display_time_24"": //wh_dim_text //
  ""display_time_12"": //wh_dim_text //
  ""meridiem_indicator"": //wh_dim_text //
}

entity "**wh_user_dimension**" {
  + ""id"": //wh_dim_id [PK]//
  --
  *""user_id"": //wt_user_id //
  ""user_name"": //wh_dim_text //
  ""user_description"": //wh_dim_text //
  *""auth_account_id"": //wh_public_id //
  ""auth_account_type"": //wh_dim_text //
  ""auth_account_name"": //wh_dim_text //
  ""auth_account_description"": //wh_dim_text //
  *""auth_method_id"": //wh_public_id //
  ""auth_method_type"": //wh_dim_text //
  ""auth_method_name"": //wh_dim_text //
  ""auth_method_description"": //wh_dim_text //
  *""user_organization_id"": //wt_scope_id //
  ""user_organization_name"": //wh_dim_text //
  ""user_organization_description"": //wh_dim_text //
  ""current_row_indicator"": //wh_dim_text //
  ""row_effective_time"": //wh_timestamp //
  ""row_expiration_time"": //wh_timestamp //
}

"**auth_account**"   }--  "**iam_user**"

"**auth_account**"   }--  "**iam_user**"

"**auth_account**"   }--  "**iam_user**"

"**auth_account**"   }--  "**iam_user**"

"**auth_account**"   }--  "**auth_method**"

"**auth_account**"   }--  "**auth_method**"

"**auth_account**"   }--  "**auth_method**"

"**auth_method**"   }--  "**iam_scope**"

"**auth_password_account**"   }--  "**auth_password_method**"

"**auth_password_account**"   }--  "**auth_password_method**"

"**auth_password_account**"   }--  "**auth_password_method**"

"**auth_password_account**"   }--  "**auth_password_method**"

"**auth_password_account**"   }--  "**auth_password_method**"

"**auth_password_account**"   }--  "**auth_password_method**"

"**auth_password_account**"   }--  "**auth_password_method**"

"**auth_password_account**"   }--  "**auth_password_method**"

"**auth_password_account**"  ||-||  "**auth_account**"

"**auth_password_account**"  ||-||  "**auth_account**"

"**auth_password_account**"  ||-||  "**auth_account**"

"**auth_password_account**"  ||-||  "**auth_account**"

"**auth_password_account**"   }--  "**auth_account**"

"**auth_password_account**"   }--  "**auth_account**"

"**auth_password_account**"   }--  "**auth_account**"

"**auth_password_account**"   }--  "**auth_account**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_conf**"   }--  "**auth_password_conf**"

"**auth_password_argon2_cred**"   }--  "**auth_password_credential**"

"**auth_password_argon2_cred**"   }--  "**auth_password_credential**"

"**auth_password_argon2_cred**"   }--  "**auth_password_credential**"

"**auth_password_argon2_cred**"   }--  "**auth_password_credential**"

"**auth_password_argon2_cred**"   }--  "**auth_password_argon2_conf**"

"**auth_password_argon2_cred**"   }--  "**auth_password_argon2_conf**"

"**auth_password_argon2_cred**"   }--  "**auth_password_argon2_conf**"

"**auth_password_argon2_cred**"   }--  "**auth_password_argon2_conf**"

"**auth_password_argon2_cred**"  ||-||  "**auth_password_credential**"

"**auth_password_conf**"   }--  "**auth_password_method**"

"**auth_password_conf**"   }--  "**auth_password_method**"

"**auth_password_credential**"   }--  "**auth_password_account**"

"**auth_password_credential**"   }--  "**auth_password_account**"

"**auth_password_credential**"   }--  "**auth_password_account**"

"**auth_password_credential**"   }--  "**auth_password_account**"

"**auth_password_credential**"   }--  "**auth_password_account**"

"**auth_password_credential**"   }--  "**auth_password_account**"

"**auth_password_credential**"   }--  "**auth_password_account**"

"**auth_password_credential**"   }--  "**auth_password_conf**"

"**auth_password_credential**"   }--  "**auth_password_conf**"

"**auth_password_credential**"   }--  "**auth_password_conf**"

"**auth_password_method**"  ||-||  "**auth_method**"

"**auth_password_method**"  ||-||  "**auth_method**"

"**auth_password_method**"  ||-||  "**auth_method**"

"**auth_password_method**"  ||-||  "**auth_method**"

"**auth_password_method**"   }--  "**auth_method**"

"**auth_password_method**"   }--  "**auth_method**"

"**auth_password_method**"   }--  "**auth_password_conf**"

"**auth_password_method**"   }--  "**auth_password_conf**"

"**auth_password_method**"   }--  "**auth_password_conf**"

"**auth_password_method**"   }--  "**auth_password_conf**"

"**auth_token**"   }--  "**auth_account**"

"**auth_token**"   }--  "**auth_account**"

"**db_test_rental**"   }--  "**db_test_car**"

"**db_test_rental**"   }--  "**db_test_user**"

"**host**"   }--  "**host_catalog**"

"**host**"   }--  "**host_catalog**"

"**host_catalog**"   }--  "**iam_scope**"

"**host_set**"   }--  "**host_catalog**"

"**host_set**"   }--  "**host_catalog**"

"**iam_group**"   }--  "**iam_scope**"

"**iam_group**"   }--  "**iam_scope**"

"**iam_group_member_user**"   }--  "**iam_group**"

"**iam_group_member_user**"   }--  "**iam_group**"

"**iam_group_member_user**"   }--  "**iam_user**"

"**iam_group_member_user**"   }--  "**iam_user**"

"**iam_group_role**"   }--  "**iam_group**"

"**iam_group_role**"   }--  "**iam_group**"

"**iam_group_role**"   }--  "**iam_role**"

"**iam_group_role**"   }--  "**iam_role**"

"**iam_role**"   }--  "**iam_scope**"

"**iam_role**"   }--  "**iam_scope**"

"**iam_role**"   }--  "**iam_scope**"

"**iam_role_grant**"   }--  "**iam_role**"

"**iam_role_grant**"   }--  "**iam_role**"

"**iam_scope**"   }--  "**iam_scope**"

"**iam_scope**"   }--  "**iam_scope_type_enm**"

"**iam_scope_global**"  ||-||  "**iam_scope**"

"**iam_scope_org**"   }--  "**iam_scope_global**"

"**iam_scope_org**"  ||-||  "**iam_scope**"

"**iam_scope_project**"   }--  "**iam_scope_org**"

"**iam_scope_project**"   }--  "**iam_scope_org**"

"**iam_scope_project**"   }--  "**iam_scope**"

"**iam_scope_project**"   }--  "**iam_scope**"

"**iam_user**"   }--  "**iam_scope**"

"**iam_user**"   }--  "**iam_scope**"

"**iam_user_role**"   }--  "**iam_user**"

"**iam_user_role**"   }--  "**iam_user**"

"**iam_user_role**"   }--  "**iam_role**"

"**iam_user_role**"   }--  "**iam_role**"

"**kms_database_key**"   }--  "**kms_root_key**"

"**kms_database_key_version**"   }--  "**kms_database_key**"

"**kms_database_key_version**"   }--  "**kms_root_key_version**"

"**kms_oplog_key**"   }--  "**kms_root_key**"

"**kms_oplog_key_version**"   }--  "**kms_oplog_key**"

"**kms_oplog_key_version**"   }--  "**kms_root_key_version**"

"**kms_root_key**"   }--  "**iam_scope**"

"**kms_root_key_version**"   }--  "**kms_root_key**"

"**kms_session_key**"   }--  "**kms_root_key**"

"**kms_session_key_version**"   }--  "**kms_root_key_version**"

"**kms_session_key_version**"   }--  "**kms_session_key**"

"**kms_token_key**"   }--  "**kms_root_key**"

"**kms_token_key_version**"   }--  "**kms_root_key_version**"

"**kms_token_key_version**"   }--  "**kms_token_key**"

"**oplog_metadata**"   }--  "**oplog_entry**"

"**session**"   }--  "**auth_token**"

"**session**"   }--  "**host**"

"**session**"   }--  "**host**"

"**session**"   }--  "**host_set**"

"**session**"   }--  "**host_set**"

"**session**"   }--  "**iam_scope_project**"

"**session**"   }--  "**iam_scope_project**"

"**session**"   }--  "**server**"

"**session**"   }--  "**server**"

"**session**"   }--  "**target**"

"**session**"   }--  "**session_termination_reason_enm**"

"**session**"   }--  "**iam_user**"

"**session**"   }--  "**iam_user**"

"**session_connection**"   }--  "**session_connection_closed_reason_enm**"

"**session_connection**"   }--  "**session**"

"**session_connection_state**"   }--  "**session_connection**"

"**session_connection_state**"   }--  "**session_connection**"

"**session_connection_state**"   }--  "**session_connection**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state**"

"**session_connection_state**"   }--  "**session_connection_state_enm**"

"**session_state**"   }--  "**session**"

"**session_state**"   }--  "**session**"

"**session_state**"   }--  "**session**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state**"

"**session_state**"   }--  "**session_state_enm**"

"**static_host**"   }--  "**static_host_catalog**"

"**static_host**"   }--  "**static_host_catalog**"

"**static_host**"  ||-||  "**host**"

"**static_host**"  ||-||  "**host**"

"**static_host**"  ||-||  "**host**"

"**static_host**"   }--  "**host**"

"**static_host**"   }--  "**host**"

"**static_host**"  ||-||  "**host**"

"**static_host_catalog**"   }--  "**iam_scope**"

"**static_host_catalog**"  ||-||  "**host_catalog**"

"**static_host_catalog**"  ||-||  "**host_catalog**"

"**static_host_catalog**"   }--  "**host_catalog**"

"**static_host_set**"   }--  "**static_host_catalog**"

"**static_host_set**"   }--  "**static_host_catalog**"

"**static_host_set**"  ||-||  "**host_set**"

"**static_host_set**"  ||-||  "**host_set**"

"**static_host_set**"  ||-||  "**host_set**"

"**static_host_set**"   }--  "**host_set**"

"**static_host_set**"   }--  "**host_set**"

"**static_host_set**"  ||-||  "**host_set**"

"**static_host_set_member**"   }--  "**static_host**"

"**static_host_set_member**"   }--  "**static_host**"

"**static_host_set_member**"   }--  "**static_host**"

"**static_host_set_member**"   }--  "**static_host**"

"**static_host_set_member**"   }--  "**static_host_set**"

"**static_host_set_member**"   }--  "**static_host_set**"

"**static_host_set_member**"   }--  "**static_host_set**"

"**static_host_set_member**"   }--  "**static_host_set**"

"**target**"   }--  "**iam_scope**"

"**target_host_set**"   }--  "**host_set**"

"**target_host_set**"   }--  "**host_set**"

"**target_host_set**"   }--  "**target**"

"**target_tcp**"  ||-||  "**target**"

"**target_tcp**"   }--  "**iam_scope**"

"**wh_session_accumulating_fact**"   }--  "**wh_host_dimension**"

"**wh_session_accumulating_fact**"   }--  "**wh_date_dimension**"

"**wh_session_accumulating_fact**"   }--  "**wh_time_of_day_dimension**"

"**wh_session_accumulating_fact**"   }--  "**wh_date_dimension**"

"**wh_session_accumulating_fact**"   }--  "**wh_time_of_day_dimension**"

"**wh_session_accumulating_fact**"   }--  "**wh_date_dimension**"

"**wh_session_accumulating_fact**"   }--  "**wh_time_of_day_dimension**"

"**wh_session_accumulating_fact**"   }--  "**wh_date_dimension**"

"**wh_session_accumulating_fact**"   }--  "**wh_time_of_day_dimension**"

"**wh_session_accumulating_fact**"   }--  "**wh_user_dimension**"

"**wh_session_connection_accumulating_fact**"   }--  "**wh_date_dimension**"

"**wh_session_connection_accumulating_fact**"   }--  "**wh_time_of_day_dimension**"

"**wh_session_connection_accumulating_fact**"   }--  "**wh_date_dimension**"

"**wh_session_connection_accumulating_fact**"   }--  "**wh_time_of_day_dimension**"

"**wh_session_connection_accumulating_fact**"   }--  "**wh_date_dimension**"

"**wh_session_connection_accumulating_fact**"   }--  "**wh_time_of_day_dimension**"

"**wh_session_connection_accumulating_fact**"   }--  "**wh_host_dimension**"

"**wh_session_connection_accumulating_fact**"   }--  "**wh_session_accumulating_fact**"

"**wh_session_connection_accumulating_fact**"   }--  "**wh_user_dimension**"
@enduml
