:PROPERTIES:
:ID:       81b6e792-644c-4c92-95c4-806be72461ae
:END:
#+TITLE: Blender: fix broken USD patch on archlinux
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:b3826464-5132-4a77-9707-93a72bd1d4a3][Blender]]
+ [[id:fbf366f2-5c17-482b-ac7d-6dd130aa4d05][Arch]]

* Original Build Issues
=./blender-git/usd_python.patch= breaks the build because of course it does.

+ manually specify the BOOST_VERSION as 1.80.
+ change in multiple places
+ build from checked out sources with =makepkg -e --nointeg=
  - integrity has already been checked 1,000 times.
+ install with =makepkg -i
  - now cmake complains about the =_GLEW=, so cross fingers or rerun yay with
    verbose options.

* Attempted Fixes

Most of this could have been avoided by checking out an old branch of
=blender-git= and building that. I guess?

** Patch references to bad boost

Described above

** Install amdgpu-pro-olgp

Whatever tf that is -- i'm sure it's beneficial, but it's really breaking my
balls at the moment and eating all my time with zero official Arch support from
AMD.

Interestingly, gpuviewer is now broken. Wouldn't that be nice to know AMD, but
it will be months before you hear it from more than a dozen Ubuntu users.
Anyways, onwards: there are more acronyms to learn.

Remove the old with =yay -Rns amdgpu-pro-opengl lib32-amdgpu-pro-opengl= and
install with =yay -Syu amdgpu-pro-oglp lib32-amdgpu-pro-oglp=

Restart your computer and cross your fingers because maybe X11 or wayland
doesn't start.

** Specify offload CPU

okay, it boots and logs the users in.

Run =yay -Syu openmp-extras= since it contains =offload-arch= which seems very
interesting ... it also seems like zero people on the internet know what it is
-- some generalization for heterogenous compute for programs compiled via LLVM?
Oh, that was succinct. I'm glad people care. If it is that, it's long overdue
and some kind of feat of technological magic. Something broke my blender though.

offload-arch is about 3 years old, almost 4. It'd be nice to hear about what it
is from an expert, but i'm hardly that -- and besides: I don't actually exist.

Anyways, back to the =openmp-extras= build. It broke. SURPRISE! It's new. Really
new. It breaks a lot of things. ArchWiki has [[https://wiki.archlinux.org/index.php?search=%22offload-arch%22&title=Special%3ASearch&wprov=acrw1][zero references to the string
"offload-arch"]]. Because it's new.
