:PROPERTIES:
:ID:       f4ad7adc-8c74-4c38-baaf-161f11154834
:END:
#+TITLE: Vendors should support Arch and Alternate Distros
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:fbf366f2-5c17-482b-ac7d-6dd130aa4d05][Arch]]

#+begin_quote
2026/7 mainly i was dumb, but also ... it's really hard to learn on your own.
one key is to err generally to the side of "I only know that I know nothing"
#+end_quote

* Main usability problem with matlab

#+begin_quote
This isn't really aimed at Matlab, per se, because there are dozens of
hardware/software vendors that do this.
#+end_quote

And the key thing is: you can't use the automagic UI/UX controls in the "live
editor" to quickly update all the plots in your

it's not like i'm some "completionist sonic the hedgehog player" who collects
every single ring or coin... i would like to move a slider and see my plots
update. and NO i do not want to run unstable "stable" for a linux distribution.
sorry. the only way i would run ubuntu is in a VM or if i took the time to learn
=debops=.

julia does this, but is hard to deal with and doesn't have simple
computer algebra (w/o python) that I can grok. jupyter does this (maybe?) but
it's python and GLHF with getting python to feel like a TI-89.

* Just support archlinux (or pacman)

OMFG it's easy for proprietary vendors to write a set of packages and it
basically costs nothing.

You can benefit from this: archlinux will get you better data from users on how
your software runs in linux, if they are okay with activating
telemetry/crashlogs.

also, these vendors /only claim to support/ linux (debian, rpm). It's a lot
better than nothing, but try running a custom kernal and/or optimizing things
with RamFS/TmpFS. And yeh, it's hard to expect vendors to support literally
everything, but literally all they do is:

+ maintain a linux build compatible with common GUI toolkits
+ maintain some build/install scripts
+ create some packaging pipelines & QA to take the builds, validate and package
  *.deb or *.rpm

That is hardly support.

** no one supports arch.

you really, really need to support archlinux. it's actually only moderately
better than ubuntu in this regard, but holy shit it is so easy to break an
ubuntu/fedora distribution once the environment becomes intractibly polluted --
which is why matlab packages its binaries/libs anyways.

once you add like 4 or 5 custom apt repos, you are like guaranteed to have
problems unless the repo's offer packages that magically play nice with each
other. they don't. they're not really aware of dep/version constraints. ubuntu
is not bad, but IMO i can't stand it. same thing with RPM distro's. good for
some applications, very very bad for my desktop.

+ ubuntu :: great for beginners, terrible for intermediate skill, good for advanced
  users with admin/scripting experience

+ fedora/rpm :: great for people who can't afford redhat? i'm not sure.
  - they certainly integrate SELinux better than anyone else (which is
    fantastic!).
  - their package management is good (tools like RPM, mock), but it is not plain
    shell script and it will take quite a bit of time to get used to if you need
    to write them.
  - RPM's kinda suck to write unless you have been initiated into "the esoteric
    order of red hat". A little hard to learn to use on your own.
  - the redhat ecosystem has exploded with about 3 different ways to copy =pacman=
    ... (COPR, silverblue, etc...).
  - redhat does have declarative configuration systems (which are based on pure
    shell scripts.)

+ arch :: not bad for beginners, but not enough users actually use arch in the
  minimalistic way it's intended to be run -- and this leaves hundreds of things
  unconfigured like BTRFS snapshots. great!
  - still very difficult to support multiple package repos without creating an
    entirely different namespace for packages that overlap ().
  - =PKGBUILD= is plain shell script.
    - custom builds are simple to figure out.
    - extending packages is not great (you can't inherit from a package)
  - fairly central package management (or at least package discovery with AUR).
  - this is good, but the lack of

+ nyx  :: a guix-like distro which could be easily mainstreamed.
  - between this distro and guix, every other major distro (deb, rpm, etc) will
    copy the hell out of these two, but they will /never/ get it right. when
    they do, it's likely to be more popular, simply because they already have
    more users.
    - old tools will remain old tools ... for better or worse.

+ Guix :: best package manager and distro i've used by far. the packages are
  written in Scheme and allow you to =inherit= from other package definitions
  and like /surgically/ replace the build steps defined by other packages.
  - you have /actual package inheritance/ and mechanisms that allow for
    "multiple inheritance" (or maybe just modules i'm not sure)
  - a bit difficult to learn (req. emacs/scheme) but /very easy/ to use once
    you've established a system
  - very easy to create ISO's or software bundles that run on USB with zero
    external dependencies
  - can suffer from hardware compatibility issues and it's a bit tough to
    discover whether an install will run without nonfree software. this is the
    biggest barrier to growth.
  - it takes a while to begin realizing exponential gains, but it's hard for
    other distro's replicate the value.
    - it's like the package manager comes with ansible.

    - if you're paranoid and, when confronted with a computer/server that needs
      to be deloused, your answer is "burn that motherfucker to the ground",
      then this or Nix is the distribution for you.



* Why not windows?

If your app has a scripting interface, no one is going to use that in windows.
ok, with matlab, maybe. but basically, no one is going to try to
automate/integrate your application. windows has changed how they think about
using software and has sheltered these users from complexity.

#+begin_quote
and to be clear, if you use windows, good for you. i hope that shit works out.
there are good tools. onenote is basically emacs.

IMO windows users will always peak in productivity on windows systems, whereas
with linux/mac, the exponential gains don't ever stop producing returns -- IF
utilizing modularity/network/cloud and ONLY IF you continue using linux/mac.
When software/hardware issues, boot clobbering, lack of support, secureboot,
lack of gaming, poluted environment, corrupted install, etc cause someone to
give up, they're going to lose most of those gains.
#+end_quote

Anyways almost no one will integrate your software into higher-order processes
driven by scripts.

Why did AutoLISP die out? yeh ... exactly, no one cares to program (even though
a Lisp is *ideal for CAD*). The GUI is so much simpler that it appears that
basically no one knows it exists. And autolisp is a bit esoteric. The point is:
you cannot chain tools together in modular fashion in Windows -- perhaps it is
theoretically possible, but if so it either requires a Visual Studio license and
Windows-based service/IPC programming OR a bundled version of Visual Basic.
Windows users are lucky that somehow Microsoft did not screw up or otherwise
neuter powershell, but you need admin priv. to install/use it.

The issue here is that there is such a learning curve when transitioning from
GUI-driven Windows to scripting/automation-driven mac/linux that no one actually
makes the leap from one paradigm to the other. They may use the other OS, but
they have no idea that they are "doing it wrong" because so few people actually
use Linux that there are almost zero good mentors to emulate. Windows users may
transition to the other OS, but they keep using it like windows -- which does
have things like cron, scripts, services, event viewer, or whatever.

But it is shit because:

- you cannot control your environment. you are lucky to run a programming
  language whose environment is simple to replicate on your next install.
  - unless you run it in a VM
- you can't configure anything important without touching the registry.
- hmmmm (not everything is bad)

What this means is that for most people, the learning curve is so steep and the
need to change how they think about using/configuring their computer is itself
vague and hard to define that they will be unable to identify what to change,
what is possible, etc.

- they won't learn how to drive a computer with simple scripts
  (whether user-invoked, event-driven or scheduled)
- they won't learn how to customize it to their needs
- they won't learn about open standards.

the worst part: there won't ever a large enough population of Linux users who
know what they are doing and use it as their daily driver for it to be easy
to...

#+begin_quote
2026/7: find a community to plug into without getting tickets to conventions or
whatever. it's just hard bc everyone's eyes were always glued to their screens i
think. idk ... i've seen and heard of developers from very remote areas (and
some being relatively impoverished areas or at least not in an area where six
figures are common).

+ some of these developers I'd have to imagine learned how to connect to the
  community from those remote areas
+ whereas others have enough experience/knowledge or quirky habits and for
  whatever reason just don't need to tap into communities in order to learn

it really depends on the person.
#+end_quote

i don't expect that using a computer "the unix way" would be
appropriate/appreciated by more than 5% of the population. As long as that
number is small, everything will stay the way it is and it will forever be a
pain in the ass to use the GPU (without VM passthrough) on an app that "supports
linux". I mean if you actually use Matlab for what it is intended to do, your
desktop better be configured as a workstation whose sole purpose is to run this
software bc if you install anything else, it is likely to fuck up and need a
reinstall after 3-6 months. This means:

- you need to maintain multiple secrets storage (password safe) and browser
  sessions between the OS installs.
- you need to shut down your computer every time you want to open up the
  GPU-using application
  - or buy a second GPU and run it in a VM, which yes is an option if you have
    like $6000 for this workstation
- you need to boot multiple OS's. hope they don't clobber each other
  - you don't care about /Secure Boot/ whatever tf that means. about as useful
    as anti-cheat on games i'm sure, but you probably don't care because who the
    fuck uses linux anyways.

