:PROPERTIES:
:ID:       a0420ef9-3c0e-446e-9bad-609ccc548cd1
:END:
#+TITLE: Common Household Dust Contaminants
#+CATEGORY: slips
#+TAGS:

+ [[id:d6782147-2239-4d0d-9e86-091cb3a5fff0][Toxicology]]
+ [[id:771f417d-8aa5-47b7-b052-6bca9542d3c6][Endocrinology]]
+ [[id:0464890c-6043-4fda-af9d-a5bec94d857b][Pharmacokinetics]]

Sources:

+ [[https://www.youtube.com/watch?v=TgDqg0C-rU4][Harmful chemicals are found in household dust]]


+ CHEMOPATH :: someone who is especially sensitive to chemicals

* Flame Retardants

** Magic Dust

There is this dust in my house and I cannot for the life of me track down its
source, which appears to be the laundry room (this is where the hot water heater
is)

+ It composes about 80% of the dust in my basement. It is confined almost
  entirely to my basement (where I spend +95% of my time at home).
+ It gets trapped in the dryer, but this sources air from the inside.
+ I'm not sure whether it gets trapped in the AC filter, but this /should/
  source air from the outside. It does show up in high concentrations in the
  room where there is AC air intake.

*** Physical properties:

+ It is extremely reactive to UV light.
+ IT DOES _NOT_ BURN IN DIRECT FLAME OF A BUTANE LIGHTER FOR ANY PERIOD OF TIME.
  - NO EFFECT. ZERO EFFECT WHATSOEVER.
  - However, while dispersing heat through fibers, flame retardants often
    redirect thermal energy towards driving chains of slow/predictible
    endothermic reactions (thus consuming heat and priortizing its spread
    towards the chemical reactions)
+ The fibers are hairlike, from 0.1mm to 1.0 mm long.
  - the fibers are 20-100 microns wide. difficult to manipulate without
    tweezers.
  - It is a plastic. It stretches a bit. The particles coil in shape.
  - IT IS A HOMOGENOUS MATERIAL. IT IS 100% THE IDENTICAL MATERIAL THROUGHOUT.
+ It likes to settle in places with moisture/humidity (on bathroom walls)
  - It floats ... a lot (electrostatic interaction)
  - It does NOT absorb water. IT IS A HOMOGENOUS PLASTIC MATERIAL.

*** Potential sources of the chemical that I've considered:

+ Dryer sheets (about the same reaction to 235nm UV light)
  - associated to laundry room
+ Hot water heater (potentially shedding some kind of flame retardant fibers
  from combustion/heat?)
  - The color and UV reactivity is always 100% homogenous: the fibers absorb
    absolutely _nothing_ that occludes/absorbes/blocks or otherwise interferes
    with the absorption/transmission of UV/VIS light.

** Biphenyls ([[https://en.wikipedia.org/wiki/Polychlorinated_biphenyl][PCB]] and [[https://en.wikipedia.org/wiki/Polybrominated_biphenyl][PBB]])

#+begin_src smiles :tangle no :file img/smiles/biphenyls.svg :results file
[*]C3=CC=C(-C1=CC=C(-[*])C=C1)C=C3
#+end_src

#+RESULTS:
[[file:img/smiles/biphenyls.svg]]

*** Polychlorinated Biphenyls (PCB)

*** Polybrominated Biphenyl Ethers (PCBE)

+ [[https://www.epa.gov/sites/default/files/2014-03/documents/ffrrofactsheet_contaminant_perchlorate_january2014_final_0.pdf][EPA fact sheet]]

* Insecticides

Exposure should be limited to areas where the insecticides are applied.

+ One issue is that the insecticides are often delivered in a vehicle which is
  insoluble so that:
  - there is limited runoff risk
  - the poison will not dissolve into water or other common solvents (mostly
    polar) and thus reduce the dosage below that of what is effective.
+ Thus, after years of applications, there are years worth of insecticides. If
  the vehicle is crystalline (as they often are), then the insecticide can form
  a dust in dry conditions. It may still absorb through the skin.
+ These chemicals can be absorbed into dust or sawdust, presenting an inhalation
  risk. The crystalline vehicles they use can also present an inhalation risk.

** [[https://pubchem.ncbi.nlm.nih.gov/compound/Deltamethrin#section=Acute-Effects][Deltamethrin]] ([[yt:][Suspend SC]] and others)

The way this product is formulated presents an inhalation risk. This pesticide
is not supposed to be used in a home with cats.

#+begin_src smiles :tangle no :file ./img/smiles/deltamethrin.svg :results file
CC1(C(C1C(=O)OC(C#N)C2=CC(=CC=C2)OC3=CC=CC=C3)C=C(Br)Br)C
#+end_src

#+RESULTS:
[[file:./img/smiles/deltamethrin.svg]]


According to [[https://haz-map.com/Agents/7834][HazMap]]:

#+begin_quote
A skin, eye, and respiratory tract irritant; May cause facial sensation of
tingling, itching, or burning; [ICSC] A severe irritant; Can be absorbed through
skin; May cause skin and respiratory sensitization after prolonged contact;
Effects in high-dose animal studies include convulsions; [MSDSonline] See
"Cypermethrin."

Other CNS neurotoxin

Hepatoxic (a) from occupational exposure (secondary effect) or (b) in animal studies or in humans after ingestion
#+end_quote

*** Personal Notes on this chemical

#+begin_quote
The chemical is probably not that bad, but can present a hazard in sensitive
people -- "chemopaths" or chemophobes, depending on how you think about it.

This chemical absolutely effects me when I come into contact with it. I have
exercised great care to remove it from my environment where I could by mopping
with gloves and a mask, throwing the towels & cleaning materials away. It is
insoluble in pretty much everything by design and must be soaked into cloth to
be removed.

I directed the person to not apply the chemical to certain areas and they
agreed, but there was already a few years of application. It seems to be cleaned
up. IDK, I am paranoid about it because there seems to be something in the
environment at home that causes me to feel like shit.
#+end_quote

Pubchem references studies from 1979 on rats that absolutely mesh with my
personal experience -- general somnulence, feeling STUPID AS HELL, sudden onset of
weeks/months of depression after cleaning out my garage/workshop area in
Feb/March 2020. I had already been socially isolated worse than 95% of people
were during coronavirus since 2015, SO IT WAS ABSOLUTELY NOT CORONAVIRUS.

#+begin_quote
BEHAVIORAL: SOMNOLENCE (GENERAL DEPRESSED ACTIVITY); BEHAVIORAL: CONVULSIONS OR
EFFECT ON SEIZURE THRESHOLD; GASTROINTESTINAL: CHANGES IN STRUCTURE OR FUNCTION
OF SALIVARY GLANDS
#+end_quote

Furthermore, I've experienced the warming/tingling sensations on contact.



* Polycyclic Aromatic Hydrocarbons

I don't even know what the fuck these are, but goddammit why the fuck is it so
hard to obtain information on household contaminants. Analyzing household dust
with GS/MS costs $500 per sample.

FIVE HUNDRED FUCKING DOLLARS PER SAMPLE ON A HUNCH. The government & health care
payers would save endless amounts of money if sources of contamination were
identified in a home _before_ decades of exposure occur.

Literally everything that motivates government to ban recreational drug use can
also be caused by casual exposure to contaminants/toxins in the environment, but
there is zero awareness of this stuff. ZERO.

It's not my fault that it's bad for business. Either address it NOW, or wait
until computational chemistry/medicine exposes it all /simultaneously/. IT'S
YOUR MOVE, CORPOS.

** [[https://pubchem.ncbi.nlm.nih.gov/compound/2336][Benzo[a]pyrine]]

Causes Chimney Sweeps' Carcinoma, a type of lung cancer recognized as being
caused by soot (in the EIGHTEENTH century)

#+begin_src smiles :tangle no :file ./img/smiles/benzoapyrine.svg :results file
C1=CC=C2C3=C4C(=CC2=C1)C=CC5=C4C(=CC=C5)C=C3
#+end_src

#+RESULTS:
[[file:./img/smiles/benzoapyrine.svg]]

* Pesticides
