:PROPERTIES:
:ID:       b73246f1-13d1-4db6-8d87-3c10e14161e3
:END:
#+TITLE: Rant: NFC another future past voided by Apple
#+CATEGORY: slips
#+TAGS:

+ [[id:efe1d534-a5e8-4929-afa8-778bc5ded253][NFC]]

Don't get me wrong, I love Apple. They have great engineering and they are
overall a force for good.

* Apple the good and the bad

The many things they do very well are far outweighed
by their faults (some of which are egregious). Some examples:

+ You can't release some software products on the App store if they include
  GPL/etc dependencies (not sure on the details) ... at least not without
  extensive repackaging. This is why you'll never see apps like Krita (and
  GIMP/gMIC?) on the App Store, whereas you can find them on Android, Microsoft
  and Steam app stores.
  - This is a result of opinionated decisions they've made in their operating
    systems and platforms. Perhaps the result of being a BSD derivative and
    perhaps for technical reasons involving how software binaries may be
    modified to make avaialable as bundles on the App Store.
  - For many decisions like these, Apple has fair reasons for doing such. In
    other words, their walled garden comes with benefits, but doesn't function
    well if they don't specific aspects of software/hardware to control.
+ Apple integration with non-apple products is pretty bad
  - You can't easily import/export data to/from Apple products
  - You can't simply work with objects on your phone (photos, downloads, app
    content) as though they are files without some extra layer. You can get
    around these things ... but that's besides the point.
  - The main problem with this, besides inconvenience, is vendor lock in.
    - i'm unsure of whether I can even access iCloud outside of my iphone right
      now. If arbitrary limitations like these change, then _I am quite often
      unaware for years at a time._ Partly social isolation, partly lacking
      initiative to constantly check if it's changed.
  - A benefit of their opinionated policies on integration:
    - your data is actually private and probably will remain so.
    - what goes in their walled garden tends to stay in their walled garden.

Apple does privacy very well. Hardware very well. Creativity very well.

How guilty should I feel for having opinions? lulz

* Apple and NFC

NFC is another tech where apple's decisions affected consumer adoption, thus
forever changing history. They simply would not adopt it like everyone else did
and unfortunately, Apple's customers quite often decide what will be and what
will not be.

** Secure Simple Pairing (SSP)

NFC is another tech where apple's decisions affected consumer adoption, thus
forever changing history.

I had this idea back in ~2015ish for a IoT configuration flow. It would be
"sneaker-net", require no network connection, include things like
hashing/keys/certs for verification of authentication and allow simple
configuration updates via NFC.

... Well it turns out that this idea is at least as old as Bluetooth 2.1:

+ See 2011 [[https://www.ellisys.com/technology/een_bt07.pdf][Ellisys: Secure Simple Pairing Explained]]

** Why we can't have nice things

I have seen an awful lot of devices where physical buttons are removed to make
it seem sleek and sexy? (probably to reduce costs? i guess?) ... I have never
seen a device in the 10+ years that SSP has existed that offers this capability.

You want to know why? When Google/Android adopted NFC, Apple dragged their feet
and perhaps even kicked and screamed. It is speculative to be sure, but this is
probably so they could exert more control in the design, implementation, &
negotiation of payment methods for their Apple Wallet... So they can take a cut
of purchases (i.e. offer a digital debit card) and sell you credit cards and
.... dominate the mobile device digital payments space.


** What probably never will be

So, we could have bluetooth devices integrated with NFC/RFID so that you can put
them into a pairing mode (push a button) and bring your phone close to begin the
authentication flow.

No one comments on things like this because they just do not see what else could
have existed or how Apple could possibly have the power to derail NFC ... or
what this means for consumers.

Have you ever tried to talk a technophobe into learning to pair bluetooth
headphones?

It is a big deal because no one will /EVER/ go back and fix this. No one will
ever adopt this style of RFID/NFC-based configuration flow. And these voided
futures past are the unintended consequences of some corpo bullshit.

So we could have /secure airgapped configuration/ of IoT devices -- but this
"tech-tree route" of technology development was prematurely aborted. So now
people don't even know something like SSP is possible. The issue here is that
configuring Bluetooth in this way /shapes how the average non-technical person
thinks about what is possible with technology/. They don't know the details, but
they can imagine what is possible because of things they did as a kid to pair
their headphones or authorize file transfers or configure smarthome devices.

But I have never seen this in a single consumer device. it wouldn't surprise me
if TEN YEARS LATER this is how you pair airpods ... but i am socially isolated.
I can literally invent something (in my head) that later ends up being commonly
used -- all while people tell me I'm crazy.

To be clear SSP/Bluetooth would not be used to configure an IoT device, but
something like a cross between a NFC/RFID on a Yubikey with temporary storage
could facility authorization requiring a physical device and physical presence.

But no.
