:PROPERTIES:
:ID:       f6702343-3b9b-4fa8-80b6-2e17b2c2e226
:END:
#+TITLE: Homelab: why does a poormans homelab suck
#+CATEGORY: slips
#+TAGS:  

These are all the things that would instantly boost my programming/tech
productivity by probably 100x while enabling retention of progress:

- vpn
- free build automation
  - distributed builds
- githooks
- platform independence
- non-NFS filesharing
- kubernetes/k3s
  - with volume management that doesn't drive you insane
  - with shared service dependencies ... or not
  - persisted databases ... that don't drive you insane
- private gitlab & sourcegraph
- certificate management
  - that either relies on let's encrypt or doesn't
- 2fa (cert mgmt)
  - dynamic 2fa-validation for ssh
- literally anything with a helm chart
  - which can easily be altered to match a k3s cluster (& its volumes)
  - with declarative configuration ... that doesn't drive you insane
- local package repositories
- reliable SSH/SCP/RSYNC across the network with security & access control
  - thus allowing you to ... not be driven insane
- local guix channel
  - that is shared on my network or via vpn
    - thus NOT driving you insane with file management
- backups
  - did i mention how much i /love/ manually moving files?
- a syncthing portal that is accessible, yet dynamic
  - while also being secure

but no. 3 old rack servers + storage and other requirements? $5000, more or less

i know, i know: i should save up money and buy it, right? well i've always been
capable of doing any of this, but when i worked in programming/tech, i reallllly
got fucked in the ass in my career while everyone know what the fuck was going
on. stood by. watched. practically taped the rape.

and so NO, i have NOT had a 6-figure salary for the last decade. i have averaged
FOUR FIGURES while enduring social alienation, which everyone would pretend to
not understand -- if it weren't that coronavirus killed 1.5 million americans.
that is the only reason that anyone close to me is /forced/ to admit that
"social isolation" might cause problems for someone. i have been told that i use
words with "too many syllables" ... you're damn right i do.
