:PROPERTIES:
:ID:       05be8b65-45ee-4bdd-a7e5-ea4b4bba22e6
:END:
#+TITLE: Rant: the discord problem
#+CATEGORY: slips
#+TAGS:

I don't want to offend anyone here, but discord is just confusing to me. It's
just not the best tool -- other than the simple fact that it has the most users.
IMO, this is plenty enough to support choosing Discord in many situations: it's
a communication tool that people will actually use that facilitates
communication. I wish there were a better tool that was more accessible ... but
no. The only thing that comes to mind is facebook messenger.

Anyways, everything after is a fairly scathing critique of discord. Again: no
offense to anyone. I just wish society was a bit more intentional about the
software/network tools it settles on. We have a lot of problems that stem from
social media and most of the social tools out there are hopelessly broken.

The main problem causing this is that the right tools don't have a business
model. Encouraging usage of apps that turn a profit on wallstreet is
surprisingly easier than encouraging the usage of free/open apps that don't rape
your privacy ... but i digress.

A good altrnative to discord is [[https://zulip.com/][Zulip]].

#+begin_quote
Zulip combines the immediacy of real-time chat with an email threading model.
#+end_quote

And it feels a lot like a light-mode discord.

But it turns out that the single most dominating factor that determines a social
app's app's perceived value, when deciding whether to integrate it into other
processes: the number of users. The value of a network scales with the number of
users ... which is something I would love to argue with, given things like the
scope of damage from a data breach scales with the number of users.

* IRC: a well-defined protocol

irc has the [[https://www.w3.org/Addressing/draft-mirashi-url-irc-01.txt][irc:[ //[ <host>[:<port>] ]/[<target>] [,needpass] ]​]] URL protocol,
which is probably /already registered/ to be recognized by all major operating
systems...

and lets not forget that URL protocol handlers lead to potential security
problems -- AND DISCORD IS CLOSED SOURCE.

+ LOG4J :: THIS WAS AN LDAP URL PROTOCOL HANDLER
+ Microsoft [[https://msrc-blog.microsoft.com/2022/05/30/guidance-for-cve-2022-30190-microsoft-support-diagnostic-tool-vulnerability/][CVE-2022-30190]] :: this was a protocol handler, closed source.

so, lets say, you click on a
=discord://[<host>[:<port>]]/[<channel>]/[context]/[url params]= link: it is
very likely that something related to cached images/media/url in channels --
these things use web requests and the content in mobile/webapps can be spoofed
in the local client's state or cache or in transit.

Why do you think that discord is so cautious about links that you click in
channels? It is unusual that they add this level of UI/UX friction when you are
merely clicking a fucking link. But security is a concern. A =discord://= URL
protocol just makes this worse.

IRC does not have any of these problems because it does one thing and does one
thing well -- chat with text. if you want images to show in an IRC channel, then
you /could theoretically write a client that fetches URLs that look like pics
and render them/. This is an option you have without risking the Discord gods
nuking your account from orbit.


But you can't have shiny things like zomg /custom emojis/ that are not
 =recognized by anyone or any content encoding scheme.

** Why not use IRC?

Because IRC is too hard for the average person. It really is because if you want
a seemless experience, then you want an IRC relay (i.e. an IRC proxy). Then you
connect to the proxy, which doesn't go offline. This way, you can get all the
chat history for channels you care about, among other things.

This is a major usability issue, but it doesn't have to be.

Also, IRC isn't shiny enough for the average person to pay attention. It
theoretically does integrate very well with video streams, yet it doesn't have a
business model.

** But you don't understand: you don't actually want embedded media!

The other reason that people don't use IRC is that it doesn't permit embedded
media.

EMBEDDED MEDIA REPRESENTS A MASSIVE SECURITY RISK, ESPECIALLY IN CLOSED SOURCE
APPLICATIONS.

* Discord: probably something propped up by "silicon valley"


** Discord's UI/UX is terrible

The entire UI/UX is fucked up. I can't imagine using it in a browser -- and
thank god they have an app ... even though the app's performance is probably the
worst part about it right after the UI/UX.

But this is the communication app that the people have demanded. For some
reason, everyone wants a discord server. And i'll admit that, some aspects of
discord fit it's use-cases very well.

The only redeeming aspect of the UI/UX are some hotkey features ... and if you
don't know about them (it's not your fault) then you're going to want to learn
them.

+ You can hit =Ctrl-K= to bring up something like a fuzzy search.
+ There are a few other _cleverly hidden features_ just like this that you
  probably wouldn't know if you're too old to be into things like Tik Tok.

** Well why aren't those features more prominent?

So that people who don't know are crippled in their ability to communicate
quickly? ... hmmmm, nope that's probably not it at all. I'm not really sure

One thing that I do know is that, if Discord were to allow custom clients, then
its users.

The other feature that's not prominent/accessible enough are the notification
histories.

** Don't get me wrong: _tabs are a ui/ux anti-pattern_

I appreciate the bold departure from

But sometimes people would

** Bots, but no clients?

your account will be permanently deleted when it is discovered that you are
using a custom client? REALLY? (yes really)

#+begin_quote
so like you can have /bots?/ ... but not /custom clients?/ ...

yes... really (that's actually real)
#+end_quote

** What Happens On Discord Stays On Discord

At the end of the day, this means that *what happens on discord, stays on
discord*: it doesn't integrate with many tools except the explicit means that
the discord business provides to its users for integrations.

Reddit had similar approaches to how it modulated user creation of content, but
I think the purpose there was more clear to users. So, for example, Reddit
created features/norms that favored high-quality posts and disdained "shitposts"
... this made their content beneficial to SEO. There are other examples of how
reddit influenced user behavior to compel them to create better content that
Reddit owns.

#+begin_quote
Nice post ... Now get back to the content farms and data mines you plebs. And if
you see a shitposter, downvote.
#+end_quote

Unlike Reddit, Discord's decisions/policies here are NOT beneficial for its
users. These policies prevent competition by ensuring that Discord's
monopolization of the users' communication/social networks promote Discord's
competitive advantage. In the end, this will prematurely squeeze out any nascent
competition for any app that resembles Discord ... making it very difficult for
society to adopt an alternative!! /g'dammit/

** I'd wager that as a startup, discord doesn't know what it is

This is a huge problem. It's almost ruined every promising startup that tries to
become the "walmart of the internet" or "the next tiktok" ... stop. You just
aren't that. If you keep trying to be that then your company is why the world
can't have nice things.

So what else were your execs going to tell your board? Your pre/post-IPO
investors?

How does this apply to discord?

+ why can't they settle on things like API versioning and API URL schemes?
  - probably because they don't know what they want
  - or custom clients are at odds with their business model
+ why can't they settle on a =discord://= protocol URL scheme?
  - probably because they don't know what they want
  - or ... i donno

** Discord's Terrible UI/UX can mean just one thing

It is intentional. By not offering tabs, they keep you locked into one set of
interactions at a time. Talk to anyone who's worked on Google Analytics (or
doubleclick) ... tabs disrupt your ability to collect stats. It's hard to
disentangle multiple web page/socket connections sharing a single session.

By locking you into interacting with one thing at a time, discord can measure
your interactions. /YOU ARE BEING WATCHED./ This product is not about you. It is
about observability and measuring trends.

That is why so many other similar options or product offerings exist, but with
one key distinction -- there is almost zero cultural adoption. Who has the deep
pockets needed to afford the marketing that's required? And it's free for most
users

* TLDR: Discord is a dead end

+ It is proprietary. Its users really have no ability to influence it's feature
  set or decide what it is.
+ It does not allow custom clients. I cannot emphasize this point enough. It is
  a bad sign.

The main problem that I have with Discord being a dead end: society could be
collaborating on /something like Discord/ but with better balance the features
that support its use cases:

+ text chat with embedded media
+ simplicity of communication
+ community formation tools
+ automation of processes through bots

i'm not sure who decided on discord. I like it for what it is and I recognize
that it simply is what people use -- you really can't argue with social
momentum, can you? But it is infuriating that society again has "spontaneously"
adopted a tool that will distract us from better solutions.

When people figure out how the discord story ends, then it will ultimately be
become abandoned. But it is a nice cool glass of "at least it's not facebook
messenger" ... it is very nice to have an alternative to that GPS tracker chip.

Yet, discord is not going away any time soon, but that it will never facilitate
the kind of functionality that your average "power user" wants -- but that your
average new user probably doesn't know how to ask for.

** Well how do you know that discord won't change and become more open?

I have a feeling that the following....

+ Discord's /borderline insane/ UI/UX decisions
+ Discord's feature selection and ignored features
+ Discord's bizarre system of server registration that lets discord initially
  masquerade as something free/open
+ Discord's hostility towards custom clients and the users who would dare defy
  them -- /who should clearly have their account history/data nuked from orbit/

... all imply that discord is not going to change the important things. Worse,
it seems that the potential paths available to them to continue problematic
stuff are more likely, while the paths leading away from this stuff are less
worthwhile to their interests.

If i was a betting man, i'd say that someone in discord has a plan and for some
reason, it does not involve custom clients whatsoever.
