:PROPERTIES:
:ID:       58718f56-68e2-4cf6-8fb1-337b605ceae8
:END:
#+TITLE: Idea for a simple sign-in form
#+CATEGORY: slips
#+TAGS:

Requirement: create a simple sign-in form for patrons who frequent a makerspace.
This is different than a one-time event sign-in form or marketing list sign-up
for. It would probably be used dozens of times by most users and should be as
unobtrusive as possible.

* Ideas

** Use a QR Code

On the kiosk that displays the sign-in form, display a QR code that allows the
user to access a google form on their phone.

+ Ideally, submitting the QR code records the time that a form was shown to
  someone (in case the person does not complete the form)
  - which should be generated with the url + an encoded time parameter for
    verification (i.e. the QR code dynamically changes
    but still resolves) then
  - however, this isn't really practical

** Something like Gravatar for faster sign-in

Provide a selection of random-gravatars, so after loading the QR url, frequent
patrons can identify the random image that represents their user.

Gravatars and other systems are hash-based, so =(value) -> (random hash)= can be
reversed -- sometimes with security implications, othertimes this could be used
with purpose.

+ list the top 12 most frequent signins at the top
  - along with some junk data that is interspersed?
  - if their random avatar is not shown
+ people may simply click a random one, defeating the purpose
  - there may be other usuability or practicality issues

** Use an RFID sensor for simple 2FA enrollment

... but not really 2FA. Just a way to uniquely distinguish an individual.

** Use a discord bot

Is there a URL protocol for discord? This could be an option


** Reuse an authentication system

With a typical approach, this would overcomplicate things. it's a PITA to
integrate auth into a webform/system -- not to mention it's sketchy to submit
these details to a app that you can't trust.

** Use an app for sign-in

It's more difficult to distribute the app on Google Play and Iphone than it is
to write the damn thing (provided it is an app that can use API's without
authentication)

** Use a keyfob for signin

This requires setup and many keyfobs may not be returned
