:PROPERTIES:
:ID:       9ca46e04-0343-4939-a5a7-71324de0ee71
:END:
#+TITLE: Git: the cherry pick
#+CATEGORY: slips
#+TAGS:

* Try explaining this to someone who cares

=git cherry-pick= is =git cherry-pick= because it is entirely possible to hang
around by the goal and wait to tap the ball in:

+ simply observe the local branches that some other schmuck from a far-off rural
  city has pushed to remote
+ set up webhooks (and/or local/remote githooks) for the github remote branches
  they are getting ready to pull-request.
+ if you're smart, change a line of code on one of your features (either in
  pullreq or submit one). you're looking for an intersection of changed lines.
  /AGAIN, GIT HAS A COMMAND FOR THIS:/ =git bisect=
+ then simply push back on the pullrequest with a few comments. the more
  superficial your remarks, the better: remember your goal here is to irritate
  the person. whoever is proactive can always act like they never had a problem.
  anything is possible from behind a computer screen.
+ this can push back an accepted pull request for 2 or 3 days, during which that
  developer's local code will diverge more and more from master/develop ...
  which means git bisect returns more results: more options.

SOME SOFTWARE DEVELOPERS ARE LEGITIMATELY EVIL.

I really don't know the origin of the term cherry pick, but this shit is evil.
