:PROPERTIES:
:ID:       496f4e00-95c7-4b1f-8cb7-49e7caecd94e
:END:
#+TITLE: Math: 3d printing tautochrone and brachistochrone curves
#+CATEGORY: slips
#+TAGS:  

* Brachistochrone in emacs-lisp via SVG

Some setup functions

#+begin_src emacs-lisp
;; change to defmacro
(defun svg-parametric (fn)
  ;; (let* (()))
  )

(defun svg-draw-linestrip (svg linestrip)

  )
#+end_src

Render the brachistochrone.

#+begin_src emacs-lisp :results file :file img/hexagram.svg
(let* ((img-file "/data/org/roam/img/slips/math-3d-printing-brachistochrone.svg")
       (total-height 800)
       (total-width 800)
       (curve-width (* 0.95 total width))
       (curve-range-min (* -1 float-pi) float-pi))
  (svg-brachistochrone )

  ....

  )
#+end_src

Render the tautochrone.

* Brachistochrone in python via STL

***** TODO write brachistochrone and tautochrone in python
+ then import into a cad program that doesn't crash when it handles 2D points
  only -- it's kinda ridiculous that the performance needs for 2D are so much
  higher simply because it utilizes underoptimized CPU code for everything
+ mesh treatment for the generated STL in fusion/inventor may be similar (but i
  bet it ends up being quite faster)

* Most CAD Programs can't handle specific parametric curves without distorting them or crashing

honestly, the best way to generate this is probably by generating the STL
directly with python. It only requires managing a set of points:

-

+ Inventor refuses to handle brachistochrone curve
  - parametric results are invalid for most domains/ranges
    - you have to hack it into generating the curve, then mirroring

+ Fusion and inventor distort parametric curve results when closing the curve
  - performance is decent, but

+ Fusion and inventor distort curve when converting it to Bezier objects
  - the curves are not anchored to the edge points. adding more points increases
    accuracy at the expense of performance.

+ FreeCAD parametric extension generates something wierd
  - not easy to integrate into other FreeCAD objects/workbenches
  - i still don't know the FreeCAD workbenches/workflow/GUI

*** TODO validate FreeCAD brachistochron precision (via extension and python)

*** TODO refactor to a zettelkasten slip

* Roam
+ [[id:a24b12f8-b3e3-4f66-9a5c-f29b715e1506][Math]]
