:PROPERTIES:
:ID:       4ce355fe-7c2b-4096-a44b-5daeebcd4b66
:END:
#+TITLE: Math: apollonean gaskets and number theory
#+CATEGORY: slips
#+TAGS:



Three circles generate an apollonean gasket, though this the minimal
representation. In any gasket where four circles having integral radius touch,
all circles will have an integer radius.

* Flower of Life

+ The flower of life generates [overlapping] apollonean gaskets
  with fractal relationships. This gasket can be tiled.
  - Here there are 3 lines, each cutting the largest circle in half.
  - The ratios of the next smallest circles are all integral, but it makes more
    sense to consider them to be rational ratios (there are 7)
    - For each adjacent pair of these 6 outer circles, their centers form an
      equilateral triangle with the center circle.
  - For the apollonean circles in the interior, their radii are rational (need
    to check to be sure), but their positions relative to the centers of the
    initial circles are algebraic.
    - specifically, the positions are drawn from specific subgroups of algebraic
      numbers (solutions to polynomials with even terms and max $2^{n}$ terms)
    - this provides relationships between transcendental numbers, rational
      numbers and specific subgroups of algebraic numbers (sums/products of
      2n-roots)

  - ... what are the ratios of the apollonean circles around the outside??
    - if you extend the flower of life to [[https://en.wikipedia.org/wiki/Overlapping_circles_grid#Progressions][19 circles]]? ()

* "Kissing Mesh"

Connecting all the points where the circles kiss gives a mesh.
+ Effectively a visualization of relationships between transcendental numbers,
  algebraic numbers, rationals and integers

What is the significance of the relative ratios of circles?

* Hyperbolic Gaskets

+ Do the $2^{n}$ algebraic subgroups result from the L2 norm? (i.e. the distance
formula).
 - If all this holds, then what does this mean for hyperbolic gaskets?
 - Does the curvature here permit similar integral gaskets where the relative
   values exhibit some other direct sum of quotients of algebraic numbers?
   - if so, then specific gaskets are like representations of subgroups of
     numbers and provide functional mappings between them.

+ If so, then what does this mean for the relationships b/w pi-derived
  transcendental numbers, algebraic irrationals and rationals?
