:PROPERTIES:
:ID:       edf5fe56-9805-4ddf-ac66-4137b7775dcc
:END:
#+TITLE: Autodesk: running AutoCAD/Inventor in the cloud with GPU
#+CATEGORY: slips
#+TAGS:

+ [[id:6a7b6508-e7cf-4f55-a589-d354cee1766d][CAD]]
+ [[id:c9e5c336-2c1a-4f3d-a88d-977889de182c][Autodesk]]
+ [[id:8a6898ca-2c09-47aa-9a34-a74a78f6f823][Cloud]]

**** TODO go through Azure portal and collect the objects needed

* Resources

+ [[https://colindblog.azurewebsites.net/2021/01/21/w/][Publishing AutoCad with Azure Windows Virtual Desktop]]
+ [[https://robinhobo.com/how-to-deliver-a-gpu-powered-azure-vm-example-for-cad-applications-with-windows-virtual-desktop/][How to deliver a GPU powered Azure VM (e.g. for AutoCAD)]]

* Requirements

** Software (VM)

** Hardware

+ GPU (nvidia)

** Cloud

+ Public IP (static)

** Software (client)

+ Remmina (to RDP from Linux)

* Cost

Probably about $10-15 a month (even with the free account for a developer)

Some estimates:

+ Storage: about $10 for the OS disk
+ VM: about $5/month if your usage is < 48 hours
+ Public IP: about $3/month

* Notes


** Cloud

It's possible to set up a firewall and load-balancing, but the former is
expensive and the latter doesn't seem to work without expensive features.

*** Load Balancing

I had a hard time configuring a port on the firewall to support both TCP/UDP.
This implies that some creating port-mapping is needed. The features available
and how they are set up in the UI/UX imply that my use-case is not so trivial to
configure ... yeh, I'm probably missing something.

*** Firewall

This was just insanely expensive: like $20/day ... for a firewall that wasn't
doing anything. And while I don't know the Azure cloud/interface as well as I'd
like... it wasn't working lol

*** Debugging and Instrumentation

This was a bit complicated to figure out (will result in more time than i'm
willing to invest for this). Running the load balancer or firewall without
intending to set this up from the start is a bit of a lost cause. You absolutely
are going to need it. It takes a bit of time to make the stats available and
you're going to want to have thought about how this data/info will become
available to you *before* you start.

*** Applications

+ Destop Application Groups: cool feature. They require creating a security group (i think?) in order to attach them to a VM. I have one ... so I didn't need them.
