:PROPERTIES:
:ID:       25b53a0c-dac2-4dff-be93-f082db5b7840
:END:
#+TITLE: Linux: Control Over Capital
#+CATEGORY: slips
#+TAGS:

* Roam

+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]

#+begin_quote
2026/7: "yo baby is ugly"... sorry i hate to be so pessimistic. i didn't publish
these for a long time, but... just consider that i'm probably wrong anyways?
...?
#+end_quote

* Rant

The hunger that smaller open source projects face is actually a strong selective
pressure for success. It forces some developers or projects to maximize
efficiency and eliminate what's unnecessary. They focus on exactly what
distinguishes a project/idea.

Linux has this problem: tons of money for Debian/RPM and nothing at all for
NixOS or Guix; plenty of money for MacOS cloning or safe Windows designs, but
almost no tooling left over to ever really support a tiling window manager.
Instead users are left to roll their own Desktop Environment. Meanwhile, there's
little automation in much of the shiny window managers, which is extremely
frustrating for some users. Most distributions are basically indistinguishable,
for better or worse and no one seems to understand they keep reinventing the
wheel, resulting in a combinatorial explosion of projects to integrate other
products.

Examples include:

- flatpak, snaps and some features in VanillaOS. these are good, but require
  many supporting tools to gradually support.

- docker, podman, ostree, rpm-ostree, toolbox

- introducing javascript dependencies to window manager scripting

**** todo: more & better examples. also steelman the need for diversity in design

