:PROPERTIES:
:ID:       af67fbb2-9a95-4ff0-bbf8-c6562ba36a7a
:END:
#+TITLE: GNU: My uniformed opinions
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:286b6d1b-362b-44fe-bb19-e0e78513d615][GNU]]

* fdsa

[[https://drewdevault.com/2023/04/11/2023-04-11-The-FSF-is-dying.html][Broken link to the article]]

The first three points are good, but most of the rest of the article is terrible
advice -- dressed up to sound palatable to people on the periphery. Why does
Drew Devault care so much anyways? Some of the suggestions towards the end sound
good, but would end up dividing the FSF/GNU and open them up to diluting their
ideas.

I don't mean to personalize this towards him, as it's reasonable to be concerned
-- especially since what follows is a rant. If you change out the old guard in
many of these institutions, you will see everything fail. That's not to say that
younger leaders aren't needed, but they would not have the same level of
personal investment and sacrifices.

It's shortsighted to measure the success of some organization's contribution
towards shared goals by gauging whether it's using the same tactics or methods
as other players. I don't know really know much about FSF/GNU politics, but I
would say that if they're adhering to their vision & mission, then it's going to
be tough -- since it's basically a "fuck yourr money" to billions and trillions
of combined marketshare.

There are better ways to use computers more freely. Most of the "open source" or
"FOSS" stuff out there is code pumped out by corporations who were going to
write the software anyways -- but since the knowledge about software systems is
essential to adoption/integration, it's far more valuable for it "open sourced"
than any revenue stream that would preclude it's adoption.

So all we have are shitty browsers that eat 200mb of ram per tab, bleeding
energy. Javascript is horrible for the environment. The browser is a terrible
way to consume/distribute information and it is a terrible way for people to
systematically expose their personal/private data online. We're just lucky that
no totalitarian government has become a hegemon capable of exploiting the
fascist machinery we've built.

FSF/GNU are some of the only people who seem to have been consistent in standing
up to surveillance, for privacy and for choice. And -- are they popular? I
wonder why. When you implicitly don't have a business model (except maybe
contracts/expertise) and you're tinkering with others' business models or policy
directives, then your vocal altruism might leave you a little isolated.

5+ billion people have been indoctrinated to use technology the way they
do and you can't teach an old dog new tricks. Once you engraine usage habits to
that extent, it takes 3+ generations "remake" how people think about UI/UX,
information consumption and technology.

These are a little hyperbolic... but here goes:

+ No one will ever relearn to use social media again.
+ Corps will push wasm to your phone generated by AI and you'll never know.
+ No one will ever ditch HTTP in favor of gopher/gemini.
+ Odysee and Library will die and no one will care.
+ Bitcoin will crash because the state gets to do whatever it wants.
+ We will be penniless and locked out of AI, pitted against each other for the
  right to use it.

No one will ever see the Oculus VR we were promised in 2013. The experiences are
synchronous and complicated, but worst of all the data they generate can't
easily be indexed to serve you ads.

Basically, no one understands what the world is missing because 90% of the "open
source" out there is just some generic crap that's apropos to a corp's business
model.

I really hate to write like this and I don't think it matters. I'm not mad
because I don't expect people to care and I'm not even informed enough to have
an opinion. You need many groups to work together /by different means/ in order
to create the possibility for freedom in technology. The correct answer is a
superposition of strategies/organizations.
