:PROPERTIES:
:ID:       f541e274-0691-472d-8e93-62599b549123
:END:
#+TITLE: On Autocomplete and Cybernetics
#+CATEGORY: slips
#+TAGS: philosophy

Ultimately, any sufficiently advanced autocomplete cannot be distinguished
from Github Co-Pilot.  If you don't understand how much you depend on it, try
going without it and see how much "original" code you produce.

From the perspective of cybernetics, autocomplete is just a signal inducing
you to create content.  The magnitude of influence lies along a spectrum.  If
your content is not identical without autocomplete or is not produced with
the same rhythm/style, then you are affected by that signal.  Whether VSCode
with LSP on corporate docker or dabbrev or Github co-pilot: this is simply a
change in cybernetic signal source, albeit qualitatively different in various
modes; ethical consequence being one such mode.  If the context is music and
the cybernetic signal source is a bassline, the jass soloist is being
modulated by the signal and would prefer better inspiration.  There are
obviously qualities in the music produced compared with the source signal
that would indicate originality and novelty.

How is signal modulation distintuished from correlation? Where is the signal
modulation complexity burden found with completion systems/interfaces? In the
user processing a popup with docs? Or in the asynchronous background tasks:
rtags, *tags, LSP, eglot? When someone doesn't independantly modulate a
signal, it modulates them.  In the extreme, this is the inversion of Kantian
transcendentalism that causes the machinic to construct the human's interface
to the unconscious.

As for computer science, if you are good, then your code (judged as a work of
computer science) may be original, but it is never novel.  See Donald Knuth's
series...

Goddamit I philosophied again.  It's really just a particular kind of
ego-gynmastics.
