:PROPERTIES:
:ID:       f0bd1231-44c0-4d9c-ad5b-5581d112ceb4
:END:
#+TITLE: Being a tryhard is actually a virtue and should not be excruciating
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:a0ef7bfe-1587-4fec-ac87-f7dda5dc0d27][Maths: Statistics]]
+ [[id:beafc05d-75b4-4013-8b43-9c0483a30328][Art]]


* Notes

Art is so relatable, since most people have two eyes and manage to make some
sense out of the photons that hit their retinas.

It's actually pretty hard for them to not try to make sense of what they're
seeing. But with tech/computers, they believe they can't understand, so they
never try and actually actively avoid thinking about it. But put some colors in
front of their eyeballs and suddenly they pretend to try to understand (since
experience/sensing doesn't require conscious thought).

But they did burn half of [[http://www.thebestpageintheuniverse.net/c.cgi?u=irule2][Van Gogh's art]] though.

And almost all of the value in the Higher Education system is so that less
educated people can reason epistemologically about things they don't understand
-- typically to make hiring/firing decisions, but also conveniently to tell
themselves and other people that there's no reason to care about what's coming
out of your mouth since you're using too many syllables.

Pictures? They don't get indexed on search and they don't have syllables.

Anyways, earlier today when I wasn't so frustrated, I was learning about
Gaussian processes. At the moment, I really couldn't even remember the formula
for a Gaussian -- yeh, that's terrible, but what you need to understand is that
there is something undeveloped in my mind. I'll never forget how to calculate
the Jacobian on a field, since I actually had the time to complete a programming
project instead of getting stuck on boilerplate. What would actually help is if
someone worked with me one on one or if I was somehow allowed to continuously
invest time on programming involving math. Preferably somewhere besides "Area
51" or whatever social desert I inhabit when I am programming.

Anyways, to develop intuition, I needed to determine what constraints there were
on the mean vector components as you change some of them. So determining what
the valid transformations on these Gaussians made sense: you can translate,
scale and rotate them. This provides a natural connection to Geometric Algebra
(which I only have a shallow appreciation of), but then I realized I was
basically thinking about Information Geometry. I checked and yep, that's what it
is, although typically you use Lie Algebra methods on the statistical
manifolds. So now I have a bit more intuition for GP, GA and IG.

[[https://www.youtube.com/watch?v=elSmfwHNTRc&t=920s][Fisher Information Geometry of Beta and Dirichley Distributions]]

However, another was that in most contexts where you have these Lie Algebra
methods, there should be the alternate methods from Geom. Algebra available,
which utilize composition of operations and typically involve Clifford Algebra.

It turns out that, yes, this may be a valid insight as well. These are not novel
ideas, but they are original.

[[https://arxiv.org/pdf/1701.02549.pdf][Geometric Algebra and Information Geometry for Quantum Computational Software]]

I'm so sorry for trying so hard to make something of myself. I'm so sorry that
it's inconvenient to more people for my life/identity to not be forgotten. I am
so fucking sorry for existing.
