:PROPERTIES:
:ID:       48fe83f9-f48f-4e5b-8dc7-087b93c865c4
:END:
#+TITLE: Fedora: Trying Out Sericea The Immutable Sway Spin
#+CATEGORY: slips
#+TAGS:

* Docs
+ [[https://docs.fedoraproject.org/en-US/fedora-sericea/reading-and-resources/][Reading/Resources]]

* Resources

* Senicea

** Components

*** OS Tree

=ostree= exposes access to files through a layered, diff-based system where
changes are composed from layers into a final blob.

=rpm-ostree= uses ostree to deliver packages

=flatpak= also uses ostree to deliver applications as packages.

There are many potential uses for =ostree=, beyond packages and their
distribution.

*** Display Manager

The Fedora 39 version of Sericea is xorgless (info [[https://fedoraproject.org/wiki/Changes/sericea-xorgless][here]]), but it's in beta.

** Installation

+ don't use groups in install, extra steps are required for useradd -aG
+ ensure disks are set up to mount /var/home/me when needed (installer won't prevent)
+ use the English (US) keyboard or French (intl deadkeys) keyboard.
+ the US algr deadkeys keyboard will screw up login

** Initial Configuration

Copy over .ssh and .config/xkb directories.

Run =systemctl enable sshd && systemctl start sshd=

Reload sway config, test keyboard

** RPM OS Tree

The very first thing you need to do is:

#+begin_src
rpm-ostree update
#+end_src

And reboot

Then add the RPM Fusion Repositories

#+begin_src sh :tangle ~/.bin/install-rpm-fusion :shebang /bin/bash
rpmfree=https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
rpmnonfree=https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo rpm-ostree install $rpmfree $rpmnonfree
#+end_src

And reboot: you must reboot before changes are effective when rpm-ostree
updates.  To apply changes to the live environment use:

=rpm-ostree install --apply-live=

But you'll need to propagate those changes to the immutable image. The point is
to not use the host system and use container-based tools only.

These packages add new layers onto the base rpm-ostree.

#+begin_src sh
rpm-ostree install alacritty emacs
#+end_src

*** Emacs

Version =29.1= is available from Fedora RPM's.

Install with =rpm-ostree install emacs=. Keep it vanilla.

*** Updating

Look for "rebase" instructions in the =rpm-ostree= cheatsheet.  You must rebase,
but this command from the RPM OSTree docs is maybe not current


** Toolbox

Run =toolbox create=. Enter a project and run =toolbox enter=

** Flatpak


* Roam

+ [[id:ca4acf9b-775b-4957-b19a-0988b7f429c5][RPM]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]
