:PROPERTIES:
:ID:       5eb6e1d1-7672-4a1b-9a1d-14114ed70c62
:END:
#+TITLE: Canvas LMS: Lacks Markdown
#+CATEGORY: slips
#+TAGS:

#+begin_quote
2026/7 well this didn't age too badly, but is also largely irrelevant as you
basically have no option but to use markdown now... and also any potential
security issues related to markdown (which are legitimate) are also apparently
moot. bc LLM, I think?

i was really going to do this with pandoc lol
#+end_quote

i otherwise really like your product, but it's unbelievable that it doesn't have
a markdown editor by default. it's impossible to gain enough support to convince
IT to adopt a 3rd party plugin when everyone's paranoid about ransomware. I've
looked into the Canvas API and I've watched videos, but maybe there's an obvious
solution that I'm not aware of.

in any K-12 school system, any community college system (where IT is managed
from the state capital) or most universities, unless there are enough users who
ask about it, IT will just default to saying no. Each year, you basically have
one real chance to request changes to Canvas defaults/plugins. Unless people are
asking for it, it won't be installed. It should definitely be a first-party
extension, where Markdown is offered without any other dynamic content
generation, which maybe could be provided by 3rd party plugins.

as soon as teachers and faculty see "Markdown" in the dropdown, they will use
it. it can convert to PDF if you're worried about user behavior resulting in
impaired analytics.

for me, i worked as a FWS in a STEM facility with lots of manufacturing
equipment, but collecting and converting the documentation is prohibitively
difficult in the WYSIWIG editor. It's possible to convert to HTML from
Markdown/Org, but then the content gets out of sync. someone edits it in canvas
and then I need pandoc to edit it quickly. i can handle that, but it's tedious.

i would need to use canvas for a wiki is because (1) it's integrated with
authentication/authorization (2) roles/policies can be enforced for
students/faculty who edit/view the content

this functionality is already bundled in to canvas and offers a starting point.
any other possibility requiring a server like Mattermost or MkDocs will face
impediments (1) if they require network customization and firewalls (2) if they
need to be vetted for security and updated (3) if it ever seems like you're
going to request Canvas API or Single-Sign On access.

for smaller projects with about 20 students (extracurricular) you need to be
*agile* and you need to leverage the contributions of the group, so the more
passionate people feel like they are building/changing something. this is
somewhat possible with Canvas courses for clubs ... but the WYZIWIG editor is a
show-stopper.

as a FWS, i just didn't have the authority to do much other than to ask for
it. the college system IT was headquartered 3 hours away. they always responded
quickly to whatever I asked for, but it was going to be difficult to even
explore adding a plugin (3-6 months of waiting time)
