:PROPERTIES:
:ID:       26f80410-ed2f-4a89-bc00-edd01abe83f9
:END:
#+TITLE: Social Physics: Zero is a very lonely number
#+CATEGORY: slips
#+TAGS:

I could really use a lot of help, but I would begin to change my outlook on this
if specific events occured ... like, for example, I pair with another programmer
or collaborate seriously on a project with other people.

Not a single person has really worked with me on a "for fun" or "for startup"
project ... I don't think ever. Connection like this is much easier to obtain
when you're young or you live in a city. I guess I complain a lot about it, but
if people really understood or listened, then they would be more available to
help. The older people are, the less social valence they have for things like
this. My social skills have long atrophied and it doesn't help that everything
I've been through has amplified an attachment disorder.

There are people I know who develop/hack, but I just don't know how to
connect. From ~2016 through 2021, I could've attended several meetup groups in
the area ... but I just didn't. It's really the confluence of several factors:

+ unconfigured or misconfigured notifications
+ simply forgetting until literally the next day
+ not having transportation
+ not having social media or being essentially zeroed out of social media

And a severely diminished, almost zero probability that someone from a group
would think of mentioning it to me ... mostly because I'm not emotionally
relevant to anyone. that's not because people don't like me or whatever
... rather it's because i'm never on anyone's mind. People mean well and I think
really would try to help ... but I don't know what to do.

This results in something worse than a "diffusion of responsibility" -- the
situation where many people assume that many other people intervene or handle
something. Here, it's a kind of diffusion of responsibility where I'm not
actually on anyone's radar.

People, generally, also don't really understand that zero in social physics is
really like a black hole. Network effects are multiplicative, which means that
they either compound in magnitute exponentially:

+ either dynamics compound in magnitude for your benefit/detriment
+ or that it requires a minimal or maximal amount of effort to
  influence/counteract them.

Some of the first things you learn when programming graphs:

+ Isolated subgraphs can be handled separately. Edges can be removed if you
  apply a threshold to the graph, which may separate it into subgraphs.
+ Nodes with one edge can be truncated to a loop on the edge they connect to.
+ Chains of nodes with only =2= edges can be truncated to a path between nodes
  having =3+= nodes.

This is analogous to the effect that an extremely limited social neighborhood
has on a person's options. Here, the social graph permits information to flow
and when it's flow is restricted in the extreme (because of a lack of edges),
then you get ZERO INFORMATION. Worse, there are no experiences of you imprinted
on others' minds. If you respond to this by becoming emotionally unstable, then
the majority of the minimal impact you have on other people -- how they remember
you, feel about you -- it's dominated by negative residue.

People are now talking about "men being isolated/etc" ... but I really don't
think they understand. The problem with social issues is that by the time you
notice there's something wrong, it takes exponentially more effort to correct
it.

EXPONENTIAL. MULTIPLICATIVE. THESE ARE /NETWORK EFFECTS/.

And it's not just "men" or whatever. The way all people socialize has
fundamentally changed. This is espeically true in specific age demographics, but
not everyone is vulnerable. However, the more time that passes, the more that
dissonance/imbalance accumulates throughout the social network. It takes an
exponential amount of effort to correct this.

However, what people should fear are nihilistic responses to these sociophysical
problems becoming systemic. Analyzing these problems can be done in extremely
rational/objective ways. Hence, the cold/distant tone above: it's just
math. People are mathematically fucked. You can quickly develop a very
rationally articulated worldview that quantifies the hopelessness of such
situations. When the causes to emotional instability or depression or whatever
are mostly in how you choose to subjectively process information, it's pretty
easy to simply think "what if it's /not/ like that or /not so bad?/" Here, once
you understand, you do have some measure of control to respond ... but in the
extreme, zero in social physics is better understood as being /like/ infinity,
since it requires so much investment of effort/energy to produce any real
change.

* Roam
+ [[id:01ace2d7-1324-4dd2-9e2e-d5c152fdc378][Social Physics]]
