:PROPERTIES:
:ID:       eb560b9c-8775-4019-bd8a-cac0a1b2d1e7
:END:
#+TITLE: Tony Smith: Taixuanjing and Uwuu physics
#+CATEGORY: slips
#+DESCRIPTION:
#+TAGS:

* Roam
+ [[id:01f7dc95-2246-4871-af7c-b9cdfc248a01][Iching]]

* Geocities: Long Live Geocities!

So my boy Tony here, he links to a page from Al Gore's internet on the [[https://web.archive.org/web/20000619130516/https://www.angelfire.com/nm/videntes/Lattice.html][I Ching
Lattice]] (last online: Sept 2000)

#+begin_quote
... That's from back when the internet was functional. Web pages only really
load like 5x as fast today despite literally 1000x the bandwidth...

Since a website and its javascript open about a hundred TCP/IP and TLS
connections anytime you click a damn thing.

I'm serious. I remember the dial-up sound. There is basically no difference
between bloated angular/react apps and dialup.
#+end_quote

* Whoa is this an episode of Stein's gate?

Behold: the [[https://www.tony5m17h.net/TCZ.html][Truth Quark]]! This Tony guy was calling the Higgs boson mass at 130
GeV in the 90's (it's 125 GeV), which I guess isn't necessarily that forward
thinking since science is way ahead of public consciousness.

#+begin_quote
Spoiler alert! They started on LIGO in 1992.
#+end_quote

And he breaks [[https://www.tony5m17h.net/play456.html][down the E8 lattice]] for you. In raw-ass Tim-Berners Lee HTML.

[[https://www.tony5m17h.net/d4d5e6hist.html][VoDou Physics and the 130GeV Truth Quark]]

* Okay, I'm done.

Not sure how often this site gets updated, but I hope it's in the arctic seed
vault ... you know, in case ([[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiGuNTt-Lz-AhWQEFkFHTVaCvYQFnoECBMQAQ&url=https%3A%2F%2Fwww.imdb.com%2Ftitle%2Ftt11286314%2F&usg=AOvVaw2cFAaIyYRvJNPDKGjKnJ1t][Don't Look Up]]) we have no netflix once the
"asteroid" hits and we can't get much on our crappy shortwave/satellite
internet.

Seriously, actually grokking half the shit on this site is like the
epistemological equivalent to smoking DMT.
