:PROPERTIES:
:ID:       204f3021-f469-43e4-9326-3cb056b93e31
:END:
#+TITLE: Stronger Skills: More Independence
#+CATEGORY: slips
#+TAGS:

This doesn't really have anything to do with Scala's tooling. Also, it's kinda
weak to complain when you use alternative editors, platforms and distros. I'm
not complaining, but trying to justify spending so much time here ... and on
python's LSP tooling.

* Notes on Tooling

Given that the scala tooling is so automagical for VSCode, there's basically no
discussion on how to use it outside of that setting, so details like "tmp
access" are rather left to the JVM Greybeards ...

Getting this to work natively on Arch /should/ be as simple as =yay -Syu scala
sbt metals=. Not only does that approach not work for Guix, but it also leaves
=randomlang= tooling around my environment. Doing things "the hard way" --
i.e. the "correct" way -- works much better for me, since I actually learn what
the fuck my computer is doing. Generally, if you're dependent on the "automagic"
tooling, then when you're actually employed to work with the language, one of
these will happen:

+ you'll look inexperienced (but you'll have time to adjust) and you may lack
  essential tools like "LSP" and "reproducibility" while you spend the first
  weeks of your job fumbling around with the tools you said you had experience
  with.
+ you'll depend on other people being nice enough to teach you (which they may
  mysteriously decide not to, while appending it to the list of 20 reasons to
  fire you)
+ you'll either learn to configure your language/project using the 12-Factor
  approach or you'll be unable to anticipate problems related to
  deployment/infrastructure

TL;DR: it basically comes down to how nice people are and whether anyone will
get you mobbed on the basis that "You vote wrong" -- i.e. you're a
conservative. So you can either deal with that or you can spend time in the
wrong hyperbolic chamber trying to upskill yourself the slow way.

#+begin_quote
This exact situation hasn't really happened to me, but back then AFAIK it seemed
like a much more forgivable political environment (compared to
2015-2022). Things are better now ... but hey, it's almost an election year.

The problems you can encounter are already sufficiently alienating with a single
manipulative person encouraging others to mob you. While I can only think of one
or two people that might have had a sufficiently political motive, imagine what
could happen when it's multiple people.

... So then, it basically comes down to how many social chips you have at the
table. Almost none? Well, then the multiplicative effect that social networks
have can realllly zero you out. It really helps when you start a job and people
around you legitimately try to help. As soon as there is consensus forming that
you /may/ not be there anymore, this itself is an existential factor that
strongly distorts behavior. Once that consensus has solidified, it's very
difficult to stand for yourself, especially if your natural disposition is
introverted without a recent history of social/career connections.
#+end_quote

* Roam
+ [[id:6f769bd4-6f54-4da7-a329-8cf5226128c9][Emacs]]
