:PROPERTIES:
:ID:       f541e274-0691-472d-8e93-62599b54abcd
:END:
#+TITLE: Subcultures, Population and Critical Mass
#+CATEGORY: slips
#+TAGS: sociology


Both the general population density and the frequency of encountering others
involved in a subculture are essential for determining how fast a subculture
will grow or whether it will slowly wither. I failed a lot when trying to grow a
jamskating team. For subcultures to grow, you need to increase the number of
people who can share knowledge/experience, enrich the time/experiences of
interactions or increase the free energy (money) introduced into the system.

In chemical reactions, energy and temperature are essential for overcoming free
energy barriers which electrochemically separate atoms. To increase temperature
is to increase the frequency of potential interactions. You could increase
concentrations of some chemicals in solution and reaction rates won't respond
unless endothermal energy needs are met.  People who have transportation issues
in an area are "less soluble" and cannot readily participate in various
events/interactions.

Even with large numbers of people, knowledge exchange may not occur --
Blacksburg is, in some respects, an example of this. There are tons of
Engineering students, but few meetup groups. Why? Because the students are busy
with class and their affinity for extra engagement in those subjects is
low. Their valence w.r.t. that subject is closed off and, if not, then there are
likely school events that aren't advertised to the outside. There is less
appetite remaining for it -- thus, the pop. density and encounter frequency
dynamics dominate the "reactions".

For subculture growth, the amount of development that can occur is ultimately
bounded by the sizes of the population with valence/appetite for the subculture
and that of the general population. The free energy introduced can do very
little about that. The internet helps ... but a general population who doesn't
methodically approach networking or subculture growth by specifically seeking
outside help will remain unconscious to those possibilities.

#+begin_quote
To be fair, I haven't attended as many meetups/etc in Roanoke as I should
have. I wouldn't want this to be taken as complaining. My life just kinda sucks
and I've never been able to drive in Roanoke. I can't get jobs here because, in
the past, the technologies have just been depressing: jQuery, PHP, Wordpress,
etc. So I get stuck in an area with low population density, great traffic and no
car.
#+end_quote
