:PROPERTIES:
:ID:       fec4d42f-6ea5-4318-86d9-b01a25559b66
:END:
#+TITLE: Finance: Correlation Between Energy, Cloud Pricing and Fundamentals
#+CATEGORY: slips
#+TAGS:
* Roam
+ [[id:8a6898ca-2c09-47aa-9a34-a74a78f6f823][Cloud]]
+ [[id:fecf9468-ffb8-4f9d-9816-b10568c5afe8][Finance]]

I learned a thing today: various revenue streams contributing to financials for
Amazon, Google and Microsoft should show lagged correlation with the tech-heavy
S&P500.

+ Stonks go up? Cloud budgets go up.
+ Stonks go down?  Cloud budgets are attended to.
+ Cloud Pricing goes up? =¯\_(ツ)_/¯= i'm not sure the bourgeois corporate
  check-writing class is paying attention.
+ Energy sees longterm rise? Lagging correlation following cloud product pricing
  changes, depending on the exchange and probably forex.

Those are my working hypotheses anyways. It's unclear how significant these
are. Corporations can't turn on a dime, but it should be at least one set of
useful measures if you're a long-term fundamentals trader. Determining how
functionally necessary the cloud products are to smaller S&P 500 players is less
clear than how essential the cloud revenue is for each of FAANG/MAMAA. They
should be backtestable hypotheses.

It is also less clear how changes to compute technology & network/tech
architecture would affect this dynamic in the long term. I'm not sure either way
... If a general reaction to AI results in increased focus on customer/partner
retention to benefit from exclusivity in social networks (and more critically
the data they generate), then there may be a return to hybrid/onprem. There are
other technological factors that would constructively interfere with this
dynamic ... and others that negate it. +100 Gb/s must be local and when
bandwidth isn't enough, you want to reduce network hops and flatten out
containers/VM's. The devops tooling around this should improve.

But, aversion to complexity is a cultural universal ... so it's just easier to
make hosting/platform someone else's problem. You are partly paying to have
someone to blame for problems or encourage for solutions. Also, you benefit from
economic specialization. However, if IoT or AR/VR are to take off, there's a
huge skills gap clear anyways
