:PROPERTIES:
:ID:       6e4869fa-902b-4cbe-90e8-f183339b9d19
:END:
#+TITLE: FUD: Ransomware, COVID and the Marxist Dialectic
#+CATEGORY: slips
#+TAGS:

IMO, one of the worst implications of ransomware: it creates F.U.D. that
restricts public education, healthcare or government services from flexibility
in adopting new technologies or experimenting with simpler options. This greatly
increases operational costs while preventing organizations from discovering
cheaper/simpler ways to conduct business, an opportunity cost. However, the
"operational costs" don't really increase, per se, since budget allocations grow
mostly linearly for departments/organizations unless resources are shifted --
this is why you hear people say "if you don't spend the money, they'll give you
less next year." Yet, if you have a limited budget that doesn't change and the
_rates & efficiencies_ at which work is done deteriorate from F.U.D or service
disruptions, then the size of the budget doesn't matter because it affords you
less gain from the personnel you pay.

The F.U.D. is maybe a first or second-order consequence of ransomware, but it's
occuring at a time when new tech possibilities exist and when COVID created a
need to change. So the next orders of consequences include:

+ Vendor lock-in to some extent. You don't want to change what works.
+ You've spent a ton of money adapting to remote work and employee,
  administration & customer appetite for change or remote tech is
  exhausted. Another example: implementing different MFA methods has been
  confusing for some and cycling new MFA methods into policy exhausts people's
  appetite for change. Now that security keys could provide better solutions,
  users are hesitent to adopt something new over what they've adjusted to.
+ Once a culture adjusts their expectations of how new technologies should be
  used, it tends to become a bit cemented in the cultural consciousness.
  e.g. people quickly create an idea of what social media is in their heads, but
  don't necessarily revisit how they think about it. So the first change is
  fairly simple once you get people to adapt, but then norms over usage or
  possibilities are established and the next cycles of change can be slow or
  long and sporatic.

** Systematic Application of Marxist Dialect

So while things like ransomware don't seem immediately related to COVID, there
are some key points:

+ Vendor lock-in creates frustration and anxiety while reducing choice.
+ Societies with capitalism and free markets have too much confidence in
  low-resolution quantitative measures like the size of budgets. If more
  functional measures or qualitative aspects of efficiency/quality are not
  prominent -- like, say, when there's a pandemic and people don't interact
  socially 20+ months -- then can disorient decision makers while creating
  dissonance/disharmony.
+ Attacking hospitals to hold their records hostage allows an adversary to
  validate coverage of COVID in American or Western media. Seizing the data can
  allow them to predict your responses by datamining to compare the "norm" for
  budget expenditures to more recent changes in response to COVID.
+ The gridlock and general political atmosphere undermines the public's faith in
  leadership. Disoriented leadership can't rely on any previous yardstick to
  back decisions with data.
+ COVID created massive need for policy intervention incentivization of economic
  participants, leading to large fluctuations in cash flows -- but also
  disruptions in how money stimulates social/economic behavior. When electrons
  flow in a solution, positively charged ions flow in the opposite directon:
  here, the electrons represent the cash and the ions the changes to
  social/economic productivity that money can incentivize. So paradoxically,
  there was rapid change and stagnation, potential economic disaster and
  apparent financial relief. Read George Simmel.

The economic aspects the above /seem/ typical of how Chinese/Russian communists
& leftists approach [[https://www.youtube.com/watch?v=xmNfUUFAclw][beating the capitalists over their head with their own shoe]].
All so in the end, they get to say "it was like that because the greedy
capitalists did X and Y."

Sure this sounds a bit presumptuous. Still aren't sure the argument is worth
considering further? The "ransom" in ransomwhere creates an artificial fixation
on money by placing an organization between Scilla and Carybdis. They must
choose between:

+ scrambling to recover while their network is actively under attack.
+ paying someone they can't even trust to halt further embarassment or
  exploitation.

Never turn your back on a threat. Look them in the eyes, but watch their toes
and hips. The head leads the body, the hips convey intent to invest
power/followthrough, but the real motion starts in the toes. Many of these
actors are proxies for Fancy Bear or GRU or [[https://en.wikipedia.org/wiki/SMERSH#In_popular_culture][SMERSH]]. The proxies may financially
motivate patsies, but if these actions are delegated from state actors with an
ideological axe to grind, then yeh, they probably don't care about money.

#+begin_quote
Every two weeks during 2020, it seemed that some new problem emerged that
multiplied the scale of COVID consequences. And by the way, fuck you CNN CEO
Jeff Zucker.
#+end_quote

The effective strategies that are shaped by the systematic application of
marxist dialectic and dialectical materialism will plan to move through the
present and near future with the intent to rewrite history from the later
future. So they manipulate free market systems or free/democratic institutions
from the shadows to create systemic stressors whose effects *multiply* while
coupling it with elements of narratives that don't make sense in the current
moment, but will absolutely be relevant when the rewrite history.

For each order of higher-order effects (see their dependency graph), the
increased complexity makes attribution difficult (see approaches for modeling
causal assumptions in AI). So even if you diagnose it, neither can you convince
people it's happening nor does any individual ailment seem worth the social
costs of forcing its prescribed medicine.

This is how you cook a frog.

And where oh where does the ransomware come from?
