:PROPERTIES:
:ID:       8ba1ecd8-8091-4bf9-9eec-561a47641661
:END:
#+TITLE: Dear Network-Linux Users: Fucking Support Wayland
#+CATEGORY: slips
#+TAGS:

Linux users are forced to be socially isolated "Third Digital-World Citizens,"
since you have to jump through a constantly shifting set of hoops to do things
like:

+ "quickly share an application window colleagues and friends"
+ "hop on a zoom to video chat without making linux or yourself look bad"

This is a great reason to hate Discord and other proprietary apps. I would
like control over personal information that give me complete insight over
config/hardware/network and to have tools available to process data. Does your
internet service provider or platform-as-a-service or web app startup run on
windows? Fuck no. Hell no. Does it run on MacOS? No. What does it fucking run
on? LINUX. So why the fuck am I a third-world citizen, simply because your
profitable apps cannot be bothered to give a shit about Linux users? It runs
ALL of your fucking online companies.

When I had previously backed out of Wayland, the complexity of the config to get
Zoom or other similar apps to work led to any setup being brittle -- and likely
to change in the future. It is going to be complicated I know. I'm angry because
it really is pretty isolating to not have some features. And Zoom/Discord/etc:
they just do not give a fuck.

It's not the challenge/difficulty that's infuriating: it's how brittle any
solution is. If for some reason my shit crashes and I need to reinstall or maybe
I get another computer, are the same scripts/automation going to work? /Probably
not./ I should try though. I should spend kinda almost all my time trying.

You know what's not complicated? Put a fucking option for a url like rtmp in
your user interface. I should be able to send almost any local video stream to
almost any local app. The privacy controls over those streams should be handled
by pipewire and assoc. applications. At any point, if there are issues
supporting wayland screensharing, it sould be pretty easy to get a video stream
to come from a local video socket. I should be able to start a script that can
send to a socket at a random filename and other apps should be able to pull from
it. The details are likely imprecise, but if =ffmpeg= can pull from a video
source, it can trivially relay it.

Then you can have it both ways: your stock can continue to benefit by running
linux while you don't have to sink so much money into actually supporting
desktop linux.

Fuck these corporate spyware suites masquerading as "software" or "web
applications" or "browser extensions" or "operating systems" seriously. At least
if you pay the Apple tax and stay in their walled garden, you get a significant
modicum of privacy.

It's not that everyone's going to even /want/ to evade being tracked: most
people don't care and they won't care. But for those who do, simply placing
boundaries around the information in your digital life shouldn't be the sum
total of everything you do with your time & life. It's already going to be
prohibitively difficult for most people, but it should be easier. Utlimately,
privacy violation from digital data comes down to the level of motivation --
whether by hacking a desktop/network, social engineering to exploit a service
provider or extracting data from a stolen drive.

... But if you place zero boundaries around your digital identity & data, then
you can't even see which door they came through or understand what
data/information they might have. It's basically impossible to reason about what
information various groups have about you or how. This will cause most people to
gradually lose the ability to understand cause & effect. AI and machine learning
will accelerate this, since algorithms can determine how to make the connections
required for causes (data sources) to inform effects (actions taken by groups
who control AI and data). The average person can't see into that black box, so
why bother trying. And it's definitely a skill: understanding cause/effect and
how information propagates to affect things over different time-scales requires
a lifetime of experience with the human condition.

What we'll end up with is learned helplessness, nihilism and slowed
developmental progress. How do I know? I fucking know everything... but also I
look for confluence of factors. When several factors align to generally
contribute to similar 2nd and 3rd order effects: that's confluence. Then, you
look for feedback. If a second-order consequence feeds back into itself or
causes more complicated 3rd-order loops, that could be bad.

It's not like I want total control over every bit of my data, but it would be
nice to have a reasonable boundary around things. If you don't have privacy, you
don't have a boundary around your ego. Very fucked up psychological developments
can unfold for people who have minimal privacy. When such a situation affects
nearly everyone all the time, it contributes to skewed psychological development
in the people they affect. If those people are 30+ and have experienced enough
development without the affect of technology, there's life experience to keep
them grounded. However, when the psychological impacts are socially distributed
and also feed back into themselves (a psychologically messed up society makes it
a bit hard to be sane) then the aggregate psychological miasma accelerates.

Oh, but it's not just one thing that's psychologically fucking up the developed
world, is it? It's many things, right? Now through a little economic collapse
into that situation and see what shakes out -- not that this is likely, but if
it were to happen, good luck. We freaked out over a rabid variant of the common
cold because it might affect some people: 1% or 10%. Do you want to see what
happens when you really can't buy toilet paper? For months? Hell no. You want
people to be relatively sane in such situations ... or at least able to handle
stress without total breakdown.

This was quite the tangent. Having a boundary around your ego -- understanding
what really leads you to feel a certain way or how you influence others or what
/really/ is the extent of your /self/, lower-case "s" -- is critical for
developmental processes. Whenever that boundary dissolves, if it's not done in a
controlled manner or even if it is, bad things happen. Like depersonalization.
Most people with a grasp on their /self/ do pretty well.

* Roam
