:PROPERTIES:
:ID:       988e80ef-1818-4a6f-a7e6-1f8c406f011f
:END:
#+TITLE: GraphQL: Autocompletion without storing your cookies on a remote server
#+CATEGORY: slips
#+TAGS:

* The gist

#+begin_quote
this has been corrected btw. there's now a single-page graphql webapp for
testing queries.

but i tend to overthink this stuff
#+end_quote

I understand that most of the GraphQL ecosystem tooling is cloud native to
supports CI, collaboration and other use cases. However, I'm having some issues
running queries on Github & Upwork.

Can someone in the GraphQL world consider allowing credentials for API tokens to
be passed into a GraphQL IDE on initialization using either:

+ environment variable
+ file/descriptor redirection
+ the UNIX `pass` tool?

On Linux (without a proper "desktop environment), things like gnome-keyring
aren't guaranteed, which could be problematic when it comes to Electron Apps
that handle API Tokens, see [here on
archwiki](https://wiki.archlinux.org/title/Visual_Studio_Code#Authentication_with_Github_failed_while_using_VSCodium)
or [this
issue](https://github.com/microsoft/vscode/issues/92972#issuecomment-625751232)
or [the VS Code
docs](https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues). After
looking at that issue, I think would encounter that issue on my Guix install,
but maybe not my Arch desktop. This is possible for Electron apps on other OS's
where an app's developer doesn't use the keychain API's (like OSX Keychain or
[Android Key Storage](https://developer.android.com/training/articles/keystore).

I've now tried the following (and perhaps others). They are all electron apps or
web apps.

+ GraphiQL
+ Altair
+ Postman
+ Insomia

Whether this API token storage is a problem depends on how an Electron app
integrates with the desktop and what calls it uses to persist data. I don't want
to persist data, but none of the docs for any app makes clear how data is
stored. Also, I should definitely not have to store my API tokens on a
server. I'm sure this would be abundantly obvious if you had copious experience
with Electron... I got sick of the frontend world after learning
Angular/Ionic/Grunt/Gulp/Webpack/etc/etc ... none of my knowledge remained
relevant for long enough to ever get a job. I'm not looking forward to a deep
dive on Electron because I know what it will be like: build customization
everywhere and obfuscation of implementation. There are a few electron apps I
use and I'd really prefer to not know how the sausage is made.

For each GraphQL IDE app (and even the GraphQL website), the docs and product
structure are fairly confusing to me ... across the entire ecosystem. If you
look at graphql/graphiql#3214 and it seems like "I'm doing it wrong", that's
what I'm talking about. Youtube usually provides some good long-form surveys of
an software/platform ecosystem, but there's not much on GraphQL. Your
ecosystem's docs seem to not be aware of how much it depends on "social
connection" in order for people to "just know" what everything means. And so the
following isn't exactly obvious:

+ just learning what tooling exists (like literally the app names i should
  google)
+ where the apps store their secrets. they all use the same UI/UX: write a
  pre/post script where it can't exec shell scripts.
+ whether the electron local session storage is cached/saved to the file system.
+ where the Gitlab and Github GraphQL query-runner-app-things went? It usually
  takes me over an hour to find them.

I'm in the middle of hopping between like 7 different languages. Not having
autocomplete is a bottleneck in learning GraphQL. Development seems to require
like 20+ tabs and i'm also in the middle of learning Ansible -- given that each
collection has it's own page, where the average margin/padding is too wide, then
those are like 30+ very frustrating tabs. And learning Ansible led me /back to
GraphQL/ ... to simplify docs search for Ansible, I need to start out getting
all of the
[AnsibleCommunity](https://github.com/ectorepo/ectorepo/tree/master/ansible-collections)
repositories ... Then I don't have tabs, I have buffers and `ripgrep` handles
everything `xref` doesn't.

I understand that [some things are just more complicated in
Emacs](https://github.com/dcunited001/zettelkasten/blob/master/slips/20230425132236-gitforge_querying_github_graphql_api.org#querying-schema). view
raw if not clear, but I tried every way I could think of until running into
curl/quoting issues. If I can write the queries with features to facilitate
learning the language, running the queries in a 100 different ways is simple.

* Roam

+ [[id:7a4a7eea-5795-44e5-86e8-eec2afebf110][GraphQL]]
