:PROPERTIES:
:ID:       41ade9d2-34a7-491c-8846-8a98ba1709fa
:END:
#+TITLE: Emacs: pgtk build
#+CATEGORY: slips
#+TAGS:

Not sure, but it's crashed like 4 times in the past 24 hours.

#+begin_quote
TODO: encountering a wierd issue with emacs-29 (pgtk, i think) where desktops
are being restored in an invalid state and causing crashes later .... or
something? see org-roam
#+end_quote

When I attempt to restore a desktop (an empty desktop) after a crash, I get this

#+begin_quote

Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  frameset-move-onscreen(#<frame F1 0x1aec530> t)
  frameset--restore-frame(((minibuffer . t) (display-type . mono) (background-mode . dark) (scroll-bar-foreground) (scroll-bar-background) (cursor-color . "white") (menu-bar-lines . 1) (tool-bar-lines . 0) (vertical-scroll-bars) (right-fringe . 10) (left-fringe . 10) (foreground-color . "unspecified-fg") (background-color . "unspecified-bg") (font . "tty") (height . 24) (width . 80) (modeline . t) (unsplittable) (tab-bar-lines . 0) (frameset--id . "A07C-27C9-9B7F-CDF2") (frameset--mini t)) (((min-height . 4) (min-width . 10) (min-height-ignore . 3) (min-width-ignore . 2) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 4) (min-pixel-width . 10) (min-pixel-height-ignore . 3) (min-pixel-width-ignore . 2) (min-pixel-height-safe . 1) (min-pixel-width-safe . 2)) leaf (pixel-width . 80) (pixel-height . 23) (total-width . 80) (total-height . 23) (normal-height . 1.0) (normal-width . 1.0) (buffer "*scratch*" (selected) (hscroll . 0) (fringes 0 0 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 146) (start . 1))) ((tabs . frameset-filter-tabs) (background-color . frameset-filter-sanitize-color) (bottom . frameset-filter-shelve-param) (buffer-list . :never) (buffer-predicate . :never) (buried-buffer-list . :never) (client . :never) (delete-before . :never) (font . frameset-filter-font-param) (font-backend . :never) (foreground-color . frameset-filter-sanitize-color) (frameset--text-pixel-height . :save) (frameset--text-pixel-width . :save) (fullscreen . frameset-filter-shelve-param) (GUI:bottom . frameset-filter-unshelve-param) (GUI:font . frameset-filter-unshelve-param) (GUI:fullscreen . frameset-filter-unshelve-param) (GUI:height . frameset-filter-unshelve-param) (GUI:left . frameset-filter-unshelve-param) (GUI:right . frameset-filter-unshelve-param) (GUI:top . frameset-filter-unshelve-param) (GUI:width . frameset-filter-unshelve-param) (height . frameset-filter-shelve-param) (left . frameset-filter-shelve-param) (parent-frame . :never) (mouse-wheel-frame . :never) (right . frameset-filter-shelve-param) (top . frameset-filter-shelve-param) (tty . frameset-filter-tty-to-GUI) (tty-type . frameset-filter-tty-to-GUI) (width . frameset-filter-shelve-param) (window-system . :never) (left . frameset-filter-iconified) (minibuffer . frameset-filter-minibuffer) (top . frameset-filter-iconified) (name . :never) (parent-id . :never) (window-id . :never)) t 0 0)
  frameset-restore([frameset 1 (25862 42247 201429 194000) (desktop . "208") "dc@kratos" nil nil ((((minibuffer . t) (undecorated) (override-redirect) (font . "-ADBO-Source Code Pro-regular-normal-normal-*-12-*...") (border-width . 0) (internal-border-width . 0) (child-frame-border-width) (right-divider-width . 0) (bottom-divider-width . 0) (vertical-scroll-bars) (horizontal-scroll-bars) (foreground-color . "#cfdfd5") (background-color . "#111111") (mouse-color . "black") (border-color . "black") (screen-gamma) (line-spacing) (left-fringe . 10) (right-fringe . 10) (no-special-glyphs) (scroll-bar-foreground) (scroll-bar-background) (menu-bar-lines . 1) (tab-bar-lines . 0) (tool-bar-lines . 0) (title) (wait-for-wm . t) (tool-bar-position . top) (inhibit-double-buffering) (icon-type . t) (auto-raise) (auto-lower) (cursor-type . box) (scroll-bar-width . 16) (scroll-bar-height . 16) (alpha) (alpha-background) (no-focus-on-map) (no-accept-focus) (fullscreen) (visibility . t) (skip-taskbar) (z-group) (environment "LC_NUMERIC=en_US.UTF-8" "_GUIX=/gnu" "_DATA=/data" "JULIA_EDITOR=emacsclient -nw" "EMACSLOADPATH=/gnu/store/1kj3jswl0daphhcfgy99qmhz2..." "MAIL=geary" "HG=/usr/bin/hg" "GUIX_TEXMF=/home/dc/.guix-extra-profiles/academic/..." "KDE_APPLICATIONS_AS_SCOPE=1" "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/..." "_STEAM=/flatpak/steam" "I_ROOT=/usr/share/icons" "PATH=/gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-p..." "ALTERNATE_EDITOR=vim" "BROWSER=firefox" "MATLAB_PATH=/flatpak/matlab/R2022a/bin" "KDE_FULL_SESSION=true" "XDG_DATA_DIRS=/gnu/store/7z9cgiq7dkajqfk991lniv77s..." "XCURSOR_THEME=Sweet-cursors" "JOURNAL_STREAM=8:42554" "QT_AUTO_SCREEN_SCALE_FACTOR=0" "STEAM_DIR=/flatpak/steam/.var/app/com.valvesoftwar..." "DOOMDIR=/home/dc/.doom.d" "EMAIL=aionfork@gmail.com" "LC_TIME=en_US.UTF-8" "DEBUGINFOD_URLS=https://debuginfod.archlinux.org" "PYENV_ROOT=/data/lang/.pyenv" "PROTON_CRASH_REPORT_DIR=/flatpak/steam/log/proton-..." "XDG_RUNTIME_DIR=/run/user/1000" "GUIX_EXTRA=/home/dc/.guix-extra-profiles" "GUIX_ENVIRONMENT=/gnu/store/1kj3jswl0daphhcfgy99qm..." "GUIX_PROFILE=/home/dc/.config/guix/current" "FLATPAK_USER_DIR=/flatpak/dc/.local/share/flatpak" "MATLAB_JAVA=/flatpak/matlab/R2022a/sys/java/jre/gl..." "MATLAB_VERSION=R2022a" "XDG_SESSION_ID=2" "UBUNTU_MENUPROXY=1" "_AGENDA=/flatpak/agenda" "XDG_VTNR=2" "LC_MEASUREMENT=en_US.UTF-8" "QT_IM_MODULE=fcitx" "JULIA_DEPOT_PATH=/data/lang/.julia:" "LC_TELEPHONE=en_US.UTF-8" "GUIX_LOCPATH=/home/dc/.guix-profile/lib/locale:/gn..." "SHLVL=1" "DISPLAY=:0" "VISUAL=emacsclient -c" "PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket" "KDE_SESSION_VERSION=5" ...) (display-type . color) (background-mode . dark) (cursor-color . "#35f038") (font-parameter) (sticky) (last-focus-update . t) ...) ((min-height . 4) (min-width . 10) (min-height-ignore . 3) (min-width-ignore . 5) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 64) (min-pixel-width . 70) (min-pixel-height-ignore . 48) (min-pixel-width-ignore . 35) (min-pixel-height-safe . 16) (min-pixel-width-safe . 14)) leaf (pixel-width . 580) (pixel-height . 560) (total-width . 82) (total-height . 35) (normal-height . 1.0) (normal-width . 1.0) (buffer "*scratch*" (selected . t) (hscroll . 0) (fringes 10 10 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 146) (start . 1))) (((minibuffer . t) (display-type . mono) (background-mode . dark) (scroll-bar-foreground) (scroll-bar-background) (cursor-color . "white") (menu-bar-lines . 1) (tool-bar-lines . 0) (vertical-scroll-bars) (right-fringe . 10) (left-fringe . 10) (foreground-color . "unspecified-fg") (background-color . "unspecified-bg") (font . "tty") (height . 24) (width . 80) (modeline . t) (unsplittable) (tab-bar-lines . 0) (frameset--id . "A07C-27C9-9B7F-CDF2") (frameset--mini t)) ((min-height . 4) (min-width . 10) (min-height-ignore . 3) (min-width-ignore . 2) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 4) (min-pixel-width . 10) (min-pixel-height-ignore . 3) (min-pixel-width-ignore . 2) (min-pixel-height-safe . 1) (min-pixel-width-safe . 2)) leaf (pixel-width . 80) (pixel-height . 23) (total-width . 80) (total-height . 23) (normal-height . 1.0) (normal-width . 1.0) (buffer "*scratch*" (selected) (hscroll . 0) (fringes 0 0 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 146) (start . 1))))] :reuse-frames t :cleanup-frames t :force-display t :force-onscreen t)
    frameset--action-map = #<hash-table eq 2/65 0x167fe8d>
    frameset--reuse-list = nil
    frameset--target-display = nil
  desktop-restore-frameset()
    [no locals]
  desktop-read()
  dc/desktop-read()
  funcall-interactively(dc/desktop-read)
  command-execute(dc/desktop-read record)
  execute-extended-command(nil "dc/desktop-read" nil)
  funcall-interactively(execute-extended-command nil "dc/desktop-read" nil)
  command-execute(execute-extended-command)
    current-minibuffer-command = execute-extended-command

#+end_quote

When I look at the crash in journalctl, I get this.

#+begin_quote
Sep 17 02:21:29 kratos syncthing[50646]: [WTTXV] INFO: Scanner (folder "edu" (cxq3r-lrku3), item "coursera/scala1/recfun/.metals/.reports/metals-full/r_compiler-error_1692371195639"): hashing: open /data/edu/coursera/scala1/recfun/.metals/.reports/metals-full/r_compiler-error_1692371195639: permission denied
Sep 17 02:36:16 kratos bash[3202216]: Backtrace:
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x52d4fb]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x42418b]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x42467d]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x52bad8]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x52bb49]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/gsjczqir1wbz8p770zndrpw4rnppmxi3-glibc-2.35/lib/libc.so.6(+0x3d2a0)[0x7f1db8efb2a0]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/nb40pwd37v6i1g4b1fq4l6q4h9px3asr-glib-2.72.3/lib/libgobject-2.0.so.0(+0x28794)[0x7f1dbc4d1794]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/nb40pwd37v6i1g4b1fq4l6q4h9px3asr-glib-2.72.3/lib/libgobject-2.0.so.0(g_signal_emit_valist+0xc09)[0x7f1dbc4d7689]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/nb40pwd37v6i1g4b1fq4l6q4h9px3asr-glib-2.72.3/lib/libgobject-2.0.so.0(g_signal_emit+0x82)[0x7f1dbc4d7bb2]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/nb40pwd37v6i1g4b1fq4l6q4h9px3asr-glib-2.72.3/lib/libgobject-2.0.so.0(+0x1a9a4)[0x7f1dbc4c39a4]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/nb40pwd37v6i1g4b1fq4l6q4h9px3asr-glib-2.72.3/lib/libgobject-2.0.so.0(g_object_notify_by_pspec+0xe4)[0x7f1dbc4c5a34]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/ivqwlszdaf8xn8qkc7p2lz7p6pl95l1g-gtk+-3.24.37/lib/libgtk-3.so.0(gtk_window_set_mnemonics_visible+0x9d)[0x7f1dbcd8e6ad]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/ivqwlszdaf8xn8qkc7p2lz7p6pl95l1g-gtk+-3.24.37/lib/libgtk-3.so.0(+0x38e75c)[0x7f1dbcd8e75c]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/ivqwlszdaf8xn8qkc7p2lz7p6pl95l1g-gtk+-3.24.37/lib/libgdk-3.so.0(+0x33a39)[0x7f1dbd270a39]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/nb40pwd37v6i1g4b1fq4l6q4h9px3asr-glib-2.72.3/lib/libglib-2.0.so.0(+0x563b4)[0x7f1dbc3c93b4]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/nb40pwd37v6i1g4b1fq4l6q4h9px3asr-glib-2.72.3/lib/libglib-2.0.so.0(g_main_context_dispatch+0x154)[0x7f1dbc3c8894]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x6400b8]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x5f3a39]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x437c60]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x51e0c6]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x51e952]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x5205a2]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x595c47]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x50c76a]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x595ba1]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x50c70f]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x513663]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x5139da]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x42d132]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/gsjczqir1wbz8p770zndrpw4rnppmxi3-glibc-2.35/lib/libc.so.6(+0x291f7)[0x7f1db8ee71f7]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/gsjczqir1wbz8p770zndrpw4rnppmxi3-glibc-2.35/lib/libc.so.6(__libc_start_main+0x7c)[0x7f1db8ee72ac]
Sep 17 02:36:16 kratos bash[3202216]: /gnu/store/1kj3jswl0daphhcfgy99qmhz26l77dxn-profile/bin/emacs[0x42d601]
Sep 17 02:36:17 kratos syncthing[50646]: [WTTXV] INFO: Scanner (folder "ml" (919kx-giwgc), item "kaggle/asl/build/mediapipe/_bazel_root/4884d566396e9b67b62185751879ad14/server"): scan: open /data/ml/kaggle/asl/build/mediapipe/_bazel_root/4884d566396e9b67b62185751879ad14/server: permission denied
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos (sd-parse-elf)[3577033]: Could not parse number of program headers from core file: invalid `Elf' handle
Sep 17 02:36:19 kratos systemd-coredump[3577029]: [🡕] Process 3202216 (.emacs-29.0.92-) of user 1000 dumped core.

Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/markdown-mode-b1337450-8f85bf86.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/markdown-mode-b1337450-8f85bf86.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/edit-indirect-a1f14a39-5a4edc8c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/edit-indirect-a1f14a39-5a4edc8c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-core-5ff85add-f6eaceae.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-core-5ff85add-f6eaceae.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-list-b6e9bb2f-a75f659e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-list-b6e9bb2f-a75f659e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-info-ecede8b3-8faa1495.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-info-ecede8b3-8faa1495.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-history-c2ad845b-57f33ff2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-button-5b69accc-4f7c7562.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-entry-7632f5e5-e7ec7573.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-utils-1cddb6d8-10ba2c8a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bui-utils-1cddb6d8-10ba2c8a.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-license-656132df-59ad0636.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-misc-a6d8e1b5-30ba48d2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-misc-a6d8e1b5-30ba48d2.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-read-2d128006-2c5f64bb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-read-2d128006-2c5f64bb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-package-18d53ba8-b7c1e72e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-package-18d53ba8-b7c1e72e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-ui-store-item-7192c4f0-518fc244.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-ui-store-item-7192c4f0-518fc244.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-ui-messages-84ce6ed9-4126f3c0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-ui-messages-84ce6ed9-4126f3c0.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-external-c6fed5fc-19eabace.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-guile-34943ef8-712cf709.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-guile-34943ef8-712cf709.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-geiser-20d8a519-e9bd5667.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-geiser-20d8a519-e9bd5667.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-xref-e05979c9-e4d1c091.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-xref-e05979c9-e4d1c091.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-compile-14c15279-3a437b83.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-debug-6bb01c08-5af9cc39.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-debug-6bb01c08-5af9cc39.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-guile-a8e4cda9-220cdb99.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-guile-a8e4cda9-220cdb99.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-image-d8650ab2-2dc7c2df.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-menu-d43130e5-2c003a8a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-doc-a5d19b33-25685d9d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-doc-a5d19b33-25685d9d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-syntax-3dbefecf-4fd87574.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-syntax-3dbefecf-4fd87574.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-popup-1fe9fb78-d95b485a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-log-ca789536-83a76d4d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-connection-31668342-fe5f2986.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-connection-31668342-fe5f2986.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-eval-8b5ff103-7bbc801b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-eval-8b5ff103-7bbc801b.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-base-b29469b9-f6161ba1.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-custom-d7bbf71e-f8a77d64.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-impl-ddfb325f-8c8f3f04.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-impl-ddfb325f-8c8f3f04.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-completion-46f86a50-4a3c81d7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-edit-ec1647f9-6db6e4a7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-edit-ec1647f9-6db6e4a7.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-autodoc-1b275a06-536aa19a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-autodoc-1b275a06-536aa19a.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-capf-e3d64e09-2b145756.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-repl-47fd0b2e-643ff3ab.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-repl-47fd0b2e-643ff3ab.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-mode-fe540632-3231890d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-mode-fe540632-3231890d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-repl-f0a2ad51-17959c29.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-repl-f0a2ad51-17959c29.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-ui-b58557c3-26031d83.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-ui-b58557c3-26031d83.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-location-bf1b3ce4-dc1063a7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-ui-package-45d66bb2-b7d163be.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-ui-package-45d66bb2-b7d163be.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-utils-b13904b5-26399570.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-utils-b13904b5-26399570.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-popup-b3df9632-3751e1bd.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-popup-b3df9632-3751e1bd.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-bundle-86c85edf-e60749df.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-bundle-86c85edf-e60749df.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-gitignore-3553eada-d836816e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-gitignore-3553eada-d836816e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-profiles-1abf3e2a-88b4fe3d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-profiles-1abf3e2a-88b4fe3d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-popup-3b8786da-03414272.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-popup-3b8786da-03414272.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/apheleia-a1e7c42b-d78664ef.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/apheleia-a1e7c42b-d78664ef.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-extras-e1ad6df9-81da1ff4.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-extras-e1ad6df9-81da1ff4.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jupyter-messages-e89ccab3-25f440e9.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jupyter-messages-e89ccab3-25f440e9.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jupyter-mime-f2cd0467-7e3ffd77.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jupyter-mime-f2cd0467-7e3ffd77.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jupyter-monads-b6958353-5446f250.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jupyter-monads-b6958353-5446f250.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jupyter-base-edfe78d9-979696d7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jupyter-base-edfe78d9-979696d7.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-node-9d109110-caa67140.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-node-9d109110-caa67140.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/request-0b68160c-fae7949b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/request-0b68160c-fae7949b.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/i-ching-1892d815-f65c5de5.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/i-ching-1892d815-f65c5de5.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/corfu-popupinfo-971a5055-df5173d7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/corfu-popupinfo-971a5055-df5173d7.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/0x0-e0b7574f-c7451efc.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/0x0-e0b7574f-c7451efc.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-imenu-6ece8d56-3ad928b7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-imenu-6ece8d56-3ad928b7.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/burly-f7e48e36-175ca32d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/burly-f7e48e36-175ca32d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/pandoc-mode-utils-bdbc3623-d408abeb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/pandoc-mode-utils-bdbc3623-d408abeb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/embark-577f3eac-be145697.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/embark-577f3eac-be145697.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-org-roam-buffer-5a939130-4c824503.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-org-roam-buffer-5a939130-4c824503.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-org-roam-468dbf1c-9c4fd167.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-org-roam-468dbf1c-9c4fd167.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-sqlite-builtin-85ec9e79-cee7dbe7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-sqlite-builtin-85ec9e79-cee7dbe7.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-attach-cb1776a0-cc5d339d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-attach-cb1776a0-cc5d339d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-sqlite-common-3da76ee0-c48e95e5.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-sqlite-common-3da76ee0-c48e95e5.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-sqlite-60388b27-913e2b28.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-sqlite-60388b27-913e2b28.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-compiler-b040d2cb-3de5951f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-compiler-b040d2cb-3de5951f.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-a9d72958-a4241958.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/emacsql-a9d72958-a4241958.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-mode-917c58c9-a44fa28c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-mode-917c58c9-a44fa28c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-db-c2410847-f7350f11.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-db-c2410847-f7350f11.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-capture-7c0343d6-9886c557.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-capture-7c0343d6-9886c557.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-appear-16dd70c5-8b9675f9.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-appear-16dd70c5-8b9675f9.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-make-toc-c31d3952-e11b9f27.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-make-toc-c31d3952-e11b9f27.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-file-55d3d6f1-faf521c0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-file-55d3d6f1-faf521c0.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-format-41710c6d-cf4c1843.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-cache-85253efd-e7f4d0e4.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-cache-85253efd-e7f4d0e4.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-784add66-b0e4d5fb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-784add66-b0e4d5fb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-capf-35e16971-c6a4c29f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-indent-d9924949-0460feb4.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-indent-d9924949-0460feb4.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-protocol-00ac2e32-a4156b4f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-protocol-00ac2e32-a4156b4f.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-crypt-56278523-216a1f99.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-gnus-497e11ee-e16a60e0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-gnus-497e11ee-e16a60e0.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-doi-400c9f30-04df16a6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-man-99dfe467-5bc16c62.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-info-6f83e92b-2ff2abc6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-buffer-eea46521-ffd68a91.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/all-the-icons-3f8bc6ef-492875aa.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/all-the-icons-3f8bc6ef-492875aa.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-dir-fff871e2-17162f9c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-dir-fff871e2-17162f9c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/lispy-91b8b4cc-e0d89fba.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/lispy-91b8b4cc-e0d89fba.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-core-1b4ca28d-bd07d529.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-core-1b4ca28d-bd07d529.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-isbn-3a040965-34585576.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-isbn-3a040965-34585576.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-patch-bfa6226d-9f49670d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-patch-bfa6226d-9f49670d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-subtree-7c3ece2c-bf904a85.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-subtree-7c3ece2c-bf904a85.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-link-3456a59d-edede731.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-org-roam-0f914a09-f4782365.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-org-roam-0f914a09-f4782365.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-utils-bd3ceec1-d2ccb307.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-utils-bd3ceec1-d2ccb307.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-migrate-67861d5e-0404f457.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-migrate-67861d5e-0404f457.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-compat-0764fcec-aa6ebb31.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-compat-0764fcec-aa6ebb31.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-log-3f2507e1-40352623.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-id-98d70026-05f26bd7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/subr--trampoline-726567696f6e2d656e64_region_end_0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/subr--trampoline-726567696f6e2d626567696e6e696e67_region_beginning_0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/debbugs-browse-cff85439-5dead6e7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-357fb99c-9621a6c9.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-roam-357fb99c-9621a6c9.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/buffer-move-8e18a884-94cdc161.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/burly-tabs-4aa1470d-93d475eb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-export-d6d19bb6-cc5a5b92.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-export-d6d19bb6-cc5a5b92.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-glossary-c299620e-d0100318.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-glossary-c299620e-d0100318.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-scopus-6d46c7fa-04d157cc.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-scopus-6d46c7fa-04d157cc.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-dd1ef8be-a954c026.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-dd1ef8be-a954c026.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-cite-41c943f9-a9cce7ad.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-cite-41c943f9-a9cce7ad.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-pubmed-3cb7f06f-757f3ad6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-pubmed-3cb7f06f-757f3ad6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-biblatex-d513d2e2-c6bb4b7f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-bibtex-15f8e78a-477c6342.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-bibtex-15f8e78a-477c6342.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-itemgetters-ea7ba939-333df43c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-itemgetters-ea7ba939-333df43c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-scifinder-3ff22ab9-ac2fe044.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bibtex-completion-142df425-595a15a1.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bibtex-completion-142df425-595a15a1.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/straight-63b816ed-e565dc97.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/straight-63b816ed-e565dc97.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-name-2b460ceb-1203b582.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-name-2b460ceb-1203b582.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-sort-68483531-877272b2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-sort-68483531-877272b2.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-subbibs-ed5b07ef-3363cc94.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-formatters-0539bb65-38d7cf78.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-formatters-0539bb65-38d7cf78.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-proc-873620ef-5aed5da6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-proc-873620ef-5aed5da6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-number-4eb88d93-27024801.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-style-4e373200-be98faa1.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-style-4e373200-be98faa1.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-date-0c3fdd34-f052f669.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-date-0c3fdd34-f052f669.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-disamb-84e8f97a-15df2567.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-disamb-84e8f97a-15df2567.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-context-19a4ac42-e0b12e63.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-context-19a4ac42-e0b12e63.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-itemdata-a121533d-f9f111e9.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-itemdata-a121533d-f9f111e9.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-todos-a135b049-c62425ee.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-todos-a135b049-c62425ee.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-rt-fa554556-416609d4.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-rt-fa554556-416609d4.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-generic-elements-1ca9c9d8-a1354c71.eln withoutbuild-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-choose-f18c2adf-6fc9d138.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-macro-2bd41c1e-6ac2e8f0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-citation-links-197dff55-62997d2c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-citation-links-197dff55-62997d2c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-term-a6926876-0e9bf00b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-term-a6926876-0e9bf00b.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-bibtex-4dac7696-7c1f4363.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-bibtex-4dac7696-7c1f4363.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-prange-71710ced-eb5b6248.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-lib-ad345448-fc02f0f2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-misc-links-48118c35-48dedd68.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-misc-links-48118c35-48dedd68.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-s-7285e089-3810611f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-s-7285e089-3810611f.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citeproc-locale-309bfc3e-c4badeb2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-status-1bc533bf-f6654216.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-status-1bc533bf-f6654216.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-ref-links-9a2b28c2-46bc7717.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-ref-links-9a2b28c2-46bc7717.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-download-6f4a8a62-67109d95.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-super-agenda-45a2005c-8b0a6edd.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-super-agenda-45a2005c-8b0a6edd.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-label-link-fb4fa9c7-d9edd3cf.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-ieee-ca7af3cb-f41d8f44.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-ieee-ca7af3cb-f41d8f44.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-dissemin-1b6c2213-fef7d781.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-dissemin-1b6c2213-fef7d781.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-hal-2644fbe2-e0d0ed82.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-bibliography-links-53647bdf-9674c627.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-bibliography-links-53647bdf-9674c627.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-dblp-5abe9b16-bbd6b761.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-dblp-5abe9b16-bbd6b761.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-crossref-3e7ac85a-0a1da358.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-crossref-3e7ac85a-0a1da358.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/doi-utils-c2016e54-5e246132.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/doi-utils-c2016e54-5e246132.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-arxiv-07b68879-6fce3b6c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-arxiv-07b68879-6fce3b6c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-core-0d2c1167-f74e6c52.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-core-0d2c1167-f74e6c52.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-doi-8c112eb1-55986462.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/biblio-doi-8c112eb1-55986462.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/subr--trampoline-72756e2d686f6f6b73_run_hooks_0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-reverse-d3f6424f-814757dd.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ts-2a60d73f-d5c61ae5.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ts-2a60d73f-d5c61ae5.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-reset-1b278234-709d5f56.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-reset-1b278234-709d5f56.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-pull-4e23dcf3-3bf3af7f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-pull-4e23dcf3-3bf3af7f.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-utils-ab4dcd38-485f6562.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-utils-ab4dcd38-485f6562.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-reflog-1003a1a6-69fc9edb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-reflog-1003a1a6-69fc9edb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/parsebib-2bfb8be8-529cc777.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/parsebib-2bfb8be8-529cc777.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-arxiv-62721c32-6599f8a0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-ref-arxiv-62721c32-6599f8a0.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/super-save-dd1e32e7-124d97a1.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/super-save-dd1e32e7-124d97a1.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/zoutline-629834e3-3b7a2b62.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/nist-webbook-2981985e-f96aca63.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ef-themes-93c2dd9b-a795e505.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ef-themes-93c2dd9b-a795e505.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-multiform-f7fea039-15eea5c6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-multiform-f7fea039-15eea5c6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-mouse-b3dfb2f3-6f1ef6d5.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-f4e0dd92-eed3bd5e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-f4e0dd92-eed3bd5e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-indexed-c3db0c92-7bea1a7d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-org-c4a1de55-919f9ecd.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-capture-f0adc05b-055f14de.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-capture-f0adc05b-055f14de.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-bibtex-3891a1a1-acec66f9.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-bibtex-3891a1a1-acec66f9.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/envrc-d52f7035-bbdbba71.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/envrc-d52f7035-bbdbba71.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/pcre2el-acf696fc-860ccd8c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/pcre2el-acf696fc-860ccd8c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-submodule-eec19af4-0e1addc3.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-submodule-eec19af4-0e1addc3.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-blame-048d28e6-5d4cd681.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-blame-048d28e6-5d4cd681.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-stash-079a2d68-f2a708b6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-stash-079a2d68-f2a708b6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-bisect-6a32caf2-6fbb9bc2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-bisect-6a32caf2-6fbb9bc2.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-push-35149179-b67bbe05.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-push-35149179-b67bbe05.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-fetch-d3b0dd85-029daf61.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-fetch-d3b0dd85-029daf61.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-clone-4d799327-e3db2e06.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-clone-4d799327-e3db2e06.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-remote-f3ae37c6-bb4a4595.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-remote-f3ae37c6-bb4a4595.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-commit-412b4aa0-ac089f0e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-commit-412b4aa0-ac089f0e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-sequence-cbbf7ffe-b1a97807.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-sequence-cbbf7ffe-b1a97807.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-notes-58b26c3a-ce57b283.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-notes-58b26c3a-ce57b283.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-worktree-cc502b62-7b120e5d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-worktree-cc502b62-7b120e5d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-tag-d4a441e6-f7b42d89.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-tag-d4a441e6-f7b42d89.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-merge-5cb3e0c4-7bc0ed2b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-merge-5cb3e0c4-7bc0ed2b.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-branch-1fef25ec-b362e334.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-branch-1fef25ec-b362e334.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-files-0c4c634e-d629cbfc.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-files-0c4c634e-d629cbfc.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-refs-5b442bad-ab4fef69.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-refs-5b442bad-ab4fef69.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-repos-c4a4d2a6-da9ca79c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-repos-c4a4d2a6-da9ca79c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-apply-564452cc-5b54af72.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-apply-564452cc-5b54af72.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-bookmark-51fa3bca-0c7afca7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/all-the-icons-dired-7ba704a2-d24190ef.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-directory-1ad2a166-dcf28928.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/vertico-grid-fc9cb33b-7190f1af.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-log-803df040-b655dbfb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-log-803df040-b655dbfb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/git-commit-513b6167-05a352a6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/git-commit-513b6167-05a352a6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-diff-ce2afaa8-4d135c0d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-diff-ce2afaa8-4d135c0d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-autorevert-017040ba-bf1f5ea3.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-autorevert-017040ba-bf1f5ea3.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/with-editor-6302a21a-ddc1b93b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/with-editor-6302a21a-ddc1b93b.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-process-687efdb6-410e523c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-process-687efdb6-410e523c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-transient-70ffa960-ba4b9651.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-transient-70ffa960-ba4b9651.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-margin-b3e26cc8-b1c0e957.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-margin-b3e26cc8-b1c0e957.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/transient-33d4ca7b-9a563ce6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/transient-33d4ca7b-9a563ce6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-mode-ef13b017-31fbb927.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-mode-ef13b017-31fbb927.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-git-8f51be27-062bff70.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-git-8f51be27-062bff70.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-section-a2406f49-0461e8af.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-section-a2406f49-0461e8af.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-base-8cd935ec-751fcac2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-base-8cd935ec-751fcac2.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/inheritenv-ec1eca75-716e8656.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-4fa26ccf-37e7cc55.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-4fa26ccf-37e7cc55.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/hl-todo-2718101a-782d053e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/hl-todo-2718101a-782d053e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/f-13db66bd-65c587d9.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/f-13db66bd-65c587d9.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/async-86e44eaa-69cfd031.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/async-86e44eaa-69cfd031.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/gtea-975b8141-8736ce15.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/glab-86f3eb6a-7cc430a2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/treepy-44e4edf5-99c45662.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/treepy-44e4edf5-99c45662.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/gsexp-89c7f712-52ba8e9b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ghub-49b4a3f0-49769412.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ghub-49b4a3f0-49769412.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ghub-graphql-bc44a731-558332bc.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ghub-graphql-bc44a731-558332bc.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/graphql-5a71b185-3a2eaaa1.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bind-key-fce540ad-dd3bfcce.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bind-key-fce540ad-dd3bfcce.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-search-d41cc305-58da4598.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-search-d41cc305-58da4598.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/xterm-color-e91d8939-6e04b321.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/xterm-color-e91d8939-6e04b321.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/rainbow-mode-266acf3d-b57d0aff.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ws-butler-25f62847-e729b19e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ws-butler-25f62847-e729b19e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/rainbow-delimiters-96271b81-84f0d533.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/.yas-setup-21571b5d-04caea0d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/yasnippet-snippets-90d7e4fb-9c969aae.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/smartparens-markdown-989a38da-b6595ca3.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/smartparens-latex-5ed76c62-caa7c9b0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/smartparens-text-bb661917-309c6a03.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/smartparens-org-2cf6404d-f9dbadb6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/smartparens-python-062d9deb-42ab8a8b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/smartparens-35b473ac-c75f7f23.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/smartparens-35b473ac-c75f7f23.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/lispy-inline-4f696b5b-420d35ee.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/lispy-inline-4f696b5b-420d35ee.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/lispy-tags-19a9b6b8-947d43b6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/lispy-tags-19a9b6b8-947d43b6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/yasnippet-9cf260e7-8df7bbfb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/yasnippet-9cf260e7-8df7bbfb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/subr--trampoline-6d616b652d70726f63657373_make_process_0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-show-eef9cf41-a6070a38.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-show-eef9cf41-a6070a38.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-csv-dc123d43-f597492f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-curl-18618046-ed0a43ac.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-curl-18618046-ed0a43ac.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-log-da4c1d93-8bcae0c7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-lib-60ed9bd8-7807261b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-lib-60ed9bd8-7807261b.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-db-e3cfb145-55e0549b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-db-e3cfb145-55e0549b.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/xml-query-95278f78-96b7a8e1.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/xml-query-95278f78-96b7a8e1.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-9b0d5030-e120d829.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-9b0d5030-e120d829.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-org-62cc2334-055b7cbb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/elfeed-org-62cc2334-055b7cbb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/latex-flymake-e29331c7-c80a148f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/texmathp-252f5f03-cd2105a3.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/tex-2855ce54-3e9b8a58.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/tex-2855ce54-3e9b8a58.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/latex-fe48159e-b8472548.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/latex-fe48159e-b8472548.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/firestarter-990b5f65-44b64673.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-clojure-836e4e3b-57f92c9c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-clojure-836e4e3b-57f92c9c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/clojure-mode-e27d4582-6a05c076.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/clojure-mode-e27d4582-6a05c076.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/cider-util-79c2c44d-1fdd9d55.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/cider-util-79c2c44d-1fdd9d55.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/cider-popup-29f3de5f-10384ad2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/spinner-3a1bc086-043a22dc.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/spinner-3a1bc086-043a22dc.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/sesman-browser-1527c9d1-8a326eeb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/sesman-browser-1527c9d1-8a326eeb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/sesman-dc38be3c-f1bb6905.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/sesman-dc38be3c-f1bb6905.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/nrepl-dict-6d5aa3ba-72e4d092.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/nrepl-dict-6d5aa3ba-72e4d092.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/nrepl-client-dd46fc43-6efe89e4.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/nrepl-client-dd46fc43-6efe89e4.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/cider-connection-f037a758-4eedd190.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/cider-connection-f037a758-4eedd190.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/let-alist-449169df-b4147693.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/package-lint-eb6724cb-3d737e04.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/package-lint-eb6724cb-3d737e04.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/flycheck-package-01a9c65f-1c268aa0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/flycheck-guile-c97fac41-0aa30e47.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/flycheck-7a6939ff-2ed79dcf.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/flycheck-7a6939ff-2ed79dcf.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jq-mode-91e23c2b-86120ec6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/jq-mode-91e23c2b-86120ec6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-jq-efafdf06-c01664c6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-python-0ceaa1b6-f83b9b33.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-python-0ceaa1b6-f83b9b33.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-shell-95965780-0a08d597.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-shell-95965780-0a08d597.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-extra-3c22cd70-8377bb4a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-dot-ba68eb12-2b20b87f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ht-6e56e18e-db3cf913.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ht-6e56e18e-db3cf913.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/s-69be150d-61be6d57.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/s-69be150d-61be6d57.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-habit-3d885377-736ac1e2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-habit-3d885377-736ac1e2.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-clock-5a8f3f30-6710922f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-clock-5a8f3f30-6710922f.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-odt-18ed735f-134ec529.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-odt-18ed735f-134ec529.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-agenda-316da69c-a2b66be5.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-agenda-316da69c-a2b66be5.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-icalendar-ee36706f-a8aa53e0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-icalendar-ee36706f-a8aa53e0.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-html-85ce30b9-b38d114d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-html-85ce30b9-b38d114d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-publish-38699bce-42ea26c0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-publish-38699bce-42ea26c0.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-ascii-a981b4dc-39c7362c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-ascii-a981b4dc-39c7362c.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-refile-16245024-af18f3c6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-refile-16245024-af18f3c6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-id-ab622879-01eea74f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-id-ab622879-01eea74f.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-persist-a8be078c-d361f662.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-persist-a8be078c-d361f662.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-eldoc-660c924f-630f10be.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-tangle-0c9f1c9d-a9ed6681.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-tangle-0c9f1c9d-a9ed6681.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-ref-f8b7e567-6b8a9ccc.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-lob-44995e04-f2b24928.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-table-bc9b7716-a87cc52a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-macro-99131549-a8c1d25a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-macro-99131549-a8c1d25a.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-comint-a8dae969-7a7e4c25.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-comint-a8dae969-7a7e4c25.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-src-841fcd65-7ec69662.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-src-841fcd65-7ec69662.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-pcomplete-14456804-422d58af.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-pcomplete-14456804-422d58af.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-footnote-e667cea6-9c6cc18e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-footnote-e667cea6-9c6cc18e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-list-fb302d24-7b6fab2d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-list-fb302d24-7b6fab2d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-faces-26c65215-099a0024.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-entities-52907d34-15e67312.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-table-42ad9952-f811133d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-table-42ad9952-f811133d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-keys-937f67b1-174600a8.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-keys-937f67b1-174600a8.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-2af396b4-be34bf72.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-2af396b4-be34bf72.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-emacs-lisp-1efad0bc-1d800b2a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-element-71ee0606-47d424c3.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-element-71ee0606-47d424c3.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-a7ed6c27-6070da7d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ol-a7ed6c27-6070da7d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/oc-a6e17c02-264cd991.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/oc-a6e17c02-264cd991.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-cycle-8ed05dd7-fd1ef952.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-cycle-8ed05dd7-fd1ef952.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-compat-626af817-af9401b3.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-compat-626af817-af9401b3.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-fold-core-2a43eb40-5c823dfe.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-fold-core-2a43eb40-5c823dfe.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-fold-67a7a6e0-429663f0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-fold-67a7a6e0-429663f0.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-eval-040ffb30-b60e1bda.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-core-33e14b8f-1551d73f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-core-33e14b8f-1551d73f.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-exp-bd94ab2a-07d0706f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ob-exp-bd94ab2a-07d0706f.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-e7726c58-31c89ed3.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-e7726c58-31c89ed3.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-macs-80cb5a5f-464a67ae.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/org-macs-80cb5a5f-464a67ae.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-latex-a01865ba-9851667e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ox-latex-a01865ba-9851667e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/info+-cc0e6138-06c6750a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/info+-cc0e6138-06c6750a.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/popper-25a2a47e-9e171d68.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/popper-25a2a47e-9e171d68.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/marginalia-10799cda-c5646b3d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/marginalia-10799cda-c5646b3d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/xref-b216d566-333fefb2.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/xref-b216d566-333fefb2.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-xref-268dbd42-5dccf615.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/wgrep-a49bbb0d-c2eb4d3e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/wgrep-a49bbb0d-c2eb4d3e.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-d1db775a-c4e25222.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/consult-d1db775a-c4e25222.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/orderless-17cd36fc-30c6644a.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/orderless-17cd36fc-30c6644a.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/svg-lib-db58c171-3107ab39.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/kind-icon-34c841c2-f74e5ee3.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/kind-icon-34c841c2-f74e5ee3.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/corfu-3efa9e42-700c45a6.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/corfu-3efa9e42-700c45a6.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/tabspaces-4398cd78-3bfb7552.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/tabspaces-4398cd78-3bfb7552.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/lv-caf4dfb1-dff3730b.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/hydra-81b513fe-93b7e0df.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/hydra-81b513fe-93b7e0df.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/avy-1d66f5aa-264e84ed.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/avy-1d66f5aa-264e84ed.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ace-window-68883559-e96e1dae.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/ace-window-68883559-e96e1dae.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/queue-3d5e6610-a3b5d031.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/queue-3d5e6610-a3b5d031.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/undo-tree-d759fed6-0261a5c8.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/undo-tree-d759fed6-0261a5c8.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/pulsar-25f67ab5-8584ac12.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/pulsar-25f67ab5-8584ac12.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/openwith-d5bf4226-51f4d1b7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/fsm-e0721243-710f0b3d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/fsm-e0721243-710f0b3d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/project-aaf87a75-15d943cb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/project-aaf87a75-15d943cb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/projectile-0a8b20cb-90e85a6f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/projectile-0a8b20cb-90e85a6f.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/dash-eb2e492a-bcac85e5.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/dash-eb2e492a-bcac85e5.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/general-8c33ae0a-0dceac76.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/general-8c33ae0a-0dceac76.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/which-key-0a56ec59-a009c002.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/which-key-0a56ec59-a009c002.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/compat-29-a014a96c-52c12079.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/compat-29-a014a96c-52c12079.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-config-6385876b-117d41a7.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/subr--trampoline-77726974652d726567696f6e_write_region_0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/subr--trampoline-6d657373616765_message_0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/subr--trampoline-7265637572736976652d65646974_recursive_edit_0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/git-timemachine-390c69f5-d5dc09f8.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/git-timemachine-390c69f5-d5dc09f8.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/subr--trampoline-64656c6574652d66696c65_delete_file_0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/subr--trampoline-72656e616d652d66696c65_rename_file_0.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/embark-org-8ef0c71d-80e395ac.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/embark-org-8ef0c71d-80e395ac.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/embark-consult-88c4a6d8-2ef3820d.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/embark-consult-88c4a6d8-2ef3820d.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-embark-e492939b-2a157639.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/citar-embark-e492939b-2a157639.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/dired-hacks-utils-3f498c4c-e8a9d371.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/dired-hacks-utils-3f498c4c-e8a9d371.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/dired-rainbow-e878aa9d-1a61956e.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/no-littering-2ab8f401-4ea69799.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/no-littering-2ab8f401-4ea69799.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/setup-4e22418b-18aa29c8.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/setup-4e22418b-18aa29c8.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/a-12e64d46-76433ecb.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/a-12e64d46-76433ecb.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/apheleia-autoloads-c546e8d3-7908822f.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/bash-completion-autoloads-cf1e0c96-d3fca4d5.eln withoutbuild-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/geiser-autoloads-613a333a-51d108db.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/embark-autoloads-97fab8ee-5d497a1c.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/tex-site-e053cdb1-d5261245.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-autoloads-4351d0f8-faddee77.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/guix-emacs-09c25907-4fc13f36.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/map-27841598-2c0f01ed.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/map-27841598-2c0f01ed.eln
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-wip-e80a355e-0371c052.eln without build-id.
Module /home/dc/.emacs.g/eln-cache/29.0.92-198a7ab3/magit-wip-e80a355e-0371c052.eln
Module misc-9bdb6d96-54dcccbc.eln without build-id.
Module windmove-15827e24-37bbb882.eln without build-id.
Module loaddefs-gen-e8a3ad9c-c5d1fe6c.eln without build-id.
Module jka-compr-40ebe92b-5cd9d4ad.eln without build-id.
Module smie-45b5c06f-6e52d466.eln without build-id.
Module mm-url-8379ac94-1f0ab2ea.eln without build-id.
Module eww-08abb1e7-9fea0d87.eln without build-id.
Module css-mode-d9896b30-7047f4b0.eln without build-id.
Module c-ts-common-11d6e279-23c6eec6.eln without build-id.
Module cc-fonts-d7d8a7f5-a00e922f.eln without build-id.
Module cc-guess-fa39ca73-6ba8d298.eln without build-id.
Module cc-menus-d370fa63-d74fb516.eln without build-id.
Module cc-cmds-9eab15be-45674078.eln without build-id.
Module cc-align-bb265728-bffe43dd.eln without build-id.
Module cc-styles-e4992978-ec276cd2.eln without build-id.
Module cc-engine-ccfcb170-8222c05c.eln without build-id.
Module cc-vars-6cc3f0fc-6805ae14.eln without build-id.
Module cc-defs-029877ca-3adcce53.eln without build-id.
Module cc-mode-515a98a5-5b1068ab.eln without build-id.
Module js-ec2c8379-33b765c8.eln without build-id.
Module facemenu-cceb809d-908133c0.eln without build-id.
Module sgml-mode-abd78252-5d125696.eln without build-id.
Module mhtml-mode-1f97c446-93d86314.eln without build-id.
Module conf-mode-547edb00-21b4655a.eln without build-id.
Module tabify-b74f3a50-77296560.eln without build-id.
Module ucs-normalize-ad11ce47-4074380d.eln without build-id.
Module rect-cd288962-47277994.eln without build-id.
Module cl-print-79bf9fb1-a7af75d1.eln without build-id.
Module shortdoc-c079c0cb-3ae66e42.eln without build-id.
Module thunk-5fcb5445-c71565f4.eln without build-id.
Module vc-svn-e027bd39-5e62e277.eln without build-id.
Module info-look-27e24920-374e9f34.eln without build-id.
Module tq-d0106ea7-554f0ff6.eln without build-id.
Module scheme-69dbcaf9-2020f9ff.eln without build-id.
Module view-faefc6b2-6c7c4cab.eln without build-id.
Module cus-edit-3cd01345-cddabe80.eln without build-id.
Module multisession-0e0caee9-a5748dc9.eln without build-id.
Module emoji-aca2d225-557044e2.eln without build-id.
Module face-remap-9d6c47ed-57d1b00c.eln without build-id.
Module disp-table-375616aa-3048566b.eln without build-id.
Module mml2015-2eff3ca9-40bbba1f.eln without build-id.
Module mm-uu-1661a81c-e775caae.eln without build-id.
Module mml-smime-9ca0ce10-1f821516.eln without build-id.
Module dig-9eb56850-18ac17e9.eln without build-id.
Module smime-846b28fb-afd694c2.eln without build-id.
Module mm-view-ea5aa834-4201ed9c.eln without build-id.
Module gnus-art-ba92929b-04d6aea4.eln without build-id.
Module nnselect-763353f0-218d428c.eln without build-id.
Module gnus-undo-97cfb5a4-ec9209a2.eln without build-id.
Module gnus-dbus-711ffae7-0dd55613.eln without build-id.
Module mail-source-6f8fd451-b74e9600.eln without build-id.
Module nnmail-703135a4-433aa39d.eln without build-id.
Module utf7-8aab9346-81c1ae54.eln without build-id.
Module nnoo-1b638390-a6416e67.eln without build-id.
Module nnimap-91c35abc-02f99486.eln without build-id.
Module gnus-cloud-175ba8bd-d7564106.eln without build-id.
Module gnus-spec-87d90d34-f373321a.eln without build-id.
Module gnus-range-becbd692-d7e1188a.eln without build-id.
Module gnus-int-7bc862cf-5c648f67.eln without build-id.
Module gnus-win-9f30cf0f-74622bfe.eln without build-id.
Module gnus-start-e3ba711c-c16682d4.eln without build-id.
Module gnus-group-4173e662-6ff3286c.eln without build-id.
Module gnus-sum-2a5c0016-57ea4775.eln without build-id.
Module dired-aux-1ff8c91a-7e0a2a59.eln without build-id.
Module gnus-dired-4026e813-2d853926.eln without build-id.
Module tree-widget-8dccf6ba-fb03554c.eln without build-id.
Module recentf-3c64dc62-9800186c.eln without build-id.
Module frameset-94504960-f5400acd.eln without build-id.
Module desktop-428f9887-5cd9fe4f.eln without build-id.
Module mule-util-5c349a87-b84378fc.eln without build-id.
Module libpixbufloader-xpm.so without build-id.
Module time-bbe7023e-e43dc814.eln without build-id.
Module rst-174b9993-b5be7942.eln without build-id.
Module timezone-f5339c31-6920ff02.eln without build-id.
Module ido-ccb260dc-0ac567a9.eln without build-id.
Module hl-line-8fa29c14-557901ac.eln without build-id.
Module bibtex-2f037630-146e1f73.eln without build-id.
Module re-builder-54a90c3c-34d86e93.eln without build-id.
Module which-func-fb53504e-1b092713.eln without build-id.
Module smerge-mode-3977987a-6b3f707d.eln without build-id.
Module pcvs-util-35d8f453-77e22550.eln without build-id.
Module add-log-cb3c2979-6f18374e.eln without build-id.
Module log-edit-bc58b2d4-d0c2748a.eln without build-id.
Module comp-cstr-ef162ef7-d5eb9f92.eln without build-id.
Module comp-7672a6ed-83372c53.eln without build-id.
Module cursor-sensor-54079dab-38f36982.eln without build-id.
Module url-gw-93360de5-f6861882.eln without build-id.
Module nsm-c2159ddd-bfc5af5a.eln without build-id.
Module url-http-d4259444-ea165812.eln without build-id.
Module url-auth-088dc9ae-325abcdb.eln without build-id.
Module gnutls-5b82d5da-54cdbc89.eln without build-id.
Module server-0cc44189-4f262c07.eln without build-id.
Module two-column-957d5508-50a71c96.eln without build-id.
Module range-2231b0fa-41d33ea3.eln without build-id.
Module nnheader-94408d86-44dd2d9a.eln without build-id.
Module gnus-a56b3481-d8630102.eln without build-id.
Module bug-reference-79735dad-04499856.eln without build-id.
Module wid-edit-5b92861a-1df476b7.eln without build-id.
Module diff-mode-ac82991e-a79dfe0e.eln without build-id.
Module vc-git-5d6756dc-13ac635c.eln without build-id.
Module fileloop-f8cb1238-ad5ca0c9.eln without build-id.
Module etags-fc6f38d6-9ec8035f.eln without build-id.
Module edebug-ddc96ebf-188401f6.eln without build-id.
Module radix-tree-669a468d-a0a70c74.eln without build-id.
Module help-fns-d233c6e8-b16fcc3e.eln without build-id.
Module mode-local-52e88da7-02e4f4e0.eln without build-id.
Module sendmail-bcf4df3f-8b79cb33.eln without build-id.
Module yank-media-62540c94-4baa40a7.eln without build-id.
Module rfc822-a91daeff-745fe122.eln without build-id.
Module epa-bdd8ea1c-6bb9ad46.eln without build-id.
Module gnus-util-b645aa9c-63d9ce85.eln without build-id.
Module mml-sec-827872f6-223802af.eln without build-id.
Module mm-decode-4a4c16d8-04aed347.eln without build-id.
Module mm-encode-4f0ce800-c4aebf9b.eln without build-id.
Module mm-bodies-5a92b2dc-8642349c.eln without build-id.
Module mml-34028078-84691b14.eln without build-id.
Module rfc2045-713c994b-f037c7c2.eln without build-id.
Module mm-util-3a4439f0-94d75bf4.eln without build-id.
Module rfc2047-b84e264d-b472d172.eln without build-id.
Module rfc2231-e2cbed75-a66ae74a.eln without build-id.
Module ietf-drums-23d9ecfe-c5fce4ab.eln without build-id.
Module mail-parse-5e7f4583-77dd5d0b.eln without build-id.
Module mailabbrev-287b6d20-3b84f5ac.eln without build-id.
Module mail-utils-ae525238-e2ef234f.eln without build-id.
Module gmm-utils-3a9b481d-38db56d1.eln without build-id.
Module mailheader-2dff755b-ad366585.eln without build-id.
Module message-4a315c5a-c83065f7.eln without build-id.
Module kinsoku-dd85875c-9d007cd2.eln without build-id.
Module pixel-fill-83d963be-fd97e6d0.eln without build-id.
Module puny-eb5a151f-210e82a0.eln without build-id.
Module shr-375ad325-340270b9.eln without build-id.
Module url-file-f44a48ab-6e0b7877.eln without build-id.
Module url-queue-4e80de45-e068c3c9.eln without build-id.
Module kmacro-048feaec-d1283377.eln without build-id.
Module edmacro-74bf45a3-8d67d033.eln without build-id.
Module dbus-f1406cab-22a38894.eln without build-id.
Module crm-f08665f2-485fb271.eln without build-id.
Module derived-381801a7-d8d463bc.eln without build-id.
Module tramp-container-a89fad9e-61a4a03c.eln without build-id.
Module align-da164663-c2905ef9.eln without build-id.
Module trampver-0d42d995-84b3c1c4.eln without build-id.
Module files-x-59c65c89-fa9baed9.eln without build-id.
Module tramp-integration-58d1aa20-9bff0925.eln without build-id.
Module iso8601-3903451a-ec9df93a.eln without build-id.
Module parse-time-ca7017be-8839d080.eln without build-id.
Module tramp-compat-fa04d39a-45088130.eln without build-id.
Module tramp-b5a14372-3a079ab9.eln without build-id.
Module external-completion-79d0c54a-a99b576e.eln without build-id.
Module array-b56b5eac-6795821a.eln without build-id.
Module ewoc-6e3ae0bf-a0668d83.eln without build-id.
Module backtrace-f58a28c5-0f89deb7.eln without build-id.
Module debug-bee52b4d-63a033ac.eln without build-id.
Module ert-786c6677-f6fd07ba.eln without build-id.
Module jsonrpc-e62a9c36-b02cc544.eln without build-id.
Module flymake-proc-bba228e0-e1e2d044.eln without build-id.
Module flymake-a41dd277-ddccfc08.eln without build-id.
Module warnings-28e75f4d-9f48f568.eln without build-id.
Module eglot-3726620f-b9a8ea1c.eln without build-id.
Module libstdc++.so.6 without build-id.
Module finder-cfd3373c-7a88257d.eln without build-id.
Module treesit-37439c61-bbcaaf50.eln without build-id.
Module python-4c762d55-23be20fa.eln without build-id.
Module shell-57930f41-f71493fe.eln without build-id.
Module ffap-4b3c5789-a2cc06fe.eln without build-id.
Module rng-uri-795a248e-6ae2b48f.eln without build-id.
Module rng-dt-6f4fabb6-c05e9130.eln without build-id.
Module rng-util-407ca456-c7fe17bc.eln without build-id.
Module rng-pttrn-3f46aa75-00f04d4b.eln without build-id.
Module rng-match-9f8fba20-d54c3bd1.eln without build-id.
Module rng-parse-fda9b375-1194fcdb.eln without build-id.
Module nxml-ns-c16d094f-3269aeea.eln without build-id.
Module nxml-enc-00fb01f2-a896ded2.eln without build-id.
Module xmltok-b50d69e4-61d0042b.eln without build-id.
Module nxml-parse-79a53381-cd587b64.eln without build-id.
Module nxml-util-19d2b98f-70864b6a.eln without build-id.
Module rng-loc-798ea863-2f72446d.eln without build-id.
Module table-353c93e5-d1c4fda2.eln without build-id.
Module pcomplete-81dbd8b0-9a037df6.eln without build-id.
Module time-date-40951a48-1eb9e3cd.eln without build-id.
Module icons-eafe82eb-be7de92f.eln without build-id.
Module outline-afc41f82-066bb392.eln without build-id.
Module find-func-64af57a4-815b28b8.eln without build-id.
Module cal-menu-9380b697-647bd434.eln without build-id.
Module calendar-d19e5c14-6c1c0829.eln without build-id.
Module generator-184aa77f-9c05f632.eln without build-id.
Module avl-tree-508a9d96-de4f3761.eln without build-id.
Module format-spec-644c0068-ff3af71f.eln without build-id.
Module advice-791b3e89-06651e7a.eln without build-id.
Module rfc6068-5e4d60aa-c483e825.eln without build-id.
Module epg-config-78240760-38c79fd9.eln without build-id.
Module epg-de089247-51e2ca0b.eln without build-id.
Module pp-5d47c1cc-03017ab4.eln without build-id.
Module bookmark-8667481e-02a71f6a.eln without build-id.
Module dom-a7939831-2046ec62.eln without build-id.
Module xml-78b9f1ba-ad52d7d9.eln without build-id.
Module svg-4c391752-62735252.eln without build-id.
Module dired-x-a2e5c184-23280968.eln without build-id.
Module vc-dispatcher-d82eb341-4d115b2a.eln without build-id.
Module vc-d8599e21-ab31d8d2.eln without build-id.
Module winner-c3a8b092-bf14fd1f.eln without build-id.
Module diff-b728f3ea-04f1f755.eln without build-id.
Module delsel-1c603c42-f1705396.eln without build-id.
Module easy-mmode-5bf0223e-4f8b421a.eln without build-id.
Module display-fill-column-indicator-82af8525-d0e01803.eln without build-id.
Module pcase-394c5744-2b285a4c.eln without build-id.
Module color-9d7980a5-7c0ccd21.eln without build-id.
Module pulse-35e729a5-4edf0306.eln without build-id.
Module imenu-a6693d03-93faffd4.eln without build-id.
Module savehist-b722b772-1aa696ac.eln without build-id.
Module filenotify-65939d6e-37a89cc5.eln without build-id.
Module autorevert-841d6890-266659fa.eln without build-id.
Module lisp-mnt-2b554e27-a9229008.eln without build-id.
Module grep-c9b5c28d-67a4c46c.eln without build-id.
Module text-property-search-db1383f6-ba5a2f0b.eln without build-id.
Module ansi-osc-b447f6a8-03cbba92.eln without build-id.
Module ansi-color-75eac800-8d1cfab0.eln without build-id.
Module ring-bff0b981-416eb898.eln without build-id.
Module comint-faef15ad-7c1d6023.eln without build-id.
Module compile-91e1c2a0-3cce2e0c.eln without build-id.
Module ibuf-ext-5624402a-7c41e962.eln without build-id.
Module ibuffer-c2dc0626-f3e33903.eln without build-id.
Module thingatpt-6fc8a4ab-65d35683.eln without build-id.
Module dired-6a3ae2bc-c728d61d.eln without build-id.
Module help-mode-d4dbae3d-8359eb28.eln without build-id.
Module cl-extra-d7051cba-0a9e5f3e.eln without build-id.
Module xdg-9947111f-7307f28d.eln without build-id.
Module eieio-base-3621993d-91fcbace.eln without build-id.
Module auto-aad53e20-9d44d232.eln without build-id.
Module rx-627d8c83-b295429d.eln without build-id.
Module info-ce12c0ca-653829c4.eln without build-id.
Module url-proxy-fc0751f0-599d5d23.eln without build-id.
Module url-privacy-7df6b777-dc416da4.eln without build-id.
Module url-methods-08bf763a-6102fe8b.eln without build-id.
Module url-expand-cf7ffc4e-d906363b.eln without build-id.
Module url-history-a9b2f6e8-3212054d.eln without build-id.
Module generate-lisp-file-20e31f41-8ca1f9d3.eln without build-id.
Module url-domsuf-beabcbfe-f27bd1b2.eln without build-id.
Module url-util-28122a93-0af885fe.eln without build-id.
Module url-cookie-02b28750-43a16a0b.eln without build-id.
Module mailcap-a1205653-6c9acee8.eln without build-id.
Module url-38944b26-fc3efcbc.eln without build-id.
Module browse-url-87f72988-0cb34386.eln without build-id.
Module cl-seq-f464c4e2-5f2e2b69.eln without build-id.
Module cl-macs-7ae82f81-e626a10e.eln without build-id.
Module eieio-core-63c05904-7d08efc3.eln without build-id.
Module eieio-0db8d1d4-24b50c02.eln without build-id.
Module password-cache-187e4eec-01cf807d.eln without build-id.
Module subr-x-02dfef32-1fdbddc8.eln without build-id.
Module byte-opt-9c5f25f5-d441f0f7.eln without build-id.
Module gv-e0cf7478-b0ac3b13.eln without build-id.
Module bytecomp-12882072-78ca9715.eln without build-id.
Module json-a90a1eab-a324d5a3.eln without build-id.
Module auth-source-49df7eef-5f9f1f33.eln without build-id.
Module url-vars-04b97511-6665993a.eln without build-id.
Module url-parse-ee297c9b-4da42516.eln without build-id.
Module url-handlers-8b35c993-e36982de.eln without build-id.
Module cl-lib-8b938900-a81a0c7c.eln without build-id.
Module package-14201d8e-2efc3002.eln without build-id.
Module hebrew-b9ed6a0d-135c9dc3.eln without build-id.
Module indian-0c4ce628-3242b0c1.eln without build-id.
Module debug-early-d734b212-a3e3837a.eln without build-id.
Module dynamic-setting-55f80457-43cc97d6.eln without build-id.
Module shorthands-1dc1e95e-1a94337e.eln without build-id.
Module rmc-9c382b5d-def97b0e.eln without build-id.
Module misc-lang-7cb33d20-e47b7d86.eln without build-id.
Module iso-transl-466860a2-970c19c5.eln without build-id.
Module cconv-3b1f1f98-980f995e.eln without build-id.
Module european-369de593-05389032.eln without build-id.
Module mwheel-168e9ec3-f1225697.eln without build-id.
Module jit-lock-8a988e43-651f5ec8.eln without build-id.
Module rfn-eshadow-25788e78-cfaff2d4.eln without build-id.
Module cus-start-26315480-b4dee053.eln without build-id.
Module map-ynp-990591b5-4ed41887.eln without build-id.
Module version-025f5cb3-b454efa3.eln without build-id.
Module page-ee7241cc-3a324cb4.eln without build-id.
Module case-table-3a8e2808-5e98b061.eln without build-id.
Module tooltip-29462ede-2a67f34c.eln without build-id.
Module fontset-da863153-8ee15fef.eln without build-id.
Module common-win-4b869e38-e45e9a3a.eln without build-id.
Module pgtk-win-9e6b24f1-72bd48d8.eln without build-id.
Module select-784d9bb7-cacf2d60.eln without build-id.
Module menu-bar-4f46ea94-9cdef28e.eln without build-id.
Module buff-menu-da4b0b04-f9de971e.eln without build-id.
Module composite-beea1fd5-f3e6c657.eln without build-id.
Module regexp-opt-d2355c94-59498e32.eln without build-id.
Module prog-mode-642b2411-4da38487.eln without build-id.
Module nadvice-64630aaa-6d0a5207.eln without build-id.
Module easymenu-1fb41c0e-c8daf6b0.eln without build-id.
Module text-mode-7f741068-e610ba61.eln without build-id.
Module epa-hook-99ab3afb-65e80994.eln without build-id.
Module obarray-318a5d56-99c3ddb9.eln without build-id.
Module pgtk-dnd-6859c677-23dfb949.eln without build-id.
Module paren-0f414553-69cf0906.eln without build-id.
Module abbrev-2af30c9a-6540a9da.eln without build-id.
Module startup-bbc6ea72-10e8addb.eln without build-id.
Module button-747c9d6e-f1e1dcc9.eln without build-id.
Module image-f221b419-e444a9af.eln without build-id.
Module lisp-1e88867d-01a98926.eln without build-id.
Module electric-a9ca6cdd-df8c4d49.eln without build-id.
Module paragraphs-faf2e9b4-10379566.eln without build-id.
Module fill-19d89c43-ff5985ac.eln without build-id.
Module tool-bar-ae0b5bc0-2100bc40.eln without build-id.
Module oclosure-b279097d-e6802564.eln without build-id.
Module elisp-mode-90dbfe40-1c21c6df.eln without build-id.
Module seq-c314b42f-2019ac31.eln without build-id.
Module scroll-bar-20650688-c89305e3.eln without build-id.
Module tty-colors-b7804baf-4c9f637b.eln without build-id.
Module timer-3ee7cfd9-7286ad5c.eln without build-id.
Module indent-396b3792-4c878d88.eln without build-id.
Module uniquify-0fb233ac-905b038c.eln without build-id.
Module syntax-bf4e4bc4-34d5fac7.eln without build-id.
Module tab-bar-f81d329c-84eaaeb6.eln without build-id.
Module dnd-12d90309-a7634b4f.eln without build-id.
Module env-72406999-9c6395ca.eln without build-id.
Module mule-cmds-c8553014-9858784e.eln without build-id.
Module widget-5b69ebb0-f2151df1.eln without build-id.
Module characters-45232aae-5cff94fe.eln without build-id.
Module isearch-693bdd75-60330646.eln without build-id.
Module cus-face-74f1689e-e975f99d.eln without build-id.
Module font-lock-895216f6-23fb5060.eln without build-id.
Module font-core-c3bff1fd-834a0f96.eln without build-id.
Module keymap-b4249274-a50ba8ee.eln without build-id.
Module files-1e8937b2-a33dbe54.eln without build-id.
Module jka-cmpr-hook-ff630d3e-7faaee46.eln without build-id.
Module cl-generic-be68ad15-5c514263.eln without build-id.
Module cl-preloaded-6e6a1f4e-24bc04cc.eln without build-id.
Module backquote-d5b20f7c-12335336.eln without build-id.
Module faces-b9447c93-81f63e21.eln without build-id.
Module tabulated-list-552ba1e5-0286342e.eln without build-id.
Module newcomment-678006bb-5bfa2117.eln without build-id.
Module bindings-d30713c5-2dd57da8.eln without build-id.
Module vc-hooks-cfa0878e-801eee12.eln without build-id.
Module mule-3352613d-5a32cafd.eln without build-id.
Module frame-b40fc590-50da48e8.eln without build-id.
Module help-59d8049f-7bd75386.eln without build-id.
Module fringe-d5d49a60-c0441738.eln without build-id.
Module custom-c166a157-13bf9880.eln without build-id.
Module minibuffer-1b0f548b-27970567.eln without build-id.
Module format-c5b23b0d-bb653605.eln without build-id.
Module subr-13adf6a6-1ad09b0b.eln without build-id.
Module mouse-15f283fa-a7101cf9.eln without build-id.
Module window-0d1b8b93-6f4eee58.eln without build-id.
Module macroexp-2c3e1495-97015f65.eln without build-id.
Module replace-fc551dbc-3f1cdd51.eln without build-id.
Module eldoc-d20a5fe9-5a429187.eln without build-id.
Module lisp-mode-410874a4-8e379a7a.eln without build-id.
Module byte-run-79ff048e-f73ac104.eln without build-id.
Module simple-fab5b0cf-bcd3ba95.eln without build-id.
Module register-80045398-74c9598f.eln without build-id.
Module libblkid.so.1 without build-id.
Module libdatrie.so.1 without build-id.
Module libatspi.so.0 without build-id.
Module libmpfr.so.6 without build-id.
Module libmpc.so.3 without build-id.
Module libisl.so.23 without build-id.
Module libcap.so.2 without build-id.
Module libhogweed.so.6 without build-id.
Module libnettle.so.8 without build-id.
Module libtasn1.so.6 without build-id.
Module libunistring.so.2 without build-id.
Module libidn2.so.0 without build-id.
Module libp11-kit.so.0 without build-id.
Module libpcre2-8.so.0 without build-id.
Module libattr.so.1 without build-id.
Module libbz2.so.1.0 without build-id.
Module libexpat.so.1 without build-id.
Module libXdmcp.so.6 without build-id.
Module libXau.so.6 without build-id.
Module ld-linux-x86-64.so.2 without build-id.
Module liblzma.so.5 without build-id.
Module libpcre.so.1 without build-id.
Module libffi.so.8 without build-id.
Module libmount.so.1 without build-id.
Module libXrender.so.1 without build-id.
Module libxcb-render.so.0 without build-id.
Module libxcb.so.1 without build-id.
Module libxcb-shm.so.0 without build-id.
Module libpixman-1.so.0 without build-id.
Module libgraphite2.so.3 without build-id.
Module libthai.so.0 without build-id.
Module libXinerama.so.1 without build-id.
Module libXrandr.so.2 without build-id.
Module libXcomposite.so.1 without build-id.
Module libXdamage.so.1 without build-id.
Module libXcursor.so.1 without build-id.
Module libXext.so.6 without build-id.
Module libwayland-egl.so.1 without build-id.
Module libwayland-cursor.so.0 without build-id.
Module libwayland-client.so.0 without build-id.
Module libxkbcommon.so.0 without build-id.
Module libXfixes.so.3 without build-id.
Module libcloudproviders.so.0 without build-id.
Module libatk-bridge-2.0.so.0 without build-id.
Module libX11.so.6 without build-id.
Module libXi.so.6 without build-id.
Module libepoxy.so.0 without build-id.
Module libfribidi.so.0 without build-id.
Module libpangoft2-1.0.so.0 without build-id.
Module libgmodule-2.0.so.0 without build-id.
Module libc.so.6 without build-id.
Module libgcc_s.so.1 without build-id.
Module libsqlite3.so.0 without build-id.
Module libtree-sitter.so.0 without build-id.
Module libgccjit.so.0 without build-id.
Module libgmp.so.10 without build-id.
Module libjansson.so.4 without build-id.
Module libelogind.so.0 without build-id.
Module liblcms2.so.2 without build-id.
Module libanl.so.1 without build-id.
Module libgnutls.so.30 without build-id.
Module libotf.so.1 without build-id.
Module libfontconfig.so.1 without build-id.
Module libfreetype.so.6 without build-id.
Module libselinux.so.1 without build-id.
Module libncursesw.so.6 without build-id.
Module libxml2.so.2 without build-id.
Module libdbus-1.so.3 without build-id.
Module libacl.so.1 without build-id.
Module libm.so.6 without build-id.
Module librsvg-2.so.2 without build-id.
Module libasound.so.2 without build-id.
Module libgif.so.7 without build-id.
Module libpng16.so.16 without build-id.
Module libjpeg.so.62 without build-id.
Module libtiff.so.5 without build-id.
Module libglib-2.0.so.0 without build-id.
Module libgobject-2.0.so.0 without build-id.
Module libgio-2.0.so.0 without build-id.
Module libgdk_pixbuf-2.0.so.0 without build-id.
Module libcairo.so.2 without build-id.
Module libcairo-gobject.so.2 without build-id.
Module libatk-1.0.so.0 without build-id.
Module libharfbuzz.so.0 without build-id.
Module libpango-1.0.so.0 without build-id.
Module libpangocairo-1.0.so.0 without build-id.
Module libz.so.1 without build-id.
Module libgdk-3.so.0 without build-id.
Module libgtk-3.so.0 without build-id.
Module .emacs-29.0.92-real without build-id.
Stack trace of thread 3202216:
#0  0x00007f1db8f44fec __pthread_kill_implementation (libc.so.6 + 0x86fec)
#1  0x00007f1db8efb202 raise (libc.so.6 + 0x3d202)
#2  0x00000000004241b3 n/a (.emacs-29.0.92-real + 0x241b3)
#3  0x000000000042467d n/a (.emacs-29.0.92-real + 0x2467d)
#4  0x000000000052bad8 n/a (.emacs-29.0.92-real + 0x12bad8)
#5  0x000000000052bb49 n/a (.emacs-29.0.92-real + 0x12bb49)
#6  0x00007f1db8efb2a0 __restore_rt (libc.so.6 + 0x3d2a0)
#7  0x00007f1dbc4d1794 n/a (libgobject-2.0.so.0 + 0x28794)
#8  0x00007f1dbc4d7689 g_signal_emit_valist (libgobject-2.0.so.0 + 0x2e689)
#9  0x00007f1dbc4d7bb2 g_signal_emit (libgobject-2.0.so.0 + 0x2ebb2)
#10 0x00007f1dbc4c39a4 n/a (libgobject-2.0.so.0 + 0x1a9a4)
#11 0x00007f1dbc4c5a34 g_object_notify_by_pspec (libgobject-2.0.so.0 + 0x1ca34)
#12 0x00007f1dbcd8e6ad gtk_window_set_mnemonics_visible (libgtk-3.so.0 + 0x38e6ad)
#13 0x00007f1dbcd8e75c n/a (libgtk-3.so.0 + 0x38e75c)
#14 0x00007f1dbd270a39 n/a (libgdk-3.so.0 + 0x33a39)
#15 0x00007f1dbc3c93b4 n/a (libglib-2.0.so.0 + 0x563b4)
#16 0x00007f1dbc3c8894 g_main_context_dispatch (libglib-2.0.so.0 + 0x55894)
#17 0x00000000006400b8 n/a (.emacs-29.0.92-real + 0x2400b8)
#18 0x00000000005f3a39 n/a (.emacs-29.0.92-real + 0x1f3a39)
#19 0x0000000000437c60 n/a (.emacs-29.0.92-real + 0x37c60)
#20 0x000000000051e0c6 n/a (.emacs-29.0.92-real + 0x11e0c6)
#21 0x000000000051e952 n/a (.emacs-29.0.92-real + 0x11e952)
#22 0x00000000005205a2 n/a (.emacs-29.0.92-real + 0x1205a2)
#23 0x0000000000595c47 n/a (.emacs-29.0.92-real + 0x195c47)
#24 0x000000000050c76a n/a (.emacs-29.0.92-real + 0x10c76a)
#25 0x0000000000595ba1 n/a (.emacs-29.0.92-real + 0x195ba1)
#26 0x000000000050c70f n/a (.emacs-29.0.92-real + 0x10c70f)
#27 0x0000000000513663 n/a (.emacs-29.0.92-real + 0x113663)
#28 0x00000000005139da n/a (.emacs-29.0.92-real + 0x1139da)
#29 0x000000000042d132 n/a (.emacs-29.0.92-real + 0x2d132)
#30 0x00007f1db8ee71f7 __libc_start_call_main (libc.so.6 + 0x291f7)
#31 0x00007f1db8ee72ac __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x292ac)
#32 0x000000000042d601 n/a (.emacs-29.0.92-real + 0x2d601)

Stack trace of thread 3202217:
#0  0x00007f1db8fb7d6f __poll (libc.so.6 + 0xf9d6f)
#1  0x00007f1dbc3c8b96 n/a (libglib-2.0.so.0 + 0x55b96)
#2  0x00007f1dbc3c8c9f g_main_context_iteration (libglib-2.0.so.0 + 0x55c9f)
#3  0x00007f1dbc3c8cf1 n/a (libglib-2.0.so.0 + 0x55cf1)
#4  0x00007f1dbc3f1d0d n/a (libglib-2.0.so.0 + 0x7ed0d)
#5  0x00007f1db8f433aa start_thread (libc.so.6 + 0x853aa)
#6  0x00007f1db8fc3f7c __clone3 (libc.so.6 + 0x105f7c)
ELF object binary architecture: AMD x86-64

#+end_quote


* Roam
+ [[id:6f769bd4-6f54-4da7-a329-8cf5226128c9][Emacs]]
