:PROPERTIES:
:ID:       e71df0e8-ee33-4649-811b-c98b9ecfcc5d
:END:
#+TITLE: Marshall McLuhan, Cybernetics, Linguistics and Semiotics
#+CATEGORY: slips
#+TAGS:

Since literacy has skyrocketed, languages have grown more fixed in place: we've
accumulated normative rules and even social/cultural institutions for specifying
the rules, in language. Marshal McLuhan's Lost Tetrads, he describes how a
reprioritization of visual senses changed the range of sensory signals that
people typically process when forming belief & knowledge from information &
experiences.

#+begin_quote
In the age of non-Euclidean geometries ... it is quite easy to see that the
Greeks had separated out visual space from the many other kinds of space in
setting up geometry. *Visual space has the unique properties of uniformity,
continuity and connectedness.*
#+end_quote

A curse of dimensionality affects how the brain perceives what is real or
knowable when primarily relying on visual information. Visual sensory signals
are intrinsically connected to time and physical space: thus the optic nerves
from the retina through the chiasm through the occipital lobe have very little
flexibility in determining what is apprehended by the visual senses. Once people
begin to accumulate knowledge primarily through visual reproduction and
language, this fundamentally changes how people process their
experiences/memories.

A similar effect occurs when a person considers reality according to their
personal set of knowledge -- i.e. when someone is reasoning primarily through
Logos. The more you think you know, often the harder it is to change your
worldview or break out of cognitive biases. The self-reinforcing constraints
imposed by reason (your connection to Logos) prevent you from "seeing" anything
else. Writing, literature and various forms of media only provide more
informational or epistemic constraints.

McLuhan continues:

#+begin_quote
Pre-literate man lives primarily in the audile-tactile world of the resonant
interval which is now familiar to us from the new quantum mechanics.
#+end_quote

I'm not exactly sure what he means here by quantum mechanics, though it's
interesting to fill in the gaps. He may be pointing to entanglement/probability
or uncertainty or an inability to communicate without causal influence. The
third possibility would highlight auditory/tactile forms of communication with
written forms. In the latter, the writer/reader are far closer to developing
consensus on what the other has communicated/interpreted almost exactly. In the
former, you cannot express spoken words without taking some action whose effects
"leak" into non-verbal, tactile, or contextual channels of communication.
Reproductions of voice and video may be another matter, but the viewer/listener
is still /experiencing/ the message through sensory means instead of /knowing/
the written meaning of the message where most of what's happening in cognition
is filtered through layers of written/linguistic abstractions and prior
knowledge/belief.

How a brain/mind develop without the written word (or before the written word)
is fascinating ... though controversial. The mediums through which we experience
life have a profound effect on:

+ how we experience life
+ whether norms converge or diverge
+ how we develop psychologically
+ how plastic or constrained our thought can be
+ whether hope or fear are scarce or easily found
+ whether we become trapped by despair or whether we need faith in a path we
  can't see yet

#+begin_quote
to clarify, i mean, faith considered existentially as a path towards hope when
things seem hopeless or, worse, when we "know" things to be hopeless.
#+end_quote

It's interesting if you're inclined to believe that sensory issues like
blindness/deafness may alter development, redirecting how people think and
ultimately contributing value to humanity as a whole through
neurological/psychological diversity. Someone who has challenges with mobility
must think much harder about social relationships. They have to ascertain things
from a distance which prioritizes other information/facts as valuable. In some
cases, perhaps some people are transformed through such constraints and develop
unique and valuable skills which otherwise may be nearly impossible.

That said, it's obviously cold/detached to think about this. It's likely
incredibly different in every situation, but that's the diversity. Who knows
what it is like? I don't know anyone unfortunately :(

* Roam
+ [[id:5bb2016d-f38e-4a0b-9678-b024973fe1dc][Linguistics]]
