:PROPERTIES:
:ID:       0f61135c-084e-44f7-900d-730b0b1bf723
:END:
#+TITLE: Guix: Building Go Modules
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:b82627bf-a0de-45c5-8ff4-229936549942][Guix]]
+ [[id:abd2d6e9-fe5b-4ba4-8533-0e5a3d174743][Golang]]
  
* Notes
For builds where =go mod download= requires many dependencies:

See [[https://www.reddit.com/r/GUIX/comments/13it1w9/go_with_gigantic_dependencies/][Go with gigantic dependencies]] where the author built:

+ (balulig build-system [[https://gitlab.com/martin-baulig/config-and-setup/guix-packages/-/blob/main/packages/baulig/build-system/go-module.scm][go-module]])
+ (baulig build [[https://gitlab.com/martin-baulig/config-and-setup/guix-packages/-/blob/main/packages/baulig/build/go-module-build-system.scm][go-module-build-system]])
+ (baulig packages [[https://gitlab.com/martin-baulig/config-and-setup/guix-packages/-/blob/main/packages/baulig/multi-fetch.scm][multi-fetch]])
+ (baulig packages [[https://gitlab.com/martin-baulig/config-and-setup/guix-packages/-/blob/main/packages/baulig/packages/gitlab-runner.scm][gitlab-runner]])

This approach may break reproducibility, but resolves an issue with go's
dependency specifications. A lot of great projects require pinned/forked
versions of even fairly standard dependencies -- e.g. step-ca, sops, hashicorp,
k8s. To me, it seems like anything with go modules can't reference current Guix
packages as dependencies without a ton of transformations, most of which
wouldn't fetch substitutes.

The author's channel has a ton of functionality that extends Guix at fairly low
levels. Lots of good stuff here:

+ Bacula for backups (on a synology VM)
+ GSSAPI for NFSv4 towards using the Kerberos features
+ A scheduler using scheme/sqlite

And elsewhere, this user has an =xkb-mode= for Emacs... which apparently is not
indexed by google, since I regularly search for it every year or so (last
searched about a month ago).


