:PROPERTIES:
:ID:       91056d16-0693-4954-b788-47e52d82c051
:END:
#+TITLE: File Systems: Managing Cloud/File Storage
#+CATEGORY: slips
#+TAGS:

* Resources



** FS Dedupe

*** [[github:qarmin/czkawka][qarmin/czkawka]]

For deduping files quickly, see the czkawka project, which also lists [[https://github.com/qarmin/czkawka#other-apps][similar
apps]] like FSLint

*** [[https://github.com/luxagen/RotKraken][RotKraken]]

For more advanced uses. RotKraken will build a database of hashes that can be
used for deduping.

* Notes

** FS Dedupe

I couldn't find much the last time I looked, but this episode of [[https://share.transistor.fm/s/f22c961a][Rust Workshop]]
talks alot about RotKraken which is a similar tool.

Autopsy, SleuthKit and other forensic tools are not really tuned to solve casual
dedupe.

Autopsy/TSK set up a Postgres database and require knowledge to integrate
specific plugins. so to do the following requires planning image management and
custom reworking of db records (like separate database for query results)

+ if you start a new forensics session or change mounts
+ if you're comparing records across multiple servers
+ if you want to change how your files are organized in a big way: tree
  traversal in SQL is slow and maybe painful ... hashes don't index well by
  default in tables.

** Storage

#+begin_quote
originally from a discord response. somewhat edited, but there's no identifying
info in here, so otherwise it disappears.
#+end_quote

Is it Google Drive or Cloud storage? I mostly keep storage off the cloud, except for specific files.

This has some recommendations for Google Drive:

https://support.google.com/drive/thread/22991034/what-s-eating-up-my-google-drive-storage?hl=en

+ I just checked mine though and i'm using like 10 GB out of 15 GB for
  email. it's mostly spam mail and small stuff. there are many unnecessarily
  large PDF's though.
+ You can sort by size and there are more advanced filters for things like this,
  but depending on whether it's Drive or Mail, then it might not help much.
+ I'm not sure about Android, but some iOS apps will back up data to iCloud,
  including a snapshot of the application binary. my iPhone fills up with
  podcasts, but content like that I have set to not sync.
+ If you're sharing the storage with others, then that can be complicated.
+ it's a really good idea to just delete anything you don't plan on keeping
  (except email)

For any storage problem, it's smart to look for apps, but they're usually
specific to the platform/context.

+ This one is for cloud https://deduplicate.app/ but there are others for
  desktop/etc.
+ They will probably hash your files (it's required to identify unique
  files)... but this could enable someone to determine whether you have a
  specific copy of a file.
+ You can basically do the same thing with other tools by pulling the Drive to
  disk and deduping, then overwriting, but you might lose data.

  I run into this alot since I don't depend on the cloud.

+ I use syncthing a bit at home, but it's a bit complicated and not exactly
  secure by default (passwords in your home directory, etc)
+ There are more complicated options like nextcloud which is for homelabs, but
  for anything like that, just expect to put in 10x - 40x the amount of time you
  plan to 😅 I haven't tried it, but...
+ I don't trust network storage without a firewall. Putting it on the router may
  be like keeping your valuables in your mailbox or inside your front door
+ If you put a fileshare on a router, it probably has USB 2.0, but even if it's
  3.0, the CPU probably can't handle the load.

The main problem you'll run into is creating additional copies of files that can
be hard to dedupe.

+ To avoid that, you just have to figure out what types of files/content you
  have and where things are going to live
+ If you're going to do anything with commandline, then invest some time in
  learning rsync. you have to use the command switches, but it takes care of
  most everything for you basically.

if you want privacy, it will eat all your time (i do it mostly for irony) i
would definitely recommend avoiding small/slow drives! no less than 2TB SSD,
since you really need to look for more storage when it gets around 40% (esp. if
you want to back up an image)

anyways, i've spent a ton of time on shuffling files around small drives
(translation: if anyone has suggestions generally, I could use some pointers
lol)

it's a fucking PITA, no matter where the data lives. with the cloud, you have
more storage, but then you're nickeled/dimed and it's complicated to change
service providers.

* Roam
+ [[id:d7cc15ac-db8c-4eff-9a1e-f6de0eefe638][File Systems]]
