:PROPERTIES:
:ID:       b363c893-4236-460d-9545-59ac58464e30
:END:
#+TITLE: Social Media: Fear, Memory and Awareness of Time
#+CATEGORY: slips
#+TAGS:

If maybe people actually cared as much about political issues as the claim to,
they would be on the sites listed in [[id:0e36af9c-a6ef-45ef-8940-b8ca1108b193][US Code]]. I'm a bit agorist so the political
system is intrinsically flawed and is something to avoid relying on if at all
possible and to cleverly counter if necessary. But if you want to affect things,
sharing on social media advances almost no meaningful changes other than to
generally increase the population's cortisol levels, while diffision the social
"free energy" people could otherwise invest in real change.

But oh no your cable news show might lose viewers because they showed a bar
graph ... never happens does it?

* Fear is the mind-killer

What does that phrase mean? IMO, it is the single story that Frank Herbert
prioritized above everything else in his Dune series.

Obviously, there is the pain that Paul experiences and we cannot help but
intuitively focus on the pain. The writing drives us there as does the
cinematographyorg acting. As well as our instinct to see/empathize with the pain
of others.

You may want to watch this before you continue.

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/aTjUzT-xto4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+end_export

How long does this scene last? How long does it feel?

More critically, what were you looking at:

+ Paul's face?
+ The box?
+ The Gom Jabbar? (the threat)
+ The person enacting the threat and pain?

Did you see the guy in the gorilla suit? How much of the visual field can you
recall without watching it again?

** What does it mean to be mindful?

Think a bit on the literal meaning of mind-full-ness... play with it a bit.

Striving for real goals requires long-term commitment and strategy requires
broadening your awareness beyond your immediate moment. Though endemic in social
networks whether IRL or digital, feedback loops in media diffuse the
population's energy by fixating the population's attention onto a limited set of
topics which are forgotten in three day's time.

Whenever your visual awareness is limited to a small space and your mental
awareness is limited to a small time horizon, this is almost identical to being
in a state of fear. Though being zoned in to social media doesn't seem like a
"fearful" state:

+ What are the primary neurotransmitters responsible for compulsive use of
  social media?
+ What are the downstream hormones that are released?

Sensory flows into the amygdala then prioritize cognitive capacity to shift
towards attending to these signals. Usually a fear-inducing stimulus requires
switching gears (interrupt request) to control sensory/motor organs in order to
aquire more information. At this point, the range of time/space over which an
animal's mind is focused narrows until it can ascertain the nature/authenticity
of the stimulus. This narrowing of the mind that provides focus/speed can also
put the animal at risk, for the solutions to the animal's problem almost never
rely solely in developing awareness of the threat. Instead, the mind needs to
rebalance and open up its awareness to a broader region of time and space
(avenues of escape or places associated with options/maneuverability to survive)

We don't usually associate the capacity of living things to feel emotions as
being associated with older "lizard brain." However, the increasing
sophistication in how mammals, primates and humans (1) regulate emotions (2)
mediate cognitive state using the prefrontal cortex and (3) manipulate
environment distinguishes these animals from the "smooth-brained" animals. (give
me a break, I don't have all day to spend on this)

[[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4169316/][Bidirectional switch of the valence associated with a hippocampal contextual
memory engram]]

I didn't fully read that but it does seem to illustrate my point that stimuli in
the amygdala are a bit hardwired into the hippocampus -- this also explains the
tendency of strong emotions to "wipe the state" in short-term & working memory,
making it harder to remember other things that happened around the time "fight
or flight" was stimulated.

TL;DR if you spend quite a bit of time on consuming content that stimulates
anger or other "cortisol-accumulating" emotions, you should try to determine
whether it's affecting things like

+ your memory/focus around the time of consumption
+ your awareness of long-term goal
+ your awareness of other people in a social situation.
+ a tendancy to not acknowledge or utilize social options/support

You break free of fear by detaching from the threat to recognize your options
and to do so requires awareness of time/space beyond the immediate thread.

And if you aren't "afraid" when you read social media, are you afraid to say
what you really think? How much pause do you give that?

* Roam
+ [[id:1c37f6c1-1e37-4172-a576-f0d8dcb5628c][Neurology]]

This draft is employing /a bit/ of "critique" by the way. I am asking the reader
to re-think about what they think they know about something -- particularly the
cultural or linguistic references above -- so they may now see it in a new
light. From that perspective, the pitch goes, the reader may also see something
else. However, such employment of post-modernism or deconstructionism, while
certainly useful and beneficial, can be dubious if not grounded in objective
fact or concerned with the moving forward in the future moreso than the past.
