:PROPERTIES:
:ID:       b124114f-f285-487a-94d6-43866aa44f1f
:END:
#+title: AI: Socioepistemological Dynamics

* Socioepistemological Aspects

** Socioepistemic Oscillator "Circuit"

Understanding how an oscillator amplifies its own resonant frequency is
essential to understanding what I've written here.

[[https://electronics.howstuffworks.com/oscillator.htm][How Stuff Works: Oscillator Circuit]]

Depending on how a crystal structure deviates from its ideal, the frequency
spectra will widen. In astrophysics and NMR, this gives rise to a Lorentz
spectrum, but other spectra are possible. Thus, a quartz crystal has resonant
frequencies, but it's spectrum also contains nearby frequencies. Under
amplification, a circuit will present non-linear responses to various
frequencies, but an oscillator circuit prefers to amplify bands near its own
resonant frequency. For socially distributed epistemic forms in the context of
AI, social interaction with AI forms an amplier circuit that feeds its own
resonance.

Our perception on human knowledge will homogenize, especially the collective
response to accessing distilled information/knowledge via AI gives rise to
self-harmonizing feedback loops. If spectral methods can effectively be applied
to analyze information and epistemic forms, then the feedback loops here can be
imagined in terms of an oscillators role in a circuit. Whether there is
convergence or harmonization in such a system would depend on the structure of
its infinite dimensions.

But it's a dynamic agent-based system so (and this is important)

#+begin_quote
the least suboptimal way to maximize predictability via observability &
controllability (while conserving energy) is to oversimplify the information
systems that agents process. in other words, you encourage conformance to an
increasingly narrow typology of behaviors.
#+end_quote

Setting the incomputable math aside... assuming these knowledge provided by AI
tends to homogenize thought, then it may paradoxically be more valuable to
disdain it's influence. While it's impossible to avoid indirect effects from
second & third-order sociocultural effects, it will be more valuable to be
different.

*** Frequency of metamodernist cycles

Post-modern shifts in culture result from the homogenization of culture that we
experience through cycles of modernization. The more globally connected we
become, the larger the amplitude of effects that the meta-modernist cycles have
on us. I would argue that these cycles of modernity are as old as culture and
norms. Post-modernism helps drive social and cultural evolution, but in the
extreme it's like an acid that dissolves everything. Regardless, people yearn to
establish their own identities in contrast to the prevailing culture, which is
part of how people discover who they really are -- whether their self, their
Self or the other.

+ How will generalized AI alter the dynamics produced by these cycles?
+ Will a "post-scarcity" economy be more responsible for change?
+ Will we retain our ability to evolve? Or succumb to a pandemic of apathy,
  hedonism and nihilism?
+ Will we blow our last chakras? Or drown in toxic sludge when rising seas flood
  the levies?

There are a six million ways it could end, but who's placing bets on new
beginnings. How essential can conformity be to transcending these challenges?

** Pedagogical Effects

AI will amplify behaviors individuals select to consume information and
integrate knowledge. This will strongly bias:

+ The amount of planning the utilize when choosing to direct their energy
  specific directions -- subject matter, source, etc -- and whether plans are
  adhered to. There is less perceived opportunity cost to pursuing one form of
  knowledge over another. The incentivization landscape becomes less clear: no
  overarching goals, no economic certainties, no one is let down if you fail.
+ How knowledge gained affects an individual's meta/cognition in order to apply
  it -- e.g. how what you learned in law school affects how you think about
  practicing law, especially in the long term.
+ How deeply reinforced and accurately encoded information becomes -- the
  breadth, depth, parity of internalized knowledge will affect its
  extensibility, retention and deviation from consensus.

The preference to seek answers via AI will empower us at the collective
level. However, absent some strong influence to guide the individual (a push)
along with strong motivating factors (a pull), the process of ingesting
knowledge in this form will yield increasingly mediocore results. Even if you
provide the proper "push" by using AI to tailor it's didactic methods for each
student, the lack of control over economic incentives implies you need one
/hell/ of a belief system to sustain student motivation. Why bother?

The ease of acquiring knowledge will result in gradual decay in the
psychological qualities needed to encourage a student to continue pursuing
it. It turns out those nerds are finely tuned machines.

The lack of depth, parity and coherence will result in impaired "ontological
reasoning" -- or the ability to categorize concepts into a partition that covers
some epistemic space (or subject or range of knowledge).

This shortcoming along with parity/retention of knowledge accumulated in these
ways will create "ontic dissonance" -- a great example of this being our
tendency to value supplying/providing knowledge in terms of its perceived value
today (see below).

* Economic Aspects

+ AI generalizes a set of knowledge related skills, wrapping them into a
  set of features made available through platforms,
  - People today are predicting the impact and trajectory of these skills
    according to traditional valuations of knowledge. We perceive this as
    valuable in many ways: socially, culturally, emotionally, interpersonally,
    economically, etc. Accepting six figures of debt to received four to eight
    years of exclusive education in prestigious institutions is considered par
    for the course if you are to be marketable in the labor market.
  - However, when these formerly exclusive skills become ubiquitous, their value
    plummets. Other factors like online education or a preference for portfolio
    & experience are already affecting the supply-side economics. AI will affect
    the "pricing" and perceived value of knowledge by stimulating dynamics in
    both supply-side and demand-side. The paradoxical nature of these dynamics
    will cause a whipsaw effect in both supply/demand. Further, the specific
    dynamics and their interplay will result from a superposition of effects on
    individuals & groups: individuals will present conflicting personal
    reactions determined by their perception of the sociocultural changes
    through the next few years, but
    - The prevalence of easy access to expert knowledge means that passion for
      learning or a subject is no longer blocked by economic friction, social
      access, personal background, access to exclusive social networks, etc.

** AI Regulation's Impact on Supply-Side Dynamics

Our response to AI thus far inculcates the perceived necessity of AI access to
an individual's economic value: you can either have instantaneous access to the
sum of all human knowledge or your career can languish alongside massive student
loans. Thereby, our society's middle-to-upper class develops a dependency on
these services.

Here, an opportunity presents itself for some group or institution to attempt to
regulate access to AI or data. They can elevate themselves as visionaries in the
field or as experts in its ethics. Consolidation of control over the rail,
telephone and steel industries appeared irresistable to the late 19th century
magnates. The ability or opportunity to bind these industries under their
control didn't arise because of some genius or skill or even luck. They
succeeded because they identified "the middle of the chessboard", so to
speak. They progressively developed their control over this new center until any
piece that moved on their board had to be mediated in some way by them.

So, there are compelling reasons to regulate/monopolize and powerful incentives
to do so. Here, monopolizing could be achieved by the state, by a coalition, by
industry -- the specific tools to do so could be legal, economic, social,
etc. However, it's not clear that anyone is capable of fulfilling these
responsibilities.

** The Unexpected Cost of Dependence

Well ... you're expendible and access to your replacement is as ubiquitous as
regulation permits.

Knowledge is everywhere but experience is shallow. Risks known in full are not
risks taken: no one has skin in the game. Knowledge aids both Intelligence and
wisdom, but the form in which knowledge is delivered/retained impairs skills
like discernment.
