:PROPERTIES:
:ID:       053b2c07-d836-4082-bd62-ca85e2cf46b2
:END:
#+TITLE: Frontend: ApolloJS Is Interesting
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:4630e006-124c-4b66-97ad-b35e9b29ae0c][Javascript]]

* Notes
#+begin_quote
ApolloJS: it was the best of frameworks, it was not the worst of frameworks.
#+end_quote

I saw this ApolloJS and it looks interesting, but if handing SEO for Angular was
problematic, I would imagine that such similar tasks is difficult with Apollo
without significant overhead in CI/CD tooling. I really have no idea though, but
it does seem a bit crazy.

#+begin_src js
(window.webpackJsonp = window.webpackJsonp || []).push([
  [ 59 ], {JISx : function(module, exports) { Date.now() }}
]);
#+end_src

Also, Rails had the equivalent of React Server Side Templates in like 2008 after
problems in scaling/assembing HTML views delivered for AJAX updates. I can't
remember what the feature was called, but Rails 1.2.4 or maybe 2.1.x would
transmit javascript to the client.

Everything that is old becomes new again. The increasingly internetworked
infrastructure differentiates how thin-client & thick-client cycles manifest as
tech. architecture decisions & software design patterns. But its the same things
over and over again.

* fdsa

I'm not entirely sure whether something involving Apollo's CDN is causing
problems with lax/strict mode cookies. My CSRF token is missing =<MISSING>= in a
script injected into the main HTML, but mentioned in 70-some console
warnings. However, =SameSite: None= is set for those cookies and I do have
cookie exceptions for those browsers.

Pearson required third party cookies across like 5+ domains ... why? Doesn't
matter: they _just get_ all kinds of free government money and the plebs don't
know the difference. They also apparently don't know how naked we are on the
internet -- and neither did I really, for far too long. It's funny how no one
tells you like what a cookie is.

Coursera AFAIK doesn't really rely on third-party cookies. I've tried it in two
separate Firefox profiles both with cookie exceptions and one Chromium browser.
I could be wrong, but the Coursera app just works on my iPhone and on an iPad.

It's been a long time since I've used the browser devtools for much
anything other than producing printable cheatsheats by prepping =<html>= tags
and altering stylesheets. Sometimes a reader view or extension works...

Anyways, I saved a copy of the altered HTML source (from devtools) along with a
PDF printout. It's, meh, not that bad and also not that efficient. The only way
I know of to explain it is by using complicated math:

#+begin_quote
A _picture_ is worth one thousand words.
#+end_quote

Yeh, it's math technically

#+begin_quote
2026/7: (the quote... is math, i guess)
#+end_quote
