:PROPERTIES:
:ID:       48fe83f9-f48f-4e5b-8dc7-087b93c865c4
:END:
#+TITLE: Fedora: Trying Out Sericea The Immutable Sway Spin
#+CATEGORY: slips
#+TAGS:

* Docs
+ [[https://docs.fedoraproject.org/en-US/fedora-sericea/reading-and-resources/][Reading/Resources]]

* Resources
+ [[https://www.youtube.com/watch?v=EuNV1EheN98&t=1128s][Sway Spin and Sericea Update]]
+ [[https://docs.fedoraproject.org/en-US/fedora-sericea/updates-upgrades-rollbacks/][Update Fedora Sericea]]

** Silverblue generally

[[https://www.reddit.com/r/Fedora/comments/zkp5y4/some_of_my_fedora_ostree_silverblue_and_kinoite/][Fedora OSTree (Silverblue and Kinoite) recommendations for post install]] includes
information on customizing a desktop, including user-level systemd services

** rpm/ostree

+ Fedora Magazine: [[https://fedoramagazine.org/trying-different-desktop-environments-using-rpm-ostree/][trying different desktop environments using =rpm ostree rebase=]]

*** Beginners Guide to Fedora Silverblue

[[https://www.dvlv.co.uk/pages/a-beginners-guide-to-fedora-silverblue.html#20-how-is-silverblue-different-from-workstation][How is Silverblue different from Workstation]]

This resolved a lot of ambiguity for me regarding the primitive concepts in
=rpm/ostree= and particularly the =rpm-ostree= concepts. Section [[https://www.dvlv.co.uk/pages/a-beginners-guide-to-fedora-silverblue.html#20-how-is-silverblue-different-from-workstation][3.0 Installing
Software on Silverblue]] is also helpful, as it addresses the telos of each
method, whether it's flatpak, rpm-ostree or toolbox.

**** Example telos

#+begin_quote
Example telos: you need to add systemd services at the system layer. You
/may/ need to install the related packages or services with rpm-ostree.

... hmmmm ...

... nevermind /etc and /var are writable, but they may lose content or conflict
with future updates.
#+end_quote


* Sericea

By running with the 39 beta on this distro:

+ seems like I get clean Sway
+ with the [[https://www.youtube.com/watch?v=s-ZxespOupU&pp=ygUYbGVhc3QgY29udHJvdmVyc2lhbCBzd2F5][wayland-centric SDDM display manager]]
+ immutable system with SELinux

But critically: a transition path from here to uBlue/Silverblue/CoreOS, which
rely on many more tools. Silverblue and CoreOS practically assume you'll be PXE
booting.

This machine isn't supposed to do much.

I'm honestly kind of interested to see if I can use it for videos and light,
automated dashboards. I would maybe drive this with =swaymsg= and
etc. remotely.

I may switch to using Guix for this, since it's just way simpler (for me) to
define shepherd services automated with mcron (or something). But I need CoreOS
elsewhere.

** Components

*** OS Tree

=ostree= exposes access to files through a layered, diff-based system where
changes are composed from layers into a final blob.

=rpm-ostree= uses ostree to deliver packages

=flatpak= also uses ostree to deliver applications as packages.

There are many potential uses for =ostree=, beyond packages and their
distribution.

*** Display Manager

The Fedora 39 version of Sericea is xorgless (info [[https://fedoraproject.org/wiki/Changes/sericea-xorgless][here]]), but it's in beta.

** Installation

+ don't use groups in install, extra steps are required for useradd -aG
+ ensure disks are set up to mount /var/home/me when needed (installer won't prevent)
+ use the English (US) keyboard or French (intl deadkeys) keyboard.
+ the US algr deadkeys keyboard will screw up login

** Initial Configuration

Copy over .ssh and .config/xkb directories.

Run =systemctl enable sshd && systemctl start sshd=

Reload sway config, test keyboard

** RPM OS Tree

The very first thing you need to do is:

#+begin_src
rpm-ostree update
#+end_src

And reboot

*** RPM Fusion

Then add the RPM Fusion Repositories

#+begin_src sh :tangle ~/bin/install-rpm-fusion :shebang /bin/bash
rpmfree=https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
pmnonfree=https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo rpm-ostree install $rpmfree $rpmnonfree
#+end_src

And reboot: you must reboot before changes are effective when rpm-ostree
updates.

**** Upgrade after major version release

If upgrading from Fedora 39 to 40 and maybe if changing desktop environments,
then you'd need to remove and readd the rpmfusion repositories ... and i think
it may need to be a oneliner, so it occurs in a single translation

#+begin_src sh :tangle ~/bin/update-rpm-ostree :shebang /bin/bash
sudo rpm-ostree update --uninstall rpmfusion-free-release --uninstall rpmfusion-nonfree-release --install rpmfusion-free-release --install rpmfusion-nonfree-release
#+end_src

**** Nonfree/Free Package Conflicts

I think =rpmfusion-free= packages take precedence on my system. I'm not sure how
to undo that. Maybe reversing the order of =$rpmfree= and =$rpmnonfree= in the
install script would do that (and similar in the update script).

However, this would be complicated if it also means removing many packages from
my system. I can get most of what I need using =toolbox= or =flatpak=.

*** Live Changes

To apply changes to the live environment use:

=rpm-ostree install --apply-live=

But you'll need to propagate those changes to the immutable image. The point is
to not use the host system and use container-based tools only.

These packages add new layers onto the base rpm-ostree.

#+begin_src sh
rpm-ostree install alacritty emacs
#+end_src

*** Emacs

Version =29.1= is available from Fedora RPM's.

Install with =rpm-ostree install emacs=. Keep it vanilla.

*** Updating

Updates are not as complicated as i thought.

#+begin_example sh
# check version
rpm-ostree status -b

# upgrade
rpm-ostree upgrade

# to check without actually running
rpm-ostree upgrade --check
#+end_example


**** RPM OSTree Updates with Rebase

Look for "rebase" instructions in the =rpm-ostree= cheatsheet or in the [[https://docs.fedoraproject.org/en-US/fedora-sericea/updates-upgrades-rollbacks/][Sericea
Docs]].  You must rebase

+ When upgrading Fedora versions: e.g. 38 -> 39
+ When jumping between Fedora Desktop Environments
+ When fetching upstream changes from a remote ref ... if rolling your own
  custom uhhhh =os-rpm= thingy.

#+begin_quote
It's like git, okay... It's just =git rebase=, basically,
which i still get switched up. I think i've been carrying around the same
=$HOME/.gitconfig= for too long and something confuses this concept.
#+end_quote

***** Nope

Maybe rebase is required after +adding custom ostree packages to your system+
adding package layers to your system? ... (maybe this is why i thought it was
complicated?)

But no, it should not be, though the more packages you add with =rpm-ostree
install=, the greater the odds are your system diverges from the base -- more or
less, you'll get =rpm-ostree= "merge" conflicts ... that don't have clever
strings to grep for like =>>>>>=

** Flatpak

[[https://docs.fedoraproject.org/en-US/fedora-sericea/getting-started/#flathub-setup][Setting up flathub]] (sericea docs) and [[https://universal-blue.org/guide/codecs/#how-to-install-the-ffmpeg-full-flatpak-runtime][how to install ffmpeg-full runtime]] (ublue docs)

#+begin_src sh
flatpak --user remote-add --if-not-exists \
        flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install --user flathub \
        org.freedesktop.Platform.ffmpeg-full \
        org.mozilla.firefox
#+end_src

Installing =ffmpeg-full= and =firefox= from flatpak the issues where firefox
wasn't playing videos.

Ensure it starts with a =$HOME/bin/firefox= script:

#+begin_src sh :tangle ~/bin/firefox :shebang #!/bin/bash
flatpak run org.mozilla.firefox $@
#+end_src

* Topics

** Just RPM

** Toolbox

Run =toolbox create=. Enter a project and run =toolbox enter=

*** Images

Update the basic toolbox images by pulling with podman.

#+begin_src sh
# for me, `toolbox create` still uses fedora-toolbox:39
podman image pull "registry.fedoraproject.org/fedora-toolbox:latest"
#+end_src

Update and add deps to the toolbox with

#+begin_src sh
# Q: when are upgrades necessary?
# toolbox run -c "$toolbox" sudo dnf upgrade -y
toolbox run -c "$toolbox" sudo dnf install -y $rpms
#+end_src


**** TODO more notes here. Also... podman/libvirt?

** Podman


** Guix/Nix

[[https://gist.github.com/queeup/1666bc0a5558464817494037d612f094][Nix package manager on Fedora Silverblue]] This gist recommends downgrading
SELinux to permissive, but that's the whole point to Fedora IMO. It makes it
relatively easy to have a decent SELinux config .... I think? I'm guessing
there's a lot I don't know about it.

** Free Desktop


*** Menu

From the same guide to silverblue: [[https://www.dvlv.co.uk/pages/a-beginners-guide-to-fedora-silverblue.html#how-do-i-add-things-from-toolbox-into-my-menu][How Do I Add Things From Toolbox Into My Menu]]

This is QOL.


** Multimedia

*** MPV

For online video and VLC, i needed to install them with =flatpak= so probably
other applications need this as well.

*** MPD

* Issues

** Drivers/Modules

Sericea doesn't support DKMS currently.

See [[https://rpmfusion.org/Packaging/KernelModules/Akmods][akmods]] and the [[https://rpmfusion.org/Packaging/KernelModules/Kmods2][RPM Fusion guide on Kmods2 packages]].


*** Video Decoding

From uBlue docs: [[https://universal-blue.org/guide/codecs/#how-to-check-that-hardware-accelerated-codecs-are-working][how to check Firefox hardware encoding]] (about:support)

I've marginally looked into silverblue/coreos, but those use ignition/butane and
I'm not quite sure how to solve this given that Sericea seems to primarily use
rpm-ostree.

Installing =ffmpeg-full= and =firefox= from flatpak fixed things.

It seems that it wasn't a driver issue:

+ The BIOS is set with GPU as the primary display device
+ WebGL was running on my [[https://te.xel.io/graphics/2017-06-29-animating-the-gradient.html][Animate the Gradient page]], so I at least have OpenGL
+ In any case, AFAIK the GPU doesn't support video decoding and the intel chip
  probably doesn't either.


* Roam

+ [[id:ca4acf9b-775b-4957-b19a-0988b7f429c5][RPM]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]
