:PROPERTIES:
:ID:       41d91c93-6b29-4094-a3fa-e3c2bcfb3549
:END:
#+TITLE: Economics: We Are Ready For A Smart Grid?
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:2eec237f-1cb8-4145-a5db-3c9c7a14d6b7][Economics]]
+ [[id:4630e006-124c-4b66-97ad-b35e9b29ae0a][Electronics]]

As much as you hear about renewbles, we are not culturally prepared for
smartgrid tech. We hear so many liberals bitching about "vampire power" and
"carbon" when no one needed to encourage us to switch our lightbulbs. However,
no one rewired their fuseboxes: some power is wasted when the load from fuses on
the pos/neg rails is not balanced out. It's really hard to find information on,
so it's likely not significant. It depends on the waveform that's returned to
the grid or sent to ground. Still, if the fusebox was balanced when you had
non-LED bulbs and you didn't rebalance, it's definitely less balanced now. How
significant that is?  =¯\_(ツ)_/¯=

+ [[https://pub.tik.ee.ethz.ch/students/2011-HS/MA-2011-19.pdf][Load-Balancing of Consumers In Electricity Networks]]: balancing load in the grid
+ [[https://www.homechargingstations.com/dynamic-load-balancing-ev-charging/][Dynamic Load Balancing for EV Charging]]: balancing a load betwen an EV and AV (+ DC)

What is needed for the SmartGrid? We need new standards for wiring in the
home. Lighting should be run by DC from routed power circuits that is
dynamically dispatched from 384V circuits/fuses. That seems a little high for
diodes, but by dispatched I mean that the selected voltage/amperage is provided
routes through a network. These same power USB devices, which already negotiate
for voltage/amperage. By the way, this renders the European ban on Apple iPhone
chargers anachronistic since we likely won't need the bulky transformers --
/just the cables/. So, when you repeat my argument back to me in five years
remember to savor that bit -- you thought that was significant. Almost all
motors are rotory and these are naturally suited to consuming AC -- retrofitting
them induces an energy loss. Appliances requiring compressors or motors would
remain on AC power and what doesn't would gradually switch to routed DC power.

Before you continue, I should remind you that in 2017, I dug into the smart grid
a bit and wrote this: [[https://te.xel.io/posts/2017-02-28-international-trends-2020-the-smart-grid.html][International Trends 2020: The Smart Grid]], although I did
maybe get something wrong about securities or datastreams on the stock
market. You tell me.

The main idea here is to reduce the number of places where energy is converted
between AC/DC. Achieving 20% increase in efficiency would be significant, though
I have no idea what to expect.

Such a system makes sense for new construction, provided we get it right from
the beginning. If it seems to cost more, that's because energy isn't expensive
yet. If the SmartGrid permitted resale of energy, people would gradually seek to
/produce energy/. Yet, please recall that some localities prohibit collection of
rainwater.

Four items consume between 50% and 80% of the power in an average home --
washer, dryer fridge and dishwasher. If you wanted to use less power, you would
handwash your dishes (as needed) and take care to not get them dirty in the
first place. You don't care about energy consumption because you can't bother to
admit what is significant or objective. You just want to /feel/ like you care
because you want to feel there is something that distinguishes you from the
"other side." You don't define your self in terms of yourself or your world, but
in terms of differences /you conveniently perceive/ between you and others.

Sorry if I sound a little judgy ... I'm just tired of being talked past,
especially when only parrot the talking heads. That's what it seamed like on
social media anyways.
