:PROPERTIES:
:ID:       35ddc0b4-789a-4880-905f-5d9b5bb1c115
:END:
#+TITLE: Finance: Technical Indicators
#+CATEGORY: slips
#+TAGS:

It's been awhile since I've used most of this... so yeh.

* Docs

* Resources
** Webull
+ r/webull [[For New Traders: Indicators Explained][For New Traders: Indicators Explained]]

** Books

+ Sheldon Natenberg: [[https://amzn.to/3hqRglr][Option Volatility and Pricing]]
+ Nassim Taleb: [[https://amzn.to/2TVvgGr][Dynamic Hedging]]
+ Paul Wilmott: [[https://amzn.to/36rvg3E][Frequently Asked Questions in Quantitative Finance]]
+ [[https://amzn.to/2T6F1Bm][Python for Data Analysis]]
+ [[https://amzn.to/3qXc47m][Introduction to Linear Algebra]]
+ [[https://amzn.to/3xwSfpX][Advances in Active Portfolio Management]]
+ [[https://amzn.to/2TU3M41][Technical Analysis is Mostly Bullshit]]

** Lectures

*** [[https://www.youtube.com/watch?v=UD92QBqA8Eo&t=1493s][Optimizing Trading Strategies Without Overfitting]]

* Charts

+ Just use Heiken-Ashi. It gives you a slight edge.

** Bollinger Bands

Technical, but goes in-depth on the Bollinger Bands strategy, explaining why you
want to watch for the frequency of recent mean-crossings. Simply following
advice like that doesn't give you much to measure though, whereas grokking the
math helps develop your intuition. The implications are paradoxical of course
... but also somewhat straight forward: if it looks like hasn't moved but it's
pulling both ways, you intuitively feel like you want to know what's going to
happen.

+ The volitility is being contributed to movement/momentum in several ways, but
  $\kappa$ is connected $\sigma$, so not all values are practical. The
  relationship from the unconditional variance seen here:
  $\sqrt{\frac{\sigma^2}{2\kappa}}$
+ When volatility is causing the price to move, then there isn't consensus and
  when the stock wants to move but the price is sticking, the market is seeking
  consensus: the Bollanger bands help you anticipate the
  drift/trajectory. That's fairly straightforward (but also not entirely
  gaussian)
+ With reasonable volume, the price is being pushed by influences described by
  distribution(s) -- this is loosely coupled to how frequently it crosses the
  center.
+ It depends on when you want to get in/out and how long you want to be in/out
  on a trade. You also need to set reasonable limits/etc on your orders. Which
  is where my experience ends.

Also [[https://www.slideshare.net/secret/djs7uSlsLph5G3][the slides]].

* Indicators

+ Everything should be weighted exponentially.
+ Most of them are irrelevant at small timescales.
+ Larger investors, brokers or portfolio managers probably don't use technicals
  ... it's not very time-efficient.
+ Unless charts are customized to show more than one security, you end up with
  tunnel vision and you'll miss the bigger picture. The faster information
  moves, the faster things go.
+ Most indicators aren't that useful because everything you see is in the
  [recent] past.

** Basics

These are useful mostly because they're simple enough to be salient,
quick and popular.

*** MACD

Overly simplistic, but actually plots the volume on top of the indicator.

*** Volume

** Support/Resisitance

*** Ichimoku Cloud                                             :predictive:

This is one of the few that can actually show you what is going to happen.


** Momentum

*** KDJ/FSTO

*** RSI

** Trends

*** WWV Weis Wave Volume                                       :predictive:

Weird, but useful. Somewhat predictive. It abstracts away a lot of
extraneous information and visually conveys trends.

*** ADX

It's a single value over time. Useful as a shit test to check assumptions you
might have about other trends. Other indicators may fake out, but

*** ADL

The parameters and method to calculate it make it one of the few indicators that
convey /volume of cash/. So, it gives you a feeling for money changing hands or
"what money is on the table."

+ When it's high, people are making money or losing money.
+ When it's low/mid, investor salience is probably elsewhere ...
+ Interesting to compare to volume and other signals
+ Not sure how predictive it is, but upward movements should pace movements in
  price.

*** Pivot Point

** Timing

*** VI [[https://www.investopedia.com/terms/v/vortex-indicator-vi.asp][Vortex Indicator]]

Helps you figure out what kind of cycle the price is in. Visually conveys points
in time for which you should check other indicators to form new hypotheses.

*** Aroon

Useful for thinking about cycles in price.

* Elliot Waves

I would like to understand how $\phi$ and $e$ relate wrt growth. There's
something to this Elliot Wave analysis ... but maybe 98% of the information on
it is garbage. As far as I can see, the stocks should:

+ exhibit some kind of "normal" metrics, like sufficient/consistent volume and
  investor salience.

The reason that it /might/ be more valuable than /irrational/ is that you could
time your trades to extract more returns. It's just a bit hard to believe and
also difficult to determine whether its 5 up and 8 down or vice versa. You
should definitely draw on the charts.

Generally, other technicals are more useful: Weis Wave, Aroon, ADL, VI


* Roam
+ [[id:fecf9468-ffb8-4f9d-9816-b10568c5afe8][Finance]]
