:PROPERTIES:
:ID:       b2f1b699-13ce-4410-97ef-9ea7470328a4
:END:
#+TITLE: Message to Rep Spanberger about Adderall
#+CATEGORY: slips
#+TAGS:

I am technically not in your district, so I do not expect a response. However, I
noticed that your office seems to be one of the only influences aware of the
DEA's involvement in creating this shortage. All the news outlets mention FDA,
but none mention the true cause. I remember the same type of shortage from 2011.
It seems artificial. Patients are encouraged to seek Vyvanse, but this is too
expensive for the uninsured like me.

I worked in the Fab Lab at Virginia Western, where we have 3D printers, CNC
machines and other equipment to facilitate workforce development in Roanoke. I
don't have much experience with industrial technology, but I'm a fast learner.
My specialty and former career skills were in software. I've done some work with
3D rendering. I was helping to support software and equipment there.

COVID had ruined a lot of the momentum that VWCC's new facility had. They are a
two-year school. By the time students learn to use equipment, they move on.
There isn't enough funding and staff to support what they're trying to build.

I could have easily started the semester off on the right foot, but I actually
have two Adderall prescriptions to fill each month: 30mg XR, 10mg IR. They are
staggered because of shortages. Twice a month, I encountered problems. It was
affecting my school. When I run out of medications, the withdrawal makes it so
that I can sleep for 10-12 hours. It's hard to function. To be honest, I
sometimes take higher dosages than I should, but I can manage so long as I know
how long it takes until I can fill a prescription. Yesterday, I spent about 5
hours calling pharmacies and my doctor.

So I dropped out. I was overworking myself at the Fab Lab trying to learn the
equipment. It was affecting my grades, but I cared more about what I could
accomplish there. I'm going to go back to software and hopefully I can bring my
skills with me. I am a Trump supporter and I wanted to participate in new
developments American manufacturing.
