:PROPERTIES:
:ID:       f541e274-0691-472d-8e93-62599b544320
:END:
#+TITLE: Over Here On The X-Axis
#+CATEGORY: slips
#+TAGS: rant

And why didn't I just learn it? People programmed me to assume I was very
talented/smart when all I had was potential. If you plot my life, you'll see
over here we have the *X-axis* for *time* and in blue there's *talent*, on the
Y-axis. Notice how it's almost zero kinda most of the time except a few spikes,
where it quickly plateaus. The derivative of "talent" of course is *growth* and
that occurs when I have a job (notice the quick spikes upward) or when I'm
living somewhere that's not Roanoke.

And again on the Y-axis we have *social support* in green.  And it starts really
high (for no fucking reason at all). In yellow we have *Effort* and after 2011,
that's just ridiculously high with some occasional drops to zero. That's called
burnout or disruption. In red, you'll see *Realistic Potential*, which of course
is a product of talent, belief and social support. Being a product, if you
multiply really anything by "almost zero" then it might as well just be "almost
zero". So thus "talent/skill" is strongly _inversely_-correlated with both
"social support" and "realistic potential" -- i.e. no one ever helped me when i
needed or deserved it; only when i didn't deserve it or need it. Notice
particularly, the lack of any correlation whatsoever between "effort" and
"social support".

Lately, things have been changing though. But definitely don't express your
feelings or try to analyze "what went wrong" with your life. Because that will
fuck everything up. Just accept the identity that was assigned to you by the
Hegelian dialectic. Struggling against the cold, passive aggressive "repression"
is not helpful.  What matters most in life is what people who don't understand
anything believe about you because that is the primary factor determining every
opportunity you will not ever be considered for.
