:PROPERTIES:
:ID:       76fa6c15-83a3-496d-8488-061e7ccd2054
:END:
#+TITLE: JS: Unnecessary Abstractions and Silicon Valley Anxieties
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:4630e006-124c-4b66-97ad-b35e9b29ae0c][Javascript]]

* Rant

#+begin_quote
"something, something, unnecessary abstractions"

- Steve Jobs
#+end_quote

Probably the smartest thing he ever said. Original, no doubt.

#+begin_quote
Later thoughts: also apparently a little misinterpreted on my part? maybe? I
thought he was talking about the software engineering that's always included an
opinionated selection of base libraries that encourage interesting design and
good UI/UX
#+end_quote

Everything cloud/platform/k8s/virt-aaS is an incestuous mess of very useful
abstractions that all overlap in 40-80% of their functionality, but which depart
significantly.

Epistemologically, some knowledge is more universal or timeless than other
knowledge. And unless providing an API or abstraction inferface (e.g. car motor
vs. car controls), then you _cannot_ reduce the complexity of a set of
abstractions to less than the domain of it's application -- e.g. SQL on Unix
systems with logging for a bank is at least as complicated as the _direct sum_
of most of banking/taxes/sql/unix. That is the minimum of complexity and when
the internals of various systems of abstractions, in their implementation, need
to be aware of the internals of other systems (e.g. the car radiator needs to be
tuned to the engine power/heat output) then the actual level of complexity is
much higher than the _direct sum_ of the components, but less their _tensor
product_ (for some imaginative definition of sum/product).

This is why monads & category theory & functional programming always fails to
deliver. The lower-order monoids that represent a potential system's relations
to other system components must be aware of the structure of connected system
components. The abstractions' structure reflects through everything.

This is explains why NPM is a little hell. So NPM has:

#+begin_export latex
\left(webpack \oplus
babeljs \oplus gulp \oplus grunt \oplus angular \oplus react \oplus astrojs
\right)\otimes\left( package mgmt, test harness.... \right)
#+end_export

... which is an oversimplication. But any dev dependencies for tooling needs to
be aware of the potential. The long & monotonous NPM package names reflect this
(it's string-space). Other languages are just as guilty but their frameworks are
far more stable. You're lucky when the javascript ecosystem is ever briefly
_metastable_. That Angular/JS broke SEO without quite a bit of work to fix it is
an example of good software design changes necessitating changes in
process/abstraction in other aspects of web-development & devops. +AstroJS flips
this inside out, once again, since it deploys to CDN.+

#+begin_quote
later discovered that ... yeh it probably not be like that
#+end_quote

This perspective on javascript functionality as needing to be monadically aware
of other system interactions that a library can't anticipate also explains why
there are so many strange one-liner javascript libraries out there. It's
seriously ridiculous. Friends don't let friends use unnecessary JS libs. Just
import decent basic libs and write as much VanillaJS as possible. Framework?
Good. Mozilla W3C APIs/Docs? Good. Oneliners that occupy valuable memory space
in my head because no one bothered to implement es6 on a reasonable timeframe
... !@#$@!%%. Also: use clojurescript, which sounds a bit hypocritical to say
while up on this soapbox ... since from a distance cljs looks like jenga tower
of constantly shifting abstractions.

NPM & the JS ecosystem aren't that bad -- if you already spend a lot of time in
it. However, even if you correct pin the versions for dev/dependencies ... it is
still a giant pain in the ass to come back to a project after 3 months. Docker
helps -- and zomg so does kubernetes. Basically, it's impossible to manage this
complexity without helm, k8s and/or minikube -- i just threw up in my mouth a
little -- minikube 2016 aftertaste: every vender tells you *not* to use it but you
can (?) but ... your on your own? Whatever that means, thanks. And every time I
connect to wifi, I'll just redo all my networking because I don't have VPN. No
problem at all with managing webdevelopment without a rack server. It's easy.
Just use jquery.

And I could use Google/Azure/RH/Amazon cloud, but every 2 months, everything I
ever did would go offline. I couldn't even pay $10/month for JetBrains IDE's,
okay. How do I convey to people how essential a +$100/month "cloud services"
bill would be? That is far more problems than it's worth. And there is free
tier, but I don't encounter enough developers with average experience to get
feedback on how other developers use free Cloud platform products, which are
eerily similar to credit care reward programs: never more valuable than the
interest.

I haven't done webdev since ~2018/2019, except to occasionally tune in, but go
to work and be compelled to fit in by engaging in the "two minutes hate" to
demonize Trump for whatever out-of-touch media circus shit is going on? No thank
you. It doesn't matter what kind of tech job it is. It is not worth it. JS is
apropos to almost all of the tech privacy and dataleak problems. No servile
criticism or empty platitudes on today's "progressive" secular sermon? And it
lends itself to fomenting alientation in some kind of wierd "conflict theory
applied to office politics" -- i.e. the current political circus is emotionally
relevant (it's triggering) and is merely a pretext for modulating negative
feedback loops in an individuals social graph.

The thought of encountering situations like that after moving across the country
to an urban area to be overworked w/o a support system is nerveracking. Just to
be alienated further? I don't think so. All urban areas have higher
democratic/progressive numbers -- no problem with liberals/democrats, per se,
but they end up acting on completely emotional arguments fed to them by the far
left. This is sad, since I may be more liberal than most people who identify as
liberal.

I can be quiet/respectful/etc, but I won't be coerced into expressing assent to
passing political contraversies that I have no power over. Especially when mere
words are not action. I'm not sure if these fears are realistic, but the state
of the media certainly indicates they are. And actually, the impression I get is
the opposite: +95% of people are either normal or understanding/open-minded.
Then it's not clear when things are simply interpersonal/circumstantial -- if I
had people skills, I'd just smooth it over and not care.
