:PROPERTIES:
:ID:       55ff2a7e-4b61-448a-9b1a-695319a04d17
:END:
#+TITLE: KDE: Tiling Window Management
#+CATEGORY: slips
#+TAGS:

Promoting this to its own org-roam node.

* Resources


* Tiling in KDE

|----------------+------+---------+--------|
|                | 5.27 | Bismuth | KZones |
|----------------+------+---------+--------|
| Per Display    | x    | x       |        |
| Per Desktop    |      | x       |        |
|----------------+------+---------+--------|
| Window Classes | n/a  | x       | x      |
| Window Titles  | n/a  | x       |        |
|----------------+------+---------+--------|

Compatibility

|---------+------+------------+------------|
|         | 5.27 | Bismuth    | KZones     |
|---------+------+------------+------------|
| 5.27    | .    | when float | yes        |
| Bismuth | .    | .          | when float |
| KZones  | .    | .          | .          |
|---------+------+------------+------------|

These three are probably all compatible if you have a certain workflow in
mind and adjust your config to that:

+ Make bismuth default to floating (you can't afaik, but it's all good)
+ Set a hotkey to toggle =Bismuth= and one for the =KDE 5.27 TWM=
+ Define common layouts for =KZones= in JSON and probably remove all the layout
  indicators except at the top.

+ When the KZone layouts don't work, revert to =5.27 TWM= where you can create
  an ad-hoc layout by splitting sections.
+ When you want automated management of windows, then cycle Bismuth to a layout
  state. The other plugins only move windows on UI interactions.

This [should] actually work pretty well. It allows you to choose what you want
at any given time. The different options have different levels of cognitive
loading depending on what you're doing, but each one can be used without much
thought. However, there are several extra steps users must take for these to
work together, since you'd expect them to clash.

** Bismuth

Bismuth was integrated recently and, if you set Bismuth's mode to float, it's
compatible with the other Tiling window option, new in 5.27+

+ You can't define new layouts or reorder them in the UI.

** 5.27 TWM

Not sure what this is called. I found the source in KDE repos when I needed to
determine whether/how it handles multiple desktops, which it doesn't for now.

+ Fairly good UI. Intuitive. Mostly uses a single keybinding.
+ Needs support to save multiple layouts (this may exist i donno)

** KZones

[[github:gerritdevriese/kzones][gerritdevriese/kzones]] can be added as an extension under KWin Scripts. The
plugin gets installed to =.local/share/kwin/scripts/kzones/=.

+ works pretty well, but doesn't support layouts per-monitor or per-desktop.
+ KZones has the best UI, but seems a bit new.
+ Only supports window classes for customization.
+ It seemed to move windows to other displays occasionally, then it functioned
  as expected. Probably a quirk or maybe an interaction with other plugins (I
  disabled most of them)
+ I'm thinking that support for per-display & per-desktop. However, it doesn't
  really throw your windows around when you change layouts.

The numpad keybindings work well, but you have to remember the order areas are
defined in the JSON. That could increase the load a bit. It may help to allow
blank entries in the JSON, so the numpad keys can correspond to general screen
space.

The numpad zero key could maybe provide some "default" like capturing window
arrangement state (per-monitor and per-display) where you can attempt to restore
that arrangement (with whatever windows are still there). This might not work
out well with C-based code or with windows whose title's change.

Lacks a lot of other keybindings, but doesn't need them. This is nice. This is
probably good. Still, I feel like I should disable Bismuth and create patch in
magit for just the keybindings, so I can apply it or reverse it when
switching. This would work just for the bindings.

* Roam
+ [[id:39e14ffe-75c9-49e6-b852-6c492c4ee3e0][KDE]]
+ [[id:f92bb944-0269-47d4-b07c-2bd683e936f2][Wayland]]
