:PROPERTIES:
:ID:       218ede4a-4d5c-44aa-b89b-893c2ba3fd93
:END:
#+TITLE: The Desoxyn Problem
#+CATEGORY: slips
#+TAGS:


Keep in mind, this is not like arguing for legalization of marijuana. It's not
exactly a hill I want to die on... however _no one else will ever question
this._ So, again, I guess it's up to me, the eternal social scapegoat, to pay
the social price required to question pervasive ignorance in society.

Years from now, when the issue no one's investigating with traditional research
methodologies, and computational medicine/metamomics have proved what I'm above
to say, no one will go back and undo the social damage in my life. This has
happened in fairly significant issues probably two dozen times, marijuana
legalization being one of them.

Metabolic acidosis leads to the increased excretion of prescription medications,
esp. Adderal, being a simple organic molecule. The molecule structure is so
simple _that it would be difficult to find another molecule where the
addition/removal of single functional groups would lead to larger changes in its
solubility characteristics._ This is one reason desoxyn should not be so
stigmatized -- or overpriced. It's interesting that it's prescribed _on-label_
for obesity though.

+ Desoxyn is $2200 for a full dose, about $200 for generic after discount
  without insurance. The UK allows double the dose as in the US.
+ The DEA/ONDCP/NIH have basically ensured that this drug will never be
  prescribed by creating artificial economic conditions that lead to such absurd
  prices.
+ The drug also distributes itself in completely different regions of the brain,
  which is again _a consequence of the fairly absurd difference in its
  solubility characteristics_. But no M.D. will consider this even though
  organic chemistry should be abundantly sufficient in making these assumptions.
+ The entire reason there was an abuse epidemic actually stems from the lack of
  health care: it's absurd to consider making pseudephedrine illegal w/o
  prescription because that essentially removes its access to anyone who lacks
  insurance and unfairly punishes poor people who caught a common cold.

Without illegally manufactured versions of this drug -- and the accompanied
overdosing where people take literally 3x - 10x the maximum legal dose of poorly
manufactured illegal drugs -- then almost none of the social harms of this drug
would exist. That social harms like dental problems, psychosis, dopamine
sensitivity skin problems result entirely from overdose and the downstream side
effects is an INDISPUTABLE FACT that people should keep in mind -- if they care
whatsoever about scientifically provable information or accumulated costs to
address downstream consequences of addiction. But no, the DEA/ONDCP/NIH must be
involved in determining what science can/not be permitted.

None of that matters, since the "strategies" to fight the abuse epidemic were
basically limited to stigmatizing its usage and never included /sufficient/
controls on pseudephedrine. IMO, a sufficient control should mean calling a
health care provider and requesting a prescription is electronically
submitted. Creating medical records in this regard, combined with the records at
a pharmacy, should be more than enough to limit precursor supply ...

But your drug warriors just love to shoot fish in a barrel -- err i mean to
imprison the fish -- and while they're doing so, they get to play hero and drink
their own righteous kool-aid. You've enabled a system that has accumulated
unbelievable social harm, since the way this drug ruins people is not to be
underestimated. The drug warriors get to play hero and demonize a drug -- while
creating incarcerations and criminal records and tolerating the accumulation of
socially distributed brain rot without actually solving any problems -- whereas
I would rather blame lazy/inept people working in drug policy for not being
creative enough.

* Roam
+ [[id:1fa38c8b-f6b6-4088-9d31-63e36b1f32b4][Pharmacology]]
+ [[id:0464890c-6043-4fda-af9d-a5bec94d857b][Pharmacokinetics]]
