:PROPERTIES:
:ID:       c6c43dc9-7aed-4377-a7f4-e8540667642a
:END:
#+TITLE: Coursera: Issues with Cookie Permissions
#+CATEGORY: slips
#+TAGS:

I hope the email is rendered properly. The other case is 03989265, but it is
closed. There was a misunderstanding because it is my browser that is causing
some problems: the main one being when I view my account-profile on the web, it
shows 0 for most of my course records. Other features of the webapp are broken
because the app doesn't have proper state to make requests and is showing
default values.  Since the web application is in an invalid state, I am hesitant
to proceed with the Scala/etc classes, potentially creating invalid/corrupt
records (if cookie permissions cause bad data stored in NoSQL, for example)

I am on the $1 trial, but today is my last day. My mom said that she will not
pay the $59.00 fee. I was offered a half price deal and will ask her to pay that
for one month. However, I cannot afford coursera until I get a job ... which is
what I'm trying to use it for: to take Scala/Crypto classes to bolster my
resume. I was very frustrated to see that my course history was missing/deleted
and I'm relieved to know that it is not! I should have contacted support more
readily, but I'm busy also learning Ansible/Terraform and GCP.

I hope you understand that I love your platform and want you to succeed. What
I've learned by dabbling in your classes has been so unimaginably helpful to
me. Unfortunately, no one in my family took it seriously because they value
"degree == money" over "education for self-empowerment." So I never really had
much of a chance in the past to pursue classes with the support of people around
me.

#+begin_quote
edit: my efforts were typically spuratic and unsustained because people around
me answered every request for help with NO, but never actually remembered the
brandname Coursera
#+end_quote

However, using the webapp for me is a bit confusing. It's almost as confusing as
trying to actually get to this "Contact Customer Support" form. This
depersonalization of webapp support is not a Coursera problem -- it is
obnoxiously pervasive throughout silicon valley companies. It is incredibly
short-sighted, as you should be so lucky to have real in person human
contact. This social contact provides vectors by which your corporation can
influence society at large. When you desiccate the people from your processes,
you undermine your organization's reach throughout society, which is not worth
the cost savings in the long run.

I've provided the attached files for your benefit.  I've tried it in two
separate Firefox profiles both with cookie exceptions and one Chromium
browser. I could be wrong, but the Coursera app just works on my iPhone and on
an iPad.

The likely cause is that I have restrictive cookies on Firefox, which are now
defaults in Firefox AFAIK. Using Coursera absolutely should not require
downgrading cookie security on my browser. I could create a Lax Firefox profile
specificically for Coursera, but I'm not sure that most Firefox users would even
know to do that.

I have the proper cookie exceptions set: https://coursera.org and
https://www.coursera.org. Coursera AFAIK doesn't really rely on third-party
cookies.  You do make use of coursera.help and coursera.support TLDs, but it
doesn't look like these are required for

Pearson does use third-party cookies -- this means that if you fix this issue in
the simplest way, you downgrade your browser making you naked on the
internet. All so that you can efficiently work through your homework! This was
irritating while taking classes at a community college and using their
textbook/testing software that logs you out every 10 minutes ... nevermind that
it seemed that quite a few people were using Chegg. I'm 38, so I don't know
about that and would not use it anyways ... and ChatGPT just put them out of
business. Pearson does this to collect very many analytics on their product
usage because they're corporate culture is one of a certifications/education
testing company.

I'm not entirely sure whether something involving Apollo's CDN is causing
problems with lax/strict mode cookies. My CSRF token is missing =<MISSING>= in a
script injected into the main HTML, but mentioned in 70-some console
warnings. However, =SameSite: None= is set for those cookies and I do have
cookie exceptions for those browsers.

It's been a long time since I've used the browser devtools for much anything
other than producing printable cheatsheats by prepping =<html>= tags and
altering stylesheets, so maybe I'm wrong.

The attached tar.gz archive contains information about the state of javascript
variables, screenshots of the cookie values I'm seeing, along with

I have the .har files for these browser states, but I wasn't sure if I should
send them since they contain the state of all the request/response headers along
with the cookies.

+ The _FIREFOX2 directory contains a blank firefox profile with no extensions,
  strict cookie permissions and cookie exceptions. I tried downgrading this to
  "Standard" cookie sessions, then starting a new

+ The other two directories contain normal browser profile with my typical
  extensions and similar strict cookie permissions and cookie exceptions.

* Roam
