:PROPERTIES:
:ID:       aeda5047-5272-4e25-b406-19c3a0bfd72d
:END:
#+title: X11: Configure X-Keys XK3 Foot Pedal For Extra Modkeys

+ [[id:ee958185-81f4-42bd-abd0-5ad1801deeca][XKB/X11]]
+ [[id:3daa7903-2e07-4664-8a20-04df51b715de][C++]]

The X-Keys keyboards are produced by P.I. Engineering a great company that makes
pretty much everything open source, including the STEP files. Their keyboards
are like industrial strength and completely customizable.

* Docs
+ [[https://github.com/piengineering/X-keys_Linux][piengineering/X-keys_Linux]]: the library
+ [[https://github.com/SuperFlyTV/xkeys][SuperFlyTV/xkeys]] node.js module to interact with x-keys panels
+X-Keys [[https://xkeys.com/xkfootfront.html][XK-3 Foot Pedal]]

* Resources
+ [[https://github.com/vrpn/vrpn#65][vrpn/vprn#65]]: osx, but building x-keys library into VR device support
  framework (2015)
+ [[https://github.com/fultonj/xkfootnix][fultonj/xkfootnix]]: Use an X-Keys Programmable Foot Pedal to provide additional
  ways to trigger the Control and Alt keys without using your hands.
  - this looks straightforward and uses =xdotool= to pass keyboard events from
    the device into the X11 Server.
+ [[https://github.com/jimmckeet/XKeys-Scripts][jimmckeet/XKeys-Scripts]]: Configure [[https://xkeys.com/xk24.html][XK-24]] for video streaming automation
  controller with OBS

* Issues

I bought this a long time ago: like 2011/2012? I had planned to get some of the
other keyboards, but they are more expensive...

** Using X-Keys as modkeys in OSX
+ It seems like OSX keeps track of the input device that's sending it keys. I
  can't remember whether I tried with Linux or not, but you have to build things
  yourself. The =Makefile= is pretty straightforward, so it's possible.
+ Anyways, you end up running into an issue where you can activate the modkeys,
  but hitting keys on the main keyboard just results in normal keypresses. There
  may have been some way around it, but I can't remember. The OSX software at
  the time by default let you do pretty much anything except use the pedal for
  modkeys :(

** Building their Linux software as packages using Guix

Eventually ... I'm going to get around to using this XK-3.
