:PROPERTIES:
:ID:       e896bdca-7c2a-43ab-ad05-32120e1f9cca
:END:
#+TITLE: Zinc and Aminopeptidase-associated disease pathways
#+CATEGORY: slips
#+TAGS:  

* Roam
+ [[id:f6d8bc06-c28b-477b-9537-ad767f70c258][Metanomics]]
+ [[id:8adf45de-c02e-427e-b8bd-ad0b169a5d34][Bioinformatics]]

Maybe science misunderstands the relationship between aminopeptidase (AP)
cleavage and cancer. While it’s complex and I don’t fully understand the range
of AP enzyme types, a brief glance at research suggests that:

- AP’s act on small proteins
- AP’s require zinc to function
- Some AP’s (APN) are involved in the HLA-1 systems that present degraded
  proteins on the cell surface for the immune system
- Many AP’s have tissue-specific distribution (e.g. LAP expression is found in
  lymph nodes at more than twice the average rate … by RNA read analysis)
- Amino acid cleavage results in functional changes to protein chains
  (hydrophilic end => hydrophobic end)
- cleavage may strongly affect the folding seen in small protein chains, which
  should be broken into subunits according to their functional properties
  resulting in many more repeated subunits than would be were the process to be
  uniformly random (I.e. a very small region of the domain of potential degraded
  protein subunits contains almost all of the observed subunits — were this not
  the case, the immune system would see more noise than signal! Viz. I am
  fucking correct about that)

However, depending on the negative feedback mechanisms for AP-x expression in
cells, it is possible that over-expression of AP-x (from *poorly distributed*
Zinc 2+ ions) causes AP-x to be paradoxically associated with disease. In the
case of poor availability of Zinc, then there should be strong
*tissue-dependent* availability of Zinc ions and thus disregulation of these
immune-marking systems. This, combined with the immune-system’s reliance on
inflammation both to access tissue networks and further expand inflammation
would exacerbate its bias to selectively engage in tissues.

* Resources
+ [[https://www.thermofisher.com/us/en/home/life-science/protein-biology/protein-biology-learning-center/protein-biology-resource-library/pierce-protein-methods/overview-post-translational-modification.html][Overview of Post-Translational Modifications (PTMs)]]
