:PROPERTIES:
:ID:       b26fbe07-77f9-4fff-b8bf-5fbb27ab8670
:END:
#+TITLE: Coursera
#+CATEGORY: slips
#+TAGS:

* Docs

* Resources
+ [[https://www.classcentral.com/report/top-moocs-2022-edition/][Best Online Courses of All Time]] (Class Central)

* Topics

** Curriculum

*** Changes since 2012


IDK. I was upset to see more generic "FAANG Cert Pro" pre-classes on Coursera
than real courses from universities. The majority of classes on Coursera from
2012 through 2017ish were put together by universities that (I think) were
trying to sell prospective students on their stronger or newer programs ...

They were also dabbling in open education. It's hard to run some of their
courses though (though the Scala course basically runs itself :thumbsup:)

**** Sync Students & Courses

+ Their peer-review requires elevated attendance. It's a little intimidating
  (who i grade?), maybe, but it works well IMO ...

#+begin_quote
I can't say have much experience with it, other than some 2017/2018ish course on
=Jacobi Modular Forms=.

/"Cleanup on E8. Cleanup on E8."/
#+end_quote

+ Synchronous usage brings in many users at once, but only if the course is well
  marketed. FAANG courses overshadow the good courses -- and you don't get a
  raise for studying "Pre-Hellenistic Greek Poetry" or "Linguistics" or well
  quite a few of their best courses (ACTUALLY TAUGHT BY ACADEMICS)
+ So, in other words, the capitalists dictate everything you want to do with
  your life and you really really want to pay $500 to take their certificate
  tests which is pocket change, isn't it Smithers? (I kid, I kid)
+ The FAANG courses are (bc they $$$ for cousera). They're fairly good, but it's
  like a guided introduction to "reading the docs" and "thinking about it as one
  do be doin some times." Google had some decent lab technology, but they were a
  bit too simple. Just going on

**** Async Students & Courses

+ Starting & restarting classes is great, but drives asynchronous usage which is
  hard to coordinate. Unless there are tools available to TA's and course forum
  moderators to specifically identify & reach out to newer students in their
  course, then few of these asynchronous course starts will stay in for longer
  than a week at a time...
+ Also, revisiting the same material for re-re-review is boring... and NO, I do
  _not_ want a =B= in a Coursera class.

hmmmm ... maybe complete this later

* Classes

* Programs
+ Bioinformatics I https://www.coursera.org/account/accomplishments/verify/JAGXUZGRN4
+ Bioinformatics II https://www.coursera.org/account/accomplishments/verify/CE9BD5JNMA
+ Epigenetic Control of Gene Expression https://www.coursera.org/account/accomplishments/verify/8BLBSXZCBH

** IBM

*** Certificates

**** [[https://www.coursera.org/professional-certificates/ibm-data-engineer][IBM Data Engineering]] (prof. cert)

** Google


*** Specializations:

+ Google Cloud Database Engineer (+ 12 courses)
+ Networking in GCloud (+ 2 courses)
+ Security in GCloud (+ 3 courses)
+ Developing Applications With GCloud (+3 courses)
+ Architecting with GCE
+ Architecting with GKE (+3 courses)

*** [Preparing for] Google Cloud Certifications (professional)

+ Cloud DevOps Engineer
  - Fundamentals
  - Developing SRE Culture
  - Reliable
  - Logging
  - Getting started with GKE
+ Cloud Developer
+ Cloud Network Engineer (+ 3 courses)
  - 2 overlap with Networking in GCloud
  - 1 unique lab
+ Cloud Engineer
+ Cloud Security Engineer (+ 7 courses)
  - 2 overlap with Networking in GCloud
  - 3 overlap with Security in GCloud
+ Cloud Architect (+6 courses)
  - 1 overlaps with "Architecting with GKE"
  - 2 Essential: foundation/core
  - 1 Elastic, 1 Reliable


* Issues

[[https://www.coursera.support/s/case/5008W000017iYnAQAU/my-course-records-are-missing-i-checked-for-a-second-account][Case 03989265]]: missing course history

* Roam
