:PROPERTIES:
:ID:       19909560-541a-4940-aaac-32a70fb4e6f5
:END:
#+TITLE: Kaggle: Notes on JPX Feature Engineering
#+CATEGORY: slips
#+TAGS:
* Roam
+ [[id:03684d61-2d11-4ad8-99b5-0139ddda433c][Kaggle]]
+ [[id:fecf9468-ffb8-4f9d-9816-b10568c5afe8][Finance]]

* Docs
+ [[https://www.kaggle.com/c/jpx-tokyo-stock-exchange-prediction][JPX Tokyo Stock Exchange Prediction]]

* Resources

* A Brief Detour

These foreign-hosted exchange competitions seem like a good way to learn finance
because hey there's 24 hours in a day and the sun rises in the east, as they
say...

From [[https://te.xel.io/posts/2017-10-30-speed-of-thought-sociophysical-postulates-1-to-11.html#social-and-informational-thermodynamics-and-convexity][Speed of Thought: Sociophysical Postulates I - XI]], Thermal Convection of
Information:

#+begin_quote
Imagine the sun rising in the Far East. It heats up the air and water, giving us
wind and ocean currents, but doesn’t its sociophysical energy also reverberate
through humanity? As the world turns each day, there is random motion moving
from the east to the west, driving social interactions. Pushing through the
noise are faint, low frequency waves of cultural information rippling over and
reflecting between geographic features. Vacuums of low population density taper
this resonance. Between the centers of civilization, the dispersion of
information is strained through translingual membranes, limiting the number of
social connections over which information can cross. These metaphors are not
perfect, as behavior was not coordinated and our modes of transportation were
limited throughout history.
#+end_quote

Is there a speed of sound for information diffusion? Well apparently no one
cares, though you can't possibly think these thoughts and not be forever
affected ... which I think may be a hallmark of decent or significant
philosophy.

And that's a challenge: think my thoughts within the virtual machine of your
mind and /if you understand them/, please tell me how you were or were not not
profoundly affected. I'd love the feedback. And actually, if you don't
understand (if you think it's meaningless, you do not understand), I'd love the
chance to explain them.

There is also a [[https://github.com/dcunited001/dcunited001.github.io/blob/sources/_drafts/2017-11-01-speed-of-thought-sociophysical-postulates-12-to-20.md][draft on Sociophysical Postulates XII - XX]], which I never
finished. It's more significant and instantaneous communication obliterates the
clarity of these mechanisms while they still are determinative.

Anyways....

* Why JPX?

Because I don't know much about the foreign exchanges, though I would've loved
to trade Dassault systems during the pandemic.

** Intro
