:PROPERTIES:
:ID:       faf58d68-8de3-4247-8e2f-62961ddc60bf
:END:
#+TITLE: Fragility and Potentiality: Heidegger's zuhandenheit and vorhandenheit
#+CATEGORY: slips
#+TAGS:

#+begin_quote
kind of a draft, really i just needed to move this out of the AI topic. Nowhere
near complete.
#+end_quote


** Heidegger's vorhandenheit vs. un/zuhandenheit vs. nilpotence

Change can be dangerous to the systems of specialization in place that are
responsible for centuries of progress and, with technology, exponential change
is certain. One one hand, we need look forward to what is coming, but on the
other hand, we can't forget about skills/knowledge from the past. There are many
tools we formerly had at least /vorhandenheit/ or /zuhandenheit/ which are now
basically /unzuhandenheit/.

From [[wikipedia:Heideggerian_terminology#Ready-to-hand][wikipedia:Heideggerian_terminology]]

#+begin_quote
In almost all cases humanity is involved in the world in an ordinary, and more
involved, way, undertaking tasks with a view to achieving something. Take for
example, a hammer: it is ready-to-hand; we use it without theorizing. In fact,
if we were to look at it as present-at-hand, we might easily make a
mistake. /Only when it breaks or something goes wrong might we see the hammer as
present-at-hand, just lying there./

Even then however, it may be not fully present-at-hand, as it is now showing
itself as something to be repaired or disposed, and therefore a part of the
totality of our involvements. In this case its Being may be seen as
*unreadiness-to-hand*.

Heidegger outlines three manners of *unreadiness-to-hand*:

+ Conspicuous :: damaged; e.g., a lamp's wiring has broken
+ Obtrusive :: a part is missing which is required for the entity to function;
  e.g., we find the bulb is missing
+ Obstinate :: when the entity is a hindrance to us in pursuing a project; e.g.,
  the lamp blocks my view of the computer screen.
#+end_quote

Whereas un/zuhandenheit impairs an entities functionality such that it requires
time/attention to become a tool to utilize, there are further grades of
/*-handenheit/ that eventually reach nilpotence, which is like the incapacity
for being or utility. In the context in which Heidegger's terminology is used
(e.g. considering the hammer as an option to solve a problem), we usually would
consider the tool as lacking the /potential/ for application in the context, but
this isn't really the same as nilpotence -- which probably relates to Heideggers
metaphysics on The Nothing.

In any case, it's interesting to combine these ideas with those of the [[https://en.wikipedia.org/wiki/Category_(Kant)#The_table_of_categories][Kantian
Category of possibility]] and particularly, the conditions of possibility. In
many cases, potential domains of $P( \cdot )$ can be bounded/excluded where $P(
\cdot , \ddots , X ) = 0$ for all X. This is useful when it is easy to define X
to be excluded from the domain of $P( \cdot )$ -- i.e. where the countability of
either X or the complete domain allows for the extraction of X. There,
renormalization is unnecessary. Useful insights include:

+ The application of algorithms, taking into account Complexity Theory and
  conditions of possibility
+ Fuzzy logic and infintessimal probabilities

When considering the impact of systems shock on cultural resillience --
i.e. whether the culture/society can absorb a shock of systemic nature or
whether it would take centuries to recover -- it's critical to realize the
difference between cultural progression and regression, where the former is
typically a /gradual process/ of cultural /progress/. Just by examining history,
we can see that progression takes centuries, that it may involve detours and
that it's not without problems like iniquity. Progress in history rarely occurs
overnight, whereas when we see regression in history, there are examples of both
fairly immediate regression as well as gradual progress. Through history, when
examining the occurance or possibilities of prosperity, it's rarely the result
of generations who enjoy the prosperity and arguably it is conditioned upon
resource availability, technology and relative population growth. Since
individuals/societies will collaborate to avoid regression, suffer to correct it
or form alliances with other groups when threatened -- then regression usually
occurs when it cannot be avoided. This is quite often sudden.

Examples of regression include the Bronze Age Collapse, which was the first
/real/ post-deluvian collapse in the Western world. Here, our systems had not
been architected with foresight to avoid the potential for collapse and, at the
time, it would be envisioned as something that happens to a city-state or
/individual society/, whether disaster, mismanagement, Gods or war. It would be
difficult to anticipate the possibility for total collapse of /all known
societies/. There are other examples, which are critical to examine to broaden
perspective.

In any case, a society benefits from exploiting role specialization, whether
it's class-based (priest, ruler, agrarian, warrior), social, psychological or
economic. Generally, when economic needs are met, then the other contexts where
role specialization may occur will support the differentiation therein and thus
benefit from it. Many of these specializations -- whether cultural like art,
literature, music and theater or economic like technology, craft, market,
transportation, etc -- are predicated on many conditional dependencies that, for
whatever reason continue to be satisfied by the status quo. That is, the
probability is almost one for their dependencies to be met -- these can be
maintained through the occasional/constant actions of individuals taking on some
level of specialized role. The level of consciousness w.r.t. these conditional
dependencies or the mechanisms that maintain them varies, but It's important to
note it's not necessary for many groups/individuals or even any group/individual
to understand how the needs are met, since much that happens in a society or
economy is the result of unconscious mechanisms/motivations/reactions.

So societies/economies evolve by distributing the need for specialization
throughout the population, where specialization itself is made of conditional
dependencies. You can only buy grain at the market in Sumeria if farmers are
growing it, reaping it and bringing it to market. You must have money to buy
grain, but there must be grain at the market. As modernity as coalesced, then
the systems of conditional dependencies that correspond to specialization have
become increasingly /stratified/ -- this can be seen by comparing quality of
life indicators throughout the world with the causes for those indicator values,
usually economic. In the more developed world, there are different problems, but
for a developed nation that's food-insecure or energy-insecure with limited
options over imports/exports, then something that happens to their trade
partners affects their citizens' ability to meet needs. German industry suffers
when it can't buy Russian natural gas, where LNG supply chains themselves are a
recent, expensive development. In place of /strata/ of specializations, it may
help to imagine something like the /strata/ of geologic layers. In some
geographic/economic/contextual areas, the spaces between strata are robustly
supported by redundant mechanisms for conditional dependencies. You can meet the
needs of conditional dependencies through redundancy, but it's always
expensive.

#+begin_quote
You can also see similar layers of conditional dependency in neural networks.

For a classification layer, when one when its output corresponds almost
one-to-one with input on one node -- and particularly when that node contributes
almost measure to other classification outputs -- then you either have a
well-trained network or perhaps a network in need of diversification to discover
other hidden variables related to that classification output.

[[Neural Network Approximation based on Hausdorff distance of Tropical Zonotopes ]]
(2022)

In any case, if you remove that node (forwarding to the output class) or at
least remove its contribution to output, then your network will be unable to
properly classify those examples. That's not a great example, but when similar
situations happen in the intermediate layers of neural networks, it gets a bit
dicey to explain in a paragraph.

If you understand the concepts in this paper, then you could anticipate how the
shape of polytopes changes when the criteria described above are true. The
volume and geometry/dimensionality (i.e. relative flatness/pointedness
vs. "convexness/roundness") will change, depending on how well an example
corresponds to the situation described above.

This is all related to the the "entangledness" of representations as well, which
can also usually be disentangled by interfacing with a neural net's layers by
appending additional layers to a network.
#+end_quote

Furthermore, it has been noted that capitalism is effectively socially
distributed machine learning. Here. nodes may describe economic entities like
banks/businesses/corporations/individuals or categories of entities. Using a
planar graph, where nodes in a plane belong to a specific category and/or tend
to form edges with nodes in other planes, is useful for conceptualizing things
supply chains tiers, but it's imprecise. If capitalism is to be effective /as/
socially distributed machine learning on supply/demand, then it must result in:

+ Optionality
+ Market Access
+ Liquidity (as opposed to stores of value, best conceptualized as batteries
  with voltage potential)
+ Coverage (sufficient flux to a sufficient area of the economic graph)

And maybe some others ... but if these are satisfied, you'll have an economy
with a middle class and minimal iniquity. More critical to our collective
prosperity is an economy's ability to adapt. While lower flux of liquidity is
generally a problem, when it corresponds to a higher "voltage potential" of
stored wealth, then when an economy experiences system shock this stored wealth
can drive change, especially when liquidity is scarce.

#+begin_quote
In the brain, there is much focus on the electrical signals, since these are
easy to measure, but the signals correspond to flows of ions in the opposite
direction. Action potentials (spikes) can result from neurotransmitter
release/receipt or local relative concentrations of ions. The spikes and
relative voltage levels (at the scale of networks with ~100 neurons) can be
further modulated by the local buildup of ions. The possibility of neural
response to transmitters depends not only on the presence of the
neurotransmitter in the synapse, but also its supply/reuptake and whether a
G-coupled protein receptor is primed with its G-coupled protein (see 5-HT &
serotonin or D1-D5 & dopamin). The downstream action of neurons, depending on
the anatomic region can be modulated/gated by the possibility of GABA/NMDA
mechanism responding. Similar mechanisms describe why smokers seek the
stimulation of nicotine, but eventually maintain nicotine levels to avoid
anxiety -- and thus, they need a cigarette to "calm down". This is a long-term
reaction to the stimulant effects of nicotine, w.r.t. its action on various
networks/types of neurons.

Notice how nicotine isn't addictive because it "causes electric activity" but
rather because it induces long-term changes in the structure/tendencies of
neurons, which now have something of a conditional dependence on the drug for
normal behavior.
#+end_quote

So, yes, you have capital flows in economies, but wherever you have capital
flows, there must be something flowing in the opposite direction. This could be
a product, a service, a contract, an option or something. Rarely do you have
flows of capital that don't result in real world changes. Just like it's hard to
measure local levels of specific neurotransmitters, it is also difficult to
measure changes to more qualitative responses in the economy. However, the
specifics of responses to flux of capital, whether large or small, are not
simply arbitrary -- they are the primary result of work or change having been
accomplished. You don't spend money so nothing happens and nothing changes. You
spend money when you need something to change.

However, the dimensionality by which changes could occur are myriad. First, an
arbitrary qualitative dimension of color:

#+begin_quote
If you buy paint do you pick white or pink? Well it depends on what change you
want or need? If you already have a pink wall, you may want to repaint it, but
you probably won't buy primer to do so. Whatever someone chooses corresponds to
what that individual needs for their circumstances. At the same time, no paint
store can supply 1,000 colors of paint -- unless they can mix on site, which
requires investment in equipment, skilled labor and maintainence. This all
requires investment and some commodities expire, but some brand of house paint
will be priced very similarly regardless of whether the pigments are in/organic
-- and they're /almost always/ inorganic, esp for exterior paint. So there's a
decoupling between how your needs are met as a consumer from how you make your
decisions. This enables you to focus on what you want which alleviates the need
to deal with complxity.
#+end_quote

But, in the above situation, compare the levels of complexity/risk/regret
experienced by the consumers and by the service/product providers. Here, mixing
the paint is really a service. It's potential depends on the relative
availability of pigments, which are generally uniform. The customer needs to
handle the complexity of identifying which particular version of off-white they
have so ... you know "HGTV" stuff. There's little risk except time and maybe $50
... unless Sherwin Williams can't maintain its oil/gas pipeline and the carbon
animus ignorantly victimizes the American supply-chains of petroleum
derivatives.

As a customer, you have to deal with the complexity of ensuring the paint
doesn't go dry, the brushes are wetted then cleans, that you bought the right
rollers ... Most people really have no idea whether how paint disposal varies
depending on whether it's latex/oil or wet/dried. Handling pollution and waste
disposal has taken a backseat to Carbon policy, which IMO looking at the science
on CO2 spectral saturation is /dangerously close/ to "not even wrong."

The paint store, however, can absolutely purchase the wrong equipment or could
even forget the upkeep. They need to train people just to provide this
capability. Someone must to continuously invest in the specialized tasks to
supply your wide variety of pantone colors, which requires first-order logic
parameterized over time -- what is the probability that these conditional
dependencies will continue to be satisfied, $\forall t \in T$, where T is not
really infinite.

In other words, you integrate over all time to determine the likelihood of being
able to purchase whatever fucking =R= or =G= or =B= paint you want. You don't
have to:

+ Think about the spectral absorption/reflection profiles of each pigment.
+ Write an application that advises employees on what ratios to mix.
+ You don't have to determine what fillers/emulsifiers to add to ensure pigments
  don't fall out of solution.
+ Assess other pigments/ingredients for cost/price.

Instead, the specializations in the economy, provided these conditional
dependencies are met has been sufficiently socialized throughout its
regions. The main issue is that these strata of specialization cannot withstand
all magnitudes of stressors at any time. If

*** Optionality And Market Access

Market access (many diverse/redundant connections between buyers/sellers), which
corresponds to the layers of a network being able to form many broad connections
in a meaningful way.

The optionality and market access will contribute to resilience, but usually
result in implicit inefficiencies, not everyone can purchase the best quality
for the best price from a singular supplier.

*** Liquidity and Coverage

Liquidity referse to efficient flux of value through edges/layers of the
graph.

Blood pressure and supply are a good example: if one part of your body really
can't get sufficient flux of blood, it /will/ become gangrenous and die. Even if
the restriction on flow isn't so extreme, that part of your body may not receive
sufficient nutrition. The capacities for nutrients to access all parts of the
body are not equal. All mineral formulations and all vitamins, whether
in/soluble have various supplies and stores in the body which are derived mainly
from their storage/uptake mechanisms and solubilities. Vitamin D absorbs into
fat, so obese people may have more total Vitamin D, but they may have a harder
time delivering it to tissues in the body.

Whether liquidity in an economy benefits everyone depends on the circularity of
flows through the network. It's not enough to

This sounds complicated, sure, but imagine an Air Conditioning system either
without a circuit that covers each floor/room in a building or with a single
centralized unit dedicated to the whole house. When you change the thermostat,
the AC needs to respond to reach equilibrium. To cool, it typically condenses
humidity in the air and provides a surface across which a coolant can
efficiently absorb the temperature delta. The coolant absorbs heat and is cycled
around the system, but is easy to cool again. This usually involves properties
such as phase transitions at useful temperatures/pressures ... but yeh, the
details don't really matter. The point is: efficient technology in a building's
AC is only one part of the solution -- you also need efficient distribution of
fluid exchange (air is also a fluid) across a sufficent /cover/ of the
building's layout. If you don't have this, you'll end up with a high
heating/cooling bill, hot/cold rooms and maybe one really dusty room that has
one entrance, one vent and very little foot traffic.

and circularity in the flows of value
  (i.e. sufficient liquidity reaches a sufficient range of the entire system)
  produces more benefits to a society/economy than its costs & shortcomings or
  at least produces more benefits to a )

Effective capitalism eliminates bottlenecks and diversifies nodes in various
layers while ensuring that sufficient measure is distributed throughout the
network -- i.e. you avoid consolidation of measure (liquidity or neural net
input measure) to singular nodes in supplying the needs for a role. If your
economy is food-insecure like Egypt, then you must diversify your food
suppliers. If your industry is reliant on a singular source of gas, then when
you /cut/ the economic graph verticies that correspond to Russian gas supply,
then you should expect consequences.

*** Leadership And Potential

Any sufficient complex of stressors can overpower a society or economies ability
to recover/adapt to change to restore functionality.  Introducing more
conditional dependencies into whatever processes support the economic or
cultural status quo increases risk of a systemic crisis. When a crisis occurs,
the set of skills needed to overcome it or to even properly diagnose it does not
primarily correspond to the set of skills needed to succeed in the pre-crisis
society/economy.

What scares me or infuriates me is not the people disagree, but rather that
there seems to be no plan/vision that would motivate Americans to cooperate --
or at least that's really the sense that I get from seeing news clips on
TV. Coronavirus was a real high watermark for crises in recent memory. Usually,
these things catalyze a response. Remember 9/11? That culturally resonated with
people. Long lines at the recruitment offices, etc. For coronavirus, there were
some equivalent responses early on: focus on "essential workers," and other
things like this. But we didn't need a short-term response from the public, we
needed a well-executed long-term vision from leadership while cultivating a
willingness to cooperate in the public, but instead diverged into arguing over
"science" on masks and things like it. The media in this country makes me sick
because while they profit sensationalizing trivila issues like paper straws, we
have to suffer being incapable of declaring a "bankruptcy on leadership."

Disagreement on political, philosophical or personal issues is actually a
feature -- it's not a bug. When there's sufficient discourse in public and
media, then we all benefit from seeing others' perspecives. However, when we
face a threat or a crisis, if there is no plan that could succeed or no
leadership capable of orchestrating people to cooperate/contribute or to call
attention to a path towards resolving issues or even to call people to hope for
change, then failure is practically a foregone conclusion given a large enough
system shock.

Managing people during such a systemic crisis requires a plan grounded in
reality, but also needs to account for the operational/logistic "minutia" of
leadership.  Regardless of how "leaderly" someone may seem or how smart they are
or how rich they are, if they can't delegate/coordinate/orchistrate or if
society just won't cooperate with what's needed for collective action, then they
will fail. We are being transformed by technology faster than we can socially
distribute the knowledge/wisdom needed to handle the changes.

To coordinate people to respond to a crisis, it requires having a reserve of
power, energy, or money that's been accumulated. Any such reserve or potential
is not infinite. Without this, in an existential crisis, people will
instinctively avoid risk/danger and seek comfort/security. Neither of these are
necessarily useful in confronting the issues or coordinating a response. They
are likley related to the problem, but only orthogonal components of a its
solution.

As for zuhandenheit and vorhandenheit, we need people who can make themselves
useful in myriad ways. However, many skills that /may/ be needed are in short
supply.....

TODO: maybe finish, maybe move elsewhere

* Roam
+ [[id:cea7d11c-8357-4e4f-90b3-fa8210eff796][AI]]
