:PROPERTIES:
:ID:       f541e274-0691-472d-8e93-62599b544321
:END:
#+TITLE: Linux Users Are Doing It Wrong
#+CATEGORY: slips
#+TAGS: philosophy

+ Linux

This has already been said, but I think it's more useful to acknowledge this
than it is to have much of an opinion on SystemD.

* What The Users Demand

By looking at what features/software are available/supported, you can tell that
this is what the people demand. It is what it is, but most people imitate
patterns they see. There are a few creatives or obstinate opinionated people who
like to explore something different. I'm not an expert here, there aren't enough
people who really understand "the Unix way" and thus there aren't very many
examples for people to imitate.

...

The reason these problems get worse is because Linux enthusiasts are pushing for
the "Year of the Linux Desktop". Designers have too much control over what UI/UX
feels like and are you going to say no to volunteers? Further, this is what the
users themselves demand and I'm sure the telemetry data supports that. But
there's skew in that data because people cannot imitate what doesn't already
exists /and/ if it only exists with limited adoption, then learning/imitating
that can only grow at that rate.

...

* How Was I Doing It Wrong?


Though this will only show my Jungian shadow, I can give a lot of examples from
personal experience:

+ I didn't know to systematically RTFM, generally before using the project/lib.
+ I didn't know /to/ write packages or /how to/ write packages. At various
  points, I cared a lot about repeatable builds with custom build options --
  building high-level OpenCV libraries that reference dependencies like FFMPeg
  built with specific options.
+ I didn't quite understand how to make XDG directories portable.
+ I knew a =~/.bin= folder was helpful, but I didn't understand how important.
+ I didn't know to approach things from VM first or how to script VM creation
  (until using Vagrant)


**** TODO finish enumerating examples

* What's My Experience With Trying to Use Linux?

Basically, being curious and spending a lot of time trying to use it while
suffering from Dunning Krueger in a society full of people who told me I was
smart even though I wasn't. Then, running into artificial limitations imposed by
hardware/software vendors who didn't want to have to compete with free -- so
they systematically RUINED anyone's experience using Linux by /not doing
anything to support it/. Fuck you Broadcom, nVidia, Microsoft.

I tried to adopt Linux at various points, always at a transition point or
inflection point:

+ In 2004/2005 when it was hard: I couldn't deal with drivers.
+ In 2008: windows just seemed simpler for my work and storage/image management
  made VM's a PITA. Issues reading/writing NTFS meant it was a PITA. I had
  already decided that I wouldn't use NFS/Samba since I didn't like the idea
  that the gubment could read/write to my disks/files, potentially planting data
  -- paranoid, but I knew I didn't know enough about setting up security to be
  sure.
+ In 2009: tried to install Linux on a new ASUS laptop. If I had been
  successful, I would've gotten back into Ruby/Rails development ... but I ran
  into GPU problems since Microsoft and their partners decided to fuck Linux one
  more time by making it a giant PITA for anyone to dare try the free shit
  without suffering. This is the "bumblebee" drama that made Linus Torvald's
  middle finger so famous.
+In 2011: here, I installed Arch, but package managers still needed to handle
  init scripts. I didn't know enough about what I didn't know about to work
  through that or it wasn't very fresh in my mind. At this point, AFAIK, SystemD
  was about to take over, which is basically the end of "traditional Unix"
  Linux. There were a lot of pros/cons in standardizing Linux init with SystemD,
  but I basically didnt' know what it was.
+ In 2013: still not learning much. Oh and proprietary disk formats without
  vendor support fucked it up again. Can't read/write to HFS. And did you read
  the note on Samba/NFS above? Do you think I trusted Dropbox? No, never used
  it.
+ In 2015: needed to run cool machine-learning shit in Docker for competitions
  in Toptal/Kaggle. But OSX/MacOS at that point had a HyperKit that wouldn't let
  you do that -- no machine learning for you, unless you want to open a Jupyter
  Notebook and push buttons like the 3 year old that thinks they're playing an
  arcade game. So I needed Linux ... but I had no idea what SystemD was. I
  didn't know to write packages. Everything was fine until I upgraded and
  something more than a hosed Grub happened to my install.
+ In 2019: needed to use Linux for POS Macbook Pro, but went with ArchLinux and
  my hardware model was specifically not getting nVidia updates, so trying to
  figure that out was where all my time when. Fuck you nVidia.
+ In 2020 (macbook pro 2011 hard disk and RAM issues)
+ In 2021 (sway issues)
