:PROPERTIES:
:ID:       3ab1834a-2e65-4273-8bad-9f4095e06484
:END:
#+TITLE: Recipe: Shakshuka
#+CATEGORY: slips
#+TAGS:

A good money saver that can incorporate quite a few spare vegetables in your
fridge. Takes a bit of time to prep, but is worth it.

See this video and others to get a feel for the process.

It's recommended to have a pan with a lid on it. This is actually really
important. Also, if the pan doesn't completely fit on the radiator, you'll have
to stir a bit more.

* Recipe

** Ingredients

Feeds four or five. I'm not sure if this recipe really scales linearly (i.e. I'm
not sure you can just double the ingredients)

I think this is everything.

*** Oils

+ ~1. tablespoon :: coconut oil
+ 1/6 stick :: butter

*** Veggies

These are somewhat in order

+ 1/2 onion :: slightly large slices, since they cook longest
+ 24 oz (1 jar) :: tomato sauce. ensure the spices complement paprika/sofrito
  (garlic is safe)
+ 1 :: zucchini. You can use slightly more
+ 6 oz (1/2 jar) :: Sofrito
+ 16 oz (1 can) :: can of chickpeas
+ 1 bunch :: cilantro

*** Seasoning

+ 1 teaspoon :: paprika

*** Optional

+ bell peppers

Added at the end (raw is better here)

+ feta cheese
+ spinach leaves
+ some remaining cilantro

*** Serve

Serve in bowl or pan, but let it cool first.  Serve with naan or pita bread or
maybe some quinoa/rice to mix it into.

** Directions

Mostly the same as the others. Pay attention to the size you chop the vegetables
and onions.

Pan at medium heat or about =50˚C= or =~125°F= start with coconut oil. Then add
butter to prevent burning.

Wait for pan to get to about =60°C=. Here, add the onions, which will take about
3-5 minutes. They should turn translucent.

Stay between a target temperature of =60-70= This is about medium heat. If you
were to sauté mushrooms, it'd be about =120˚C= to start and =140˚C= max. If
using an IR temp scanner, the temperature of oils can be misleading and anything
underneat is higher. Mix to average out the temperature if it's permissable.

When onions are all good, add the peppers or zucchini, depending on how large
the zuccini is sliced. Wait for the temp to build back up, but maybe not all the
way. Throughout, stir the veggies to ensure the heat is even.

Add the [diced?] garlic throughout the pan. You want some vegetables out at this
point, but maybe not all of them. Wait for the garlic to get over its initial
sizzling and add the rest of the veggies.

Whenever it seems like there's not enough oil for the veggies, add a bit of
olive oil. If you just add that from the beginning, it will burn.

Then add the sofrito first. Then gradually add the tomato sauce. It doesn't
really need to cook, but its acids will make the veggies softer (the heat
probably does more here, but they work together)

Add the paprika and stir thoroughly to avoid clumping.

Add chickpeas. These add protein and fill to the dish. They're already soft:
high in protein, lowish in fiber, so they don't need to cook long. If they are
cool, this will give you time to cook the eggs without overdoing the veggies,
which is a problem you may not encounter with sqeezed canned tomatos.

Possibly add some water here to help create steam.

Add the eggs. Create some divets for the eggs to sink into. Ensure that you do
not use partially cracked eggs. Breaking them leads to a bit of a mess, so be
ready for that.

Cover the pan and wait for the tops of the eggs to almost finish
changing. Remove the heat and cool.

Add the spinach, extra cilantro or

Serve with naan or pita bread.

** Tips

Ensure that at least the big stems are out of the cilantro

The order of the incredients depends on how quickly they cook and timing is
important. Don't include too many vegetables or you won't have room for the eggs
and you'll get a messy pan lid.

You can use the additional ingredients to control the heat. Too hot? Sometimes
it's okay to add something a bit early. This is why you want everything warm.

If you use Sofrito, don't overseason. Parika complements safrito, but I'm not
sure about cumin.

+ Add salt just before pouring in the sofrito/sauce.
+ Add paprika after sofrito/sauce, but add slowly, since it clumps up.
+ Add pepper at the end.

Subbing the vegetables avoids the need for squashable canned tomatoes, but they
serve a purpose: to provide enough structure in the shakshuka so the eggs sit
right on top and so it's easy to press in a dip that they can sit in.

Breaking the yolk causes the eggs to cook faster and you won't end up with the
egg yellows (if you don't want that)

+ Eggs should cook at =63˚ C= which is =~140° F=

* Original Recipe

From [[https://www.allrecipes.com/recipe/256299/mexican-shakshuka/][Allrecipes]]

Included here for comparison

** Ingredients

Basics

+ 2 tablespoons vegetable oil
+ 1 cup diced onion
+ 1 tablespoon minced garlic

Veggies

+ 2 (14.5 ounce) cans Hunt's® Diced Tomatoes, undrained
+ 3 tablespoons Hunt's® Tomato Paste
+ 1 (8 ounce) jar roasted red bell peppers, drained and chopped

Meat

+ 6 +large+ medium eggs, or more as needed

Spices

+ 1 teaspoon chili powder
+ 1 teaspoon ground ancho chile powder
+ 1 teaspoon ground cumin
+ 1 teaspoon Spanish paprika
+ salt and pepper to taste (later)

Misc

+ ½ cup water

** Directions

Heat oil in a skillet over medium heat. Sauté onion in hot oil until translucent
and tender, about 5 minutes. Add roasted peppers and garlic; sauté until
fragrant, 1 to 2 minutes. Stir in tomato paste, chili powders, cumin, and
paprika. Sauté until well combined, 1 to 2 minutes more.

Stir in tomatoes and water. Season with salt and pepper. Raise heat to
medium-high and bring mixture to a boil. Immediately reduce heat to medium and
cook for about 5 minutes.

Reduce heat to medium-low. Make a well in tomato mixture for each egg; pour 1
egg into each well. Cover; poach until whites are firm and yolks have thickened
but are not hard, 2 1/2 to 5 minutes.

** Tips

Serving size depends on the number of eggs you want to poach. If they are large,
only 5 or 6 will fit. I now use medium eggs to get more servings with more
sauce. Yum.

* Roam
+ [[id:4bbb591a-dd94-40ba-93eb-7386de2f5f4b][Cooking]]
