:PROPERTIES:
:ID:       4ea74826-8caf-47d0-bb40-f23e27359d07
:END:
#+TITLE: Cloud: Terraform On GCP
#+CATEGORY: slips
#+TAGS:

* Docs

* Resources

* Notes

** Concepts

+ Manage infrastructure
+ Track changes
+ Automate changes
+ Standardize configurations

*** Provisioning vs Configuration

The concepts are blurred and aren't simple to discriminate. In networking
contexts, whether signaling to routers or GCP network device objects,
provisioning may include sending a subset of network state sufficient to
complete the configuration. Sometimes, you may consider this configuration
management, but the two are not separated from each other in semantics or in
your processes/code. This convolutes your projects and processes.

+ Provisioning :: signaling to VM hosts, cloud API's, network controllers or
  rack controllers to manage objects.

  In the cloud, the API provides an interface with rules/logic. You signal to it
  and on the backend it prepares the cloud provider state. You receive signals
  from it in response and proceed with provisioning. On bare metal, this would
  involve some cfg mgmt.

+ Config management :: distributing configuration/state to entities on the
  network, usually internal to those entities. e.g. cloud-config or ssh keys or
  network device configuration.

*** Stages

| write   |   |
| init    |   |
| plan    |   |
| apply   |   |
| destroy |   |

* Roam
+ [[id:8a6898ca-2c09-47aa-9a34-a74a78f6f823][Cloud]]
+ [[id:ac2a1ae4-a695-4226-91f0-8386dc4d9b07][DevOps]]
