:PROPERTIES:
:ID:       eb560b9c-8775-4019-bd8a-cac0a1b2d1e7
:END:
#+TITLE: Tony Smith: Taixuanjing and Uwuu physics
#+CATEGORY: slips
#+DESCRIPTION:
#+TAGS:

* Roam
+ [[id:01f7dc95-2246-4871-af7c-b9cdfc248a01][Iching]]

* Geocities: Long Live Geocities!

So my boy Tony here, he links to a page from Al Gore's internet on the [[https://web.archive.org/web/20000619130516/https://www.angelfire.com/nm/videntes/Lattice.html][I Ching
Lattice]] (last online: Sept 2000)

#+begin_quote
... That's from back when the internet was functional. Web pages only really
load like 5x as fast today despite literally 1000x the bandwidth...

Since a website and its javascript open about a hundred TCP/IP and TLS
connections anytime you click a damn thing.

I'm serious. I remember the dial-up sound. There is basically no difference
between bloated angular/react apps and dialup.
#+end_quote

* Whoa is this an episode of Stein's gate?

Behold: the [[https://www.tony5m17h.net/TCZ.html][Truth Quark]]! This Tony guy was calling the Higgs boson mass at 130
GeV in the 90's (it's 125 GeV), which I guess isn't necessarily that forward
thinking since science is way ahead of public consciousness.

#+begin_quote
Spoiler alert! They started on LIGO in 1992.
#+end_quote

And he breaks [[https://www.tony5m17h.net/play456.html][down the E8 lattice]] for you. In raw-ass Tim-Berners Lee HTML.

[[https://www.tony5m17h.net/d4d5e6hist.html][VoDou Physics and the 130GeV Truth Quark]]

* Okay, I'm done.

Not sure how often this site gets updated, but I hope it's in the arctic seed
vault ... you know, in case ([[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiGuNTt-Lz-AhWQEFkFHTVaCvYQFnoECBMQAQ&url=https%3A%2F%2Fwww.imdb.com%2Ftitle%2Ftt11286314%2F&usg=AOvVaw2cFAaIyYRvJNPDKGjKnJ1t][Don't Look Up]]) we have no netflix once the
"asteroid" hits and we can't get much on our crappy shortwave/satellite
internet.

Seriously, actually grokking half the shit on this site is like the
epistemological equivalent to smoking DMT.

* Okay nevermind: they banned his book

Oh and apparently Cornell banned his book ... because of course they would. It
really looks like he didn't have much support, but thank God people like this
are permitted to be prolific in their own way instead of marginalized/alienated
by a mostly ignorant public. It's easy to turn people against intellectuals:
just tell the public they're crazy and no one will know the difference. The more
complicated their ideas, the more alienating that any struggle will become -- by
the measure of intellect your enemy will be destroyed. If they aren't accepted
by the coronated institutional academics then they're just crazy.

They did the same thing to Nassim Taleb by the way:

[[https://www.quora.com/Why-does-Nasim-Taleb-hate-psychologists-so-much][Why does Nassim Taleb Hate Pyschologists So Much?]]

The plebs didn't understand his work (or something) and he ended up going
through psychiatric treatment in the 1990's before he realized that it doesn't
fucking matter what the plebs think (my uniformed interpretation anyways)

The term he used was iatrogenics -- see the chapter from [[https://fooledbyrandomness.com/medicine.pdf][Fooled by Randomness on
Convex Responses in Medicene]] about the lack of counterfactual analysis in
iatrogenic interventions. Reading this and discovering Nassim's work was a
critical turning point in a pretty dark period in my life because I found
someone who critically deconstructed (with math) just how badly "smart" and
"credentialed" people can fuck things up.

** Youtube is the only reason I have heard of Ibn Arabi

The [[https://www.youtube.com/watch?v=-bgWnzjONXE][videos]] on this channel explain the Sufi lineage behind and significance of
Ibn Arabi's ideas. His metaphysics and cosmology are not really arbitrary --
although metaphysics always lacks parity in its implementation. He provides a
kind of missing link extending from the Roman era's lost neoplatonist tradition
that was outcompeted by the theology/cosmology of Christianity. The link then
connects back to the Renaissance era developments in European
philosophy.

If this Tony guy was onto Ibn Arabi, Vedic mysticism, Iching, fucking
Taixuanjing and everything else in the 1990's, he had basically exhausted the
[[https://en.wikipedia.org/wiki/The_Library_of_Babel][Library of Babel]].

This guy was a genius and was not well-connected with the people around
him. They probably found his interests in the esoteric or spiritual or occult to
be irrational or trivial curiosities at best. Aetheists and scientists can
sometimes be real dicks -- they can easily play politics in an arena where it
just doesn't matter who is correct. And after the 1990's everyone kinda woke up
from the "string theory" era -- i.e. very few theoretical physicists were doing
anything other than smoking budgets.

Most of them are not as smart as they think they are. It's easy to use other
people as benchmarks to make yourself appear bigger/smarter.
