:PROPERTIES:
:ID:       24e96588-715c-49fc-b409-d1eb865688d8
:END:
#+TITLE: Python: Pyenv fix
#+CATEGORY: slips
#+TAGS:

okay seriously how did I not know about =locate --ignore-case= ... Like I knew
about =locate=, but I didn't realize it was system wide by default.

if it weren't that =M-x find-grep= showed the command it ran, I never would've
known about it. that command changed my life.

=M-x consult-locate= meh i donno it doesn't make as big of a geometric
difference now as =find-grep= made an arithmetic difference then.

locate found them all, but they're only half checked into git as .envrc.eg
files. syncthing would get a lot of them. i think I can use scp though, but one
wrong move and i'll be tapping the yubikey all night.

* Before

where's the error? keep in mind that, if for some reason, pyenv notices that an
ancestor specifies a =.python-version= file, it eats that file. a bit of a red herring.

#+begin_src sh
# -*- mode: sh; -*-
[[ -f ".python-version" ]] && pyversion=$(head .python-version) || pyversion="3.10.11"
[[ -f ".python-virtualenv" ]] && pvenv=$(head .python-virtualenv) || pvenv=$(basename $PWD)

# Create the virtualenv if not yet done (just depend on .python-version for this)
layout virtualenv ${pyversion} ${pyenv}
layout activate ${pyenv}-${pyversion}
  #+end_src

* After

this is exactly why ChatGPT's not that revolutionary. good thing it doesn't
include evil typos. good coder copy, bad coder paste.

#+begin_src sh
# -*- mode: sh; -*-
[[ -f ".python-version" ]] && py_version="$(head .python-version)" || py_version="3.10.11"
[[ -f ".python-virtualenv" ]] && py_venv="$(head .python-virtualenv)" || py_venv="$(basename $PWD)"

# Create the virtualenv if not yet done (just depend on .python-version for this)
layout virtualenv ${py_version} ${py_venv}
layout activate ${py_venv}-${py_version}
  #+end_src

