:PROPERTIES:
:ID:       7c84b0ff-5cc8-4554-a98c-256a93b37e89
:END:
#+TITLE: UV Vis: Detecting Presence of Toxic Chemicals on a 3000 annual salary
#+CATEGORY: slips
#+TAGS:


yeh, so this guy describes how your environment and chemical exposures
contribute to neurological inflammation

[[https://www.youtube.com/watch?v=TZuApro3rDw&t=530s][How to reduce brain inflammation with food & lifestyle ()Datis Kharrazian)]]

#+begin_export html
<iframe width="560" height="315"
src="https://www.youtube.com/embed/TZuApro3rDw?si=FmyxH64Zo2F0cUVN"
title="YouTube video player" frameborder="0" allow="accelerometer; autoplay;
clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
allowfullscreen></iframe>
#+end_export

how those "BPAs" are in even more chemicals and I
still can't figure how what this fibrous & flame-resistant & UV-reactant dust
is.

* Tools

I make about $3,000 per year and no one takes me seriously. I have labeled dust
samples dating back years, so if I wanted to test for specific contaminants, all
I need is several hundred dollars per hunch. GS/MS and other methods aren't
available to me.

This is far too expensive, so I fill in the gaps with creativity.

** UV/Vis Absorption and Emission

Wavelength of UV Flashlight: $\lambda =~ 265nm$

The flashlight has a Wood filter on it, which blocks many of the non-UV
frequencies. This makes reading the emission color (with human eyes) a bit more
clear. Since UV light is close to blue/purple, LED's which include frequencies
close to this can make objects appear to fluoresce when they don't. Emitted
wavelengths do exhibit transmittance and interference with other objects: nearby
objects will also glow blue, which is confusing.

For the purposes of estimating confidence in what my "anatomic spectrometer" is
reading, I'm assuming that:

+ spectral broadening of UV absorption generally doesn't extend more than
  $20nm$. This narrows things down quite a bit. The lower UVC bands are harmful
  in many ways, but these will also exhibit peaks around many bond types --
  i.e. UVC around $200nm$ causes fluorescence in 50% to 75% of common bonds.
+ any similar spectral broadening in the emission spectra can be difficult to
  interpret, given that the opsin proteins in our eyes can only detect three
  frequency bands and gradually lose their reactance after exposure.

*** Bonds and their absorption/emission characteristics

This table from [[https://www.priyamstudycentre.com/2021/07/ultraviolet-visible-spectroscopy.html][Ultraviolet Visible Spectroscopy]] helps narrow down what
functional groups could be responsible for observed Vis emission at $265nm$

Basically, when limited to these functional groups, most emissions should result
from four bond types:

+ Nitrogens: the extra electron pairs would enter an anti-bonding orbital.
+ Ketones: Similar energy transitions are possible as are with nitrogen.
+ Carbonyl: this group should not include carbonyls (nor aldehydes)


| Compounds      | λ_{max} (nm) | ∈_{max} (L/cm/mol) | Electronic transition |
|----------------+--------------+--------------------+-----------------------|
| Alkenes        |          177 |       1.3 × 10^{4} | n → π^{∗}              |
| Alkyne         |   178 -- 225 | 10 × 10^{3} -- 150 | n → π^{∗}              |
| Carbonyl       |   186 -- 280 | 1.0 × 10^{3} -- 16 | n → π^{∗}              |
| Carboxyl       |          204 |                 41 | n → π^{∗}              |
| Amide          |          214 |                 60 | n → π^{∗}              |
| Azo            |          339 |                  5 | n → π^{∗}              |
| Nitro          |          280 |                 22 | n → π^{∗}              |
| Ketone         |          282 |                 27 | n → π^{∗}              |
| Water          |          167 |      1.48 × 10^{3} | n → σ^{∗}              |
| Methyl Alcohol |          184 |                 15 | n → σ^{∗}              |
| Benzene        |          204 |       7.9 × 10^{3} | n → σ^{∗}              |

This table doesn't really account for potential halogens (fluorine, chlorine,
bromine). AFAIK, /generally/ any bond lengths between Row 2 elements (like
carbon/nitrogen) and Row 2/3/4 elements:

+ should be longer if it's a single bond with the exception of C-F bonds (and
  perhaps others)
+ should have double bonds longer than your average single bond and shorter than
  your average C-C double bonds.
+ triple bonds do not commonly occur outside of C-C bonds and organometallic
  bonds.

So, because the bond lengths change then the bond's available energy level
transformations also change. Thus the functional groups contribution to
potential absorption/emission events changes accordingly ... but in which
specific ways is hard to determine since "general rules of thumb" don't get you
very far. This is all complicated by things like tranistions between conformers,
which all exist simultaneously.

And unfortunately, since American society has so brutally keep me under its
boot, then I have a fucking flashlight and a BIC lighter to work with -- so I'm
really so fucking sorry about how pissed off I am when I know very precisely how
angry to be.

#+begin_quote
Interesting sidenote, organometallic chemistry is essential for manufacture of
solar panels and computer chips. Various Vapor Deposition techniques involve
combining lithography with series of "drop and swap" reactions using mechanisms
to carry ions in organometallic form to the surface of the substrate. Here
limiting the set of functional groups involved limits the range of
organometallic reaction mechanisms. Planning each "stage" involves figuring out
how to tune the affinity of mechanisms that lay down ions into the crystal
lattice while leaving ochem functional groups "on the table" which tune the
affinity of reactions in future stages. The reactants are filtered out after
each "stage."
#+end_quote

Carbonyls are functional groups encompassing ketones, aldehydes and carboxilic
acids. The latter two are carbonyls connecting a single R group opposite to
either a hydrogen or hydroxide, which determines their capacity to contribute to
alkalinity or acidity respectively.

***** TODO bonds and characteristics/stability

** Thermal Degradation

Temperature of a BIC lighter: $T = 1087^{\circ} C$ from $1900^{\circ} F$

* Chlorophyll

Almost all plants glow orange/red under UVC/UVB

* Fire Retardants

** BPA Family

* References

[cite:@kowalski-2014-simul-deter-six]

[[https://www.priyamstudycentre.com/2021/07/ultraviolet-visible-spectroscopy.html][Ultraviolet Visible Spectroscopy]] (Priyam Study Centre)

* Roam
+ [[id:fe6cfff6-52e4-44fe-a429-b8e599a3f008][Chemistry]]
+ [[id:7b98efac-9db8-4293-9e1c-d5730f0b1667][Spectroscopy]]
+ [[id:1e9132fa-33ec-4306-8a5c-47dd972293a7][Physics]]
