:PROPERTIES:
:ID:       6a3887bc-8ab9-478b-a109-ede45293724c
:END:
#+TITLE: So SSH JumpProxy Is A Thing
#+CATEGORY: slips
#+TAGS:  

* Roam
+ [[id:c2afa949-0d1c-4703-b69c-02ffa854d4f4][Cryptography]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]
+ [[id:ac2a1ae4-a695-4226-91f0-8386dc4d9b07][DevOps]]

* Rant

#+begin_quote
2026/7: yeh.... this one definitely caused me to start systemically questioning
everything else that um maybe i also did not know
#+end_quote

We didn't have this way back when. Everyone in 2012 (when the world was on Mayan
Calender Time) was like "Don't use SSH Agent Forwarding! But definitely you have
to use it ... but don't do it!" Forward the ports I guess?

... So I'm just inherently suspicious that this wasn't already a thing. What's
the catch? It seems very simple and when computers were dumb, people did simple
things because not only bc was easier to program/configure, but because it was
performant/tractible. The computational and networking limitations forced
protocol design up on a pedestal.

My guess is: newer OpenSSH has newer capabilities and maybe something permits
=stdin/stdout= to be forwarded ... though that's really a client capability for
programs on Linux that encapsulate(?) a socket within network. Yeh my unix is
still dumb.

Also, I feel really dumb for just assuming "jump host or proxy" was lingo
... the concept is trivially simple, esp when compared to the security headache
you need to worry about when your exposed Bastion uses SSH Agent Forwarding.

#+begin_quote
TFW... You binge on programming, devops & tech on and off for a decade ... but
only rarely see another person using a computer. And basically never work
alongside another person on a project.
#+end_quote

