:PROPERTIES:
:ID:       f2155afc-a61c-4bb4-ac49-e546412f0436
:END:
#+TITLE: Guix: Why Efficient Packaging Is Essential To Desktop Linux
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:b82627bf-a0de-45c5-8ff4-229936549942][Guix]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]
  
* YOLD

If you're wondering why "the year of the Linux Desktop" never arrives it's
because Linux on desktop and Linux in the network are two completely different
worlds. The capital available for Linux systems/development is controlled by
corporations who have quite a bit of inertia. It's hard for them to advocate for
new ideas for package management (like Nix or Guix), esp. since their own
packaging/infrastructure just really could not compete with the agility that you
gain. Most users just want to download/use a package though -- and this creates
a bad look where all you see in search/support is people having problems trying
to reuse code/packages/configs they don't actually understand. If your users are
not writing their own packages, you'll mostly just get unix porn. Devops and
systems work is maybe a bit different. The rest of us who don't get exposure to
corporate networks, automation, etc have to work with tooling tends to create
slow feedback loops and thus doesn't incentivize reuse of scripts/packages.

* Nix

Tooling for schemes and Geiser are probably available in vim, but the obvious
choice for lisp is Emacs. The Nix language/ecosystem seems to be on Team Vim,
but it's language/tooling should be fairly straightforward to configure in other
editors.

So Guix does pretty much require using emacs though, since efficient package
development requires using Geiser and parenedit/lispy. If you're not using those
tools, writing/building ad hoc packages going to be hard and slow. You can still
consume Guix packages, but for the time being, you may have considerably more
trouble when packages aren't available. That's just how it is.
AFAIK, neither =deb= nor =rpm= nor =pacman= have anything remotely like =guix
transform=. Each system has it's own way of supplying alternate packages, but
for me, it always seems like I don't want to have to go through supplying
alternatives lower level package dependencies with another, especially since
there's no concept of "profile." You can target alternate package installation
roots, but this doesn't work so well with Desktop packages that supply
higher-level dependencies: you need to ensure that icons/fonts/services/scripts
are all the ones you intend the rest of your desktop to refer to.

* On Guix Channels

Guix is actually much easier to use than most distributions, IMO, and I have
learned about Linux like 20x faster ... but you're going to need to =grep= the
codebase, since you /must/ write packages.

For channels:

+ All the commits need to be signed for all upstream branches AFAIK, which is a
  bit onerous. This may not be precise, but you need to ensure the Channel's
  =keyring= branch is manageable. If you forget to sign git commits, then
  downstream channels will fail, depending on how =channels.scm= validates git
  objects.
+ This encourages a patch-based workflow with better oversight over what makes
  it into a Guix channel. This increase in difficulty/complexity is actually
  beneficial for consumers in the longrun, In your local environments, you can
  still basically do whatever you want.
+ ... this _only seems difficult_ because Guix isn't insanely popular, so you
  have to know how to grok the manual and workflows. This apparent steep
  learning curve would be more manageable if larger distributions (or smaller
  distributions) didn't preemptively siphon all the capital/manpower available
  for Linux experimentation.

* Archlinux


So why is Arch popular? Because unix porn or installers or streamers? No. It's
because it disrupted the package evolution/disribution of corporate Linux
distro's. With Arch, you could more easily get packages for newer code. No more
waiting until next Christmas to get the next minor version of nodejs or
libxyz.so or whatever ... but in the entire history of Arch Linux, what
proprietary vendors set up pacman package repositories? Like basically none. So
on one hand, you could experiment with new things, but woe unto he who needs
"normal" software like Matlab, Bazel or GPU drivers (for most of the
history). Some may have been listed on Arch/AUR, but then it became a mess
because the corps were like "no fuck that. that's your problem." Linux as a
whole collectively benefitted from this and so did many of the corporations who
needed open source to evolve faster.

For most use cases, containers resolved these problems. Still, whenever there's
particularly onerous software licensing, they don't release containers, they
don't support reasonable approaches and, on Linux, you're perpetually treated
like maybe you're stealing their software. It's not that bad, but it's annoying
as shit. I just want to install it. You saw my receipts. I have the lhe license.
I want to use it on my Arch system, but it's basically as good as useless. After
about 2015ish, getting software on unpackaged distributions became more
reasonable. These vendors should have always been maintaining AppImage's,
IMO.. However, you can't easily persist custom configurations for some of this
software if you download a zip with raw binary. The installation process is
entirely contorted around their need to ask for your receipt.

On other platforms, it can be better or worse. Installing 10 - 20 Autodesk
installations back-to-back is fairly straightforward, but you have to run them
one at a time because their .NET Service manages Licensing/Installation.
Convenient, and not that bad, once you can predict how long each installation
will take. But notice how the process is contorted around the
licensing/pricing. It is what it is. It's not so bad when it takes your time
once. Autodesk configuration is fairly simple to back up and make portable. And
I don't want to complain about Windows software, it's more that Linux
software/configuration shouldn't be reduced to feeling like it's software you've
installed on Windows ... simply because you paid for it.

For Linux software, it's when the licensing mechanism interferes with automation
or portability of configuration. Typically, the number of problems you encounter
will depend on how much government money these vendors get. It's much better
/these days/ -- which is great considering we're on the edge of the literal
apocalypse. If you deep-dive into pretty much every application you use, it
really sucks to /invest your time/ to learning their proprietary system just to
realize that, later:

+ this contortion prevented you from backing up or restoring configs.
+ you can't automate installation/configuration
+ there's no real scripting interface, since the product was just ported from an
  application that wasn't designed from the ground up to be modular.

Well I've paid quite a bit of my time to learn Linux because the allure was
modularity, easy builds, a wide array of tools, reproducibility, services
without .NET and Visual Studio, etc. This is all very powerful, but because
large corporations need to check your receipts for contracts which are mostly
awarded outside of a free market system (by circumventing your choice to
purchase and leaving it to administration), then the way I would like to work on
things is basically null and void. It will certainly never accumulate much
social momentum because automation is challenging. People with the ability to
decide what their corp/business/department/etc uses are few in number, and
they're decisions are made in their best interests or the best interests of
students. Still this rigs the marketplace. And ultimately, if you no longer have
access to the license, you can only continue to use the general skills you
learned. Really, both the proprietary software and free options are needed, even
favoring the proprietary software for situations where it's obviously better or
more likely to get you a job. However, the development of more open alternatives
should perhaps receive funding -- this isn't free market if the government is
disrupting the balance in some industry. However, we are far from a free market
in quite a few industries/contexts.


