:PROPERTIES:
:ID:       1cb19e27-8fb8-4381-948d-1ba3af963175
:END:
#+TITLE: Abnormal sociology: compare circumlocution to a random walk through conversational topics
#+CATEGORY: slips
#+TAGS:

How could I not realize this and a few other key things? And I get the feeling
that I've been isolated (that's clear), but that occasionally I ask for help and
either get nothing or worse. I'm just not sure how I could try so hard to get
answers/advice (with various levels of competence) and yet be so confused
... because it's not hard. I simply never acknowledged some basic things about
Linux for various reasons. Things I thought I knew were some of the worst. It's
like the non-zen mind.

And I'm not trying to blame other people here. There have been many
meetups/mentors or IRL/IRC/discord conversations that end up being
formative. I'm stupid sometimes, but also exceedingly intelligent: if my mind
acknowledges the right parts of something there's basically no way I can't
understand it. I have blindspots, but I am coachable. Neurological or
idiosyncratic limitations may cause problems, but I'm pretty sure isolation and
mischaracterization are far worse. It just seems like people don't interact wiht
me the way that they normally interact/converse with others.

I just navigated through life as though of course everyone would altruistically
help everyone else. The smarter people were, the more capable and willing I
assumed they would be in doing so. I never imagined that people would want to
keep the wool over your eyes because either (somehow) people think you deserve
to fail or people just systematically keep knowledge/experience close to their
chest ... for reasons, whatever they are. Pair programming could've helped a
lot. Office politics blindsided me a few times, but social dynamics can have
disproportionate effects on people with characteristically unusual social
connections/graphs. I barely remember what things were like when I would
describe them as "normal" and I remember that people's general disposition was
to help other people or me, even when I didn't deserve it. And then, things got
wierd and never returned to normal. Something has been very wrong with my life
in a very abnormal & disorienting way.

It's not every arbitrary person's responsibility to teach you everything
... however, when you definitively know that people are probing the boundaries
of your knowledge set, wouldn't they normally reciprocate by conveying new
information to you. Take your average conversation's random walk through
adjacent topics: information tends to be exchanged in both directions. If the
flow of information is extremely biased and this bias is almost universally
conserved ... then that is abnormal. If instead, key words and phrases are
tossed around until it is clear something was mentioned that you don't recognize
and that topic's circumlocution moves to a new topic ... then maybe your
knowledge set is being probed.

And mostly it's not the things people said or did ... it's the obvious
answers/tips that they didn't clue me in on.

+ Like can =pacman= really not install to multiple package roots or prefixes?
+ Do you really need a second pacman repository locally to do that?
+ Can you really not clone the entire =AUR= in one command like you can for the
  =Arch= package repositories??

And that last thing: that you can =ripgrep= ALLLLL of the archlinux =PKGBUILD=
files in one go after cloning like 5 repositories..... How did I never encounter
resources that mentioned that? And why wouldn't this be one of the first things
an experienced person conveys to a programmer who is new to arch and knows how
to use =find-grep= or =ripgrep=?

It's this wierd "reality distortion field" where somehow everyone can be so much
smarter than me yet almost never do I get help from people in my field. Not in
the way that I would reciprocate if I could. The isolation is quite
disorienting.
