:PROPERTIES:
:ID:       d78fbb42-963f-448a-aeef-e86919aec4cf
:END:
#+TITLE: Emacs: Combining Emacs Packages from Straight and Guix
#+CATEGORY: slips
#+TAGS:

* Resources

* Notes

Until recently, I haven't had many problems with combining Guix and Straight
packages, although it's important to define 'straight-built-in-pseudo-packages
for any conflicts. The way that Guix sets things up, the load-path is
constructed before =init.el= runs and contains everything


This has been a fairly good way to load packages for me, but it's definitely
non-standard. It's definitely not correct, per se. The Guix packages are always
stable and straight packages (1) give me the flexibility to pull in new packages
and (2) make it fairly easy to contribute to emacs packages, since everything is
ready to fork/pull/checkout/etc.

You will need to manually run things like:

+ straight-pull-packages
+ straight-build-packages


* Issues

** Straight uses vc-mode

If you use forge to manage pull requests ... well straight uses =vc-mode= so you
may run into issues when updating your straight packages. I haven't fully
figured that out yet. It's best to just stick with =vc-mode= when working on
straight repositories.

There's something different about the =.git/config= that straight doesn't like
when you fork a repository using forge. I haven't had time to fully figure it
out. Ideally, you could fork the repository with forge and straight will
continue updating.

#+begin_quote
it could be simple, but it might not be ... when using emacs, you're always
hedging against complexity. I wish there was a complexity broker to offer me
profitable "emacs-config" futures ... but there's not. Maybe there is i donno.
#+end_quote

** Fonts don't load

For me, this has been a good indicator that init.el doesn't finish loading or
that blocks from =(with-eval-after-load 'apkg' ...)= aren't running.

However, the fonts aren't a great indicator not entirely clear.

** Something can't find 'compat

This just popped up, but I can't find what's prompting the message. I searched
the straight source, but i haven't searched the emacs =site-lisp=

There don't immediately appear to be any consequences, but I'm worried something
is lurking or that my =init.el= will stop fully loading.

*** Problem

Can't seem to silence these warnings on init:

#+begin_example
Unable to activate package ‘with-editor’.
Required package ‘compat-29.1.4.1’ is unavailable
Unable to activate package ‘transient’.
Required package ‘compat-29.1.4.1’ is unavailable
Unable to activate package ‘no-littering’.
Required package ‘compat-29.1.4.2’ is unavailable
Unable to activate package ‘magit’.
Required package ‘compat-29.1.3.4’ is unavailable
Unable to activate package ‘magithub’.
Required package ‘magit-2.12’ is unavailable
Unable to activate package ‘magit-section’.
Required package ‘compat-29.1.3.4’ is unavailable
Unable to activate package ‘magit’.
Required package ‘compat-29.1.3.4’ is unavailable
Unable to activate package ‘helm-bibtex’.
Required package ‘helm-1.5.5’ is unavailable
Unable to activate package ‘git-commit’.
Required package ‘compat-29.1.3.4’ is unavailable
Unable to activate package ‘ghub’.
Required package ‘compat-29.1.4.1’ is unavailable
Unable to activate package ‘ghub’.
Required package ‘compat-29.1.4.1’ is unavailable
Unable to activate package ‘ghub+’.
Required package ‘ghub-2.0’ is unavailable
Loading /home/dc/.dotfiles/.emacs.d/per-system-settings.el (source)...done
Loading /tmp/emacs-custom-1000.el (source)...done
Loading dired (native compiled elisp)...done
Loading /home/dc/.emacs.d/per-system-settings.el (source)...done
Loading info+ (native compiled elisp)...done
org-super-agenda-mode enabled.
Loading cider-connection (native compiled elisp)...done
Loading gnus (native compiled elisp)...done
Starting Emacs daemon.
Restarting server
Turning on magit-auto-revert-mode...done
Running direnv in /home/dc/ ... (C-g to abort)
Direnv succeeded in /home/dc/
Running direnv in /home/dc/ ... (C-g to abort)
Direnv succeeded in /home/dc/
Loaded ‘ef-frost’
 *** Emacs loaded in 6.11 seconds with 36 garbage collections.
[yas] Prepared just-in-time loading of snippets successfully.
When done with this frame, type C-x 5 0
Desktop file in use; not loaded.
You can run the command ‘desktop-read’ with C-h <f2> D r
Loading /home/dc/.emacs.g/var/recentf-save.el (source)...done
Cleaning up the recentf list...
File /tmp/refcard-ERT/README.org removed from the recentf list
File /tmp/refcard-ERT/README.pdf removed from the recentf list
File /tmp/refcard-ERT/README.tex removed from the recentf list
File /tmp/refcard-ERT/theme-readtheorg.setup removed from the recentf list
File /tmp/refcard-ERT/README.log removed from the recentf list
File /tmp/lsp.Dockerfile removed from the recentf list
Cleaning up the recentf list...done (6 removed)
bookmark-get-bookmark: Invalid bookmark ~/.emacs.g/var/desktop
Use M-x make-directory RET RET to create the directory and its parents
Running direnv in /home/dc/ ... (C-g to abort)
Direnv succeeded in /home/dc/
previous-line: Beginning of buffer [2 times]
previous-line: Beginning of bufferInvalid face reference: quote
Invalid face reference: quote
Delete .emacs.desktop.lock (y or n) y
Deleting...done
next-line: End of buffer
Problems while trying to load feature ‘org-notify’
org-make-toc-mode enabled. [2 times]
Wrote /home/dc/.emacs.g/var/desktop/.emacs.desktop.lock
Clearing removed files...done
Processing modified files...done
Clearing removed files...done
Processing modified files...done
finalizer failed: (wrong-type-argument sqlitep nil)
Desktop: 3 frames, 10 buffers restored.
Beginning of buffer [5 times]
scroll-down-command: Beginning of buffer [2 times]
Quit
Mark set
Quit
org-make-toc-mode enabled.
Mark set
with-editor
Quit
org-make-toc-mode enabled.
Quit
magit-display-buffer-same-window-except-diff-v1
Mark set
Quit [2 times]
Mark set [4 times]
nil
You can run the command ‘emoji-list’ with C-x 8 e l
Mark set [2 times]
gnu/linux
Quit
Fetching Revisions...done
David Conner: updates [Sat Sep 16 18:10:56 2023 -0400 (3 hours ago)]
Blaming...done
Quit
Auto-saving...done
Saving file /home/dc/.emacs.g/modules/dc-interface.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-interface.el
Mark set [2 times]
Saving file /home/dc/.emacs.g/modules/dc-interface.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-interface.el
Saving file /home/dc/.emacs.g/modules/dc-interface.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-interface.el
Mark set
Saving file /home/dc/.emacs.g/modules/dc-interface.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-interface.el
Mark set
Saving file /home/dc/.emacs.g/modules/dc-interface.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-interface.el
Dependents of "with-editor": ("ein" ("git-commit" ("magit" "magit-tbdiff")) ("magit" "magit-tbdiff"))
(No changes need to be saved)
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Quit
Dependents of "with-editor": ("ein" ("git-commit" ("magit" "magit-tbdiff")) ("magit" "magit-tbdiff"))
Saving file /home/dc/.emacs.g/modules/dc-dev.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-dev.el
Note: file is write protected
Quit
Starting Guix REPL ... [5 times]
A single package with name 'emacs-ghub'.
(No changes need to be saved)
Dependents of "with-editor": ("ein" ("git-commit" ("magit" "magit-tbdiff")) ("magit" "magit-tbdiff"))
You can run the command ‘straight-dependents’ with C-h <f2> $ D
Dependents of "with-editor": ("ein" ("git-commit" ("magit" "magit-tbdiff")) ("magit" "magit-tbdiff"))
Mark set
Saving file /home/dc/.emacs.g/modules/dc-dev-python.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-dev-python.el
Running git commit --
Only whitespace and/or comments; message not saved
Diffing changes to be committed (C-g to abort diffing)
When done with a buffer, type C-c C-c
Type C-c C-c to finish, C-c C-k to cancel, and M-p and M-n to recover older messages
Mark set [2 times]
Saving file /home/dc/.emacs.g/.git/COMMIT_EDITMSG...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/.git/COMMIT_EDITMSG
Message saved
Git finished
Running git push -v origin master:refs/heads/master
Git finished
Quit [2 times]
Saving file /home/dc/.emacs.g/modules/dc-dev.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-dev.el
Dependents of "magit-section": (("org-roam" "consult-org-roam") ("magit" "magit-tbdiff"))
You can run the command ‘straight-dependents’ with C-h <f2> $ D
Dependents of "magit-section": (("org-roam" "consult-org-roam") ("magit" "magit-tbdiff")) [2 times]
You can run the command ‘straight-dependents’ with C-h <f2> $ D
Dependents of "magit-section": (("org-roam" "consult-org-roam") ("magit" "magit-tbdiff"))
Beginning of buffer [5 times]
Quit
Type q to delete help window.
Note: file is write protected
Quit
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Mark set [2 times]
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
org-make-toc: No TOC node found.
Mark set
Quit [2 times]
<f2> p C-g is undefined
Quit [7 times]
Ace - Window
Quit
A single package with name 'emacs'. [2 times]
Invalid face reference: quote [8 times]
<f2> C-g is undefined
A single package with name 'emacs'. [3 times]
A single package with name 'emacs-ghub'.
bui-history-back: No previous element in history [3 times]
A single package with name 'emacs'. [2 times]
Quit
Beginning of buffer [2 times]
Saving file /home/dc/.emacs.g/modules/dc-shim.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-shim.el
Saving file /home/dc/.emacs.g/modules/dc-shim.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/modules/dc-shim.el
Mark set
(No changes need to be saved)
Beginning of buffer [5 times]
Mark set [2 times]
Quit
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Mark set
(No changes need to be saved)
Mark set [3 times]
Type q to delete help window.
Note: file is write protected
Quit
Mark set [2 times]
Quit [2 times]
"v3.3.0-768-g4f4ad9c0"
Beginning of buffer [22 times]
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Mark set
compat
Delete compat (y or n) y
Deleting...done
Mark set [2 times]
Quit [2 times]
Grep finished with matches found
Mark set [3 times]
Quit
Mark set [2 times]
Type q to delete help window.
Quit
Mark set
Quit
Mark set [2 times]
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Quit
Dependents of "magit-section": (("org-roam" "consult-org-roam") ("magit" "magit-tbdiff"))
Type q to delete help window.
Mark set
Type q to delete help window.
Buffer is read-only: #<buffer *Help*>
Followed link to /home/dc/.emacs.g/straight/repos/magit/lisp/magit-section.el
Quit
Auto-saving...done
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Mark set [3 times]
Copied text from "
Loading /home/dc/.emacs.d/per-system-se"
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
(New file)
org-make-toc-mode enabled.
Auto-saving...done
Quit
#[257 \300!\210`\300[!\210`B\207 [forward-char] 4

(fn X)]: End of buffer
Quit
Mark set [2 times]
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
Mark set
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
(No changes need to be saved)
Mark set
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
Mark set
Mark set (rectangle mode)
Mark set [5 times]
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
Mark set [2 times]
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
Mark set
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
org-edit-src-code: No such language mode: nil-mode
Mark set
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
Mark set [3 times]
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
Mark set
[other]: h j k l SPC g
zero candidates
lispy--eval-elisp: Symbol’s value as variable is void: \.emacs.g/scratch/package-warnings.org
Quit
Saving file /home/dc/.emacs.g/init.el...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/init.el
Mark set [3 times]
Saving file /home/dc/.emacs.g/scratch/package-warnings.org...
org-make-toc: No TOC node found.
Wrote /home/dc/.emacs.g/scratch/package-warnings.org
org-make-toc-mode enabled. [2 times]
(New file)
org-make-toc-mode enabled. [17 times]
org-make-toc: No TOC node found.
Wrote /data/org/roam/slips/20230916212950-emacs_combining_emacs_packages_from_straight_and_guix.org

#+end_example

*** Solution?

alot of warnings like this when loading ghub

- Required package ‘compat-29.1.4.1’ is unavailable
- these reference the wrong version numbers (magit-2.21, ghub-2.0, ghub+)
- see .emacs.g/scratch/package-warnings.org

I added compat/magit to =straight-built-in-pseudo-packages= and even required it
very early on.

#+begin_src emacs-lisp
(require 'compat)


;; get straight to avoid fetching these (i'm hoping it will build against the
;; correct entryies in load-paths, but I haven't had problems yet.

(let ((deps-from-guix
       '(pdf-tools org which-key hydra eglot magit compat
                   embark consult corfu cape vertigo marginalia
                   orderless kind-icon)))
  (mapc (apply-partially #'add-to-list 'straight-built-in-pseudo-packages)
        deps-from-guix))

#+end_src

* Roam
+ [[id:6f769bd4-6f54-4da7-a329-8cf5226128c9][Emacs]]
