:PROPERTIES:
:ID:       52e8cc43-e252-4f76-bfda-40afbfffb1b8
:END:
#+TITLE: Medical Stuff And Things
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:ef2ad591-9e40-4011-9c91-3942462ecb58][Medicine]]

* Notes

I feel like it's important for people to do some personal research, take notes,
collect health data, etc. i've had some issues going on, but i feel like for
some reason, I haven't had the proper tests done. for the past 5 or so years,
this is because I haven't been insured. before that, it was likely that I wasn't
persistent enough or regularly seen by my doctors enough. most doctors i've seen
have listened to me, with the exception of maybe a psychiatrist or two, which i
only would have seen once. if i don't trust my doctor, i will definitely find
another doctor.

what I'm dealing with is mostly fatigue and brain fog, specifically in reaction
to food. I did have a gluten allergy, which i eventually fixed with a specific
probiotic product (i tried four or more), but that was just one cause for one
specific pattern of symptoms. i was tested for celiac, which is recognized as a
diagnosis, but it was negative. at one point, i suspected a thyroid issue for
various reasons, but i've since looked at the digital copies and those levels
were fairly normal. most of the test records that I have accessible are really
within fairly normal levels AFAIK. i seem to be very sensitive to various
products containing VoC's, which just seems to be a general temporary
response. i also suspect neurological inflammation, for which I take low-dose
aspirin and eat broccoli/spinach/eggs/mushrooms.

now i suspect something is causing metabolic acidosis. and i should be able to
get some lab tests done at a free clinic, i think. i'm not sure what it would
show, since the patterns of sympoms are fairly sporatic and definitely depend on
what i eat. i think there are problems with bicarbonate reabsorption, but my
urine is definitely on the acidic side unless i eat vegetables like
broccoli/etc. if there's a strong anion gap, then this will be plain to see. if
it's not a metabolic acidosis that presents with anion gap, it would likely take
a few visits and the first lab results will show seemingly negative results. i
really just don't have the time (or experience) to delve into system's medicine
and the kidney. i know enough to see how i've been wrong or shortsighted about
things in the past. ultimately having a few sets of lab results should make
things clear enough to determine whether there's something to worry about. if
so, then now i know, but if not, then i know how certain foods make me feel and
i listen to my body.

i really wish I had been more persistent about having lab tests done while i had
health insurance, but i could barely afford the co-pays. i've been out of work
for a long time because i was traumatized from being bullied at work and then
couldn't stop ruminating over it, which only reinforced the trauma. in the past
ten years, i only earned enough income to qualify for obamacare for three of
those years. i should otherwise be making six figures (after maybe a year or
so). i'm also socially isolated and i don't trust the few people that are close
to me enough to bring them to the doctor, since what they have will simply
dominate everything. they don't really listen and need people to see things
their way, which is basically that I'm a deadbeat PoS who cant/wont do anything.

a bit too long and maybe TMI, but it is what it is. it does suck, but it's not
really anyone's fault. it's really a lack of social connection, which is no
one's fault. this is worse because then no one can really fix it and no pill
would directly help it. when i've tried to ask for help or get people to pay
attention, it really only makes things worse. and yeh, there are things I could
do to mildly improve the situation ... but consequences of social isolation are
multiplicative: when you have zero social connections it's like multiplying
typical benefits of social connection by zero. with the absence of other people,
there's no one to ask for help and very few people who would even be able to
describe what I'm normally like, let alone what I'm like if I'm experiencing
"metabolic acidosis" or adrenal fatigue or whatever.

and trying to get a job only brings me further away from other people because it
requires that i spend an inordinate amount of time learning new technologies,
prog. languages, frameworks, etc. there are very few people in my local area
interested in the same thing, so spending time with other people usually means
giving up on all my goals or returning to a normal life.


...


and reading through some of these comments really brings things into
perspective. a few of these are really sad. regardless of whether things really
went down the way they are presented in some of these comments, they are really
sad stories about critical moments in the healthcare system and people are left
feeling that the medical system has treated them this way. i'm not saying
they're true or not, but people are recounting in good faith what they believe
has happened in their lives as they see it. but these are high-stakes situations
where it's already challenging to validate the meaning/implication of medical
terminology/treatments, but especially so the members of a healthcare system
generally want to avoid the possibility of a lawsuit while conducting themselves
honestly/ethically. it can already be difficult to extract information from
medical records, especially if it relates to someone else or someone deceased.

i think bringing down the cost of lab testing should make it much easier to
avoid edge cases in surgeries. the pricing on lab tests can be outrageous, but
generally no one recognizes what their provider is paying. the provider is
simply obligated to pay based on the doctor's experience/analysis and the
patient's conditions. collecting more data earlier or being able to combine it
with dietary/nutritional data would really help inform better decisions or
better care.  things like time of day could affect test results, esp. for people
who work late shifts. it should be normal to collect multiple lab tests or to
schedule lab tests to be conducted at a time of the patients' choosing (in some
cases).

but they nuked theranos from orbit, which was a company whose intellectual
property will not be integrated into other products for about a decade. the test
that the media focused on was for warfarin ... which itself affects the
solubility characteristics of blood: the medium which is used for UV/VIS or
other methodologies. the capillary action that their so-called "small sample"
tests depend on would be something that warfarin would make incredibly
unpredictable: it's a huge challenge to get accurate spectroscopic readings for
levels of a blood thinner when the drug itself affects the hydrostatics of the
solution -- in a capillary tube! a blood thinner. warfarin is like *the very
last test* that theranos should have been attempting to get approval for.

