:PROPERTIES:
:ID:       94d8711e-2bcf-4f18-8df5-268780a2df2b
:END:
#+TITLE: Social Media: Comment on using Davinci Resolve on Linux Deleted
#+CATEGORY: slips
#+TAGS:

I am using org-mode to export this to PDF, which will be faxed to Google's
office at =+1 650-253-0001=, since there is no way to actually get someone to
look at my complaint. If I want, I will fax this to YouTube every day until I
get a response.

I got screwed out of $75 by Apple, since they wouldn't refund me after
doublecharging me for a Tidal subscription. I am tired of not having any voice
in your platforms or products. You can do whatever you want with impunity and
there is no recourse for the user.

I watched a video on using Davinci Resolve on Linux. Here is the URL.

https://www.youtube.com/watch?v=4Wl0oYYgbuM

I wanted to give the creator some advice on using Silverblue or uBlue. I am also
going through some issues with OpenCL reliability on Linux. Since this is an
average person with some experience and not a developer, I wanted to spend time
making sure that if I recommended some experimental distribution, that I
included enough information to not send the user down the wrong path.

In the past, if I included any URL, the comment was deleted and made
unrecoverable with zero indication as to why. You cannot survive without your
users. The data they submit to your applications gives you power. So you delete
my content without any notification because some spam filter flags it? Are you
serious? If the creator deleted it, that sucks, but that is their decision. If
an automated process deletes my content, it has wasted my time and my energy. I
should make better decisions and not waste the time providing you with data.

It is insulting to think that simply because Silicon Valley's social networks
vastly outcompete any remotely similar products. You are propped up as
monopolies and smear any competitor that begins to develop their own digital
social network.

The _only_ reason I have not deleted YouTube itself is for the lectures from
channels like Simon's institute. I deleted Facebook, Twitter and Instagram a
long time ago. I realized that because of my diverse interests and posts about
esoteric topics, Facebook's algorithm was just zeroing out my publication. I was
constantly shadowbanned -- just for being intelligent and wanting to find other
people to talk to.

I may delete YouTube anyways. I should be /reading/ to learn, instead of wasting
my time watching videos. Why would I not, if your algorithms cannot bother to
value my time as a living, breathing person who does not want to feel like they
don't exist?

I wasted about an hour typing with my thumbs. The content was abour 800
words. Your app's mobile text entry sucks and encourages crappy 12-word comments
with zero real value. By implicitly discouraging intelligent & descriptive
responses to others online drives the political divide in America.

+ I am so tired of being made invisible on social media.
+ I am so tired of being subject to passive agressive policies on social media.
+ I am so tired of my politics being mischaracterized.

Respectfully _not_ yours,

David Conner
