:PROPERTIES:
:ID:       1c5d9a8a-faf1-420c-9f6b-48b669261a81
:END:
#+TITLE: Social Media: Dconstructing Identity
#+CATEGORY: slips
#+TAGS:
* Roam

* why avoid concent creation on forums?

My rational:

+ First, You give up claims to specific rights via their EULA, so you basically
  don't own the content. People may eventually be verrry angry abot this -- I
  never imagined that anyone would care.
+ More critical: you don't benefit whatsoever. You give away your time and it is
  completely fucking rigged. No one will ever see anything if people stop
  interacting with your content. The only people who will are lurkers. My
  content on social media has never done anything other than ruin my life. I was
  trying to find other intelligent people to talk to...

Instead, if you take more time to develop your content and publish it elsewhere
(website, book, etc), then as smaller total set of content is associated to
you. More people will have more consensus on the information that is important
in defining who you. LinkedIn might see more of this concensus (on how
individuals think society sees some specific individual), but only because their
network is so tightly coupled to brick & morter social institutions.

+ So much of someone's identity resides in the minds of other people,
  which are also aspects of identity not directly determined or governed by that
  individual themselves
+ _Consensus on identity_ causes it to congeal, become tangible and in some
  cases ossify. Thus, by disrupting this consensus process, sometimes being
  indirectly incentived to do so, Social media is to some extent [[https://en.wikipedia.org/wiki/Deconstruction][deconstructing]]
  not just individuals, but the viability of individuality.

The social media newsfeed is like an _infinite stack_ where the rate of /content
consumption/ is outpaced by /content creation/. i.e. things go onto the stack
faster than they come off. Their UI/UX is designed so no one searches or leaves
the site. So the content is irrelevant, since 99% of attention is directed
towards what happened less than 3 days ago. So many apps are like this.

The newsfeed and notifications tell you what to push and click. People won't
remember what happened three days ago (& maybe can't) ... to even try, they
would need to develop/persist the intention to find older content or specific
content on Facebook. Many of these companies cripple their search because

1) they aren't great at search
2) excellent search on social media is creepy. silicon valley doesn't the
   average /social/ media user to think too hard about it.
3) it's expensive
4) it screws with their A/B testing

So your content is only /briefly/ discoverable on Facebook or Social Media if
the Newsfeed Gods favor your fortune. /Discoverable/ is not the correct word
because the /subject-object relationships/ that give rise to /transitivity/ in
language are flipped inside out. Some individuals may be somewhat intentional
about social media, but you are not X-ing the Y on social media, Y is X'ing you.

Social Media is basically gambling. You either won your you'll be losing
forever. Younger people will have a harder time trying to gain ground online fi
they don't have an IRL presence first.
