:PROPERTIES:
:ID:       e7b14a19-db17-449c-bec7-a704810451ff
:END:
#+TITLE: Art: Lighting
#+CATEGORY: slips
#+TAGS:

* Topics

** Water

*** Ripples On Water

I'm not sure why it's so easy to visually imagine ripples moving outward, while
being less intuitive to imagine the same image with time flowing backwards.

You wouldn't notice most of these being off, but some of them are more essential
to visually parse an image. And, too much detail or effort in the wrong place
will ruin composition. Most of this relies to shallow pools of infinite size.

**** Shadow

+ Reflections redirect light energy, creating an apparent shadow. These occur on
  the waters' surface but also on the containers' surface, the latter of which
  is responsible for apparent shadow.
+ Refraction lenses the light energy, blurring the apparent shadow. The blur is
  increased with the depth of the water.

**** Value

Maxima, minima and saddle points are good points to focus on to identify similar
values, esp for surface highlights (resulting from reflections). The blurred
shadows should correlate to these maxima/minima, especially with a flat
container surface.

**** Motion

Ripples contain a history of recent motion with solid objects, etc. For objects
exerting force on the water surface, the image (shape) of the object's contact
may be encoded into the radial motion (the waves develop self-similar shapes
even if most are circular)

**** Singular Light Source (esp. parallel rays)

Observer sees ripples flowing out with radial dispersion of energy.

**** Shallow Water

If ripples flow across shallow water, several effects should be seen, especially
if the container surface is flat with uniform hue/value.

+ ripples disperse energy radially. this is in circular fashion at the surface,
  but spherically in the volume of water until they hit the container surface
  (floor of pool, etc)
+ the less the height a volume of water, the less time passes between reflection
  from the floor back to the surface.
+ thus, depending on the depth of water relative to the dominant frequency of
  kinetic waves, some frequencies will create interference with waves propagated
  along the surface.

It's well known that the depth of the water strongly shapes the propagation of
waves. See [[https://wikiwaves.org/Category:Shallow_Depth][Shallow Depth on wikiwaves.org]]

**** Energy

+ Height of ripples: energy in amplitude (taller, greater; smaller less)
+ Wavelength: more change over smaller periods
+ sound and transfer of energy between particles both occur occur more quickly
  in water (and, generally, in dense matter). but they also lose energy faster.

***** Parseval's Theorem

Applications of [[https://en.wikipedia.org/wiki/Parseval%27s_theorem][Parseval's Theorem]] utilize the conservation of power across
temporal and spectral domains, but it's especially useful when you can make
assumptions about continuity constraints and constraints on spectrum.

#+begin_quote
The interpretation of this form of the theorem is that the total energy of a
signal can be calculated by summing power-per-sample across time or spectral
power across frequency.
#+end_quote

Parseval's theorem can be applied to the energy in both the water and the light.

Continuity constraints in water

+ a tsunami is not going to spontaneously emerge in a swimming pool (the total
  energy in a system should only increase/decrease relative to the first/second
  order derivatives of kinetic energy transmission)
+ but also, the frequency spectrum of ripples through a point on the surface
  should change fairly smoothly from moment to moment. if it doesn't, it's an
  interesting event that requires more information to explain (it sticks
  out). This is separate from other spectral constraints on power spectral
  density.

**** Transfer of kinetic energy

The TLDR here is that water absorbs the impulse of objects to then radiate it
outwards in waves. As the change in momentum spreads, the waves decay in
magnitude.

Extrapolating from the model for bouyancy...

#+begin_quote
The [bouyancy] force exerted on the body can be calculated by integrating the
stress tensor over the surface of the body which is in contact with the fluid.
#+end_quote

In the [[https://en.wikipedia.org/wiki/Buoyancy][Bouyancy wiki]], the forces in the boundary are "traced" through the
submerged volume; the flux is summed to integrate to an idealized net force (sum
of divergence).

\begin{align*}
\label{}
\mathbf {B} =\oint \sigma \,d\mathbf {A}
=\int \operatorname{div}\sigma \, dV
=-\int \mathbf {f} \,dV
\end{align*}

From wiki on [[https://en.wikipedia.org/wiki/Divergence_theorem][Divergence Theorem]]:

#+begin_quote
Intuitively, it states that "the sum of all sources of the field in a region
(with sinks regarded as negative sources) gives the net flux out of the region".
#+end_quote

These bouyancy relations are normally applied to static systems, but using
another structure like the stress tensor on the surface of the sphere could
account for the [[https://www.khanacademy.org/science/physics/linear-momentum/momentum-tutorial/a/what-are-momentum-and-impulse][net change in momentum]] (the fluid displacement over time) by
relating it to impulse. Fluids "absorb" energy with turbulence, so it acts a bit
differently. A similar process should be capable of relating the Laplacian
(here, the divergence of gradient w.r.t. time), which usually indicates the
magnitude of action w.r.t. the direction of a gradient.

The shortest answer on the laplacian [[https://physics.stackexchange.com/a/31524][here on s/o]] is the best:

#+begin_quote
A practical application of the Laplacian can be found in the [[http://www.chemistry.mcmaster.ca/aim/aim_5.html][Atoms in Molecules]]
analysis of the electron density. The electron density of a molecule is a scalar
field, and its Laplacian sort of gives the regions where the electrons are
+locally concentrated or depleted+ /locally concentrating or depleting/ (the
density itself usually has no minima, and maxima only at the nuclei).
#+end_quote

It's how I think of it, since my first introduction to Laplacian was when I
decided to "study" plasma physics and fusion by watching lectures ... that was
also my first introduction to vector calculus. There, the electrons have less
momentum, but equivalent charge to protons. On a small timescale, the Lapacian
there describes the direction/magnitude of changes in force. Because of the
relative masses of electrons/protons, a lot of dissonance in their distribution
occurs, resulting in strong transient accumulation of EM force. The mass
difference "imprints" itself into the time domain, resulting in waves and
dynamics -- by imprint, i mean something similar to how the component values in
a differentiating/integrating opamp circuit rely on the temporal difference in
response to "accumulate" voltage as "value" on the capacitor. A capacitor's
frequency response results from a similar dissonance that bleeds over into the
time-domain (it's hard to explain.)

I'm glad mathjax is fairly portable with $\LaTeX$. Nice to know. It must be why
they call it "Math Jack".

* Roam
+ [[id:beafc05d-75b4-4013-8b43-9c0483a30328][Art]]
