:PROPERTIES:
:ID:       324bd5d7-c7e1-4626-bb81-4a3935376543
:END:
#+TITLE: Extract Duolingo Transcriptions With JQuery... Yes, JQuery

From [[https://podcast.duolingo.com/episode-98-the-secret-life-of-josephine-baker-josephine-la-cible][Duolingo French Podcast, Episode 98: The Secret Life of Josephine Baker]]

Reading through this before listening to the episode should help a bit. It's also easily printed for formatting, though the tables may be a bit of a problem.

* Roam

+ Language

* Duolingo

Remove Ariana's lines from =.entry-content=.

#+begin_src javascript
$('p:has(strong:contains("Ariana:"))').map(function (i,el) {
    el.innerHTML = el.firstChild.outerHTML;
    el.setAttribute("style","color:#DDDDDD");
    return el});
#+end_src

Then, replace the =body= with Josephine's lines... There are cleaner ways to do
this using =filter= (or ideally =reduce= but we don't have that here). I would
imagine that the Javascript DOM API obviates the need for jquery, but it's at
least nearly ubiquitous with the exception of AngularJS.

#+begin_src javascript
$('.entry-content p').replaceAll('body');
#+end_src

** Results

With the =ob-translate= package, i can chunk up this plain text and translate to
many languages in-line. After running =regexp-replace= to remove Ariana's lines
and to convert Josephine's lines into babel blocks, i can translate it into
multiple langauges simultaneously.

#+begin_src translate :src fr :dest ht,ja
Josephine: Pour la première fois de ma carrière en Europe, je sentais une haine dirigée contre moi. Contre moi, Josephine Baker ! Je connaissais cette sensation : j’avais connu ce genre de racisme. Mais là, il y avait quelque chose de plus. Ils n'aimaient pas ma danse, mon art, ma liberté d'être moi-même ! C’était un grand choc pour moi. Ce voyage était un désastre.
#+end_src

#+RESULTS:
| ht | Josephine: Pou premye fwa nan karyè mwen an Ewòp, mwen te santi rayisman dirije kont mwen. Kont mwen, Josephine Baker! Mwen te konnen santiman sa a: mwen te fè eksperyans kalite rasis sa a. Men, te gen yon bagay plis la. Yo pa t renmen danse mwen, atizay mwen, libète mwen pou mwen menm! Se te yon gwo chòk pou mwen. Vwayaj sa a te yon dezas. |
| ja | ジョゼフィーヌ: ヨーロッパでのキャリアで初めて、私に対して憎しみが向けられていると感じました。対するはジョセフィン・ベイカー！私はこの気持ちを知っていました。私はこの種の人種差別を経験したことがあります。しかし、そこにはさらに何かがありました。彼らは私のダンス、芸術、私らしくある自由が気に入らなかったのです。それは私にとって大きなショックでした。この旅行は大惨事でした。                       |

#+begin_src translate :src fr :dest ht,ja
Josephine: La police de Munich avait décidé d’interdire mon spectacle. Je ne pouvais pas le croire. Selon eux, mon spectacle pouvait mettre en danger la morale publique et causer des problèmes. Alors, je n’avais plus le droit de monter sur scène. On m’enlevait le droit de danser, de chanter, de m’exprimer ! Comme si une simple danse pouvait représenter un danger ! J’étais tellement en colère. Mes amis m’avaient dit de ne pas venir en Allemagne. Et maintenant, je réalisais que tout ce qu'ils m’avaient dit était vrai.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: J'avais des fans dans toute l'Europe. Alors s'ils ne voulaient pas de moi en Allemagne, c’était leur problème. Je savais que la France m'attendait. Paris m’attendait. Les théâtres et mes fans m’attendaient. Personne n'allait m'empêcher de faire ce que j'aimais : danser, chanter, apporter de la joie. On n'arrête pas si facilement Josephine Baker !
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Le château des Milandes, c’est un endroit magnifique. C’est un château de la Renaissance, entouré par un jardin à la française. À travers ses grandes fenêtres, on peut admirer la vallée de la Dordogne, avec son fleuve et ses collines vertes. Dès que j’arrive là-bas, j’ai un sentiment de paix intérieure et de beauté. Quand je suis entourée par la nature, je me sens bien. C’est l’endroit parfait pour venir me reposer entre deux spectacles, et pour inviter tous mes amis.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Dès que je voyais mes animaux, je me sentais bien, et en paix ! Ce sont les meilleurs compagnons. Dernièrement, à cause du fascisme, les nouvelles étaient très inquiétantes. J’étais triste, et en colère. Mais en voyant mes animaux, j’ai décidé que je n’allais pas déprimer. La vie continuait, et j’allais sourire à la vie ! Il était temps d’organiser une petite fête aux Milandes.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Mon cuisinier avait préparé un repas magnifique, et la table était très élégante, avec des assiettes en porcelaine, des verres en cristal et de belles bougies. Je voulais que mes invités se détendent et s’amusent, qu’ils oublient tous les problèmes. Tout ce que je voulais, c’était qu’on soit ensemble ! Pendant cette période difficile, je voulais apporter un peu de bonheur et de joie à mes amis.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Male guest: Il paraît qu’Hitler veut envahir d’autres pays comme l’Autriche et la Pologne.

Female guest: Vous pensez qu’il s’arrêtera là ? Moi, je ne crois pas… Cet homme est un fou et un tyran. Il veut que toutes les personnes qui ne sont pas de « race pure », comme il dit, disparaissent…

Male guest: Et dire que certains Français sont d’accord avec lui… Quelle horreur !
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Le spectacle allait être très glamour et sophistiqué. Je porterais une longue robe très chic, et je serais entourée par mes danseurs et mes danseuses. C’était quelque chose de très spécial de revenir aux Folies Bergère pour diriger mon propre spectacle. La ceinture de bananes m’avait rendue célèbre, mais maintenant, j’étais connue pour bien plus que ça.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Quel bonheur de retrouver mes fans français ! J’ai toujours dit que les gens avaient besoin de musique, de danse et de rire dans la vie, même dans les moments difficiles. Plus que jamais, j’étais décidée à offrir ce cadeau à mon public.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Tout va bien, Fred ?

Fred: Josephine, je dois te montrer quelque chose. J’ai beaucoup hésité à t’en parler, mais je crois que c’est important que tu sois au courant…

Josephine: Qu’est-ce qu’il y a, Fred ? Je préfère tout savoir, même si c’est une mauvaise nouvelle. Dis-moi ce qui se passe, s’il te plaît… Je peux tout entendre.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: La brochure était écrite en allemand, donc je ne comprenais rien. Tout ce que je voyais, c'était un dessin de mon visage au milieu. Et il y avait d’autres dessins d’artistes noirs ou juifs. Je sentais que c’était inquiétant…
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Range ça, Fred ! Le racisme, je connais, merci. Je ne veux rien savoir de cette propagande pleine de haine.

Fred: Mais Jo, écoute-moi ! Cet homme attaque tous les artistes qu’il appelle « dégénérés ». Et il mentionne ton nom directement. Je suis très inquiet, Jo. Je sais que tu as vécu des choses difficiles à Munich. Mais là, c’est différent. Tu as une cible dans le dos.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Je me demandais pourquoi mon existence dérangeait autant cet homme. Tout ce que je voulais, c’était apporter de la joie aux gens avec mon art. Moi, mes danses et mes chansons, nous lui faisions si peur que ça ? En quoi était-ce dangereux ? Être une artiste, une artiste noire, ce n’est pas un crime !
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Mon rêve, c’était que les personnes de toutes les origines et de toutes les religions vivent en harmonie, avec leurs différences. Je voulais que les femmes soient libres de réaliser leurs rêves de carrière, et qu’on soit tous libres d’aimer qui on veut. Mais toutes ces idées étaient interdites par le Nazisme. Pour les Nazis, mon existence même était un crime. Et je n’étais pas la seule : des millions de personnes étaient en danger.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Un sentiment a commencé à grandir à l’intérieur de moi : le désir de me battre contre cette haine, de dire non, de résister.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: J’ai réalisé que depuis toujours, être sur scène, ça avait été ma façon de donner de l’amour, et de la joie. Ça avait été le combat de ma vie. Parce que la joie, c’est une forme de résistance. Personne ne pouvait nous enlever notre joie, et surtout pas les Nazis. Je n’allais pas leur faire ce cadeau. Alors j’allais continuer ce que j’avais toujours fait, et ce que je faisais le mieux : être une artiste.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Voir la France, mon pays d’adoption, se préparer à la guerre, ça me rendait tellement triste. J’avais peur de ce que ça voulait dire. J’ai pensé à tous ces soldats français qui étaient partis sur la ligne Maginot. Ils allaient peut-être risquer leur vie pour notre liberté. Ils allaient peut-être mourir. En les voyant se préparer au combat, j’ai pris une décision : j’irais chanter pour eux. Les Allemands ne voulaient pas que je chante, alors je chanterais à la frontière ! J’allais faire un spectacle sur la ligne Maginot pour apporter un peu de joie à ces soldats.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Des spectacles, j’en avais fait des centaines. Mais celui-là était différent. La France vivait une période très difficile de son histoire. Ce spectacle était né dans la guerre, et pourtant, il était plein de joie et d’espoir. Dans le public, j’ai vu tous ces hommes en uniforme, parfois très jeunes, me regarder avec des étoiles dans les yeux. C’est là que j’ai compris combien ce que je faisais était important. J’avais une grande responsabilité.

Josephine: Messieurs ! À vous qui vous battez pour la France, je veux vous chanter… Le Temps des cerises.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Pendant un court instant, je les ai vus sourire. Il y avait de la joie sur leurs visages. Malgré la peur, malgré le doute, malgré la douleur, il y avait de la joie. Ce jour-là, j’ai chanté pour donner du courage aux soldats, mais aussi pour me donner du courage à moi-même. Je me sentais prête à me battre pour ce pays qui était le mien.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Je voulais faire plus, quelque chose de radical et de courageux. Mais qu’est-ce que je pouvais faire ? Chanter pour les soldats, c’était bien, mais ce n’était pas suffisant. En tant qu’artiste, je me sentais inutile dans cette guerre. Comment pouvais-je combattre le Nazisme et protéger mon pays d'adoption ?
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: Euh… Bonjour Monsieur…

Jacques Abtey: Bonjour, Madame Baker. Je m’appelle Monsieur Fox.
#+end_src

#+begin_src translate :src fr :dest ht,ja
Josephine: « Monsieur Fox »… C’était un nom bien mystérieux. Qui était cet homme ? Était-il venu pour me faire du mal ? Est-ce que j’étais en danger ? Ce qui était sûr, c’est que cette rencontre allait tout changer.
#+end_src
