:PROPERTIES:
:ID:       899a7d23-4321-436e-b6dc-978241ce94f5
:END:
#+TITLE:     Org: Using =org-attach= in Ectorepo
#+AUTHOR:    David Conner
#+EMAIL:     aionfork@gmail.com
#+DESCRIPTION: notes

* Reorganization for org-attach

TODO: instead of =org-attach=, set =headerargs:dir:= in =:PROPERTIES:= or as variable

#+begin_quote
NOTE: I've recently rediscovered =org-attach=. TL;DR; Usage of =org-attach= will
completely change how I take notes for the projects described by XML or adhoc
checkouts:
#+end_quote

The eminently preeminent re-org-anization:

I had always intended for a future reorganization -- this is why I always
accompanied the generation of XML with some =org-mode= content or =org-babel=
script to regenerate.

** Problems

*** Ad hoc pseudo-config

When running commands to analyze groups of repositories, this results in
hard-to-grok "pseudo-config" in org-babel (like
[[https://github.com/ectorepo/ectorepo/blob/master/typescript/astro-repo/README.org?plain=1][./typescript/astro-repo/README.org]]). The ==

_Pseudo-config_: Not simply config, but should be.  It should simply describe
how it configures the rest of a file's =org-babel= procedures, but requires some
extra handling or evaluation.

This usually requires =(setq-local ...)=, order-specific evaluation and maybe
too many assumptions about emacs/org knowledge & config.

+ I do intend to mask some parts of the procedure (like how to get an API token
  into the buffer's emacs-lisp evaluation)
+ I try to avoid =cd= or directories specified by =env= vars, which are
  *usually* but not always shared across the Emacs server's processes.
+ I don't want absolute path references to my filesystem in notes
+ Relative path references based on 2 or 3 absolute path references are equally
  problematic.

I've gone through 3 or 4 cycles of grokking the =org-mode= structure. I believe
I had noticed this =org-attach= but the default options of =ID= and =DIR= just
didn't quite work for me. Since =org-attach= requires a lot of foresight and
since any reorganization is a huge time investment, I evaluated it only once and
forgot.

Ideally, the majority of my notes will exist under a single umbrella, except
when necessary as documentation explicitly intended for consumers of a single
repository (or a project's repository ecosystem).

There are a few examples a basis for notes on repositories

- multi-project repo XML for framework (e.g. ./typescript/astro)
- multi-project repo XML for language:
  - well-organized semi-manual
    - using sensible strings from package manager, e.g. ./rustetc/
  - well-organized manual (using)
  - well-organized graphql
  - semi-flat, manuaol
    1) XML derived from scraping (e.g. [[https://github.com/ectorepo/ectorepo/blob/master/hashicorp/gcp_blueprints.xml][./hashicorp/gcp]])
    2) manually assembled
  - mostly flat:
  - multi-topic

will make it simple for me & others to quickly jump to the source file, project,
maybe git-ref
