:PROPERTIES:
:ID:       66a69017-cbd5-4dc5-bd01-8c60065708b2
:END:
#+TITLE: TimelineJS: Create a simple timeline
#+CATEGORY: slips
#+TAGS:  
* Roam

* Docs

* Resources
** App Scripts
+ [[https://developers.google.com/apps-script/guides/sheets/functions#using_a_custom_function][Using a custom function in scripts]]
+ [[https://workspace.google.com/marketplace/app/hash_calculator/250473016562?flow_type=2][Hash Calculator]]

* Notes
Why?

I'm tired of this "psychotherapy-mulligan" my family keeps pulling. Introducing
myself is extremely stressful when I don't know what I'm walking in to. I do _NOT_
want to be forcibly medicated on drugs which are known to destroy the cognition
of people who do not need to be on them. They are lying, ignorant and abusive
and shopping around for therapists who will be their "nurse ratchet on a stick"

* Issues

** App SCripts
*** TimelineJS Evaluation Context and App Scripts

These are a bit wonky. The Knights Lab host doesn't always have access to the
context which would otherwise load your spreadsheet's app scripts. I also didn't
want to install a Google Workspace extension to calculate a hash.

*** Testing and Debugging

+ The "Apps Script" functionality is actually not that bad
  - In order to run/debug a function, you must create a new function with no
    arguments (or change the function to set default values). The former is what
    you should do.
  - Other than that, debugging & running works as expected, except you cannot
    get insight into lower-level functionality
