:PROPERTIES:
:ID:       36f12cfc-408b-4c63-90a5-b443838367b4
:END:
#+TITLE: Python: Mise, UV, Jupyter and Kernels
#+CATEGORY: slips
#+TAGS:
* Roam
+ [[id:2049060e-6755-4a64-b295-F7B563B41505][NixOS]]
+ [[id:b4c096ee-6e40-4f34-85a1-7fc901e819f5][Python]]
+ [[id:cf847bc5-31f7-4bb8-8324-7680a8f2953d][Shell]]

* Resources

** Cookiecutter
+ [[https://github.com/fpgmaas/cookiecutter-uv][fpgmaas/cookiecutter-uv]]
+ [[https://cookiecutter.readthedocs.io/en/stable/][cookiecutter docs]]

** Jupyter
*** [[https://marimo.io/][Marimo]]: "The future of python"

... oh that's cute. it's a _literal pluto clone_. Thanks, but i'll pass. Julia had
macros. ytf do idiots run the world?

Pluto's HTML5 elements weren't super fantastic anyways. They were great... but
very, very "scrolly" if you know what i mean. Can we just all agree that DatGUI
is the One True GUI GOAT?

And Marimo's shortcuts, lack of editor functionality? I guess I don't know that
for real. Just from an instantaneous prompt to the "programmer LLM" in my brain.
Domain problems. Can't simplify that. AVOID THE DOMAIN.

** NixOS
*** Jupyter Envs

+ [[https://www.reddit.com/r/NixOS/comments/1ojtcmm/comment/nmeex42/?context=3][r/NixOS: Python uv + Nix-ld: "RuntimeError: Found no NVIDIA driver on your system"]]
  - [[https://github.com/Naxdy/nix-flake-templates/blob/main/python-nn/flake.nix][uv2nix: 250 line template for flake.nix]] yo dawg, i heard you like pins

user wants to run [[github.com/comfyanonymous/ComfyUI][ComfyUI]], but restoring configuration across install states for
applications that have graph-based configureation is at least as hard as
programming it (hardness as in spatial computation)

anyways, i like dragging connections between nodes in my wireplumber audio graph
(i don't though). nlg OP sounds smart though. but data science really comes down
to who can afford a ferrari. it's not really a test of it's not exactly a battle
of wits. i'm honestly pretty happy to have not spent a ton of effort learning
these tools. i can't say i'm regret-free for not using it at all though.

*** tweag/jupyenv

Examples in [[https://github.com/tweag/jupyenv/tree/main/examples][examples/$lang]]

+ [[https://github.com/tweag/jupyenv/blob/main/modules/default.nix#L15-L60][Options for =jupyterlab= modules/default.nix]]
+ [[https://github.com/tweag/jupyenv/blob/main/modules/kernel.nix#L12-L84][Options for =kernel.*= and =kernel.python= modules/kernel.nix]]
+ [[https://github.com/tweag/jupyenv/blob/main/modules/kernels/haskell/default.nix#L63-L100][Options for =kernel.haskell= modules/kernels/haskell/default.nix]]
+ [[https://github.com/tweag/jupyenv/blob/main/modules/kernels/julia/default.nix#L73-L104][Options for =kernel.julia= modules/kernels/julia/default.nix]]
  
| bash       | minimal |         |         |        |
| c          | minimal |         |         |        |
| dotnet     | csharp  | fsharp} |         |        |
| elm        | minimal |         |         |        |
| go         | minimal |         |         |        |
| haskell    | minimal |         |         |        |
| javascript | minimal |         |         |        |
| julia      | minimal |         |         |        |
| nix        | minimal |         |         |        |
| ocaml      | minimal |         |         |        |
| postgres   | minimal |         |         |        |
| python     | minimal | native  | science | stable |
| r          | minimal |         |         |        |
| rust       | minimal |         |         |        |
| scala      | minimal |         |         |        |
| typescript | minimal |         |         |        |
| zsh        | minimal |         |         |        |

* Notes
** Setup
*** Omarchy

*** Nixos


* Projects

** 

#+begin_src shell
# TODO: set :dir and make org-babel callable?
uv init my-uv-project
cd my-uv-project
uv add --dev ipykernel


#+end_src


** Layout

#+begin_example
/data/lang/python/kernels
/data/lang/python/kernels/k1/.venv
/data/lang/python/kernels/k1/pyproject.toml
/data/lang/python/kernels/k1/mise.toml
/data/lang/python/kernels/k2/.venv
/data/lang/python/kernels/k2/pyproject.toml
/data/lang/python/kernels/k2/mise.toml
/data/lang/python/projects
/data/lang/python/projects/p1/.venv
/data/lang/python/projects/p1/pyproject.toml
/data/lang/python/projects/p1/mise.toml
/data/lang/python/projects/p2/.venv
/data/lang/python/projects/p2/pyproject.toml
/data/lang/python/projects/p2/mise.toml
/data/lang/python/projects/tries
/home/dc/.jupyter/lab/user-settings
/home/dc/.jupyter/lab/workspaces
/home/dc/.local/share/jupyter/kernels
#+end_example


#+begin_example
.
├── data
│   └── lang
│       └── python
│           ├── kernels
│           │   ├── k1
│           │   │   ├── mise.toml
│           │   │   ├── pyproject.toml
│           │   │   └── .venv
│           │   └── k2
│           │       ├── mise.toml
│           │       ├── pyproject.toml
│           │       └── .venv
│           └── projects
│               ├── p1
│               │   ├── mise.toml
│               │   ├── pyproject.toml
│               │   └── .venv
│               ├── p2
│               │   ├── mise.toml
│               │   ├── pyproject.toml
│               │   └── .venv
│               └── tries
└── home
    └── dc
        ├── .jupyter
        │   └── lab
        │       ├── user-settings
        │       └── workspaces
        └── .local
            └── share
                └── jupyter
                    └── kernels
#+end_example

* Jupyenv

** Quick Start

#+begin_src shell
d=$(mktemp -d)
nix flake init --template github:tweag/jupyenv
#+end_src

This generates the following flake

#+begin_src nix
{
  description = "Your jupyenv project";

  nixConfig.extra-substituters = [
    "https://tweag-jupyter.cachix.org"
  ];
  nixConfig.extra-trusted-public-keys = [
    "tweag-jupyter.cachix.org-1:UtNH4Zs6hVUFpFBTLaA4ejYavPo5EFFqgd7G7FxGW9g="
  ];

  inputs.flake-compat.url = "github:edolstra/flake-compat";
  inputs.flake-compat.flake = false;
  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  inputs.jupyenv.url = "github:tweag/jupyenv";

  outputs = {
    self,
    flake-compat,
    flake-utils,
    nixpkgs,
    jupyenv,
    ...
  } @ inputs:
    flake-utils.lib.eachSystem
    [
      flake-utils.lib.system.x86_64-linux
    ]
    (
      system: let
        inherit (jupyenv.lib.${system}) mkJupyterlabNew;
        jupyterlab = mkJupyterlabNew ({...}: {
          nixpkgs = inputs.nixpkgs;
          imports = [(import ./kernels.nix)];
        });
      in rec {
        packages = {inherit jupyterlab;};
        packages.default = jupyterlab;
        apps.default.program = "${jupyterlab}/bin/jupyter-lab";
        apps.default.type = "app";
      }
    );
}
#+end_src

Then edit =kernels.nix=, so

#+begin_src nix
{ pkgs, ... }:
{
  kernel.python.basic = {
    enable = true;
    runtimePackages = [
      pkgs.coreutils
    ];
    env = pkgs.python3.withPackages (
      ps: with ps; [
        ps.ipykernel
        ps.numpy
        ps.scipy
        ps.matplotlib
      ]
    );
  };
}
#+end_src

It looks like it works for simple things. For more advanced scenarios, it would
require a lot of overrides. The =pyproject= kernel works for more native deps, I think

But for now, I'm getting this error, which has been unaddressed for a while,
probably bc it's more difficult than it looks ... which is sad.

#+begin_example
… while calling the 'throw' builtin
  at /nix/store/lv4kcr2y4b9k4ynhkga157507zxf372b-source/pkgs/development/compilers/rust/make-rust-platform.nix:84:23:
    83|   # Added in 25.05.
    84|   fetchCargoTarball = throw "`rustPlatform.fetchCargoTarball` has been removed in 25.05, use `rustPlatform.fetchCargoVendor` instead";
      |                       ^
    85| }
    
error `rustPlatform.fetchCargoTarball` has been removed in 25.05, use `rustPlatform.fetchCargoVendor` instead
#+end_example

** Advanced

*** AMD
