:PROPERTIES:
:ID:       906f0085-c2ca-4037-a096-fc2a164fcf27
:END:
#+TITLE: Arch: Omarchy Bin Scripts
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:fbf366f2-5c17-482b-ac7d-6dd130aa4d05][Arch]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]
+ [[id:77df4a7f-ce6a-4b0a-a4cf-453d9da625c5][Build]]
+ [[id:2049060e-6755-4a64-b295-F7B563B41505][NixOS]]
+ [[id:b3f26f1f-1527-4707-9e5f-baac3ac7b865][NixOS: mixing packages and profiles with home-manager]]

* Resources

This is basically the same approach as described in this article: [[https://zaynetro.com/post/2024-you-dont-need-home-manager-nix][You may not
need a Home Manager]]

** Dotfiles
+ [[https://github.com/dcunited001/ellipsis/blob/master/nixos/pkgs/common/omarchy-scripts/package.nix#L16][nixos/pkgs/common/omarchy-scripts/package.nix#L16]]
+ a commit with the changes: [[https://github.com/dcunited001/ellipsis/commit/5dd114142480dba95e1c5173f686dcbe0129f376][dcunited001/ellipsis]]

** Nix
+ android-udev-rules: [[https://github.com/NixOS/nixpkgs/blob/3a4e23f7835a8f561b4c83686a8069ecfa9707eb/pkgs/by-name/an/android-udev-rules/package.nix#L18][pkgs/by-name/an/android-udev-rules/package.nix#L18]]
  - A package guaranteed to install one static file & one static file only

* Nix Pkg

nixos/pkgs/common/omarchy-scripts/package.nix:

#+begin_src nix
{ stdenv, lib, fetchFromGitHub }:

stdenv.mkDerivation rec {
  name = "omarchy-scripts-${version}";
  srcVersion = "3.0.2";
  version = "3.0.2-revision0"; # increment revision number when package changes

  src = fetchFromGitHub {
    owner = "basecamp";
    repo = "omarchy";
    rev = "v${srcVersion}";
    sha256 = "sha256-1QJBoMe6MzaD/dcOcqC8QpRxG0Z2c1p+WYqtNFlsTOA=";
  };

  # from android-udev-rules
  installPhase = ''
    runHook preInstall
    install -D bin/omarchy-cmd-terminal-cwd $out/bin/omarchy-cmd-terminal-cwd
    runHook postInstall
  '';

  doInstallCheck = true;

  meta = {
    description =
      "A collection of scripts from DHH's opinionated arch/hyprland setup.";
    homepage = "https://github.com/basecamp/omarchy";

    license = lib.licenses.mit;
    platforms = lib.platforms.linux;
  };
}
#+end_src


** Fairly simple

Diff to integrate

#+begin_example diff
diff --git a/nixos/modules/users/dc.nix b/nixos/modules/users/dc.nix
index 51242a9..2d7f879 100644
--- a/nixos/modules/users/dc.nix
+++ b/nixos/modules/users/dc.nix
@@ -2,6 +2,8 @@
 let
   hyprdc = (pkgs.callPackage
     (lib.custom.relativeToRoot "pkgs/common/hyprdc/package.nix") { });
+  omarchy-scripts = (pkgs.callPackage
+    (lib.custom.relativeToRoot "pkgs/common/omarchy-scripts/package.nix") { });
 in {

   users.groups = {
@@ -46,6 +48,7 @@ in {
     packages = with pkgs; [
       # CUSTOM
       hyprdc
+      omarchy-scripts

       # CLI
       tree
diff --git a/nixos/pkgs/common/omarchy-scripts/package.nix b/nixos/pkgs/common/omarchy-scripts/package.nix
new file mode 100644
index 0000000..e94ee8e
--- /dev/null
+++ b/nixos/pkgs/common/omarchy-scripts/package.nix
@@ -0,0 +1,32 @@
+{ stdenv, lib, fetchFromGitHub }:
+
+stdenv.mkDerivation rec {
+  name = "omarchy-scripts-${version}";
+  srcVersion = "3.0.2";
+  version = "3.0.2-revision0"; # increment revision number when package changes
+
+  src = fetchFromGitHub {
+    owner = "basecamp";
+    repo = "omarchy";
+    rev = "v${srcVersion}";
+    sha256 = "sha256-1QJBoMe6MzaD/dcOcqC8QpRxG0Z2c1p+WYqtNFlsTOA=";
+  };
+
+  # from android-udev-rules
+  installPhase = ''
+    runHook preInstall
+    install -D bin/omarchy-cmd-terminal-cwd $out/bin/omarchy-cmd-terminal-cwd
+    runHook postInstall
+  '';
+
+  doInstallCheck = true;
+
+  meta = {
+    description =
+      "A collection of scripts from DHH's opinionated arch/hyprland setup.";
+    homepage = "https://github.com/basecamp/omarchy";
+
+    license = lib.licenses.mit;
+    platforms = lib.platforms.linux;
+  };
+}
#+end_example

* Notes
** Integrating
Fairly simple. Most users don't take this approach to building content with nix
derivations, but it's very simple.

+ Depending on the runtime dependencies of this script (and whether it changes
  upstream), you can integrate some static files.

+ Obviously, doing too much of this would be taxing, esp. if you don't plan for
  upstream changes or analyze script dependencies.

*** Nix Profile Path

#+begin_quote
NOTE: this depends on:

+ whether you use =home-manager=
+ whether it's standalone
+ how you set up the =.nix-profile= integration for it
#+end_quote

If you add this =omarchy-scripts= to =users.users.myuser.packages=, it ends up in
the =PATH=. For some types of files, you may need to ensure other search path
variables are updated. Some of these may require relogin, if it affects the
content of =PATH=. If your path includes a symlink to =~/.nix-profile=, it doesn't.

#+begin_quote
NOTE: I'm just manually managing the =~/.nix-profile= link with the command below.
I'm not using =nix-env= or =nix profile=.

=ln -fs /etc/profiles/per-user/dc ~/.nix-profile=

Trying to do this with a store derivation for a single system would usually
involve impure =/nix/store= derivations. Other approaches:

1) use symlinkJoin (somehow via hjem), but this would be wierd or
2) a pkgs.runCommand that forces a store item to link out of store and is then
   linked by hjem (not great)
3) something with home-manager. I may try this next, since I could use via
   standalone on omarchy elsewhere. But i'm not using it at the moment.
#+end_quote

Other changes may require restarting.

+ The WM if its PATH doesn't include whatever
+ Or the dbus session, if you've added new dbus specifications without a
  mechanism to have that process learn about them (I don't recall needed to
  worry about this)
+ ... or systemd: usually the need to "reactivate" systemd seems to be
  detected by nixos-rebuild. Sometimes it won't, like if the systemd path
  includes packages not in the =systemd-path systemd-search-user-unit= by
  symlink

It's possible that this would work with just a standalone =.nix-profile= setup on
a foreign distribution.

+ It depends on whether your =.nix-profile= already exports
  variables for a specific type of search path before adding something that does
  require it.
+ There are some package definitions which don't indicate that to the
  derivation (e.g. they don't result in exporting =GUILE_LOAD_PATH= or
  =QT_PLUGIN_PATH= or whatever)
+ So if that profile doesn't have a need to prepend to =XDG_DATA_DIRS=, it won't
  - if it needs to modify =systemd-search-user-unit=, then you may need to relogin
    for =daemon-reload= to include things

** Maintaining
:PROPERTIES:
:header-args+: :var chkout=(expand-file-name "omarchy" (or (bound-and-true-p ob@arch_omarchy_bin_scripts) (setq ob@arch_omarchy_bin_scripts (make-temp-file "roam-" t))))
:header-args+: :dir (identity ob@arch_omarchy_bin_scripts)
:END:

Basically, which content do you choose to import?

*** Script dependencies

Most scripts seem to be listed by =omarchy-menu= so I've filtered all edges or
nodes that contain =omarchy-menu=.

#+begin_src dot :file img/omarchy-scripts.svg :cmdline "-Tsvg -Kdot" :dir (f-dirname (buffer-file-name (current-buffer))) :noweb yes
digraph G {
    graph[rankdir="LR"]
    <<omarchyScriptsEdges()>>
}
#+end_src

#+RESULTS:

All scripts that don't run =omarchy-*= scripts

| omarchy-battery-monitor    | omarchy-cmd-apple-display-brightness | omarchy-cmd-audio-switch                | omarchy-cmd-close-all-windows | omarchy-cmd-first-run     | omarchy-cmd-missing        |
| omarchy-cmd-missing        | omarchy-cmd-screenrecord             | omarchy-cmd-screenshot                  | omarchy-cmd-terminal-cwd      | omarchy-dev-add-migration | omarchy-font-current       |
| omarchy-font-current       | omarchy-font-list                    | omarchy-install-chromium-google-account | omarchy-install-docker-dbs    | omarchy-install-steam     | omarchy-launch-about       |
| omarchy-launch-about       | omarchy-launch-browser               | omarchy-launch-editor                   | omarchy-launch-wifi           | omarchy-lock-screen       | omarchy-menu-keybindings   |
| omarchy-menu-keybindings   | omarchy-pkg-drop                     | omarchy-pkg-missing                     | omarchy-pkg-pinned            | omarchy-pkg-present       | omarchy-powerprofiles-list |
| omarchy-powerprofiles-list | omarchy-refresh-applications         | omarchy-refresh-pacman-mirrorlist       | omarchy-refresh-plymouth      | omarchy-reset-sudo        | omarchy-restart-bluetooth  |
| omarchy-restart-bluetooth  | omarchy-restart-pipewire             | omarchy-restart-wifi                    | omarchy-setup-dns             | omarchy-setup-fido2       | omarchy-setup-fingerprint  |
| omarchy-setup-fingerprint  | omarchy-show-logo                    | omarchy-theme-current                   | omarchy-theme-list            | omarchy-theme-update      | omarchy-toggle-idle        |
| omarchy-toggle-idle        | omarchy-toggle-screensaver           | omarchy-toggle-waybar                   | omarchy-tui-remove            | omarchy-update-available  | omarchy-version-branch     |
| omarchy-version-branch     |                                      |                                         |                               |                           |                            |

Tree of non-communicating nodes

#+begin_src shell :results output verbatim :var edges=omarchyScriptsEdges
comm -1 -3 <(echo $edges \
    | sed -E 's/" -> "/"\n"/g' | sed -E 's/" "/"\n"/g' \
    | sort | uniq) \
    <(ls omarchy/bin | sort \
    | sed -E 's/^(.*)/"\1"/g' \
    | sort | uniq | grep -v '"omarchy-menu"') \
    | tr -d '"' | tr '-' '/' | tree --fromfile .
#+end_src

#+RESULTS:
#+begin_example
.
└── omarchy
    ├── cmd
    │   ├── apple
    │   │   └── display
    │   │       └── brightness
    │   ├── audio
    │   │   └── switch
    │   ├── first
    │   │   └── run
    │   ├── screenrecord
    │   ├── screenshot
    │   └── terminal
    │       └── cwd
    ├── dev
    │   └── add
    │       └── migration
    ├── font
    │   ├── current
    │   └── list
    ├── hyprland
    │   └── workspace
    │       └── toggle
    │           └── gaps
    ├── install
    │   ├── chromium
    │   │   └── google
    │   │       └── account
    │   ├── docker
    │   │   └── dbs
    │   ├── steam
    │   └── xbox
    │       └── controllers
    ├── launch
    │   ├── browser
    │   └── walker
    ├── lock
    │   └── screen
    ├── menu
    │   └── keybindings
    ├── pkg
    │   ├── drop
    │   ├── pinned
    │   └── present
    ├── powerprofiles
    │   └── list
    ├── refresh
    │   └── applications
    ├── reset
    │   └── sudo
    ├── restart
    │   ├── bluetooth
    │   ├── pipewire
    │   └── wifi
    ├── setup
    │   ├── dns
    │   ├── fido2
    │   └── fingerprint
    ├── show
    │   └── logo
    ├── theme
    │   ├── current
    │   ├── list
    │   └── update
    ├── toggle
    │   ├── idle
    │   ├── screensaver
    │   └── waybar
    ├── tui
    │   └── remove
    ├── update
    │   └── available
    └── version
        ├── branch
        ├── channel
        └── pkgs

34 directories, 42 files
#+end_example

*** Nodes

#+name: omarchyScriptsNodes
#+begin_src shell :results output verbatim
ls omarchy/bin | sort \
    | sed -E 's/^(.*)/"\1"/g' \
    | sort | uniq | grep -v '"omarchy-menu"'
#+end_src

#+RESULTS: omarchyScriptsNodes
#+begin_example
"omarchy-battery-monitor"
"omarchy-battery-remaining"
"omarchy-branch-set"
"omarchy-channel-set"
"omarchy-cmd-apple-display-brightness"
"omarchy-cmd-audio-switch"
"omarchy-cmd-first-run"
"omarchy-cmd-missing"
"omarchy-cmd-present"
"omarchy-cmd-reboot"
"omarchy-cmd-screenrecord"
"omarchy-cmd-screensaver"
"omarchy-cmd-screenshot"
"omarchy-cmd-share"
"omarchy-cmd-shutdown"
"omarchy-cmd-terminal-cwd"
"omarchy-debug"
"omarchy-dev-add-migration"
"omarchy-drive-info"
"omarchy-drive-select"
"omarchy-drive-set-password"
"omarchy-font-current"
"omarchy-font-list"
"omarchy-font-set"
"omarchy-hook"
"omarchy-hyprland-window-close-all"
"omarchy-hyprland-window-pop"
"omarchy-hyprland-workspace-toggle-gaps"
"omarchy-install-chromium-google-account"
"omarchy-install-dev-env"
"omarchy-install-docker-dbs"
"omarchy-install-dropbox"
"omarchy-install-steam"
"omarchy-install-tailscale"
"omarchy-install-terminal"
"omarchy-install-vscode"
"omarchy-install-xbox-controllers"
"omarchy-launch-about"
"omarchy-launch-bluetooth"
"omarchy-launch-browser"
"omarchy-launch-editor"
"omarchy-launch-floating-terminal-with-presentation"
"omarchy-launch-or-focus"
"omarchy-launch-or-focus-tui"
"omarchy-launch-or-focus-webapp"
"omarchy-launch-screensaver"
"omarchy-launch-tui"
"omarchy-launch-walker"
"omarchy-launch-webapp"
"omarchy-launch-wifi"
"omarchy-lock-screen"
"omarchy-menu-keybindings"
"omarchy-migrate"
"omarchy-notification-dismiss"
"omarchy-pkg-add"
"omarchy-pkg-aur-accessible"
"omarchy-pkg-aur-install"
"omarchy-pkg-drop"
"omarchy-pkg-install"
"omarchy-pkg-missing"
"omarchy-pkg-pinned"
"omarchy-pkg-present"
"omarchy-pkg-remove"
"omarchy-powerprofiles-list"
"omarchy-refresh-applications"
"omarchy-refresh-config"
"omarchy-refresh-fastfetch"
"omarchy-refresh-hypridle"
"omarchy-refresh-hyprland"
"omarchy-refresh-hyprlock"
"omarchy-refresh-hyprsunset"
"omarchy-refresh-limine"
"omarchy-refresh-pacman"
"omarchy-refresh-plymouth"
"omarchy-refresh-swayosd"
"omarchy-refresh-walker"
"omarchy-refresh-waybar"
"omarchy-reinstall"
"omarchy-reset-sudo"
"omarchy-restart-app"
"omarchy-restart-bluetooth"
"omarchy-restart-hypridle"
"omarchy-restart-hyprsunset"
"omarchy-restart-pipewire"
"omarchy-restart-swayosd"
"omarchy-restart-terminal"
"omarchy-restart-walker"
"omarchy-restart-waybar"
"omarchy-restart-wifi"
"omarchy-restart-xcompose"
"omarchy-setup-dns"
"omarchy-setup-fido2"
"omarchy-setup-fingerprint"
"omarchy-show-done"
"omarchy-show-logo"
"omarchy-snapshot"
"omarchy-state"
"omarchy-theme-bg-next"
"omarchy-theme-current"
"omarchy-theme-install"
"omarchy-theme-list"
"omarchy-theme-next"
"omarchy-theme-remove"
"omarchy-theme-set"
"omarchy-theme-set-browser"
"omarchy-theme-set-cursor"
"omarchy-theme-set-gnome"
"omarchy-theme-set-obsidian"
"omarchy-theme-set-vscode"
"omarchy-theme-update"
"omarchy-toggle-idle"
"omarchy-toggle-nightlight"
"omarchy-toggle-screensaver"
"omarchy-toggle-waybar"
"omarchy-tui-install"
"omarchy-tui-remove"
"omarchy-tz-select"
"omarchy-update"
"omarchy-update-available"
"omarchy-update-available-reset"
"omarchy-update-branch"
"omarchy-update-confirm"
"omarchy-update-firmware"
"omarchy-update-git"
"omarchy-update-keyring"
"omarchy-update-perform"
"omarchy-update-restart"
"omarchy-update-system-pkgs"
"omarchy-update-time"
"omarchy-update-without-idle"
"omarchy-upload-log"
"omarchy-version"
"omarchy-version-branch"
"omarchy-version-channel"
"omarchy-version-pkgs"
"omarchy-webapp-handler-hey"
"omarchy-webapp-handler-zoom"
"omarchy-webapp-install"
"omarchy-webapp-remove"
"omarchy-windows-vm"
#+end_example

**** Edges

***** Nodes Without Edges

All nodes with edges

#+name: omarchyNodesWithEdges
#+begin_src shell :results output verbatim :var edges=omarchyScriptsEdges
# echo $edges | sed -E 's/"omarchy-/\nomarchy/g'
echo $edges \
    | sed -E 's/" -> "/"\n"/g' | sed -E 's/" "/"\n"/g'\
    | sort | uniq
#+end_src

#+RESULTS: omarchyNodesWithEdges
#+begin_example
"omarchy-base"
"omarchy-battery-monitor"
"omarchy-battery-remaining"
"omarchy-branch-set"
"omarchy-channel-set"
"omarchy-cmd-missing"
"omarchy-cmd-present"
"omarchy-cmd-reboot"
"omarchy-cmd-screensaver"
"omarchy-cmd-share"
"omarchy-cmd-shutdown"
"omarchy-debug"
"omarchy-drive-info"
"omarchy-drive-select"
"omarchy-drive-set-password"
"omarchy-font-set"
"omarchy-hook"
"omarchy-hyprland-window-close-all"
"omarchy-hyprland-window-pop"
"omarchy-install"
"omarchy-install-dev-env"
"omarchy-install-dropbox"
"omarchy-install-tailscale"
"omarchy-install-terminal"
"omarchy-install-vscode"
"omarchy-keyring"
"omarchy-launch-about"
"omarchy-launch-bluetooth"
"omarchy-launch-editor"
"omarchy-launch-floating-terminal-with-presentation"
"omarchy-launch-or-focus"
"omarchy-launch-or-focus-tui"
"omarchy-launch-or-focus-webapp"
"omarchy-launch-screensaver"
"omarchy-launch-tui"
"omarchy-launch-webapp"
"omarchy-launch-wifi"
"omarchy-manual"
"omarchy-migrate"
"omarchy-new"
"omarchy-notification-dismiss"
"omarchy-nvim-setup"
"omarchy-pkg-add"
"omarchy-pkg-aur-accessible"
"omarchy-pkg-aur-install"
"omarchy-pkg-install"
"omarchy-pkg-missing"
"omarchy-pkg-remove"
"omarchy-refresh-config"
"omarchy-refresh-fastfetch"
"omarchy-refresh-hypridle"
"omarchy-refresh-hyprland"
"omarchy-refresh-hyprlock"
"omarchy-refresh-hyprsunset"
"omarchy-refresh-limine"
"omarchy-refresh-pacman"
"omarchy-refresh-plymouth"
"omarchy-refresh-swayosd"
"omarchy-refresh-walker"
"omarchy-refresh-waybar"
"omarchy-reinstall"
"omarchy-restart-"
"omarchy-restart-app"
"omarchy-restart-hypridle"
"omarchy-restart-hyprsunset"
"omarchy-restart-swayosd"
"omarchy-restart-terminal"
"omarchy-restart-walker"
"omarchy-restart-waybar"
"omarchy-restart-xcompose"
"omarchy-show-done"
"omarchy-snapshot"
"omarchy-state"
"omarchy-theme-bg-next"
"omarchy-theme-install"
"omarchy-theme-next"
"omarchy-theme-remove"
"omarchy-theme-set"
"omarchy-theme-set-browser"
"omarchy-theme-set-cursor"
"omarchy-theme-set-gnome"
"omarchy-theme-set-obsidian"
"omarchy-theme-set-vscode"
"omarchy-toggle-nightlight"
"omarchy-tui-install"
"omarchy-tz-select"
"omarchy-update"
"omarchy-update-available-reset"
"omarchy-update-branch"
"omarchy-update-confirm"
"omarchy-update-firmware"
"omarchy-update-git"
"omarchy-update-keyring"
"omarchy-update-perform"
"omarchy-update-restart"
"omarchy-update-system-pkgs"
"omarchy-update-time"
"omarchy-update-without-idle"
"omarchy-upload-log"
"omarchy-version"
"omarchy-webapp-handler"
"omarchy-webapp-handler-hey"
"omarchy-webapp-handler-zoom"
"omarchy-webapp-install"
"omarchy-webapp-remove"
"omarchy-windows"
"omarchy-windows-vm"
#+end_example

=echo '<< omarchyNodesWithEdges() >>'= $#@!

#+name: awkRollup
#+begin_src awk
BEGIN { count=0 }
# { print $0; next }
(count % 6 == 5) { print $0; count++; }
(count % 6 != 5) { printf "%s ", $1; count++; }
#+end_src

All non-communicating nodes

#+begin_src shell :results output verbatim :var edges=omarchyScriptsEdges a=awkRollup :noweb yes
comm -2 -3 <(echo $edges \
    | sed -E 's/" -> "/"\n"/g' | sed -E 's/" "/"\n"/g'\
    | sort | uniq) \
    <(ls omarchy/bin | sort \
    | sed -E 's/^(.*)/"\1"/g' \
    | sort | uniq | grep -v '"omarchy-menu"') \
    | awk "$a"
# still empty?? for diff, the last echo is important
#+end_src

#+RESULTS:

***** All Edges

All the script names are =omarchy-([a-z]+-)*([a-z]+)=

#+name: omarchyScriptsEdges
#+begin_src shell :results output verbatim
cd omarchy
find bin -name 'omarchy*' -type f -exec grep -E '(omarchy-[a-z-]+)' \{\} + \
    | sed -E 's/:.*(omarchy-[a-z-]+).*$/ -> \1/g' \
    | sed -E 's/^bin\///g' \
    | sed -E 's/^(.*) -> /"\1" -> /g' \
    | sed -E 's/ -> (.*)$/ -> "\1"/g' \
    | sort | uniq | grep -v '"omarchy-menu" -> '
#+end_src

#+RESULTS: omarchyScriptsEdges
#+begin_example
"omarchy-battery-monitor" -> "omarchy-battery-remaining"
"omarchy-branch-set" -> "omarchy-branch-set"
"omarchy-channel-set" -> "omarchy-channel-set"
"omarchy-channel-set" -> "omarchy-refresh-pacman"
"omarchy-channel-set" -> "omarchy-update"
"omarchy-cmd-reboot" -> "omarchy-hyprland-window-close-all"
"omarchy-cmd-reboot" -> "omarchy-state"
"omarchy-cmd-share" -> "omarchy-cmd-share"
"omarchy-cmd-shutdown" -> "omarchy-hyprland-window-close-all"
"omarchy-cmd-shutdown" -> "omarchy-state"
"omarchy-debug" -> "omarchy-debug"
"omarchy-drive-info" -> "omarchy-drive-info"
"omarchy-drive-select" -> "omarchy-drive-info"
"omarchy-drive-set-password" -> "omarchy-drive-select"
"omarchy-font-set" -> "omarchy-font-set"
"omarchy-font-set" -> "omarchy-hook"
"omarchy-font-set" -> "omarchy-restart-swayosd"
"omarchy-font-set" -> "omarchy-restart-waybar"
"omarchy-hook" -> "omarchy-hook"
"omarchy-hyprland-window-pop" -> "omarchy-hyprland-window-pop"
"omarchy-install-dev-env" -> "omarchy-install-dev-env"
"omarchy-install-dev-env" -> "omarchy-pkg-add"
"omarchy-install-dropbox" -> "omarchy-pkg-add"
"omarchy-install-tailscale" -> "omarchy-tui-install"
"omarchy-install-tailscale" -> "omarchy-webapp-install"
"omarchy-install-terminal" -> "omarchy-install-terminal"
"omarchy-install-terminal" -> "omarchy-pkg-add"
"omarchy-install-vscode" -> "omarchy-pkg-add"
"omarchy-install-vscode" -> "omarchy-theme-set-vscode"
"omarchy-launch-about" -> "omarchy-launch-or-focus-tui"
"omarchy-launch-bluetooth" -> "omarchy-launch-or-focus-tui"
"omarchy-launch-editor" -> "omarchy-cmd-present"
"omarchy-launch-editor" -> "omarchy-launch-tui"
"omarchy-launch-floating-terminal-with-presentation" -> "omarchy-show-done"
"omarchy-launch-or-focus" -> "omarchy-launch-or-focus"
"omarchy-launch-or-focus-tui" -> "omarchy-launch-or-focus"
"omarchy-launch-or-focus-tui" -> "omarchy-launch-tui"
"omarchy-launch-or-focus-webapp" -> "omarchy-launch-or-focus"
"omarchy-launch-or-focus-webapp" -> "omarchy-launch-or-focus-webapp"
"omarchy-launch-or-focus-webapp" -> "omarchy-launch-webapp"
"omarchy-launch-screensaver" -> "omarchy-cmd-screensaver"
"omarchy-launch-wifi" -> "omarchy-launch-or-focus-tui"
"omarchy-notification-dismiss" -> "omarchy-notification-dismiss"
"omarchy-pkg-add" -> "omarchy-pkg-missing"
"omarchy-pkg-aur-accessible" -> "omarchy-update"
"omarchy-pkg-aur-install" -> "omarchy-show-done"
"omarchy-pkg-install" -> "omarchy-show-done"
"omarchy-pkg-remove" -> "omarchy-show-done"
"omarchy-refresh-fastfetch" -> "omarchy-refresh-config"
"omarchy-refresh-hypridle" -> "omarchy-refresh-config"
"omarchy-refresh-hypridle" -> "omarchy-restart-hypridle"
"omarchy-refresh-hyprland" -> "omarchy-refresh-config"
"omarchy-refresh-hyprlock" -> "omarchy-refresh-config"
"omarchy-refresh-hyprsunset" -> "omarchy-refresh-config"
"omarchy-refresh-hyprsunset" -> "omarchy-restart-hyprsunset"
"omarchy-refresh-swayosd" -> "omarchy-refresh-config"
"omarchy-refresh-swayosd" -> "omarchy-restart-swayosd"
"omarchy-refresh-walker" -> "omarchy-refresh-config"
"omarchy-refresh-walker" -> "omarchy-restart-walker"
"omarchy-refresh-waybar" -> "omarchy-refresh-config"
"omarchy-refresh-waybar" -> "omarchy-restart-waybar"
"omarchy-reinstall" -> "omarchy-base"
"omarchy-reinstall" -> "omarchy-new"
"omarchy-reinstall" -> "omarchy-nvim-setup"
"omarchy-reinstall" -> "omarchy-refresh-limine"
"omarchy-reinstall" -> "omarchy-refresh-plymouth"
"omarchy-restart-hypridle" -> "omarchy-restart-app"
"omarchy-restart-hyprsunset" -> "omarchy-restart-app"
"omarchy-restart-swayosd" -> "omarchy-restart-app"
"omarchy-restart-waybar" -> "omarchy-restart-app"
"omarchy-restart-xcompose" -> "omarchy-restart-app"
"omarchy-snapshot" -> "omarchy-snapshot"
"omarchy-snapshot" -> "omarchy-update"
"omarchy-snapshot" -> "omarchy-version"
"omarchy-state" -> "omarchy-state"
"omarchy-theme-install" -> "omarchy-manual"
"omarchy-theme-install" -> "omarchy-theme-install"
"omarchy-theme-install" -> "omarchy-theme-set"
"omarchy-theme-next" -> "omarchy-theme-set"
"omarchy-theme-remove" -> "omarchy-theme-next"
"omarchy-theme-remove" -> "omarchy-theme-remove"
"omarchy-theme-set-browser" -> "omarchy-cmd-present"
"omarchy-theme-set-cursor" -> "omarchy-theme-set-vscode"
"omarchy-theme-set-obsidian" -> "omarchy-theme-set-obsidian"
"omarchy-theme-set" -> "omarchy-hook"
"omarchy-theme-set" -> "omarchy-restart-swayosd"
"omarchy-theme-set" -> "omarchy-restart-terminal"
"omarchy-theme-set" -> "omarchy-restart-waybar"
"omarchy-theme-set" -> "omarchy-theme-bg-next"
"omarchy-theme-set" -> "omarchy-theme-set"
"omarchy-theme-set" -> "omarchy-theme-set-browser"
"omarchy-theme-set" -> "omarchy-theme-set-cursor"
"omarchy-theme-set" -> "omarchy-theme-set-gnome"
"omarchy-theme-set" -> "omarchy-theme-set-obsidian"
"omarchy-theme-set" -> "omarchy-theme-set-vscode"
"omarchy-theme-set-vscode" -> "omarchy-cmd-present"
"omarchy-toggle-nightlight" -> "omarchy-restart-waybar"
"omarchy-tz-select" -> "omarchy-restart-waybar"
"omarchy-update-branch" -> "omarchy-snapshot"
"omarchy-update-branch" -> "omarchy-update-branch"
"omarchy-update-branch" -> "omarchy-update-perform"
"omarchy-update-firmware" -> "omarchy-cmd-missing"
"omarchy-update-firmware" -> "omarchy-pkg-add"
"omarchy-update-keyring" -> "omarchy-keyring"
"omarchy-update-keyring" -> "omarchy-update-system-pkgs"
"omarchy-update" -> "omarchy-snapshot"
"omarchy-update" -> "omarchy-update-confirm"
"omarchy-update" -> "omarchy-update-git"
"omarchy-update" -> "omarchy-update-perform"
"omarchy-update" -> "omarchy-update-without-idle"
"omarchy-update-perform" -> "omarchy-hook"
"omarchy-update-perform" -> "omarchy-migrate"
"omarchy-update-perform" -> "omarchy-update-available-reset"
"omarchy-update-perform" -> "omarchy-update-keyring"
"omarchy-update-perform" -> "omarchy-update-restart"
"omarchy-update-perform" -> "omarchy-update-system-pkgs"
"omarchy-update-perform" -> "omarchy-update-time"
"omarchy-update-restart" -> "omarchy-restart-"
"omarchy-update-restart" -> "omarchy-state"
"omarchy-update-system-pkgs" -> "omarchy-pkg-aur-accessible"
"omarchy-upload-log" -> "omarchy-install"
"omarchy-webapp-handler-hey" -> "omarchy-launch-webapp"
"omarchy-webapp-handler-zoom" -> "omarchy-launch-webapp"
"omarchy-webapp-install" -> "omarchy-launch-webapp"
"omarchy-webapp-remove" -> "omarchy-webapp-handler"
"omarchy-windows-vm" -> "omarchy-pkg-add"
"omarchy-windows-vm" -> "omarchy-windows"
"omarchy-windows-vm" -> "omarchy-windows-vm"
#+end_example

*** The full list

Here =-= in each string is replaced by =/= except the first. It's bit confusing, but
useful at a first glance (=omarchy-menu= and =omarchy-menu-keybindings= are both
commands)

#+begin_src shell :results output code :wrap example text
# :eval never
ls $chkout/bin | tr '-' '/' | sed -e 's/omarchy\//omarchy-/g' | tree --fromfile .
# ls $chkout/bin | tr '-' '/' | tree --fromfile .
#+end_src

#+RESULTS:
#+begin_example text
.
├── omarchy-battery
│   ├── monitor
│   └── remaining
├── omarchy-branch
│   └── set
├── omarchy-channel
│   └── set
├── omarchy-cmd
│   ├── apple
│   │   └── display
│   │       └── brightness
│   ├── audio
│   │   └── switch
│   ├── first
│   │   └── run
│   ├── missing
│   ├── present
│   ├── reboot
│   ├── screenrecord
│   ├── screensaver
│   ├── screenshot
│   ├── share
│   ├── shutdown
│   └── terminal
│       └── cwd
├── omarchy-debug
├── omarchy-dev
│   └── add
│       └── migration
├── omarchy-drive
│   ├── info
│   ├── select
│   └── set
│       └── password
├── omarchy-font
│   ├── current
│   ├── list
│   └── set
├── omarchy-hook
├── omarchy-hyprland
│   ├── window
│   │   ├── close
│   │   │   └── all
│   │   └── pop
│   └── workspace
│       └── toggle
│           └── gaps
├── omarchy-install
│   ├── chromium
│   │   └── google
│   │       └── account
│   ├── dev
│   │   └── env
│   ├── docker
│   │   └── dbs
│   ├── dropbox
│   ├── steam
│   ├── tailscale
│   ├── terminal
│   ├── vscode
│   └── xbox
│       └── controllers
├── omarchy-launch
│   ├── about
│   ├── bluetooth
│   ├── browser
│   ├── editor
│   ├── floating
│   │   └── terminal
│   │       └── with
│   │           └── presentation
│   ├── or
│   │   └── focus
│   │       ├── tui
│   │       └── webapp
│   ├── screensaver
│   ├── tui
│   ├── walker
│   ├── webapp
│   └── wifi
├── omarchy-lock
│   └── screen
├── omarchy-menu
│   └── keybindings
├── omarchy-migrate
├── omarchy-notification
│   └── dismiss
├── omarchy-pkg
│   ├── add
│   ├── aur
│   │   ├── accessible
│   │   └── install
│   ├── drop
│   ├── install
│   ├── missing
│   ├── pinned
│   ├── present
│   └── remove
├── omarchy-powerprofiles
│   └── list
├── omarchy-refresh
│   ├── applications
│   ├── config
│   ├── fastfetch
│   ├── hypridle
│   ├── hyprland
│   ├── hyprlock
│   ├── hyprsunset
│   ├── limine
│   ├── pacman
│   ├── plymouth
│   ├── swayosd
│   ├── walker
│   └── waybar
├── omarchy-reinstall
├── omarchy-reset
│   └── sudo
├── omarchy-restart
│   ├── app
│   ├── bluetooth
│   ├── hypridle
│   ├── hyprsunset
│   ├── pipewire
│   ├── swayosd
│   ├── terminal
│   ├── walker
│   ├── waybar
│   ├── wifi
│   └── xcompose
├── omarchy-setup
│   ├── dns
│   ├── fido2
│   └── fingerprint
├── omarchy-show
│   ├── done
│   └── logo
├── omarchy-snapshot
├── omarchy-state
├── omarchy-theme
│   ├── bg
│   │   └── next
│   ├── current
│   ├── install
│   ├── list
│   ├── next
│   ├── remove
│   ├── set
│   │   ├── browser
│   │   ├── cursor
│   │   ├── gnome
│   │   ├── obsidian
│   │   └── vscode
│   └── update
├── omarchy-toggle
│   ├── idle
│   ├── nightlight
│   ├── screensaver
│   └── waybar
├── omarchy-tui
│   ├── install
│   └── remove
├── omarchy-tz
│   └── select
├── omarchy-update
│   ├── available
│   │   └── reset
│   ├── branch
│   ├── confirm
│   ├── firmware
│   ├── git
│   ├── keyring
│   ├── perform
│   ├── restart
│   ├── system
│   │   └── pkgs
│   ├── time
│   └── without
│       └── idle
├── omarchy-upload
│   └── log
├── omarchy-version
│   ├── branch
│   ├── channel
│   └── pkgs
├── omarchy-webapp
│   ├── handler
│   │   ├── hey
│   │   └── zoom
│   ├── install
│   └── remove
└── omarchy-windows
    └── vm

58 directories, 135 files
#+end_example

* Export

Export as subtree =C-c C-e C-s h o=

** Scripts

=bin/omarchy-*= scripts that don't run =bin/omarchy-*= scripts

#+begin_export html
<pre>
bin                            bin                                      bin                          bin
└── omarchy                    └── omarchy                              └── omarchy                  └── omarchy
    ├── battery                    ├── install                              ├── powerprofiles            ├── theme
    │   ├── monitor                │   ├── chromium                         │   └── list                 │   ├── bg
    │   └── remaining              │   │   └── google                       ├── refresh                  │   │   └── next
    ├── branch                     │   │       └── account                  │   ├── applications         │   ├── current
    │   └── set                    │   ├── dev                              │   ├── config               │   ├── install
    ├── channel                    │   │   └── env                          │   ├── fastfetch            │   ├── list
    │   └── set                    │   ├── docker                           │   ├── hypridle             │   ├── next
    ├── cmd                        │   │   └── dbs                          │   ├── hyprland             │   ├── remove
    │   ├── apple                  │   ├── dropbox                          │   ├── hyprlock             │   ├── set
    │   │   └── display            │   ├── steam                            │   ├── hyprsunset           │   │   ├── browser
    │   │       └── brightness     │   ├── tailscale                        │   ├── limine               │   │   ├── cursor
    │   ├── audio                  │   ├── terminal                         │   ├── pacman               │   │   ├── gnome
    │   │   └── switch             │   ├── vscode                           │   ├── plymouth             │   │   ├── obsidian
    │   ├── first                  │   └── xbox                             │   ├── swayosd              │   │   └── vscode
    │   │   └── run                │       └── controllers                  │   ├── walker               │   └── update
    │   ├── missing                ├── launch                               │   └── waybar               ├── toggle
    │   ├── present                │   ├── about                            ├── reinstall                │   ├── idle
    │   ├── reboot                 │   ├── bluetooth                        ├── reset                    │   ├── nightlight
    │   ├── screenrecord           │   ├── browser                          │   └── sudo                 │   ├── screensaver
    │   ├── screensaver            │   ├── editor                           ├── restart                  │   └── waybar
    │   ├── screenshot             │   ├── floating                         │   ├── app                  ├── tui
    │   ├── share                  │   │   └── terminal                     │   ├── bluetooth            │   ├── install
    │   ├── shutdown               │   │       └── with                     │   ├── hypridle             │   └── remove
    │   └── terminal               │   │           └── presentation         │   ├── hyprsunset           ├── tz
    │       └── cwd                │   ├── or                               │   ├── pipewire             │   └── select
    ├── debug                      │   │   └── focus                        │   ├── swayosd              ├── update
    ├── dev                        │   │       ├── tui                      │   ├── terminal             │   ├── available
    │   └── add                    │   │       └── webapp                   │   ├── walker               │   │   └── reset
    │       └── migration          │   ├── screensaver                      │   ├── waybar               │   ├── branch
    ├── drive                      │   ├── tui                              │   ├── wifi                 │   ├── confirm
    │   ├── info                   │   ├── walker                           │   └── xcompose             │   ├── firmware
    │   ├── select                 │   ├── webapp                           ├── setup                    │   ├── git
    │   └── set                    │   └── wifi                             │   ├── dns                  │   ├── keyring
    │       └── password           ├── lock                                 │   ├── fido2                │   ├── perform
    ├── font                       │   └── screen                           │   └── fingerprint          │   ├── restart
    │   ├── current                ├── menu                                 ├── show                     │   ├── system
    │   ├── list                   │   └── keybindings                      │   ├── done                 │   │   └── pkgs
    │   └── set                    ├── migrate                              │   └── logo                 │   ├── time
    ├── hook                       ├── notification                         ├── snapshot                 │   └── without
    └── hyprland                   │   └── dismiss                          └── state                    │       └── idle
        ├── window                 └── pkg                                                               ├── upload
        │   ├── close                  ├── add                                                           │   └── log
        │   │   └── all                ├── aur                                                           ├── version
        │   └── pop                    │   ├── accessible                                                │   ├── branch
        └── workspace                  │   └── install                                                   │   ├── channel
            └── toggle                 ├── drop                                                          │   └── pkgs
                └── gaps               ├── install                                                       ├── webapp
                                       ├── missing                                                       │   ├── handler
                                       ├── pinned                                                        │   │   ├── hey
                                       ├── present                                                       │   │   └── zoom
                                       └── remove                                                        │   ├── install
                                                                                                         │   └── remove
                                                                                                         └── windows
                                                                                                             └── vm
</pre>
#+end_export

=bin/omarchy-*= scripts that depend on =bin/omarchy-*= scripts by name

[[file:img/omarchy-scripts.svg]]

* noexport :noexport:

#+begin_src css
/* org reset --------------------------------------------- */
body { font-size: 0.9em; margin: 0.1em; padding: 0em }
p { font-size: 0.9em; display: table;margin: 2em auto;}
th { background-color: seagreen; color: #F6F6F6; }
table { border: 1px solid darkgreen; border-radius: 3px; }
th,td { border: 1px solid darkgreen; padding: 0.2em; font-size: 0.9em; }
#content { max-width: 100% !important }
code { color: indigo; }
h1,h2,h3,h4,h5 { margin: 0.2em; padding: 0.1em}
ul,ol { margin: 0.1em; }

dd { margin: 0.1em 2em; }
li { margin: 0.1em; }

/* cheatsheet --------------------------------------------- */
table { display: table; margin: auto; }
pre { background: inherit; border: none; padding: 0.2em; margin: 0.2em auto; display:table; }
h2 { color: darkblue; font-size: 1.1em; line-height: 1.1em; text-align: center; margin: 0.2em auto; }

/* this rule is needed twice for some reason */
p.verse b { color: darkgreen !important; }
p.verse b { color: darkgreen; }
p.verse span.underline { color: maroon !important; }  /* font-weight: 550; */
/* p.verse b { color: darkgreen; } */
p.verse { font-family: monospace; line-height: 0.7em; padding: 0; margin: 0.2em}; }
#+end_src
