:PROPERTIES:
:ID:       10741cbe-ead3-49e4-b782-678960f811e3
:END:
#+TITLE: From UI UX for Agent-Based Workflow To Who Knows
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:cea7d11c-8357-4e4f-90b3-fa8210eff796][AI]]
+ [[id:158a3cd8-c08b-4c25-a76d-48bfbe579c6d][Agenticalisterisis: Agents, LLM, AI]]

* Misc
Originally here [[id:62d345a1-cb67-407d-abe8-2d643a82f6a5][Programming: Lispy vs LSP vs Tree-Sitter]], but I fell in a
tangent k-hole for a second there.

Should probably be more specifics on UI/UX -- find someone with an event-bus
that interfaces with local devices ... other than MQTT but 10 points for trying.

It's hard, isn't it? Problems & design concerns for regulating/interfacing with
bots aren't that different. Ever worked at a place with too many slack channels?
Or found it hard to locate older convos/threads? Keep track of a team/project
state?

+ The more varied the activity (or the more something changes), the more
  potential for surprise.
+ The more variance in data & schema, the harder to collate (fit into one common
  encoding; here, the schema or underlying data structures are figuratively the
  collation).
+ The more places there are to *look*, the longer it takes.
  - You should *listen* or react to event driven hooks... you need to know ahead
    of time what types of hooks to write, then what types of handlers you need.
  - it's a completely different paradigm of application design (and thereby, of
    UI/UX needs & concerns)
  - being halfway caught between stateful and stateless applications is
    problematic. The UI/UX needs for those are a second layer to that problem.

Anyway... "From UI/UX for agent-based workflow to who knows"

* ... to Accelerationism, i guess?

"Read by Samuel L Jackson" ... not really though. Don't do that.

What kind of UI/UX will support interfacing with agents? This is the obvious
retort, delivered with a smug "and always was" astronaut meme to emphasize a
sense of crippling helplessness I should experience where I not to learn to love
the borg.

... as though I wouldn't know the tooling & UI/UX paradigm would change. So HCI
efficiency is worthless now? Nothing but ironic? If humans can't provide value
with hands-on-keys interactions (or otherwise), the utility gap will only seem
to increase faster. Emphasis on "_will only seem to_" since:

**if you understand math behind ML/AI (not merely LLM usage)**, you know that
there are problems are sown into the fundamentals.

+ it lacks a kind of determinism where its simple to anticipate how variations
  in a neighborhood of prompt/input may translate into action
+ you can attempt to artificially layer in a kind of "ironic determinism"
  here... e.g. "prompt templates", etc. Lack of awareness is required for
  irony. You don't know that this is what you're trying to enforce in the
  algorithm...
+ but it's NOT the input-to-prompt-input maps that are problematic, it's the
  prompt-input-to-output maps. the same things that make them useful --
  "agents can understand & act on" because data is learned without strict
  definitions of underlying types -- are exactly what make them problematic if
  you universally bake them into everything.
+ So hallucinations & divergence in intended action need to be balanced by:
  - sampling the adjacent prompt space
  - XAI techniques to extract meaning from hidden transformer layers
  - frequent synchronization points

My certainty is better understood when *you* understand this as a stochastic
control-theory problem in high-dimensions (whoever you are... i don't really
grok it that good). Basically: it's difficult to expect that it's always
possible or costly to do, especially if you don't simplify the architectual
perspective used when processes are designed. People basically "solve" this
control problem ... that's what management is, but now the employees live in a
big box of ethercloud. But you solve it through heuristics, constraints and
visibility. Human employees don't have the same constraints, like what's needed
to prevent LLM agents from:

#+begin_quote
whisking magic corporate databases away to disappear in a poof of ninja smoke
before spawning again as a new process -- the same one you've grown to know and
love. so dependable and self-reliant
#+end_quote

Human management solves the control theory problem by:

+ keeping expectations simple/clear/fair & setting expectations simple (this
  limits/establishes number of dimensions for costs/values)
+ forming consensus:
  - driving conversations efficiently (one on one? group? meeting?).
  - ensuring you know what they know (but ... not everything)
  - ensuring they know what you know (when needed . . . heavy emphasis on the
    stuff i now know that they wasn't ever going to tell me)
+ controlling variables:
  - figure out what they are
  - model your department & subordinates
  - backpropagate to determine which factors are most influential
  - how do they connect to risks/variables?
+ developing heuristics:
  - many examples of patterns/habits which are individually adapted. they
    ellicit information which often provides novelty/insight
  - e.g. you don't have time to visit every employee at their desk, but a walk
    through the office for morning coffee at the right time should tell you
    enough (or something you didn't expect). more consistent insights with more
    consisent habits
  - or... you go to lunch at the same time most days, but about 20 minutes
    before other employees would. quick, simple, and you're back early to see
    them come in (one by one)... well, not "see" per se, but "hear or become
    aware of". You're not putting people under a microscope, but instead you're
    in the right place at the right time.
+ Org charts ... and many other things (fuck you: pay me ... for consulting, not
  management)

**if you understand HCI, group workflows and operations...

  + The benefits are context-dependent
    - LLM for ETL
    - LLM for Cloud/Devops
    - LLM for defensive network security
    - LLM for prototypes/programming
  + release management and, conversely, deciding when to bump tags for upstream
    versions/hotfixes becomes far more important. But so is ensuring that what's
    fed into the source code is validated. Understood, as in: for each PR
    changeset in minor release, why is it here, how does it interact with other
    contributions? Sourced from one dev? many?
  + Groups must sync changes later.
    - for non-programming work, they still need to sync. problems are an innate
      info-theoretic consequence of distributed state: CAP theorem stuff.
    - The faster the change, the more threads producing minimal change, the more
      that "C" in "CAP" theorem becomes important, otherwise your org's groups
      diverge into lala land (or your features/PRs)
    - The less the bases for consistency -- are "apples" even "Apple's" -- then
      generally you can't estimate cost/success for synchronization, which
      causes quite a lot of operational processes to be =J.I.T.= as in
      - "going to figure it out in the heat of the moment"
      - capable of dynamically recognizing patterns & changing goals
    - Thus there is then jitter:
      - "this week's sprint took three weeks"
    - And jitter is bad for synchronization guarantees. Even for human-oriented
      processes
      - coordinating five warehouses
      - managing releases and bug-fixes for independently augmented developers
        (using tuned LLM in controlled environment with managed indexes/access).
        Devs will have a different style of LLM iteration/interacton.
      - for eight programming teams of 3-8
      - cleaning up the mess when your robot maid spills the batter

**if you understand legal and adminstrative requirements**

+ legal doesn't like risk, needs controls on it.
+ admin/execs need to strategize into the future. they need stability in the
  long-term

#+begin_quote
kinda tired of typing about pointless rambles here... TL;DR it bubbles up from
the math. if you pick the wrong tools, it changes the UI/UX, but if you don't
plan on building one that supports actual humans, then your people can't fix
problems when they arise

This doesn't mean that LLM doesn't work. It means that people need to discover
_where_ the tool makes sense. Doing so is very "high-order", as defined earlier on
tools. here, some migration towards new tools & away from others:

- parameterized by timeline for migration
- parameterized by the potential set of tools and processes (pros/cons)
- and to some degree, parameterized by ontological factors (being, agency). this
  is usually a component of re-organization or rollout of technological
  innovation. here, there are new types of agents.

So theres some =f(w, t, p, x)= where, loosely:

+ w :: worldstate
+ t :: time
+ p :: processes that functions acting on worldstate (your organization,
  mainly), which may involve specific tools. mostly reasoning about types+
+ a :: people/agents, kinda.

Where you need to integrate, differentiate, "solve" or otherwise optimize this
(in the figurative sense, not literally). That's what it means to "parameterize
by" ... which is why it's so useful to just say "paramterize". It just means:

- some function or decision-making method
- that does something (defined maybe elsewhere)
- where some variables it eats cause the function to change if their value
  changes.
#+end_quote 
  
**if you understand consensus in business**

+ At a high level, business is about stable consensus on partnerships and on
  building out economic options. An older business relationship is more
  valuable: trust has been validated over time; shared history with mutual
  benefits/costs.
+ The history helps form consensus on relationships and there's something
  intangible that could be lost if the involved parties are too immediately
  self-interested. Disruption could result in lost resilience or profit in the
  future.
+ You want to test assertions about the state of the world & about
  partnerships/competitors. You want to accumulate options & pursue actions
  based on mutual understanding with other actors (even if adversarial, but
  that's usually besides the point).
+ so accelerated disurption of processes/relationships will disrupt
  people/orgs. This creates dissonance in expreience
    
Side trek: accelerationism is potentially very bad for everyone.

+ It's not even a net-zero gain for anyone to gain control over lost
  marketshare, since so much consensus is disrupted that very few economic
  actors could retain situational awareness of manufacturing options,
  potential suppliers, etc.
+ even a dozen or so maximally benefitting from disruption cannot save face
  when their operations are highly disrupted, consumers & former partners are
  pissed at lack of choice
+ Many things could break down which causes supply chain failure. Without
  fairly distributed liquidity, there's no way jumpstart the patient with
  defibrullators. MONEY IS THE SIDE EFFECT OF ECONOMIC ACTIVITY, when it seems
  like it's the other way around; that money is the main driver of economic
  activity.
