:PROPERTIES:
:ID:       feb4d288-6906-4661-a7eb-14f0fd358411
:END:
#+TITLE: Security: Linux, Keepass and Secret Service Integration
#+CATEGORY: slips
#+TAGS:  

* Roam
+ [[id:133c1418-9705-4528-8856-ccaea4a3d0ff][Security]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]
+ [[id:6f769bd4-6f54-4da7-a329-8cf5226128c9][Emacs]]
+ [[id:c2afa949-0d1c-4703-b69c-02ffa854d4f4][Cryptography]]
+ [[id:259e67ca-539b-4877-ae9e-86240dab7ca9][TPM: Using age-plugin-tpm, ssh-tpm-agent and tpm2-tools]]

 
* Resources

+ [[https://github.com/keepassxreboot/keepassxc/pull/12252][Configure Freedesktop Secret Service Aliases]] A github PR for managing the
  =libsecret= aliases, a feature in a version I haven't upgraded to yet. This
  would allow setting the =default= alias hosted by =keepassxc= on D-Bus.
  
* Overview

** Libsecret D-Bus Interface

+ Collections :: these have =items=
+ Aliases :: 
** Keepass

TLDR if you're using these integrations:

+ Lock it up. _Do NOT_ leave it open.
+ Make the integration ask for permission, every time, unless it's a separate
  set of passwords. =libsecret= exposes multiple collections that can be searched.
+ =keepassxc= creates objects on the service bus at it's own UUID addresses.
  - It has a separate call for =GetSecret=, but you can dump all the objects &
    notes fields ... so things are not secure in the notes fields
  - That should probably be an application option: don't expose the notes fields
    to integrations.
  
** Compatibility b/w =keepassxc-proxy= and =libsecret= integrations

Anything can ask for credentials, but usually apps only know about their own
credentials. However, apps can enumerate the collections IIRC. It's not so
simple as a user or while testing.

- There are some coming (or already arrived) cryptographic protections for the
  secret service to guarantee only specific apps have access to the credentials
  they own in the keychain IIRC
+ That's why I'd only grant access to specific folders

+ =keepassxc-proxy= will let me choose a group when I create new credentials from
  the browser, but I don't normally register accounts this way.
+ I haven't quite used the =libsecret= integration yet, so idk how those
  credentials are automatically added.

* Integrating

** Other Desktop Environments

+ KDE has an app that lets you open a "wallet"
+ =seahorse= lets you browse =gnome-keyring= data

Both KDE & Gnome handle the backend data separately AFAIK, so idk whether these
apps would show you keychain organization when =libsecret= is fetching data from
=keepassxc=

** Emacs and Shell
Technically, it's possible to get =keepassxc= secrets via emacs, since =auth-source=
will let you fetch via =libsecret= as well. Configuring emacs to do this by
default is a bit too much, since it's just going to have anything that D-Bus
gives it. None of =auth-sources= is enabled by default.

+ =(auth-source-pass-get 'secret "api.github.com/dcunited001^ghub")= would get a
  token value to unsafely handle thereafter -- i.e. it ends up in the messages
  buffer, if you arbitrarily evaluate this stuff. So keep that in mind.
+ You can also fetch with =libsecret= via the =auth-source-secrets= backend, but the
  spec query needs to be stringified (it's in the source). I've tried this
  manually, but it was confusing. The comments clarify somewhat. 

#+begin_src emacs-lisp
(defun auth-source-secrets-search (&rest spec
                                         &key backend create delete label max
                                         &allow-other-keys)
  ;; ...
  )
#+end_src

As a shit-test, once =secrets.el= is loaded and once something is providing that
=D-Bus= service: you can run =M-: (secrets-list-collections)=

#+begin_src emacs-lisp
(secrets-list-collections)
#+end_src

#+RESULTS:
| muh-secrets-on-keepass |

It's seriously obtuse getting to this point otherwise. The code examples in
the actual Gnome libsecret docs look like they'd help.

*** Other Emacs Functionality

+ auth-source-pass--parse-secret
+ auth-source-backends-parser-secrets
+ auth-source-secrets-listify
+ auth-source-secrets-search
+ auth-source-secrets-create
+ auth-source-secrets-saver

** Secret-Tool

if you have zero apriori knowledge about how to use this...

+ =secret-tool= doesn't help 
  - it made more sense for me once I created a test wallet in KDE
+ =qdbus-viewer= can help, but you have to know the magic words
  - GetSecret :: this call requires a =session QDBusViewerObject=, which I don't
    know how to provide

#+begin_src shell :results output code :wrap example text
secret-tool --help
#+end_src

#+RESULTS:
#+begin_example
usage: secret-tool store --label='label' attribute value ...
       secret-tool lookup attribute value ...
       secret-tool clear attribute value ...
       secret-tool search [--all] [--unlock] attribute value ...
       secret-tool lock --collection='collection'
#+end_example

Once you have the collection, you can ask more questions. Thankfully, you can
get the collections with their attributes.

#+begin_src shell
secret-tool search --all Title soundiiz
#+end_src

** Anyways

Really =pass= is the best...

i'd rather use =pass=, but it's just not great at all to sync to mobile. It's
better with the GPG integration and handling API keys. confusingly, there's also
=pass-secret-service=, which allows you to use =pass= CLI to fetch from keyring...
but then there's just =secret-tool= for that. The =libscret= CLI and D-Bus api won't
mesh well with =.password-store=

#+begin_quote
The only reason I know about =libsecret= is because I was bored while DJ'ing at
the rink and =emacs= is on the computer, but it's windows so basically =M-x info= is
the only useful thing to do there. Even with the default windows install, it
includes these generally useful guides: [[https://www.gnu.org/software/emacs/manual/html_mono/auth.html][Auth Source]], [[http://gnu.org/software/emacs/manual/dbus.html][D-Bus]], [[https://www.gnu.org/software/emacs/manual/epa.html][EasyPG Assistant]],
[[https://www.gnu.org/software/emacs/manual/sasl.html][SASL]] ... and others.

There are a ton of things I'd never know if it weren't for an hour or two with
nothing better to do than google new acronyms. It's amazingly difficult to learn
(for real) in Roanoke .... and it's disorienting when you leave.
#+end_quote
