:PROPERTIES:
:ID:       35cdd063-b646-4141-83ea-fcac8b337875
:END:
#+TITLE: Orange Pi
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:708d6f59-64ad-473a-bfbb-58d663bde4f0][IoT]]
+ [[id:584f8339-a893-40ab-b808-7b4f7046313c][Hardware]]

* Docs

+ [[http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-Pi-5-plus.html][Orange Pi 5 Plus Resources]]: manuals, schematics, step file, tools, images
  - The manual is basically a PDF of the wiki page for the device
+ [[https://uthings.uniud.it/building-mainline-u-boot-and-linux-kernel-for-orange-pi-boards][Building mainline U-boot and Linux Kernel for Orange Pi boards]]

** Repos

+ [[https://github.com/orangepi-xunlong/orangepi-build][orangepi-xunlong/orangepi-build]]
  - in [[https://github.com/orangepi-xunlong/orangepi-build/blob/36a2f27f9b2d064331e4e22ccd384e0d269dbd31/scripts/compilation.sh#L371-L387][./scripts/compilation.sh]]:
    - =compile_kernel()=
    - [[https://github.com/orangepi-xunlong/orangepi-build/blob/36a2f27f9b2d064331e4e22ccd384e0d269dbd31/scripts/compilation.sh#L113-L129][compile_uboot()]]
    - most functions use =dpkg-deb= to wrap in a package.
+ [[https://github.com/orangepi-xunlong/firmware][orangepi-xunlong/firmware]]
+ [[https://github.com/orangepi-xunlong/u-boot-orangepi][orangepi-xunlong/u-boot-orangepi]]
+ [[https://github.com/orangepi-xunlong/wiringOP][orangepi-xunlong/wiringOP]]
  - [[https://github.com/orangepi-xunlong/wiringOP/blob/37b32bc8a046ea59bd6855f4e8baa77fa7ef0c51/gpio/gpio.1#L4][gpio manpage]]

+ [[https://github.com/orangepi-xunlong/wiringOP-Python/tree/next][orangepi-xunlong/wiringOP-python]] next branch
+ [[https://github.com/orangepi-xunlong/linux-orangepi][orangepi-xunlong/linux-orangepi]] see branches for Linux 6.6+

** U-Boot

+ [[https://docs.u-boot.org/en/latest/board/rockchip/index.html][U-Boot Board-Specific Doc for Rockchip]]

*** Device Tree

A lot of info for Device Tree setup is required to build a custom information.
This maps the operating system to the hardware componets (and the drivers...)

+ [[https://github.com/devicetree-org/devicetree-specification/releases/download/v0.4/devicetree-specification-v0.4.pdf][device-tree-specification-v0.4]]
  
*** Misc

+ [[U-Boot Reference Manual][2011 U-Boot Reference Manual]]
+ 2024 [[https://www.nuvoton.com/export/resource-files/en-us--UM_EN_MA35H0_U-boot.pdf][NuMicro MA35H0 U-Boot User Manual]] (ARM Cortex A35)

Unrelated to the specific hardware, but lots of images detailing the U-Boot
process: [[https://ww1.microchip.com/downloads/aemDocuments/documents/MPU64/ProductDocuments/SupportingCollateral/Booting_Application_Workloads_on_PIC64GX_White_Paper.pdf][Booting Application Workloads (including Linux) on Microchip PIC64GX]]

** Hardware Functions

These are the values from the =Linux System Adaptation= table.

CPU/etc

| GPU | VPU | NPU |

#+begin_quote
The arch build does not support =NPU= or =Chromium hard solution video=
#+end_quote

Disk

| eMMC Extension ports |
| TF card start        |
| SPI+NVME start       |

Video/Audio/Camera

| HDMI TX1 Video               | HDMI TX1 Audio      |
| HDMI TX2 Video               | HDMI TX2 Audio      |
| HDMI RX Video                | HDMI RX Audio       |
| MIPI LCD display             | MIPI LCD Touch      |
| OV13850 camera               | OV13855 camera      |
| Onboard MIC                  | SPK Horn            |
| headphone playback           | headphone recording |

#+begin_quote
Plus =Chromium hard solution video= whatever that is

Also, the Android build supports a =HDMI CEC= function for remote control via
other HDMI devices. The docs for Linux don't seem to cover this.
#+end_quote

USB

| USB2.0X2        | USB3.0X2            |
| Type-C USB3.0   | Type-C ADB Function |
| Type-C DP Video | Type-C DP Audio     |

Network

| 2.5G PCIe network port X2 | 2.5G PCIe network port light |

Wireless

#+begin_quote
the official kernel builds support drivers for these M.2 E-key devices
#+end_quote

| AP6275P-WIFI   | AP6275P-BT   |
| AX200-WIFI     | AX200-BT     |
| AX210-WIFI     | AX210-BT     |
| RTL8852BE-WIFI | RTL8852BE-BT |

The =infrared function= "requires the use of the official remote" (yeah right)

HDMI CEC

GPIO/etc

| 40PIN GPIO        | 40PIN UART |
| 40PIN I2C         | 40PIN CAN  |
| 40PIN SPI         | 40PIN PWM  |
| Debug serial port |            |

Misc

| MaskROM button        | switch button |
| FAN interface         | RTC Chip      |
| Three-color LED light |               |

RTC is a clock with a battery interface (if reset is needed)

Reboot/Poweroff

| REBOOT command restarts | Poweroff command shutdown |

* Resources
* Issues

* Topics
** Orange Pi

+ The OrangePi 5x boards are too good for the price.
+ Quite a lot of chinese blobs in the builds though.
  - That just is what it is. Not sure whether it's better/worse than someone
    else's blobs.
+ But it's like 3-5x better than a Pi for the same price.
  - eMMC is superfast.
  - RAM is cheap and fast.
  - 2x ethernet @ 2.5Gbps makes some things more possible (idk where to find a
    2.5 Gpbs switch though)
+ The OPI 5+ is going to get hot. And it's not easy to keep cool. Apparently
  thermal throttling kicks in very quickly. You'll need to buy the heatsink+fan
  jacket combo.

** Kernel

*** ubuntu-rockchip

+ [[https://github.com/Joshua-Riek/ubuntu-rockchip][Joshua-Riek/ubuntu-rockchip]]

  
*** DietPi


[[https://github.com/MichaIng/DietPi][MichaIng/DietPi]]

+ [[https://github.com/MichaIng/build][MichaIng/build]] Forked from Armbian Linux Build Framework
  - accumulated [[https://github.com/MichaIng/build/tree/b7ab97f8873e7fc5d6db1ed5351bcd2a35a93577/patch/u-boot/u-boot-rockchip64][u-boot patches for rockchip64]] (aka what could have ever possibly
    went wrong)
+ [[https://github.com/MichaIng/hacks][MichaIng/hacks]] sets up a [[https://github.com/MichaIng/hacks/blob/main/screen_ssh_sessions.sh][screen config]]

Minimized Ubuntu Images with a Wide selection of boards

+ [[https://github.com/search?q=repo%3AMichaIng%2FDietPi%20rk3588&type=code][GH Search on rk3588]]
+ 

*** Orange Pi
[[https://github.com/orangepi-xunlong/linux-orangepi][orangepi-xunlong/linux-orangepi]] see branches for Linux 6.6+

+ [[https://github.com/orangepi-xunlong/linux-orangepi/tree/orange-pi-6.6-rk35xx/arch/arm64/boot/dts/rockchip][rockchip device tree]] and [[https://github.com/orangepi-xunlong/linux-orangepi/blob/orange-pi-6.6-rk35xx/arch/arm64/boot/dts/rockchip/Makefile][Makefile]]
+ [[https://github.com/orangepi-xunlong/linux-orangepi/blob/018b9c0bc2d5130651a7a1dfc33e46028037fba4/arch/arm64/configs/defconfig#L50][arch/arm64/configs/defconfig]] var =CONFIG_ARCH_ROCKCHIP= gets set here (and in
  the arm7 defconfig)

Then =CONFIG_ARCH_ROCKCHIP= affects:

+ drivers/phy/Makefile
+ drivers/soc/Makefile
+ drivers/clk/Makefile
+ arch/arm64/boot/dts/rockchip/Makefile: include device trees

And some other armv7-a files

** Commands

*** gpio
 
|------------------------+----------------------------------------------------|
| gpio mode 4 output     | Set pin 4 to output                                |
| gpio -g mode 23 output | Set GPIO pin 23 to output (same as WiringPi pin 4) |
| gpio mode 1 pwm        | Set pin 1 to PWM mode                              |
| gpio pwm 1 512         | Set pin 1 to PWM value 512 - half brightness       |
| gpio export 17 out     | Set GPIO Pin 17 to output                          |
| gpio export 0 in       | Set GPIO Pin 0 (SDA0) to input.                    |
| gpio -g read 0         | Read GPIO Pin 0 (SDA0)                             |
|------------------------+----------------------------------------------------|


** Guix

*** U-Boot

The package in [[(define-public u-boot-orangepi-r1-plus-lts-rk3328
  (make-u-boot-rockchip-package "orangepi-r1-plus-lts" 'rk3328))][gnu/packages/bootloaders.scm]]

#+begin_src scheme
(define-public u-boot-orangepi-r1-plus-lts-rk3328
  (make-u-boot-rockchip-package "orangepi-r1-plus-lts" 'rk3328))
#+end_src

... Inherits from a bootloader package, generated by
=make-u-boot-rockchip-package=, also in [[https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/bootloaders.scm?h=master#n1153][gnu/packages/bootloaders.scm]]

#+begin_src scheme
(define* (make-u-boot-rockchip-package board soc #:optional configs)
  "Return the U-Boot package for BOARD with AAarch64 Rockchip SOC
(System on Chip)."
  (let* ((board (string-append board "-" (symbol->string soc)))
         (base (make-u-boot-package board "aarch64-linux-gnu"
                                    #:configs configs)))
    (package
      (inherit base)
      (arguments
       (substitute-keyword-arguments (package-arguments base)
         ((#:phases phases)
          #~(modify-phases #$phases
              (add-after 'unpack 'set-environment
                (lambda* (#:key inputs #:allow-other-keys)
                  (setenv "BL31" (search-input-file inputs "/bl31.elf"))))))))
      (inputs (modify-inputs (package-inputs base)
                (append (match soc
                          ('rk3588 arm-trusted-firmware-rk3588)
                          ('rk3399 arm-trusted-firmware-rk3399)
                          ('rk3328 arm-trusted-firmware-rk3328))))))))
#+end_src

The bootloader in [[https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/bootloader/u-boot.scm?h=master#n224][gnu/bootloader/u-boot.scm]] (which inherits from the package)

#+begin_src scheme
(define u-boot-orangepi-r1-plus-lts-rk3328-bootloader
  (bootloader
   (inherit u-boot-rockchip-bootloader)
   (package u-boot-orangepi-r1-plus-lts-rk3328)))
#+end_src

The system image in [[https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/system/images/orangepi-r1-plus-lts-rk3328.scm?h=master#n44][gnu/system/images/orangepi-r1-plus-lts-rk3328.scm]] refers to
the =u-boot-...-bootloader= package

#+begin_src scheme
(define orangepi-r1-plus-lts-rk3328-barebones-os
  (operating-system
    (host-name "windmolen")
    (timezone "Europe/Amsterdam")
    (locale "en_US.utf8")
    (bootloader (bootloader-configuration
                  (bootloader u-boot-orangepi-r1-plus-lts-rk3328-bootloader)
                  (targets '("/dev/mmcblk0"))))
    (initrd-modules '())
    (kernel linux-libre-arm64-generic)
    (file-systems (cons (file-system
                          (device (file-system-label "my-root"))
                          (mount-point "/")
                          (type "ext4")) %base-file-systems))
    (services
     (cons* (service agetty-service-type
                     (agetty-configuration (extra-options '("-L")) ;no carrier detect
                                           (baud-rate "1500000")
                                           (term "vt100")
                                           (tty "ttyS2")))
            (service dhcp-client-service-type)
            (service ntp-service-type) %base-services))))
#+end_src

** Docs


*** Sections to review

It repeats kinda a lot of content, but there are some very useful commands to
know in here.

+ 40 pin interface GPIO, I2C, UART, SPI, CAN and PWM tests

*** Convert from wiki

Pandoc would be too much. I'm just looking to browse the useful commands while
retaining the original context

#+begin_src shell :results output org raw  :eval no
grep  -E "(^=+|\\$ '''|# ''')" /tmp/orangepi-5-plus.wiki \
    | grep -vE '^# ' \
    | sed -E 's/<span.*>(.*)<\/span>/\1/g' \
    | sed -E 's/^<p>//' | sed -E 's/<\/p>$//' \
    | sed -E 's/^<li>//' | sed -E 's/<\/li>$//' \
    | sed -E 's/^= /* /' | sed -E 's/^== /** /' | sed -E 's/^=== /*** /' | sed -E 's/^==== /**** /' \
    | sed -E 's/ =+$//' | sed -E "s/'''/=/g" \
    | sed -E 's/^(.+@.+:.+[$#]) /+ \1 /g' \
    | sed 's/&lt;/</g' | sed 's/&gt;/>/g' | sed 's/&nbsp;/ /g' | sed "s/&quot;/'/g" | sed 's/&amp;/&/g'

# included &gt; &lt; &quot; &nbsp; &amp;
# still includes a few artifacts
# some of the user@host:~$
#+end_src

This is somewhat pointless, as the manual is a PDF printout of the same file
they generate the wiki page with
