:PROPERTIES:
:ID:       8da4dba6-5fbd-46a0-9f34-68bb116c9003
:END:
#+TITLE: LSP: Rant On Whatever
#+CATEGORY: slips
#+TAGS:  
* Roam
+ [[id:711d6a41-5425-4853-97ed-f7698a4a3605][LSP]]

* Rant

I swear I'm not actually as pissed off as I sound. Jesus christ.

LSP in emacs is more difficult. And, depending on the language: YAGNI! You
should _not_ need it anyways, especially if it's lisp. AFAIK, only clojure has an
LSP which is just utterly ironic -- _because LSP is equivalent to a LISP repl
without the fucking parentheses!_ It's actually inferior. I mean I get it, but
... at the same time: it's a horrrrrrible experience. Either

+ languages are over-supported (like with Python) and you can never figure out
  which server to use.
+ Or they are under supported (by the editors!) and there's not enough
  blood/sweat/tears left over from mono-language corporate gov't contract money
  to reasonably support editor integration

LSP in emacs is more difficult. ISTG that =eglot= is better, but it requires more
familiarity with tools. =lsp-mode= is pretty good. But whenever something is
wrong, I have no ability to compare it against VSCode (it depends on the
language, since VSCode will download arbitrary (1) nodejs packages, (2) nodejs
=gypsy.so= libs, IDFK (3) prettier-useless or biome binaries. NixOS can handle
this somewhat more than other tools, but like I'd need to see what it does for _5
fucking seconds_.

Keep in mind that I'm mainly using =nix= bc i thought it'd simply my configuration
while using some proprietary software to mentor in FRC. And I thought it's more
mainstream, but I still don't have anyone supplying me with:

+ information about what's normal & the new stuff that's cool
+ comparing/contrasting what's available in the ecosystem or helping to
  translate which projects do what

#+begin_quote
My gripe here isn't with nix, I usually get help when I ask. It's not that. It
is a large ecosystem, but it's also not really that.

2026/7: too many ranty f-bombs ensued mainly relating to the difficulties
encountering people who can teach me things who also have free facetime to spend
#+end_quote

I'm mainly frustrated bc I still barely know where to start when the editor/LSP
integration exhibits problems. JSON-RPC. Yeh. I would've understood the idea 20
years ago.

This is more of a problem if you cover more languages than the average
programmer or visit more projects.

+ more stuff to configure, more terms to learn, more CLI, more programs to run,
  more packages more styles to track in your head, more exceptions to rules,
  more idiomatic solutions to specific problems (there's usually two or so good
  ways to address a specific problem)

none of this ever results in getting me closer to a job, by the way. so when
people are like "skills issues", i'd love to ask you about 10-20 specific or
general questions with 5-15 minutes to explain those concepts. I'll grade you on
a 1-5 point scale, given the "five levels of understanding" for any given topic.
if at any point you mention that "an endofunctor is a monoid in the class of
assfunctors", you're done. No questions about category theory. more like:

+ how would you integrate LDAP on high-load Linux servers in a corporate
  network? How would you manage upgrades?
+ where does LetsEncrypt fail? what specific additional functionality does ACME
  permit?
+ which design constraint is primary: X509 names & chains or DNS?
+ What is necessary to DNS about the TLD? e.g. the =.com= or =.io=. How does this
  relate to flexibility in architecture over time? How does that principle
  comport to:
  - flexibility in: IP addressing?
  - X509 Common Names and properties?
  - Future-proof metadata keys?
  - URL Routing Scheme to avoid link rot? To avoid later usage of subroutes?

e.g. Route collisions: Github requires =/org= in
=github.com/org/$userOrOrg/repositories= otherwise it collides with
=github.com/$userOrOrg/$repo=. This means no user or org can ever have the name
=org= or =user=.

+ To avoid this, after the =FQDN=, you should guarantee a prefix before
  any dynamic routing that occupies the entire URL space of that component.
+ you need a _finite_ set (e.g. =/u= or =/o=) or a _countable subset_ =[0-9]+.*= which can
  be "infinite" but is still distinguishable as a subspace of the domain of a
  left-adjoint [[https://en.wikipedia.org/wiki/Free_monoid][free monoid]].
  - The former is shorter to type, easier to remember (and harder to remember as
    an exception). 
  - The solution GH went with is still mnemonic, but requires familiarity with
    the app's concepts/schemas in order to explain. You need to know =a priori=
    that GH has orgs or has users. For routing at scale to SOA, it's still not a
    bad solution, but requires pushing some of the complexity to layer-7
    gateways to terminate TLS connections, while forwarding the actual requests
    to the service provider's internal =github.com/(org|user)/(route)= handler
  - Simply branching off the =fqdn= is more mnemonic for the average "=www.tld.com=
    is almost too hard" American.

It's not that complicated, but it's definitely easier to reason about the later
consequences if, =a priori= you understand the free-monoid thing -- or at least if
you're good at working with name-space in a first-principles manner. If instead
you encounter these issues =a postieri=, your solutions will be ad hoc, your
options will be somewhat limited or you may find yourself at a dead end. In
systems where one person can, for practical purposes, reason about the entire
system... but most ubiquitous apps had transcended that point long ago. So when
you go to buy Twitter (or whatever), a majority of the engineering staff will
claim you are literally insane for attempting to fix some of these SOA issues.
And they'll have an endless amount of reasonable arguments for why your demands
are impractical.

the principle btw: if you need to future proof "name-space" (_any_ name-space)
then you ALWAYS retain one or more degrees from the root of the tree. If you do,
you can ALWAYS support old identifiers in namespace by "linking" them to other
subtrees. It's a general principle that shows up everywhere. And NO ONE teaches
this in school AFAIK. I've never seen it in a book or explained plainly. It's
very simple. It's also as easy to break as it is expensive to support migrating
from an old name-space partitioning scheme. So many people encourage "Agile" and
"Don't think, Don't plan: It's tooo hard" without understanding that if you
follow some simple rules, you can have your agile now _and_ in the future.

The idea is pretty plainly seen in the conventions for IPv6 reserved addresses.
And it's also important for keeping enough "free registers" to solve your "tower
of hanoi" when migrating from one system to another (i.e. maintaining service
availability & consistent configuration across devices/subnets/services that are
being moved to a new address space). IPv6 has mechanisms for avoiding that
problem entirely.

+ How does this principle relate to lexing and parsing in compiler design or in
  managing closures for programs? (The one connecting namespace design for DNS,
  X509, IP Addressing, etc)
  - This was simpler to understand in the 1950s, 60s and 70s -- you know, when
    [[https://sarabander.github.io/sicp/html/4_002e3.xhtml#g_t4_002e3]["AMB"]] and [[https://sarabander.github.io/sicp/html/Chapter-5.xhtml#Chapter-5][register machines]] were necessary to reason about, but somehow
    didn't give the entire computer science field a crippling depression.
  - You have a syntax tree and a means of distinguishing concrete values from
    values referenced by names. The latter is a graph, the former is a tree (as
    is name-space).
  - So when you're thinking about how to organize names in a library/language or
    values in nested dictionaries, simple mistakes seriously impair the
    socializability of your code. i.e. it won't be readily adopted... or worse,
    a popular project will propagate its inadequacies through its dependent
    libraries
  - And i'm coming at these problems as someone who is /bad/ at this, not
    necessarily /good/ at it. It's not instinctual and I've been searching for
    simpler ways to understand the same things. Few people explain well what
    could only be taught through experience.

Keep in mind that I've never really had the time to study the SICP book. It took
me about 10 years to find the money to buy it (while I was taking college
courses)... but literally zero people would care if I worked to solve the
problems or develop a more complete understanding of the book. Most people are
idiots. "Get a certification" -- advice from several people, no one in
particular. Anyways, why don't you go on to Target and buy you a certified
sicophant. It's not bad advice, per se, but it's also a gigantic waste of time.
If I thought it was the most efficient way for me to develop skills (or to get a
job), I'd do it. It also happens to be a convenient way to justify
risk/fairness. But it's a piece of paper. It's wierd how stupid I was when I got
my CCNA. It's just so fucking wierd. I'm not 2 years out of college.

Anyways, that principle also appears in D-Bus design: the names of services are
organized in trees, the objects are state which needs to be mirrored in multiple
coordinating programs. Thus, there are trees with service names, references
(names) to objects in foreign programs and reference tracking for sequences of
inter-service interactions. When one service interacts with another, this forms
an edge.

People have lost the ability to reason clearly about these things -- at least,
they don't intentionally apply the first-principles from one context to another,
not without being asked to. And the more recent the graduate, the more they take
this knowledge for granted -- they are _unknown knowns_. To complete projects in a
CS program, you overcome specific challenges that require having applied various
methods. You don't necessarily understand the deeper aspects, though someone in
CS is more likely to be able to explain/generalize, especially with masters or
higher. Later problems are approached differently and you avoid problematic
starting points for design, mostly out of habit.

+ Can you explain configuration-space or name-space in terms of "Degrees of
  Freedom"? What types of dimensions are there? How do you simplify
  design-space?
+ Where does an organization enocunter problems with custom SELinux policy
  deployments? How much money would you budget given:
  - ~30 on-prem servers with reasonable load
  - located at 3+ sites, using a total of <30 ports and accessing up to 5T in
    data, some of which is filebased. 1 application runs containers and 2 run on
    VMs.
  - Running 5 integated applications where 3 of them are custom? 
  - I would budget like $1 to $3M per year in contracting to cover that in
    addition to other services as demand varies according to what's left in the
    services retainer (in other words, SELinux is basically a joke)
