:PROPERTIES:
:ID:       f531f214-f1ba-4855-b6cb-41b79354f0a9
:END:
#+TITLE: Calcium Crystal Structures in Efflorescence
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:1e9132fa-33ec-4306-8a5c-47dd972293a7][Physics]]
+ [[id:fe6cfff6-52e4-44fe-a429-b8e599a3f008][Chemistry]]

* Resources

+ doi:10.1039/c9dt03558c: efflorescense on calcareous objects in museums:
  crystallization, phase characterization and crystal structures of calcium
  acetate formate phases
+ [[doi:10.1107/S2052520615021563]]: Crystal structure of monoclinic Calcium
  Pyrophosphate dihydrate (m-CPPD) involved in inflammatory reactions and
  osteoarthritis

** Aragonite

That "fuzzy" amorphous crystal. When growing, it apparently has or can have
monoclinic tendrils/fibers that break off.

** Glyphosate

From [[https://pubchem.ncbi.nlm.nih.gov/compound/Glyphosate#section=Names-and-Identifiers][pubchem]]

#+begin_src smiles :results output file :file img/smiles/glyphosate.svg
C(C(=O)O)NCP(=O)(O)O
#+end_src

#+RESULTS:
[[file:img/smiles/glyphosate.svg]]

* Notes

Calcium deposits form several different crystal forms, but the presence of
salts/additives in water/soil can change the distribution of ions and reaction
precendence.

The "UV Smell Test" says: definitely calcium... which has the background "white
yellow" and purple glow -- use UV on almost any calcium supplement (or any
supplement using calcium as a filler ... e.g. almost all of them, but you need
one that doesn't include too many other fillers). False positives are easy, but
the "color" results from UV->Fluorescense interaction where the energy has a
specific wavelength w.r.t. the number/kinds of bonds (and /small/ ions, /not/ large
ones; e.g. Mercury).

There definitely other salts moving as well (those are more difficult to see)


** TLDR

Basically, how much roundoff runoff is there, how likely is it the
phosphate detaches and/or enters porous stone material? Does it affect the
crystal structures formed by calcium as to select for monoclinic (hair-like)
crystals over those forming planar sheets?

Or ... does glyphosate have anything to do with anything? ... probably not.
Molarity is relatively low I think.
