:PROPERTIES:
:ID:       62d345a1-cb67-407d-abe8-2d643a82f6a5
:END:
#+TITLE: Programming: Lispy vs LSP vs Tree-Sitter
#+CATEGORY: slips
#+TAGS:  

* Roam
+ [[id:6f769bd4-6f54-4da7-a329-8cf5226128c9][Emacs]]
+ [[id:aeff1aef-4321-4666-8a70-a81025c5c01b][Lisp]]
+ [[id:b82627bf-a0de-45c5-8ff4-229936549942][Guix]]
+ [[id:87c43128-92c2-49ed-b76c-0d3c2d6182ec][Scheme]]
+ [[id:aef34489-3943-4c2f-bf88-828f5ea39e16][Tree-sitter]]
+ [[id:b82627bf-a0de-45c5-8ff4-229936549942][Guix]]
+ [[id:4cdfd5a2-08db-4816-ab24-c044f2ff1dd9][Programming]]
  
* Lispy Forks

There are a few main forks of lispy (this is incomplete). No one knows where
abo-abo is ... or perhaps who it was? The development here has stalled out
because there's no authoritative fork

#+begin_src shell :results output code :wrap verse
echo abo-abo/{,papercatlol,enzuru,enzuru/simendsjo,enzuru/simendsjo/vtrichon,enzuru/simendsjo/pierre-rouleau} \
    | tr ' ' '\n' | tree --noreport --fromfile .
#+end_src

#+RESULTS:
#+begin_verse
.
└── abo-abo
    ├── enzuru
    │   └── simendsjo
    │       ├── pierre-rouleau
    │       └── vtrichon
    └── papercatlol
#+end_verse

There have been many forks to fix a single issue: mainly that =le-geiser.el= only
supported =racket= and causes issues when running any non-racket scheme. It's =1
LoC=.

There's much else that could be done to improve the project.

+ The docs are created by HTML and they're essential: the basics are simple, but
  many keybinds are contextual and hidden. To figure out =lispy-x= and a few other
  issues there's a hydra.
+ The project supports many languages, but some are easier. abo-abo was working
  on =le-python.el=, which seems to have required considerable effort.

The whole thing is frustrating because the project clearly demonstrates the
value of tree-based navigation of text. Lisp programmers have always wanted what
LSP "offers" -- and _we've always had it_. However, emacs exposes an interface to
language-specific tooling, which makes it easier to switch out between various
project environments.

It's just a tragedy of forever unknown potential. See below.

** Lispy vs Code Actions

Anyways! Reasons lispy is fantastic, at least for lisp:

+ The main difference between this an LSP is that I can TRY the "code-actions"
  without having to wrestle through 10,000 lines of mostly identical
  LSP-template typescript. _OPERATIONS ARE COMPOSITIONAL_ and there are many
  ad-hoc ways to =code-act=
  - instead of one way to click the =code-action= light-bulb thinking "maybe it
    will show me a NEW thing I can do, but I may read a list just to reinforce
    the belief that none of those features work anyways"
  - and forget about enumerating the set of possible code-actions: they're never
    documented or obvious. They're ALWAYS context-dependent, unless you read the source
+ You begin to instinctually think in terms of the cursor position's relation to
  the grammer. it's simple.
  - Many potential s-expression transformations or cursor-state transformations
    are known almost instantly to me. I often need to slow down because I need
    to think about the features I haven't used yet.
+ Transforming code in front of you is simple. "Refactor to Macro"
  is not a thing that needs to 100% work because it's trivial to make your
  editor do that in about 6 main steps
  - mostly =]m= then =C-w= then =qa= then =C-y= then =]= -- now at the end of a top-level
    s-exp you inserted into the source.
  - then =[m C-w= and =(mymacro )= and =C-y= to be redundant.
  - There are better ways to "Refactor to Defun", but you can make do without
    them.

** REPL Workflow

And, if the language-tooling is there for the REPL (and editor integration is
correct), then =eval-expression= usually just works. It's similar in other
editors, but most of their REPL functionality is a forgotten appendage at this
point. It's always an afterthought. If I use it, I'm always wondering "is this a
waste of time?".

Meanwhile, _that exactly WHAT the jupyter workflow is_. It's a way to evaluate
code from a specific context while editing it. This is almost implicitly
required for mixing formatting with programming, if it's in the same file. You
can't directly edit =.ipynb= files without some third tooling for that. The
devtools workflow/interface is very similar to Emacs.

+ One textbox is more important than any other: not a place to enter commands
  until recently
+ A javascript console connected to a runtime context (this is the same as a
  repl bound to a buffer/project)
+ And other associated tools that activate depending on context. You just can't
  easily change the visual presentation of that context.

** Agent-Based workflow

What kind of UI/UX will support interfacing with agents? This is the obvious
retort, delivered with a smug "and always was" astronaut meme to emphasize a
sense of crippling helplessness I should experience where I not to learn to love
the borg.

... as though I wouldn't know the tooling & UI/UX paradigm would change. So HCI
efficiency is worthless now? Nothing but ironic? If humans can't provide value
with hands-on-keys interactions (or otherwise), the utility gap will only seem
to increase faster. Emphasis on "_will only seem to_" since:

... continue here [[id:10741cbe-ead3-49e4-b782-678960f811e3][From UI UX for Agent-Based Workflow To Who Knows]]

* LSP is Ubiquitous

LSP is ubiquitous and somewhat "convenient" to _install_. In VSCODE. It's main
practical problem is that it's _NOT_ easy to learn which features you don't know
the _LSP SERVER_ supports (or could support) and what's missing from your editor's
general LSP interface, the functionality for which needs to be extended on a
per-language basis -- really, it's a per-LSP server & per-project basis.

As for tree-sitter query syntax, and the tooling to support or explore it,
you'll never guess what it uses! C'mon. Guess. I'll give you a clue....

#+begin_quote
it was used in the 70's and 80's to specify parameters for elecronic components
and was part of KiCAD until some js-brainrot programmers decided "JSON" would
somehow be an improvement over access to 40 years of parts databases.
#+end_quote

That's right. Everything is denoted in terms of S-Expressions.

** LSP != BAD

It's not that "LSP BAD", it's just a case of overly simplistic tools sucking the
oxygen out of the room for everything else.

+ Theming is low-order: not parameterized by time. i.e. you can very quickly
  evaluate the changes introduced.
  - For static sites, changing themes may mean changing integration tests
    (usually adding). Even there, it's pretty straight forward to see "theme
    changed, theme look good".
  - For editors or applications, same thing: cheap to verify.
+ Tooling is necessarily higher-order (usually parameterized by time or state)
  - how the tool becomes useful based on the state of the world or the state of
    tooling it's integrated into.
  - This necessarily begets you an existential dimension wherefore you should
    reevaluate other tools, ask yourself tough questions like "omg i could
    that... for ten years?"
  - Even a dashboard is usually dependent on the state of the external world.
  - Do you really _need_ the tool? (even small features: configuration change like
    an extra keybinding, a window grouping rule for hyprland or a set of
    workspaces)
  - What's the net-utility gain? Answering that requires understanding: how your
    potential "_being_" would be affected either having or not-having this tool in
    its arsenal of options to equip when solving problems.
    - being in the sense of the nominalized gerund as a thing having agency:
      (emphasis on "_The Thing_" that be's out there "being" in the world)

Some less philosophical examples back down here on earth:
      
+ Justfile vs. bashrc aliases
+ Makefiles vs. logic pushed into Github Action
+ Message Bus vs. Systemd Services
+ LSP action vs. TS queries that select to parameterize a function that
  specifies a grammatical structure to create.

And so, deciding to proceed solving problems with some editor/tooling vs another
requires a bit of trying/failing, but mostly imitation/iteration. When that
iteration is expensive where LSP is "convenient", then determining the net
utility gain (or loss) will almost certainly seem like a loss.

It's not each programmer exploring that for themselves. If you're not on Tom
Hanks Island, you're part of a team/community where devs pursue their interests
and people talk about the tools that solved (or _apparently_ caused problems)

* Treesitter Query Language

Tree-sitter also offers tree-based nav/edits! And a full query language. Is it
used to that extent? NO! Because you already have LSP to configure, then your
editor tooling.

There's an ongoing effort [[https://github.com/mickeynp/combobulate][mickeynp/combobulate]] from the Mastering Emacs author
to demonstrate usage of Tree Sitter's query language. Where treesitter has
query-based operations and edits, there are a few difficulties when implement
this for an editor or for users generally.

+ First off: the editor needs to support the query language: just syntax
  highlighting
+ Then someone needs to implement a third-party thing. This would be so much
  easier if the editor(s) integrate treesitter queries as first-party
  features. Most now do, but you only go looking for similar features when
  your workflow seems to be missing something.
+ Then the user needs to be aware that exists (usually you discover this as
  you begin to use it)
+ Then the user needs to explore functionality. Where can they extend it?
  - Where do they iterate on extensions (e.g. queries are a bit like snippets:
    where do you put your snippets? how should you distribute queries?)
  - For mickeynp/combobulator, it's in your emacs-lisp or maybe .dir-locals.el
    or somewhere else. The good news here is that raw queries can be shared
    between other editors (mostly true of yasnippets, since most everything
    descended from TextMate)
  - It still suffers from a iteration-workflow issue to that of snippets: as you
    change the snippet, it's interface like variabes/etc also changes. Which
    version are you invoking? Does it still have the same keybinds? When queries
    are used to select (instead of select->transform), this is fairly simple to
    deal with.
  - The other issue is that some queries are project-specific.

And a few heavy-weight usages:

+ [[https://github.com/github/semantic][github/semantic]]: treesitter-based parsing, analyzing and comparing. Semantic
  generates haskell types from treesitter grammers and implements the ideas at
  scale -- or _it formerly did_ until assumed transcendant supremacy of LLMs
  cometh! LLM is great for coding, but it's utility is highly dependent on
  context.
+ [[github:github/stack-graphs][github/stack-graphs]] and [[https://docs.rs/tree-sitter-stack-graphs/0.7.0/tree_sitter_stack_graphs/][tree_sitter_stack_graphs]] provides the Tree Sitter DSL
  for stack graphs ... so it's more useful when trying to figure out how various
  parts of the source code interact with other parts.

It's really so sad: the enthusiasm that programmers formerly had for projects
like github/semantic or generalized applications of Bison/Antlr (e.g. language
to language conversion without parity loss) has been totally transferred onto
LLMs (transferrance, kinda in the Jungian sense). like these deterministic
methods.
