:PROPERTIES:
:ID:       cc0abb38-0af4-4e25-bb21-879a8e025f89
:END:
#+TITLE: Roanoke Lacks Many Resources Commonplace In Most Smaller US Cities
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:01ace2d7-1324-4dd2-9e2e-d5c152fdc378][Social Physics]]
+ [[id:4cdfd5a2-08db-4816-ab24-c044f2ff1dd9][Programming]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]

* Preface

#+begin_quote
Moved this here because it's too off-topic.

These are my own thoughts from my own experiences, which I do believe are
exceptional. I've met several people who live here and worked remotely for
companies like Google, CircleCI, etc. Those people don't /need/ meetups or events
and have contributed a lot to the community.

Things have been changing a lot and it's hard for me to get out much. I have
remote access now, but I'm still missing a lot of network services. I lose
productivity without a secondary monitor, but that's kinda necessary to working
out in public (at a coworking space or makerspace).

It's more that the software-oriented community events we have don't really
encourage random free-form interaction except events at a bar. There is a "Code
and Coffee" meetup. It is .NET, but I somehow end up forgetting about it. We've
lacked sufficient "third spaces" except those that are paywalled in one way or
another.

I've developed a ton of ideas for modeling this. See [[https://github.com/dcunited001/zettelkasten/blob/master/slips/20260102034541-social_physics_explained_via_chemistry_analogies.org?plain=1#L9][Social Physics Explained
Via Chemistry Analogies]].

Things have improved a lot, but my life is still fragile. It takes a long time
for things to improve and I get frustrated/pissed off easily.
#+end_quote

* Notes

#+begin_quote
moved this here because it's too off-topic
#+end_quote

Other VA Cities (even those half the size) have

+ LUG and Python groups (we used to have them, but i never heard about it)
+ An Apple Store. I would've applied there, if it was between 2012-2018 almost
  certainly. it's also super useful just to see what they have, etc...
+ Makerspace (we now have one, but i remember looking at Google Groups in 2012)
+ A large four-year college -- and I really mean no offense, RC, but we have a
  large area almost totally without a large college. There's VA Tech, but those
  students never need to leave.
+ VA Western is great, but lacks a student body with.
+ There are no PHD programs outside of Carillion/VT.

I never see much in Roanoke that profoundly affects my understanding of
technical things. This isn't exactly frequent outside of Roanoke either, but it
almost never happens here.

#+begin_quote
+ Mention the lack of technology groups, who takes offense? Those who organize
  tech meetups.
+ Mention a lack of education? Who takes offense? Colleges, etc.

That's not what I mean. You're part of the solution. The problem is seriously
just the people in Roanoke. They don't know what to seek out and they've been
"colonized" by social media and corporate dependence.
#+end_quote

There's just straight academic classism here, which results from

+ geographic isolation, the primary cause
+ gatekeeping: older money in Roanoke is timid/uncertain; somewhat displaced by
  influence of newer money
+ chiaroscuro (exaggerating differences in intellect & in distribution of
  knowledge). there's strong bias in who socializes with who

It's October Sky, basically. If you don't leave -- i.e. if you aren't
artificially boosted or if you screw up 4-year college -- then the brain drain
will trap you here for the rest of your life.

I'm sure these opportunities are great for those who have access to them (or if
you don't need bleeding edge technology) but most of the people here who don't
care _have no idea_ what it's like to be somewhere else. I'm classified as
basically some kind of nebulous mental health problem

Consider again the "educated" here have /social connections overrepresented with
tight connections/ to medical research. On average, Roanokers with:

- some *epistemic authority* on a discipline/profession
- are far more likely to have medical training
- than you'd find for areas with a 4-year student population of 5-10% metro area
  population

This means that the wealthier & more educated Roanokers connected to them will
find it more likely to share the same viewpoint. If you value rationalism and
you need an expert, there are plenty here with medical expertise. So that will
trickle down to the common folk here in Roanoke. If there's an epistemic dispute
-- e.g. some dispute predicated on whether someone certainly has or has not some
mental health issue -- then if you seek advice you'll find answers from experts
in unison. People's viewpoints will tend to be tainted with clinical
terminology. I'm sure it doesn't affect many people here, but strangely:
"everyone in Roanoke knows me ... but i don't know anyone in Roanoke"

The argument is a bit stilted/contorted, I know...

But seriously? WTF is wrong with my life that someone in this area could never
treat me as though I had potential? It's because _almost zero_ of the people that
I'm most frequently connected to can validate anything I say or guide me in any
of my interests. Why would it take a decade for anyone to try? When people try,
they seem to underestimate the gravity of my social poverty. It's asymptotic
like a black hole.
