:PROPERTIES:
:ID:       f38730e0-1f42-42e3-b173-e12535e55bcd
:END:
#+TITLE: Smallstep: CA, Policy and Provisioner Configuration
#+CATEGORY: slips
#+TAGS:
#+PROPERTY: header-args+ :comments none

* Roam
+ [[id:49373db0-532d-4b0f-b8ec-3f9a3f897895][StepCA]]
+ [[id:cf2191d6-e159-47b1-8e57-4154e190b956][Crypto]]
+ [[id:48d763a8-5579-4585-a9a2-e7cbb11701fe][Homelab]]
+ [[id:d4acf534-f60c-4471-bee8-f4b925dd0d90][SOPS]]

* Resources


* X-509

** Trust Bundle

* Concepts
** Contexts

These map a =profile= to an =authority= in =contexts.json=

*** Profiles

+ [[https://smallstep.com/docs/tutorials/intermediate-ca-new-ca/][Smallstep: Use step-ca with your existing Root CA]] This guide clarifies the
  purpose of profiles & their =defaults.json=
+ This =defaults.json= gets merged on top of the authority's =defaults.json=

*** Authority

+ contains =ca.json= server configuration and =defaults.json= for certificate
  defaults

** Policies

+ Limited to [[https://smallstep.com/docs/step-ca/configuration/#policy][one per authority]] in the open source product.

** Templates

** Provisioner

+ An authority has a list of provisioners

* Smallstep
:PROPERTIES:
:header-args+: :dir (setq-local step-root "/tmp/tmp.AdBB5gOL2w")
:END:

** Yubikey PIV

If you don't need a 3-tier CA, then the Smallstep [[https://smallstep.com/docs/step-ca/cryptographic-protection/#yubikey-piv][Yubikey PIV]] example will:

+ generate keys on-device, certs off of the YK device
+ sign the certs with the YK device
+ install the certs to the YK
+ set up the CA to sign additional certs/CSRs

Though the ability to do this is infinitely valuable, as is the example, there's
one slight problem:

+ the same key with ICA signing authority...
+ also has the Root CA signing authority
+ and the yubikey PIV hardware app can only have one PIN

This is further complicated if you're using the PIV app for other things:
signing email, VPN access, mTLS access, AGE for SOPS. You must configure the
touch & pin policy _after_ the management key is loaded and _before_ the pins are
set. You _cannot_ change it afterwards

This is partly addressed by using multiple keys and adding =serial= as a
parameter:

#+begin_src shell
# NOTE this hasn't been tested
# - it needs some further configuration in ca.json
rootCard=993210; rootSlot=82; rootPin=123456;
ca1Card=993220;  ca1Slot=83;  ca1Pin=123456;
ca2Card=983230;  ca2Slot=84;  ca2Pin=123456;
rootProfile=root-ca; rootName=root; rootCert=root_ca.crt
ca1Profile=ca1-ca;   ca1Name=ca1;   ca1Cert=ca1_ca.crt;  ca1context=ca1
ca2Profile=ca2-ca;   ca2Name=ca2;   ca2Cert=ca2_ca.crt;  ca2context=ca2

# the root CA doesn't necessarily need to be generated on-device. I plan on
# keeping it offline, so i really only need $ca2context (which is another
# potential point of failure where it doesn't work or I need to dig deeper)
step kms create --json "yubikey:slot-id=$rootSlot"
step certificate create --profile "$rootProfile" \
    --kms "yubikey:serial=$rootCard&pin-value=$rootPin" \
    --key "yubikey:serial=$rootCard&slot-id=$rootSlot" \
    "$rootName" "$rootCert" # output PEM file

# ca-{kms,key} set the signing authority
step kms create --json "yubikey:slot-id=$ca1Slot"
step certificate create --profile "$ca1Profile" \
    --ca-kms "yubikey:serial=$rootCard&pin-value=$rootPin" \
    --ca-key "yubikey:serial=$rootCard&slot-id=$rootSlot" \
    --kms "yubikey:serial=$ca1Card&pin-value=$ica1Pin" \
    --key "yubikey:serial=$ca1Card&slot-id=$ca1Slot" \
    "$ca1Name" "$ca1cert"

# ensure these are set in ca.json for the $ca1context, 
# - .root, .crt, .key, .kms.type, .kms.uri

ykman piv certificates import "$rootSlot" "$rootCert"
ykman piv certificates import "$ca1Slot"  "$ca1Cert"

# here, it may be necessary to switch --context=$ca1context unless all
# parameters are specified (iirc)
step kms create --json "yubikey:slot-id=$ca2Slot"

# here, I would ensure this ca2 config has an expiration < 90 days or so
step certificate create --context "$ca1context" --profile "$ca2Profile" \
    --ca-kms "yubikey:serial=$ca1Card&pin-value=$ca1Pin" \
    --ca-key "yubikey:serial=$ca1Card&slot-id=$ca1Slot" \
    --kms "yubikey:serial=$ca2Card&pin-value=$ica2Pin" \
    --key "yubikey:serial=$ca2Card&slot-id=$ca2Slot" \
    "$ca2Name" "$ca2cert"

# then ensure these are set in ca.json for the $ca2context
# .root, .crt, .key, .kms.type, .kms.uri
ykman piv certificates import "$ca2Slot"  "$ca2Cert"

# now, using --context=$ca2 should allow you to sign with ca2's keys
#+end_src

I keep waffling between intended configurations to address various
insufficiencies:

+ couldn't simultaneously use piv and openpgp apps with scdaemon
  - fixed with gnupg 2.4 if =scdaemon.conf= includes =application-priority piv=
+ couldn't use =age= keys if =scdaemon= was active
  - this is sops-specific, but for the next few weeks at least,
    =age-plugin-yubikey= can't use =x25519= keys
  - may stll be problems getting =age-plugin-yubikey= and =scdaemon= to play nice

To overcome these, i either needed

1) moar yubikeys (i'm poar)
2) to use =tpmkms=, which i do still need to use

Seems kinda pedantic to block out the variables as above... but it's not. I need
to understand the configuration surface for each operation. that helps
generalize, so I can brainstorm the necessary configuration schemas, while
ensuring it's not excruciating to remember arbitrary strings.

** ykbootstrap ca
:PROPERTIES:
:header-args+: :var STEPPATH=".step.ykbootstrap" yk5root="12345678" ykpivpin="123456" ykpivpuk="12345678" SOPS_EDITOR="vim" SOPS_AGE_KEY_FILE=".age/keys.txt"
:END:

if ={SOPS_,}EDITOR=vim= is set, org-babel cannot interactively complete.
=emacsclient= interrupts asking whether I want to save =/tmp/12345678= and doesn't
seem to complete the request. =vim= is safer anyways.

Screenrc

#+begin_src shell :tangle (expand-file-name "step.ykbootstrap.screenrc" step-root)

#+end_src


#+begin_src shell

#+end_src

*** CA

#+name: stepConfigDefaults
#+begin_src sh :results output code :wrap example json
export STEPPATH # set in :properties:
# echo $(date +%s) | sha256sum | base64 | head -c32
echo Yzk1NWQ2ZjlhYzUwMDQ1MTJmZmY4NThk
step ca init --name 'ykbootstrap' --deployment-type=standalone

# step ca init --name "Local CA" --provisioner admin --dns localhost --address ":443"
# step ca certificate --offline foo.smallstep.com foo.crt foo.key
#+end_src



#+begin_src shell
# step ca certificate --key yubikey:slot-id=82 # --kms yubikey:pin-value=123456
#+end_src


*** Yubikey

Doing this in org-babel is risky with multiple keys

**** PIV

#+begin_src shell :results output
# also in :properties
yk5root=12345678 # ykroot="$(ykman list -s | grep 123)"
ykpivpin=123456
ykpivpuk=12345678

# echo $(date +%s) | sha256sum | head -c48 # defaults to aes192
ykpivmgmt_default=010203040506070801020304050607080102030405060708
ykpivmgmt=7eea8019e3c3042a33db408e8682efb5b3c415c52cee4952

# set mgmt key first. needed to set-retries (which resets PIN/PUK)
ykman -d "$yk5root" piv access change-management-key -P $(echo $ykpivpin) \
    -t -a aes192 -m $ykpivmgmt_default -n $ykpivmgmt
ykman -d "$yk5root" piv access set-retries -P $(echo $ykpivpin | rev) -m $(echo -m $ykpivmgmt)  7 7
ykman -d "$yk5root" piv access change-pin -P $(echo $ykpivpin) -n $(echo $ykpivpin | rev)
ykman -d "$yk5root" piv access change-puk -p $(echo $ykpivpuk) -n $(echo $ykpivpuk | rev)
#+end_src

PIN/Touch policies need to be set before import/generate [[https://docs.yubico.com/yesdk/users-manual/application-piv/pin-touch-policies.html#setting-keys-to-a-non-default-policy-all-slots-other-than-80-81-9b-f9][Non-default pin/touch
policies for PIV slots]]

Generate on =9c= which will contain the second =ICA=

#+begin_src shell :results output code :wrap example :var ykpivmgmt="7eea8019e3c3042a33db408e8682efb5b3c415c52cee4952"
ykman -d "$yk5root" piv keys generate -F pem -a ed25519 \
    --pin-policy always --touch-policy always \
    -P $(echo $ykpivpin | rev) -m $(echo $ykpivmgmt) \
    9c -
#+end_src

#+RESULTS:
#+begin_example
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA+abPSAzd8FYX/IX3DfMf0QbjvkWR2Qh6bU41vimRce4=
-----END PUBLIC KEY-----
#+end_example

**** SOPS

Create initial =.sops.yaml=

#+begin_src yaml :tangle (expand-file-name ".sops.yaml" step-root)
keys:
  users:
    # - &admin0    # gpg1 key
    # age1 key: x25519 via age-keygen
    - &admin1 age1n49hgtpev0deasvk85lwr4s79e33wxlg0zyq7vlgc7jxn8rz649sk00ds8
    # age2 key: x25519 via openssl & ssh-to-age
    - &admin2 age10g7nyzg2llvav0hjyrt3g8yet2huhe4vq9c5jmsde9x4sn7j9vzsy6s2d9

creation_rules:
  - path_regex: \.step\.ykbootstrap/root\.yaml$
    mac_only_encrypted: true
    key_groups:
      - age:
          # - *admin0
          - *admin1
          - *admin2
#+end_src

***** ykbootstrap.yaml
:PROPERTIES:
:header-args+: :var y=".step.ykbootstrap/root.yaml"
:END:

| y  | .step.ykbootstrap/root.yaml |

Sops Schema



Create an initial sops yaml file

#+begin_src shell :results output code :wrap example yaml
export SOPS_AGE_KEY_FILE
sops edit $y
# ykbootstrap:
#     ca2:
#         provisioners:
#             - name_unencrypted: admin
#               kms_unencrypted:
#     ca1:
#         provisioners:
#             - name_unencrypted: admin
#     root:
#         provisioners:
#             - name_unencrypted: admin
#+end_src

#+begin_src shell :results output code :wrap example yaml
export SOPS_AGE_KEY_FILE
d=$(date +%s) # not great
# v=$(echo $d | sha256sum | base64 | head -c32)
k='["ykbootstrap"]["root"]["password"]'
v=Yzk1NWQ2ZjlhYzUwMDQ1MTJmZmY4NThky

sops set --value-file $y $k <(echo "\"$v\"")

k='["ykbootstrap"]["ca1"]["password"]'
v=$(echo $v | rev)
sops set --value-file $y $k <(echo "\"$v\"")

# no password for the ca2, since it's on the key

cat $y
#+end_src

#+RESULTS:
#+begin_example yaml
ykbootstrap:
    ca1:
        provisioners:
            - name_unencrypted: admin
        password: ENC[AES256_GCM,data:wJVG0zfHJCRy4hR4YzOtlR/7aDqx1T85fZ+5EWBmOcRV,iv:2QwxT0LnqC2X4jU801XTepdpbuCP58CCOueIrXglX7I=,tag:L9Ungs/eEKRgmgSwosIx4g==,type:str]
    root:
        provisioners:
            - name_unencrypted: admin
        password: ENC[AES256_GCM,data:HsS17m1Nlfa3xbgu8ZSaVMqir1SNE8wfgVW14SpD4m33,iv:sa6m6f+npabR517xTIAkBbC1/5WynBFwBFLxPCL7SFc=,tag:fSEt+U+aZyf2sGGAaRZCqA==,type:str]
sops:
    age:
        - recipient: age1n49hgtpev0deasvk85lwr4s79e33wxlg0zyq7vlgc7jxn8rz649sk00ds8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUld3ejlqSmNGcjhrNzFp
            d0hPR2pRWUZXM3ZZWUpReUlFeElNNnRMYTFVCnh6a3FGOHRITGpqR3ltLy9UNUpX
            NjVmcXE3NDB6WW1kalpOeWJXU2JJMkUKLS0tIGlIN0s2VE5vTVc0MHVPeTVRK2RC
            OW4zVzBWT3lrSXI5OUY2YUNsb2NSOUUKlCOEWMVq2WyMtmonHgD6sICy0tA0Cstj
            aJGVsJUgE1iwgCfzqzyVf3odynmpeLjYwoXatQ9tggX/+FnS3rDvsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10g7nyzg2llvav0hjyrt3g8yet2huhe4vq9c5jmsde9x4sn7j9vzsy6s2d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISVNzL0xJRmZDV0M2U29N
            TFZOQWsySEV5WEt6a1lhdHdIeXE0NS9XSEdNCm5yVFY4NTNYZE9VZitWQTVkQ0Nh
            RzNkVEhCRTBQRThGUTVWOWd2ODFFcmsKLS0tIGpHUmFlaVFBMkVmOTdKZGRaSGVO
            ekxGZXR3eWRENHRIOXJOTWxmSGg2U3cKtKpcleeBb9bKzT8+ZqV7/ldaOJrRwDfT
            xF+4iXcP+Zk2ugvbaJit7uhyc5yyV1bLdVFu6tC5+z8gdq+fU6EFtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T19:41:10Z"
    mac: ENC[AES256_GCM,data:IftsY77hCCemAKE4v8bxo1RtinLie15TafvnIAcy+McRqNpAjOBj+aOIWALT4fmQWzwgqu60okaBryNcAzhK/0TUPG6IuEXnLO3QFeYusxjay1uEq0jivuZTN43ovU+QqxJ3Mgrf40/n8WO6uZ2WGbATmaAcJbKmg4abvhwXB3c=,iv:tsYK7N+kggxT6N3a0Mc93h03haxJSkDBF/ORqYlipuo=,tag:+7rq9mW4hl7/uM4X4SURVA==,type:str]
    unencrypted_suffix: _unencrypted
    mac_only_encrypted: true
    version: 3.11.0
#+end_example

Ensure =yq -Y .= to retain multiline strings like =enc: |=, otherwise you get line
breaks.

#+begin_src shell :results output code :wrap example yaml
yq . -Y $y
#+end_src

Add secrets

#+begin_src shell

#+end_src

#+RESULTS:

***** =exec-env= and =exec-file=

+ [[https://blog.scottlowe.org/2024/08/14/using-sops-with-pulumi/][Using SOPS with Pulumi]]

Select data and merge into a =sops exec-env= file


**** Age

Create keys (some of these tools may reset the key)

+ x25519 keys are not available yet with (see [[https://github.com/str4d/age-plugin-yubikey/issues/174][str4d/age-plugin-yubikey#174]] and
  [[https://github.com/iqlusioninc/yubikey.rs/pull/577][iqlusioninc/yubikey.rs#577]]) and the UX may be a bit clunky, if it's at all
  like the extant workarounds
+ =ssh-to-age= from mic92/sops-nix only mentions x25519 keys
+ manually pushing x25519 to yubikey slot won't work naively (idk)

#+begin_src shell
mkdir {.age,.ssh} && chmod 700 {.age,ssh}

#userid=alice.id25519.pem
#svc1id=svc1.id25519.pem
#host1d=host1.id25519.pem
admin1=alice.age.id_25519
age-keygen > .age/$admin1.txt
admin1pub=$(age-keygen -y .age/$admin1.txt)
#+end_src

Using =ssh-keygen=

#+begin_src shell
admin2=bob.ssh.id_25519
ssh-keygen -t ed25519 -f .ssh/$admin2
nix shell nixpkgs#ssh-to-age --command ssh-to-age -private-key -i .ssh/$admin2 > .age/$admin2.txt
#+end_src

Encrypt/delete the loose AGE keyfiles except =.age/keys.txt= after concatting them.
Then set ~SOPS_AGE_KEY_FILE=.age/keys.txt~ when decrypting with sops.

#+begin_src shell
cat .age/{alice,bob}*25519.txt | grep -ve '^#'
#+end_src

#+RESULTS:
| AGE-SECRET-KEY-1RNCQT3XW208JSFER458MAAWCE2RTFVSHUHUNN2W809ML5Z6CM3AQ8YWSP4 |
| AGE-SECRET-KEY-18XK52JWFZQSH0QH7HNCC94RJNNZ6GA3URKLN0QZKQZYMWVKYV34SVT9MCD |

#+begin_src shell
age-keygen -y <(cat .age/{alice,bob}*25519.txt | grep -ve '^#')
#+end_src

#+RESULTS:
| age1n49hgtpev0deasvk85lwr4s79e33wxlg0zyq7vlgc7jxn8rz649sk00ds8 |
| age10g7nyzg2llvav0hjyrt3g8yet2huhe4vq9c5jmsde9x4sn7j9vzsy6s2d9 |

***** Via openssl

This is a key... not an ssh key-thing ... it's =PKCS#8= i guess? nope... still not
working... i guess this is a raw key. This wasn't working. Probably safer to use
=ssh-keygen= anyways, since these allow setting lower-level options

#+begin_src shell
admin2=bob.ssl.id_25519
openssl genpkey -algorithm x25519 -out .ssh/$admin2.priv.der -outform DER
openssl pkey -in .ssh/$admin2.priv.der -algorithm x25519 -out .ssh/$admin2.der
# openssl genpkey -algorithm x25519 -out .ssh/$admin2.priv.pem
# openssl pkey -in .ssh/$admin2.priv.pem -out .ssh/$admin2.pem
ssh-keygen -i -f .ssh/$admin2.priv.der -m PKCS8
#+end_src

=M-x x509-viewasn1= shows ASN1... whatever C/C++ inspired witchcraft the
ITU engaged it that wouldn't be reinvented until +JSON+ XML. Truly an ambitious
vision: assign an integer to um everything? lol

Anyways, equivalent to =openssl asn1parse -in .ssh/$admin2.priv.der -inform der=

#+begin_quote
    0:d=0  hl=2 l=  46 cons: SEQUENCE
    2:d=1  hl=2 l=   1 prim: INTEGER           :00
    5:d=1  hl=2 l=   5 cons: SEQUENCE
    7:d=2  hl=2 l=   3 prim: OBJECT            :X25519
   12:d=1  hl=2 l=  34 prim: OCTET STRING      [HEX DUMP]:0420C0868E47552DF004E324625091D6AD27794CADCDEE13D996E86B04F8079D2E6E
#+end_quote

* UML
** Config

+ Defined in [[https://github.com/smallstep/certificates/blob/b5e87345c0527c222c6ef773b429505fb4eea6f9/authority/config/config.go#L67][./authority/config/config.go]]

#+begin_src shell
grep --include '*.go' -re '`json:".*"`' /data/ecto/crypto/smallstep/certificates/authority/
#+end_src

+ root :: a =MultiString=
+ kms :: defined in smallstep/crypto in [[https://github.com/smallstep/crypto/blob/4949ea39338a56b8e02ae539ef71e6b4c55afb14/kms/apiv1/options.go#L197][kms/apiv1/options.go#L197]]

#+begin_src plantuml :file img/devops/step-ca-config.svg
@startjson
{
  "root": "examples/pki/secrets/root_ca.crt",
  "federatedRoots": null,
  "crt": "examples/pki/secrets/intermediate_ca.crt",
  "key": "examples/pki/secrets/intermediate_ca_key",
  "address": ":9000",
  "insecureAddress": ":9000",
  "tls": {
    "cipherSuites": [
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    ],
    "minVersion": 1.2,
    "maxVersion": 1.2,
    "renegotiation": false
  },
  "dnsNames": [ "localhost" ],
  // commonName, KMS and SSH omitted by default
  "kms": {},
  "ssh": {},
  "commonName": "TheICACommonName",
  "logger": { "format": "text" },
  // CRL, MetricsAddress and Monitoring omitted by default
  "crl": {
    "enabled": false,
     "generateOnRevoke": true // cacheDuration, renewPeriod, idpURL
   },
  "monitoring": {},
  "authority": {
    "authorityId": "",
    "deploymentType": "",
    "provisioners": [
      { "type": "jwk", "name": "mariano@smallstep.com" },
      { "type": "jwk", "name": "mike@smallstep.com", "claims": { "minTLSCertDuration": "1m0s", "defaultTLSCertDuration": "2m0s" } },
      { "type": "jwk", "name": "decade", "claims": { "maxTLSCertDuration": "87600h", "defaultTLSCertDuration": "87600h" } },
      { "type": "jwk", "name": "90days", "claims": { "maxTLSCertDuration": "2160h", "defaultTLSCertDuration": "2160h" } }
    ],
    "admins": [],
    "claims": { "enableSSHCA": false, "disableRenewal": true },
    "policy": {
      "x509": {
        "allowWildcardNames": false,
        "allow": {
          "cn": ["some", "commonnames"],
          "dns": ["dns.name.com"],
          "ip": ["123.231.123.231"],
          "email": ["foo@fdsa.com"],
          "uri": ["https://some.uri.com"]
        },
        "deny": {}
      },
      "ssh": {
        "user": {
          "allow": {
            "dns": ["dns.name.com"],
            "ip": ["123.231.123.231"],
            "email": ["foo@fdsa.com"],
            "principals": ["principalidentity"]
          },
          "deny": []
        },
        "host": {
          "allow": [],
          "deny": []
        }
      }
    }
  },
  "password": "password",
  "kms": {
    "type": ["one of ...", "softkms", "cloudkms", "awskms", "pkcs11", "yubikey", "sshagentkms", "azurekms", "capi", "tpmkms", "mackms"],
    "credentialsFile": "path/to/awsorcloud/credfile",
    "uri": "pkcs11-uri:rfc7512",
    "pin": "omit",
    "managementKey": "hexstring",
    "region": "aws-us-east1",
    "profile": "aws-profile",
    "storageDirectory": "path/to/serializedTPMobjects"
  }
}
@endjson
#+end_src

#+RESULTS:
[[file:img/devops/step-ca-config.svg]]

** X509 Templates
+ [[https://github.com/smallstep/crypto/blob/4949ea39338a56b8e02ae539ef71e6b4c55afb14/x509util/name.go#L30][smallstep/crypto ./x509util/name.go]] (see the [[https://pkg.go.dev/go.step.sm/crypto/x509util#Certificate][pkg.go.dev docs]])
+ [[https://github.com/smallstep/crypto/blob/4949ea39338a56b8e02ae539ef71e6b4c55afb14/x509util/testdata/fullsimple.tpl][smallstep/crypto ./x509util/testdata/fullsimple.tpl]]
+ see [[https://smallstep.com/docs/step-ca/templates/#advanced-x509-template-examples][advanced x.509 template exmaples]].
+ the most important fields are:
  - =commonName= and =issuer= (the latter should be auto)
  - =dnsNames=, or other similar shorthand for =sans=
  - =signatureAlgorithm= and =publicKeyAlgorithm=
  - =notBefore= and =notAfter=
+ Unless =sans= are set (whether in full or using shorthand), the
  =.Subject.CommonName= will be set as =SANs=
+ =.Insecure.CR= values indicate what's supplied by the client requesting CSR
  - this contains a subset of [[https://smallstep.com/docs/step-ca/templates/#x509-template-variables][Go tpls properties]] that are available.

A certificate template needs to render to json like below

#+begin_src plantuml :noweb yes :file img/devops/step-ca-tls.svg
@startuml

' !pragma layout smetana
' '!pragma ratio 1
skinparam backgroundcolor transparent
' skinparam DefaultTextAlign left
' skinparam packageTitleAlign left
set namespaceSeparator none
hide circle
hide empty fields
hide empty methods

title Step TLS Configuration

<<x509Name>>
<<x509NameConstraints>>
<<x509Certificate>>
@enduml
#+end_src

#+RESULTS:
[[file:img/devops/step-ca-tls.svg]]

*** Certs

#+name: stepJsonMerges
#+begin_src emacs-lisp :var a-merges='(((id . 42) (foo . 43)) ((id . 43)))
(json-encode (apply #'a-merge a-merges))
#+end_src

#+RESULTS: stepJsonMerges
: {"id":43,"foo":43}

Certificate

#+begin_src plantuml :noweb-ref x509Certificate
json certificate {
  "version": 3,
  "subject": {
    "commonName": "TheCommonName",
    "extraNames": [{"type":"1.2.840.113549.1.9.1", "value":"jane@example.com"}]
  },
  "rawSubject": "deadbeef",
  "issuer": "issuerCommonName",
  "serialNumber": "0x1234567890",
  "dnsNames": ["foo.bar.com", "baz.qux.org"],
  "emailAddresses": ["foo@bar.com"],
  "ipAddresses": ["123.231.123.231"],
  "uris": ["https://doe.com"],
  "sans": [
        {"type": "dns", "value": "backend.example.com"},
        {"type": "email", "value": "jane@example.com"},
        {"type": "ip", "value": "10.0.1.10"},
        {"type": "uri", "value": "https://backend.example.com/root.crt"}
  ],
  "notBefore": "2009-02-13T23:31:30Z",
  "notAfter": "2009-02-14T23:31:30Z",
  "extensions": [{"id":"1.2.3.4","critical":true,"value":"ZXh0ZW5zaW9u"}],
  "keyUsage": ["digitalSignature"],
  "extKeyUsage": ["serverAuth"],
  "unknownExtKeyUsage": ["1.3.6.1.4.1.44924.1.6", "1.3.6.1.4.1.44924.1.7"],
  "subjectKeyId": "c3ViamVjdEtleUlk",
  "authorityKeyId": "YXV0aG9yaXR5S2V5SWQ=",
  "ocspServer": "https://ocsp.server",
  "issuingCertificateURL": "https://ca.com",
  "crlDistributionPoints": "https://ca.com/ca.crl",
  "policyIdentifiers": {},
  "basicConstraints": {
    "isCA": false,
    "maxPathLen": 0
  },
  "nameConstraints": { "critical": true, "permittedDNSDomains": "jane.doe.com" },
  "signatureAlgorithm": "Ed25519",
  "publicKeyAlgorithm": "Ed25519"
}
#+end_src

Name

#+begin_src plantuml :noweb-ref x509Name
json name {
  "country": ["US"],
  "organization": ["Org1"],
  "organizationalUnit": ["Org1 OU1", "Org1 OU2"],
  "locality": [],
  "province": [],
  "streetAddress": [],
  "postalCode": [],
  "serialNumber": "",
  "commonName": "TheCommonName",
  "extraNames": [{"type":"1.2.840.113549.1.9.1", "value":"jane@example.com"}]
}
#+end_src

Name Constraints

#+begin_src plantuml :noweb-ref x509NameConstraints
json nameConstraints {
  "critical": false,
  "permittedDNSDomains": ["doe.com"],
  "excludedDNSDomains": ["doe.org"],
  "permittedIPRanges": ["1.2.3.0/24"],
  "excludedIPRanges": ["3.2.1.0/24"],
  "permittedEmailAddresses": ["jane@doe.com"],
  "excludedEmailAddresses": ["jane@doe.org"],
  "permittedURIDomains": ["https://doe.com"],
  "excludedURIDomains": ["https://doe.org"]
}
#+end_src


* Test Run

Submitting basic values to =step ca init= gives the file-tree below.

#+begin_quote
.
├── certs
│   ├── intermediate_ca.crt
│   └── root_ca.crt
├── config
│   ├── ca.json
│   └── defaults.json
├── db
├── secrets
│   ├── intermediate_ca_key
│   └── root_ca_key
└── templates
#+end_quote

The keys in these tables are all =--cli=options=

|---------+-------------------+----------------------------------|
| ca.json | cli               |                                  |
|---------+-------------------+----------------------------------|
|         | --deployment-type | standalone                       |
|         | --name            | TestCA                           |
|         | --dns             | 127.0.0.1                        |
|         | --address         | 127.0.0.1:443                    |
|         | --provisioner     | me@testca.com                    |
|         | --password        | eFC253hSVyjVWesxccfoCvxKbIweeOMv |
|---------+-------------------+----------------------------------|

It creates a root cert

|--------------------+--------+------------------------------------------------------------------|
| ca.json            | cli    |                                                                  |
|--------------------+--------+------------------------------------------------------------------|
| root               | --root | ./certs/root_ca.crt                                              |
| key                |        | ./secrets/root_ca_key                                            |
| issuer-fingerprint |        | ade4a50390a06e8f8af19e396af81aa35c56ace2f2d25b4a02cb5cc8ec147003 |
|--------------------+--------+------------------------------------------------------------------|

It creates a db and an intermediate cert. These keys aren't CLI options, but
instead match the =ca.json= keys.

|---------------+-----+-------------------------------|
| ca.json       | cli |                               |
|---------------+-----+-------------------------------|
| crt           |     | ./certs/intermediate_ca.crt   |
| key           |     | ./secrets/intermediate_ca_key |
| db.dataSource |     | ./db                          |
|---------------+-----+-------------------------------|

** Adding provisioners

Running =step ca init= with =--acme= adds that provisioner in addtion to JWK.

+ provisioner defaults: ={"type":"ACME","name":"acme"}=

... TODO

** Using KMS

See [[https://smallstep.com/docs/step-ca/cryptographic-protection/#notes-on-azure-key-vault-iam-permissions][Cryptographic Protection]]. Use =step kms create --json [--kms] $kms $kmsUri= to
associate your

** Multi-Context

See [[https://smallstep.com/docs/step-cli/the-step-command/#contexts-working-with-multiple-cas][Working with multiple CAs]]

+ profiles :: client configurations (how you expect clients to)
+ authorities :: CA server config/data.
  - [[ others][Certificate policies]] also go here
  - =type= should only be relevant for [[https://smallstep.com/docs/step-ca/registration-authority-ra-mode/][Registration Authorities]] (e.g. stepcas, a
    frontend for acme and maybe other provisioners simultaneously?)

If you don't specify =--profile= or =--authority= for =step ca init=, then you'll need
to rearrange the file tree. It won't delete the content in =STEPPATH= though.

Running =step ca init --acme --context foobcontext= gives you this file-tree

#+begin_quote
.
├── authorities
│   └── foobcontext
│       ├── certs
│       │   ├── intermediate_ca.crt
│       │   └── root_ca.crt
│       ├── config
│       │   ├── ca.json
│       │   └── defaults.json
│       ├── db
│       ├── secrets
│       │   ├── intermediate_ca_key
│       │   └── root_ca_key
│       └── templates
├── contexts.json
├── current-context.json
└── profiles
    └── foobcontext
        └── config
            └── defaults.json
#+end_quote

+ ./profiles/foobcontext/config/defaults.json :: Empty ={}=
+ ./authorities/foobcontext/config/ca.json :: Looks like the other one

Most of the relevant differences between using =--context= and not:

=diff $STEPPATH/config/ca.json $STEPPATH2/authorities/foobcontext/config/ca.json=

#+begin_example diff
2c2
<       "root": "./certs/root_ca.crt",
---
>       "root": "./authorities/foobcontext/certs/root_ca.crt",
4,5c4,5
<       "crt": "./certs/intermediate_ca.crt",
<       "key": "./secrets/intermediate_ca_key",
---
>       "crt": "./authorities/foobcontext/certs/intermediate_ca.crt",
>       "key": "./authorities/foobcontext/secrets/intermediate_ca_key",
16c16
<               "dataSource": "./db",
---
>               "dataSource": "./authorities/foobcontext/db",
#+end_example

*** List Contexts

#+begin_src sh :eval no
export STEPPATH=/tmp/foostep
cat $(step path --base)/contexts.json | jq 'to_entries | map(.value.profile)'
#+end_src

That should be equivalent to =step context list=


* Test Yubikey PIV



* Babel

#+name: stepPath
#+begin_src emacs-lisp :eval query
(setq-local step-path (or (bound-and-true-p step-path)
                          (read-string "Step path: " (make-temp-file "step-" t))))
#+end_src

#+RESULTS: stepPath
: /tmp/step-SxOKdZ

start a session

#+header: :dir stepPath
#+begin_src sh :session *guix* :results silent :eval query :async yes
pkgs=(step-cli-bin step-ca-bin step-kms-plugin-bin sops)
guix shell -L $HOME/.dotfiles/ellipsis -L $HOME/.dotfiles/ellipsis ${pkgs[@]}
#+end_src

test session

#+begin_src sh :session *guix* :results silent :eval query
step kms --help
#+end_src

Can't seem to use =org-babel-switch-to-session=. There aren't many [[https://emacs.stackexchange.com/questions/5293/how-to-force-an-org-babel-session-to-reset-or-initialize][answers]] on this.
