:PROPERTIES:
:ID:       f57629e9-2b38-4934-b3d7-1075ca6e91af
:END:
#+TITLE: Carbide Create: Install via Wine & Bottles
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:6a7b6508-e7cf-4f55-a589-d354cee1766d][CAD]]
+ [[id:ead2a3c7-131f-4fec-8d83-35b3a7b511dc][CAM]]


* Resources
+ [[https://community.carbide3d.com/t/carbide-create-pro-on-linux-wine/90130][Carbide Create Pro on Linux (wine)]] covers getting the license file accepted
  if the pro version is running under Wine.

* Notes

Judging from forum posts, the developers seem to have no idea that Flatpak
exists nor understand App Images, citing "users would want their distribution to
work." This is strange, considering their CNC milling software only runs on Pi
and their downloads are being pulled from Linode. Oh... and it's a QT
application.

** Setup Wine & Bottles on Garuda Linux

The instructions would be different on Nix... I was about to remove Arch.

+ Open =Garuda Gamer=, check Bottles, Wine and Wine Tricks, click Apply.
+ Open =Configure Wine= and click around. Nothing custom seems necessary for now.
  I believe this Wine environment is different than the containerize Wine
  environments from within Bottles.
+ Download the =CarbideCreate-814.exe= installer from
  [[https://carbide3d.com/carbidecreate/download]]
+ Open =Bottles=, click through the startup menu. Then click =Create New Bottle=,
  set an =Application= use case. For now, I'm using =soda-9.0.1= as the runner, but
  =sys-wine=10.15= is also posssible.
+ Click into the bottle after it's finalized. Explore =Settings=, check
  =Dependencies=. To install, click =Install Programs= ... nevermind, these just
  provide quicker access to "curated installers.". Instead, click =Run
  Executable...= and select the =exe=.
+ It installs to =C:\Program Files\CarbideCreatedV8=. Once that's done, click the
  play icon beside =carbidecreate=.

** Using Carbide Create

You would need =Carbide Create Pro= for 3D cam. Projects save to =*.c2d= format

+ You can import (open) vector files: =*.dxf=, =*.svg=, =*.c2d=
+ You can export: =*.svg=

It doesn't seem that you can directly export the =*.gcode= for carbide motion.

** Using Carbide Motion

Carbide motion can:

+ Understand jobs in =*.c2d= and =*.gcode= formats
+ Preview jobs. Tool changes are specifed... somehow.
+ Interpret jobs and export G-Code.
+ Seems to be based on GBRL.
+ Can send G-Code directly to the machine (using MDI)
