:PROPERTIES:
:ID:       906f0085-c2ca-4037-a096-fc2a164fcf27
:END:
#+TITLE: Arch: Omarchy Bin Scripts
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:fbf366f2-5c17-482b-ac7d-6dd130aa4d05][Arch]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]
+ [[id:77df4a7f-ce6a-4b0a-a4cf-453d9da625c5][Build]]
+ [[id:2049060e-6755-4a64-b295-F7B563B41505][NixOS]]
+ [[id:b3f26f1f-1527-4707-9e5f-baac3ac7b865][NixOS: mixing packages and profiles with home-manager]]

* Resources

This is basically the same approach as described in this article: [[https://zaynetro.com/post/2024-you-dont-need-home-manager-nix][You may not
need a Home Manager]]

** Dotfiles
+ [[https://github.com/dcunited001/ellipsis/blob/master/nixos/pkgs/common/omarchy-scripts/package.nix#L16][nixos/pkgs/common/omarchy-scripts/package.nix#L16]]
+ a commit with the changes: [[https://github.com/dcunited001/ellipsis/commit/5dd114142480dba95e1c5173f686dcbe0129f376][dcunited001/ellipsis]]

** Nix
+ android-udev-rules: [[https://github.com/NixOS/nixpkgs/blob/3a4e23f7835a8f561b4c83686a8069ecfa9707eb/pkgs/by-name/an/android-udev-rules/package.nix#L18][pkgs/by-name/an/android-udev-rules/package.nix#L18]]
  - A package guaranteed to install one static file & one static file only

* Nix Pkg

nixos/pkgs/common/omarchy-scripts/package.nix:

#+begin_src nix
{ stdenv, lib, fetchFromGitHub }:

stdenv.mkDerivation rec {
  name = "omarchy-scripts-${version}";
  srcVersion = "3.0.2";
  version = "3.0.2-revision0"; # increment revision number when package changes

  src = fetchFromGitHub {
    owner = "basecamp";
    repo = "omarchy";
    rev = "v${srcVersion}";
    sha256 = "sha256-1QJBoMe6MzaD/dcOcqC8QpRxG0Z2c1p+WYqtNFlsTOA=";
  };

  # from android-udev-rules
  installPhase = ''
    runHook preInstall
    install -D bin/omarchy-cmd-terminal-cwd $out/bin/omarchy-cmd-terminal-cwd
    runHook postInstall
  '';

  doInstallCheck = true;

  meta = {
    description =
      "A collection of scripts from DHH's opinionated arch/hyprland setup.";
    homepage = "https://github.com/basecamp/omarchy";

    license = lib.licenses.mit;
    platforms = lib.platforms.linux;
  };
}
#+end_src


** Fairly simple

Diff to integrate

#+begin_example diff
diff --git a/nixos/modules/users/dc.nix b/nixos/modules/users/dc.nix
index 51242a9..2d7f879 100644
--- a/nixos/modules/users/dc.nix
+++ b/nixos/modules/users/dc.nix
@@ -2,6 +2,8 @@
 let
   hyprdc = (pkgs.callPackage
     (lib.custom.relativeToRoot "pkgs/common/hyprdc/package.nix") { });
+  omarchy-scripts = (pkgs.callPackage
+    (lib.custom.relativeToRoot "pkgs/common/omarchy-scripts/package.nix") { });
 in {

   users.groups = {
@@ -46,6 +48,7 @@ in {
     packages = with pkgs; [
       # CUSTOM
       hyprdc
+      omarchy-scripts

       # CLI
       tree
diff --git a/nixos/pkgs/common/omarchy-scripts/package.nix b/nixos/pkgs/common/omarchy-scripts/package.nix
new file mode 100644
index 0000000..e94ee8e
--- /dev/null
+++ b/nixos/pkgs/common/omarchy-scripts/package.nix
@@ -0,0 +1,32 @@
+{ stdenv, lib, fetchFromGitHub }:
+
+stdenv.mkDerivation rec {
+  name = "omarchy-scripts-${version}";
+  srcVersion = "3.0.2";
+  version = "3.0.2-revision0"; # increment revision number when package changes
+
+  src = fetchFromGitHub {
+    owner = "basecamp";
+    repo = "omarchy";
+    rev = "v${srcVersion}";
+    sha256 = "sha256-1QJBoMe6MzaD/dcOcqC8QpRxG0Z2c1p+WYqtNFlsTOA=";
+  };
+
+  # from android-udev-rules
+  installPhase = ''
+    runHook preInstall
+    install -D bin/omarchy-cmd-terminal-cwd $out/bin/omarchy-cmd-terminal-cwd
+    runHook postInstall
+  '';
+
+  doInstallCheck = true;
+
+  meta = {
+    description =
+      "A collection of scripts from DHH's opinionated arch/hyprland setup.";
+    homepage = "https://github.com/basecamp/omarchy";
+
+    license = lib.licenses.mit;
+    platforms = lib.platforms.linux;
+  };
+}
#+end_example

* Notes
** Integrating
Fairly simple. Most users don't take this approach to building content with nix
derivations, but it's very simple.

+ Depending on the runtime dependencies of this script (and whether it changes
  upstream), you can integrate some static files.

+ Obviously, doing too much of this would be taxing, esp. if you don't plan for
  upstream changes or analyze script dependencies.

*** Nix Profile Path

#+begin_quote
NOTE: this depends on:

+ whether you use =home-manager=
+ whether it's standalone
+ how you set up the =.nix-profile= integration for it
#+end_quote

If you add this =omarchy-scripts= to =users.users.myuser.packages=, it ends up in
the =PATH=. For some types of files, you may need to ensure other search path
variables are updated. Some of these may require relogin, if it affects the
content of =PATH=. If your path includes a symlink to =~/.nix-profile=, it doesn't.

Other changes may require restarting.

+ The WM if its PATH doesn't include whatever
+ Or the dbus session, if you've added new dbus specifications without a
  mechanism to have that process learn about them (I don't recall needed to
  worry about this)
+ ... or systemd: usually the need to "reactivate" systemd seems to be
  detected by nixos-rebuild. Sometimes it won't, like if the systemd path
  includes packages not in the =systemd-path systemd-search-user-unit= by
  symlink

It's possible that this would work with just a standalone =.nix-profile= setup on
a foreign distribution.

+ It depends on whether your =.nix-profile= already exports
  variables for a specific type of search path before adding something that does
  require it.
+ There are some package definitions which don't indicate that to the
  derivation (e.g. they don't result in exporting =GUILE_LOAD_PATH= or
  =QT_PLUGIN_PATH= or whatever)
+ So if that profile doesn't have a need to prepend to =XDG_DATA_DIRS=, it won't
  - if it needs to modify =systemd-search-user-unit=, then you may need to relogin
    for =daemon-reload= to include things

** Maintaining
:PROPERTIES:
:header-args+: :var chkout=(expand-file-name "omarchy" (or (bound-and-true-p ob@arch_omarchy_bin_scripts) (setq ob@arch_omarchy_bin_scripts (make-temp-file "roam-" t))))
:header-args+: :dir (identity ob@arch_omarchy_bin_scripts)
:END:

Basically, which content do you choose to import?

*** Script dependencies

Most scripts seem to be listed by =omarchy-menu= so I've filtered all edges or
nodes that contain =omarchy-menu=.

#+begin_src dot :file img/omarchy-scripts.svg :cmdline "-Tsvg -Kdot" :dir (f-dirname (buffer-file-name (current-buffer))) :noweb yes
digraph G {
    graph[rankdir="LR"]
    <<omarchyScriptsEdges()>>
}
#+end_src

#+RESULTS:
[[file:img/omarchy-scripts.svg]]

All scripts that don't run =omarchy-*= scripts

| omarchy-battery-monitor    | omarchy-cmd-apple-display-brightness | omarchy-cmd-audio-switch                | omarchy-cmd-close-all-windows | omarchy-cmd-first-run     | omarchy-cmd-missing        |
| omarchy-cmd-missing        | omarchy-cmd-screenrecord             | omarchy-cmd-screenshot                  | omarchy-cmd-terminal-cwd      | omarchy-dev-add-migration | omarchy-font-current       |
| omarchy-font-current       | omarchy-font-list                    | omarchy-install-chromium-google-account | omarchy-install-docker-dbs    | omarchy-install-steam     | omarchy-launch-about       |
| omarchy-launch-about       | omarchy-launch-browser               | omarchy-launch-editor                   | omarchy-launch-wifi           | omarchy-lock-screen       | omarchy-menu-keybindings   |
| omarchy-menu-keybindings   | omarchy-pkg-drop                     | omarchy-pkg-missing                     | omarchy-pkg-pinned            | omarchy-pkg-present       | omarchy-powerprofiles-list |
| omarchy-powerprofiles-list | omarchy-refresh-applications         | omarchy-refresh-pacman-mirrorlist       | omarchy-refresh-plymouth      | omarchy-reset-sudo        | omarchy-restart-bluetooth  |
| omarchy-restart-bluetooth  | omarchy-restart-pipewire             | omarchy-restart-wifi                    | omarchy-setup-dns             | omarchy-setup-fido2       | omarchy-setup-fingerprint  |
| omarchy-setup-fingerprint  | omarchy-show-logo                    | omarchy-theme-current                   | omarchy-theme-list            | omarchy-theme-update      | omarchy-toggle-idle        |
| omarchy-toggle-idle        | omarchy-toggle-screensaver           | omarchy-toggle-waybar                   | omarchy-tui-remove            | omarchy-update-available  | omarchy-version-branch     |
| omarchy-version-branch     |                                      |                                         |                               |                           |                            |

Tree of non-communicating nodes

#+begin_src shell :results output verbatim :var edges=omarchyScriptsEdges
comm -1 -3 <(echo $edges \
    | sed -E 's/" -> "/"\n"/g' | sed -E 's/" "/"\n"/g' \
    | sort | uniq) \
    <(ls omarchy/bin | sort \
    | sed -E 's/^(.*)/"\1"/g' \
    | sort | uniq | grep -v '"omarchy-menu"') \
    | tr -d '"' | tr '-' '/' | tree --fromfile .
#+end_src

#+RESULTS:
#+begin_example
.
└── omarchy
    ├── battery
    │   └── monitor
    ├── cmd
    │   ├── apple
    │   │   └── display
    │   │       └── brightness
    │   ├── audio
    │   │   └── switch
    │   ├── close
    │   │   └── all
    │   │       └── windows
    │   ├── first
    │   │   └── run
    │   ├── missing
    │   ├── screenrecord
    │   ├── screenshot
    │   └── terminal
    │       └── cwd
    ├── dev
    │   └── add
    │       └── migration
    ├── font
    │   ├── current
    │   └── list
    ├── install
    │   ├── chromium
    │   │   └── google
    │   │       └── account
    │   ├── docker
    │   │   └── dbs
    │   └── steam
    ├── launch
    │   ├── about
    │   ├── browser
    │   ├── editor
    │   └── wifi
    ├── lock
    │   └── screen
    ├── menu
    │   └── keybindings
    ├── pkg
    │   ├── drop
    │   ├── missing
    │   ├── pinned
    │   └── present
    ├── powerprofiles
    │   └── list
    ├── refresh
    │   ├── applications
    │   ├── pacman
    │   │   └── mirrorlist
    │   └── plymouth
    ├── reset
    │   └── sudo
    ├── restart
    │   ├── bluetooth
    │   ├── pipewire
    │   └── wifi
    ├── setup
    │   ├── dns
    │   ├── fido2
    │   └── fingerprint
    ├── show
    │   └── logo
    ├── theme
    │   ├── current
    │   ├── list
    │   └── update
    ├── toggle
    │   ├── idle
    │   ├── screensaver
    │   └── waybar
    ├── tui
    │   └── remove
    ├── update
    │   └── available
    └── version
        └── branch
#+end_example

*** Nodes

#+name: omarchyScriptsNodes
#+begin_src shell :results output verbatim
ls omarchy/bin | sort \
    | sed -E 's/^(.*)/"\1"/g' \
    | sort | uniq | grep -v '"omarchy-menu"'
#+end_src

#+RESULTS: omarchyScriptsNodes
#+begin_example
"omarchy-battery-monitor"
"omarchy-cmd-apple-display-brightness"
"omarchy-cmd-audio-switch"
"omarchy-cmd-close-all-windows"
"omarchy-cmd-first-run"
"omarchy-cmd-missing"
"omarchy-cmd-present"
"omarchy-cmd-screenrecord"
"omarchy-cmd-screensaver"
"omarchy-cmd-screenshot"
"omarchy-cmd-share"
"omarchy-cmd-terminal-cwd"
"omarchy-cmd-tzupdate"
"omarchy-dev-add-migration"
"omarchy-drive-info"
"omarchy-drive-select"
"omarchy-drive-set-password"
"omarchy-font-current"
"omarchy-font-list"
"omarchy-font-set"
"omarchy-install-chromium-google-account"
"omarchy-install-dev-env"
"omarchy-install-docker-dbs"
"omarchy-install-dropbox"
"omarchy-install-steam"
"omarchy-install-tailscale"
"omarchy-install-terminal"
"omarchy-launch-about"
"omarchy-launch-browser"
"omarchy-launch-editor"
"omarchy-launch-floating-terminal-with-presentation"
"omarchy-launch-or-focus"
"omarchy-launch-or-focus-webapp"
"omarchy-launch-screensaver"
"omarchy-launch-webapp"
"omarchy-launch-wifi"
"omarchy-lock-screen"
"omarchy-menu-keybindings"
"omarchy-migrate"
"omarchy-notification-dismiss"
"omarchy-pkg-add"
"omarchy-pkg-aur-accessible"
"omarchy-pkg-aur-install"
"omarchy-pkg-drop"
"omarchy-pkg-ignored"
"omarchy-pkg-install"
"omarchy-pkg-missing"
"omarchy-pkg-pinned"
"omarchy-pkg-present"
"omarchy-pkg-remove"
"omarchy-powerprofiles-list"
"omarchy-refresh-applications"
"omarchy-refresh-config"
"omarchy-refresh-fastfetch"
"omarchy-refresh-hypridle"
"omarchy-refresh-hyprland"
"omarchy-refresh-hyprlock"
"omarchy-refresh-hyprsunset"
"omarchy-refresh-pacman-mirrorlist"
"omarchy-refresh-plymouth"
"omarchy-refresh-swayosd"
"omarchy-refresh-walker"
"omarchy-refresh-waybar"
"omarchy-reset-sudo"
"omarchy-restart-app"
"omarchy-restart-bluetooth"
"omarchy-restart-hypridle"
"omarchy-restart-hyprsunset"
"omarchy-restart-pipewire"
"omarchy-restart-swayosd"
"omarchy-restart-walker"
"omarchy-restart-waybar"
"omarchy-restart-wifi"
"omarchy-restart-xcompose"
"omarchy-setup-dns"
"omarchy-setup-fido2"
"omarchy-setup-fingerprint"
"omarchy-show-done"
"omarchy-show-logo"
"omarchy-snapshot"
"omarchy-state"
"omarchy-theme-bg-next"
"omarchy-theme-current"
"omarchy-theme-install"
"omarchy-theme-list"
"omarchy-theme-next"
"omarchy-theme-remove"
"omarchy-theme-set"
"omarchy-theme-set-browser"
"omarchy-theme-set-eza"
"omarchy-theme-set-gnome"
"omarchy-theme-set-terminal"
"omarchy-theme-set-vscode"
"omarchy-theme-update"
"omarchy-toggle-idle"
"omarchy-toggle-nightlight"
"omarchy-toggle-screensaver"
"omarchy-toggle-waybar"
"omarchy-tui-install"
"omarchy-tui-remove"
"omarchy-update"
"omarchy-update-available"
"omarchy-update-available-reset"
"omarchy-update-branch"
"omarchy-update-git"
"omarchy-update-perform"
"omarchy-update-restart"
"omarchy-update-system-pkgs"
"omarchy-upload-log"
"omarchy-version"
"omarchy-version-branch"
"omarchy-webapp-handler-zoom"
"omarchy-webapp-install"
"omarchy-webapp-remove"
#+end_example

**** Edges

***** Nodes Without Edges

All nodes with edges

#+name: omarchyNodesWithEdges
#+begin_src shell :results output verbatim :var edges=omarchyScriptsEdges
# echo $edges | sed -E 's/"omarchy-/\nomarchy/g'
echo $edges \
    | sed -E 's/" -> "/"\n"/g' | sed -E 's/" "/"\n"/g'\
    | sort | uniq
#+end_src

#+RESULTS: omarchyNodesWithEdges
#+begin_example
"omarchy-cmd-present"
"omarchy-cmd-screensaver"
"omarchy-cmd-share"
"omarchy-cmd-tzupdate"
"omarchy-drive-info"
"omarchy-drive-select"
"omarchy-drive-set-password"
"omarchy-font-set"
"omarchy-install"
"omarchy-install-dev-env"
"omarchy-install-dropbox"
"omarchy-install-tailscale"
"omarchy-install-terminal"
"omarchy-launch-floating-terminal-with-presentation"
"omarchy-launch-or-focus"
"omarchy-launch-or-focus-webapp"
"omarchy-launch-screensaver"
"omarchy-launch-webapp"
"omarchy-manual"
"omarchy-migrate"
"omarchy-notification-dismiss"
"omarchy-pkg-add"
"omarchy-pkg-aur-accessible"
"omarchy-pkg-aur-install"
"omarchy-pkg-ignored"
"omarchy-pkg-install"
"omarchy-pkg-remove"
"omarchy-refresh-config"
"omarchy-refresh-fastfetch"
"omarchy-refresh-hypridle"
"omarchy-refresh-hyprland"
"omarchy-refresh-hyprlock"
"omarchy-refresh-hyprsunset"
"omarchy-refresh-swayosd"
"omarchy-refresh-walker"
"omarchy-refresh-waybar"
"omarchy-restart-"
"omarchy-restart-app"
"omarchy-restart-hypridle"
"omarchy-restart-hyprsunset"
"omarchy-restart-swayosd"
"omarchy-restart-walker"
"omarchy-restart-waybar"
"omarchy-restart-xcompose"
"omarchy-show-done"
"omarchy-snapshot"
"omarchy-state"
"omarchy-theme-bg-next"
"omarchy-theme-install"
"omarchy-theme-next"
"omarchy-theme-remove"
"omarchy-theme-set"
"omarchy-theme-set-browser"
"omarchy-theme-set-eza"
"omarchy-theme-set-gnome"
"omarchy-theme-set-terminal"
"omarchy-theme-set-vscode"
"omarchy-toggle-nightlight"
"omarchy-tui-install"
"omarchy-update"
"omarchy-update-available-reset"
"omarchy-update-branch"
"omarchy-update-git"
"omarchy-update-perform"
"omarchy-update-restart"
"omarchy-update-system-pkgs"
"omarchy-upload-log"
"omarchy-verion-branch-set"
"omarchy-version"
"omarchy-webapp-handler-zoom"
"omarchy-webapp-install"
"omarchy-webapp-remove"
#+end_example

=echo '<< omarchyNodesWithEdges() >>'= $#@!

#+name: awkRollup
#+begin_src awk
BEGIN { count=0 }
# { print $0; next }
(count % 6 == 5) { print $0; count++; }
(count % 6 != 5) { printf "%s ", $1; count++; }
#+end_src

All non-communicating nodes

#+begin_src shell :results output verbatim :var edges=omarchyScriptsEdges a=awkRollup :noweb yes
comm -2 -3 <(echo $edges \
    | sed -E 's/" -> "/"\n"/g' | sed -E 's/" "/"\n"/g'\
    | sort | uniq) \
    <(ls omarchy/bin | sort \
    | sed -E 's/^(.*)/"\1"/g' \
    | sort | uniq | grep -v '"omarchy-menu"') \
    | awk "$a"
# still empty?? for diff, the last echo is important
#+end_src

***** All Edges

All the script names are =omarchy-([a-z]+-)*([a-z]+)=

#+name: omarchyScriptsEdges
#+begin_src shell :results output verbatim
cd omarchy
find bin -name 'omarchy*' -type f -exec grep -E '(omarchy-[a-z-]+)' \{\} + \
    | sed -E 's/:.*(omarchy-[a-z-]+).*$/ -> \1/g' \
    | sed -E 's/^bin\///g' \
    | sed -E 's/^(.*) -> /"\1" -> /g' \
    | sed -E 's/ -> (.*)$/ -> "\1"/g' \
    | sort | uniq | grep -v '"omarchy-menu" -> '
#+end_src

#+RESULTS: omarchyScriptsEdges
#+begin_example
"omarchy-cmd-share" -> "omarchy-cmd-share"
"omarchy-cmd-tzupdate" -> "omarchy-restart-waybar"
"omarchy-drive-info" -> "omarchy-drive-info"
"omarchy-drive-select" -> "omarchy-drive-info"
"omarchy-drive-set-password" -> "omarchy-drive-select"
"omarchy-font-set" -> "omarchy-font-set"
"omarchy-font-set" -> "omarchy-restart-swayosd"
"omarchy-font-set" -> "omarchy-restart-walker"
"omarchy-font-set" -> "omarchy-restart-waybar"
"omarchy-install-dev-env" -> "omarchy-install-dev-env"
"omarchy-install-dev-env" -> "omarchy-pkg-add"
"omarchy-install-dropbox" -> "omarchy-pkg-add"
"omarchy-install-tailscale" -> "omarchy-tui-install"
"omarchy-install-tailscale" -> "omarchy-webapp-install"
"omarchy-install-terminal" -> "omarchy-install-terminal"
"omarchy-install-terminal" -> "omarchy-pkg-add"
"omarchy-launch-floating-terminal-with-presentation" -> "omarchy-show-done"
"omarchy-launch-or-focus" -> "omarchy-launch-or-focus"
"omarchy-launch-or-focus-webapp" -> "omarchy-launch-or-focus-webapp"
"omarchy-launch-or-focus-webapp" -> "omarchy-launch-webapp"
"omarchy-launch-screensaver" -> "omarchy-cmd-screensaver"
"omarchy-notification-dismiss" -> "omarchy-notification-dismiss"
"omarchy-pkg-aur-accessible" -> "omarchy-update"
"omarchy-pkg-aur-install" -> "omarchy-show-done"
"omarchy-pkg-install" -> "omarchy-show-done"
"omarchy-pkg-remove" -> "omarchy-show-done"
"omarchy-refresh-fastfetch" -> "omarchy-refresh-config"
"omarchy-refresh-hypridle" -> "omarchy-refresh-config"
"omarchy-refresh-hypridle" -> "omarchy-restart-hypridle"
"omarchy-refresh-hyprland" -> "omarchy-refresh-config"
"omarchy-refresh-hyprlock" -> "omarchy-refresh-config"
"omarchy-refresh-hyprsunset" -> "omarchy-refresh-config"
"omarchy-refresh-hyprsunset" -> "omarchy-restart-hyprsunset"
"omarchy-refresh-swayosd" -> "omarchy-refresh-config"
"omarchy-refresh-swayosd" -> "omarchy-restart-swayosd"
"omarchy-refresh-walker" -> "omarchy-refresh-config"
"omarchy-refresh-walker" -> "omarchy-restart-walker"
"omarchy-refresh-waybar" -> "omarchy-refresh-config"
"omarchy-refresh-waybar" -> "omarchy-restart-waybar"
"omarchy-restart-hypridle" -> "omarchy-restart-app"
"omarchy-restart-hyprsunset" -> "omarchy-restart-app"
"omarchy-restart-swayosd" -> "omarchy-restart-app"
"omarchy-restart-waybar" -> "omarchy-restart-app"
"omarchy-restart-xcompose" -> "omarchy-restart-app"
"omarchy-snapshot" -> "omarchy-snapshot"
"omarchy-snapshot" -> "omarchy-update"
"omarchy-snapshot" -> "omarchy-version"
"omarchy-state" -> "omarchy-state"
"omarchy-theme-install" -> "omarchy-manual"
"omarchy-theme-install" -> "omarchy-theme-install"
"omarchy-theme-install" -> "omarchy-theme-set"
"omarchy-theme-next" -> "omarchy-theme-set"
"omarchy-theme-remove" -> "omarchy-theme-next"
"omarchy-theme-remove" -> "omarchy-theme-remove"
"omarchy-theme-set-browser" -> "omarchy-cmd-present"
"omarchy-theme-set" -> "omarchy-restart-swayosd"
"omarchy-theme-set" -> "omarchy-restart-waybar"
"omarchy-theme-set" -> "omarchy-theme-bg-next"
"omarchy-theme-set" -> "omarchy-theme-set"
"omarchy-theme-set" -> "omarchy-theme-set-browser"
"omarchy-theme-set" -> "omarchy-theme-set-eza"
"omarchy-theme-set" -> "omarchy-theme-set-gnome"
"omarchy-theme-set" -> "omarchy-theme-set-terminal"
"omarchy-theme-set" -> "omarchy-theme-set-vscode"
"omarchy-theme-set-vscode" -> "omarchy-cmd-present"
"omarchy-toggle-nightlight" -> "omarchy-restart-waybar"
"omarchy-update-branch" -> "omarchy-snapshot"
"omarchy-update-branch" -> "omarchy-update-perform"
"omarchy-update-branch" -> "omarchy-verion-branch-set"
"omarchy-update" -> "omarchy-snapshot"
"omarchy-update" -> "omarchy-update-git"
"omarchy-update" -> "omarchy-update-perform"
"omarchy-update-perform" -> "omarchy-migrate"
"omarchy-update-perform" -> "omarchy-update-available-reset"
"omarchy-update-perform" -> "omarchy-update-restart"
"omarchy-update-perform" -> "omarchy-update-system-pkgs"
"omarchy-update-restart" -> "omarchy-restart-"
"omarchy-update-restart" -> "omarchy-state"
"omarchy-update-system-pkgs" -> "omarchy-pkg-aur-accessible"
"omarchy-update-system-pkgs" -> "omarchy-pkg-ignored"
"omarchy-upload-log" -> "omarchy-install"
"omarchy-webapp-handler-zoom" -> "omarchy-launch-webapp"
"omarchy-webapp-install" -> "omarchy-launch-webapp"
"omarchy-webapp-remove" -> "omarchy-launch-webapp"
#+end_example

*** The full list

Here =-= in each string is replaced by =/= except the first. It's bit confusing, but
useful at a first glance (=omarchy-menu= and =omarchy-menu-keybindings= are both
commands)

#+begin_src shell :results output code :wrap example text :eval never
ls $chkout/bin | tr '-' '/' | sed -e 's/omarchy\//omarchy-/g' | tree --fromfile .
#+end_src

#+RESULTS:
#+begin_example text
.
├── omarchy-battery
│   └── monitor
├── omarchy-cmd
│   ├── apple
│   │   └── display
│   │       └── brightness
│   ├── audio
│   │   └── switch
│   ├── close
│   │   └── all
│   │       └── windows
│   ├── first
│   │   └── run
│   ├── missing
│   ├── present
│   ├── screenrecord
│   ├── screensaver
│   ├── screenshot
│   ├── share
│   ├── terminal
│   │   └── cwd
│   └── tzupdate
├── omarchy-dev
│   └── add
│       └── migration
├── omarchy-drive
│   ├── info
│   ├── select
│   └── set
│       └── password
├── omarchy-font
│   ├── current
│   ├── list
│   └── set
├── omarchy-install
│   ├── chromium
│   │   └── google
│   │       └── account
│   ├── dev
│   │   └── env
│   ├── docker
│   │   └── dbs
│   ├── dropbox
│   ├── steam
│   ├── tailscale
│   └── terminal
├── omarchy-launch
│   ├── about
│   ├── browser
│   ├── editor
│   ├── floating
│   │   └── terminal
│   │       └── with
│   │           └── presentation
│   ├── or
│   │   └── focus
│   │       └── webapp
│   ├── screensaver
│   ├── webapp
│   └── wifi
├── omarchy-lock
│   └── screen
├── omarchy-menu
│   └── keybindings
├── omarchy-migrate
├── omarchy-notification
│   └── dismiss
├── omarchy-pkg
│   ├── add
│   ├── aur
│   │   ├── accessible
│   │   └── install
│   ├── drop
│   ├── ignored
│   ├── install
│   ├── missing
│   ├── pinned
│   ├── present
│   └── remove
├── omarchy-powerprofiles
│   └── list
├── omarchy-refresh
│   ├── applications
│   ├── config
│   ├── fastfetch
│   ├── hypridle
│   ├── hyprland
│   ├── hyprlock
│   ├── hyprsunset
│   ├── pacman
│   │   └── mirrorlist
│   ├── plymouth
│   ├── swayosd
│   ├── walker
│   └── waybar
├── omarchy-reset
│   └── sudo
├── omarchy-restart
│   ├── app
│   ├── bluetooth
│   ├── hypridle
│   ├── hyprsunset
│   ├── pipewire
│   ├── swayosd
│   ├── walker
│   ├── waybar
│   ├── wifi
│   └── xcompose
├── omarchy-setup
│   ├── dns
│   ├── fido2
│   └── fingerprint
├── omarchy-show
│   ├── done
│   └── logo
├── omarchy-snapshot
├── omarchy-state
├── omarchy-theme
│   ├── bg
│   │   └── next
│   ├── current
│   ├── install
│   ├── list
│   ├── next
│   ├── remove
│   ├── set
│   │   ├── browser
│   │   ├── eza
│   │   ├── gnome
│   │   ├── terminal
│   │   └── vscode
│   └── update
├── omarchy-toggle
│   ├── idle
│   ├── nightlight
│   ├── screensaver
│   └── waybar
├── omarchy-tui
│   ├── install
│   └── remove
├── omarchy-update
│   ├── available
│   │   └── reset
│   ├── branch
│   ├── git
│   ├── perform
│   ├── restart
│   └── system
│       └── pkgs
├── omarchy-upload
│   └── log
├── omarchy-version
│   └── branch
└── omarchy-webapp
    ├── handler
    │   └── zoom
    ├── install
    └── remove

50 directories, 109 files
#+end_example

* Export

Export as subtree =C-c C-e C-s h o=

** Scripts

=bin/omarchy-*= scripts that don't run =bin/omarchy-*= scripts

#+begin_export html
<pre>
.                                   .                                  .
└── omarchy                         └── omarchy                        └── omarchy
    ├── battery                         ├── install                        ├── reset
    │   └── monitor                     │   ├── chromium                   │   └── sudo
    ├── cmd                             │   │   └── google                 ├── restart
    │   ├── apple                       │   │       └── account            │   ├── bluetooth
    │   │   └── display                 │   ├── docker                     │   ├── pipewire
    │   │       └── brightness          │   │   └── dbs                    │   └── wifi
    │   ├── audio                       │   └── steam                      ├── setup
    │   │   └── switch                  ├── launch                         │   ├── dns
    │   ├── close                       │   ├── about                      │   ├── fido2
    │   │   └── all                     │   ├── browser                    │   └── fingerprint
    │   │       └── windows             │   ├── editor                     ├── show
    │   ├── first                       │   └── wifi                       │   └── logo
    │   │   └── run                     ├── lock                           ├── theme
    │   ├── missing                     │   └── screen                     │   ├── current
    │   ├── screenrecord                ├── menu                           │   ├── list
    │   ├── screenshot                  │   └── keybindings                │   └── update
    │   └── terminal                    ├── pkg                            ├── toggle
    │       └── cwd                     │   ├── drop                       │   ├── idle
    ├── dev                             │   ├── missing                    │   ├── screensaver
    │   └── add                         │   ├── pinned                     │   └── waybar
    │       └── migration               │   └── present                    ├── tui
    ├── font                            ├── powerprofiles                  │   └── remove
        ├── current                     │   └── list                       ├── update
        └── list                        ├── refresh                        │   └── available
                                            ├── applications               └── version
                                            ├── pacman                         └── branch
                                            │   └── mirrorlist
                                            └── plymouth
</pre>
#+end_export

=bin/omarchy-*= scripts that depend on =bin/omarchy-*= scripts by name

[[file:img/omarchy-scripts.svg]]
