:PROPERTIES:
:ID:       5b16446b-00f0-48fd-af51-e61d11e74f03
:END:
#+TITLE: Dynamic Epistemic Logic and Games
#+CATEGORY: slips
#+TAGS:

Dynamic Epistemic Logic $\otimes$ (doxastic $\oplus$ normative)

This is missing some pieces (particularly, some lists (e.g.
complexity/decideability) don't really cover enough range of types)


* Roam

+ [[id:a0ef7bfe-1587-4fec-ac87-f7dda5dc0d24][Maths: Foundations]]
+ [[id:01ace2d7-1324-4dd2-9e2e-d5c152fdc378][Social Physics]]

* Resources

+ Dynamic Epistemic Games: [[https://en.wikipedia.org/wiki/Dynamic_epistemic_logic][wiki]] and [[https://iep.utm.edu/dynamic-epistemic-logic/#H7][stanford encyclopedia]]

* Epistemic Games

What's crazy is how little I know about myself. There are epistemic games where
people must control the diffusion of information, which if not controlled
uncovers information, alters salience/attention or sublimates ambiguity.

[[https://arxiv.org/pdf/2303.00067][Playing to Learn, or to Keep Secret: Alternating-Time Logic Meets Information Theory]]

Adding elements of other modal logics reduces the complexity for agents engaged
in these games (whether they know they're playing or not)

- doxastic (should, must, ought)
- or normative logic (the difficulty in proving/modeling is circumvented by
  leveraging distributed computation)

To maximize utility/control, other players can attempt to constrain the flow of
information (w.r.t some player or goal information exchange with other players)
such that information will flow almost entirely _away_ from a player and rarely
towards them.

** The "Language" Construction

So, let's say you have a typcial "alphabet, language & logic bundle" that
defines syntax (interpretation, rules, evaluation, precedence) and enables
construction of interpretable predicates. I've seen so many papers on this which
model Fuzzing, Fuzzy Logic, Modal Logic, computer/network security, etc. _first_
introducing you on page 2 to this confusing "Language" that seems to be required
for pages 3+ in entirety.

When a mathematician mixes all the "modal logic paint colors" together, it's
difficult to:

+ Determine whether your language is sufficient/correct. This is easy-peasy:
  keep it simple lol.
+ And to ensure your logic is significantly distinguished from other similar
  constructions and also comprehensive in its treatment of the the subjects of
  analysis.

Fortunately, this doesn't happen for philosophers at all. (j/k... it's not like
I would prefer the less complicated & less complete)

** Complexity and Decidability

One major issue ends up being computability and decidability. If you've ever
seen idiocracy, not many people seem too concerned with the various "halting"
problems they may have in their life. Doesn't matter. Obviously, people deal
with the computational complexity by:

+ reducing the complexity of a model (heuristics)
+ reading the crowd: this involves normative logic, perhaps fuzzy logic
  (feelings oriented)
+ relying on habits or more prescribed methods, which results in more
  deterministic behavior patterns. this is usually somewhat doxastic (influenced
  by morals/ethics and a tendency to avoid things that provoke cognitive
  dissonance thereof)

** Your Knobs To Turn

Given such a model, other strategize for leveraging mechanics/modulating:

+ inculcation of belief or false knowledge
+ logical "sentences" whose pre
+ distortion of perceived norms, either by using noise/etc to impair the
  perception of norms (regarding beliefs/) or with anti-correlation).
  - you may present a false norm -- whether about yourself or some object of
    knowledge/belief -- e.g. "here work is pretty lax, it is _normally_ okay for
    people to occasionally to leave about 20 minutes early if they need to"
  - you wouldn't want someone to believe you manipulated them (it's easy to
    improperly convey things like this entirely by accident, which I'm sure is
    what _normally_ happens)

* Nullification

I'll probably revisit this.

+ Unthinkable :: you can't quite think it. it's irrational, particularly w.r.t
  ethics or practicality.
+ Unnameable :: you can't name it or maybe you shouldn't. If it can be named,
  this is half the battle. This is particularly terrible if the named object is
  a person: when it's difficult to name a person they gradually fade away into
  nothing. This occasionally makes it useful (and also kinda fucked up)
+ Unknown :: "it" isn't known quite yet and "it" is likely to be unnameable or
  undescribable by whoever doesn't quite know it yet
+ Unknowable :: it's either something that, transitively, cannot be an object of
  thought. Or, intransitively, it's also conceivable this refers to what one
  _must not_ know.
+ Unconscionable :: it doesn't feel good in your head.
+ Inconceiveable :: maybe still doesn't feel good in your head, but whether
  something is conceivable may be a shortcoming of the conscious mind. Can I
  imaging _the_ stone so heavy that God cannot lift it? Can I imagine what it's
  like for birds to see if they have 4 types of cones, including UV? I can try,
  but is it accurate?
+ Unforgettable :: for one reason or another, there's a lasting impression

The point here is to imagine the existential aspects of these types of =un-X-able=
things. What is it like for the =un-X-ed= state of something to change, as it's
experienced by a person. Why would it change?

+ What would cause people to avoid naming a thing -- whether once or whether
  using the name as a reference. Clearly, names are a convention. If I use a
  name or word that you don't recognize, it needs to come with a
  definition/explanation. This is more difficult to imagine in the reverse.
  Fortunately, the example of Voldemort in the Harry Potter moving is a well
  known extreme example of an unnameable

* Secrets

There are many fields where confidentiality & secrecy are important, but if
someone has completely never experienced this, that may indicate something
strange.

#+begin_quote
um never? weird?! that's definitely weird. run? yeh, run! as fast as you can

... maybe
#+end_quote

Seriously, if you can't relate to this at all, then you're probably the one that
everyone is keeping secrets from. it's almost never so simple as to be one-sided
(i.e. you are the /only/ one that /everyone else/ avoids relating to or exposing
information to)

** Modal Logic in Epistemic Games Involving Secrecy

There are epistemic games where where one gains utility through more exclusive
access/verification of epistemes. If the utility function becomes negative given
enough exposure w.r.t. specific potentially unnamable/unmentionable pieces of
information, then players on a team may need doxastic logic -- i.e. one
should/must attempt to remove epistemic structures from the game board where
possible. The players may also have a coordination problem: a high utility value
is risked when players name & mention the target epistemes (occasionally
conspiracy theories).

Now, this shouldn't happen IRL, but it does. Everywhere. And, apparently
nowhere. Most secrets are fairly harmless, considering that (technically)
everything you don't know is each implicity a tiny secret to you. Other concerns
IRL:

+ bandwidth: most people are not actually participating in most games that are
  being played. thus they're incentivized by other utility functions
+ salience: some information doesn't move/absorb quickly and may not be
  "sticky". when many knowledge dependencies are required to understand/validate
  new pieces of knowledge

The main "weird" point about these games:

+ There are ways to qualify that "from now on, only A,B,C agents will know
  X,Y,Z". It may actually necessary to ensure it stays that way.
+ Knowledge dependences that afford more methods of validation or that are
  apropos to risky knowledge may need to be observed/managed
+ Validation of information may risk exposing information. Your drunk uncle
  was never going to understand whether it was real, but instead didn't like
  what the information /implied/ when considered alongside whatever they believe
  is normal (or ought to be ... cuz 'merica!)

If it /really/ is the government secretly screwing with your life -- it's probably
not, since it's also convenient to screw with someone's head and blame it on the
govt -- but if it is, they paradoxically will not leave you alone until you
believe (and falsely know) that it's not them and never was. They'll drop in
from time to time to check up on your beliefs ... if for some reason it is
necessary to eradicate the information. Maybe, idk. It's actually pretty hard to
imagine, but probably happens in some limited contexts.

idk about the govt other than that they would need to cover things up from time
to time. However, people engage in epistemic games all the time ... just on a
less epic scale. They may need to patch up beliefs or prevent someone from
learning something that leads to a cascade of new knowledge. First off, any
handling procedures (for mental health or for difficult customers) lead to
different reactions depending on what knowledge the person has about rules,
training, preferences or strategies to handle a situation. From the perspective
of people who are not me, maybe it's possible it would cascade into worse
outcomes, cycling into more headaches.

In such a situation, people can modulate/tune how they handle/react, but this is
usually more effective given more training, more information or clear
perspectives combined from multiple people. Usually people don't like to
coordinate in groups when it involves something uncomfortable or disagreeable.

My main issue is that I just don't have that kind of social connection or
perspective that allows me to fit my chosen reactions to the situation. I also
don't have any money or friends. It's easy to set things off and I feel
cornered. So when my family ignores me for the first half of 2024 then initiates
some therapist ultimatum that can't really address the employment/social issues
... yeh it's just BS. My problems are my life. I deserve to understand what's
going on. What's abnormal is not neurotransmitters in my brain or a lack of
understanding psychology ... it's a lack of relationships and opportunities.

My family could have done quite a bit more to understand how I may approach a
getting a job. They didn't though. There aren't a ton of tech networking
opportunities here in Roanoke, but I never considered asking my mom for $250 to
sign up for RBTC. She would pay for groceries, but never anything
technological.

+ Nothing was every written down: thus, I may have an argument, but it requires
  tree-traversal over _ALL_ the logical predicates. My brother seems to have
  adopted a methodic way of creating stack overflow by nitpicking e.v.e.r.y
  s.i.n.g.l.e predicate or concept. IT LITERALLY BLOWS THE STACK OF THE
  CONVERSATION. It is intentional IMO. It turns any /serious/ discussion into
  emotional BS where they can claim I'm crazy and emotionally unstable.
+ . . it's just impossible for me to get my brother/mother to admit any facts at
  all. So no other logic may follow.. HENCE: EPISTEMIC GAMES
+ Again, nothing is ever written down ... this also makes me feel a bit wierd
  about my therapy. In my experience, don't suppress your intuition.

Pity is nice, but pity doesn't have high expectations. Expectation, habit,
anticipation -- these aren't things that can definitively be said to exist. Our
mind considers the possibilities, then as what will happen unfolds, we are left
with some of the emotional residue. Times imagined spent together, anticipation,
hope, dread and reflecting on the unexpected that occured in between -- these
spur your brain on with mental energy that is forward-looking towards the future
(or at least a need for mental energy to coordinate social stuff). The past is
prologue for many futures unfolding simultaneously; we forget as quickly as
their possibility bubbled into our heads. What could have happened (for
better/worse) and also the futures in front of me exert gravity on the mind. I
have noticed that the need to plan for the short-term future is more powerful
than medication. However, the conscious mind doesn't usually consider it's
experience of the future as "tangible" objects of narrative that definitively
happened. Those existential components are amorphous ... but "people remember
how you made them feel."

When MSM, social media, notification and tiktoks drain your attention, pulling
you from the "present day;present time", it attenuates the magnitude of these
existential factors.

I'm not saying that people are making me feel bad. It's my own life's
constraints, coupled with the extended "white noise" torture of nothing
happening all day every day, being in the same basement with the same dreams and
same traumas, as most prior relationships whither away -- while I'm frequently
getting many snapchat notifications from old friends living in about 20 other
states. This and so many other things are like a "Chinese Water Torture' that
reminds me of what my life used to be like. That sounds selfish, but it is what
it is. They're probably better off not worrying about things they can't do
anything about. It's also apparently exigent that I never get attention for the
many talents I have or could have. I'm constantly reminded just how pointless
everything is.

So, if I just need to stop struggling and learn to live at minimum wage, why
don't I? Because it's hard for me to understand why none of the startups, tech
ideas or hobbies that I've struggled to learn has ever even resulted in a
collaboration with other people.

I need to get away from this place.

*** The Memory Hole

And so ... what if it is the government that's screwing wth your life? Well,
they don't really need to. fortunately, social media provides a mechanism for
people to label each other. The labels can potentially be viral. So... just
don't say anything, right? It's that easy! And all you have to do is be nervous
about any opinions that ever come up in conversation.

People in America simply do not understand how /terrified/ they are. They don't
experience this fear consciously, so it acts more like anxiety, which is
experienced by the mind as something external that requires you to turn your
attention inwards. The spatial and temporal closures that your mind binds its
thoughts to? These fluctuate when you are anxious: you start thinking in many
directions at once and many feelings/thoughts simultaneously compete for your
attention. This pulls you away from the present.

#+begin_quote
A [[https://en.wikipedia.org/wiki/Closure_(computer_programming)][closure]] is the list of bindings that are in-scope for a program. Some are
local and redefined, others are more global. For cognition, your mind extracts
information, symbols and parameters from its experience. As thoughts flow, they
string together bindings for symbols in your thoughts & memories to exterior
bindings which are usually constrained to some region of space & time (hence the
spatial and the temporal). Your brain doesn't use a compiler, isn't a Von
Neumann machine, doesn't evaluate source code... etc. But it absolutely does
have operate with a these closures -- there are likely small scale structures
close to the center of the brain loosely analogous to the LLM attention heads.
#+end_quote

For me, anxiety is not experienced as an overwhelming thing ... The uncertainty
over provenance of information causes people to become increasingly worried
about some content they see online. The anxiety over how info/data can leak from
social media to prod you with insinuation.

IMO people are so unbelievably uptight about content online. I vent about my
feelings (for years), rarely does anyone directly interact with me about it, but
I can never shake the social emptiness. When I live in other cities, it's easier
to access more around me, but it feels like people here avoid me because they've
been programmed by anecdotes or shit maybe even all my posts that no ever
liked/interacted with. Oh and the algorithm nukes your social media reach if you
include too many keywords at once. That: on top of being boring content that is
scrolled past with a palpable indifference that AI & Newsfeed are trained to
censor.

So keep your interests strictly IQ 105! Watch the speed limit son. do you want
to get a ticket for Algebra Two without a license? I mean jesus christ how the
fuck am i ever supposed to learn anything complicated.

some average idiots can start a never ending cascade of bullshit where they are
mercilessly trying to stomp out a fire, but have ZERO ability to distingush a
cigarette butt from a forest fire from a patent /which probably already exists./

#+begin_quote
it was definitely not Billy Bob's first rodeo and wouldn't be his last.

But what Billy Bob did not quite understand is that philosophy is legal and math
is normal and that some highly technically is, yes, quite a bit like DMT in it's
ability to subject the mind to unprecendented novelty. Billy bob never did like
reading. He didn't even like big words.

#+end_quote

... idk. it's just so dumb how people ignorantly don't give a fuck. I stopped
caring a long time ago, whether people would understand. However, as long as The
System says you are smart, then dumb people will pay you a lot of respect
(whatever it's worth ... i wouldn't know would I?). And they'll probably leave
you alone. Dumb people don't pick these kinds of fights with someone who is more
strongly supported by The System ... but they still feel small and dumb. I guess
patriotism feels good when you can't understand just how much of one weak
person's future that your detached & complacent ignorance ruined.

These are the people that wouldn't bother asking ChatGPT about it. If you say
it (wutever it is), they'll treat you like a heretic. If ChatGPT says it ...
well they never could read too good anyhow.

What is absolutely ridiculous is when your identity needs to be surpressed or
stomped out. Like it's a fucking necessary objective of an epistemic game. Do
you know how insane that is?

Normally, it should be basically impossible for anyone to single-handedly ruin
someone's social life (and it pretty much is 99.9% of the time) However, once
enough of the sociophysical metrics become highly abnormal (esp. those regarding
connectivity), then a small about of resistence or influence can actually do a
lot of harm ... though probably not as much are as total indifference or a lack
of help.

** "Privacy" and Formation/Propagation of Norms

+ What is done in private impairs normalization and thus impairs consensus on
  norms. Sex and drugs are two examples where "things that happen in Vegas are
  supposed to stay in Vegas." If one relies heavily on reasoning about norms
  (see above), then it's difficult for that to be effective.
+ This plays out differently for those on the outside looking in vs. those
  inside looking out. f your personality and rationale do not overly rely on
  norms, then things done in private can have a strong mutagenic kind of effect
  on your mind (... or at least on your perception of norms). The effect can be
  high-magnitude response that eventually either causes reinforcement,
  unraveling or ablation of conditioning

** Dysnormalization (on a small scale)

I think it's imporant to understand just how =SOCIAL= this can be. Though it
definitely may affect one's =PSYCHE=, there is actually nothing that needs to
happen to your mind in order to affect your life in a pretty severe way.
Granted, given enough normalizing force in someone's life and enough potential
sociophysical interactions, then a person who has been mischaracterized (even
via mis/disinformation) will usually recover from the social damage given enough
opportunities to turn it around.

However, as noted above, many people's rationalization relies on consensus and
norms. They follow the crowd.

+ When there is less explicit information: then other signals dominate rational
  and logic. These may be implicit (situational, instinctual) or aggregate
  (norms & consensus)
+ In the absense of a healthy local social neighborhood (in the graph theoretic
  sense), the flow of information may be completely stymied. An isolated
  subgraph is _not_ connected to the other subgraphs.
+ When social connections are consistently disrupted -- your "GRE tunnels are
  flapping" so to speak, which for networking may cause very strange bugs --
  - e.g.: solitary confinement given intermittently, which is /more/ humane, i
    suppose. less extreme examples like weekends in jail can also be
    disorienting because you're cycling through patterns of connectivity to
    people and through the practicality of options.
+ If social connections convey heavily distorted information (strong bias), this
  can easily lead you to improperly read norms/consensus or misinterpret
  beliefs/knowledge.

So to summarize:

+ The interactions between nodes are limited by salience & bandwidth. Sometimes
  there are overt rules/structures governing communication/interactions.
+ The state of the social graph enables information flows. Long-term patterns of
  connectivity give rise to a personal history of interactions,
  expectations/assumptions and regularity/seasonality. disruptions in
  regularity/pattern can enable change.
+ Connectivity may not require proximity, but proximity would tend to promote
  higher bandwidth experiences, yielding memories with more comprehensive &
  robust patterns of memory encoding. Furthermore, people
+ perceptions of people and social graph conditions are likely to change until
  stabalization, after which these structures/beliefs need fairly high-magnitude
  changes to permit many social nodes to form new beliefs.
  - a useful physics metaphor: energy involved in breaking AND forming crystal
    bonds. rarely does change of crystalization state not involve energy.
  - once bonds are formed, energy is required to break them. if the system's
    material provides a local energy minimum in various crystal forms, these are
    basically energy wells (i.e. you have to nudge the material at small & large
    scales to push the system out of the energy wells).
  - However, if there is no crystalization present in a solution/material that
    readily forms one or more, then kinetic interactions may cause it to readily
    gravite towards that.
  - so, even though interactions are random, factors like social valence and
    attraction/repulsion create stability that is likely to last for more time
    than was required for the patterns (or beliefs) to emerge.
