:PROPERTIES:
:ID:       36f12cfc-408b-4c63-90a5-b443838367b4
:END:
#+TITLE: Python: Mise, UV, Jupyter and Kernels
#+CATEGORY: slips
#+TAGS:
* Roam
+ [[id:2049060e-6755-4a64-b295-F7B563B41505][NixOS]]
+ [[id:b4c096ee-6e40-4f34-85a1-7fc901e819f5][Python]]
+ [[id:cf847bc5-31f7-4bb8-8324-7680a8f2953d][Shell]]

* Resources

** Cookiecutter
+ [[https://github.com/fpgmaas/cookiecutter-uv][fpgmaas/cookiecutter-uv]]
+ [[https://cookiecutter.readthedocs.io/en/stable/][cookiecutter docs]]
  
** ROCm
+ [[https://rocm.docs.amd.com/en/latest/reference/env-variables.html][ROCm environment variables]]
+ [[https://rocm.docs.amd.com/en/latest/conceptual/file-reorg.html][ROCm Linux FHS Reorganization]] (... and it breaks lol oh boy)
*** Libraries
+ [[https://rocm.docs.amd.com/en/latest/compatibility/ml-compatibility/tensorflow-compatibility.html][TensorFlow support in ROCm]]
+ [[https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/tensorflow-install.html][TensorFlow on ROCm Installation]]

*** Misc
+ [[https://web.archive.org/web/20250117000431/https://theholytachanka.com/posts/setting-up-resolve/][theholytachanka.com: setting up davinci resolve]]

** NixOS

+ [[https://github.com/NixOS/nixpkgs/blob/fba245c24ffe3733ad7ccc1e377f6c0e39b8b3e1/pkgs/development/rocm-modules/6/clr/default.nix#L36][./pkgs/development/rocm-modules/6/clr/default.nix#L36]] contains an example of
  what a ROCm development environment should look like.

#+begin_quote
Source code _is_ best the docs... and you really wouldn't want it any other way.
it sucks when you're searching github bc HTTP is slooowww, esp with javascript.
fortunately that's not a problem here
#+end_quote

=onnxruntime= ([[https://github.com/NixOS/nixpkgs/blob/fba245c24ffe3733ad7ccc1e377f6c0e39b8b3e1/pkgs/by-name/on/onnxruntime/package.nix#L175-L188][pkgs/by-name/on/onnxruntime/package.nix#L175-L188]]) contains a
fairly complete list of rocm packages needed for building foreign packages

*** hardware.graphics.extraPackages

WTF is [[https://discourse.nixos.org/t/what-exactly-does-hardware-opengl-extrapackages-influence/36384/2][hardware.graphics.extraPackages]]? There are almost zero references =nixpkgs=
to this mythical thing... it adds packages to a =/run/opengl-drivers= path, which
is great bc now I know where all these AMD libraries are going (not to
=/opt/rocm=)

Ultimately, =/opt/rocm/hip -> /nix/store/a1b2c3d4= and many =/run/opengl-driver/bin=
link to the same store path.

** Jupyter
*** [[https://marimo.io/][Marimo]]: "The future of python"

... oh that's cute. it's a _literal pluto clone_. Thanks, but i'll pass. Julia had
macros. ytf do idiots run the world?

Pluto's HTML5 elements weren't super fantastic anyways. They were great... but
very, very "scrolly" if you know what i mean. Can we just all agree that DatGUI
is the One True GUI GOAT?

And Marimo's shortcuts, lack of editor functionality? I guess I don't know that
for real. Just from an instantaneous prompt to the "programmer LLM" in my brain.
Domain problems. Can't simplify that. AVOID THE DOMAIN.

** Python

* Notes
** Setup
*** Omarchy

** ROCm

*** CL Runtime

These bins

| amdclang  | amdclang++             | clinfo                    |            |
| hipcc     | hipcc.pl               | hipcc_cmake_linker_helper |            |
| hipconfig | hipdemangleatp         | hipconfig.pl              | hipvars.pm |
| rocminfo  | rocm_agent_enumerator  |                           |            |
| roc-obj   | roc-obj-extract{,.bat} | roc-obj-ls{,.bat}         |            |

These libs

| libamdhip64.so | libamdocl64.so        |
| libOpenCL.so   | libcltrace.so         |
| libhiprtc.so   | libhiprtc-builtins.so |

A bunch of headers and =include/hip-clang=

*** rocm-installer.run

+ [[https://github.com/ROCm/rocm-installer-runfile][ROCm/rocm-installer-runfile]] and [[https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/rocm-runfile-installer.html][doc]]

This is a self-extracting installer for linux platforms intended for offline
environments. It runs some sanity checks: =offline-installer-contained/test=

The build for this (and most scripts) have a shortlist of distributions. It
fails out otherwise.

**** =amd-smi-test.sh=

#+begin_src shell
amd-smi version
amd-smi metric -tc
amd-smi static --asic --board

# then
python -m pip list | grep amd-sm # (expecting these already isntalled)
#+end_src  

**** =rocdecode-test.sh=

+ Finds an installed =*/rocm-*/.info/version=
+ then extracts major/minor/patch from it.
+ Then it detects os & package mgr, installs some packages
+ Runs video decoding tests, etc.
+ Then cleans up... (only if successful: test tests are meant for CI)

**** rocm-examples-test.sh

+ Same version detection, similar flow, different dependencies.
+ Clones [[https://github.com/ROCm/rocm-examples.git][ROCm/rocm-examples]], tries building, then runs their tests.
+ Conveys how =cmake= and =ctest= should work using their toolchain.

** Nixos
*** Environment

**** runpath_to_rpath.py

I'm not sure this is needed, but i've seen it in many configs. In any case, it
only sets up HIP, but doesn't set up the runtime.

#+begin_src nix
  systemd.tmpfiles.rules = [
    "L+ /opt/rocm/hip - - - - ${pkgs.rocmPackages.clr}"
    # "L+ /opt/rocm/hip - - - - "/opt/rocm/hip2" # overwrite to remove the mount
  ];
#+end_src

=/nix/store/......rocm-core-6.4.3/libexec/rocm-core/runpath_to_rpath.py= gets
called to find =rocm.cfg= and only if it doesn't find it does it check
alternatives lik environment like =ROCM_PATH=. its doing this to ensure LLVM links
everything consistently (it needs to know what =ROCM_PATH= will be by link time)

I think =systemd.tmpfiles.rules= and =ROCM_PATH= above are only needed when running
FHS packages on the system which can't have =ROCM_PATH= shimmed.

=lsof -p $(pgrep blender | head -n1)=

#+begin_example text
.blender- 821986 /dev/dri/renderD128
.blender- 821986 /nix/store/...-llvm-19.0.0-rocm-lib/lib/libLLVM.so.19.0 (path dev=0,31)
.blender- 821986 /nix/store/...-rocm-runtime-6.4.3/lib/libhsa-runtime64.so.1.15.0 (path dev=0,31)
.blender- 821986 /nix/store/...-rocm-comgr-19.0.0-rocm/lib/libamd_comgr.so.3.0.0 (path dev=0,31)
.blender- 821986 /nix/store/...-clr-6.4.3/lib/libamdhip64.so.6.4.43484 (path dev=0,31)
#+end_example

This implies that some other magical process is connecting the link-ed to the link-ee

***** On Second thought

esp. since [[https://rocm.docs.amd.com/en/latest/conceptual/file-reorg.html][ROCm Linux FHS Reorganization]] (and also, =rocm-toolchain= contains
clang, etc), to build link foreign packages via =nix-ld= into a NixOS system's
rocm, the =systemd.tmpfiles.rules= thing does make sense. it doesn't necessarily

one problem is that you'd need to regenerate environments outside of NixOS if
your AMDGPU environment changes...

**** Verification

Is your GPU there?

#+begin_src shell
rocminfo | grep -i "Marketing Name:"
#+end_src

#+begin_src shell :results output verbatim
clinfo | grep -i version
#+end_src

#+RESULTS:
:   Platform Version                                OpenCL 2.1 AMD-APP (3649.0)
:   Device Version                                  OpenCL 2.0 
:   Driver Version                                  3649.0 (HSA1.1,LC)
:   Device OpenCL C Version                         OpenCL C 2.0 
:   ICD loader Version                              2.3.4

#+begin_src shell :results output verbatim
amd-smi version | tr '|' '\n'
#+end_src

#+RESULTS:
: AMDSMI Tool: 25.5.1+unknown 
:  AMDSMI Library version: 25.5.1 
:  ROCm version: N/A 
:  amdgpu version: Linuxversion6.17.9-zen1(nixbld@localhost)(gcc(GCC)14.3.0,GNUld(GNUBinutils)2.44)#1-NixOSZENSMPPREEMPT_DYNAMICTueJan100:00:00UTC1980 
:  amd_hsmp version: N/A

** Guix

Equivalents

| Guix                 | Nix                         |                          |
|----------------------+-----------------------------+--------------------------|
| rocm-bandwidth-test  |                             |                          |
| rocm-opencl-runtime  |                             |                          |
| roct-thunk-interface |                             | deprecated               |
| rocm-cmake           |                             |                          |
| rocm-comgr           |                             |                          |
| rocm-device-libs     |                             |                          |
| rocm-hip-cpu         |                             |                          |
| rocminfo             |                             |                          |
| rocr-runtime         |                             |                          |
| llvm-for-rocm        | rocmpackages.llvm.llvm, ... | a hidden package in guix |



#+name: rocmpkgs
#+begin_src shell :results output verbatim
guix search 'rocm' \
    | guix shell recutils -- recsel -P name \
    | grep -vE '^(procmail|amd-smi)' \
    | sort | uniq | grep -e '\S'
#+end_src

#+RESULTS: rocmpkgs
: rocm-bandwidth-test
: rocm-cmake
: rocm-comgr
: rocm-device-libs
: rocm-hip-cpu
: rocminfo
: rocm-opencl-runtime
: rocr-runtime
: roct-thunk-interface

#+name:
#+headers: :var pkgs=rocmpkgs
#+begin_src shell
guix graph --max-depth=2 --type=reverse-package $pkgs | dot -Tsvg
# guix graph --max-depth=2  $rocmpkgs | dot -Tsvg
#+end_src

#+RESULTS:
[[file:img/guix-rocm-revpkgs.svg]]

#+name: rocmdeps
#+begin_src shell :results output verbatim
guix search '^roc[mrt]' \
    | guix shell recutils -- recsel -P name,dependencies \
    | tr ' ' '\n' | sed -E 's/(.*)@.*$/  \1/g'
    | sort | uniq | grep -e '\S'
#+end_src

#+RESULTS: rocmdeps
#+begin_example
rocm-cmake
  git

rocr-runtime
  libdrm
  libelf
  llvm-for-rocm
  numactl
  pkg-config
  rocm-device-libs
  roct-thunk-interface
  xxd

rocminfo
  kmod
  rocr-runtime

rocm-opencl-runtime
  glew
  mesa
  numactl
  opencl-headers
  opencl-icd-loader
  rocm-comgr
  rocr-runtime

rocm-device-libs
  llvm-for-rocm

rocm-comgr
  llvm-for-rocm
  python
  rocm-device-libs

r-rocr
  r-gplots
  r-knitr
  r-testthat

roct-thunk-interface
  gcc
  libdrm
  numactl
  pkg-config

rocm-hip-cpu


rocm-bandwidth-test
  rocr-runtime

amd-smi
  libdrm
  python
#+end_example


#+begin_src shell
pkgs=(rocm-opencl-runtime rocm-comgr rocr-runtime rocm-bandwidth-test rocminfo \
    roct-thunk-interface rocm-device-libs rocm-cmake rocm-hip-cpu)

guix shell ${pkgs[@]} -- tree -l '$GUIX_ENVIRONMENT'
# tree -J -l $GUIX_ENVIRONMENT/{lib,bin,libexec}
#+end_src

* Projects

** simple setup

** Torch ROCm

Project Name

#+begin_src emacs-lisp
"testtorchuv"
#+end_src

clone the torch repo

#+begin_src shell :var p=testtorchuv
# clone to ./testtorchuv
git clone https://github.com/pytorch/examples $p
#+end_src

add =pyproject.toml= to project root

#+begin_example toml
[project]
name = "testtorchuv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "numpy>=2.3.5",
  "torch", # unpinned (bc 15G! w/o hard links OMFG SMH LOL)
  "torchvision"
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.4"
explicity = true

[tool.uv.sources]
torch = [{ index = "pytorch-rocm" }]'
#+end_example

copy a template =main.py=

#+begin_src python
def main(): print("Hello from uvtorch!")
if __name__ == "__main__": main()
#+end_src

ensure mise is loaded

#+begin_src shell :var p=testtorchuv
cd $p && uv run main.py

cd ..
cd $p

# check ROCM_PATH (wasn't required for me, strangely ... dammit can i ever get a
# clue from another programmer?)
echo $ROCM_PATH
#+end_src

Ensure deps are installed/loaded

#+begin_src shell :var p=testtorchuv
uv pip install torch --torch-backend=auto
uv pip install torchvision --torch-backend=auto
UV_TORCH_BACKEND=auto uv pip install torch
#+end_src

Run the =mnist= example

#+begin_src shell
# from root of repo
python mnist/main.py --save-model # saves model to mnist_cnn.pt

# Test set: Average loss: 0.0258, Accuracy: 9918/10000 (99%)
#+end_src

** Tensorflow ROCm

#+begin_src shell
# TODO: set :dir and make org-babel callable?
p=my-uv-project
uv init $p && cd $p

# need to run main.py first, otherwise .venv hasn't been created
uv run main.py

# need to jump out/in, so mise reloads path
cd .. && cd $p

rocmrepo=https://repo.radeon.com/manylinux/rocm-rel
tensorflow-rocm==[wheel-version] -f [repo] --upgrade
uv add --dev ipykernel
#+end_src



** Layout

#+begin_example
/data/lang/python/kernels
/data/lang/python/kernels/k1/.venv
/data/lang/python/kernels/k1/pyproject.toml
/data/lang/python/kernels/k1/mise.toml
/data/lang/python/kernels/k2/.venv
/data/lang/python/kernels/k2/pyproject.toml
/data/lang/python/kernels/k2/mise.toml
/data/lang/python/projects
/data/lang/python/projects/p1/.venv
/data/lang/python/projects/p1/pyproject.toml
/data/lang/python/projects/p1/mise.toml
/data/lang/python/projects/p2/.venv
/data/lang/python/projects/p2/pyproject.toml
/data/lang/python/projects/p2/mise.toml
/data/lang/python/projects/tries
/home/dc/.jupyter/lab/user-settings
/home/dc/.jupyter/lab/workspaces
/home/dc/.local/share/jupyter/kernels
#+end_example


#+begin_example
.
├── data
│   └── lang
│       └── python
│           ├── kernels
│           │   ├── k1
│           │   │   ├── mise.toml
│           │   │   ├── pyproject.toml
│           │   │   └── .venv
│           │   └── k2
│           │       ├── mise.toml
│           │       ├── pyproject.toml
│           │       └── .venv
│           └── projects
│               ├── p1
│               │   ├── mise.toml
│               │   ├── pyproject.toml
│               │   └── .venv
│               ├── p2
│               │   ├── mise.toml
│               │   ├── pyproject.toml
│               │   └── .venv
│               └── tries
└── home
    └── dc
        ├── .jupyter
        │   └── lab
        │       ├── user-settings
        │       └── workspaces
        └── .local
            └── share
                └── jupyter
                    └── kernels
#+end_example

** NixOS
*** Jupyter Envs

+ [[https://www.reddit.com/r/NixOS/comments/1ojtcmm/comment/nmeex42/?context=3][r/NixOS: Python uv + Nix-ld: "RuntimeError: Found no NVIDIA driver on your system"]]
  - [[https://github.com/Naxdy/nix-flake-templates/blob/main/python-nn/flake.nix][uv2nix: 250 line template for flake.nix]] yo dawg, i heard you like pins

user wants to run [[github.com/comfyanonymous/ComfyUI][ComfyUI]], but restoring configuration across install states for
applications that have graph-based configureation is at least as hard as
programming it (hardness as in spatial computation)

anyways, i like dragging connections between nodes in my wireplumber audio graph
(i don't though). nlg OP sounds smart though. but data science really comes down
to who can afford a ferrari. it's not really a test of it's not exactly a battle
of wits. i'm honestly pretty happy to have not spent a ton of effort learning
these tools. i can't say i'm regret-free for not using it at all though.

*** tweag/jupyenv

Examples in [[https://github.com/tweag/jupyenv/tree/main/examples][examples/$lang]]

+ [[https://github.com/tweag/jupyenv/blob/main/modules/default.nix#L15-L60][Options for =jupyterlab= modules/default.nix]]
+ [[https://github.com/tweag/jupyenv/blob/main/modules/kernel.nix#L12-L84][Options for =kernel.*= and =kernel.python= modules/kernel.nix]]
+ [[https://github.com/tweag/jupyenv/blob/main/modules/kernels/haskell/default.nix#L63-L100][Options for =kernel.haskell= modules/kernels/haskell/default.nix]]
+ [[https://github.com/tweag/jupyenv/blob/main/modules/kernels/julia/default.nix#L73-L104][Options for =kernel.julia= modules/kernels/julia/default.nix]]
  
| bash       | minimal |         |         |        |
| c          | minimal |         |         |        |
| dotnet     | csharp  | fsharp} |         |        |
| elm        | minimal |         |         |        |
| go         | minimal |         |         |        |
| haskell    | minimal |         |         |        |
| javascript | minimal |         |         |        |
| julia      | minimal |         |         |        |
| nix        | minimal |         |         |        |
| ocaml      | minimal |         |         |        |
| postgres   | minimal |         |         |        |
| python     | minimal | native  | science | stable |
| r          | minimal |         |         |        |
| rust       | minimal |         |         |        |
| scala      | minimal |         |         |        |
| typescript | minimal |         |         |        |
| zsh        | minimal |         |         |        |

* Jupyenv

** Quick Start

#+begin_src shell
d=$(mktemp -d)
nix flake init --template github:tweag/jupyenv
#+end_src

This generates the following flake

#+begin_src nix
{
  description = "Your jupyenv project";

  nixConfig.extra-substituters = [
    "https://tweag-jupyter.cachix.org"
  ];
  nixConfig.extra-trusted-public-keys = [
    "tweag-jupyter.cachix.org-1:UtNH4Zs6hVUFpFBTLaA4ejYavPo5EFFqgd7G7FxGW9g="
  ];

  inputs.flake-compat.url = "github:edolstra/flake-compat";
  inputs.flake-compat.flake = false;
  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  inputs.jupyenv.url = "github:tweag/jupyenv";

  outputs = {
    self,
    flake-compat,
    flake-utils,
    nixpkgs,
    jupyenv,
    ...
  } @ inputs:
    flake-utils.lib.eachSystem
    [
      flake-utils.lib.system.x86_64-linux
    ]
    (
      system: let
        inherit (jupyenv.lib.${system}) mkJupyterlabNew;
        jupyterlab = mkJupyterlabNew ({...}: {
          nixpkgs = inputs.nixpkgs;
          imports = [(import ./kernels.nix)];
        });
      in rec {
        packages = {inherit jupyterlab;};
        packages.default = jupyterlab;
        apps.default.program = "${jupyterlab}/bin/jupyter-lab";
        apps.default.type = "app";
      }
    );
}
#+end_src

Then edit =kernels.nix=, so

#+begin_src nix
{ pkgs, ... }:
{
  kernel.python.basic = {
    enable = true;
    runtimePackages = [
      pkgs.coreutils
    ];
    env = pkgs.python3.withPackages (
      ps: with ps; [
        ps.ipykernel
        ps.numpy
        ps.scipy
        ps.matplotlib
      ]
    );
  };
}
#+end_src

It looks like it works for simple things. For more advanced scenarios, it would
require a lot of overrides. The =pyproject= kernel works for more native deps, I think

But for now, I'm getting this error, which has been unaddressed for a while,
probably bc it's more difficult than it looks ... which is sad.

#+begin_example
… while calling the 'throw' builtin
  at /nix/store/lv4kcr2y4b9k4ynhkga157507zxf372b-source/pkgs/development/compilers/rust/make-rust-platform.nix:84:23:
    83|   # Added in 25.05.
    84|   fetchCargoTarball = throw "`rustPlatform.fetchCargoTarball` has been removed in 25.05, use `rustPlatform.fetchCargoVendor` instead";
      |                       ^
    85| }
    
error `rustPlatform.fetchCargoTarball` has been removed in 25.05, use `rustPlatform.fetchCargoVendor` instead
#+end_example

** Advanced

*** AMD

* NixOS ROCm Environments


#+begin_src shell
 
#+end_src


migraphx
hiprand 
hipfort 
rocprim 
mscclpp 
hipblas 
rpp-hip 
rocblas 
rocmlir 
rocrand 
tensile 
rocwmma 
rpp-cpu 
hipfft 
amdsmi 
hipcub 
miopen 
rocfft 
rocgdb 
hipify 
hsakmt 
hiprt 
clang
hipcc 
half 
rccl 
rpp 
mpi 
clr 
rdc 
