:PROPERTIES:
:ID:       2ffb2e0e-811e-4b90-a0b4-0a0c562cd440
:END:
#+TITLE: Rant: Idiot Proof Tools Are The Worst
#+CATEGORY: slips
#+TAGS:  
* Roam
* Notes

What sucks is having to drive this fucking moped (and it's not even a ZMQ moped)

** Idiot Proof

I cannot stand the "idiot-proof" office app scripting. These languages _should
not_ be idiot proof.

+ e.g. It's unclear whether installing a Workspaces plugin would allow that
  plugin permissions to a specific document or to just everything. If you're
  an idiot in a rush to impress your boss, you don't care, do you? (Just don't
  tell them you installed a plugin)
+ The "idiot-proof" nature of the scripting language makes it simple to use,
  but, basically, it's a foot-gun. An idiot-proof interface that
  oversimplifies lends itself to creating code thats:
  - hacky & overly-complicated in how it handles implementation details
  - which are excruciatingly difficult to discover, if you even bother.

In organizations, the opaque nature of "idiot-proof" tools creates small
"silos" of expertise in document manipulation, where some "expert" in "dogshit
  programming" carves out their territory

+ that's a fairly extreme case: simple stuff is very useful and some
    expertise can be very valuable (you can advise other employees on "where
    be dragons" since they fucking be there.) 

These tools are just such a massive risk to manage permissions & access that
it's just omfg holy shit why would you bother? any "expert" who uses these tools
_for "productivity"_ is a massive risk

The microsoft tools have been a perpetual source of "zomfg i had no idea the
spreadsheet could install a rootkit on the CFO's personal laptop"

For academic research or small operations, it makes sense, given the users know
enough about their tools to avoid the foot-guns and foot-nukes.

JUST. USE. SQL -- _NOT_ "ACCESS" -- JUST SQL. Your fucking MBA should have
included some education on that? Right? And if it did not, what the fuck is
wrong with you? Most skilled professionals I've encountered know a bit about a
database. They're decent DBD's, but not necessarily DBA's.

+ You can run these services on your laptop.
+ Then you can convert tabular data into a spreadsheet for visualization. YES,
  it does require a tiny bit of "Export to CSV" and "Drag the CSV to this
  folder" and "Convert to Excel"
  - Y U NO POWERSHELL? What the fuck? That's actually a decent tool. But you're
    not intelligent. You're just a bourgeoisie patsy parasite -- and imminantly
    replaceable.

This is obviously a hyperbolic rant. Small usages of these tools are fine and
just because you don't have access to my expertise (or programming expertise)
doesn't mean it applies to you. But programming is the meta-skill. Learning it
is how you:

+ learn to manipulate data for arbitary ETL
+ learn to reason abstractly about abstract processes
+ think methodically about org-charts and operations as though they're programs
+ etc,etc,etc
