:PROPERTIES:
:ID:       d4b92df9-eff7-42f9-911d-0e13175da4bf
:END:
#+TITLE: VyOS: Staying On Top Of CVEs
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:5aa36ac8-32b3-421f-afb1-5b6292b06915][VyOS]]
+ [[id:e967c669-79e5-4a1a-828e-3b1dfbec1d19][Route Switch]]
+ [[id:ea11e6b1-6fb8-40e7-a40c-89e42697c9c4][Networking]]
+ [[id:23716a1b-7937-4cd1-923d-9adae1286601][Debian]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]
+ [[id:29d8222b-618f-454e-8a76-6fa38f8ff1f6][Blue Team]]

* Resources
** Debian

[[https://security-tracker.debian.org/tracker/][security-tracker.debian.org]]

+ [[https://security-tracker.debian.org/tracker/CVE-2026-43503][CVE-2026-43503: DirtyClone]], an IPSec vuln when user namespaces are on

** VyOS


* Notes


** Validating

*** Last ISO Build

VyOS builds its kernels using =lb=.

From a vyos/vyos-build checkout:

#+begin_src shell
# check the debian dist. version (This should remain constant for awhile)
grep -re LB_DISTRIBUTION # it's Debian 12: Bookworm
#+end_src

Run =ssh muhrouter uname -a= and note the kernel version. Cross check it against
Debian's =security-tracker= notes on the CVE... unfortunately, VyOS uses
=linux-kbuild=, but not the =linux= package. Usually =dpkg -l | grep linux= would show
a corresponding package version... but it's not there.



*** Kernel =kconfig=

.... hmmm

** Updating

Since my ISOs include a few extra packages, I need to rebuild the image, instead
of downloading the main nightly ISO for the VyOS rolling release.

From a vyos/vyos-build checkout:

#+begin_src shell
git pull
docker pull vyos/vyos-build:latest

# TODO: rebuild image
#+end_src

No =dd= required. Load the ISO onto a flash drive or copy to the system with =scp=.

Login with ssh and =add system image /path/to/newbuild.iso=
