:PROPERTIES:
:ID:       70b5392c-3407-4010-8160-721d4d945432
:END:
#+TITLE: Linux: First Attempt At Structuing An Ontology For Core Linux Repos
#+CATEGORY: slips
#+TAGS:

Like [[id:c7b74513-16fe-4f50-8cae-ed8b05ef3ff1][Linux: Perf and Tracing]], these notes were squirreled away in
[[https://github.com/ectorepo/ectorepo][ectorepo/ectorepo]]... It didn't go that well: immediately sidetracked by trying
to grok an "ontology" from SPDX... using its software categories probably. I
likely planned to mirror something like that to plan things.

The folder structure folder.

* Roam
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]
+ [[id:8fb0a586-9c0f-4f36-b1ab-dc5c26681d15][OSS: Open Source]]
+ [[id:8a037e1b-0673-4353-9c35-c1e7d15b04e5][Copyright]]
+ [[id:563e2fb8-df10-485e-bc41-3d56d2bcccda][SBOM]]

* Old Notes

#+begin_example org
#+title:     Ectorepo: GNU/Linux
#+author:    David Conner
#+email:     noreply@te.xel.io
#+PROPERTY: header-args+ :comments none
#+end_example

It's difficult to determine what should be in this manifest and what should not.
There are already [planned] manifests for KDE, Garuda, the Linux Kernel and
other related projects/categories. This issue itself is similar to the ontological issues resolved by SPDX, OWL and RDF described below.

What is in Linux that is clearly not better categorized as part of:

+ Linux kernel development?
+ A specific distribution?
+ A Window Manager or Desktop Environment?
+ X11 or Wayland?
+ Essential GNU software tools?

What makes the most sense is to define this repo as containing the last
category, plus anything that isn't readily contained within the others while
also being considered a staple of Linux distributions. For now, I may include
information about some alternatives to the Linux kernel or in the traditional
Linux ecosystem, generally, before splitting that off.

Eventually everything could move, as the GNU tools themselves have alternatives:
whether one-to-one replacements (posix compatible) or tools whose usage/API
overlaps with established needs for computering systems or tools that could
invalidate those needs entirely.

* New Developments

** SPDX

3.0 is the first ISO version of SPDX. It codifies a working ontology within
which software packages can be completely modeled. SPDX bundles information that
conveys:

+ Components of a software package
+ Tracking of software package provenance
+ Licensing of the package and its components (enabling validation)

+ SPDX :: Software Package Data Exchange
  - [[https://spdx.org/rdf/ontology/spdx-2-2/][SPDX spec]] definied defined with RDF ontology modeling
  - Interesting SPDX docs:
    + 3 [[https://spdx.github.io/spdx-spec/v3-draft/terms-and-definitions/][Terms and Definitions]]
    + 5 [[https://spdx.github.io/spdx-spec/v3-draft/composition-of-an-SPDX-document/][Composition of an SPDX Document]]
    + 9 [[https://spdx.github.io/spdx-spec/v3-draft/snippet-information/][Snippet Information]]
    + 7 [[https://spdx.github.io/spdx-spec/v3-draft/package-information/][Package information]]
    + 11 [[https://spdx.github.io/spdx-spec/v3-draft/relationships-between-SPDX-elements/][Relationships between SPDX elements]]
    + The appendices are also useful

+ RDF :: W3C's Resource Description Framework
  - see the repo [[https://github.com/w3c/EasierRDF][w3c/easierRDF]] for clearer descriptions
+ OWL :: W3C's [[https://www.w3.org/OWL/][Web Ontology Language]]
  - wikipedia has a more dense intro

*** SPDX categories

These are the categories, but they're specific to packaging

From https://spdx.github.io/spdx-spec/v3.0.1/rdf/spdx-model.ttl

rdf:spdx/3.0.1/terms/Software/SoftwarePurpose

| archive       | documentation   | library         | requirement   |
| bom           | evidence        | manifest        | source        |
| configuration | executable      | model           | specification |
| container     | file            | module          | test          |
| data          | filesystemImage | operatingSystem |               |
| device        | firmware        | other           |               |
| diskImage     | framework       | patch           |               |
| deviceDriver  | install         | platform        |               |

* Emerging Distros
** Guix System
** Gentoo

[[https://wiki.gentoo.org/wiki/Distributions_based_on_Gentoo][Info on Gentoo-based distributions]]

*** [[https://wiki.redcorelinux.org/doku.php/about_redcore_linux][Redcore OS]]
A security focused distro with a hardened kernel, built from Gentoo Stage 3. Uses its own Sisyphus package manager alongside Portage.

... But I ran into errors during and after an install of Redcore on a 2011 Macbook pro. Two attempts. Not a big deal, since I'm not really using that computer, but I didn't have time to look into it.

*** [[https://docs.clip-os.org/][CLIP OS]]
A security-focused distro from ANSSI, a French cybersecurity institution.

*** [[https://www.mocaccino.org/docs/][Mocaccino OS]]
Uses the Luet package manager (which serves dependencies via Docker)... very interesting.

*** [[https://www.sabayon.org/][Sabayon Linux]]
A beginner-friendly gentoo. Uses its own Entropy package manager alongside
Portage.

*** [[https://gentoostudio.org/][Gentoo Studio]]
A build of Gentoo with audio features cranked up to eleven.

* Package Managers

** Red Hat
** Debian
*** Apt
** Arch
*** Pacman
** Gentoo
*** Portage
*** Sisyphus
*** Entropy
** GNU
*** Guix
** Container
*** Luet

* Linux Alternatives

** Google Fuschia

** Open BSD

** Haiku

