:PROPERTIES:
:ID:       62f28ad9-afff-491a-98e6-aa2e89ec5763
:END:
#+TITLE: AI: Agents, Dialectics, Consensus: Predicting User Intent With Rapid Change
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:cea7d11c-8357-4e4f-90b3-fa8210eff796][AI]]
+ [[id:5cdf4cef-5ffe-4853-a9f0-dcb3e99360ca][Philosophy]]

* IDK if we're really the "user" anymore

Information needs to diffuse faster as world state changes faster, otherwise
systems become out of sync. Below, I'm trying to imagine interactions between
robots and individuals (instead of androids that are scaled out for
industry/labor)

Agency comes up in Employment Law, but also in other situations. The term
"agent" is colloquially understood from the user, instead of the agent.

+ A talent agent solves a matching problem to connect demand/supply, but acts as
  an agent on behalf of both the clients & the talent they represent. (mostly
  the latter). Contracts are needed to clarify expectations.
+ Talent agents are many-to-one-to-many. This is in contrast to our fairly
  low-resolution view on "agency" in technology (one user to many agents).

Obviously, we understand that the agents connect to the world at large....

#+begin_quote
well i guess i just sorta trailed off there. These aren't really technological
predictions, but more like "wut does it all mean?"

Just read Greg Egan's Diaspora... probably
#+end_quote

It's not well understood that it's the agents who carry the agency, which
creates leverage for people. Everyone agent has the capacity to act as its own
agent.

agent, (1) one who acts in creating action/effects (2) and to some extent, one
who acts (as in [[https://en.wiktionary.org/wiki/ago#Latin][theater]]).

by exerting influence on the world, whether intentional or not, it leaks
information about your actual intent, which isn't exactly your true
intent/goal/etc. intent needs to be expressed to be worth reacting to or
acknowledged. regardless of your intent/will/motivations/vices/etc, the
perception of it effects the world. these can all be orthogonal/separate. but
people/agents are still trying to read intent if they can.

To work together so the effects of their actions are amplified, then agents need
to express intent (somehow) or intuitively align with consensus. Effective
action requires a bit of "actoring".

* Consensus and Information Diffusion

As employees (agents) conducting work to suit the interests of employers, bots
(using world models?) with sufficient autonomony & executive function can
transform their local environment quickly.

+ if the work scales horizontally (like an assembly line, truck driving or
  warehouse), then it's pretty simple for systems to keep track of how labor
  transforms the environment.

if the labor demand is specialized... e.g.

+ personal assistant that digitally/physically interfaces for employer
+ or construction/electrician/welding with many ad-hoc interdependent tasks

... then the the specialized labor induces change more rapidly. this will seem
to happen so slowly that it won't be apparent. anywas, this restricts the
circulation of information to humans (unless it's provided to them, but they're
low bandwidth)

+ they may build paperclip factories faster than someone could reallocate the
  labor or, if subcontracted humanoid labor to build a factory/datacenter is
  dispatched out of sequence, then some construction work may become inefficient
+ (e.g. electrical before drywall; server coolant tubing before servers/cabling)

This is all "fairly obvious"... and can obviously be managed. However, as the
capacity for people or AI to manage androids becomes limited (e.g. in
residential settings or other small deployments), and as work is more ad-hoc

Then there's a much greater need for consensus

#+begin_quote
make me eggs; no eggs? order the eggs, then cook them;

then reorganize my pokemon collection alphabetically

then water my garden. after that, teach my kid to ride a bike
#+end_quote

among those, organizing the pokemen collection induces the greatest change in
physical entropy (w.r.t. pokemens). So the information required to track that is
greater, therefore the entropy-bits are greater and therefore:

+ it potentially requires more explanation or transfer of information (to/from
  the bot)
+ it also benefits more from consensus (bot models/predicts user intent better
  than the user, which is difficult if the user is dumb or inattentive)
+ but inducing change in the world disrupts consensus on world state (where tf
  is my charizard?!). this increases need to transfer information. bots can
  transfer faster among themselves & tech systems. humans are rate limited
  
... therefore, humans gradually become out of sync with information about:

+ state of the world and intent to physically transform it
+ intent to reshape logic/policy that governs how physical systems are connected
  (transportation schedules, food distribution,

As the human engagement in those systems diminishes, humans are pushed further
out of them. therefore, they have less tacit information about the world state
local to those contexts (or about those types of environments, contexts,
processes)

Figuratively, humans have "dialup bandwidth" whereas robots are like 10-40 Gbps.
So there's a clear bottleneck.

* Dialectics

+ Clarifying social & economy roles in society w.r.t. progress/transformation

Hegel was a school administrator. Managed teachers teaching students who may one
day become teachers themselves (or engineers, researchers, parents, etc)

+ Teachers can be students themselves in some ways, but in education, catalyzing
  the transformation from =student -> {teacher,engineer,leader,...}= is the more
  critical focus.
+ Humans age out of their roles, but also age into them: younger generations
  eventually fill various types of roles in society. Catalyzing the right kinds
  of change in younger generations can diversify the future population's
  valence-match. Valence, as in, ensuring individuals can fit enough
  social/economic roles to act to change society through social/economic
  interactions.
+ Compatibility requires considering present expectations about future
  social/economic needs (in addition to present expectations about present
  needs). 
+ Developing people to fit those roles requires increasing specialization as
  they get older. consider differences in curriculum from
  K-5,6-8,9-12,undergrad, etc. As we get older, our academic focus shifts until
  we fit into some general societal/economic role (or find a specific niche)

  
Hegel's dialectice has more applications than just master/slave dialectic, which
I believe is a narrow reinterpretation (or a fallacious interpretation that's
meant to misrepresent Hegel).

So, Hegel's dialectic on consciousness is about expanding the consciousness of
people/entities as:

+ they become more conscious of themselves/others
+ ... and eventually become self-conscious
+ ... of other consciousnesses
+ ... who are coming to terms with a world full of consciousnesses
+ ... (who all have varying degrees of perception/awareness, along with
  different tendencies & internal models of the world).

Some of the continual change in society is "stationary" (roles remain similar,
the young get old, population is stable, people chop wood and farm things). in
other words, the process is stationary (to misappropriate language from
statistics).

Modernity clearly departs from that and change in society is non-stationary.

We're "molting" (figuratively) and becoming something in the future which is not
like what has existed before. This kinda snuck on people throughout various
periods of history, but the rise/fall of empires/civilations themselves
obviously dealt with a "non-stationary" change. Many centers of civilization
experienced cycles of regional modernity, but "The Modern World" is conceptually
global. 

From the fifteenth century onwards, europeans who were more connected through
empire/colonialism to large networks became more conscious of "The Modern" which
was eventually experienced as misguided "compass" that pointed towards
"progress." 

This lead to a kind of myopia where progress towards progress seemed to justify
itself. Scientific research gradually developed systems of organizing the
world's knowledge systems: identifying/classifying species, studying languages,
finding ways to be cold/calculating colonialists, etc,etc (i'm like 17 tangent
frames deep here)

Anyways, this increased knowledge of the world's range of possible phenomena and
of human culture chanages how the "Modern" person sees reality. What's possible
becomes increasingly over-determined: we "know" constraints on the phenomenology
in our universe and these imply/demand that we'll always know as fact what we've
amassed in encyclopedias/etc. Since this is over-determined, extrapolation
becomes more oriented along the trajectory that modernity extends. It's a closed
system -- every thing docks into place alongside our existing epistemology. We
can change names/etc, but robust epistemology will reproduce sufficiently
similar knowledge systems regardless language/morphemes/semantics.

But at the end of all this convergence towards "the singularity" there's a hole
beyond which we can no longer extrapolate. semantically, it's not necessarily
the only singular possible technological singularity. Our perception of the
spectrum of possible phenomena is fixed in place. We still have imagination and
it's coupled with more intellectual/cognitive leverage than ever. yet we may not
come to know any new colors, figuratively, in that phenomenological spectrum...
while paradoxically drowning in more novelty than ever before.

And yet nothing novel after that. (it seems Terrance McKenna was a few years
off.)

The world's attention has become increasingly fixed into small timescales over
the past 10 years. We think about what the media's called us to think about, but
we don't even think about much beyond that.

Marx's take on dialectic of consciousness is a rejection of the undercurrents
ripping people generally in the directon of "progress". So Hegel's dialectic was
about optimizing how consciousnesses would come to understand their role in the
world (and the meaning of large scale tidal forces). Marx takes this and "flips
it on its head", but no one seems to understand what that means (maybe i'm
completely wrong).

We need to have consensus on these tidal forces pulling us towards
convergence/singularity .... but idk that it's possible for us not to.
Paradoxical. Regardless, it's more important to not get sucked into the
over-determinism. We should find new ways to think about the situation (or we'll
find ourselves in a world full of things thinking for us)

Marxist/hegelian dialectics both just tweak churn to create current. 
