:PROPERTIES:
:ID:       fdaa094a-3254-4de3-bc98-df279219762f
:END:
#+TITLE: Omarchy: Upgrade to Quattro
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:fbf366f2-5c17-482b-ac7d-6dd130aa4d05][Arch]]
+ [[id:95146708-4046-4cdb-a5df-e15594f17733][Bootloader]]
+ [[id:04edaf13-987d-4337-a65b-3d661c3153d3][Omarchy: Upgrading To Quattro As A Nixos User]] (stream)

* Resources

* Plan

The original installation was around omarchy =3.2.3=

|        |         | distro | desk env | hypr                                |
|--------+---------+--------+----------+-------------------------------------|
| kharis | laptop  | arch   | omarchy  | custom lua on omarchy               |
| kratos | desktop | nixos  | n/a      | custom lua compat with some omarchy |


** Boot

Need to check =quattro='s upgrade script:

+ what state does it expect to migrate from? migrate to?
+ does it preserve/handle older btrfs snapshots? does their configuration remain
  manually bootable?
+ does it make any assumptions about or changes to btrfs subvolumes & snapshots?

*** Snapshots

*** Limine

** Lua

+ Run omarchy's Lua on kharis enough to discover the dependencies
+ Plan to make some lightweight functionality compatible
  - mainly just the =hypr= module namespace, which requires =bootstrap.lua=
  - however, i may stick with a distinct module namespace to avoid most
    crossover. i can't really guarantee that I can keep up with the rate of
    change.

** Migrations

What's the content of migration scripts in quattro?
* Prep

Upgraded omarchy from =3.8.3 -> 3.8.4= and restarted to ensure the running
software (linux, hyprland) matches the environment expected in 

** Backup

Just in case, i booted an image and copied the partitions

#+begin_src shell
devoma3=/dev/nvme0n1
devbackup=/dev/sdb

# check the partition table
sfdisk -J $devoma3

# copying the entire 1TB disk to a 2TB disk would take to long, so
# copy the partition table
sfdisk -d $devoma3 | sfdisk $devbackup

# check the new partition table
sfdisk -J $devbackup
#+end_src

Then copy the specific disks

#+begin_src shell
devoma3=/dev/nvme0n1
devbackup=/dev/sdb

# careful with these commands!
echo dd if="$devoma3"p1 of="$devbackup"1 bs=1M status=progress
echo dd if="$devoma3"p2 of="$devbackup"2 bs=1M status=progress
#+end_src

I'm getting about =6.5GB/min=, so this will take about 150 min ... which seems way
too long, but whatever. It could be drivers or something. This is copying over
USB3.

*** Regenerate =UUID='s

+ this would likely make the drive unbootable until the UUIDs are restored, but
  concurrently mountable with the backup source.
+ if doing so, you should backup the UUIDs from the source and =mount= read-only

Doing that risks leaving your linux a bit confused, since the UUIDs are the same
-- esp. if you try to boot from the backup while the source disk is still
plugged in. Gemini says this would remove the partition UUIDs, forcing =sfdisk= to
recreate them. It keeps the GPT label-id in tact...

#+begin_src shell
sudo sfdisk -d /dev/sda \
    | grep -v ^label-id \
    | sed -e 's/, *uuid=[0-9A-F-]*//I'
    | sudo sfdisk /dev/sdb
#+end_src



* Changes

See "Changes" in [[id:04edaf13-987d-4337-a65b-3d661c3153d3][Omarchy: Upgrading To Quattro As A Nixos User]] for environment diffs

* Upgrade

The upgrade went pretty well

** Environment

** Dots
+ cleaned backup files and configs from old applications

*** Emacs
+ Fixed fonts (they were apparently broken for awhile ...)
  - Doom emacs could respond to emacsclient with =doom/reload-font= to match
    omarchy fonts.
  - Getting themes to match would be difficult, especially for custom themes.
+ Set =doomedit= to load as editor
  + via =~/.config/omarchy/extensions/omarchy-menu.jsonc=

*** Hypr

* Issues

** Environment

*** Checking UWSM environment

#+begin_src shell
hyprctl dispatch 'hl.dsp.exec_cmd("notify-send " .. os.getenv("HYPRHOST") .. " $HYPRHOST")'
hyprctl dispatch 'hl.dsp.exec_cmd("notify-send $HYPRHOST")' # prefer the above
#+end_src

*** SSH Path

This gets set in PAM config [[https://github.com/basecamp/omarchy/blob/fa955bfa9d2c94339f452e4c56cb5bbfc5e1718e/install/config/ssh-command-path.sh#L9][here]] (had a hard time figuring this out for
classical linux)

#+begin_src shell
PATH DEFAULT=/usr/local/sbin:/usr/local/bin:/usr/bin:@{HOME}/.local/share/mise/shims:@{HOME}/.local/bin
#+end_src

Fixing this will allow =guix copy= to succeed
** Quirks

*** Default apps

Using the =omarchy menu= to set a default editor (or any default, afaik) will
initially require =mkdir -p ~/.local/state/omarchy/default=. Until then:

+ =echo doomedit > ~/.local/state/omarchy/defaults/editor= fails (sets the editor)
+ also checking that the editor exists fails (it fails for any command)

This is likely because certain installation/setup scripts weren't run.
* Topics

** TUIs

*** Using =alacritty=

See [[https://github.com/dcunited001/ellipsis/blob/20a7cadf2c90c71be1497d35ffa77826c3a54ad7/.config/hypr/workspaces/tuitray.lua#L5][.config/hypr/workspaces/tuitray.lua#L14]]... i had [[https://github.com/dcunited001/ellipsis/commit/20a7cadf2c90c71be1497d35ffa77826c3a54ad7#diff-9ac351717f39c263f7a6404e999c8df59b98189f37a3a61c29bacde6ca3905a3][kinda forgotten]] that:

- these were only window rules. the binds were configured with a shimmed version
  of omarchy's =.conf= rules.
- only =isd= was intended to launch with =MOD3 + Prior=

#+begin_src lua
local function tuitray_cmd(tui)
    -- tui class and bin name should match
    return "alacritty --class 'Alacritty:org.dc.tuitray' -T 'tuitray:" .. tui .. "' -e " .. tui
end
#+end_src

soo... basically this entire file now goes away

*** Using =omarchy-launch-or-focus-tui= which wraps =xdg-terminal-exec=

#+begin_src lua
o.bind(keybind, "Launch TUI: " .. k, )
#+end_src

**** With =alacritty= on NixOS

Requires the =X-TerminalArg.*= properties on the desktop file:

#+begin_src nix
  hjem.users.dc.xdg.data = {
    files = {
      "applications/Alacritty.desktop" = {
        text = ''
          [Desktop Entry]
          Type=Application
          TryExec=alacritty
          Exec=alacritty
          Icon=Alacritty
          Terminal=false
          Categories=System;TerminalEmulator;

          Name=Alacritty
          GenericName=Terminal
          Comment=A fast, cross-platform, OpenGL terminal emulator
          StartupNotify=true
          StartupWMClass=Alacritty
          Actions=New;

          [Desktop Action New]
          Name=New Terminal
          Exec=alacritty
          X-TerminalArgExec=-e
          X-TerminalArgAppId=--class=
          X-TerminalArgTitle=--title=
          X-TerminalArgDir=--working-directory=
        '';
        clobber = true;
      };
    };
  };
#+end_src

So for alacritty

#+begin_src shell
pushd `nwix alacritty`
cat "$(pwd)/share/applications/Alacritty.desktop" | wl-copy # and paste
ssh myhost ~/.local/share/applications/Alacritty.desktop" | wl-copy # and paste/scrape
#+end_src

Ghostty is already done, but causes my =MOD3= keybinds to be double-processed :(

#+begin_src shell
pushd `nwix ghostty`
cat "$(pwd)/share/applications/com.mitchellh.ghostty.desktop" | wl-copy # and paste
ssh myhost ~/.local/share/applications/com.mitchellh.ghostty.desktop | wl-copy # and paste
#+end_src

** Flake

#+begin_src nix
{ ... }: # for example
{
  description = "nixos omarchy";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";
    hjem = {
      url = "github:feel-co/hjem";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    omarchy = {
      url = "github:basecamp/omarchy/tree/quattro/config";
      flake = false;
    };
  };

  outputs = {
    nixpkgs,
    hjem,
    omarchy,
    ...
  }: let
    system = "x86_64-linux";
    pkgs-unstable = nixpkgs-unstable.legacyPackages.${system};

  in {
    nixosModules.default = {...}: {
      _module.args.omarchy = omarchy;

      imports = lists.flatten [
        hjem.nixosModules.hjem
      ];
    };
  };
}
#+end_src
