:PROPERTIES:
:ID:       891df5ee-2b34-40ec-a7da-92e16c5424b2
:END:
#+TITLE: FRC: WPILib 2027                                                                                                                                                                                               @slips                                                 
#+CATEGORY: slips
#+TAGS:

* Roam
+ [[id:c75cd36b-4d43-42e6-806e-450433a0c3f9][FRC]]
+ [[id:18d07822-9dda-4430-85a1-f7eb39f40429][VSCode]]
+ [[id:97ae00f5-9337-4108-b85f-1edfc7f86ed7][Java]]

* Resources

* Notes

** Project Templates

** Vendor Deps

After generating the "Commands v3 REBUILT" project, needed to check vendor dep
availability to gauge support at launch, esp. for hardware.

| advantage kit      | logging    |
| choreo             | trajectory |
| phoenix v6         | hw         |
| phoenix v6 replay  | hw         |
| doglog             | logging    |
| pathplannerlib     | trajectory |
| reduxlib           | hw         |
| revlib             | hw         |
| yams (commands v2) | mechanism  |
| yams (commands v2) | mechanism  |

Some hardware support is missing for now. Photonvision is experimental for now,
but needs a =dev= build.

** VSCode

Managing multiple installs is a problem. Team members should select a distinct
theme when first starting the editor.

*** Extensions

| extra                                |    new | version | default                       |      old |              new | microsoft                             |     old |     new |
|--------------------------------------+--------+---------+-------------------------------+----------+------------------+---------------------------------------+---------+---------|
| huntertran.auto-mardown-toc          |        |  3.0.15 | redhat.java                   |   1.38.0 |           1.55.0 | ms-vscode-remote.remote-containers    | 0.469.0 | 0.469.0 |
| richardwillis.vscode-spotless-gradle |  1.2.1 |   1.2.1 | wpilibsuite.vscode-wpilib     | 2026.2.1 | 2027.0.0-alpha-7 | vscjava.vscode-gradle                 |  3.17.2 |         |
| takumii.markdowntable                | 0.13.0 |  0.13.0 | vscjava.vscode-java-depenency |   0.24.1 |           0.27.6 | vscjava.vscode-java-test              |  0.44.0 |  0.46.0 |
| mermaidchart.vscode-mermaid-chart    |        |   2.5.9 | vscjava.vscode-java-debug     |   0.58.2 |           0.59.0 | ms-vscode-remote.remote-ssh           | 0.120.0 | 0.128.0 |
|                                      |        |         | ms-vscode.cpptools            |   1.28.3 |           1.33.8 | ms-vscode-remote.remote-ssh-edit      |  0.87.0 |  0.87.0 |
|                                      |        |         |                               |          |                  | ms-vscode-remote.remote-extensionpack |  0.26.0 |  0.26.0 |
|                                      |        |         |                               |          |                  | ms-vscode-remote.remote-wsl           | 0.104.3 | 0.104.3 |
|                                      |        |         |                               |          |                  | ms-vscode.remote-server               |   1.5.3 |   1.5.3 |
|                                      |        |         |                               |          |                  | ms-vscode.remote-explorer             |   0.5.0 |   0.5.0 |
|                                      |        |         |                               |          |                  |                                       |         |         |

+ mermaidchart.vscode-mermaid-chart :: requires disabling AI features
  - =mermaidChart.aiSkills.{enabled,promptOnDetect,aiExportName}=. The
    =aiExportName= was obnoxious and notifying on completely unrelated files
  - also =mermaidChart.{createDiagramFromStage,preCommitSync}.enabled=,
    =mermaidChart.enableTelemetry= and =mermaidChart.showGenerateDiagramCodeLens=

I generally _never begin_ to consider _anything_ that requires a subscription. I
cannot afford it. Why depend on a tool just to lose it later? The more valuable
the tool, the greater the disruption. This is why I have never signed up for _any
LLM_.

I wish this wasn't terrible advice, but it is. I wish that it would've lead me
to me a stronger developer... but it turns out most software/platforms skills
get you paid require a bit of money to use (looking at you, big cloud). Finding
other tools to fill the gaps leads you to strengthen skills which just aren't
"super employable".

A bit of a sore spot... Anyways

*** VSCode =settings.json=

#+begin_src shell :results output code :wrap example diff
q='to_entries | sort_by(.keys) | from_entries'
# ff=$(ls ~/{wpilib/2026,.local/share/wpilib/2027_alpha7}/vscode/VSCode-linux-x64/data/user-data/User/settings.json)
v1=~/wpilib/2026
v2=~/.local/share/wpilib/2027_alpha7

diff <(jq "$q" $v1/vscode/VSCode-linux-x64/data/user-data/User/settings.json) \
    <(jq "$q" $v2/vscode/VSCode-linux-x64/data/user-data/User/settings.json)
#+end_src

#+begin_example diff
--- /dev/fd/63	2026-10-06 01:49:20.862882819 -0400
+++ /dev/fd/62	2026-10-06 01:49:20.863882820 -0400
@@ -1,6 +1,6 @@
 {
-  "java.jdt.ls.java.home": "/home/dc/wpilib/2026/jdk",
-  "extensions.autoUpdate": false,
+  "java.jdt.ls.java.home": "/home/dc/.local/share/wpilib/2027_alpha7/jdk",
+  "extensions.autoUpdate": "off",
   "settingsSync.ignoredSettings": [
     "extensions.autoUpdate",
     "extensions.autoCheckUpdates",
@@ -10,7 +10,10 @@
     "update.showReleaseNotes",
     "java.completion.matchCase",
     "workbench.secondarySideBar.defaultVisibility",
-    "terminal.integrated.env.linux"
+    "security.workspace.trust.startupPrompt",
+    "terminal.integrated.env.linux",
+    "update.enableWindowsBackgroundUpdates",
+    "workbench.welcomePage.experimentalOnboarding"
   ],
   "extensions.autoCheckUpdates": false,
   "extensions.ignoreRecommendations": true,
@@ -19,35 +22,26 @@
   "update.showReleaseNotes": false,
   "java.completion.matchCase": "off",
   "workbench.secondarySideBar.defaultVisibility": "hidden",
+  "security.workspace.trust.startupPrompt": "once",
   "terminal.integrated.env.linux": {
-    "JAVA_HOME": "/home/dc/wpilib/2026/jdk",
-    "PATH": "/home/dc/wpilib/2026/jdk/bin:${env:PATH}"
+    "JAVA_HOME": "/home/dc/.local/share/wpilib/2027_alpha7/jdk",
+    "PATH": "/home/dc/.local/share/wpilib/2027_alpha7/jdk/bin:${env:PATH}"
   },
   "java.configuration.runtimes": [
     {
-      "name": "JavaSE-17",
-      "path": "/home/dc/wpilib/2026/jdk",
+      "name": "JavaSE-25",
+      "path": "/home/dc/.local/share/wpilib/2027_alpha7/jdk",
       "default": true
     }
   ],
   "settingsSync.ignoredExtensions": [
     "wpilibsuite.vscode-wpilib"
   ],
-  "[markdown]": {
-    "editor.wordWrap": "off"
-  },
-  "markdown-toc.depthTo": 4,
-  "markdown-toc.updateOnSave": false,
-  "chat.disableAIFeatures": true,
-  "editor.tabSize": 2,
-  "editor.lineNumbers": "off",
-  "editor.minimap.enabled": false,
-  "editor.fontFamily": "'JetBrains Mono Nerd Font','Droid Sans Mono', 'monospace', monospace",
-  "workbench.colorTheme": "Default Dark+",
-  "redhat.telemetry.enabled": false,
-  "editor.fontLigatures": false,
-  "java.jdt.ls.vmargs": "",
-  "git.blame.editorDecoration.enabled": false,
-  "git.blame.statusBarItem.enabled": true,
-  "wpilib.skipSelectSimulateExtension": true
+  "update.enableWindowsBackgroundUpdates": false,
+  "workbench.welcomePage.experimentalOnboarding": false,
+  "terminal.integrated.initialHint": false,
+  "workbench.colorTheme": "Solarized Dark",
+  "mermaidChart.aiSkills.promptOnDetect": false,
+  "mermaidChart.aiSkills.enabled": false,
+  "mermaid.vscode.aiExportName": false
 }
#+end_example

** Driver Station

+ Need to create a group and add it =input= group.
+ =chgrp= on the DS bin, then run as =sgid=. Otherwise the spacebar check fails (it
  monitors input)
