:PROPERTIES:
:ID:       58db2280-a05f-4900-9c8a-d91f86046880
:END:
#+TITLE: Social Physics Explained Via Chemistry Analogies
#+CATEGORY: slips
#+TAGS:  
* Roam
+ [[id:01ace2d7-1324-4dd2-9e2e-d5c152fdc378][Social Physics]]

* "Chemistry"

I've developed a ton of ideas for modeling this, which I called "Social
Physics." For the kind of interactions that produce change in a community, there
are dependencies and interaction times required, so pattern languages based
around chemistry and/or cooking provide a basis for analogies. What's needed:

* Sufficient interaction time

Chemical reactions are based around the frequency
of interactions and sufficient local free energy to "knock something loose" to
induce change. For endothermic reactions, you either need more time or more
heat. 

* Sufficient molarity/ingredients

some reactions just aren't going to happen without enough ingredients. This can
also be imagined as kneeding bread to mix in oxygen: small changes in seemingly
inconsequential steps produce about an order of magnitude difference in how the
bread rises. When there is plenty of air mixed in and when surface area
surrounding dissolved oxygen is high, it accelerates the reaction rates.

* Matching valence

for chemical reactions, there seem to be endless varieties of functional groups
and sidechain reactions. But social physics has even more variation, making it
seem like there's no systematic way to approach structuring a process for change
-- a chemical reaction is literally a method for producing intentional change in
materials.

There is still a concept of _valence_ for socially mediated change though -- for
some individuals/groups' needs, can other individuals/groups _supply_ something
that fits a _demand_. In the bread analogy, a supply of oxygen is required for
yeast to chemically transform the carbs. This is seen clearly in educational
institutions -- they have a supply of experts' manhours, which students need in
order for a "sociophysical reaction" to occur. This can't happen if students
don't have teachers and teachers don't have students.

This is similar to the affinity that specific elements have for participating in
reactions with other elements -- it's literal valence, but more complicated
since you can't measure it.

* Sufficient thermal free energy

Heat is just a proxy for "transit time." This sounds overly technical, but it's
pretty similar. Fusion is a special kind of chemical reaction: it's semantically
defined as a nuclear reaction, but it's not very different than other chemical
reactions. Increase $\frac{t}{d^{2}}$ for each pair of nuclei and the reaction
rate increases. Just as the rates of chemical reactions increase with "transit
time". Heat is just one way to do this.

* Appropriate phase

_For social interactions_... heat is not quite the correct tool. Instead, some
groups need phase changes. Solids don't move: reactions can only occur between
adjacent molecules and the distances between molecules are mostly static. linear
increases in temperature don't produce linear changes in reaction rates ...
until a phase change occurs, at which the deficits in reaction rate increase are
compensated -- the reaction events that weren't produced are then produced
faster than expects after the phase change ... though it's not a great general
rule.

Social groups on a small scall require enough physical movement to drive
specific conversations needed to drive reaction mechanisms to produce
intentional change. You're not trying to produce a free radical or pull a
pi-bond's electron out, but proximity and degrees of intimacy are required for
information to become available to participants. A teacher needs to elicit each
student's specific needs to identify knoweldge gaps, corrections and guidance.
To form a startup, a founder needs to identify people whose valence & appetite
for risk is appropriate but also needs to identify skills/tendancies.

But there are more than 4+ "phases of social matter. A physical phase is a
collection of interaction dynamics. _For groups_, phases are abstract. e.g.

+ the meet/greet (gas phase)
+ the keynote (solid phase)
+ the time between talks at a conference (liquid phase),
+ lunch (gas phase: fills a larger container)

So the physical shape of the reaction vessel -- the venue & location -- is
tightly coupled to the *interaction modes*: i.e. host an event in Orlando and
/somebody/ is going to Disney World.

The range of interaction modes then have different possibilities for intentional
change. The key takeaway for phases is that interaction rules are distinct while
the mechanics are. Phase changes aren't necessarily expensive, but usually
correspond to changes in movement patterns that create broadly more variety in
subgroups and pairs.

* Potential > Control 

In actual practice, nothing goes perfectly. Control backfires because social
behavior is inherently stochastic. Instead, it's important to provide variety to
create possibilities, letting people deal with the micro-decisions. However,
some physical aspects of a space will strongly shape the kinds of interactions
or even the directions people face on average (polarization btw). e.g.

+ a classroom where people can't easily stand while a speaker is presenting will
  not facilitate group interactions on a small scale & will instead conduct the
  groups attention towards the speaker.
+ a classroom without computers will tend to produce laptops & ipads, unless
  there is some rule imposed.

If the intent is to provide a physical space that reinforces the hierarchy --
i.e. students pay attention to a teacher with minimal individual/group
distractions -- then the direction of the visual cone is an important parameter
to optimize. So, if the "phase" is appropriately constructed, the average time
each person spends looking in a specific direction will minimize entropy -- for
the "distribution" of "facings" over the domain of radians (or steradians, if
laptop/ipad distractions should be minimal).

However, if the goal is to promote interpersonal interactions and help people
meet each other, the the same physical environment or agenda will not encourage
new relationships to form. People will feel rushed to interact before/after a
presentation. Afterwards, peoeple *may* feel a bit awkward. If there aren't enough
people with _sufficiently conscious_ valence for optimizing interaction-time with
other programmers/devs, then reflection on social consensus takes over: people
follow each others' lead. One person leaves then several people leave in bursts.
Now the apparent potential remaining in the space is less and each individuals
competing priorities will take successively greater precedence.

* It is all social physics

A group is only made conscious of itself through the eyes of the individuals
that constitute it. Groups are subject to emergent phenomena, but usually
"weakly emergent phenomena", where strongly emergent phenomena is one that can't
be explained through first-order dynamics from the first-principles of the
mechanics.

Thus, the strongly emergent phenomena, here, include a group's tendancies to
promote organization in spite of entropy. Specifically, by optimizing for
enthalpy production. This _always_ requires energy, if not phyiscal energy then
social energy.

In other words, compensating for a group's lack of consciousness &
intentionality requires magnifying intentionality within some subset of
individuals themselves, which isn't possible without group identification. That
requires organization, reflection, branding and hierarchy. Groups that thrive
_require_ that some of its members _contribute more_ effort. People understand this
all very well -- it's why we've developed norms & even codified them into law or
etiquette. Successful groups are not the natural state of things: they are
neither a product of chaos nor are they possible without volatility (in the
stochastic sense).

And thus, the upkeep cost of communities causes churn. It's expensive and the
qualities and propritious factors required to cultivate & motivate informal
leadership are more easily damaged than they are repaird. Everything that rises
must fall and thus there's a basis for reorganization.

Since the attention economy is directly connected to how much interaction time
occurs between people, then disrupting how people organize or spend time with
each other disrupts the formation & upkeep of groups. The opportunity cost of
lost social interaction accumulates in the form of memories not made, which
impairs the attractive forces that motivate sustainence of small, especially
informal groups. Without mechanisms for information exchange or to promote group
self-awareness, a group's self-identification as such is quickly injured. Again,
since group dynamics are not a product of "consciousness" of the group itself,
then such an injury is not recognized until later maybe the individuals of the
group wonder what happened? Where is everyone? ... But if there was never a
group at all, then there's nothing to wonder about. Thus, the reference to
opportunity cost about: these are "first-order" costs that don't properly fit on
a balance sheet.
