:PROPERTIES:
:ID:       95dbfd43-ed70-4fa9-a0bf-8d20d3b6ba45
:END:
#+TITLE: Chromium: Potential Network Stack Issue
#+CATEGORY: slips
#+TAGS:

#+begin_quote
I'm 99.9% sure that this problem is caused by an interaction between
chromium-based browsers and KeepassXC. For some reason when a second
Chromium-based browser instance starts, it causes KeepassXC to pop up prompting
me to open/create is already open. and the Network Now that I know that, it's
much easier to deal with.

> As I'm typing this, i needed a password to login on firefox. I use KeePassXC
with some restrictions applied to the extensions. These are configured in the
extension UI. This prevents it from fetching passwords from one of two files.
When I closed the file that does communicate with chromium, the NetworkService
was instantly restored. IDK whether that's conflation or what.

#+end_quote

* Roam

+ [[id:a76b66a6-808b-4078-a1af-cac7e4d380c3][Chromium: Crash Dumps]]
+ [[id:38638b3e-e023-460e-9670-84776e61468e][Browser]]

* Resources

* Issue

+ Chrome crashes, producing a dump. A site hangs CPU, then the browser crashes.
  Usually takes about 2-8 seconds.
+ After restart, only =file:///= urls work & only incognito will connect to any
  HTTP requiest.
+ Affects even the profile selection window. May affect crashdump reporting
  - There are no other crash dumps, except these recent ones.
  - Um chromium has a hard time with any HTTPS connections at startup
  - By the time it gets fixed... idk whether it backs up to past

** For now...

Not enough time. Not running chromium until I learn a bit more (maybe at least
parse the crash dump)

Will run google chrome from a nix profile or something (entirely separate stack
and set of profiles AFAIK)

* Notes

Tips in comments from earlier somehow slipped my attention. Saw them, but didn't
immediately drill into it. Hard for me to test, since it just seems to happen
every two weeks or so.

** Related Issues

*** [[https://issues.chromium.org/issues/482074640][Network connection getting lost, unresponsive tabs, high CPU usage]]

| 2026/2/6 | 146.0.7655.0 | Linux |

+ Suggests race conditions in =Network Service Task Scheduler= via feature
  disabled by flag =--disable-features=NetworkServicePerPriorityTaskQueues=

+ Discussion of effects of experimental feature (race condition causes infinite
  loop, then OOM)
+ Potential A/B testing (a [[Finch Study]] mentioned later in #21,27 ... lol bc a/b
  testing is super simple... =</sarcasm>=)
+ [[https://issues.chromium.org/issues/482074640#comment19][Comment 19]] mentions [[https://chromiumdash.appspot.com/commit/963585f1f3f91e9e780cc26d32b8dd45137fd6fa][this commit]]
+ #26: Seems experiment for feature =NetworkServicePerPriorityTaskQueues= is no
  longer tested in production (experiment stopped)

**** [[https://issues.chromium.org/issues/481336398][Chrome: Crash Report - [Out of Memory] net::HttpStreamFactory::RequestStreamInternal]]

Potential duplicate of 482074640 above

| 2026/2/3 | No Build Number | Windows |
