:PROPERTIES:
:ID:       27362e6b-9da4-4ff8-9c80-89b9107e7a52
:END:
#+TITLE:     Forensics: Search ExtFS With Tsurugi and Foremost
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes


+ [[id:d7cc15ac-db8c-4eff-9a1e-f6de0eefe638][File Systems]]
+ [[id:bdae77b1-d9f0-4d3a-a2fb-2ecdab5fd531][Linux]]

** Docs

+ [[https://linuxleo.com/Docs/LinuxLeo-4.95.1.pdf][The Law Enforcement and Forensic Examiner's Introduction to Linux]]
+ Sans Institute [[https://www.sans.org/posters/?msc=main-nav][Posters & Cheatsheets]]

** Resources

- [S/O question with useful diagnostic commands](https://unix.stackexchange.com/questions/33284/recovering-ext4-superblocks)
- [Ubuntu data recovery](https://help.ubuntu.com/community/DataRecovery)
- [Arch data recovery](https://wiki.archlinux.org/index.php/File_Recovery)
- [TSK Home Page](https://www.sleuthkit.org/autopsy/desc.php)


* Process

## Emacs

- only emacs 24 is available from repos. you must build.
- install `texinfo` which provides `makeinfo`

these libraries may be required:

#+begin_src sh
sudo apt-get install libc6-dev libncurses5-dev libpng-dev libtiff5-dev xaw3dg-dev zlib1g-dev texinfo libgif-dev
#+end_src

** Foremost

#+begin_src sh
sudo foremost -i /media/dc/wut/arch-data.img -o foremost-recovery
#+end_src

** Ext4Magic

- most of the modes in `ext4magic` are terminating early.
- for some reason, i think Garuda overwrote all my superblocks

#### Attempt Recovery of all data

#+begin_src sh
sudo ext4magic /media/dc/wut/arch-data.img -D -d ~/dev/recovery/ext4/ -c
#+end_src

** Analyze Ext

(Perl script)

** Bash History For Tsurugi Session

+ Attempting a recovery of an ExtFS drive:
  - I lost most of my media, but recovered my library of PDF's ... no filenames though.
  - other more sophisticated techniques like block hashing & file hashing would
    produce better results
  - other techniques would require too much time (and disk-space)
    - format-aware scanning of disk images
    - filtering/operating on a partial reconstruction of Ext4 inodes
    - scanning the recovered (but corrupted) journal
      - in reverse, starting from  $T_crash$ and backwards to $T_crash - T_window$
      - this should help one focus on the most recent FS problems and the most
        recently(frequently) accessed files
+ the techniques listed above require require probably +2 TB for a 256gb drive
  - they require intimate awareness of Block-level and FS-level details of disks/ext4
  - and tons of custom scripts, preferably reproducible.
  - ideally, this should be in the form of a processing pipeline:
    - starting with an tools, scripts, & image
    - producing databases for: file/block hashes, file/block metadata DB, inode/block pointer DB
    - And producing some kind of "transaction log" for operations taken, data
      artifacts yielded
      - and partial images/files/blocks/etc produced
+ Docs from SANS/DFIR describe the standards that dictate processes for law enforcement, court systems, investigators and expert witnesses to follow.
  - These processes are similar:
    - isolation of original images
    - network requirements
    - production of intermediate images
    - production of final data artifacts
    - documentation of process (almost certainly a reproducible one) can be found in the PDF's linked above

#+begin_src bash
ext4magic --help
ext4magic
ext4magic -h
man ext4magic
exit
man ext4magic
sudo fdisk --list
less /etc/fstab
sudo cp /media/dc/wut/arch-data.img /media/dc/wut/arch-data.bak.img
sudo apt-get emacs
sudo apt-get install emacs
sudo apt-get update
sudo apt-get check launcher
sudo apt-get check ubuntu-app-launch
sudo apt-get install launchy
sudo apt-get update
ls -al /media/dc/
ls -al /media/dc/wut/
mkdir -p dev/recovery
ls -al /media/dc/wut/
debugfs -R "dump <8> $HOME/dev/recovery/wut.journal" /media/dc/wut/arch-data.img
ls -al dev/recovery/wut.journal
less dev/recovery/wut.journal
man ext4magic
man time
now
date
date -u
date --date="@12345"
mkdir dev/recovery/ext4
sudo ext4magic /media/dc/wut/arch-data.img -M -a 1601553600 -b 1602849600 -d /home/dc/dev/recovery/ext4
ls dev/recovery/ext4
rm -r .*
ls -al
cd dev/recovery/ext4/
ls -al
ls -al lost+found/
sudo ls -al lost+found/
sudo ls -al .Trashes/
sudo ls -al .Trashes/501
rm -rf .fseventsd/
cd ..
sudo rm -rf ext4/
mkdir ext4/
sudo ext4magic /media/dc/wut/arch-data.img -M -b 1602849600 -d /home/dc/dev/recovery/ext4
sudo ext4magic /media/dc/wut/arch-data.img -J
man date
ls -al /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/
sudo ext4magic /media/dc/wut/arch-data.img -D -d ~/dev/recovery/ext4/
man ext4magic
ls -al ext4/
rm -rf ext4/
sudo rm -rf ext4/
mkdir ext4
sudo ext4magic /media/dc/wut/arch-data.img -D -d ~/dev/recovery/ext4/ -c
sudo ext4magic /media/dc/wut/arch-data.img -J
ls -al /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/
sudo apt-get install doom-emacs
mkdir src
cd src
cd ..
mkdir local
rm -rf src
cd local/
mkdir src
cd src
git clone https://git.savanna.gnu.org/git.emacs.git
git clone https://git.savannah.gnu.org/git.emacs.git
sudo apt-get uninstall emacs
sudo apt-get remove emacs
git clone https://git.savannah.gnu.org/git/emacs.git
cd emacs/
ls -al
less INSTALL
less ./configure
less INSTALL
cd src/
ls -al
cd ..
ls -al
autoconf configure.ac
./configure.ac
git reset --hard HEAD
./configure.ac
./autogen.sh
./configure
sudo apt-get install makeinfo
sudo apt-get install build-essential
sudo apt-get install texinfo
./configure
yum search makeinfo
sudo apt install yum
sudo apt-get install libxawy
sudo apt-get install libxaw7
./configure
sudo yum -h
sudo yum install emacs
history | grep tex
sudo apt-get install libc6-dev libjpeg62-dev libncurses5-dev libpng-dev libtiff3g-dev libungif4-dev xaw3dg-dev zlib1g-dev xlibs-dev
sudo apt-get install libc6-dev libjpeg62-dev libncurses5-dev libpng-dev libtiff5-dev xaw3dg-dev zlib1g-dev
sudo apt-get install libc6-dev libncurses5-dev libpng-dev libtiff5-dev xaw3dg-dev zlib1g-dev
./configure
sudo apt-get install libgif-dev
./configure
sudo apt-get install gnutls-bin
which gnutls
./configure
./configure --with-gnutls=ifavailable
make
make clean
cd ..
ls -a
ls -al
cd ../local/
ls -al
cd src/
make -j7
git clone https://github.com/halpomeranz/analyzeEXT
make check
ls -al emacs
ls -al
make install
sudo make install
which emacs
cd ../../.emacs.d/
ls -al
emacs ~/.emacs.d/init.el
sudo apt-get remove emacs
sudo apt-get remove emacs*
cd .. && git clone --depth 1 https://github.com/hlissner/doom-emacs ./emacs.d
rm -rf .emacs.d/
mv .emacs.d/ .emacs.d/
mv emacs.d/ .emacs.d/
cd .emacs.d/
cd bin/
cd ../../
~/.emacs.d/bin/doom install
cd ~
cd local/src/analyzeEXT/
./analyzeEXT.pl
./analyzeEXT.pl  --help
ls -al /media/dc/wut/
tail -F dev/recovery/analyzeEXT.log
tail -n 20 dev/recovery/analyzeEXT.log
cat /media/dc/wut/arch-data.img | ./analyzeEXT.pl -DP > ~/dev/recovery/analyzeEXT.log
./analyzeEXT.pl -H
less ~/dev/recovery/analyzeEXT.log
ls -al ~/dev/recovery/analyzeEXT.log
cp ~/dev/recovery/analyzeEXT.log ~/dev/recovery/analyzeEXT.log.bak
tail -n 20 ~/dev/recovery/analyzeEXT.log.bak
tail -n 20 ~/dev/recovery/analyzeEXT.log
cat /media/dc/wut/arch-data.img | ./analyzeEXT.pl -DP > ~/dev/recovery/analyzeEXT.log
ls -al ~/dev/recovery/analyzeEXT.log
cat /media/dc/wut/arch-data.img | ./analyzeEXT.pl -DPH > ~/dev/recovery/analyzeEXT.log
ls -al ~/dev/recovery/analyzeEXT.log*
man mke2fs
sudo
history | grep wut
sudo mke2fs -n /media/dc/wut/arch-data.img
cd dev/recovery/
ls -al
ls -al ext4/
rm -rf ext4/
sudo rm -rf ext4/
mkdir foremost && sudo formost -i /media/dc/wut/arch-data.img -o foremost
mkdir foremost && sudo foremost -i /media/dc/wut/arch-data.img -o foremost
rm -rf foremost
sudo foremost -i /media/dc/wut/arch-data.img -o foremost
rm -rf foremost
less foremost/audit.txt
sudo less foremost/audit.txt
sudo ls -al foremost/jpg
sudo chown dc:dc foremost/
sudo chown -R dc:dc foremost/
man foremost
less foremost/audit.txt
sudo foremost -i /media/dc/wut/arch-data.img -o foremost
rm -rf foremost
cd dev/recovery/
sudo tail -n foremost/audit.txt
sudo tail -n 20 foremost/audit.txt
sudo ls -al foremost/pdf
sudo ls -al foremost/pdf | less
sudo ls -al foremost/mp4
sudo foremost -i /media/dc/wut/arch-data.img -o foremost
sudo rm -rf foremost/
ls -al /etc/scalpel/scalpel.conf
less /etc/scalpel/scalpel.conf
less /etc/foremost.conf
sudo ls -al /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost/
sudo less /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost/audit.txt
sudo chown dc:dc /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost
sudo ls -al /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost/mp4
sudo ls -al /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost/mov
sudo ls -al /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost
sudo ls -al /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost/mp4
sudo ls -al /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost/jpg
sudo foremost -i /media/dc/wut/arch-data.img -o /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost
sudo chown -R dc:dc /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost
less /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost
less /media/dc/6b03e238-e432-4a13-9bc9-757cbd0b3fc2/foremost/audit.txt
sudo apt-get install zoom
cd ~/Downloads/

# ... and zoom LOL
wget https://zoom.us/client/latest/zoom_amd64.deb
sudo apt install ./zoom_amd64.deb
#+end_src
