
@startuml
hide empty methods
hide empty fields


class "**ContainerlabTopologyDefinitionFile**" as ContainerlabTopologyDefinitionFile {
        StringType name
        StringType prefix
        ContainerlabTopologyDefinitionFileMgmt mgmt
        ContainerlabTopologyDefinitionFileTopology topology
        ContainerlabTopologyDefinitionFileSettings settings
}

 

class "ContainerlabTopologyDefinitionFileMgmt" as ContainerlabTopologyDefinitionFileMgmt {
        StringType network
        StringType bridge
        StringType ipv4-subnet
        StringType ipv6-subnet
        ipv4-addr ipv4-gw
        StringType ipv6-gw
        StringType ipv4-range
        StringType ipv6-range
        mtu mtu
}
note top: configuration container for management network

 

class "**ipv4-addr**" as ipv4-addr {
}
note top: IPv4 address

 

class "**mtu**" as mtu {
}
note top: MTU for the custom network

 

class "ContainerlabTopologyDefinitionFileTopology" as ContainerlabTopologyDefinitionFileTopology {
        ObjectType nodes
        ContainerlabTopologyDefinitionFileTopologyKinds kinds
        node-config defaults
}
note top: topology configuration container

 

class "ContainerlabTopologyDefinitionFileTopologyKinds" as ContainerlabTopologyDefinitionFileTopologyKinds {
        node-config nokia_srlinux
        node-config arista_ceos
        node-config juniper_crpd
        node-config sonic-vs
        node-config sonic-vm
        node-config dell_ftosv
        node-config dell_sonic
        node-config nokia_sros
        node-config juniper_vmx
        node-config juniper_vsrx
        node-config juniper_vjunosrouter
        node-config juniper_vjunosswitch
        node-config juniper_vjunosevolved
        node-config aruba_aoscx
        node-config cisco_xrv
        node-config cisco_xrv9k
        node-config cisco_nxos
        node-config cisco_csr
        node-config cisco_cat9kv
        node-config cisco_ftdv
        node-config cisco_iol
        node-config linux
        node-config bridge
        node-config ovs-bridge
        node-config host
        node-config ipinfusion_ocnos
        node-config keysight_ixia-c-one
        node-config checkpoint_cloudguard
        node-config ext-container
        node-config cisco_xrd
        node-config rare
        node-config cisco_8000
        node-config cisco_c8000v
        node-config cumulus_cvx
        node-config openbsd
        node-config freebsd
        node-config huawei_vrp
        node-config generic_vm
        node-config fdio_vpp
}
note top: topology kinds configuration container

 

class "**node-config**" as node-config {
        StringType type
}
note top: topology node configuration container

 

class "ContainerlabTopologyDefinitionFileSettings" as ContainerlabTopologyDefinitionFileSettings {
        certificate-authority-config certificate-authority
}
note top: Global containerlab settings

 

class "**certificate-authority-config**" as certificate-authority-config {
        StringType cert
        StringType key
        IntegerType key-size
        StringType validity-duration
}
note top: Certificate Authority

 

class "**link-config-short**" as link-config-short {
        StringType[] endpoints
        mtu mtu
        link-vars vars
}
note top: link configuration container

 

class "**link-vars**" as link-vars {
}
note top: link-scoped variables used by config\nengine

 

class "**link-type-veth**" as link-type-veth {
        StringType type
        link-endpoint[] endpoints
        mtu mtu
        link-vars vars
        labels labels
}
note top: Link definition to support the\nveth interfaces

 

class "**link-endpoint**" as link-endpoint {
        StringType node
        StringType interface
        StringType mac
}
note top: Common link endpoint object for\nextended link configs

 

class "**labels**" as labels {
}
note top: container labels

 

class "**link-type-mgmt-net**" as link-type-mgmt-net {
        StringType type
        link-endpoint endpoint
        link-host-interface host-interface
        mtu mtu
        link-vars vars
        labels labels
}
note top: Link definition for management network\ninterfaces

 

class "**link-host-interface**" as link-host-interface {
}
note top: link-scoped variables used by config\nengine

 

class "**link-type-macvlan**" as link-type-macvlan {
        StringType type
        link-endpoint endpoint
        mtu host-interface
        mtu mtu
        link-vars vars
        labels labels
}
note top: Link definition describing a macvlan\nlink endpoint configuration

 

class "**link-type-host**" as link-type-host {
        StringType type
        link-endpoint endpoint
        link-host-interface host-interface
        mtu mtu
        link-vars vars
        labels labels
}
note top: 

 

class "**link-type-vxlan**" as link-type-vxlan {
        StringType type
        link-endpoint endpoint
        link-vxlan-remote remote
        link-vxlan-vni vni
        link-vxlan-udpport udp-port
        mtu mtu
        link-vars vars
        labels labels
}
note top: 

 

class "**link-vxlan-remote**" as link-vxlan-remote {
}

 

class "**link-vxlan-vni**" as link-vxlan-vni {
}
note top: VXLAN VNI

 

class "**link-vxlan-udpport**" as link-vxlan-udpport {
}
note top: Remote UDP port

 

class "**link-type-vxlan-stitched**" as link-type-vxlan-stitched {
        StringType type
        link-endpoint endpoint
        link-vxlan-remote remote
        link-vxlan-vni vni
        link-vxlan-udpport udp-port
        mtu mtu
        link-vars vars
        labels labels
}
note top: 

 

class "**link-type-dummy**" as link-type-dummy {
        StringType type
        link-endpoint endpoint
        mtu mtu
        link-vars vars
        labels labels
}
note top: 

 

class "**extras-config**" as extras-config {
        StringType[] srl-agents
        StringType mysocket-proxy
}
note top: node's extra configurations

 

class "**config-config**" as config-config {
        ObjectType vars
}
note top: containerlab config engine parameters

 

class "**certificate-config**" as certificate-config {
        BooleanType issue
        StringType[] sans
        IntegerType key-size
        StringType validity-duration
}
note top: Node's Certificate configuration option

 

class "**healthcheck-config**" as healthcheck-config {
        StringType[] test
        IntegerType interval
        IntegerType retries
        IntegerType timeout
        IntegerType start-period
}
note top: Node's Healthcheck configuration option

 

class "**dns-config**" as dns-config {
        StringType[] servers
        StringType[] search
        StringType[] options
}
note top: Node's DNS configuration option

 

class "**stages-config**" as stages-config {
        Stages-configCreate create
        Stages-configCreate-links create-links
        Stages-configConfigure configure
        Stages-configHealthy healthy
        Stages-configExit exit
}
note top: node's stages configurations

 

class "Stages-configCreate" as Stages-configCreate {
        Wait-for-configInner[] wait-for
        stage-exec exec
}
note top: create stage configuration

 

class "**wait-for-config**" as wait-for-config extends List {
}

class "**stage-exec**" as stage-exec {
}
note top: per-stage exec configuration

 

class "Stages-configCreate-links" as Stages-configCreate-links {
        Wait-for-configInner[] wait-for
        stage-exec exec
}
note top: create stage configuration

 

class "Stages-configConfigure" as Stages-configConfigure {
        Wait-for-configInner[] wait-for
        stage-exec exec
}
note top: create stage configuration

 

class "Stages-configHealthy" as Stages-configHealthy {
        Wait-for-configInner[] wait-for
        stage-exec exec
}
note top: create stage configuration

 

class "Stages-configExit" as Stages-configExit {
        Wait-for-configInner[] wait-for
        stage-exec exec
}
note top: create stage configuration

 

class "Wait-for-configInner" as Wait-for-configInner {
        StringType node
        StringType stage
}

 

enum "Stages-enum" as Stages-enum {
    CREATE
    CREATE_LINKS
    CONFIGURE
    HEALTHY
    EXIT
}

class "**stage-exec-list**" as stage-exec-list extends List {
}

class "**ipv6-addr**" as ipv6-addr {
}
note top: IPv6 address

 


    


ContainerlabTopologyDefinitionFile  *--  ContainerlabTopologyDefinitionFileMgmt

ContainerlabTopologyDefinitionFile  *--  ContainerlabTopologyDefinitionFileTopology

ContainerlabTopologyDefinitionFile  *--  ContainerlabTopologyDefinitionFileSettings

    




ContainerlabTopologyDefinitionFileMgmt  *--  ipv4-addr




ContainerlabTopologyDefinitionFileMgmt  *--  mtu

    
    
    

ContainerlabTopologyDefinitionFileTopology  *--  ContainerlabTopologyDefinitionFileTopologyKinds

ContainerlabTopologyDefinitionFileTopology  *--  node-config

    
ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

ContainerlabTopologyDefinitionFileTopologyKinds  *--  node-config

    

    
ContainerlabTopologyDefinitionFileSettings  *--  certificate-authority-config

    




    

link-config-short  *--  mtu

link-config-short  *--  link-vars

    
    

link-type-veth "0" *-- "n" link-endpoint

link-type-veth  *--  mtu

link-type-veth  *--  link-vars

link-type-veth  *--  labels

    



    
    

link-type-mgmt-net  *--  link-endpoint

link-type-mgmt-net  *--  link-host-interface

link-type-mgmt-net  *--  mtu

link-type-mgmt-net  *--  link-vars

link-type-mgmt-net  *--  labels

    
    

link-type-macvlan  *--  link-endpoint

link-type-macvlan  *--  mtu

link-type-macvlan  *--  mtu

link-type-macvlan  *--  link-vars

link-type-macvlan  *--  labels

    

link-type-host  *--  link-endpoint

link-type-host  *--  link-host-interface

link-type-host  *--  mtu

link-type-host  *--  link-vars

link-type-host  *--  labels

    

link-type-vxlan  *--  link-endpoint

link-type-vxlan  *--  link-vxlan-remote

link-type-vxlan  *--  link-vxlan-vni

link-type-vxlan  *--  link-vxlan-udpport

link-type-vxlan  *--  mtu

link-type-vxlan  *--  link-vars

link-type-vxlan  *--  labels

    
    
    
    

link-type-vxlan-stitched  *--  link-endpoint

link-type-vxlan-stitched  *--  link-vxlan-remote

link-type-vxlan-stitched  *--  link-vxlan-vni

link-type-vxlan-stitched  *--  link-vxlan-udpport

link-type-vxlan-stitched  *--  mtu

link-type-vxlan-stitched  *--  link-vars

link-type-vxlan-stitched  *--  labels

    

link-type-dummy  *--  link-endpoint

link-type-dummy  *--  mtu

link-type-dummy  *--  link-vars

link-type-dummy  *--  labels

    


    

    




    





    



    
stages-config  *--  Stages-configCreate

stages-config  *--  Stages-configCreate-links

stages-config  *--  Stages-configConfigure

stages-config  *--  Stages-configHealthy

stages-config  *--  Stages-configExit

    
Stages-configCreate "0" *-- "n" Wait-for-configInner

Stages-configCreate  *--  stage-exec

    
    
    
Stages-configCreate-links "0" *-- "n" Wait-for-configInner

Stages-configCreate-links  *--  stage-exec

    
Stages-configConfigure "0" *-- "n" Wait-for-configInner

Stages-configConfigure  *--  stage-exec

    
Stages-configHealthy "0" *-- "n" Wait-for-configInner

Stages-configHealthy  *--  stage-exec

    
Stages-configExit "0" *-- "n" Wait-for-configInner

Stages-configExit  *--  stage-exec

    


    
    
    

footer \ngenerated with yacg (https://github.com/OkieOth/yacg),\n(template: plantUml.mako v1.1.0)\npowered by plantuml (https://plantuml.com/)
@enduml