
@startuml
hide empty methods
hide empty fields

/'
 ' class "**Ipv6Addr**" as Ipv6Addr {}
 ' class "**Ipv4Addr**" as Ipv4Addr {}
 ' class "**MTU**" as MTU {}
 ' class "**LinkVars**" as LinkVars {}
 '/

class "**LinkConfigShort**" as LinkConfigShort {
        StringType[] **endpoints**
        MTU **mtu**
        LinkVars **vars**
}


class "**LinkTypeVeth**" as LinkTypeVeth {
        StringType **type**
        LinkEndpoint[] **endpoints**
        MTU **mtu**
        LinkVars **vars**
        Labels **labels**
}

class "**LinkEndpoint**" as LinkEndpoint {
        StringType **node**
        StringType **interface**
        StringType **mac**
}

class "**Labels**" as Labels {}

class "**LinkTypeMgmtNet**" as LinkTypeMgmtNet {
        StringType **type**
        LinkEndpoint **endpoint**
        LinkHostInterface **host-interface**
        MTU **mtu**
        LinkVars **vars**
        Labels **labels**
}

class "**LinkHostInterface**" as LinkHostInterface {}

class "**LinkTypeMacvlan**" as LinkTypeMacvlan {
        StringType **type**
        LinkEndpoint **endpoint**
        LinkHostInterface **host-interface**
        MTU **mtu**
        LinkVars **vars**
        Labels **labels**
}

class "**LinkTypeHost**" as LinkTypeHost {
        StringType **type**
        LinkEndpoint **endpoint**
        LinkHostInterface **host-interface**
        MTU **mtu**
        LinkVars **vars**
        Labels **labels**
}

class "**LinkTypeVxlan**" as LinkTypeVxlan {
        StringType **type**
        LinkEndpoint **endpoint**
        LinkVxlanRemote **remote**
        LinkVxlanVni **vni**
        LinkVxlanUdpPort **udp-port**
        MTU **mtu**
        LinkVars **vars**
        Labels **labels**
}

class "**LinkVxlanRemote**" as LinkVxlanRemote {}

class "**LinkVxlanVni**" as LinkVxlanVni {}

class "**LinkVxlanUdpPort**" as LinkVxlanUdpPort {}

class "**LinkTypeVxlanStitched**" as LinkTypeVxlanStitched {
        StringType **type**
        LinkEndpoint **endpoint**
        LinkVxlanRemote **remote**
        LinkVxlanVni **vni**
        LinkVxlanUdpPort **udp-port**
        MTU **mtu**
        LinkVars **vars**
        Labels **labels**
}

class "**LinkTypeDummy**" as LinkTypeDummy {
        StringType **type**
        LinkEndpoint **endpoint**
        MTU **mtu**
        LinkVars **vars**
        Labels **labels**
}

/' LinkConfigShort  *-- MTU '/
/' LinkConfigShort  *--  LinkVars '/

LinkTypeVeth "0" *-- "n" LinkEndpoint
/' LinkTypeVeth  *-- MTU '/
/' LinkTypeVeth  *--  LinkVars '/
/' LinkTypeVeth  *--  Labels '/

LinkTypeMgmtNet  *--  LinkEndpoint
LinkTypeMgmtNet  *--  LinkHostInterface
/' LinkTypeMgmtNet  *-- MTU '/
/' LinkTypeMgmtNet  *--  LinkVars '/
/' LinkTypeMgmtNet  *--  Labels '/

LinkTypeMacvlan  *--  LinkEndpoint
/' LinkTypeMacvlan  *-- MTU '/
/' LinkTypeMacvlan  *--  LinkVars '/
/' LinkTypeMacvlan  *--  Labels '/

LinkTypeHost  *--  LinkEndpoint
LinkTypeHost  *--  LinkHostInterface
/' LinkTypeHost  *-- MTU '/
/' LinkTypeHost  *--  LinkVars '/
/' LinkTypeHost  *--  Labels '/

LinkTypeVxlan  *--  LinkEndpoint
LinkTypeVxlan  *--  LinkVxlanRemote
LinkTypeVxlan  *--  LinkVxlanVni
LinkTypeVxlan  *--  LinkVxlanUdpPort
LinkTypeVxlan  *-- MTU
/' LinkTypeVxlan  *--  LinkVars '/
/' LinkTypeVxlan  *--  Labels '/

LinkTypeVxlanStitched  *--  LinkEndpoint
LinkTypeVxlanStitched  *--  LinkVxlanRemote
LinkTypeVxlanStitched  *--  LinkVxlanVni
LinkTypeVxlanStitched  *--  LinkVxlanUdpPort
LinkTypeVxlanStitched  *-- MTU
/' LinkTypeVxlanStitched  *--  LinkVars '/
/' LinkTypeVxlanStitched  *--  Labels '/

LinkTypeDummy  *--  LinkEndpoint
/' LinkTypeDummy  *-- MTU '/
/' LinkTypeDummy  *--  LinkVars '/
/' LinkTypeDummy  *--  Labels '/

footer \ngenerated with yacg (https://github.com/OkieOth/yacg),\n(template: plantUml.mako v1.1.0)\npowered by plantuml (https://plantuml.com/)
@enduml
